### ISSUE TITLE
TODO: add tests for PHP 5.6+ support

### ISSUE THREAD

**Issue by TylerBarnes** [wp-graphql/wp-graphql#1002]
There used to be tests for PHP 5.6 and up but they were removed. Since we support 5.6+ for now we should write tests for this.

**Comment by TylerBarnes** [comment]
This will help with https://github.com/wp-graphql/wp-graphql/issues/865

**Comment by kidunot89** [comment]
This needs a bit more discussion. The [code](https://github.com/wp-graphql/wp-graphql/blob/develop/src/Data/Connection/AbstractConnectionResolver.php#L201) specifically isn't compatible with PHP 5.6.

**Comment by TylerBarnes** [comment]
I believe @jasonbahl wanted to commit to keeping support in line with WP. Maybe we could do it as TDD, write the tests and then change incompatible code until the tests pass.

**Comment by jasonbahl** [comment]
Closing as we are going to support 7.0+
