### ISSUE TITLE
Add `resolve_node` helper methods

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#1019]
(originated here: https://github.com/wp-graphql/wp-graphql/pull/1005#issuecomment-553161908)

----

## Problem

Adding Types that implement the `node` interface is easy, but the `RootQuery.node` field doesn't have an easy way to resolve nodes of _all_ Types that implement said interface. 

## Solution

We should add a way for Types to easily declare their `resolve_node` method so that when adding new Types to the registry which implement the `node` interface, we can register _how_ they should resolve an individual node, and that will allow the `RootQuery.node` field to always be kept up to date and functioning, as each Type that implements the `Node` interface will control it's resolver for the node field. 

The `resolve_node` can also be used for connections to that Type, in place of the (currently) manually defined `resolveNode` field when registering connections.

**Comment by kidunot89** [comment]
I'm highly interested in this issue. WooGraphQL and few more extension I maintain design acutely to work with the current design. If it'll help lessen the breaks here are the `graphql_resolve_node*` callbacks for WooGraphQL. 
WooGraphQL's `graphql_resolve_node` [callback](https://github.com/wp-graphql/wp-graphql-woocommerce/blob/develop/includes/data/class-factory.php#L208-#L229)
WooGraphQL's `graphql_resolve_node_type` [callback](https://github.com/wp-graphql/wp-graphql-woocommerce/blob/develop/includes/data/class-factory.php#L239-#L277)

**Comment by jasonbahl** [comment]
@kidunot89 with improvements to the loaders, and the introduction of the `$loader->load_deferred()` method, and the cleanup of the DataSource file to use it, I’m not sure I feel there’s as much need for this. 

I think we can now use the loaders passed through context to load deferred nodes pretty easily. 

Marking this as a close candidate, but if you have further ideas to consider let me know.

**Comment by jasonbahl** [comment]
Closing this as I believe the loaders passed down in `$context` help here. 

`$context->get_loader( 'post' )->load_deferred( $id );` allows developers to take advantage of deferred loading of nodes in their resolvers.
