### ISSUE TITLE
Registering fields on Interfaces and Types can throw duplicate field errors and prevent the Schema from generating

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#1020]
See: https://github.com/wp-graphql/wp-graphql-woocommerce/issues/169

**Comment by jasonbahl** [comment]
Ok, so I did some more digging. 

This is actually _not_ an issue with Interfaces, but an issue with `register_graphql_connection`.

As it stands, you can register multiple graphql connections with the same `fromFieldName` and there's no warning/error. 

For example:

```
register_graphql_interface_type( 'TesterInterface', [
		'fields' => [
			'test' => [
				'type' => 'String',
			],
		],
	] );

	register_graphql_type( 'TesterType', [
		'interfaces' => [ 'TesterInterface' ],
		'fields' => [
			'test' => [
				'type' => 'Int',
			],
		],
	]);

	register_graphql_field( 'RootQuery', 'tester', [
		'type' => 'TesterType'
	] );

	register_graphql_connection([
		'fromType' => 'RootQuery',
		'toType' => 'TesterType',
		'fromFieldName' => 'testerConnection'
	]);

	register_graphql_connection([
		'fromType' => 'RootQuery',
		'toType' => 'TesterInterface',
		'fromFieldName' => 'testerConnection'
	]);
```

This just fails because we are trying to register `RootQuery.testerConnection` twice. 

So, we need to check if `${FromType}.{fromFieldName}` is an existing field before registering the connection.

**Comment by jasonbahl** [comment]
Ok, so looking into this more, I think this is actually the behavior we DO want. 

Right here we throw an error if a duplicate field is registered, but only if GRAPHQL_DEBUG is enabled. 

This allows developers to know _why_ their Schema isn't generating as expected, and I think that's what we _want_. 

If you were to register `RootQuery.testerConnection` multiple times, you, the developer would want to know why that's invalid. 

I'm closing this as I believe this is working as intended. 

@kidunot89 @Nessario, thoughts?

**Comment by Nessario** [comment]
By disabling the `GRAPHQL_DEBUG`, fixed my issue as well.

I think it's all good too!
