### ISSUE TITLE
`GRAPHQL_REQUEST` should be dynamic

### ISSUE THREAD

**Issue by esamattis** [wp-graphql/wp-graphql#1024]
Opening new issue from https://github.com/wp-graphql/wp-graphql/issues/1021#issuecomment-555159476

There are multiple places where wp-graphql specific filters are active when the `GRAPHQL_REQUEST` is set to true.

For example in Config.php:

https://github.com/wp-graphql/wp-graphql/blob/4855753012815b13b4eb002e22d6ad407703ebfc/src/Data/Config.php#L250

https://github.com/wp-graphql/wp-graphql/blob/4855753012815b13b4eb002e22d6ad407703ebfc/src/Data/Config.php#L298

https://github.com/wp-graphql/wp-graphql/blob/4855753012815b13b4eb002e22d6ad407703ebfc/src/Data/Config.php#L223

https://github.com/wp-graphql/wp-graphql/blob/4855753012815b13b4eb002e22d6ad407703ebfc/src/Data/Config.php#L198

https://github.com/wp-graphql/wp-graphql/blob/4855753012815b13b4eb002e22d6ad407703ebfc/src/Data/Config.php#L179

https://github.com/wp-graphql/wp-graphql/blob/4855753012815b13b4eb002e22d6ad407703ebfc/src/Data/Config.php#L155

So when you do a graphql request from PHP using `graphql()` the constant `GRAPHQL_REQUEST` gets set to true and there for those filters are active even after the `graphql()` call which will break or change some normal WordPress functionality. 

`GRAPHQL_REQUEST` needs to be changed to something that can be set to false once graphql request has completed. Maybe `\WPGraphQL::is_graphql_http_request()` and `\WPGraphQL::is_graphql_request()`?

**Comment by CodeProKid** [comment]
This probably needs to happen in a second constant, or some other global context. I'm not a big fan of constants containing dynamic data, and we need a single flag to indicate _any_ GraphQL request for people wanting to modify schema or anything else for any GraphQL request.

**Comment by jasonbahl** [comment]
Well, let's say, for some strange reason, you have something like this in your template file:

```
$a = graphql([ 'query' => '{posts{nodes{id,title}}}']);
$b = do_rest_request( '/wp/v2/posts' );
$c = graphql([ 'query' => '{posts{nodes{id,title}}}']);
```

Currently, `GRAPHQL_REQUEST` would be true after the first call, and would remain true even for the call to `do_rest_request`, which hypothetically could cause filters to execute against things like WP_Query which try to limit to only filtering during GraphQL Requests. 

Ideally, once the WPGraphQL Request is over, it should be reset to false, so filters on things like WP_Query could be ignored knowing it's no longer a GRAPHQL_REQUEST, but then for the second `graphql()` call, it would be true again.
