### ISSUE TITLE
Adding `isFrontPage` boolean to Pages data #5

### ISSUE THREAD

**Issue by zgordon** [wp-graphql/wp-graphql#1028]
It would be helpful to know if a page is assigned as the static homepage from WordPress. If we could expose this then we could tell when calling createPage() when to reassign the URI from the slug in WordPress to `/` so it loads as the homepage in Gatsby automatically as well.  This would allow someone to use WordPress menus to dynamically control the Gatsby homepage more easily.

**Comment by jasonbahl** [comment]
closed by #1029  and #1031
