### ISSUE TITLE
WPGraphQL should call `html_entity_decode()` for all content fields

### ISSUE THREAD

**Issue by esamattis** [wp-graphql/wp-graphql#1035]
By default WordPress encodes HTML entities before they are saved to database. This can be convinient when templating HTML strings in PHP because developers don't have to think about it.

But with WPGraphQL this is a burden when content is rendered via React or any other modern tool that has HTML entity encoding build-in because you'll get double html entity encoding.

There are tools that allow HTML entity decoding in JS but they neither intentionally incomplete like [unescape][] in Lodash or too large like [he][] or [ent][] to be bundled into the browser bundles. But even if we had good tools to do it, it is very cumbersome because developers would have to remember to use them basically every single time when content is being rendered from WP. This is a common issue we have faced when building real world headless sites and apps using React and React Native with WPGraphQL.

So we end up building HTML entity decoding as WPGrapQL filters on the PHP side:
https://gist.github.com/esamattis/54abd801b078056f9e646d63d47ccc4c

I believe tools like React are the major consumers of WPGraphQL and so **I would like to propose that WPGraphQL would add build-in HTML entity decoding** for the content fields.

By content fields I mean text content which is added by the content creators. Such are title, post content, excerpts, ACF text fields etc. Examples of non-content fields would be url, slugs, id where decoding could break something if they where to contain strings that match HTML entities.

[unescape]: https://lodash.com/docs/4.17.11#unescape
[he]: https://bundlephobia.com/result?p=he@1.2.0
[ent]: https://bundlephobia.com/result?p=ent@2.2.0

**Comment by CodeProKid** [comment]
I think this would be a positive change, we'll have to think about the implementation a bit though, would it make sense to add another format arg to the enum like `ENCODED`, or should we just do this for _all_ text fields.

**Comment by esamattis** [comment]
> would it make sense to add another format arg to the enum like `ENCODED`

Maybe to disable the decoding. If this were opt-in it would be too easy for developers to forget to use it because you'll see the mistake only after when content with encodable characters get first inserted. It's awkward to get these issue reports multiple times from clients. Talking from experience 😬 

> or should we just do this for all text fields

I don't think it would be safe. Even if it would in the context of wp-graphql core we cannot know what wp-graphql extension developers are doing. Somebody might even add field that just returns list of HTML encoded entities and that would break it 🤷‍♂ 😂 

So I think we have to specifically target the fields we need.

**Comment by drewbaker** [comment]
Yes, this is something we have run into with Nuxt and our WordPress boilerplate. We solved it by having a `wp-content` component on the frontend that sanitizes and decodes HTML, and it does some cool stuff to handle shortcodes too. Check it here: https://github.com/funkhaus/haus-components/blob/master/WpContent.vue. 

This is also an issue with any `title` that comes out of WP-GQL too. In Vue/Nuxt we use `v-html=""` to display that, but it's annoying and doesn't feel very modern for WP-GQL to be outputting encoded HTML always.

I think disabling encoding all around, and then having some filters like `content(filter: ENCODED)` to opt into it is the way to go. Developers "forgetting" isn't really WP-GQL's problem is it? Can't that just be solved with good docs?

**Comment by esamattis** [comment]
> Developers "forgetting" isn't really WP-GQL's problem is it? 

I personally believe it is. Frameworks are supposed to help developers to succeed and I think this is a clear win for devs. I cannot see any real downsides if we do this. One could argue that it makes harder to use the `graphql()` function from PHP templates but we can actually detect that and disable the decoding in that case automatically if needed.

> Can't that just be solved with good docs?

Consider escaping of user generated content in PHP templates. It is really well documented and there is even a linter to enforce it and yet we see constantly new XSS vulnerabilies in WP plugins. I'd argue that's because WP (or actually PHP) doesn't do it automatically. This is of course not that critical but that's my point actually: Nobody's gonna do it right if it's not critical for security and is just cumbersome. So it's gonna get forgotten unless it's automatic.

**Comment by izzygld** [comment]
couldnt help notice we do [currently](https://github.com/wp-graphql/wp-graphql/blob/master/src/Type/Enum/PostObjectFieldFormatEnum.php) have a `PostObjectFieldFormatEnum` on  The format of post field data.

`RAW`
Provide the field value directly from database

`RENDERED`
Apply the default WordPress rendering

Perhaps we can have one more called:  `ENCODE`

**Comment by jasonbahl** [comment]
Related: #1034

**Comment by PTiCA1** [comment]
I have the same problem. I use Nuxt.js and html entities are displaying poorly. I'd like to use 'title (format: RAW)' but return null. Didn't someone solve the same problem?

![GraphQL format:raw return null](https://i.imgur.com/eIhhjEgl.png)

**Comment by esamattis** [comment]
@PTiCA1 Did you try my gist? gist.github.com/esamattis/54abd801b078056f9e646d63d47ccc4c

**Comment by jonshipman** [comment]
> I have the same problem. I use Nuxt.js and html entities are displaying poorly. I'd like to use 'title (format: RAW)' but return null. Didn't someone solve the same problem?
> 
> ![GraphQL format:raw return null](https://camo.githubusercontent.com/7ee4c38ace5f07263e7e7e90aca0a2b5958ded64/68747470733a2f2f692e696d6775722e636f6d2f654968686a45676c2e706e67)

To retrieve the RAW content, the current user needs to have the edit_posts cap

![image](https://user-images.githubusercontent.com/12699954/79597989-d08d3e80-80a8-11ea-9e52-484e8cfb2913.png)

**Comment by wmtmartinez** [comment]
@jonshipman did you solved the issue? i have the same problem in react, how can i solve that?
Thank you

**Comment by jonshipman** [comment]
@wmtmartinez You can use esamattis's solution here https://gist.github.com/esamattis/54abd801b078056f9e646d63d47ccc4c for the decoding.

If you're talking about accessing the raw unfiltered content, best (at the moment) to add your own fields like so:
```
add_action(
    'graphql_register_types',
    function () {
        $name   = 'rawPostTitle';
        $config = array(
            'type'        => 'String',
            'description' => __( 'Returns the raw, unfiltered title as god intended', 'ploogin' ),
            'resolve'     => function ( $post ) {
                return $post->post_title;
            },
        );

        register_graphql_field( 'Page', $name, $config );
        register_graphql_field( 'Post', $name, $config );
    }
);
```

**Comment by wmtmartinez** [comment]
@jonshipman thank you so much for your answer, but i'm really new to wordpress and i don't really know how or where to add that esamattis's code.
If you may give some guide or help about it i would appreciate it.
Thank you so much

**Comment by esamattis** [comment]
There's usage info in the gist comments.

**Comment by jasonbahl** [comment]
@jonshipman @wmtmartinez This PR (#1337) addresses this issue by applying `html_entity_decode()` to post content and titles and term names and descriptions.

Would be good to get some folks testing that. 

Some examples: 

## Querying Posts:

**Before:**
![Screen Shot 2020-06-03 at 10 58 11 AM](https://user-images.githubusercontent.com/1260765/83665837-3b2b0880-a589-11ea-83d1-475bfdcc2683.png)

**After:**
![Screen Shot 2020-06-03 at 10 57 16 AM](https://user-images.githubusercontent.com/1260765/83665834-39f9db80-a589-11ea-8df8-b7f71b8c9ee5.png)

## Querying a Category

**Before:**
![Screen Shot 2020-06-03 at 10 58 11 AM](https://user-images.githubusercontent.com/1260765/83666061-95c46480-a589-11ea-86a0-d0985b8ca7a4.png)

**After:**
![Screen Shot 2020-06-03 at 10 57 16 AM](https://user-images.githubusercontent.com/1260765/83666056-94933780-a589-11ea-93a2-e98bac5c4617.png)

**Comment by jasonbahl** [comment]
(^ accidentally used the same screenshots for both examples, updated with correct ones)

**Comment by drewbaker** [comment]
@jonshipman If you're using Nuxt, then our boilerplate and theme combo might help you a lot:
https://github.com/funkhaus/fuxt
https://github.com/funkhaus/fuxt-backend

Also, in Vue/Nuxt, you can use `v-html` to display raw HTML, like this:`<h2 v-html="page.title"/>`.

**Comment by jonshipman** [comment]
@drewbaker Thanks, I'm more of a React/Apollo combo-er.

Here's the boilerplate I am messing around with: https://github.com/jonshipman/headless-wp-starter

@jasonbahl Thanks, working on a project today. Will try merging the PR and let you know if any bugs scare me.

**Comment by drewbaker** [comment]
By applying `html_entity_decode` to the entire `post_content` I've found oembeds or data attributes with escaped encoded JSON in them will cause node-mismatch errors on assembly in Vue.

For example, now that we `html_entity_decode` everything, this YouTube video will create an oEmbed like this:

https://www.youtube.com/watch?v=9tpBc8kmuJY

Becomes:
```
<iframe title="Honda "Paper" - Behind the Scenes with PES" width="500" height="281" src="https://www.youtube.com/embed/9tpBc8kmuJY?feature=oembed" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```

And you'll notice the title attribute will now break everything on the page.

It's especially bad with a shortcode that does something like this (to feed props into a Vue component):

```
		return "<shortcode-gallery class='shortcode' :columns='". esc_attr($columns) ."' :images='". esc_attr($images) ."'>".$content."</shortcode-gallery>";
```

The `html_entity_decode` will decode the JSON and break everything. 

We need a smarter way to handle the decoding I think. Because we totally would need encoded attributes for HTML elements right? Or am I missing something?

Perhaps a good solve is to have an easy way to make our own `FORMAT` filters? Then we could do `content(FORMAT: ESCAPED)` ?

**Comment by drewbaker** [comment]
For future reference, changing this:
```
// https://github.com/wp-graphql/wp-graphql/blob/develop/src/Model/Post.php#L475-L479
				'contentRendered'           => function() {
					$content = ! empty( $this->data->post_content ) ? $this->data->post_content : null;

					return ! empty( $content ) ? html_entity_decode( apply_filters( 'the_content', $content ) ) : null;
				},
```

To:

```
				'contentRendered'           => function() {
					$content = ! empty( $this->data->post_content ) ? $this->data->post_content : null;

					return ! empty( $content ) ?  apply_filters( 'the_content', $content ) : null;
				},
```

Fixes a lot of issues for me with omebeds and shortcodes.

**Comment by jasonbahl** [comment]
> Perhaps a good solve is to have an easy way to make our own FORMAT filters? Then we could do content(FORMAT: ESCAPED) ?

@drewbaker One thing you can do _now_ without needing to worry about format filters is adding a new field. Let's say `Post.unencodedContent`. 

```php
add_action( 'graphql_register_types', function() {
  register_graphql_field( 'Post', 'unencodedContent', [
    'type' => 'String',
    'resolve' => function( $post ) {
       $content = get_post( $post->databaseId )->post_content;
       return ! empty( $content ) ?  apply_filters( 'the_content', $content ) : null;
    }
  ]);
});
```

![Screen Shot 2020-09-11 at 11 39 58 AM](https://user-images.githubusercontent.com/1260765/92956110-8de74c80-f423-11ea-963f-b27994f0f12d.png)

**Comment by drewbaker** [comment]
Thanks @jasonbahl for the quick response. Is there any easy way to do that across all post types?

```
add_action( 'graphql_register_types', function() {
  register_graphql_field( 'All', 'unencodedContent', [
    'type' => 'String',
    'resolve' => function( $post ) {
       $content = get_post( $post->databaseId )->post_content;
       return ! empty( $content ) ?  apply_filters( 'the_content', $content ) : null;
    }
  ]);
});
```

**Comment by jasonbahl** [comment]
@drewbaker oh ya, you could register it to the `NodeWithContentEditor` Interface and then the field will be available on all Types that implement `NodeWithContentEditor` (all post types that [support](https://developer.wordpress.org/reference/functions/post_type_supports/) the editor): 

```php
add_action( 'graphql_register_types', function() {
	register_graphql_field( 'NodeWithContentEditor', 'unencodedContent', [
		'type' => 'String',
		'resolve' => function( $post ) {
			$content = get_post( $post->databaseId )->post_content;
			return ! empty( $content ) ?  apply_filters( 'the_content', $content ) : null;
		}
	]);
});
```

**Comment by jasonbahl** [comment]
^ Interfaces are 🤩

**Comment by drewbaker** [comment]
Is it bad to just override the regular `content` field?

```
register_graphql_field( 'NodeWithContentEditor', 'content', [])
```
