### ISSUE TITLE
Docs: add search feature 🕵🏼‍♂️

### ISSUE THREAD

**Issue by jacobarriola** [wp-graphql/wp-graphql#1036]
The new documentation site does not have a search feature, which makes searching for answers a bit arduous. 

Happy to explore adding Algolia to the Gatsby site, since it looks like the theme has some configs for it.

Let me know if you'd like to me to kickoff a PR for this 👍

**Comment by jasonbahl** [comment]
@jacobarriola The plan is to have Algolia set up with DocSearch. I need to chat with Algolia to make that happen.

**Comment by jasonbahl** [comment]
@jacobarriola I've emailed Algolia about DocSearch.

**Comment by jacobarriola** [comment]
@jacobarriola cool. Let me know whether you need any help with the implementation.

**Comment by jasonbahl** [comment]
I've heard back from Algolia, so I'm going to look into setting this up here shortly.
