### ISSUE TITLE
sendPasswordResetMutation returns internal server error

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#1046]
When executing the `sendPasswordResetEmail` mutation as a non-authenticated user, an internal server error is returned. 

I believe there's an issue with the Model Layer and non-authenticated requests. 

We should: 

1) Move the shape of the response to: `user{ node { ...userFields } }` instead of just `user { ...userFields }` as that will allow for us to null the `node` field for when the user info is private without causing errors because the User.ID is null

2) provide additional fields in the Payload to allow users to query something else, like: 

```
mutation sendPasswordResetEmail( clientMuationId: "pw_reset" username:"jasonbahl" ) {
 success
}
```

where success is a Boolean

**Comment by jasonbahl** [comment]
@kellenmace did you fix this with your recent multisite PR?

**Comment by kellenmace** [comment]
@jasonbahl Good catch on this one. No, my recent multisite-related PR only affected the createUser mutation.

**Comment by jasonbahl** [comment]
Closing as I'm unable to reproduce this at this time.

**Comment by aresrioja10** [comment]
Hi @jasonbahl !

I'm getting this error with non-authenticated users. 

Did you find a solution?

**Comment by jasonbahl** [comment]
@aresrioja10 based on my last comment, it looks like the last time I tried to replicate, I was unable to

Could you maybe provide more information on what query you're running, what your expectation is for a response, what the underlying data in the database is, etc? 

This would all be helpful in replicating and identifying if there's a bug that needs to be squashed.

**Comment by aresrioja10** [comment]
I've changed this query:

```
mutation SendPasswordResetEmail($email: String!) {
  sendPasswordResetEmail(input: {username: $email}) {
    user {
      id
    }
  }
}
```

into this

```
mutation SendPasswordResetEmail($email: String!) {
  sendPasswordResetEmail(input: {username: $email}) {
    clientMutationId
  }
}
```

and now it works. Not sure what's happening

**Comment by jasonbahl** [comment]
Ok, I can try and debug with the first query and see if I can replicate again.
