### ISSUE TITLE
"Cannot return null for non-nullable field PostType.id."

### ISSUE THREAD

**Issue by TylerBarnes** [wp-graphql/wp-graphql#1047]
```
{
  users {
    nodes {
      revisions {
        postTypeInfo {
          id
        }
      }
    }
  }
}
```

When I run this query I get the error "Cannot return null for non-nullable field PostType.id.". Seems like this shouldn't be an error and should just return null. Also can Users be revised? 

This might be irrelevant once you rework revisions!

**Comment by TylerBarnes** [comment]
Ohh wait. This is for revisions that user created, I see!

**Comment by jasonbahl** [comment]
@TylerBarnes with the PR for #974 this `postTypeInfo` field will no longer be available on the `revisions` connections, as they will be a `ContentRevisionUnion` and not a specific PostType, so that field `postTypeInfo` will no longer exist at all.
