### ISSUE TITLE
"Connection between the User type and the User type"

### ISSUE THREAD

**Issue by TylerBarnes** [wp-graphql/wp-graphql#1048]
In this query, if I command click on revisions in Graphiql, I get the field description as "Connection between the User type and the User type". Shouldn't it be "Connection between the User type and the Revision type"?
```
{
  users {
    nodes {
      revisions {
        postTypeInfo {
          id
        }
      }
    }
  }
}

```

**Comment by jasonbahl** [comment]
This is addressed in the PR for #974 

The description for `User.revisions` is now `Connection between the User and Revisions authored by the user`
