### ISSUE TITLE
User role display names missing from schema

### ISSUE THREAD

**Issue by kellenmace** [wp-graphql/wp-graphql#1050]
Currently, in WPGraphQL 0.4.2, these fields are available when querying for user roles:
```
capabilities
id
isRestricted
name
```
There is no field for getting the display names for roles.
Also, the description for the `name` field says it is "The UI friendly name of the role", but that's not correct – it is the registered name for the role.

## Recommended changes
1. Add a `displayName` field to the schema that returns the role display name.
1. Update the `name` field description to "The registered name for the role".

**Comment by jasonbahl** [comment]
@kellenmace good call. fix coming.
