### ISSUE TITLE
Docs: demo code syntax error

### ISSUE THREAD

**Issue by mashirozx** [wp-graphql/wp-graphql#1057]
Remember, an issue is not the place to ask general questions. You can use [Slack](https://wp-graphql.slack.com) for that ([join here](https://wpgql-slack.herokuapp.com/)).

Before you open an issue, please check if a similar issue already exists or has been closed before.

### When reporting a _bug_, please be sure to include the following:
- [x] A descriptive title
- [ ] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)
- [x] What version of `WPGraphQL` you're using, and the platform(s) you're running it on
Version 0.4.1
- [x] What other plugins you're using
No one else
- [ ] The behavior you expect to see, and the actual behavior

### When you open an _issue_ for a feature request, please add as much detail as possible:
- [ ] A descriptive title
- [ ] A description of the problem you're trying to solve, including *why* you think this is a problem
- [ ] An overview of the suggested solution
- [ ] If the feature changes current behavior, reasons why your solution is better

Demo code in <https://github.com/wp-graphql/wp-graphql/blob/f6d8c59fcf2bffa88fb30e222cbe1802764273a2/docs/source/extending/types.mdx#union-types>

```php
'types'       => [
    \\WPGraphQL\\TypeRegistry::get_type( 'Dog' ),
    \\WPGraphQL\\TypeRegistry::get_type( 'Cat' )
  ],
```

> Parse error: syntax error, unexpected '/\' (T_NS_SEPARATOR), expecting identifier (T_STRING)

I just past these demo code in a WP theme's functions.php, aren't they using in this way?

**Comment by jasonbahl** [comment]
@mashirozx thanks for reporting. I've updated this piece of documentation here: https://github.com/wp-graphql/wp-graphql/commit/c5c5dcc07ff9bff4080f631ad9d90d798968d75b
