### ISSUE TITLE
`postBy` and similar queries give an error when no post is found

### ISSUE THREAD

**Issue by mdrayer** [wp-graphql/wp-graphql#1059]
The `postBy` and similar queries throw an error when no post is found.

Example query:
```
{
  postBy(uri: "foo-bar") {
    id
    title
  }
}
```

Example response:
```
{
  "errors": [
    {
      "message": "No post exists with this id: ",
      "category": "user",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "postBy"
      ]
    }
  ],
  "data": {
    "postBy": null
  }
}
```

Since nothing really went wrong here, I would not expect an error to be thrown; just a `null` response in `data.postBy`. While the error message is helpful, it ultimately leads to promises being falsely rejected.

Tested with WPGraphQL version 0.4.2

**Comment by jasonbahl** [comment]
Ok, so when an individual resource cannot be found, it seems most APIs actually do return an error of some sort. 

For example, the WP REST API will return a 404 and the following message, if you try to hit an endpoint for a post that doesn't exist, such as `https://www.wpgraphql.com/wp-json/wp/v2/posts/3445456353`: 

```
{
  "code": "rest_post_invalid_id",
  "message": "Invalid post ID.",
  "data": {
    "status": 404
  }
}
```

The Github GraphQL API will also return an error if you try and fetch a resource that doesn't exist. 

For example (you can try this here: https://developer.github.com/v4/explorer/):

```
{
  repository(name: "does-not-exist" owner:"does-not-exist") {
    name
    id
  }
}
```

Returns: 

```
{
  "data": {
    "repository": null
  },
  "errors": [
    {
      "type": "NOT_FOUND",
      "path": [
        "repository"
      ],
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "message": "Could not resolve to a User with the username 'does-not-exist'."
    }
  ]
}
```

I was thinking about making a quick PR to address this and remove the error that is thrown, but it seems that the error is actually inline with common API practices. 

🤔

**Comment by mdrayer** [comment]
Ah, okay. I figured it would work like the `posts` query where it returns empty if nothing is found; but if `postBy` is already following common API practices, I should probably just use `posts` instead ;-)

**Comment by jasonbahl** [comment]
No direct answers in here, but helpful article about errors in GraphQL here for reference: https://itnext.io/the-definitive-guide-to-handling-graphql-errors-e0c58b52b5e1

**Comment by jasonbahl** [comment]
@mdrayer For consistency sake, I think I'll just remove the error to behave like `post` entry point. 

It's still a toss up what's best. Graph.Cool, for example returns null with no errors, and I do think it will alleviate some headaches if we do the same, and at minimum will lead to better consistency with our other single-node entry points. 

I'll PR it, and if we feel in the future that we have a _really_ good pattern for handling individual resource errors more consistently we can add it back and document it better.
