### ISSUE TITLE
bug: comment `hasNextPage` incorrect when `first` is null

### ISSUE THREAD

**Issue by mashirozx** [wp-graphql/wp-graphql#1062]
Remember, an issue is not the place to ask general questions. You can use [Slack](https://wp-graphql.slack.com) for that ([join here](https://wpgql-slack.herokuapp.com/)).

Before you open an issue, please check if a similar issue already exists or has been closed before.

### When reporting a _bug_, please be sure to include the following:
- [x] A descriptive title
- [x] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)
<https://dev.2heng.xin/graphql>

- [x] What version of `WPGraphQL` you're using, and the platform(s) you're running it on
Version 0.4.1

- [x] What other plugins you're using
No one else

- [x] The behavior you expect to see, and the actual behavior

The query:
```graphql
query GET_POST($postId: Int, $first: Int, $after: String) {
  postBy(postId: $postId) {
    comments(first: $first, after: $after) {
      edges {
        node {
          content
          children(first: $first, after: $after) {
            nodes {
              content
            }
            pageInfo {
              endCursor
              hasNextPage
              hasPreviousPage
              startCursor
            }
          }
        }
      }
      pageInfo {
        endCursor
        hasNextPage
        hasPreviousPage
        startCursor
      }
    }
  }
}
```

When I set `first: 10`:
```json
{
  "postId": 1,
  "first": 10,
  "after": null
}
```

It returns `hasNextPage: true` in both `comments` and `comments.children`:
```
"pageInfo": {
          "endCursor": "YXJyYXljb25uZWN0aW9uOjEy",
          "hasNextPage": true,
          "hasPreviousPage": false,
          "startCursor": "YXJyYXljb25uZWN0aW9uOjI2"
}
```

But When I set `first: null`:
```json
{
  "postId": 1,
  "first": null,
  "after": null
}
```

It returns `hasNextPage: false` in both `comments` and `comments.children`:
```
"pageInfo": {
          "endCursor": "YXJyYXljb25uZWN0aW9uOjEy",
          "hasNextPage": false,
          "hasPreviousPage": false,
          "startCursor": "YXJyYXljb25uZWN0aW9uOjI2"
 }
```

Actually the API seems to return the first 10 comments by default if `first` be null, so the `hasNextPage` field goes wrong.

**Comment by mashirozx** [comment]
By the way, how can I get all the comments at once (I don't know how many children under a comment)?

**Comment by mashirozx** [comment]
Looked the code, found that the default `query_amount` was 100, however, I only get 10 items from 17 items with `first=null` or unset as above.

https://github.com/wp-graphql/wp-graphql/blob/d9fb0b73f669ebba3762e89ff3df262cdc155fc3/src/Data/Connection/AbstractConnectionResolver.php#L146

**Comment by mashirozx** [comment]
https://github.com/wp-graphql/wp-graphql/blob/d9fb0b73f669ebba3762e89ff3df262cdc155fc3/src/Data/Connection/AbstractConnectionResolver.php#L402

I thinks this should not be `false` if we use the default value `$amount_requested ` in
https://github.com/wp-graphql/wp-graphql/blob/d9fb0b73f669ebba3762e89ff3df262cdc155fc3/src/Data/Connection/AbstractConnectionResolver.php#L322

**Comment by jasonbahl** [comment]
@mashirozx This behavior is not a bug. 

According the the Relay Specification for Connections ([https://facebook.github.io/relay/graphql/connections.htm#HasNextPage()](https://facebook.github.io/relay/graphql/connections.htm#HasNextPage())), `hasNextPage` should return `false` if neither `first` or `last` are set with a value.
