### ISSUE TITLE
bug: a bug on your website :)

### ISSUE THREAD

**Issue by mashirozx** [wp-graphql/wp-graphql#1063]
![image](https://user-images.githubusercontent.com/16148054/70376261-0b84a600-1942-11ea-8df3-287a8a44aae2.png)

**Comment by emaildano** [comment]
This is an easy fix, it's just a CSS index jawn.

```
.graphiql-wrapper {
    z-index: 0;
    position: relative;
}
```

![Screen Shot 2019-12-08 at 3 23 36 PM](https://user-images.githubusercontent.com/1872327/70395636-b6db3c80-19ce-11ea-8061-14e810acc173.png)

**Comment by jasonbahl** [comment]
@emaildano @mashirozx Thanks for reporting the issue and the solution. I've PR'd a fix. Should get deployed and live within a few moments. 

Thanks!
