### ISSUE TITLE
Feature Request: Query by offset of the content list

### ISSUE THREAD

**Issue by mashirozx** [wp-graphql/wp-graphql#1065]
### When you open an _issue_ for a feature request, please add as much detail as possible:
- [x] A descriptive title
- [x] A description of the problem you're trying to solve, including *why* you think this is a problem
- [ ] An overview of the suggested solution
- [ ] If the feature changes current behavior, reasons why your solution is better

I'm building a page navigation to the comment list of the post, just like `paginate_comments_links()` do:
![image](https://user-images.githubusercontent.com/16148054/70528945-598bea80-1b8a-11ea-913a-ca4d2158f48d.png)

So the `startCursor` and `endCursor` is useless here. What I hope, is to Query by `WP_Comment_Query`'s `$offset` parameter (however, not  `ArrayConnection::cursorToOffset`).

Actually, we may not need this extra query for commentID here:
https://github.com/wp-graphql/wp-graphql/blob/d840b2847dd99cc2323f26b02fb2d8adc7f0b443/src/Data/Config.php#L322

**Comment by esamattis** [comment]
@darylldoyle just released a plugin for this

https://github.com/darylldoyle/wp-graphql-offset-pagination

I don't think this needs to be in the core.

**Comment by darylldoyle** [comment]
@mashirozx the plugin I've released is only currently tested with version `0.3.8` of wp-graphql. That said, the core logic is there so it shouldn't take too much effort to get it working with the newer versions. Once we've upgraded our version internally, then I'll bring it up to date if no one has done so beforehand.

**Comment by mashirozx** [comment]
Thank you! @darylldoyle  @esamattis

**Comment by abumalick** [comment]
upgraded on https://github.com/valu-digital/wp-graphql-offset-pagination
