### ISSUE TITLE
Endpoint change to home_url in 0.5.1. (legitimately?) breaks bedrock-based installs

### ISSUE THREAD

**Issue by mlbrgl** [wp-graphql/wp-graphql#1087]
### When reporting a _bug_, please be sure to include the following:
- [x] A descriptive title
- [ ] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)
**--> Please let me know when and if this would be helpful and I'll create one**
- [x] What version of `WPGraphQL` you're using, and the platform(s) you're running it on
**WPGraphQL 0.5.1, Wordpress 5.3, Bedrock (https://roots.io/bedrock/), Nginx, Lando**
- [x] What other plugins you're using
```json
"require": {
    "php": ">=7.1",
    "composer/installers": "1.7",
    "oscarotero/env": "1.2.0",
    "roots/wordpress": "5.3",
    "roots/wp-config": "1.0.0",
    "roots/wp-password-bcrypt": "1.0.0",
    "vlucas/phpdotenv": "3.6.0",
    "wp-api/basic-auth": "dev-master",
    "wp-graphql/wp-graphql": "0.5.1",
    "wpackagist-plugin/add-category-to-pages": "1.2",
    "wpackagist-plugin/admin-starred-posts": "2.5",
    "wpackagist-plugin/broken-link-checker": "1.11.9",
    "wpackagist-plugin/co-authors-plus": "3.4",
    "wpackagist-plugin/image-cleanup": "1.9.2",
    "wpackagist-plugin/mailgun": "1.7.1",
    "wpackagist-plugin/my-default-post-content": "0.6.0",
    "wpackagist-plugin/post-types-order": "1.9.4.2",
    "wpackagist-plugin/public-post-preview": "2.9",
    "wpackagist-plugin/public-post-preview-configurator": "1.0.3",
    "wpackagist-plugin/redirection": "4.4.2",
    "wpackagist-plugin/regenerate-thumbnails": "3.1.2",
    "wpackagist-plugin/safe-svg": "1.9.6",
    "wpackagist-plugin/simple-embed-code": "2.3.2",
    "wpackagist-plugin/simple-history": "2.33",
    "wpackagist-plugin/tablepress": "1.10",
    "wpackagist-plugin/taxonomy-terms-order": "1.5.7.1"
  }
```
- [x] The behavior you expect to see, and the actual behavior
- Pre 0.5.1 behaviour: GraphQL endpoint exposed on mysite/graphql
- 0.5.1+: GraphQL endpoint is now exposed on mysite/wp/graphql

I understand the motivation behind 21c4275496feede65986a067cce3cd817cc5e68f, but on a typical Bedrock install:
- site_url = mysite/wp
- home_url = mysite

By shifting from home_url to site_url, this means that the GraphQL endpoint is now exposed on mysite/wp/graphql, when the REST API is still mysite/wp-json/wp (as opposed to mysite/wp/wp-json/wp). That discrepancy is confusing (and likely to trip WPGraphQL early-adopters and Bedrock users).

- this is properly documented for new comers (https://docs.wpgraphql.com/getting-started/install-and-activate/#verify-the-endpoint-works) but a breaking change item in the 0.5.1 release notes would be welcome
- should the REST API also be exposed on wp-prefixed paths (/wp/wp-json/wp/...)? This is most certainly a question for the Bedrocks folks but curious to hear some thoughts on this. Maybe @kidunot89?

**Comment by esamattis** [comment]
I think this was not intended? WPQL should be exposed like the rest api.

**Comment by kidunot89** [comment]
@mlbrgl My bad bro, I hadn't even factored REST into the equation when I made the change, and it was such small change I didn't think it would even be noticed :sweat_smile: .

And I think the REST endpoint should be exposed on the `site_url` for a couple of reasons.
 - **Consistency** this way going forward the `site_url` can be used to target all backend functionality and the `home_url` for frontend routes.
 - **Does REST even work with the `home_url`?** The reason for the change in WPGraphQL was because if the `Site Address` was changed to a new domain. When GraphQL request was made to a `home_url/graphql_endpoint`, `home_url` would return the URL in `Site Address`, resulting in a 404.

**Comment by mlbrgl** [comment]
Thanks for your insights, it's helpful to get other point of views. 

I agree, it would be helpful to have a clearer separation between the respective roles of site_url and home_url in that context, and not expect that they are somehow interchangeable. On the other hand, I wonder if people would not rely more on .env variables rather than a key in the WP DB for frontend use cases.

> Does WP-REST even work from home_url/wp-json if the Site Address has been changed?
I don't know for sure, I would need to test it.

**Comment by jasonbahl** [comment]
Ya, this is an interesting issue. 🤔 

One big reason for changing `site address` is that it generates internal links to that address. So, let's say you're using your WordPress site as a source for a headless application. Your WP install is at data.site.com and your headless application is at site.com

By changing the WordPress Address setting to `data.site.com` and your Site Address to `site.com` (where your headless application lives), links in pages and posts, etc will be generated with `site.com` and will work in your headless app (assuming your headless app routing matches WP routing)

This is a pretty common thing for folks to be doing when using WordPress as an API and another system as the presentation layer. 

I'm open to other ways of handling this, but I do think it's becoming more common to see the Site Address pointing to something that isn't even executing PHP, and thus the GraphQL endpoint couldn't be available on regardless. 

---

@mlbrgl I did update the release notes as well. Thanks for bringing this up

**Comment by mlbrgl** [comment]
@jasonbahl thanks for the thorough write-up!
