### ISSUE TITLE
Inputs that expect an ID, should all be of the ID Type and should accept the Integer or Relay ID

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#109]
In various Input args, we're currently setup to accept the WordPress ID as the input, but we should be accepting Global Relay IDs. 

For example, the `where` args for the `posts` query has an input of `authorIn` which accepts a list of Ints. . .this should accept a list of `ID`s and should parse out the WP ID from the Global ID.

Same goes for basically all inputs where the expected input is an ID

More examples, but not necessarily a comprehensive list

```
authorIn
authorNotIn
categoryAnd
categoryIn
in
notIn
parentIn
parentNotIn
tagAnd
tagIn
tagNotIn
```

**Comment by CodeProKid** [comment]
I will try to come up with a comprehensive list in #221

**Comment by jasonbahl** [comment]
related to #532

**Comment by hsimah** [comment]
I don't think we should necessarily stop accepting the database IDs as arguments. There are a lot of plugins out there which rely on linking to posts by their ID. For example I integrate with MB Relationships and FacetWP. I personally don't like the idea of using `atob` in my client to modify an ID returned from the server to request an item.

I do think that there is scope for both input types. Perhaps we could come up with a naming standard where `id` is the relay ID and `databaseId` (or similar) is the int value. It would mean duplicated fields, but would ensure flexibility for the end user.

**Comment by jasonbahl** [comment]
@hsimah ya, I _believe_ that if the Input type is ID that it can accept either an integer _or_ a String, so we can have the same input field accept either the database ID _or_ the Relay ID

Then let the execution handle what to do. 

Like, during execution, as we handle the input we can check something like the following (pseudo code): 

```
if ( is_int( $arg['inputId'] ) {
  $id = absint( $arg['inputId'] );
} else if ( is_relay_id( $args['inputId'] ) {
  $id = Relay::fromGlobalId()['id'];
} else {
  throw new UserError( 'The ID is invalid. . .' );
}
```

**Comment by jasonbahl** [comment]
related: #532 and #263

**Comment by jasonbahl** [comment]
Closing in favor of #997 and #998
