### ISSUE TITLE
Query MediaItem by sourceUrl

### ISSUE THREAD

**Issue by TylerBarnes** [wp-graphql/wp-graphql#1091]
This would be useful for pulling info about images in post_content or other html fields where only the attachment URL is available.

**Comment by TylerBarnes** [comment]
Looks like there's a core function that does this https://developer.wordpress.org/reference/functions/attachment_url_to_postid/

**Comment by jasonbahl** [comment]
@TylerBarnes I've got this working in the v0.6.0 release. 

See it in action: 

Here I query to get a media item. I then copy the `sourceUrl` for use as input in the next query.

![Screen Shot 2020-01-13 at 10 33 19 PM](https://user-images.githubusercontent.com/1260765/72316993-1cb58680-3655-11ea-90cf-65f24fc9064a.png)

I then use the sourceUrl as the input for the next query, asking for a mediaItem and setting the idType to `SOURCE_URL`

![Screen Shot 2020-01-13 at 10 35 32 PM](https://user-images.githubusercontent.com/1260765/72316994-1cb58680-3655-11ea-832c-07b8b51b1090.png)

**Comment by jasonbahl** [comment]
closed by #1112

**Comment by TylerBarnes** [comment]
Oh, wow! This is huge for processing inline images in html. Thanks @jasonbahl !
