### ISSUE TITLE
Query with custom theme

### ISSUE THREAD

**Issue by reinisg** [wp-graphql/wp-graphql#1092]
Hello,
I have issue with custom WordPress theme, in functions.php I have registered menus: 

```
function mytheme_menus() {
        $locations = array(
               'primary'   => __( 'Main menu', 'mytheme' ),
	       'secondary'  => __( 'Second menu', 'mytheme' ),
	);
	register_nav_menus( $locations );
}
add_action( 'init', 'mytheme_menus' );
```

And in admin I have created new primary menu. But when I go to the http://localhost:8000/___graphql in locations dropdown shows only EMPTY. Is there other place where need to register menu, to show it in graphql query?

```
wpgraphql
   menuItems
      where
         locations EMPTY
```

Regards,
Reinis

**Comment by jasonbahl** [comment]
@reinisg after registering nav menus like you did above, you should be able to query for menus by specific location like so:

```
{
  menus(where: {location: SECONDARY}) {
    nodes {
      id
    }
  }
}
```

![Screen Shot 2019-12-30 at 7 46 22 AM](https://user-images.githubusercontent.com/1260765/71586757-80c63f80-2ad8-11ea-94f2-3e6d34df3451.png)

**Comment by reinisg** [comment]
@jasonbahl Thanks for the answer, but problem were - to upgrade npm packages, then all worked fine again.
