### ISSUE TITLE
PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /home2/wp/public_html/wp-content/plugins/wp-graphql-develop/src/Data/Connection/AbstractConnectionResolver.php on line 177

### ISSUE THREAD

**Issue by atiyahio** [wp-graphql/wp-graphql#1094]
Everytime I setup wordpress to work with gatsby I get this error:
![image](https://user-images.githubusercontent.com/47905558/71384821-4c401880-25ec-11ea-8df4-c1792a9cd7e2.png)

Any idea whats wrong here?

**Comment by jasonbahl** [comment]
@atiyahio hey, it looks like you are on a PHP version below 7.0. The plugin requires PHP 7.0+

I'll open an issue to return a proper error stating as much to help users identify why things aren't working when on a server using a lower PHP version.

**Comment by jasonbahl** [comment]
Closing in favor of #1096
