### ISSUE TITLE
Correct & standardize descriptions for global "id" input fields

### ISSUE THREAD

**Issue by kellenmace** [wp-graphql/wp-graphql#1095]
For the `updateUser` mutation, the `id` input field's description says "The ID of the user". That is misleading though – WPGraphQL users will think that they should pass in the WP user ID, rather than the globally unique identifier for the user object. Screenshot: https://cloudup.com/crBNDmBdh5z

I think that to avoid that confusion for the `updateUser` mutation and any other operations, it would be good to do a quick sweep through the plugin and make sure that any `id` input fields have their descriptions updated with text like this, for clarity & consistency:
`The globally unique identifier for the <whatever type> object.`

Who's with me? 🍺

**Comment by THPubs** [comment]
I think this should be updated soon. I just got stuck while trying to issue a `updateUser` mutation. It said `An unknown error occurred`. At the end, the issue was the id!

**Comment by justlevine** [comment]
With #2506 merged, I recommend closing this in favor of #998 , which will render the  issue on any remaining descriptions (the ones for `ID` types) moot
