### ISSUE TITLE
Page is being listed in unselected parent category

### ISSUE THREAD

**Issue by mlbrgl** [wp-graphql/wp-graphql#1100]
(cross-posting from Slack in case the wider audience can help out)

_hi! I'm working with (hierarchical) categories and I can't figure out whether what I'm witnessing is the expected behaviour or not. When a page is attached to a child category, it also shows in the parent category. Is this how it is supposed to be? How to not list it there but only in the child category?
here is some additional info to illustrate what I'm trying to accomplish_
![Screenshot 2019-12-21 at 20 34 53](https://user-images.githubusercontent.com/13406362/71662119-a8274180-2d50-11ea-9c5f-3f9395ae3496.png)

Since then, I experimented with from `shouldOnlyIncludeConnectedItems`and `shouldOutputInFlatList` introduced in https://github.com/wp-graphql/wp-graphql/pull/387 and mentioned in https://github.com/wp-graphql/wp-graphql/issues/381 but my use case seems slightly different: **I am trying to build a tree with categories as the root notes and pages as the children** where `shouldOnlyIncludeConnectedItems` is being showcased on the reverse structure (pages as roots and attached categories as children).

**Comment by jasonbahl** [comment]
@mlbrgl thanks for reporting. I'll have to look into this a bit. Thanks for the screenshots and details. Should help reproduce and identify issues.

**Comment by jasonbahl** [comment]
@mlbrgl I am able to reproduce this, and I would agree this is not intended behavior. I'm looking into the cause. 

The "posts" or in your case "pages" queried in connection with a specific term should be posts (or pages) connected to that term, not that term's parent.

**Comment by jasonbahl** [comment]
@mlbrgl aha! It looks like the `tax_query` include_children defaults to true: 

https://developer.wordpress.org/reference/classes/wp_query/#taxonomy-parameters

And we aren't properly handling that here: https://github.com/wp-graphql/wp-graphql/blob/fe71e01dd95388f5b89ec971f52cdf4499f330df/src/Data/Connection/PostObjectConnectionResolver.php#L219-L224

PR coming.

**Comment by jasonbahl** [comment]
@mlbrgl this is kind of interesting though. If you navigate in your WP Dashboard to Categories, select a Parent Category and click "View", you will see both unselected and selected posts. 

For example, I have just one post titled "Many Categories" in the "Parent Category" and this is what I see: 

![Screen Shot 2020-01-09 at 3 49 30 PM](https://user-images.githubusercontent.com/1260765/72111488-2c9d3580-32f8-11ea-8cfb-99d675004112.png)

So we _at least_ will need a way to include children on these connections, but I would agree that it shouldn't be the default as it is currently.

**Comment by jasonbahl** [comment]
> So we at least will need a way to include children on these connections, but I would agree that it shouldn't be the default as it is currently.

Regarding this, I'm not sure the best approach. 

For example, let's say we want to query like so: 

```
{
  category( id: "some-category" ) {
     nodes {
        id
        title
        posts( where: { includePostsInChildrenCategories: true } ) {
           ...PostFields
        }
     }
  }
}
```
What do we name that option? Something like the above `includePostsInChildrenCategories` or something else? 🤔 And how does this work when composed with other `$where` args? We'll need to make sure to include it only on connections from Terms to Post Objects, as that wouldn't make sense as an argument on a `RootQuery->Posts` connection, but we still need a _similar_ way to do this for `RootQuery->Posts` connections. Perhaps this is where the TaxQuery plugin coming to core in some form would make sense? 

For example, we can currently query: 

```
{
  posts( where: { categorySlug: "uncategorized" ) {
    ...PostFields
  }
}
```

And with the TaxQuery extension we can query like so: 

```
{
  posts(where: {
    taxQuery: {
      taxArray: [
        {
          taxonomy: CATEGORY, 
          field: SLUG, 
          terms: ["child-category"], 
          includeChildren: true, 
          operator: NOT_IN
        }
      ]
  }
  }) {
    nodes {
      ...PostFields
    }
  }
}
```

**Comment by mlbrgl** [comment]
@jasonbahl thanks for addressing this so quickly! I also saw #1108, and although most of it is beyond my current understanding, it looks promising from a black box perspective. If at all helpful, I can run that PR code in my current project and see how it behaves.

Not sure if this is still relevant but `includePostsInChildrenCategories` is very descriptive, so from that angle, it's getting my vote.

Thanks again!
