### ISSUE TITLE
Replace - in addition to _ for allowed_setting_types 

### ISSUE THREAD

**Issue by saleebm** [wp-graphql/wp-graphql#1103]
Using the [Google site kit plugin](https://github.com/google/site-kit-wp), and version 0.5.1 of WPGraphQL, the query name for the setting was google-site-kitSetting.

![Screen Shot 2020-01-04 at 12 20 01](https://user-images.githubusercontent.com/34875122/71770805-73a5b800-2eff-11ea-89a0-112eebc296b1.jpg)

I believe the issue is from here in the [type registry].

[type registry]: https://github.com/wp-graphql/wp-graphql/blob/fe71e01dd95388f5b89ec971f52cdf4499f330df/src/Registry/TypeRegistry.php#L301

I also see the settings_group [referenced here] with a regex replace

[referenced here]: https://github.com/wp-graphql/wp-graphql/blob/dd11205fc9ef572d0cbb5ddcc32d9d58b95475cc/src/Data/DataSource.php#L534

**Comment by jasonbahl** [comment]
@saleebm I've opened a PR to address this. #1107. 

I tested quickly with the Google Site Kit plugin and it seems to resolve the issue. Would love if you could also confirm. 

Thanks!

**Comment by saleebm** [comment]
Confirmed! Thank you
