### ISSUE TITLE
Revisions should use parent post's categories

### ISSUE THREAD

**Issue by let00** [wp-graphql/wp-graphql#1106]
```
query {
  revisions {
    nodes {
      ... on Post {
        categories(where: {shouldOutputInFlatList: true}) {
          nodes {
            id
          }
        }
      }
    }
  }
}

```

The response:
```
{
  "data": {
    "revisions": {
      "nodes": [
        {
          "categories": {
            "nodes": []
          }
        }
      ]
    }
  }
}
```

This query will not return categories, as Wordpress Core does not support revisions for categories. I think we should still return the parent post's categories, rather return an empty array of categories. Seems like this should be an easy change in the [TermObjectConnectionResolver](https://github.com/wp-graphql/wp-graphql/blob/dd11205fc9ef572d0cbb5ddcc32d9d58b95475cc/src/Data/Connection/TermObjectConnectionResolver.php#L130), if we replace the `source ID` with the `parent ID` for revision post types.

### When reporting a _bug_, please be sure to include the following:
- [x] A descriptive title
- [x] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)
- [x] What version of `WPGraphQL` you're using, and the platform(s) you're running it on
WPGraphQL 0.5.0, OSX Mojave
- [x] What other plugins you're using
WPGraphQL ACF
- [x] The behavior you expect to see, and the actual behavior

### When you open an _issue_ for a feature request, please add as much detail as possible:
- [x] A descriptive title
- [x] A description of the problem you're trying to solve, including *why* you think this is a problem
- [x] An overview of the suggested solution
- [x] If the feature changes current behavior, reasons why your solution is better

**Comment by jasonbahl** [comment]
🤔 This is an interesting idea. 

I wonder if this is better suited for plugin territory? 

One thing that might be worth exploring would be to store an array of term IDs as meta on revisions at the time the revision is created, then use those IDs to resolve `revision->term` connections, that way there's actually a record of the terms associated with the Post node at that point in time. 

Something like:

- hook in where revisions are saved
- store array of `[ "taxonomy": [ id, id, id ]` as meta on the revision, representing the terms connected at that point in time
- filter the `revision->term` connection to resolve using those IDs

**Comment by let00** [comment]
@jasonbahl That sounds like a great idea! I see there is a `graphql_term_object_connection_query_args` hook that we can use if we decide to make a plugin. And then WP has the `wp_put_post_revision` hook which we can use to store revision meta.

I can work on a plugin in my free time if you decide this is not worth supporting in WPGraphQL.

**Comment by jasonbahl** [comment]
@let00 I'm on the fence. 

It's kind of disappointing that querying terms associated with revisions returns nothing, but it's also misleading to have it return terms of the parent, as it would appear that that was the terms associated with the revision at XX point in time, and that's not accurate. 

It would be nice if there were a core mechanism to store revisions of term relationships so we could see how things actually evolved over time.

**Comment by let00** [comment]
@jasonbahl Trying to understand what you mean. Let's say the first revision has a category with `ID=1` and `name=Adventure`. Then we change the post's category to `ID=2`, `name=Comedy`. We then change the `ID=1` category's name to `Thriller`. Even though the first revision will still point to the `ID=1` category, it's name won't be `Comedy`.

This makes sense for the multiple revision s feature in WP admin, but does not make sense for preview. In preview, we always want the latest state of the post. So what if we create a new field for Posts, called preview, which points to the latest revision that uses the parent post's categories (and other fields not supported by WP Core revisions)?

Right now, for WP headless preview we have to make a query for both the revision and the parent post and then merge the two objects. Wish WPGraphQL could simplify this process.

**Comment by jasonbahl** [comment]
@let00 ya, I think you bring up some good points, especially regarding preview. Perhaps the better option is to do as you suggest and support the parent categories by default, and plugins, such as the idea I proposed, could filter that. 🤔

**Comment by jasonbahl** [comment]
I'm also interested in exploring multiple entry points, as you suggest. One for `revisions` and one for `preview` that might have somewhat different behaviors. This could get confusing, as they would be _nearly_ identical with some likely non-obvious changes. 

I'm leaning more toward your initial proposal of supporting parent terms on revision connections. I think that supports the preview case and the "frozen in time" case (at least for core parity of that feature, as core doesn't have a UI for terms connected to any given revision)

**Comment by jasonbahl** [comment]
@let00 I'm going to label this actionable. I think you've laid out a good argument for the default behavior. It does seem to line up the most with existing core behavior, and other ways of revising term connections (like my proposal) can come in the way of plugins, etc.

**Comment by jasonbahl** [comment]
@let00 this is addressed in #1337. More details here: https://github.com/wp-graphql/wp-graphql/issues/1312#issuecomment-638882448

**Comment by let00** [comment]
lol what a beast of a PR

**Comment by jasonbahl** [comment]
😆  ya. . .got in the zone, just hammering things out. Need to quit working like this. . .it's hard to grok for folks reviewing etc. 🤦‍♂️
