### ISSUE TITLE
How to exept some categories from posts query?

### ISSUE THREAD

**Issue by DimaBur** [wp-graphql/wp-graphql#1110]
Is it possible to exept some categories from query? 
For example if I want to query some posts with special parameters I can use such query:

```
query GET_POSTS($categoryName: String) {
        posts(where: {categoryName: $categoryName}) {
            edges {
            cursor
                node {
                    id
                    date
                    title
                    uri
                  	excerpt
                  	tags {
                      edges {
                        node {
                          name
                        }
                      }
                    } 
                }
            }
        }
    }
```

Is it possible to make an opposite query, where I can exclude some post categories from response data?

**Comment by jasonbahl** [comment]
@DimaBur at the moment the core WPGraphQL doesn't expose arguments to do this. But, you could use the WPGraphQL Tax Query plugin (https://github.com/wp-graphql/wp-graphql-tax-query) to do this.

With that plugin active along with WPGraphQL, you can do a query like so, and that will provide you with posts that are NOT IN the "uncategorized" category:

```
{
  posts(where: {
    taxQuery: {
      taxArray: [
        {
          taxonomy: CATEGORY, 
          field: SLUG, 
          terms: ["uncategorized"], 
          includeChildren: false, 
          operator: NOT_IN
        }
      ]
    }
  }) {
    nodes {
      id
      title
      categories {
        nodes {
          name
        }
      }
    }
  }
}
```

**Comment by jasonbahl** [comment]
@DimaBur actually, I mis-spoke. WPGraphQL core plugin _does_ allow you to do a `categoryNotIn` query without an extension. 

You can do the following: 

```
{
  posts(where: {categoryNotIn: 1}) {
    nodes {
      id
      title
      categories {
        nodes {
          id
          categoryId
          name
        }
      }
    }
  }
}
```

The input value for `categoryNotIn` should be the integer database id for the term to not include. Ideally this would be more flexible to accept the global hashed ID or fields like the category slug or name, but for now it accepts the integer ID

**Comment by DimaBur** [comment]
Thank you!

**Comment by jasonbahl** [comment]
You're welcome! Excited to hear more about what you're building with WPGraphQL!

**Comment by emaildano** [comment]
The answer I needed wasn't here but these answers did help. I needed a list of just categories but excluding a few based on their category ID.

In case this helps someone else:

Exclude categories with ID 13 and 14 and any empty ones too.

```
{
  wpgraphql {
    categories(where: {hideEmpty: true, exclude: ["13", "14"]}) {
      nodes {
        name
        categoryId
      }
    }
  }
}
```

**Comment by parkerproject** [comment]
@jasonbahl I noticed your guys mentioned operators like `categoryNotIn`, `hideEmpty` ,etc.
where do I find documentation on all available query operators

**Comment by jasonbahl** [comment]
@parkerproject at the moment, the best place to find what options are available would be to browse the Schema in a tool like GraphiQL. 

You can install GraphiQL in the WordPress dashboard using this plugin: https://github.com/wp-graphql/wp-graphiql

**Comment by parkerproject** [comment]
@jasonbahl omg that's a lifesaver, wasn't aware of that plugin. thanks
