### ISSUE TITLE
Making axios or fetch request to graphql endpoint

### ISSUE THREAD

**Issue by SunooBertsch** [wp-graphql/wp-graphql#1113]
We are trying to create a sitemap using @nuxtjs/sitemap and need to make a request to the wordpress graphql API in order to obtain all of the dynamic routes from the backend. Is it possible to send an axios or fetch request to our graphql API from within nuxt.config, and if so, how should the headers be set in the post request?

Any help would be greatly appreciated!

**Comment by jasonbahl** [comment]
@SunooBertsch you can read about various ways to fetch the WPGraphQL endpoint on this page: https://docs.wpgraphql.com/getting-started/interacting-with-wpgraphql/

This example is close to what using Axios would look like: https://docs.wpgraphql.com/getting-started/interacting-with-wpgraphql/#browser-console

Hopefully this helps?

**Comment by SunooBertsch** [comment]
Turns out our flywheel hosting was blocking the requests we were making before. Your response is greatly appreciated though, and noted for the future. Thanks for taking the time Jason!
