### ISSUE TITLE
Upcoming release bug: Cannot query field "excerpt" on type "Page".

### ISSUE THREAD

**Issue by TylerBarnes** [wp-graphql/wp-graphql#1118]
On master this query works, but the type is removed in the upcoming release
```graphql
{
  pages {
    nodes {
      excerpt
    }
  }
}
```

**Comment by jasonbahl** [comment]
Ok, so this is expected. Pages don't support excerpts in out-of-the-box WordPress, so they shouldn't have ever been exposed to the Page type. This release places the field behind a `post_type_supports()` check, so only Post Types that support excerpts will have this field.

**Comment by TylerBarnes** [comment]
Cool, makes sense!
