### ISSUE TITLE
Filter the Query to allow for caching and using cached ASTs

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#112]
See: https://github.com/graphql/graphql-js/issues/158#issuecomment-135158371

To enable named/cached queries, we should filter the `$query` to allow for a $_REQUEST to send the key to a cached AST and use that AST to run the query. 

Lee Byron points out some of the benefits of doing this in that github thread.

But this would allow for clients to send just a small key that is a reference to a query, and that key would be used to get the full query AST from the cache and process the query. 

So instead of a client sending something like: 

```
{
  comments(first: 5) {
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
    edges {
      cursor
      node {
        id
        content
        commentedOn {
          __typename
        }
      }
    }
  }
  posts(first: 5) {
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
    edges {
      cursor
      node {
        id
        link
        title
        date
      }
    }
  }
}
```

They could just send something like: 

```
id_of_the_cached_query
```

So the upload time by a network to pass the query to the server would be extremely minimal compared to sending the data for the full query string.

**Comment by jasonbahl** [comment]
![screen shot 2017-04-21 at 8 35 02 am](https://cloud.githubusercontent.com/assets/1260765/25282350/6f01c57a-266d-11e7-8182-c2b3842ff20c.png)

**Comment by jasonbahl** [comment]
Closing this. Not enough clarity (even though I opened the issue)

**Comment by jasonbahl** [comment]
@epeli if you want to take a stab at caching/co ASTs that would be sweet. Then we can identify if we need a new hook or if existing hooks give us enough info at proper locations.

**Comment by jasonbahl** [comment]
Closing per #590

**Comment by esamattis** [comment]
Persisted queries are somewhat related persisted quereis but AST caching is useful as is too. Reopening.
