### ISSUE TITLE
Undefined index: order

### ISSUE THREAD

**Issue by drewbaker** [wp-graphql/wp-graphql#1120]
Using WP-GQL v0.5.1, this query gives an error:

```
query MyQuery {
  posts(where: {categoryName: "us", orderby: {field: AUTHOR}}) {
    nodes {
      title
    }
  }
}
```

Error is `Notice: Undefined index: order in /www/wp-content/plugins/wp-graphql/src/Data/Connection/PostObjectConnectionResolver.php on line 270`

The `field: AUTHOR` seems to be the source of the error. Any valid setting of that gives the same error.

This query will work though:
```
query MyQuery {
  posts(where: {categoryName: "us", orderby: {field: AUTHOR, order: ASC}}) {
    nodes {
      title
    }
  }
}
```

**Comment by jasonbahl** [comment]
@drewbaker I've opened a Pull Request to address this. Can you confirm that it indeed resolves the issue you were experiencing? 

https://github.com/wp-graphql/wp-graphql/pull/1127
