### ISSUE TITLE
Upcoming release regression: Cannot return null for non-nullable field User.databaseId.

### ISSUE THREAD

**Issue by TylerBarnes** [wp-graphql/wp-graphql#1121]
On master User.databaseId doesn't exist but on release/next it does and querying for it causes this error `Cannot return null for non-nullable field User.databaseId.`

```graphql
query {
  viewer {
    databaseId
  }
}

```

**Comment by jasonbahl** [comment]
@TylerBarnes Hmm. I'm not able to reproduce this. 

As an authenticated user I can query and get the databaseId returned.

As an unauthenticated user I get the following payload:

```
{
  "errors": [
    {
      "debugMessage": "You must be logged in to access viewer fields",
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "viewer"
      ]
    }
  ],
  "data": {
    "viewer": null
  }
}
```

**Comment by TylerBarnes** [comment]
Looks like this was fixed at some point!
