### ISSUE TITLE
Cursor Pagination for User connection

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#113]
There's not any filters in the \WP_User_Query class for modifying the SELECT statement in order to customize for cursor pagination, so we'll need to come up with another way to add cursor pagination for users.

See other cursors implemented here: #114

**Comment by CodeProKid** [comment]
This does not sound like a fun issue to tackle...

**Comment by CodeProKid** [comment]
This might be puntable, since it _technically_ works right now, just not in a very relay way.

**Comment by jasonbahl** [comment]
I believe the work done by @epeli should make this an accomplishable task now 😄 

Can probably get this on the roadmap for the next release 🤔

**Comment by let00** [comment]
I can try to poke at this.
