### ISSUE TITLE
feat: uri field on MenuItem

### ISSUE THREAD

**Issue by TylerBarnes** [wp-graphql/wp-graphql#1137]
Since uri got added to the new ContentNode type, it would be really useful for menus to be able to use that to link to pages that are created from nodes using the uri field as the page path.

**Comment by TylerBarnes** [comment]
Ahh, ok I guess this is already possible.

```graphql
{
  menus {
    nodes {
      menuItems {
        edges {
          node{
            connectedObject {
              __typename
              ... on ContentNode {
                uri
              }
            }
          }
        }
      }
    }
  }
}
```
Seems like a lot of work to get the uri though. Curious what you think

**Comment by TylerBarnes** [comment]
Maybe we could just return the url with the current site url stripped as a `path` field instead? Since that wouldn't be garunteed to be the uri

**Comment by zambo** [comment]
> ```graphql
> connectedObject {
>               __typename
>               ... on ContentNode {
>                 uri
>               }
>             }
> ```

Thanks for pointing this out, helped a lot for regular menu items.

I Just want to to point out that this solution only works for regular menu items. In my case, I have a custom port type archive on my menu and it doesn't work out of the box.

**Comment by TylerBarnes** [comment]
Yeah, a `path` field would be super helpful here as a menu item could be connected to an object or it could have some other kind of link

**Comment by jasonbahl** [comment]
Added a `path` field that returns a relative path for internal resources and absolute path for external resources. 

More info in this duplicate issue: https://github.com/wp-graphql/wp-graphql/issues/834#issuecomment-649794076

Closing as resolved (and duplicate)
