### ISSUE TITLE
[Users Query -> where -> loginIn/logNotIn ] - incorrect variable requested

### ISSUE THREAD

**Issue by holyblast** [wp-graphql/wp-graphql#1140]
The Users query has a way to look for a group of logins.
login itself being a string variable.

the query condition terms should request an array of strings yet requests an Int variable instead.

(Same situation for the where condition: loginNotIn)

![image](https://user-images.githubusercontent.com/12165693/73618447-7d225d00-4630-11ea-8877-b83bfcba6507.png)

![image](https://user-images.githubusercontent.com/12165693/73618459-8ca1a600-4630-11ea-805c-e132ff40f489.png)

**Comment by justlevine** [comment]
This was fixed in #1368. Closing

(screenshot from 1.7.2)
![image](https://user-images.githubusercontent.com/29322304/161408409-17b96654-3ad6-4716-b8b8-fa94b648eae6.png)
