### ISSUE TITLE
Error in NodeResolver when querying nested page

### ISSUE THREAD

**Issue by andersthorborg** [wp-graphql/wp-graphql#1142]
Thanks for bringing graphql to Wordpress!

There is currently and issue with querying nested paths using contentNode(id: $uri, idType: URI).

It seems to narrow down to line ~357 in Data/NodeResolver.php

```
$args  = array(
	'name'            => $this->wp->query_vars['pagename'], // this line
	'post_type'           => 'page',
	'post_status'         => 'publish',
	'posts_per_page'      => 1,
	'ignore_sticky_posts' => true,
	'no_found_rows'       => true,
);
```

Changing `name` to `pagename` resolves the issue for me, but I am not entirely sure about the workings of the resolve_uri-function to judge whether there are any side effects to this change?

**Comment by jasonbahl** [comment]
@andersthorborg Thanks for reporting. 

I've confirmed this is indeed a bug. See below:

### Query Post by ID
![Screen Shot 2020-02-21 at 1 15 03 AM](https://user-images.githubusercontent.com/1260765/75016204-b12aba00-5447-11ea-9932-f7fec3d6d257.png)

### Query Post by Path
![Screen Shot 2020-02-21 at 1 13 39 AM](https://user-images.githubusercontent.com/1260765/75016202-aff98d00-5447-11ea-8890-5eada7a51ab7.png)

---

I've got a PR coming to address!

**Comment by jasonbahl** [comment]
@andersthorborg I've opened a PR here: https://github.com/wp-graphql/wp-graphql/pull/1158

Could you confirm that this resolves the situations you were running into?
