### ISSUE TITLE
User/Author fields value treated as function

### ISSUE THREAD

**Issue by iamlili** [wp-graphql/wp-graphql#1144]
Hi,

Bug found in core wp-graphql

Initially thought it was related to ACF therefore created an issue here https://github.com/wp-graphql/wp-graphql-acf/issues/105

If any user fields eg, firstName, lastName, have a value that happens to also be a function name eg. count, sizeof, the function is actually run, resulting in a null value.

See link above for more details and how to replicate

**Comment by jasonbahl** [comment]
@iamlili thanks for reporting this! 

I think I've tracked down the source of the bug. 

Chatting with @CodeProKid about best path for resolving and working on a pull request now. Hope to have this bug squashed shortly. 

@henrikwirth thanks for replicating and consolidating the issues across the repos to this issue. 🙏

**Comment by iamlili** [comment]
Great!
Thanks @jasonbahl  for getting onto this so quickly!!
