### ISSUE TITLE
Version update messed with end-point /graphql

### ISSUE THREAD

**Issue by D19cannon** [wp-graphql/wp-graphql#1145]
Hi for those who run in a similar problem,

I just wanted to mention that the end-point has been affected in some newer versions.

I happen to setup Apollo and set use the wpgraphq where the end-point used to be www.yoursite.test/graphql

However, that is no longer the case.  **It only works in v5.0** from what I have tested quickly.
Other version I tried were v6.0 and v6.1

Just heads up if anyone else runs in the same problem and can't find it in the docs like me.

**Comment by jasonbahl** [comment]
@D19cannon the docs were updated to reflect this change here: https://docs.wpgraphql.com/getting-started/install-and-activate/#verify-the-endpoint-works

If you have thoughts on making it more clear, or different ways/places to communicate this, let us know. 

Thanks so much for using WPGraphQL and sharing your experience in issues like this for everyone to benefit from!
