### ISSUE TITLE
docs: Extensions pages don't have a link to the repo

### ISSUE THREAD

**Issue by TylerBarnes** [wp-graphql/wp-graphql#1165]
For example if you go to https://docs.wpgraphql.com/extensions/wpgraphql-content-blocks/, there's no link on the page to https://github.com/Quartz/wp-graphql-content-blocks

I'm not sure if those two repos are the same actually 🤔 the readme looks different

**Comment by jasonbahl** [comment]
@TylerBarnes this is why I was working on sourcing the extensions from the Github repos themselves. 

I originally started adding extensions by manually copying stuff from their README's, but that gets outdated _very quickly_. 

I never did get the sourcing from Github README's working. Need to circle back to that.

**Comment by jasonbahl** [comment]
Related: 
- https://github.com/wp-graphql/wp-graphql/issues/1124
- https://github.com/wp-graphql/wp-graphql/pull/1134

**Comment by TylerBarnes** [comment]
Ahhh, for some reason I thought that work was already merged.

**Comment by TylerBarnes** [comment]
I can take a look at it in a week or two if you'd like
