### ISSUE TITLE
OrderBy Field not working

### ISSUE THREAD

**Issue by hutber** [wp-graphql/wp-graphql#1168]
I am currently trying to use the `where` clause with a Custom Post Type and apply ordering on this field. I am using an older version, `0.5.1`, which may very well the cause of the problem.

The field is `menuOrder` and it is an `Int`

`  rankings(where: {orderby: {field: MENU_ORDER, order: ASC}}) {`

Steps to reproduce: create a CPT and order on this field. Changing order has no effect.

![image](https://user-images.githubusercontent.com/1344898/75390514-47dff680-58e0-11ea-8bc6-9942cc344c66.png)
![image](https://user-images.githubusercontent.com/1344898/75390528-4f070480-58e0-11ea-8aea-2e8499fc21de.png)

**Comment by jasonbahl** [comment]
@hutber I'm unable to replicate this behavior. 

Here, I've registered a `rankings` post type using the snippet below: 

```php
add_action( 'init', function() {

	register_post_type( 'ranking', [
		'show_ui' => true,
		'label' => __( 'Rankings', 'wp-graphql' ),
		'show_in_graphql' => true,
		'graphql_single_name' => 'Ranking',
		'graphql_plural_name' => 'Rankings',
		'supports' => [ 'title', 'page-attributes', 'thumbnail' ]
	] );

} );
```

Then I created 5 Rankings post and set the menu order for each one. 

When I query and order by menu order, we can see WPGraphQL returns the Rankings in appropriate order with `ASC` or `DESC` as the order:

![Screen Shot 2020-03-10 at 10 24 36 AM](https://user-images.githubusercontent.com/1260765/76336175-3d980200-62bb-11ea-8deb-21c8d22b6bc8.png)

![Screen Shot 2020-03-10 at 10 24 50 AM](https://user-images.githubusercontent.com/1260765/76336177-3ec92f00-62bb-11ea-9335-a3a89c4be63b.png)

My guess is that perhaps there is a plugin that might be affecting the underlying `WP_Query` calls.

I would suggest checking out the WPGraphQL Insights plugin (https://github.com/wp-graphql/wp-graphql-insights) which will output a QueryLog with the results and you can see the RAW MySQL query that WordPress is executing to get the results. 

When using GraphiQL, you can collapse the `tracing` in the extensions output to make it easier to browse the `queryLog` like shown in this screenshot: 

![Screen Shot 2020-03-10 at 10 45 31 AM](https://user-images.githubusercontent.com/1260765/76337004-6967b780-62bc-11ea-86e8-c0ac78abca7d.png)

Then you can scroll through to see all the underlying queries being executed. 

For me, in a pretty bare environment, the raw query is: 

```
SELECT   wp_posts.ID FROM wp_posts  WHERE 1=1  AND wp_posts.post_parent = 0  AND wp_posts.post_type = 'ranking' AND ((wp_posts.post_status = 'publish'))  ORDER BY wp_posts.menu_order DESC, wp_posts.ID DESC  LIMIT 0, 11
```

And the full trace of this log from WPGraphQL Insights is below:

```
        {
          "sql": "SELECT   wp_posts.ID FROM wp_posts  WHERE 1=1  AND wp_posts.post_parent = 0  AND wp_posts.post_type = 'ranking' AND ((wp_posts.post_status = 'publish'))  ORDER BY wp_posts.menu_order DESC, wp_posts.ID DESC  LIMIT 0, 11",
          "time": 0.0002579689025878906,
          "stack": "require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array('parse_request'), WP_Hook->do_action, WP_Hook->apply_filters, WPGraphQL\\Router->resolve_http_request, WPGraphQL\\Router::process_http_request, WPGraphQL\\Request->execute_http, GraphQL\\Server\\StandardServer->executeRequest, GraphQL\\Server\\Helper->executeOperation, GraphQL\\Server\\Helper->promiseToExecuteOperation, GraphQL\\GraphQL::promiseToExecute, GraphQL\\Executor\\Executor::promiseToExecute, GraphQL\\Executor\\Executor->doExecute, GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter->create, GraphQL\\Executor\\Executor->GraphQL\\Executor\\{closure}, GraphQL\\Executor\\Executor->executeOperation, GraphQL\\Executor\\Executor->executeFields, GraphQL\\Executor\\Executor->resolveField, GraphQL\\Executor\\Executor->resolveOrError, WPGraphQL\\Utils\\InstrumentSchema::WPGraphQL\\Utils\\{closure}, call_user_func, WPGraphQL\\Utils\\InstrumentSchema::WPGraphQL\\Utils\\{closure}, call_user_func, WPGraphQL\\Registry\\TypeRegistry->WPGraphQL\\Registry\\{closure}, call_user_func, WPGraphQL\\Connection\\PostObjects::WPGraphQL\\Connection\\{closure}, WPGraphQL\\Data\\DataSource::resolve_post_objects_connection, WPGraphQL\\Data\\Connection\\AbstractConnectionResolver->get_connection, WPGraphQL\\Data\\Connection\\AbstractConnectionResolver->execute_and_get_ids, WPGraphQL\\Data\\Connection\\PostObjectConnectionResolver->get_query, WP_Query->__construct, WP_Query->query, WP_Query->get_posts"
        }
```

**Comment by jasonbahl** [comment]
@hutber ah, I looked over your mention of using `0.5.1`. I was testing on `v0.7.0`.

I just went and checked out v0.5.1, and I'm still not able to replicate. Ordering is still working fine for me. 

![Screen Shot 2020-03-10 at 10 56 49 AM](https://user-images.githubusercontent.com/1260765/76338192-f9f2c780-62bd-11ea-8e01-47c787f8288d.png)
![Uploading Screen Shot 2020-03-10 at 10.57.10 AM.png…]()

**Comment by jasonbahl** [comment]
@hutber ah, I looked over your mention of using `0.5.1`. I was testing on `v0.7.0`.

I just went and checked out v0.5.1, and I'm still not able to replicate. Ordering is still working fine for me. 

![Screen Shot 2020-03-10 at 10 56 49 AM](https://user-images.githubusercontent.com/1260765/76338192-f9f2c780-62bd-11ea-8e01-47c787f8288d.png)
![Screen Shot 2020-03-10 at 10 57 10 AM](https://user-images.githubusercontent.com/1260765/76338201-fbbc8b00-62bd-11ea-8ce7-cef604304ae9.png)

**Comment by hutber** [comment]
Thank you enormously Jason!!

I believe using the raw queries will return as expected, but I will go through this thoroughly once home. 

i did disable all of my plugins, but now I know that it is working on the code as you have said, I can more closely make sure everything is as it should be.

**Comment by adriandmitroca** [comment]
Hmm, how have you added `where` argument? I don't see this available on my side.

>Unknown argument \"where\" on field \"allWpPage\" of type \"Query\".

Only filter, skip, sort & order arguments are available.

**Comment by jasonbahl** [comment]
@adriandmitroca `allWpPage` is part of the Gatsby Schema, not WPGraphQL. 

The arguments you have when querying the Gatsby GraphQL API are different than the arguments available when querying WPGraphQL directly.

**Comment by adriandmitroca** [comment]
@jasonbahl 

Damn, that's a shame - any idea at all for a quick workaround?

**Comment by jasonbahl** [comment]
@adriandmitroca what are you trying to accomplish in Gatsby? The filters available in Gatsby should get you pretty far. 

Also, what Gatsby Source plugin are you using? I'd recommend `gatsby-source-wordpress-experimental` and _not_ `gatsby-source-wordpress`. 

The experimental plugin communicates with WordPress using WPGraphQL and the `gatsby-source-wordpress` uses the WP REST API, and there are many problems with that we're solving with the new experimental plugin (which will become gatsby-source-wordpress v4 in the future) and the official WordPress source we'll be supporting at Gatsby.

**Comment by adriandmitroca** [comment]
@jasonbahl 

I'm using `gatsby-source-wordpress-experimental`. I've just noticed that `menuOrder` field isn't available in custom type (registered by Custom Post Type UI), but is available for default Pages, so most likely solution is trivial and I'm missing something obvious

**Comment by jasonbahl** [comment]
@adriandmitroca I believe you need to register the post type in WordPress to support "page attributes" in order for menu-order to be supported. Can you try that?

**Comment by adriandmitroca** [comment]
That was it! Thanks

**Comment by hutber** [comment]
Closeing due to date and that it certainly works for me now, thank you
