### ISSUE TITLE
Decode object titles

### ISSUE THREAD

**Issue by renatonascalves** [wp-graphql/wp-graphql#1169]
Task: Make sure all the object titles are decoded.

Bug first mentioned here: https://github.com/wp-graphql/wp-graphql-woocommerce/issues/244

**Comment by jasonbahl** [comment]
Related: 
- #1035 
- #410

**Comment by jasonbahl** [comment]
So, one thing to note, the WP REST API _also_ outputs the strings this way. . .not that we should always do the same as the REST API, but might be helpful context.

<img width="483" alt="Screen Shot 2020-02-28 at 4 55 44 PM" src="https://user-images.githubusercontent.com/1260765/75593532-454de000-5a4b-11ea-9b2a-639b6c7ec64b.png">

**Comment by jasonbahl** [comment]
@renatonascalves I'm removing the `Good First Issue` as I think this needs more discussion. There's been some discussion in the related issues and I'm not 💯 sure I feel like we have "the right" solution. 

@henrikwirth @esamattis @TylerBarnes @chriszarate @CodeProKid ya'll have further thoughts on this?

**Comment by esamattis** [comment]
I still stand behind my arguments in #1035 that wpgraphql and its extensions should remove the escaping by default.

But maybe we should create a plugin from my [gist](https://gist.github.com/esamattis/54abd801b078056f9e646d63d47ccc4c) first and how it received by the comminity?

**Comment by jasonbahl** [comment]
@esamattis ya, I think I'm leaning toward WPGraphQL removing the escaping via `html_entity_decode()`. 

I wonder if we apply `html_entity_decode()` to all string fields by default, but allow a string to disable it via the registry for the rare cases a string field may want to allow it?

something like the following (could happen in the default resolver instead of a filter too): 

```
add_filter( 'graphql_resolve_field', function( $result, $source, $args, $context, $info, $type_name, $field_key ) {

  // pseudo code
  // If the field is a String, and the config for the field doesn't explicitly ask the
  // field to be encoded
  if ( 'string' === $context->getFieldType() && true !== $context->getFieldConfig()['encode_entities'] ) {

     return html_entity_decode( $result, ENT_QUOTES );

  }

  return $result;

}, 10, 7 );
```

**Comment by CodeProKid** [comment]
Yeah, I think I'm OK with this being the functionality by default. I can't think of too many use cases where you _wouldn't_ want this. And I don't really think this change would break many consumers.

**Comment by esamattis** [comment]
It might be "rare" but it could still have unseen consequences. For example it is ok that html entities appear in urls. And there are a lot of fields returning urls.

Ex. field returning `http://example.com?data=&copy;` is completely legit but it has different meaning when decoded to `http://example.com?data=©`. Maybe. We cannot know that. Esp. when it comes to extensions authors. This is not very real world example but it kinda feels dangerous to enable it for all strings.

But is it worse than the current situation? I don't know. I've seen the current behaviour causing a lot of rendering bugs in React apps but it does not usually break anything.

**Comment by jasonbahl** [comment]
> Ex. field returning http://example.com?data=&copy; is completely legit but it has different meaning when decoded to http://example.com?data=©. Maybe. We cannot know that. Esp. when it comes to extensions authors. This is not very real world example but it kinda feels dangerous to enable it for all strings.

Ya. . .we for sure need to consider this kind of scenario. This type of thing is why I've been hesitant to make a move one way or another.

**Comment by renatonascalves** [comment]
Maybe that's why the BP REST API didn't add it. My goal actually was to add it only on the object titles. Not everywhere.

**Comment by esamattis** [comment]
I kinda lean on manually whitelisting the fields that get automatically decoded. Or does anyone see some dowsides if we just decode `title`, `content` etc.? It's probably a long list but doable.

**Comment by jasonbahl** [comment]
Ya. I’m probably more a fan of explicitly adding it to the fields we feel should have it. 

Content is a tricky one though as it’s likely the field with the most instances of links, such as the `http://example.com?data=©` example. 🤔

**Comment by jasonbahl** [comment]
Content will have so much unpredictable input. Hard to say for sure how this would affect output. Could get real interesting

**Comment by esamattis** [comment]
Hmm. WordPress has to call the opposite (`htmlentities()`) when it saves the content.

Example before save

![image](https://user-images.githubusercontent.com/225712/76397415-b06cb000-6383-11ea-9736-49a3bbdba70d.png)

After saving it becomes

![image](https://user-images.githubusercontent.com/225712/76397447-be223580-6383-11ea-972c-3d75897fc5ef.png)


So WordPress is kinda broken by default and calling  `html_entity_decode()` would actually fix it.


-----------


BUT! While testing this I realized that WordPress does not actually encode all html entities. Eg. my `©` example was invalid. It does not get converted to `&copy;`. This means `html_entity_decode()` is not the correct function to reverse WordPress entity encoding.

Quick look to the WP core brought up`wp_kses_normalize_entities()`

https://github.com/WordPress/WordPress/blob/bcb8ee6dcf8ea69bc5e60ff196d9452d5b14eaa1/wp-includes/kses.php#L1741-L1762

Which is used in `_wp_specialchars()`

https://github.com/WordPress/WordPress/blob/bcb8ee6dcf8ea69bc5e60ff196d9452d5b14eaa1/wp-includes/formatting.php#L997

**Comment by jasonbahl** [comment]
In testing, `wp_kses_normalize_entities()` doesn't do what we need here. 

`html_entity_decode()` does seem to be working pretty well. 

Going to run with `html_entity_decode( $string, ENT_QUOTES )`. If this causes issues for anyone, please let me know and we can address and tests for that specific situation.

**Comment by jasonbahl** [comment]
This has been addressed. It would be good to get folks testing this in case there are cases not fully covered by `html_entity_decode()` but in my tests it seems to be the right option here. 

Here are some examples. 

## Saving a post with ampersand in the title and content: 

![Screen Shot 2020-06-04 at 9 15 28 AM](https://user-images.githubusercontent.com/1260765/83775514-4131ef80-a644-11ea-8249-2af32536f547.png)

## BEFORE: 

![Screen Shot 2020-06-04 at 9 16 28 AM](https://user-images.githubusercontent.com/1260765/83775589-5a3aa080-a644-11ea-9d2f-3b9f02030d1f.png)

## AFTER:

![Screen Shot 2020-06-04 at 9 15 50 AM](https://user-images.githubusercontent.com/1260765/83775583-59097380-a644-11ea-95e4-0f3df2c7ed2d.png)

----

The query used in the examples above: 

```graphql
{
  post(id: "cG9zdDo2MTQ") {
    ...PostFragment
    preview {
      node {
        ...PostFragment
      }
    }
  }
}

fragment PostFragment on Post {
  id
  databaseId
  title
  content
  author {
    node {
      name
    }
  }
  featuredImage {
    node {
      sourceUrl
    }
  }
}
```

The fields in question: 

## Before
```json
{
  "title": "Tests &#038; More",
  "content": "\n<p>tests &amp; more&#8230;</p>\n\n\n\n<p></p>\n\n\n\n<p><a href=\"http://example.com?data=©\">http://example.com?data=©</a></p>\n",
}
```

## After
```json
{
  "title": "Tests & More",
  "content": "\n<p>tests & more…</p>\n\n\n\n<p></p>\n\n\n\n<p><a href=\"http://example.com?data=©\">http://example.com?data=©</a></p>\n",
}
```

**Comment by renatonascalves** [comment]
Nice! ✌️

**Comment by TylerBarnes** [comment]
Awesome :D
