### ISSUE TITLE
User loginIn and loginNotIn inputs are incorrect types and don't influence query

### ISSUE THREAD

**Issue by kellenmace** [wp-graphql/wp-graphql#1174]
When running a `WP_User_Query()` in PHP, `login__in` and `login__not_in` accept an array of user logins to be included in/excluded from the query. Docs: https://developer.wordpress.org/reference/classes/WP_User_Query/prepare_query/.

When running a `users` query using WPGraphQL however, the corresponding `loginIn` and `loginNotIn` input fields each accept a single integer. They need to be updated to accept an array of user logins instead, and use those logins to influence the users query that ultimately gets executed.

### Example Query

This query shows the input fields in question:

```graphql
query {
  users(where: {
    loginIn: 123 # Should be an array of user logins.
    loginNotIn: 456 # Should be an array of user logins.
  }) {
    nodes {
      userId
      name
    }
  }
}
```

### Expected behavior:
The `loginIn` and `loginNotIn` input fields would take an array of user logins as strings, which would then be used when the users query is run.

### Actual behavior:
The `loginIn` and `loginNotIn` input fields each take a single integer, and are not used when the users query is run.

### Plugin Version
WPGraphQL version: 0.7.0

**Comment by jasonbahl** [comment]
This _should_ be pretty straight forward to address. I believe all we need to do is change the Type of the fields for `loginIn` and `loginNotIn` to be `'type' => [ 'list_of' => 'Int' ]`. We'll need to make sure they are passing to the connection resolver properly as well, but I think this should be a pretty quick PR!

**Comment by holyblast** [comment]
same issue:  #1140 
but login itself is a string (user's slug name),
shouldn't the type of loginIn / loginNotIn be a list of String instead of Int?

**Comment by jasonbahl** [comment]
🤦‍♂ haha! yes. The issue right now is that it _is_ an Int. I need to slow down when I type. 

Should be changed to `'type' => [ 'list_of' => 'String' ]`

**Comment by jasonbahl** [comment]
@holyblast I updated the comment above to properly reflect. Thanks!
