### ISSUE TITLE
Implementing default Wordpress Search

### ISSUE THREAD

**Issue by daniyals14** [wp-graphql/wp-graphql#1182]
Im trying to replicate the WordPress default search which looking for the search term in titles, the search available under posts node looks for the keyword in content.

Im trying to implement search as requested in the initial request of this thread to look `post_title` contains "cat"

The current implementation translates to `/wp-json/wp/v2/posts?search=cat`
what im looking for `/wp-json/wp/v2/search?search=cat`

**Comment by jasonbahl** [comment]
> Im trying to implement search as requested in the initial request of this thread

@daniyals14 I'm not sure what thread you're referring to. If that context is helpful, please provide a link. 

That said, you can search WordPress posts in WPGraphQL like so:

```graphql
{
  posts(where: {search: "cats"}) {
    nodes {
      id
      title
      content
    }
  }
}
```

See it in action here: 

![Screen Shot 2020-03-10 at 2 33 51 PM](https://user-images.githubusercontent.com/1260765/76356819-303f3f80-62dc-11ea-8785-d758d6465bc1.png)

**Comment by daniyals14** [comment]
Sorry for include the initial issue created which was previously closed, https://github.com/wp-graphql/wp-graphql/issues/278

As i mentioned in the post earlier, the search in posts looks for keywords in content and does not replicate the default search for wordpress which I am looking for.

**Comment by jasonbahl** [comment]
@daniyals14 Can you share more details on how the results are different for you in REST vs. GraphQL?

I have 2 posts with the word "cat" in the title, and created another one with "cat" in the content but _not_ the title. 

When I search in REST and WPGraphQL, I get the same results, those 3 posts and no other posts: 

![Screen Shot 2020-03-11 at 8 53 57 AM](https://user-images.githubusercontent.com/1260765/76430485-fde22080-6375-11ea-87ac-090b51397621.png)

![Screen Shot 2020-03-11 at 8 52 27 AM](https://user-images.githubusercontent.com/1260765/76430478-fcb0f380-6375-11ea-8c5f-3f4cd307eca1.png)

**Comment by daniyals14** [comment]
Following is the GraphQL request and response
<img width="1054" alt="Screenshot 2020-03-11 at 10 52 21 PM" src="https://user-images.githubusercontent.com/56673332/76448214-cf069180-63eb-11ea-82ef-7d5df0ed11be.png">

Following is the response from `wp-json/wp/v2/search?search=jbr`

![Screenshot 2020-03-11 at 10 56 06 PM](https://user-images.githubusercontent.com/56673332/76448275-ecd3f680-63eb-11ea-838a-39574fe6308b.jpg)

Notice the order of search results, last screenshot titles both have keyword 'jbr' but not the same for Graphql response

**Comment by jasonbahl** [comment]
@daniyals14 where does the `language: EN` filter come from? That's not part of WPGraphQL core, so I'm curious if that is affecting the underlying query. I don't see you passing a language to the REST request, so it seems perhaps what is being searched is different for each request?

**Comment by daniyals14** [comment]
@jasonbahl its from wp-graphql-polylang, https://github.com/valu-digital/wp-graphql-polylang

**Comment by jasonbahl** [comment]
I imagine that is filtering the underlying query. Can you try without that argument and see if the results are still different than expected?

**Comment by daniyals14** [comment]
No difference

<img width="1036" alt="Screenshot 2020-03-16 at 10 20 26 AM copy" src="https://user-images.githubusercontent.com/56673332/76773151-01a7e580-6770-11ea-91ba-ba3ff5846747.png">

**Comment by jasonbahl** [comment]
@daniyals14 can you try with no plugins other than WPGraphQL and WPGraphiQL active?

I was able to replicate identical results between the WP REST API and WPGraphQL. I imagine a plugin is likely affecting the underlying queries. 

You could also install and activate the WPGraphQL Insights (https://github.com/wp-graphql/wp-graphql-insights) plugin and check out the raw sql query that's being generated.

When I execute the following GraphQL Query:

```
{
  posts(where: {search: "cats"}) {
    nodes {
      id
      title
      content
    }
  }
}
```

The raw SQL query that is executed (as found in the queryLog in WPGraphQL Insights) is: 

```
SELECT wp_posts.ID FROM wp_posts  WHERE 1=1  AND wp_posts.post_parent = 0  AND
(((wp_posts.post_title LIKE '%cats%') OR (wp_posts.post_excerpt LIKE '%cats%') OR
 (wp_posts.post_content LIKE '%cats%')))  AND wp_posts.post_type = 'post' AND
 ((wp_posts.post_status = 'publish'))  ORDER BY wp_posts.post_date DESC, wp_posts.ID
 DESC  LIMIT 0, 11
```

**Comment by jose-donato** [comment]
There is any approach to include the tags and categories in the search results as well?

**Comment by jasonbahl** [comment]
@jose-donato WordPress search internally doesn't search for terms, so you'd need to do something custom behind the scenes to get that to work. 

Have you implemented this type of search in WordPress outside of WPGraphQL?

**Comment by jose-donato** [comment]
Hello, @jasonbahl thanks for the fast answer.

Not really, I'm still researching for which approach I should use. The current options are using what you showed here or some service like algolia.

**Comment by jasonbahl** [comment]
@jose-donato Algolia and ElasticSearch are definitely better equipped at handling advanced searching than internal WordPress search. 

You might be able to accomplish something similar using this extension too: https://github.com/wp-graphql/wp-graphql-tax-query

You would be able to specify what taxonomy to search and could use the `LIKE` operator. 

So something like: 

```graphql
query{
  posts(
    where: {
      taxQuery: {
        relation: OR,
        taxArray: [
          {
            terms: ["cat"],
            taxonomy: CATEGORY,
            operator: LIKE,
            field: SLUG
          },
          {
            terms: ["cat"],
            taxonomy: CATEGORY,
            operator: LIKE,
            field: NAME
          }
        ]
      }
  	}
  ){
   ...
}
```

**Comment by jose-donato** [comment]
@jasonbahl thanks for the help. I also think Algolia is the best alternative for the usecase.
