### ISSUE TITLE
Convert query results to post object connections (to use Relevanssi)

### ISSUE THREAD

**Issue by a-barbieri** [wp-graphql/wp-graphql#1185]
I've been working on a simple implementation for [Relevanssi](https://www.relevanssi.com/) which enables to search posts via GraphQL.

The query works and returns results properly, but the implementation described in the [extending connections](https://github.com/wp-graphql/wp-graphql/blob/98c4bf6aca08b09d71af9caad627893aba91a325/docs/source/extending/connections.mdx) guideline **forces me to run the query twice**. 

This is due to the fact that I have tu use `relevanssi_do_query( $query )` to fetch posts using Relevanssi, and I don't know how to **transform the returned query into the right format for the resolver**.

Here is the code that can be added to `function.php` or to a custom plugin:

```php
use WPGraphQL\Data\DataSource;
use WPGraphQL\Data\Connection\PostObjectConnectionResolver;

add_action( 'graphql_register_types', 'register_my_custom_graphql_connection', 99 );

function register_my_custom_graphql_connection() {
  $config = [
    'fromType' => 'RootQuery',
    'toType' => 'Post',
    'fromFieldName' => 'myCustomGraphqlConnection',
    'connectionTypeName' => 'PostsFromMyCustomGraphqlConnection',
    'resolve' => function( $id, $args, $context, $info ) {

      // Prepare WP query for Relevanssi
      $args = array(
          //  `s` is the query parameter used by Relevanssi
          's' => $args['where']['search'],
      );
      $query = new WP_Query();
      $query->parse_query( $args );
      // https://www.relevanssi.com/user-manual/using-relevanssi-outside-search-pages/
      $search_results = relevanssi_do_query( $query );

      // Get an array of IDs
      $ids = wp_list_pluck( $search_results, 'ID' );

      // Extend post object connection
      // https://github.com/wp-graphql/wp-graphql/blob/develop/docs/source/extending/connections.mdx
      $resolver   = new PostObjectConnectionResolver( $source, $args, $context, $info, array('some_post_type', 'some_other_post_type') );
      $resolver->setQueryArg('post__in', $ids );
      $connection = $resolver->get_connection();

      return $connection;
    },
    'resolveNode' => function( $id, $args, $context, $info ) {
      return DataSource::resolve_post_object( $id, $context );
    },
    'connectionArgs' => [
      'search' => [
        'name' => 'search',
        'type' => 'String',
        'description' => __( 'Show Posts based on a keyword search', 'wp-graphql' ),
      ],
    ]
  ];
  register_graphql_connection( $config );
};
```

The above script lets you run the following query:

```
query MyQuery {
  myCustomGraphqlConnection(where: {search: "blu"}) {
    edges {
      node {
        slug
      }
    }
  }
}
```

Which will return the slugs every post which is somehow related to the word `blu`.

---

I've though about using `WPGraphQL\Data\DataSource::resolve_post_objects_connection` method, but I guess it runs a query as well.

## How can you properly format the query result?

More explicitely: **What if I have already the query results and I only want to convert them in a way that WPGraphQL can use them?**

Something like:
```
WPGraphQL\Data\DataSource::convert_query_result_to_post_objects_connection
```

---

### Side note:
I haven't been able to use the example code directly: meaning the double backslash in `\\WPGraphQL\\Data\\Connection\\PostObjectConnectionResolver` was generating a error.  I've seen someone has already [pushed an update](https://github.com/wp-graphql/wp-graphql/commit/98c4bf6aca08b09d71af9caad627893aba91a325), but left some examples with the broken syntax (see https://github.com/wp-graphql/wp-graphql/blob/develop/docs/source/extending/connections.mdx#custom-connection-resolvers).

**Comment by a-barbieri** [comment]
I was looking at the `PostObjectConnectionResolver` and I was thinking about extending it and overriding the `get_query` method:

https://github.com/wp-graphql/wp-graphql/blob/4b62ca5b06fd58edb1797621cba2f6d2ddce462d/src/Data/Connection/PostObjectConnectionResolver.php#L69-L74

and I would replace the WP_Query at line 73 with the Relevanssi suggested code:

```php
$query = new WP_Query();
$query->parse_query( $this->query_args );
$results = relevanssi_do_query( $query );
return $results;
```

As the author of Relevanssi [says](https://www.relevanssi.com/user-manual/using-relevanssi-outside-search-pages/): 
> Notice that the code doesn’t do `$query = new WP_Query( $args );`, because that runs the query. If you create the object without parameters and use `parse_query()` instead, the query won’t be run, which is a small performance advantage.

Would this be ok?

**Comment by a-barbieri** [comment]
So, I updated the code but the query **doesn't return anything.** 

```php
use WPGraphQL\Data\DataSource;
use WPGraphQL\Data\Connection\PostObjectConnectionResolver;


add_action( 'graphql_register_types', 'register_my_custom_graphql_connection', 99 );

function register_my_custom_graphql_connection() {

  class RelevanssiConnectionResolver extends PostObjectConnectionResolver {
    /**
     * @return \WP_Query
     */
    public function get_query() {
      $query = new \WP_Query();
      $query->parse_query( $this->query_args );
      $search_results = relevanssi_do_query( $query );
      return $search_results;
    }
  }

  $config = [
    'fromType' => 'RootQuery',
    'toType' => 'Post',
    'fromFieldName' => 'myCustomGraphqlConnection',
    'connectionTypeName' => 'PostsFromMyCustomGraphqlConnection',
    'resolve' => function( $id, $args, $context, $info ) {
      $resolver = new RelevanssiConnectionResolver( $source, $args, $context, $info, array('some_post_type', 'some_other_post_type') );
      return $resolver->get_connection();
    },
    'resolveNode' => function( $id, $args, $context, $info ) {
      return DataSource::resolve_post_object( $id, $context );
    },
    'connectionArgs' => [
      's' => [
        'name'        => 's',
        'type'        => 'String',
        'description' => __( 'Show Posts based on a keyword search', 'wp-graphql' ),
      ],
    ]
  ];

  register_graphql_connection( $config );
};
```

I guess the objects coming from `new WP_Query()` and `relevanssi_do_query()` are different. 

See the method `relevanssi_do_query` [here](https://github.com/msaari/relevanssi/blob/ac50b936773ec910d135298494876d4403c6f33b/lib/search.php#L830)

### Is there anyway I can make use of it or do I need to go back to the duplicate query?

If could debug the GraphQL queries I might understand what's wrong. Unfortunately errors are swallowed everytime I click play on the GraphiQL editor: I just get `internal server error` and no trace in the logs.

**Comment by a-barbieri** [comment]
I've noticed one downside of doing a second query: **Relevanssi** returns an array of **posts ordered by relevance**, which **is lost** when I run the query through **WPGraphQL**.

**Comment by a-barbieri** [comment]
I've done a little gist if anyone needs the plugin and/or want to expand it.

https://gist.github.com/a-barbieri/7802dee5938fee53e6f1a5cbd6f81cca

**Comment by leovant** [comment]
I have a similar issue. Tried to use the gist created by @a-barbieri but it seems like the get_query inside the child class does not execute (my logs inside there do not execute).

**Comment by jasonbahl** [comment]
@a-barbieri this is interesting. I've not used Relevanassi before, so I'm not sure the best way to approach all this. I will read through this all and see if I have anything to add to the conversation. 

Thanks for using WPGraphQL and extending it to work with the greater WordPress ecosystem!!

**Comment by a-barbieri** [comment]
Hey @jasonbahl , happy to be helpful. :)

I've been able to prevent losing the order within one query. See below: 
```
//...
    $search_results = relevanssi_do_query( $query );

    // Get an array of IDs and add it to the query arguments
    $ids = wp_list_pluck( $search_results, 'ID' );

    // Update the query to ensure results correspond to Relevanssi ones
    $this->query_args['post__in'] = $ids;

    // Keep Relevanssi order
    $this->query_args['orderby'] = 'post__in';
//...
```

Find the code [on the updated gist](https://gist.github.com/a-barbieri/7802dee5938fee53e6f1a5cbd6f81cca#file-relevanssi-connection-resolver-php-L19-L20)

Now I have few other issues I'd like to solve, but it's best to open a new thread and close the current one.

**Comment by jasonbahl** [comment]
Oh great. Perfect! Look forward to seeing what else you have!

**Comment by jasonbahl** [comment]
@a-barbieri do you have a repository for the plugin? I couldn't find it

**Comment by a-barbieri** [comment]
Nope, unfortunately I have only that [gist](https://gist.github.com/a-barbieri/7802dee5938fee53e6f1a5cbd6f81cca). This is due to the fact I haven't automated the Custom Post Type recognition which needs to be done directly on the code. 

If you want to try it out:
1. setup a new Wordpress application
1. create a directory /wp-content/plugins/wp-graphql_relevanssi_plugin and copy/paste all files of the gist
1. copy/paste [Relevanssi](https://www.relevanssi.com/), [WP GraphQL](https://github.com/wp-graphql/wp-graphql),  [WP GraphiQL](https://github.com/wp-graphql/wp-graphiql) inside /wp-content/plugins
1. enable all plugins
1. create some posts (and `document` custom post types) containing some text
1. go to Relevanssi and build the index
1. go to WP GraphiQL and paste this query:

```
{
  documentsSearch(where: {s: "lorem"}) {
    edges {
      node {
        slug
      }
    }
  }
}
```

If there's any lorem it will be found.
