### ISSUE TITLE
Remove @access from docblocks

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#1192]
The `@access` tag in Doc blocks is unnecessary. 

See: https://github.com/wp-graphql/wp-graphql/pull/1163#discussion_r384151112

🚀 We should remove all instances of `@access` from Doc blocks

**Comment by izzygld** [comment]
@jasonbahl can you check why some tests are failing?

**Comment by jasonbahl** [comment]
closed by #1194

**Comment by jasonbahl** [comment]
@izzygld I'm re-running the tests. I don't see anything in your PR that should affect execution, so tests _should_ be fine. Could've been a hiccup in the test runner. Every once in a while it fails to download a dependency like WordPress from Docker Hub, or WP CLI, or whatever. Re running the tests now.

**Comment by jasonbahl** [comment]
@izzygld looks like there actually is a failure with some of the user tests 🤔 

I wonder if I missed this on another PR. 👀
