### ISSUE TITLE
Internal Server Error | No Schema Available

### ISSUE THREAD

**Issue by minecraft00z** [wp-graphql/wp-graphql#1195]
After installing and activating WPGraphql plugin on my Wordpress site, when I visit https://mysite.com/graphql, I get Internal Server Error.

![error](https://user-images.githubusercontent.com/52003320/77111330-d3f0c400-6a2f-11ea-8cc9-2615e6e08207.jpg)

I also installed WPGraphiQL plugin, but when I navigate to the GraphiQL section, it shows "No Schema Available".

![no_schema](https://user-images.githubusercontent.com/52003320/77111534-2f22b680-6a30-11ea-935c-ac6802a05bce.png)

So, I'm stuck at this point. As suggested in a similar issue #295, I tried to disable all other plugins and my custom child theme, but that didn't help. It looks like something is wrong with my setup. I'm running Wordpress in a Docker container. 

- Wordpress 4.9.13
- MySQL 5.7
- PHP 5.6.23
- I don't have WooCommerce installed
- I don't have  wp-graphql-insights installed too

Where should I look for more details on this error?

**Comment by jasonbahl** [comment]
@minecraft00z WPGraphQL requires PHP 7.0+. WordPress also recommends PHP 7.0+ as PHP 5.6 end of life was in 2018.

**Comment by minecraft00z** [comment]
Thanks!

**Comment by xuala69** [comment]
Getting the same error. 

> PhP version is 7.4.15 (Supports 64bit values)

> Server architecture Linux 4.19.0-14-cloud-amd64 x86_64

> Wordpress version 5.7

The error goes away when I disable the plugin "WPGraphQL JWT Authentication" and re appears when I activate it. Any help would be appreciated.

**Comment by pedapudibhargav** [comment]
Same issue when used along with "WP GraphQL Gutenberg"
