### ISSUE TITLE
Feature Request: Delete Posts in Bulk

### ISSUE THREAD

**Issue by kellenmace** [wp-graphql/wp-graphql#1200]
In the wp-admin, WordPress makes it possible to delete posts in bulk. It would be nice to also provide that functionality in WPGraphQL. Then apps that require similar bulk deletion functionality would have support for it.

WPGraphQL currently supports deleting posts individually, like this:

```graphql
mutation deletePost {
  deletePost(input: {
    clientMutationId: "123"
    id: "cG9zdDo0NDA="
    forceDelete: true
  }) {
    clientMutationId
    deletedId
    post {
      postId
    }
  }
}
```

It seems like a bulk deletion mutation could look very similar, like this:

```graphql
mutation deletePosts {
  deletePosts(input: {
    clientMutationId: "123"
    ids: ["cG9zdDo0NDA=", "cG9zdDo0NDE=", "cG9zdDo0NDI="]
    forceDelete: true
  }) {
    clientMutationId
    deletedIds
    posts {
      nodes {
        postId
      }
    }
  }
}
```

## Considerations
There are lots of factors to consider with this feature, such as this one related to permissions that @jasonbahl noted:

> What if you attempt to delete posts 1,2,3,4,5 and you only have permission to delete 1,3,5?

Maybe in that case, the `deletedIds` and `posts` in the response would only reflect the 1, 3 and 5 posts that were deleted, but an error would also be returned indicating the reason why posts 2 & 4 could not be deleted.

## Comparison with other GraphQL APIs
I think it would be wise to look at how other GraphQL APIs out there that support bulk deletion have implemented it, and steal ideas from those projects. I'm excited to hear ideas on how this could best be implemented in WPGraphQL.

**Comment by CodeProKid** [comment]
FWIW, I think we should support this with the existing `deletePost` mutation, or replace it with a `deletePosts` mutation. I think we only need a single mutation to do this.

**Comment by jasonbahl** [comment]
@CodeProKid so the payload you get in response is my concern. 

If you delete many things, what you need in response to the mutation would be different than if you deleted one thing. 

At the moment, client applications can technically already do bulk deletes via bulk mutations. 

You could have a checkbox that adds many IDs to an array, and then send an array of `deletePost` mutations like so (a bit pseudo code): 

```
[
	{
		"query": "
                  mutation {
                    deletePost(input: {clientMutationId: "Delete", id: "someId"}) {
                      clientMutationId
                      deletedId
                      post {
                        id
                        title
                      }
                    }
                  }
                 ",
           "variables": $variables
         },
	{
		"query": "
                  mutation {
                    deletePost(input: {clientMutationId: "Delete", id: "someId"}) {
                      clientMutationId
                      deletedId
                      post {
                        id
                        title
                      }
                    }
                  }
                 ",
          "variables": $variables
	}
]
```

I think to support something like `deletePosts` etc, we'll need to consider what payloads are necessary. 

When you delete posts, many things happen in the graph. For example, term counts change, author counts change, etc. 

When you delete one post, you get that one post back in the payload and can ask for connections from that, such as the Post Author or Categories, etc. 

We probably need to consider what else needs to be returned in the initial payload for individual `deletePost` mutations, as well as bulk. 

🤔 

Things get real weird when you try to support bulk, but the user tries to delete 5 posts and only has permission to delete 4 of them. What happens to the 5th? You reject the full bulk mutation? Or do you delete 4, leave the 5th and somehow let the user know the 5th didn't delete?

Lots to think about here.

**Comment by CodeProKid** [comment]
@jasonbahl yeah I hadn't considered that 🤔 you are right, there's a lot to consider with what is returned from the mutation to properly invalidate the cache in the client.

There's definitely somewhat of a balance there though, where the client needs to assume some responsibility of doing that on their own, or maybe some lib to be a middleware between your app and WPGraphQL can be used to do it.

Definitely not as straight forward as I first thought though 🤔 this is great context to have on this ticket.

**Comment by kellenmace** [comment]
Thanks for the thoughtful comments on this one, @jasonbahl & @CodeProKid.

For anyone coming across this issue thread –
If you want to be able to delete multiple posts in a single HTTP request right now, it's possible using something like Apollo Client's [apollo-link-batch-http](https://www.apollographql.com/docs/link/links/batch-http/) middleware. With that in place, you can fire off multiple `deletePost` mutations in rapid succession, and have them all sent across the wire in a single HTTP request, which was what @jasonbahl & @CodeProKid were alluding to in some of their comments above.

**Comment by justlevine** [comment]
Ignoring the payload implications, I wonder whether this would belong in WPGraphQL core regardless.

> In the wp-admin, WordPress makes it possible to delete posts in bulk. 

While this is true, the underlying WP api is a `foreach()` loop calling `wp_delete_post()`. We have API parity, and using batching gives us 'feature parity' i.e. all this happening in a single server request. Since there is a client solution, it seems to me a better home than a server-side shim that just loops over the same `mutateAndGetPayload` callback as the existing `deletePost` mutation (which is also simple enough for a user to implement themselves with `register_graphql_mutation()` if they _really_ feel a separate mutation is necessary for their flow).


I suggest we should close this as `wontfix`.

**Comment by jasonbahl** [comment]
@justlevine I agree. I think I still stand by [my comments](https://github.com/wp-graphql/wp-graphql/issues/1200#issuecomment-620125279) above. There's a lot of complexity to consider to support bulk mutations at the GraphQL Schema level. If there was a very compelling case in the future, we could re-open, but I think this can be closed as it is already possible via the client as demonstrated above.
