### ISSUE TITLE
Access-Control-Allow-Origin is hard-coded to *, prevents browsers from including credentials

### ISSUE THREAD

**Issue by ravinggenius** [wp-graphql/wp-graphql#1203]
We have a static site built with Gatsby which uses WordPress as a backend CMS. The public frontend is served from a different domain than the CMS. Our client wants to use the preview feature while editing pages in WordPress, so I wrote some code to query the server for the most recent revision. WordPress requires authentication to verify a nonce that it creates. (We send this in the `X-WP-Nonce` header, which isn't whitelisted, but we were able to work around.) However the browser won't send cookies with the request for preview data because the `Access-Control-Allow-Origin` header is set to `*`. We traced this header back to https://github.com/wp-graphql/wp-graphql/blob/v0.4.3/src/Router.php#L260.

We're using v0.4.3 on AWS, though I notice the header is still set in current master. I'm not sure what would be an ideal solution, but would you consider adding a configuration setting to override the `*` with a specific origin? Or not setting this header at all?

**Comment by jasonbahl** [comment]
@ravinggenius you might want to check out @kidunot89 wp-graphql-cors: https://github.com/funkhaus/wp-graphql-cors

> The primary purpose of this plugin is to make the WP GraphQL plugin authentication "just work". It does this by allowing you set the CORS headers that GraphQL will accept, which means that WordPress's default authentication cookies will be accepted.

> This means that if a user is logged into WordPress, they will be able to see things like draft and private pages/posts via GraphQL.

**Comment by ravinggenius** [comment]
We managed to find a work-around by patching out the `Access-Control-Allow-Origin` line and setting other needed headers with Apache.

**Comment by jasonbahl** [comment]
For context, in case anyone else comes across this: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials#What_went_wrong

----

@ravinggenius by "patch" do you mean you filtered it? Or did you actually have to modify the core WPGraphQL code? If the latter, we should fix that. 

I do think that `Access-Control-Allow-Origin: *` is the most sensible default, as it allows the API to be interacted with from any client, such as web, native mobile, etc, but we should ensure that this is easily filterable for folks that want to change it to something else, like one specific allowed origin.

**Comment by ravinggenius** [comment]
By "patch" I mean we applied a patch via composer. The patch removed the line and is automatically applied when the wp-graphql package is installed.

**Comment by ThyNameIsMud** [comment]
@jasonbahl The issue arises when the webserver is configured to set CORs headers and the plugin still tells PHP to send them out. You get a response that shows two `Access-Control-Allow-Origin: *` and Chrome rejects the request.

Our only options are removing the header from the `Router.php` like @ravinggenius notes with a patch, or add a filter to remove them like the plugin you recommended.

Our recommendation would have an option to tell the plugin to not set the CORs header. Even if headers were on by default it would be nice to opt-out of them.

**Comment by jasonbahl** [comment]
Ok, I just confirmed that this is filterable: https://github.com/wp-graphql/wp-graphql/blob/v0.4.3/src/Router.php#L287 so folks can customize the default headers. 

Looks like the WPGraphQL Cors plugin makes use of this filter here: https://github.com/funkhaus/wp-graphql-cors/blob/12f74fc5aa6000e504177437ccb21ac0fbcedd3d/includes/class-wp-graphql-cors.php#L80
