### ISSUE TITLE
Fix description for Post Types and Taxonomies added to the Schema

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#1204]
Currently, when adding a Post Type or Taxonomy to the WPGraphQL Schema, the root field for the single node entry point isn't documented properly. The field documentation says `A object`. 

It should instead say `A $post_type Object`. Additionally, it should probably include the description of the Post Type as well. 

This looks like the erroneous line: https://github.com/wp-graphql/wp-graphql/blob/develop/src/Type/Object/RootQuery.php#L431

Instead of `%` it should be `%s`. That will make it go from `A object` to `A post object`, but we should also consider adding the post type description.

Maybe something like: `sprintf( __( 'A %1$s object. %2$s', 'wp-graphql' ), $post_type_object->graphql_single_name, $post_type_object->description ),`

**Comment by jacobarriola** [comment]
@jasonbahl can I take a stab at this?

**Comment by jasonbahl** [comment]
@jacobarriola that would be great! Please do. 🙏

**Comment by bahiirwa** [comment]
The same behavior is noticed with taxonomies. See image below.

![Screenshot 2020-04-09 at 18 54 37](https://user-images.githubusercontent.com/7713923/78916075-9c58c300-7a95-11ea-97ac-1445908464b2.png)

It also doesn't make grammatical sense when article "a" when working with vowel beginning words like Event/Apple. So we would end up with a statements saying "A event object". See same image above.

Suggestion
1. Make provision for an object description through args like `$args['graphql_object_description']` seeing that in some cases `$args['description']` is left empty.
2. Remove 'A' before the "%1$s".

**Comment by jasonbahl** [comment]
@bahiirwa  We could word it like `An object of the $tyepname Type`

**Comment by jasonbahl** [comment]
@jacobarriola @bahiirwa submitted PR #1232 for this. If you have thoughts on further improving the Schema docs, further PRs welcome too 😄
