### ISSUE TITLE
uri field should have a slash at the beginning instead of the end

### ISSUE THREAD

**Issue by TylerBarnes** [wp-graphql/wp-graphql#1206]
Right now the uri field returns something like `post/12/`. In the browser that's a relative path. For example when on `site.com/about` and clicking `<a href="post/12/">post 12</a>`, that would link to `site.com/about/post/12`.
This should be an absolute path. For example `<a href="/post/12">post 12</a>` would link to `site.com/post/12`.

**Comment by TylerBarnes** [comment]
Ok, I think we should have a slash on both ends actually. This is what WP core does.
Also see https://tommcfarlin.com/trailing-slash-in-wordpress/

**Comment by curtisbelt** [comment]
Concerning trailing slash -- to be consistent with how WordPress handles this, I think it should be based on if the permalink structure has a trailing slash or not, see [user_trailingslashit](https://developer.wordpress.org/reference/functions/user_trailingslashit/).

**Comment by CodeProKid** [comment]
Closing this, as it was completed in #1208
