### ISSUE TITLE
Preview abstraction field

### ISSUE THREAD

**Issue by TylerBarnes** [wp-graphql/wp-graphql#1207]
When using revisions for previews, it's a bit tricky since brand new posts that have yet to be published aren't revisioned. I think a preview field would be useful here. It could either be a root field or a field on previewable post types. It would return a single connected node which would be the latest non-autosave revision OR if it's a brand new post it would return the initial draft.
In the classic editor and [in Gutenberg](https://github.com/WordPress/gutenberg/pull/12097), initial previews on new posts work by saving a draft and using the draft in the preview. 

So for example:

```graphql
{
  # this will either return a draft or the latest revision.
  # In both cases created by clicking the "Preview" button
  preview(id: 3424, id_type: DATABASE_ID) {
    title
    content
  }

  post(id: 34, id_type: DATABASE_ID) {
    preview {
      title
      content
    }
  }
}
```

I think from a consumer it would be nicest to be able to mix the two, but I'm not sure if it's good API design or not.

```graphql
  post(id: 34234, id_type: DATABASE_ID, view: PREVIEW) {
    title
    content
  }
```

**Comment by TylerBarnes** [comment]
Ok, I was confused about the draft vs revision thing. There is always a revision even for new posts. It would still be cool to have this abstraction where we know we're getting the "preview" you would get in vanilla WP.

**Comment by jasonbahl** [comment]
We discussed and since you can pass a Draft Post ID to the `{post(id: $id) { ...fields }}` you should use that entry.
