### ISSUE TITLE
error inmutation

### ISSUE THREAD

**Issue by IndraS1998** [wp-graphql/wp-graphql#1210]
mutation {
  createTodo(text: "item2") {
    id
    text
    completed
  }
}
res

  "data": {
    "createTodo": null
  },
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Todo.completed.",
      "locations": [
        {
          "line": 5,
          "column": 5
        }
      ],
      "path": [
        "createTodo",
        "completed"
      ]
    }
  ]
}

**Comment by jasonbahl** [comment]
@IndraS1998 I'll need a lot more information to help here. 

From what I can tell, based on the error message: 

> "message": "Cannot return null for non-nullable field Todo.completed.",

It looks like you've registered a field `completed` on the `Todo` type as a `nonNull` field, but your resolver has it returning an empty value. 

Make sure your resolver is returning a non-null value if the field is registered as a nonNull field.

**Comment by IndraS1998** [comment]
hey! i'm actually new in graphql and i'm following a tutorial. the server keeps sending this same error
Here below is the code ive written so far

**Comment by IndraS1998** [comment]
const Todo = mongoose.model('Todo',{
   text: String,
   complete: Boolean,
});

const typeDefs = `
  type Query {
    hello(name: String): String!
    todos: [Todo]
  }
  type Todo {
    id: ID!
    text: String!
    completed: Boolean!
  }
  type Mutation {
    createTodo(text: String!): Todo
  }
`;

const resolvers = {
    Query: { //essentially running get requests
        hello: (_, { name }) => `Hello ${name || 'World'}`,
        todos: Todo.find()
    },
    Mutation : { // all the other http verbs over here
        createTodo: async (_,{ text })=>{
            const todo = new Todo({text ,completed: false}); // the todo class was essentially created in typeDefs
            await todo.save(); /* saving the todo ive created to the db*/
            return todo;
        }
    }
};
const server = new GraphQLServer({ typeDefs, resolvers });
mongoose.connection.once('open',()=>{
    server.start(() => console.log('Server is running on localhost:4000'));
});

**Comment by IndraS1998** [comment]
please yourr help will be greatly appreciated

> @IndraS1998 I'll need a lot more information to help here.
> 
> From what I can tell, based on the error message:
> 
> > "message": "Cannot return null for non-nullable field Todo.completed.",
> 
> It looks like you've registered a field `completed` on the `Todo` type as a `nonNull` field, but your resolver has it returning an empty value.
> 
> Make sure your resolver is returning a non-null value if the field is registered as a nonNull field.
