### ISSUE TITLE
Argument 1 passed to WPGraphQL\\Model\\Post::__construct() must be an instance of WP_Post, null given

### ISSUE THREAD

**Issue by riccardolardi** [wp-graphql/wp-graphql#1220]
- ACF Pro
- Custom Post Types UI
- wp-graphql-acf
- wp-graphql-custom-post-type-ui

When I run (while "acts" is a custom post type and "act_field" is a advanced custom field, image is an ACF image field):

```
{
  acts {
    nodes {
      title
      act_field {
        description
        media {
          type
          image {
            id
          }
          youtube
          vimeo
        }
      }
    }
  }
}
```

I get internal server error:

```
{
  "errors": [
    {
      "debugMessage": "Argument 1 passed to WPGraphQL\\Model\\Post::__construct() must be an instance of WP_Post, null given, called in /Users/riccardo/Sites/sommernachts-ball-wp/wp-content/plugins/wp-graphql/src/Data/Loader/PostObjectLoader.php on line 154",
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 9,
          "column": 11
        }
      ],
      "path": [
        "acts",
        "nodes",
        0,
        "act_field",
        "media",
        0,
        "image"
      ]
    }
    ]
}
```

When I leave the "images" field away, I get no error so it seems related to that.

Sorry for not so reproductive way of posting this, still hope it's useful.

**Comment by a-barbieri** [comment]
Can you post the version of your plugins?

I had a similar issue when I upgraded WP Graphql to `0.8`. It contains some breaking. Maybe that's related to your issue.

**Comment by MHeitsch** [comment]
@riccardolardi I had the same problem and changed the following lines in src/Data/Loader/PostObjectLoader.php lines 148 and following from:
`/**
			 * Once dependencies are loaded, return the Post Object
			 */
			$loaded_posts[ $key ] = $load_dependencies->then(
				function() use ( $post_object ) {
						$post = new Post( $post_object );
						if ( ! isset( $post->fields ) || empty( $post->fields ) ) {
							return null;
						}
						return $post;
				}
			);`

to `/**
			 * Once dependencies are loaded, return the Post Object
			 */
			$loaded_posts[ $key ] = $load_dependencies->then(
				function() use ( $post_object ) {
					if($post_object){
						$post = new Post( $post_object );
						if ( ! isset( $post->fields ) || empty( $post->fields ) ) {
							return null;
						}
						return $post;
					}
					return null;
				}
			);`

**Comment by CodeProKid** [comment]
@mrmagoon this should be fixed in the next release from the changes here: https://github.com/wp-graphql/wp-graphql/pull/1281 The model layer no longer does type checking on the incoming object, so it should just return null without throwing the error.

**Comment by simplenotezy** [comment]
I am getting this error, not sure if it is related:

`Argument 1 passed to WPGraphQL\\Extensions\\Polylang\\PostObject::WPGraphQL\\Extensions\\Polylang\\{closure}() must be an instance of WPGraphQL\\Model\\Post, instance of WPGraphQL\\Model\\PostType given, called in /Users/mf/Projects/washworld/wp-content/plugins/wp-graphql/src/Utils/InstrumentSchema.php on line 151`

Happened after adding:

	translations {
		link
		language {
			locale
		}
	}

To my `page` query.

**Comment by evangelinepapanicola** [comment]
I'm also experiencing this issue, when querying `parent` on a subpage that doesn't exist:

```graphql
query MyQuery {
  page(id: "join-us/studio", idType: URI) {
    parent {
      node {
        id
      }
    }
  }
}
```

result:
```
"debugMessage": "Argument 1 passed to WPGraphQL\\Connection\\PostObjects::WPGraphQL\\Connection\\{closure}() must be an instance of WPGraphQL\\Model\\Post, instance of WPGraphQL\\Model\\PostType given, called in /public_html/wp-content/plugins/wp-graphql/src/Type/WPConnectionType.php on line 452",
```

**Comment by ttstauss** [comment]
Hello, hoping someone can point me in the right direction. Been using WPGraphQL without issue and it's been awesome. I recently set up ACF and WPGraphQL for ACF along with a custom ACF block (a simple relationship field). When I attempt to run a query on blocks, I'm getting the following `debugMessage`: `DOMDocument::loadHTML(): Argument #1 ($source) must not be empty`. The error only happens when I actually add the custom ACF block to a page. Any ideas?

**Comment by jasonbahl** [comment]
I'm unable to reproduce this with the given information. 

I'm going to close this, but if this is still relevant, please open a new issue with proper steps to reproduce so we can take another look. 🙏
