### ISSUE TITLE
Speed up response time

### ISSUE THREAD

**Issue by IRediTOTO** [wp-graphql/wp-graphql#1222]
Hello, can you please make response time faster? I tried in a blank WP with 10 products but time response up to 500ms :( 
This too longgggg, I think. 
I tried plugin API cache WP REST Cache but look like it not work with wp graphql. 
Thank you

**Comment by izzygld** [comment]
@warcraft14115 not sure how you are implementing your data,

have you tried apollo cache?

take a look at [https://www.apollographql.com/blog/graphql-caching-the-elephant-in-the-room-11a3df0c23ad](https://www.apollographql.com/blog/graphql-caching-the-elephant-in-the-room-11a3df0c23ad)

**Comment by CodeProKid** [comment]
@warcraft14115 can you give some more info on the query you are making that is taking this long? Could you also let us know what version of the plugin you are on, and how you are making this query (ex. from the client, through WPGraphiQL, From another server, etc...).

**Comment by dpacmittal** [comment]
@CodeProKid Is there a hook/filter which runs right before returning the response? I'd like to cache queries using transients api. I've looked all over docs and github but couldn't find anything.

**Comment by dpacmittal** [comment]
Nvm, I just found out about `graphql_execute` and `graphql_request_results`. Now just need to find a way to short circuit the request.

**Comment by izzygld** [comment]
@dpacmittal did you ever try working on using `graphql_execute` and `graphql_request_results` to cache queries using transients api?

**Comment by dpacmittal** [comment]
@izzygld I am using `do_graphql_request` and `graphql_return_response` hooks and it works great. I'm not using transients api though, just storing in redis.

**Comment by izzygld** [comment]
can you share an example of how you are doing it?

Are you wrapping the whole wpgraghql into a `do_graphql_request` or just specific parts?

**Comment by dpacmittal** [comment]
@izzygld You should use https://github.com/valu-digital/wp-graphql-cache. If you still want to use a custom solution (like I did because I wanted to do stale-while-revalidate), here it is - https://gist.github.com/dpacmittal/e837e2a36714c6d1a279fbd5999debd0

**Comment by jasonbahl** [comment]
I'm going to transfer this to a Discussion. I think it's a good discussion and a lot of ways we can go about caching requests, but not an actionable issue on its own.
