### ISSUE TITLE
error if featured Image is not set

### ISSUE THREAD

**Issue by vana-dev** [wp-graphql/wp-graphql#1223]
my post query:
`query getPost($slug: String!){
  postBy(slug: $slug) {
    id
    slug
    title
    excerpt
    date
    categories {
      nodes {
        id
        name
        slug
      }
    }
    featuredImage {
      mediaItemUrl
    }
    post_settings {
      onlyForUsers
    }
    author {
      lastName
      firstName
      avatar {
        url
      }
      slug
    }
    content
  }
}
`

if featured Image in post is not set, graphql returns error 

`"errors": [
    {
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 15,
          "column": 5
        }
      ],
      "path": [
        "postBy",
        "featuredImage"
      ]
    }
  ],`

instead it should return null to avoid errors

**Comment by jasonbahl** [comment]
@vana-dev the featuredImage will return a null when there is no image set for the post. 

Can you check behind the scenes to see if you post has an ID set for the thumbnail on the post, but it's an invalid ID? I think the error is likely that you have a thumbnail set, but it's been deleted since being associated with the post?

**Comment by jasonbahl** [comment]
Here's an example of querying a post with no featuredImage and getting a null and no error. 

![Screen Shot 2020-04-06 at 8 11 28 AM](https://user-images.githubusercontent.com/1260765/78567639-3bec2c00-77de-11ea-89a7-ebdb5e7e88d1.png)

**Comment by vana-dev** [comment]
![Zrzut ekranu 2020-04-6 o 20 06 02](https://user-images.githubusercontent.com/884763/78590397-12fd8280-7842-11ea-8223-b604d0dae9f3.png)

**Comment by vana-dev** [comment]
debug:
![Zrzut ekranu 2020-04-12 o 10 07 45](https://user-images.githubusercontent.com/884763/79064034-bc5ed100-7ca5-11ea-8310-097e314d68c1.png)

**Comment by izzygld** [comment]
I’ve actually come across this myself when the there’s bad data.
A quick fix would be, to set a new featured image and remove it.

We should look into returning null when the `featuedImage` value is a non-image.

**Comment by jasonbahl** [comment]
I've confirmed that in v0.10.1 this is no longer an issue. 

Here's an example. 

I set a featured image and queried for the post and its featured image like so: 

![Screen Shot 2020-07-01 at 3 51 11 PM](https://user-images.githubusercontent.com/1260765/86294976-d926e880-bbb2-11ea-8c7e-268f37497119.png)

Then, I went to the media library and deleted the image, but did NOT update the post. So the post still has a reference to the deleted image ID. You can see the reference to `_thumbnail_id:660` in the meta for post 657 .

![Screen Shot 2020-07-01 at 3 56 32 PM](https://user-images.githubusercontent.com/1260765/86295287-78e47680-bbb3-11ea-8e7a-c4e2222713de.png)

I re-queried and this time, featured image returns null with no errors: 

![Screen Shot 2020-07-01 at 3 51 33 PM](https://user-images.githubusercontent.com/1260765/86295028-f5c32080-bbb2-11ea-970a-baef4db664af.png)

**Comment by AmAnpreet235** [comment]
![Screenshot (1376)](https://user-images.githubusercontent.com/76172052/231371197-6f073c01-d700-4aba-ac65-8b50f08e1f7e.png)
please help me with this

**Comment by jasonbahl** [comment]
@AmAnpreet235 there's no guarantee that there will be a featuredImage, so you need to ensure there is one before trying to render it. 

Something like: 

```
{ post?.node?.featuredImage?.node && <img src={post.node.featuredImage.node.sourceUrl} /> }
```

This will only output the `<img>` if there's a featuredImage node returned. For the cases where there is no featured image, no image will be output. 

Of course, you could also maybe output a default image if no featured image were set, or something similar to that as well.

The problem though, is that you're trying to use the `url` of the featuredImage even when the featuredImage doesn't exist (which is common as many posts will not have one set)
