### ISSUE TITLE
Joined queries return only two levels of sub categories but on single query works fine

### ISSUE THREAD

**Issue by endzi007** [wp-graphql/wp-graphql#1238]
Hello, 
I've recently started using graphql with WordPress and I'm stuck with this issue. 
For example I have this hierarchy of categories: seminarski-> bezbjednost -> kriminalistika 
When I run this query I receive categories as expected: 
![q1](https://user-images.githubusercontent.com/20710311/79206909-4e024600-7e40-11ea-8a85-cf5c9efc585e.JPG)

But if I combine queries, for example I add to fetch pages too, I get only first two levels of categories:
![q2](https://user-images.githubusercontent.com/20710311/79207207-b2bda080-7e40-11ea-886c-4417299b0ef6.JPG)

As you can see, the "kriminalistika" is missing and I'm using same query like before, am I missing something or is this a bug?

**Comment by justlevine** [comment]
Seems to be working fine now in 1.8.1

![image](https://user-images.githubusercontent.com/29322304/168146037-bb732cc9-185d-4b09-a1e7-c153e798f67f.png)

**Comment by jasonbahl** [comment]
Closing as this appears to be fixed as demonstrated by @justlevine.
