### ISSUE TITLE
Fix avatar resolution on UserType

### ISSUE THREAD

**Issue by BE-Webdesign** [wp-graphql/wp-graphql#124]
Currently we are returning false if a user does not have an avatar.  I think we should return null for the field to keep things consistent with the rest of the API.  Is there something in the history where false makes more sense here?

**Comment by jasonbahl** [comment]
Null makes more sense. . .probably was just moving fast when I implemented.

**Comment by jasonbahl** [comment]
I have a PR coming to actually fix the size input as well

**Comment by BE-Webdesign** [comment]
Okay sounds good.

**Comment by BE-Webdesign** [comment]
We are also checking $avatar->{field_name}.  `get_avatar_data()` returns an array so we want to do array access like `$avatar[ $field_name ]`.

**Comment by BE-Webdesign** [comment]
Fixed by #122
