### ISSUE TITLE
pagination issue on posts when order by custom field

### ISSUE THREAD

**Issue by safouane-ahmed-salah** [wp-graphql/wp-graphql#1243]
I am trying to order custom post type using **meta_key_value**

Here is what I added
```
add_filter( 'graphql_register_PostObjectsConnectionOrderbyEnum_config', function( $config ) {
	$config['values']['FEATURED'] = [
		'value'       => 'featured',
		'description' => __( 'Order by the featured', 'your-custom-plugin' ),
	];
	return $config;
});

add_filter( 'graphql_post_object_connection_query_args', function( $query_args, $source, $args, $context, $info ) {
    if(isset($query_args['orderby']['featured'])){
           $query_args['orderby'] = 'meta_value_num';
           $query_args['meta_key'] = 'listing_is_featured';
      });
    }
    return $query_args;
}, 10, 5 );
```

this does order the posts however similar posts returns back on the next pages on pagination

**Comment by CodeProKid** [comment]
I believe this is a known issue, needs to be reproduced though. @safwan39 could you add the version of WPGraphQL you are seeing this error on? And also the query you are using?

**Comment by safwan39** [comment]
> I believe this is a known issue, needs to be reproduced though. @safwan39 could you add the version of WPGraphQL you are seeing this error on? And also the query you are using?

version: 0.3.5
query: query MyQuery($endCursor: String!) {
  listings(first: 10, after: $endCursor, where: {orderby: {field: FEATURED}}) {
    pageInfo{
      endCursor
    }
    nodes {
      title
    }
  }
}

**Comment by andrewmumblebee** [comment]
Getting the same issue, trying to orderby a custom `datetime` value which is needed by our plugins.

Minimal reproduction for me that had issues.

1. Create an ACF datepicker field to register for meta value to sort by, i.e. `event_datetime`
2. Create a few posts with this field on so there is enough to paginate with.
3. Register graphql filter to allow for ordering by given field
```php
add_filter(
	'graphql_PostObjectsConnectionOrderbyEnum_values',
	function( $values ) {

		$values['EVENT_DATETIME'] = [
			'value'       => 'event_datetime',
			'description' => 'Datetime of the event.',
		];

		return $values;

	}
);

add_filter(
	'graphql_post_object_connection_query_args',
	function ( $query_args, $source, $args, $context, $info ) {
		if ( isset( $args['where']['orderby'] ) && is_array( $args['where']['orderby'] ) ) {

			foreach ( $args['where']['orderby'] as $orderby ) {

				if ( ! isset( $orderby['field'] ) || 'event_datetime' !== $orderby['field'] ) {
					continue;
				}

				$query_args['meta_key'] = 'event_datetime';
				$query_args['orderby']  = 'meta_value';
				$query_args['order']    = $orderby['order'];
			}
		}
	}
);

```
5. Run query (should work fine)
```graphql
  query PaginationQuery {
    posts(
      where: {orderby: {field: EVENT_DATETIME, order: DESC}}
      first: 5
    ) {
      pageInfo {
        endCursor
        startCursor
        hasNextPage
      }
      edges {
        node {
          title
        }
      }
    }
  }
```
6. Run query to get second page of results (should return some of the same results)
```
query PaginationQuery {
    posts(
      where: {orderby: {field: EVENT_DATETIME, order: DESC}}
      first: 5
      after: "CURSOR_VALUE"
    ) {
      pageInfo {
        endCursor
        startCursor
        hasNextPage
      }
      edges {
        node {
          title
        }
      }
    }
  }
```

Also seems to bug out with a JSON error sometimes where it seems to try to write a SQL query that assumes the meta key is a column of the `wp_posts` entry.

One of our archives is completely dependent on this type of sorting, as events may be in the future, using the publish date for this is not something we can do as that's used for queuing up posts for future publishing.

**Comment by justlevine** [comment]
I believe this case is tested as passing as of at least #2457
