### ISSUE TITLE
`Notice: Undefined property: WP_Post_Type::$graphql_single_name` for `nav_menu_item`

### ISSUE THREAD

**Issue by esamattis** [wp-graphql/wp-graphql#1256]
Comes from `src/Model/Post.php` line 155 using the develop branch.

![image](https://user-images.githubusercontent.com/225712/79951809-0ef87400-8482-11ea-85e0-8438500ee802.png)

Here's the query

```
{
  menuItems(where: {location: PRIMARY_NAVIGATION}) {
    nodes {
      id
    }
  }
}
```

Does seem to happen with every menu.

**Comment by jonshipman** [comment]
For me, I see it on line 429 and line 156 of ./src/Model/Post.php. If I error_log $this->data, it looks like nav_menu_item isn't getting assigned a graphql_single_name. The notice goes "away" if this dirty hack is applied:

```
if (empty($this->post_type_object->graphql_single_name)) {
         if ('nav_menu_item' === $this->post_type_object->name) {
                $this->post_type_object->graphql_single_name = 'menuItem';
         }
 }
```

If that block is added above those two lines, it's "technically" a fix. Though I'm curious why menuItem isn't getting the graphql_single_name. Might also be solved outside of core with a register_post_type_args filter for the nav_menu_item shortcode.

**Comment by jonshipman** [comment]
Just did a quick confirmation:

```
add_filter( 'register_post_type_args', function( $args, $post_type ) {
    if ( 'nav_menu_item' === $post_type ) {
        $args['graphql_single_name'] = 'menuItem';
    }

    return $args;
}, 10, 2 );
```

Will also fix the undefined property. I just stuck this in the functions.php of my theme.
