### ISSUE TITLE
Cant find ACF fields for the Front Page in WPGraphQL Editor in WP

### ISSUE THREAD

**Issue by aakash19090** [wp-graphql/wp-graphql#1263]
Hi @jasonbahl , i am unable to see the ACF fields in WPgraphQL Schema editor. I went through your video exactly https://www.youtube.com/watch?v=rIg4MHc8elg . Have all the needed plugins.

Note : I have created ACF fields for the "Page" not "Post" i.e. for my Front Page. Also selected that option "Show in GraphQL". But when i go in to that editor, don't know under which field the ACF fields would appear. Also i searched in the Documentation Explorer typing that fieldname, but its not producing results. Please guide out !

**Comment by jasonbahl** [comment]
@aakash19090 hello. 

Is your Location rule set to something like: `Page is equal to "Some Page"` or is your location rule set to the `Page` post type, like `Post Type is equal to "Page"`?

Currently, it's difficult to map the ACF location rules to the GraphQL Schema. The GraphQL Schema doesn't have a lot of context that WordPress has in the Admin. 

GraphQL exposes Types, for example Page, Post, etc. 

When assigning field groups to locations, such as `Page is equal to Home`, that's difficult to translate to the Schema. 

Should the field group be available in the Schema on _all_ pages? What if that page was deleted, where should the fields show in the Schema now?

----

Right now, the location rules must be set a bit more globally to work with WPGraphQL for ACF. 

I realize, that's not ideal for the editing experience though. 

So, I'm actually working on a new Interface to set the locations in the Schema explicitly. 

This will allow you to set the ACF Location rules to handle the editing experience, and set where in the GraphQL Schema to show the field group. This should reduce some of the confusion between the current Location Rules and GraphQL Schema. 

Something like the below is what I'm exploring now. A checkbox of Types you can assign the field group to in the GraphQL Schema: 

![Screen Shot 2020-04-20 at 1 56 00 PM](https://user-images.githubusercontent.com/1260765/80427261-968c1b80-88a4-11ea-85e4-89114d21eb0c.png)

**Comment by aakash19090** [comment]
Hey @jasonbahl 

Yup now i have got the issue that was in Location Rules as you mentioned.  I was applying to `Post` type for my **Gatsby** Site. 

Anyways, the kind of data I have to show via ACF, I have changed my approach now & using currently `CPT-UI` + `ACF` via your provided `WPgraphQL Custom Post Type UI` plugins together. All is going smooth now and i m getting the ACF fields in WPgraphQL Schema as I have to map them with `Gatsby GraphQL Schema`

Basically its only a Single Page site. So I haven't created any Page for it as I m using `Custom Post Type-UI` plugin to create custom posts & map its data into WPGraphQL schema.  


Now i m stuck in using Contact Forms in my footer. Is there any plugin get the `Form` data or create fields for it so that i can map that as well into my `Gatsby GraphQL` to make queries  ????

Is there any Plugin Stack you suggest to make Contact Form & make its fields visible in WPGraphQL ??????

**Comment by jasonbahl** [comment]
@aakash19090 forms + GraphQL are an interesting thing right now. 

The most ambitious project I've seen with forms is WPGraphQL for Gravity Forms:https://github.com/harness-software/wp-graphql-gravity-forms

I've yet to personally use it, but it's got a lot of good stuff happening.
