### ISSUE TITLE
query popular post

### ISSUE THREAD

**Issue by vana-dev** [wp-graphql/wp-graphql#1264]
Hi, I try to query posts by their popularity. I know that's not default wordpress functionality, but maybe someone already figured it out, how to achieve that in wpgraphql? 

First idea, create custom post meta, with views count. 
https://docs.wpgraphql.com/getting-started/custom-fields-and-meta/

But how to mutate this value on single post query, and how to orderBy post list by this views?

**Comment by vana-dev** [comment]
I tried to extend mutation on post
https://docs.wpgraphql.com/extending/mutations/

`add_action( 'graphql_register_types', function() {
  register_graphql_field( 'Post', 'views', [
     'type' => 'Number',
     'description' => __( 'Post views', 'wp-graphql' ),
     'resolve' => function( $post ) {
       $views = get_post_meta( $post->ID, 'views', true );
       return ! empty( $views ) ? $views : 0;
     }
  ] );
} );

add_action( 'graphql_post_object_mutation_update_additional_data', 'graphql_register_edit_mutation', 10, 5 );

function graphql_register_edit_mutation( $post_id, $input, $mutation_name, $context, $info ) {

	if ( ! empty( $input['example'] ) ) {
		update_post_meta( $post_id, 'views', $input['views'] );
	}

}`

but it doesn't work :/ 

![Zrzut ekranu 2020-04-26 o 12 48 21](https://user-images.githubusercontent.com/884763/80305287-3fab1700-87bc-11ea-8840-f76b510a26a7.png)

**Comment by vana-dev** [comment]
Ok, I figure it out creating custom mutation:

```
add_action( 'graphql_register_types', function() {

	register_graphql_mutation( 'updatePostView', [

		'inputFields'         => [
			'views' => [
				'type' => 'Number',
				'description' => __( 'Post views', 'wp-graphql' ),
			],
			'post_id' => [
				'type' => 'Number',
				'description' => __( 'Post id', 'wp-graphql' ),
			]
		],

		'outputFields'        => [
			'views' => [
				'type' => 'Number',
				'description' => __( 'Post views', 'wp-graphql' ),
				'resolve' => function( $payload, $args, $context, $info ) {
					return isset( $payload['views'] ) ? $payload['views'] : null;
				}
			]
		],

		'mutateAndGetPayload' => function( $input, $context, $info ) {

			update_post_meta( $input['post_id'], 'views', $input['views'] );

			$views = get_post_meta( $input['post_id'], 'views', true );

			return [
				'views' => $views
			];
		}
	] );

} );
```

last problem, how to add this value to post query parameter orderBy?
![Zrzut ekranu 2020-04-26 o 13 31 22](https://user-images.githubusercontent.com/884763/80306265-797f1c00-87c2-11ea-831a-69ec7ff12adb.png)

**Comment by jasonbahl** [comment]
@vana-dev check out this GIST showing how to order by ACF field: 

https://gist.github.com/jasonbahl/da87dbccb58f1323a324a9b3e8952d6c
