### ISSUE TITLE
In WordPress graphql show 200 post but not show in Gatsby graphql

### ISSUE THREAD

**Issue by jnkyst** [wp-graphql/wp-graphql#1265]
Remember, an issue is not the place to ask general questions. You can use [Slack](https://wp-graphql.slack.com) for that ([join here](https://wpgql-slack.herokuapp.com/)).

Before you open an issue, please check if a similar issue already exists or has been closed before.

### When reporting a _bug_, please be sure to include the following:
- [ ] A descriptive title
- [ ] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)
- [ ] What version of `WPGraphQL` you're using, and the platform(s) you're running it on
- [ ] What other plugins you're using
- [ ] The behavior you expect to see, and the actual behavior

### When you open an _issue_ for a feature request, please add as much detail as possible:
- [x] A descriptive title
- [x] A description of the problem you're trying to solve, including *why* you think this is a problem
- [ ] An overview of the suggested solution
- [ ] If the feature changes current behavior, reasons why your solution is better

**Comment by CodeProKid** [comment]
@jnkyst could you add some more info about your setup here? What version of the WPGraphQL plugin are you using? Which gatsby-source plugin are you using?

**Comment by jasonbahl** [comment]
@jnkyst we'd love to help, but as @CodeProKid pointed out, we'll need more information.

**Comment by jnkyst** [comment]
Sir
There is a problem with 
Gatsby-sources-graphql plugin
How to increase more than 100 posts in Gatsby
Only show less than 100posts using this plug-in why

**Comment by jasonbahl** [comment]
@jnkyst do you have a repo? What queries have you tried that are not returning as many posts as you’d expect?

Also, i would recommend checking out `gatsby-source-wordpress-experimental` 

It’s the new WordPress plugin we will be officially supporting at Gatsby. 

You can read more here: 
https://github.com/gatsbyjs/gatsby/issues/19292

And see an example site using it here:
https://github.com/TylerBarnes/using-gatsby-source-wordpress-experimental

**Comment by jasonbahl** [comment]
@jnkyst WPGraphQL responds with a max of 100 root items to ensure the WordPress server doesn't melt trying to respond with _everything_.

When using `gatsby-source-graphql` you will need to fetch more than 100 items using pagination. 

You can see an example of this in action here: 

## The Query 

Note the use of the `first:$first` and `after:$after` variables here. These are used for pagination. Also, asking for `{ pageInfo { hasNextPage, endCursor } }` allows us to know if there are more items to fetch and where to start the next fetch.

https://github.com/wp-graphql/gatsby-wpgraphql-blog-example/blob/master/gatsby/createPosts.js#L3-L23

## Fetch More
Here we check if `pageInfo.hasNextPage` is true. If it is, there are more items to fetch, so we fetch more, this time passing the `pageInfo.endCursor` as the value of the `$after` variable. This tells WPGraphQL to fetch the next set of posts _after_ the end post from the previous request. 

https://github.com/wp-graphql/gatsby-wpgraphql-blog-example/blob/master/gatsby/createPosts.js#L56

**Comment by jnkyst** [comment]
Hi sir now I am using gatsby-source-wordpress
It's working and fetching more than 300 posts one time.
And your opinion
What 
Gatsby-source-wordoress vs gatsby-souce-graphql
Which is best.

**Comment by jasonbahl** [comment]
@jnkyst Gatsby is putting resources into supporting the `gatsby-source-wordpress-experimental` plugin mentioned above. 

It's currently in Alpha and will be supporting features like Gatsby Incremental Builds, Gatsby Preview, and more. 

In the future, it will become `gatsby-source-wordpress` and will be _the_ officially supported Gatsby Source plugin for WordPress. 

I'd recommend checking it out.

**Comment by jnkyst** [comment]
Thank you sir you are great for making Gatsby
And these type plugins

**Comment by jasonbahl** [comment]
Thank you for the kind words. I'm a _very_ small part of a larger Gatsby [team](https://www.gatsbyjs.com/about/) and [much larger community](https://github.com/gatsbyjs/gatsby/graphs/contributors) making Gatsby. Lots of folks involved in making Gatsby great!

**Comment by eduardogoncalves** [comment]
I'm using `gatsby-source-graphql`, and I had the same issue as @jnkyst trying to load posts at build time. During my tests, I had to use a large number to fetch all posts using ex.: `posts(first: 500) {}`, but I couldn't find a way to get all posts or fetch next posts using cursors at build time.

## gatsby-node.js
```js
exports.createPages = async ({ actions, graphql }) => {
const result = await graphql(`
    {
      wpgraphql {
        pages {
          nodes {
            uri
            id
          }
        }
        posts(where: { orderby: { field: DATE, order: DESC } }, first: 500) {
          edges {
            cursor
            node {
              id
              uri
            }
          }
        }
        readingSettings {
          postsPerPage
        }
      }
    }
  `)

const posts = result.data.wpgraphql.posts.edges

posts.forEach(post => {
    actions.createPage({
      path: post.node.uri,
      component: require.resolve("./src/templates/post-template.js"),
      context: {
        id: post.node.id,
      },
    })
  })
}
```

But after reading what @jasonbahl said, I'm going to try `gatsby-source-wordpress-experimental`.
