### ISSUE TITLE
Fix schema linting on builds

### ISSUE THREAD

**Issue by CodeProKid** [wp-graphql/wp-graphql#1268]
Currently, the schema linting is breaking on all of the builds. The issue is we're not doing all of the docker setup before trying to install the DB and running the command to generate the schema here: https://github.com/wp-graphql/wp-graphql/blob/d8bbb4ca0e58c51bd3525009efe2d105fb10855d/.github/workflows/schema-linter.yml#L35

We should probably just move this check into one of the other build steps rather than setting up docker again.

**Comment by CodeProKid** [comment]
@jasonbahl I noticed you took a stab at this in #1278 but I think we should take a different approach.

I think we should add a `GENERATE_SCHEMA` env flag, and then add that to the matrix for a single build, like how we generate codecov. Then have _that_ run the CLI command while the environment is bootstrapped, and save the file as an artifact. Then we can reference the persisted artifact in the schema linting job. This way we don't have to bootstrap the entire environment again. Some GH docs on persisting artifacts during jobs: https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts

**Comment by jasonbahl** [comment]
Ah nice. Ya, this is good stuff. I'll give it another go.
