### ISSUE TITLE
Rename /graphql enpoint to /wp-graphql

### ISSUE THREAD

**Issue by jooola** [wp-graphql/wp-graphql#1272]
I propose to change the root endpoint from `/graphql` to `/wp-graphql`.

At start I thought I could simply proxy every /wp-* request to wordpress and the rest to gatsby. But it won't work for the graphql enpoint.

I know this can be fixed with an extra path to the reverse proxy settings, but I feel this is could be improved.

This would make the endpoint consistent with wp-json, but I don't know if the wp- prefix is reserved for wordpress core. 

Even if this breaking change occurs before v1, it is a big one.

**Comment by jasonbahl** [comment]
@jooola thanks for the issue! 

We're not currently considering changing the default endpoint. The greater GraphQL community uses the `/graphql` endpoint and a lot of tooling expects that as the default. 

Potentially if there was serious discussion of a WordPress core merge and there was compelling enough cases to change it, we'd consider at that point.

The endpoint is filterable, so for your needs you can change the endpoint to something like `/wp-graphql` with this filter: 

```
function my_new_graphql_endpoint() {
  return 'wp-graphql';
};

add_filter( 'graphql_endpoint', 'my_new_graphql_endpoint' );
```

After adding this filter, be sure to [flush your permalinks](https://typerocket.com/flushing-permalinks-in-wordpress/).
