### ISSUE TITLE
Change ContentTemplateUnion to an interface

### ISSUE THREAD

**Issue by TylerBarnes** [wp-graphql/wp-graphql#1291]
Since every template only seems to have the templateName field, it seems like this would be better served as an interface.

```graphql
      template {
        __typename
        ... on DefaultTemplate {
          templateName
        }
        ... on CoverTemplateTemplate {
          templateName
        }
        ... on FullWidthTemplateTemplate {
          templateName
        }
      }
```

could become

```graphql
      template {
        templateName
      }
```

**Comment by TylerBarnes** [comment]
While we're at it why not rename templateName to name?
`template.name`

**Comment by jasonbahl** [comment]
@TylerBarnes I'm open to this. 

The goal here is to provide a place for extensions like ACF to add fields that belong to specific templates.

So while there's not anything different with current templates, they can be radically different when ACF field groups are registered. 

I think this pre-exists good support for `register_graphql_interface` but perhaps an Interface might make more sense? 🤔

**Comment by TylerBarnes** [comment]
@jasonbahl that makes sense, I figured it was pre-interface support & meant with the idea of registering more fields. Even if there's only ever 1 common field between the template types it will be a simplification for the common use-case of just wanting the template name

**Comment by jasonbahl** [comment]
Ya, I'll go that route. Thanks for the suggestion!
