### ISSUE TITLE
Graphql End Point Not Working

### ISSUE THREAD

**Issue by britzdylan** [wp-graphql/wp-graphql#1295]
Good day, I have been struggling to get Graphql to work, out of frustration I created a local Wordpress installation with Bitnami ( it has the latest Wordpress version ) and installed woocommerce. I then went on to install wp-graphql,wp-GraphiQL & WooGraphQL. **The graphiql in the admin dashboard works perfectly**, however when I try and visit the endpoint: **HTTP://localhost:81/wordpress/graphql I get redirected to my posts page**, this has happened both times on my **live Wordpress website as well as my local installation**. No other plugin is currently installed on my local Wordpress website and it's using the woocommerce storefront theme. 

**Please help!**
![Screenshot (1)](https://user-images.githubusercontent.com/47594494/81068131-269f1600-8ee0-11ea-968a-689af7ced993.png)

**Comment by jasonbahl** [comment]
@britzdylan I'll need more information to help here. 

As described in the issue description, we'll need instructions on reproducing, what other plugins you have active, what version of WPGraphQL you have, what steps you took so far to try and make things work, what version of PHP you're on, etc.

**Comment by britzdylan** [comment]
please see my first comment, I am using the latest version of WPGraphQL PHP version is at 7.3

**Comment by britzdylan** [comment]
UPDATE: I redownloaded each major branch of graphql and graphiql, If I now visit the end point /graphql I get a json response as follows:
![Screenshot (3)](https://user-images.githubusercontent.com/47594494/81070137-23f1f000-8ee3-11ea-8f1e-6d8393597565.png)

**Comment by jasonbahl** [comment]
@britzdylan glad you got it working. Thanks for the follow-up

**Comment by britzdylan** [comment]
A side note: If a query a list of products and one of them is missing data from one of the fields I requested will it just return null instead?

**Comment by jasonbahl** [comment]
@britzdylan yes, typically a Node that has no data for a given field, or if the field is considered private to the requesting user, null will be the response for the field

**Comment by britzdylan** [comment]
Thank you, I managed to get it working. Thank you for the help.

**Comment by TylerJNewman** [comment]
> Thank you, I managed to get it working. Thank you for the help.

How? I am trying to query products and I cannot query products...  How did you get this working?

**Comment by eriteric** [comment]
I've tried wp-graphql on two different local environments and the endpoint just doesn't work, but it works fine on a staging site.
