### ISSUE TITLE
Bail early in Model layers and use null coalescing on object properties

### ISSUE THREAD

**Issue by CodeProKid** [wp-graphql/wp-graphql#1296]
This just dawned on me, I moved a little too quickly with #1281. Now that the incoming data isn't assumed to be of a particular object type with the type checking on the param in the constructor, we need to add some more checks within the constructor to decide if we should bail early, and use null coalescing when referencing fields on the incoming object so we don't throw an error.

With the current implementation, someone could pass an empty array to the `Post` model, and it would start throwing all sorts of errors since we'd be attempting to access properties on what we assume to be a `WP_Post` object currently.

We should also just bail early in the constructor if we don't have the proper data we need like an ID to hydrate the non-null fields for the Type. This is a bit of a slippery since now that anything can be passed to the Model, since some people wanting to extend the model could pass in a random data shape, and then make it work with the available hooks / filters.

This should be fixed before we cut a release from develop though, since I'm pretty sure it's going to cause some issues in the wild in it's current form.

**Comment by jasonbahl** [comment]
@CodeProKid good catch.

**Comment by jasonbahl** [comment]
The referenced PR #1281 was merged, then reverted before being released. 

Because of that, and the fact that the constructor still contains `\WP_Post $post` as the PHP typing and not a generic object, I believe this issue is not currently relevant.
