### ISSUE TITLE
Custom Taxonomy Query Registration API

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#13]
This will allow taxonomies to register their own type definition class. This is useful when the schema is considerably different than the standard taxonomy schema.

**Comment by CodeProKid** [comment]
Is this still something we want to do? I know we talked about this a while ago, and it seemed like something that still needed to happen. I am all for it, personally. Just not sure of the priority.

**Comment by jasonbahl** [comment]
I think it would be cool, but not sure what it should look like. . .

I think there's plenty of room for `register_*` functions of some sort. . .

Like `register_graphql_field` or `register_graphql_type` or something along those lines. . .

I just don't have clear ideas on what that should look like. . .so def need to discuss it more.

**Comment by jasonbahl** [comment]
So, there are enough hooks and filters in place that if someone wanted to add their own Type that resolved to terms, or custom post type, or anything else they can do it fairly easily. 

I think this is a vague enough issue that we can close it and consider it resolved. We do have other issues with more details on possibly adding functions like `register_graphql_field`, etc.
