### ISSUE TITLE
Feature request: add arguments to post image sizes

### ISSUE THREAD

**Issue by joshuaiz** [wp-graphql/wp-graphql#1300]
Currently, when querying post featured image sizes, you can only return either all sizes or choose a single size. It would be great to be able to return a subset of sizes so something like this:

```javascript
{
    posts {
        edges {
        node {
          id
          image {
            altText
            sizes(size: [LARGE, THUMBNAIL])
          }
    }
}
```
As you can see in this screenshot, I have probably way too many sizes but they are already set in the db so can't remove them now:

<img width="307" alt="Screen Shot 2020-05-06 at 7 58 58 PM" src="https://user-images.githubusercontent.com/1096738/81243007-3435c800-8fd4-11ea-9965-14258b2ad984.png">

Thus, it would be ideal to return only the ones I need. This could be of use to a lot of people, especially if they are converting older WP sites with many legacy image sizes built in.

Also, this should work for featured images across post types so for pages, products, etc.

**Comment by jasonbahl** [comment]
Related: https://github.com/wp-graphql/wp-graphql/issues/889

**Comment by joshuaiz** [comment]
@jasonbahl sorry didn't see that other issue. We can close this if you want.

**Comment by jasonbahl** [comment]
I marked it as duplicate. Let me read them both again tomorrow but ya I’ll probably close on and track the other

**Comment by justlevine** [comment]
closing in favor of #889
