### ISSUE TITLE
speed problem in simple query

### ISSUE THREAD

**Issue by aminhir** [wp-graphql/wp-graphql#1303]
Hi I'm new to wpgraphql.
wpgraphql and jwt has been installed.
The problem is the response time.
This is the query:
`query GET_POSTS($first: Int) {
  posts(first: $first) {
    edges {
      node {
        id
        title
        date
      }
    }
  }
}`
and $first is 1
,but the response time with postman is 2260ms !!
what's wrong?

**Comment by jasonbahl** [comment]
Hard to say what the exact issue is. WPGraphQL is just a wrapper over your WordPress install. There's a good chance your REST API endpoints are slow also, as well as other functionality on the site. 

Here's an example of the same query responding from a live WPGraphQL API in 17ms:

![Screen Shot 2020-05-11 at 10 26 38 AM](https://user-images.githubusercontent.com/1260765/81585852-f0471800-9371-11ea-9192-4b618f0bbbdd.png)

**Comment by jasonbahl** [comment]
@aminhir you might want to check out WPGraphQL Insights. It's a debug tool that adds data to your GraphQL requests such as SQL query logs and trace data. It can help you identify bottlenecks and see what's executing under the hood: 

https://github.com/wp-graphql/wp-graphql-insights

**Comment by jasonbahl** [comment]
I'm going to close this as I don't believe there's any evidence suggesting WPGraphQL is responsible for the slowness. In most cases, you'll find it to be _faster_ than other options. If you believe you have evidence that something in WPGraphQL itself is the culprit, please open an issue with details you've discovered.

**Comment by stephanedemotte** [comment]
@jasonbahl Hello, 17ms on siliconsvalley is pretty quick!! I've trying to get this speed on my website, but i think siliconvalley has a caching services.

When you try the query the first time, the response is relatively slow.

First time ~400ms
<img width="1792" alt="Screen Shot 2020-10-08 at 10 00 26 AM" src="https://user-images.githubusercontent.com/2158130/95469278-7b423380-094d-11eb-89b2-d9bbc153d28c.png">

After that ~30ms
<img width="1792" alt="Screen Shot 2020-10-08 at 10 00 36 AM" src="https://user-images.githubusercontent.com/2158130/95469353-8e550380-094d-11eb-9d4f-eec32fb19a5f.png">

In my side, i've a blank wordpress, and i got everytime ~150ms response time.

Do you know what kind of caching service siliconvalley.com use ?

Thanks !!

**Comment by oskr1103** [comment]
@jasonbahl Hello, I hope you are well, I am presenting a problem similar to this but when I add a product for the first time, the response time can even reach 14 seconds, I contact the hosting company and they tell me that the cpu reaches 100 %, the site is developed in NextJs (https://flowershopcolombia.com/) and consumes wp-graphql, if you could give me an indication of how to search I thank you 
![image](https://user-images.githubusercontent.com/30869944/117311710-0f279f80-ae4a-11eb-8a3f-47550ff7003e.png)

**Comment by joaovpmamede** [comment]
@oskr1103 I'm having the exact some problem (site was developed with Next.js and deployed on vercel, WP hosted on Digital Ocean).
Did you find the solution?

**Comment by oskr1103** [comment]
@joaovpmamede I did not get a solution, if you manage to find something please let me know, I'm still looking for a solution

**Comment by Plinpod** [comment]
Facing a similar issue. I'm running a caching service but even the initial requests are grinding my database to a halt. Unclear if I missed some sort of optimization step.

**Comment by joaovpmamede** [comment]
I think it still an issue even with the latest versions.

**Comment by justlevine** [comment]
@Plinpod @joaovpmamede 

There's not much we can do without a replicable test case.
To provide a 2023-accurate update to @jasonbahl already [noted](https://github.com/wp-graphql/wp-graphql/issues/1303#issuecomment-626809927), the best way to debug this would be to go to the WPGraphQL Settings, enable the SQL log tracing options and share the results so we see what db query is taking so long.

A step further (requires some PHP skills tho) that would be to use PHP Profiling (xdebug or whatever), and share the timings of the entire lifecycle.

Once you do either/both, please create a **new** bug report along with all the requested info, so we have everything we need to investigate and address it.
