### ISSUE TITLE
Taxonomy label showing as null

### ISSUE THREAD

**Issue by TheoKoenig** [wp-graphql/wp-graphql#1304]
When querying the label of a taxonomy, **HTTP clients** return `null` instead of the actual label.
Tested this on two different sites, using "post" type and a custom post type.

Tested using the latest version of WPGraphQL.

### Query
```graphql
query MyQuery {
  categories(first: 1) {
    nodes {
      taxonomy {
        node {
          name
          label
        }
      }
      name
      slug
    }
  }
}
```
### Response in GraphiQL
```json
{
  "data": {
    "categories": {
      "nodes": [
        {
          "taxonomy": {
            "node": {
              "name": "category",
              "label": "Categories"
            }
          },
          "name": "Arts &amp; crafts",
          "slug": "arts-crafts"
        }
      ]
    }
  }
}
```
### Response in Axios and Postman
```json
{
    "data": {
        "categories": {
            "nodes": [
                {
                    "taxonomy": {
                        "node": {
                            "name": "category",
                            "label": null
                        }
                    },
                    "name": "Arts &amp; crafts",
                    "slug": "arts-crafts"
                }
            ]
        }
    }
}
```

**Comment by jasonbahl** [comment]
@TheoKoenig Labels on Post Types are not publicly exposed by WordPress. They are attributes for use in the Admin, and are treated with respect to proper access to the admin. 

To see the labels, the user requesting them must be authenticated. 

When a user requesting a `PostType`, these are the following fields that are by default allowed to be viewed by a public request: https://github.com/wp-graphql/wp-graphql/blob/develop/src/Model/PostType.php#L58-L70

You can use the `graphql_allowed_fields_on_restricted_type` filter to expose more fields publicly if you chose to do so: https://github.com/wp-graphql/wp-graphql/blob/develop/src/Model/Model.php#L287

Something like the following should work: 

```
add_filter( 'graphql_allowed_fields_on_restricted_type', function( $fields, $model_name, $data, $visibility, $owner, $current_user ) {
	if ( 'PostTypeObject' === $model_name ) {
		$fields[] = 'label';
	}
	return $fields;
}, 10, 6 );
```

Here's the filter in action:

**BEFORE ADDING FILTER**

![Screen Shot 2020-05-11 at 11 17 38 AM](https://user-images.githubusercontent.com/1260765/81591101-23d97080-9379-11ea-86a8-ce0047debfb2.png)


**AFTER ADDING FILTER**

![Screen Shot 2020-05-11 at 11 17 34 AM](https://user-images.githubusercontent.com/1260765/81591113-28058e00-9379-11ea-911d-0a0d7474682a.png)

**Comment by TheoKoenig** [comment]
Oh I did not know that! Thank you, will try that :)

**Comment by TheoKoenig** [comment]
It seems I couldn't find a similar filter for taxonomies?

What I want to expose is:

```graphql
  Colour(id: "cHJvZHVjdF9jb2xvdXJzOjEx") {
    taxonomy {
      node {
        label
      }
    }
  }
```

What would be the code to expose publicly the label of _every_ taxonomy?

Thank you for your time.

**Comment by jasonbahl** [comment]
@TheoKoenig it's the same filter. Just a different ModelName. 

Something like: 

```
add_filter( 'graphql_allowed_fields_on_restricted_type', function( $fields, $model_name, $data, $visibility, $owner, $current_user ) {
	if ( 'PostTypeObject' === $model_name || 'TermObject' === $model_name ) {
		$fields[] = 'label';
	}
	return $fields;
}, 10, 6 );
```

**Comment by TheoKoenig** [comment]
It works perfectly, thank you.
I ended up using the `TaxonomyObject` ModelName.
