### ISSUE TITLE
Possible compatibiliy issue with WPML on menus query

### ISSUE THREAD

**Issue by danieleperot** [wp-graphql/wp-graphql#1305]
I found an issue regarding the `menus` query if WPML is used:

```json
{
  "errors": [
    {
      "debugMessage": "Argument 1 passed to WPGraphQL\\Model\\Term::__construct() must be an instance of WP_Term, null given, called in /var/www/html/wp-content/plugins/wp-graphql/src/Data/Loader/TermObjectLoader.php on line 97",
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "menus"
      ]
    }
  ],
  "data": {
    "menus": null
  }
}
```

This is the query I used to reproduce the error:
```graphql
query MyQuery {
  menus {
    nodes {
      id
    }
  }
}
```

------
### PHP, Wordpress and plugin version and related information
* Wordpress version: **5.4.1**
* PHP version: **7.2**
* WP GraphQL version: tested both with **0.8.0** and the latest **0.8.4**
* WPML Multilingual CMS version: **4.3.12**
* WPML String Translation version: **3.0.9**
------

### Detailed explenation
I'm using for this example English as my primary language and Italian as my secondary language.

I have 2 menus in English, plus their relative translations in Italian.

In my database, `wp_terms` contains the following rows:
|term_id|name|slug|
|---|---|---|
|...|...|...|
|5|main-menu|Main menu|
|7|footer|Footer|
|...|...|...|
|14|main-menu-italian|Main menu - Italian|
|16|footer-italian|Footer - Italian|
|...|...|...|

As the error is thrown in `WPGraphQL\Data\Loader\TermObjectLoader`, I inspected the `$keys` and `$terms` variables defined at lines [31](https://github.com/wp-graphql/wp-graphql/blob/5381e5c4c1cb4f623764f279e839e2f8efb5ed80/src/Data/Loader/TermObjectLoader.php#L31) and [52](https://github.com/wp-graphql/wp-graphql/blob/5381e5c4c1cb4f623764f279e839e2f8efb5ed80/src/Data/Loader/TermObjectLoader.php#L52).

The `$keys` variable is rightfully loaded as such:
```php
$keys = [7, 16, 5, 14]; // The list of the IDs of all the menus in wp_terms
```

HOWEVER, the `$terms` variable results in this array of duplicated values:
```php
$terms =  [

  [
    'term_id' => 7,
    'slug' => 'footer',
    'name' => 'Footer',
    // ...
  ],
  [
    'term_id' => 7,
    'slug' => 'footer',
    'name' => 'Footer',
    // ...
  ],
  [
    'term_id' => 5,
    'slug' => 'main-menu',
    'name' => 'Main menu',
    // ...
  ],
  [
    'term_id' => 5,
    'slug' => 'main-menu',
    'name' => 'Main menu',
    // ...
  ],
  // There is a duplication for every menu
];
```
I suspect that WPML interferes with the terms query, returning a duplication of values for the current selected language (in my case, English).

This causes troubles down the line, as inside the `foreach` loop at line 76 the `$term_object` variable is null for each duplicated menu (the `$terms_by_id` option does not include, for example, the ID `14` as WPML returns for that menu the object with ID `5`):
https://github.com/wp-graphql/wp-graphql/blob/5381e5c4c1cb4f623764f279e839e2f8efb5ed80/src/Data/Loader/TermObjectLoader.php#L76

The `if` is then not verified at line 85,  as `null` is not equal to `"nav_menu"`:
https://github.com/wp-graphql/wp-graphql/blob/5381e5c4c1cb4f623764f279e839e2f8efb5ed80/src/Data/Loader/TermObjectLoader.php#L85

Following the code, line 93 is then called and crashes the query, as it is trying to load `null` to a new `WPGraphQL\Model\Term`:
https://github.com/wp-graphql/wp-graphql/blob/5381e5c4c1cb4f623764f279e839e2f8efb5ed80/src/Data/Loader/TermObjectLoader.php#L93

------

### Possible solution
In my case I solved the problem wrapping all the code between lines [78 and 99](https://github.com/wp-graphql/wp-graphql/blob/5381e5c4c1cb4f623764f279e839e2f8efb5ed80/src/Data/Loader/TermObjectLoader.php#L78-L99) with this `if` statement:
```php
if ($term_object) {
  // Continue normally from line 78 to line 99
}
```

This has the side effect of **never returning a the translated menus**, although to me it is kind of the expected behavior.

------

I hope I was clear enough with the explaination.

I didn't open a Pull Request as I'm not sure that this is the *right* solution, but I would certainly this bug to be known and possibly fixed: if you feel like this patch could be included in your code, I will happily create a Pull Reqest.

**Comment by jasonbahl** [comment]
@danieleperot thanks for the detailed information. I'll see what I can find out and if there's something we should consider modifying in WPGraphQL or if there's something that should change with WPML or some middle ground between the two

**Comment by jasonbahl** [comment]
I'm going to close this as a lot of the code in the loaders has changed since this was reported. 

If this is still an issue, and someone can provide concrete steps to reproduce it (ideally without requiring a WPML license) that would be great.

**Comment by rboddy** [comment]
Still finding a similar issue, but I don't know if replication without a WPML license is possible. The following query:

`{
  menus {
    nodes {
      menuItems(first: 100, where: { parentId: null}) {
        nodes {
          label
          parentId
          childItems {
            nodes {
              label
            }
          }
        }
      }
    }
  }
}`

Still returns all menu items, even when the parentId is not null. Client on this site requires WPML for multilingual. Please let me know if any other details could help dig in.
