### ISSUE TITLE
Add introspection tests.

### ISSUE THREAD

**Issue by BE-Webdesign** [wp-graphql/wp-graphql#131]
Currently, there are no unit tests for testing whether the schema we have designed indeed exists. We should use GraphQL's introspection system to add unit tests proving the schema. Then as the schema is changed the build will fail, alerting to any potential regressions.

**Comment by jasonbahl** [comment]
With the mutations I'm working on now I've included some tests for the Schema per the Relay spec to make sure the mutations we add adhere to the spec (https://facebook.github.io/relay/graphql/mutations.htm#sec-Introspection)

GraphQL JS also has a "findBreakingChanges" method built in and I've read about some folks integrating CI to check the schema to make sure breaking changes aren't being introduced. (http://joelgriffith.net/setting-up-graphqls-findbreakingchanges-and-eslint-plugin-graphql/) 

Would be good to check out for sure.

**Comment by jasonbahl** [comment]
the Relay spec docs actually give very good detailed introspection queries to use to make sure connections, etc adhere to the spec. 

https://facebook.github.io/relay/graphql/objectidentification.htm
https://facebook.github.io/relay/graphql/connections.htm
https://facebook.github.io/relay/graphql/mutations.htm

**Comment by jasonbahl** [comment]
Closing in favor of #335
