### ISSUE TITLE
GraphQL endpoint rewrite not working with Laravel Valet and Bedrock

### ISSUE THREAD

**Issue by zamson** [wp-graphql/wp-graphql#1311]
The GraphQL endpoint does not work when running Laravel Valet and Bedrock locally. I suspect is has to do with the valet Bedrock driver and the directory rewrite `/wp/`. On my production server the rewrite works as suspected `/wp/graphql` but locally only `/?graphql`.

**Proposed solution**

Bedrock supports running a [local driver](https://laravel.com/docs/5.4/valet#custom-valet-drivers) per project. The Bedrock driver found [here](https://raw.githubusercontent.com/laravel/valet/master/cli/drivers/BedrockValetDriver.php) can be extended with a new function that takes care of the `/?graphql` rewrite, however I need some help implementing this since I'm a bit clueless. Another option would be to create an nginx rewrite... not sure what's best practice here.

**Comment by bhardie** [comment]
We have other users working with Bedrock now, and believe this to be resolved.  Can you please verify and close the ticket if it is resolved or reply if you are still experiencing problems?

**Comment by jasonbahl** [comment]
I'm going to close this as we've successfully used WPGraphQL with bedrock for some testing and have other users using the plugin with that stack. 

If you are still experiencing issues with Bedrock + WPGraphQL, please open a new issue with steps to reproduce and reference this issue.
