### ISSUE TITLE
Add `asPreview` input argument to single post object RootQuery entry points in the graph

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#1312]
In order to preview a Post, we should add an `asPreview` input argument on RootQuery entry points for single content nodes. 

For example: 

```
{
  post( id: 123, idType: DATABASE_ID, asPreview: true ) {
    id
    title
    content
    ...NodeWithPreview {
       isPreview # <-- new boolean field
    }
  }
}
```

or

```
{
  contentNode( id: 123, idType: DATABASE_ID, asPreview: true ) {
    ...on Post {
      ...PostFragment
    }
  }
}
```

This would allow us to set the global `$wp_query->is_preview` state so that underlying resolution of previews could execute properly.

**Comment by drewbaker** [comment]
How are you thinking the auth would work to be able to see a preview?

**Comment by jasonbahl** [comment]
@drewbaker Auth will work the same it works any other way you can auth for GraphQL. 

WPGraphQL JWT Auth, WP GraphQL Cors, etc. 

The preview nodes respect the capabilities of the Post it's a preview of. Users must be authenticated and have capabilities to edit the node to see a preview/revision of it.

**Comment by jasonbahl** [comment]
Here are some examples of this in action: 

# Query a Post and it's preview

In this example GIF, I update the title and content and click "Preview". This stores the changes as a revision. 

I can then use GraphQL to query for the post, and ask for the preview as a connection to that Post. 

![wp-graphql-preview-example](https://user-images.githubusercontent.com/1260765/83768106-a03f3680-a63b-11ea-86b8-0d1c46bf8893.gif)

Here's a static screenshot of the query in GraphiQL too: 

![Screen Shot 2020-06-04 at 8 19 57 AM](https://user-images.githubusercontent.com/1260765/83768567-2fe4e500-a63c-11ea-81b9-c2c22babb308.png)

Here, we can see that I'm querying for fields of the node itself, but connected nodes as well, such as the Author and Featured Image. 

The Post shows the title and content as they appear on the published node, but the preview node shows the changes I made just before clicking "Preview". 

However, you will note that the author and featured image are the same for both the Published post and the preview! 

Connections from Preview nodes to things like Author, Terms and meta resolve using the parent node's connections by default, as _most_ things about a Post are not revised behind the scenes by WordPress core. 

For plugins, such as Advanced Custom Fields, that actually do revise meta, there's a filter that allows for meta to be resolved using the Revision meta instead of the parent meta. This can be applied to work for certain meta keys, so that some meta that's not revised can resolve from the parent, and meta that _is_ revised can resolve from the Revision itself.
