### ISSUE TITLE
Publish release archive to release page

### ISSUE THREAD

**Issue by jooola** [wp-graphql/wp-graphql#1315]
I propose to publish release archives on the github release page. This could simplify some installation processes.

The current release archives are the whole source code, and we don't necessarily want all the files. We could bundle a zip with the minimal production files using CI.

This enhancement could then by used for the rest of the wp-graphql projects (graphiql, acf, ...)

**Comment by jasonbahl** [comment]
@jooola we use the `.gitattributes` file to define files to leave out of the release zips. 

What files specifically are you seeing in your downloads that you believe shouldn't be there?

The extensions such as `wp-graphql-acf` and `wp-graphiql`, etc don't currently make use of this, so they are indeed a bit more messy. Would love a PR to help clean those up 😄

**Comment by jooola** [comment]
Ok, I'll push PRs on the other repos. Probably not today though.

**Comment by jooola** [comment]
@jasonbahl Like I said in my PR above, I am confused by how we use .gitattribute and the export-ignore filter.

My idea of a release would be an archive with only the files for production. This means no composer.json, or package.json.

Still I think we need to provide a snapshot of the full source code (hence the "source code" archive name in the github release page) with all the files we might have remove using the .gitattribute technique.

Why not rely on CI to build such packages with fresh dependencies and clean archives ?

**Comment by jasonbahl** [comment]
@jooola I'm not opposed to CI to build such packages. Just hasn't been a priority. If you've got ideas on a sound approach to get this setup and easy-ish to maintain, I'm open for sure.

**Comment by jooola** [comment]
@jasonbahl Would you mind explaining me your current release process ? I prefer not change the way you work, and I'll automate as much as possible from there.

**Comment by jasonbahl** [comment]
@jooola the .zips are now packaged and uploaded to the releases starting with v1.2.0

see: https://github.com/wp-graphql/wp-graphql/releases
