### ISSUE TITLE
Hierarchical terms like categories should have child parent connections.

### ISSUE THREAD

**Issue by BE-Webdesign** [wp-graphql/wp-graphql#133]
Hierarchical taxonomy terms like categories should have child parent relations exposed in their type.

**Comment by jasonbahl** [comment]
yes, not sure how I missed this before 😢 

I also have a PR coming with ancestor support

**Comment by BE-Webdesign** [comment]
>yes, not sure how I missed this before 😢

It's the entirety of WordPress trying to be exposed through a single API, very easy to miss stuff and the inner relations.

**Comment by shah** [comment]
Hi there @jasonbahl - is there a way to get categories at a particular level and all subcategories (children) from that level and below? I see "ancestors" in the Schema already but I do not see "children" so I wanted to make sure I didn't miss anything.

**Comment by jasonbahl** [comment]
@shah still an open issue. . .shouldn't be too hard to implement though if you want to give a shot at a PR?

**Comment by shah** [comment]
Would love to @jasonbahl ... new to PHP and WP but happy to give it a shot.

**Comment by jasonbahl** [comment]
addressed by #185
