### ISSUE TITLE
ACF orderby - breaks pagination (endCursor returns the same page)

### ISSUE THREAD

**Issue by guilhermejbranco** [wp-graphql/wp-graphql#1331]
Hello,

I'm trying to order some events I have by their start_date. 

I added the following code to my functions.php file, and the posts are ordered as expected.

```
$paged = ( get_query_var('paged') ) ? get_query_var('paged') : 1;
$query_args['orderby'] =  ['meta_value_num' => 'ASC'];
$query_args['paged'] = $paged;
$query_args['meta_key'] =  'dates_dates_$_start_date';
```

 The thing is, when I try to fetch the second page (hasNextPage is True), the query returns the very same page.

Any ideas?

**Comment by justlevine** [comment]
Leaving closed since I'm assuming it was solved by #2457 , if not before. 
If someone runs into this again, please open up a new issue tested against the latest version of both plugins.
