### ISSUE TITLE
The result of graphql_is_graphql_http_request filter should be respected if it returns false

### ISSUE THREAD

**Issue by janus-reith** [wp-graphql/wp-graphql#1332]
Each request is parsed by the Router to determine if it is mean to be be processed by the graphql endpoint.

This functionality can be overriden by a filter here:
https://github.com/wp-graphql/wp-graphql/blob/135cf0fa5278fce06c651ab9d5d9b8d34e5552c1/src/Router.php#L139

After applying the filter, it will check if that returned `true`, else it will just continue:
https://github.com/wp-graphql/wp-graphql/blob/135cf0fa5278fce06c651ab9d5d9b8d34e5552c1/src/Router.php#L146:L148

Next, it will continue with the default parsing, thereby overriding any previous value for`is_graphql_http_request` here:
https://github.com/wp-graphql/wp-graphql/blob/135cf0fa5278fce06c651ab9d5d9b8d34e5552c1/src/Router.php#L160

Adding a filter for `graphql_is_graphql_http_request` should allow to alter the outcome for that check to return `false` for the default /graphql route.

This could be solved either by initializing as `null` as @jasonbahl pointed out, and just skip the internal check if some filter set the value, or do the internal check first and apply the custom filter afterwards.

**Comment by jasonbahl** [comment]
@janus-reith my preference would be to filter first. If external criteria is needed to determine what a graphql request is, and they're using this filter, it _probably_ doesn't also need the default logic first.

**Comment by janus-reith** [comment]
@jasonbahl Agreed. The only usecase I would see is, if the custom function would somehow deduce its result based on the outcome of the default check, but these specific usecases could also just copy over that check, while most usual cases probably won't benefit much from such chaining.

But I have to say, I'm not that knowledged in Wordpress and don't know what the default, rather expected behaviour of filters is.

**Comment by jasonbahl** [comment]
ya, it can go either way really. And in this case, the logic executed isn't "expensive". 

Usually the filter _before_ the logic with an early return helps avoid "expensive" processing if the filter returns something. 

In this case, the execution of the default behavior is negligible and shouldn't result in any tangible difference whether the filter were applied early and returned early or applied late after the default logic. 

I could go either way here.
