### ISSUE TITLE
No sub-categories showing on posts

### ISSUE THREAD

**Issue by mehdibahrami** [wp-graphql/wp-graphql#1336]
When the post category is a parent, I don't face any problem, and I have a category/categories in my post/posts query, but when it's a child category, I can't get it!
<img width="943" alt="Screen Shot 2020-06-02 at 19 55 33" src="https://user-images.githubusercontent.com/63710663/83538715-6a9b3000-a50b-11ea-83fd-8384b5e5481d.png">
<img width="950" alt="Screen Shot 2020-06-02 at 19 56 47" src="https://user-images.githubusercontent.com/63710663/83538780-7d156980-a50b-11ea-897c-6a1bb8ca1af8.png">
But when I try to get posts from categories, I can get them without any problem!
<img width="948" alt="Screen Shot 2020-06-02 at 20 02 20" src="https://user-images.githubusercontent.com/63710663/83539184-fd3bcf00-a50b-11ea-9247-d5075f9532f4.png">

**Comment by jasonbahl** [comment]
This is a bug that I have a fix in the works for. 

Right now, connections with hierarchical content (Categories, Pages, for example) return top-level nodes by default and you have to query for the child nodes if you want them. 

This sounded like a good idea initially, but it's been problematic in practice. 

In an upcoming release, the behavior will be modified to return connections in a flat list. 

So, the categories associated with a post will be returned as part of the connection, regardless of their parent-child relationship with other categories. 

More context in this issue https://github.com/wp-graphql/wp-graphql/issues/887#issuecomment-508808865

I have a PR I plan to open today that aims at resolving this.

**Comment by mehdibahrami** [comment]
Thanks @jasonbahl, for your response.
I saw that Issue before posting this one, and even with query for the child nodes, I can't get them.
<img width="952" alt="Screen Shot 2020-06-02 at 20 26 28" src="https://user-images.githubusercontent.com/63710663/83541792-5e18d680-a50f-11ea-8c55-d7f0b710d86c.png">
I think I should wait for your upcoming release.

**Comment by jasonbahl** [comment]
Going to close this in favor of #887
