### ISSUE TITLE
Expose `MediaItem.fileSize` (in bytes)

### ISSUE THREAD

**Issue by TylerBarnes** [wp-graphql/wp-graphql#1350]
Currently there's no way to query for the file size of a media item in bytes (not dimensions). It'd be great to be able to access this. My use case is to be able to set a maximum file size that should be fetched in Gatsby. So if a file is larger than 5mb for example, I will know not to fetch that file and to instead use the publicUrl

related to https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/26

**Comment by felixaa** [comment]
This would be awsome. Any workaround for this currently?

**Comment by CodeProKid** [comment]
@TylerBarnes I'm curious, would you need this on each of the image crop size (IE. the `MediaSize` Type) as well? Seems like it should probably be there for consistency.

**Comment by TylerBarnes** [comment]
@CodeProKid yeah, that seems like a good idea. I was just thinking on the main file but for this to be generally useful that makes sense to me.

**Comment by jasonbahl** [comment]
@TylerBarnes I've got this added as a field on the `MediaItem` as well as the `MediaSize` like so:

![Screen Shot 2020-07-10 at 10 24 51 AM](https://user-images.githubusercontent.com/1260765/87176651-a3ab8a80-c297-11ea-880d-54e8280f87d3.png)

Right now it outputs an integer of the filesize in Bytes

**Comment by TylerBarnes** [comment]
@jasonbahl woo! that looks great!

**Comment by jasonbahl** [comment]
@TylerBarnes I got it working for Videos as well. Of course only for the parent file and not `MediaDetails.sizes` because videos don't expose that. 

But you can query like so: 

![Screen Shot 2020-07-10 at 2 16 52 PM](https://user-images.githubusercontent.com/1260765/87198557-057bec80-c2b8-11ea-8c46-93a08833ac55.png)
