### ISSUE TITLE
Mutation with `list_of` of a newly registered o-type as argument

### ISSUE THREAD

**Issue by rubas** [wp-graphql/wp-graphql#1361]
I get an error with my schema (`Introspection must provide input type for arguments, but received: [FooType]`), if I use `list_of` with a newly registered object type as an argument for a mutation.

```
register_graphql_object_type('FooType', [
  'description' => 'Bar',
  'fields'      => [
    'id'   => ['type' => 'Integer', 'description' => 'ID'],
    'name' => ['type' => 'String', 'description' => 'Name'],
  ],
]);

register_graphql_mutation(
  'mutation',
  [
    'inputFields'  =>  'list' => ['type' => ['list_of' => 'FooType'], 'description' => 'List'],
     ...
   ]
);
```

---

It works fine if I use the type `String` =>  `'inputFields'  => 'list' => ['type' => ['list_of' => 'String'], 'description' => 'List'],`.

**Comment by jasonbahl** [comment]
@rubas it looks like you have some syntax issues here. 

Try: 

```
'inputFields' => [
  'list' => [
     'type' => [
        'list_of' => 'FooType',
        'description' => 'One or more FooTypes'
     ]
  ]
]
```

**Comment by jasonbahl** [comment]
@rubas ah! Actually, you cannot use an object type for input. You need to use an input type. 

So instead of `register_graphql_object_type( 'FooType', ... );` you would need to do `regsiter_graphql_input_type( 'FooInputType', ... );`

Input types are very similar to object types, but they're treated differently by GraphQL because they expect input and process differently than Object Types that expect output and not input.

**Comment by jasonbahl** [comment]
@rubas something like: 

```php
add_action( 'graphql_register_types', function() {

	register_graphql_input_type( 'FooInputType',  [
		'fields'      => [
			'id'   => ['type' => 'Integer', 'description' => 'ID'],
			'name' => ['type' => 'String', 'description' => 'Name'],
		]
	]);

	register_graphql_mutation( 'FooMutation', [
		'inputFields' => [
			'foos' => [
				'type' => [
					'list_of' => 'FooInputType',
				],
			],
		],
		'outputFields' => [
			'something' => [
				'type' => 'String',
			],
		],
		'mutateAndGetPayload' => function() {
			return [
				'something' => 'foo mutated.'
			];
		}
	] );

} );
```

**Comment by rubas** [comment]
Sorry, I missed  the `register_graphql_input_type` function. 

For reference: All those functions can be found [here](https://github.com/wp-graphql/wp-graphql/blob/master/access-functions.php).

```
/**
 * Given a Type Name and a $config array, this adds an InputType to the TypeRegistry
 *
 * @param string $type_name The name of the Type to register
 * @param array  $config    The Type config
 */
function register_graphql_input_type( $type_name, $config ) {
	$config['kind'] = 'input';
	register_graphql_type( $type_name, $config );
}
```

I'm sure the documentation will get a lot more love after 1.0 release and an increasing adoption of the plugin.
