### ISSUE TITLE
Expose archive page urls

### ISSUE THREAD

**Issue by TylerBarnes** [wp-graphql/wp-graphql#1365]
This is necessary to be able to programatically create archive pages using the url pattern specified in WP. I guess this should exist for the `Taxonomy` and `ContentType` types and possibly other types?

**Comment by jasonbahl** [comment]
I'm thinking we can expose this as `uri` field, and then we could even expose the ability to query like so: 

```graphql
{ 
  contentType( id: "/post" idType: URI ) { 
    ...fields 
  }
}
```  

We also have the `nodeByUri( uri: $uri )` entry point, so this will play nice if they have a `uri` field as well.
