### ISSUE TITLE
Slack invite link says "Token Revoked"

### ISSUE THREAD

**Issue by dpacmittal** [wp-graphql/wp-graphql#1373]
The link https://wpgql-slack.herokuapp.com/ doesn't work anymore.

**Comment by jasonbahl** [comment]
@dpacmittal thanks for the issue. Looking into this 👀

**Comment by jasonbahl** [comment]
Looks like Slack has a built-in feature for what I had a service for. 

The new link to join slack will be: https://join.slack.com/t/wp-graphql/shared_invite/zt-3vloo60z-PpJV2PFIwEathWDOxCTTLA

I'll update the README and the website

**Comment by babgyy** [comment]
Hello,
Just for information : the herokuapp still ranks first on google : https://wpgql-slack.herokuapp.com/
As a suggestion you could redirect to the correct URL : 

![image](https://user-images.githubusercontent.com/852926/102200121-b79d8d00-3ec4-11eb-930a-bf70103952ea.png)

Anyway thanks again for this gem
