### ISSUE TITLE
How to update CORS params in the plugin?

### ISSUE THREAD

**Issue by jorgeluis1706** [wp-graphql/wp-graphql#1386]
Hi, i need to set a specific domain to access-control-allow-origin, but the plugin hardcode the * option.

How can i change that? there is a filter or action to change this?

**Comment by jonshipman** [comment]
```
add_filter(
	'graphql_response_headers_to_send',
	function( $headers ) {		
		$headers['Access-Control-Allow-Origin'] = 'http://your-frontend.com';
		return $headers;
	}
);
```

Usually it's better to ask for help in the slack channel. https://join.slack.com/t/wp-graphql/shared_invite/zt-3vloo60z-PpJV2PFIwEathWDOxCTTLA

**Comment by bhardie** [comment]
See @jonshipman response
