### ISSUE TITLE
Review fields.

### ISSUE THREAD

**Issue by BE-Webdesign** [wp-graphql/wp-graphql#139]
A lot of fields are return `null` when they probably shouldn't be.  Instead of doing `! empty()` checks we should do `isset()` checks instead potentially?

**Comment by jasonbahl** [comment]
possibly. . .do you have examples of fields that aren't behaving properly?

**Comment by BE-Webdesign** [comment]
A bunch of the ones in on terms I think?  I came across many, probably do a review at some point.  One was terms count, if the count is 0 you get null instead of 0, because 0 is an empty value.

**Comment by jasonbahl** [comment]
Ah. Ya. Ok. I'll do a review of all the fields. Make sure integers properly return 0 when appropriate, etc. thanks!

**Comment by BE-Webdesign** [comment]
If we change a lot of the `! empty() ? value : null` to `isset() ? value : null` it will solve most of these quirks.  But in some cases the ! empty() might be appropriate.

**Comment by jasonbahl** [comment]
I believe this has all been taken care of over several PRs in the past few months. If there's specific cases that still need addressed, let's create a new issue outlining the specifics.
