### ISSUE TITLE
Auto replace the key that contains hyphen for settings.

### ISSUE THREAD

**Issue by PlusA2M** [wp-graphql/wp-graphql#1392]
### Auto replace the key that contains hyphen for settings
In WordPress, we often use hyphen for something like `text-domain`, and that often contains hyphen like `wp-graphql`, when we use this as part of the settings, it's allowed by WordPress's core but it is not allowed in GraphQL to have hyphen, therefore I think an auto replacement from `-` to `_` would be nice for that scenario.

`$setting['key']           = preg_replace('/-/', '_', $key);`

**Comment by bhardie** [comment]
@PlusA2M can you provide code and settings you are trying to register so we can reproduce?

**Comment by PlusA2M** [comment]
> @PlusA2M can you provide code and settings you are trying to register so we can reproduce?

The different naming conventions between GraphQL and WordPress would cause this issue. Just using normal `register_graphql_settings` to dynamically expose some of the custom settings to GraphQL.

**Comment by jasonbahl** [comment]
@PlusA2M I'm going to close this as I believe this was fixed by #1953 and released in `v1.4.0`. 

If you update to `v1.4.*`+ and are still having this issue, please open a new issue and reference this one.
