### ISSUE TITLE
performance issues

### ISSUE THREAD

**Issue by vana-dev** [wp-graphql/wp-graphql#1394]
I have some performance issues, can't figure out what is the cause. Wordpress works very slow some time, returning 500 error on graphql. I check server logs. Is it normal?

![Zrzut ekranu 2020-07-21 o 11 53 59](https://user-images.githubusercontent.com/884763/88040701-93be6100-cb49-11ea-99bb-5e7d60a9431a.png)

**Comment by ririen** [comment]
For me also. Anyone know solution?

**Comment by bhardie** [comment]
@vana-dev @ririen There's not enough information in this issue for us to act on it.  If this is still a problem for you can you please open a new issue with enough information for us to reproduce.  For example, the slow requests, details about your environment, and reproduce steps.
