### ISSUE TITLE
Cannot query for comments

### ISSUE THREAD

**Issue by enricocupellini** [wp-graphql/wp-graphql#1395]

**Comment by enricocupellini** [comment]
Hello to everybody,
I am trying to integrate WPGraphQL to my gatsby project but I find an error when I try to perform a given query:

`query MyQuery {
  wpgraphql {
    comments {
      nodes {
        author {
          node {
            id
          }
        }
      }
    }
  }
}`

to reproduce this error I cloned the last version of your gatsby example project from here: "https://github.com/wp-graphql/gatsby-wpgraphql-blog-example"

and I installed "Local" software to run a Wordpress project locally : "https://localwp.com"

installed the last version of WPGraphQL plugin from master (and develop branch)
installed the last version of WPGraphiQL  plugin

everything run smoothly and I can see the develop version of the website on localhost, but when I try that query from the http://localhost:8000/__graphql  it gives me an error:

{
  "errors": [
    {
      "message": "Cannot query field \"node\" on type \"WPGraphQL_CommentAuthorUnion\".",
      "locations": [
        {
          "line": 6,
          "column": 11
        }
      ],
      "stack": [
        "GraphQLError: Cannot query field \"node\" on type \"WPGraphQL_CommentAuthorUnion\".",
        "    at Object.Field (/Users/enricocupellini/Documents/gatsby/gatsby-wordpress/gatsby-wpgraphql-blog-example/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:53:31)",
        "    at Object.enter (/Users/enricocupellini/Documents/gatsby/gatsby-wordpress/gatsby-wpgraphql-blog-example/node_modules/graphql/language/visitor.js:324:29)",
        "    at Object.enter (/Users/enricocupellini/Documents/gatsby/gatsby-wordpress/gatsby-wpgraphql-blog-example/node_modules/graphql/language/visitor.js:375:25)",
        "    at visit (/Users/enricocupellini/Documents/gatsby/gatsby-wordpress/gatsby-wpgraphql-blog-example/node_modules/graphql/language/visitor.js:242:26)",
        "    at validate (/Users/enricocupellini/Documents/gatsby/gatsby-wordpress/gatsby-wpgraphql-blog-example/node_modules/graphql/validation/validate.js:73:24)",
        "    at /Users/enricocupellini/Documents/gatsby/gatsby-wordpress/gatsby-wpgraphql-blog-example/node_modules/express-graphql/index.js:121:32",
        "    at runMicrotasks (<anonymous>)",
        "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
      ]
    }
  ]
}

**Comment by sboerrigter** [comment]
I think you should remove the `wpgraphql` field. This query does work for me:

```
query MyQuery {
  comments {
    nodes {
      author {
        node {
          id 
        } 
      } 
    } 
  } 
}
```

**Comment by bhardie** [comment]
There have been some changes to comments over the past several months.  For example, the commentAuthorUnion has been replaced with an interface.  There is a good chance comments are in a better state than when this issue was written.  If this is still a problem, can you please open a new issue with enough information that we can reproduce.
