### ISSUE TITLE
menuItems with location argument returns all menu items

### ISSUE THREAD

**Issue by sboerrigter** [wp-graphql/wp-graphql#1396]
I noticed that the menuItems query example in the [documentation](https://docs.wpgraphql.com/getting-started/menus/#menu-items) returns all menu items from all menu's and not just the items from the provided menu in the `where: {location:` argument.

## How to reproduce

1. Register two custom menu's in the theme's `functions.php` file with the following code:

```
add_action('init', function () {
    register_nav_menu('main', 'Main menu');
    register_nav_menu('footer', 'Footer menu');
});
```

2. Add two custom menus with some menu items and assign them to both menu locations.

3. Check the following query and see that it returns all menu items from both menu's instead of just the menu items from the `main` menu:

```
{
  menuItems(where: {location: MAIN}) {
    nodes {
      id
      label
      url
      locations
    }
  }
}
```

## Details

I am using the following WordPress plugins and versions:

- WordPress 5.4.2
- WP GraphQL 0.10.3
- WP GraphiQL 1.0.1

I have the same problem when I deactivate all other plugins and comment all other code in my theme.

Thanks in advance!

**Comment by jasonbahl** [comment]
@sboerrigter oof. This is a bug for sure. I confirmed this behavior. 

I'll work on a fix here shortly. 

Thanks for the detailed report!

**Comment by sboerrigter** [comment]
Thanks and good luck!

**Comment by jasonbahl** [comment]
@sboerrigter I opened a PR to address this: https://github.com/wp-graphql/wp-graphql/pull/1402

If you have time to confirm that it's working for you as well that would be great. 

I updated a test to cover this scenario better and prevent future regressions.

**Comment by sboerrigter** [comment]
@jasonbahl I just checked your PR. That indeed fixes the issue on my end. Thanks!
