### ISSUE TITLE
Field added with register_graphql_field() returns "false" if it is the first field in a query

### ISSUE THREAD

**Issue by sboerrigter** [wp-graphql/wp-graphql#1398]
I've added a GraphQL field to using the `register_graphql_field()` function. I noticed that the field returns `"false"` instead of the field value for the first node if this field is the first field in a query.

### How to reproduce

Register a GraphQL field with the following code:

```
// Add fields to all post types
add_action('graphql_register_types', function () {
    foreach (\WPGraphQL::get_allowed_post_types() as $postType) {
        $postTypeName = get_post_type_object($postType)->graphql_single_name;

        // Formatted date
        register_graphql_field($postTypeName, 'dateFormatted', [
            'type' => 'String',
            'resolve' => function ($post) {
                return get_the_date('', get_the_id($post));
            }
        ]);
    }
});
```

With the following query all posts return the formatted post date:

```
{
  posts {
    nodes {
      title
      dateFormatted
    }
  }
}

```

This returns:

```
{
  "data": {
    "posts": {
      "nodes": [
        {
          "title": "Deze heeft een header",
          "dateFormatted": "23 juli 2020"
        },
        {
          "title": "Nog zo’n mooie blogpost",
          "dateFormatted": "23 juli 2020"
        },
        {
          "title": "Blogpost test",
          "dateFormatted": "23 juli 2020"
        }
      ]
    }
  }
}
```

But if you move the added field to the first item in the query the first node returns false at `dateFormatted`:

```
{
  posts {
    nodes {
      dateFormatted
      title
    }
  }
}

```

This returns:
```
{
  "data": {
    "posts": {
      "nodes": [
        {
          "dateFormatted": "false",
          "title": "Deze heeft een header"
        },
        {
          "dateFormatted": "23 juli 2020",
          "title": "Nog zo’n mooie blogpost"
        },
        {
          "dateFormatted": "23 juli 2020",
          "title": "Blogpost test"
        }
      ]
    }
  }
}
```

I had the same issue with a different field, but instead of `"false"` it returned an empty string (`""`).

### Context

I am using the following WordPress plugins and versions:

- WordPress 5.4.2
- WP GraphQL 0.10.3
- WP GraphiQL 1.0.1

**Comment by jasonbahl** [comment]
@sboerrigter so the `$post` that is passed to the resolver is an instance of a `WPGraphQL\Model\Post` model, it's not a `WP_Post`. 

So the `get_the_id( $post )` might not work as you might expect here. 

Try the following:

```php
add_action( 'graphql_register_types', function() {
	foreach ( \WPGraphQL::get_allowed_post_types() as $postType ) {
		$postTypeName = get_post_type_object( $postType )->graphql_single_name;

		// Formatted date
		register_graphql_field( $postTypeName, 'dateFormatted', [
			'type'    => 'String',
			'resolve' => function( $post ) {
				return get_the_date( '', $post->databaseId );
			}
		] );
	}
} );
```

### In Action:

![Screen Shot 2020-07-24 at 4 52 04 PM](https://user-images.githubusercontent.com/1260765/88441343-0e97ae00-cdce-11ea-9d00-e230e6957af2.png)

**Comment by sboerrigter** [comment]
Ok, thanks for the explanation! It indeed works as expected if I use `$post->databaseId` or `$post->ID` like specified in the [documentation](https://docs.wpgraphql.com/getting-started/custom-fields-and-meta/#register-multiple-fields-specifying-type).
