### ISSUE TITLE
Syntax Error: Invalid number, expected digit but got: "W". (1:831)

### ISSUE THREAD

**Issue by MussadiqKhan** [wp-graphql/wp-graphql#1404]
Hello,

I am using the latest gatsby-source-wordpress-experimental and trying to fetch data from a WP site but I am getting below error.
Any help?

`Syntax Error: Invalid number, expected digit but got: "W". (1:831)
> 1 |  query NODE_LIST_QUERY($first:Int!,$after:String,){mediaItems(first:$first,after:$after,where:{parent:null}){nodes{altText ancestors(first:100){nodes{id}}author{node{id}}authorDatabaseId authorId caption wpChildren:children(first:100){nodes{id}}commentCount commentStatus comments(first:100){nodes{id}}contentType{node{id}}databaseId date dateGmt description desiredSlug enclosure guid id lastEditedBy{node{id}}link mediaDetails{file height meta{aperture camera caption copyright createdTimestamp credit focalLength iso keywords orientation shutterSpeed title}sizes{file height mimeType name sourceUrl width}width}mediaItemUrl mediaType mimeType modified modifiedGmt wpParent:parent{node{id __typename}}parentDatabaseId parentId sizes slug sourceUrl srcSet status template{__typename ... on DefaultTemplate{templateName}... on 100WidthTemplate{templateName}... on BlankPageTemplate{templateName}... on ContactTemplate{templateName}... on 
SideNavigationTemplate{templateName}}terms(first:100){nodes{id}}title uri __typename}pageInfo{hasNextPage endCursor}}}    | 

          ^

> 1 |  query NODE_LIST_QUERY($first:Int!,$after:String,){mediaItems(first:$first,after:$after,where:{parent:null}){nodes{altText ancestors(first:100){nodes{id}}author{node{id}}authorDatabaseId authorId caption wpChildren:children(first:100){nodes{id}}commentCount commentStatus comments(first:100){nodes{id}}contentType{node{id}}databaseId date dateGmt description desiredSlug enclosure guid id lastEditedBy{node{id}}link mediaDetails{file height meta{aperture camera caption copyright createdTimestamp credit focalLength iso keywords orientation shutterSpeed title}sizes{file height mimeType name sourceUrl width}width}mediaItemUrl mediaType mimeType modified modifiedGmt wpParent:parent{node{id __typename}}parentDatabaseId parentId sizes slug sourceUrl srcSet status template{__typename ... on DefaultTemplate{templateName}... on 100WidthTemplate{templateName}... on BlankPageTemplate{templateName}... on ContactTemplate{templateName}... on 
SideNavigationTemplate{templateName}}terms(first:100){nodes{id}}title uri __typename}pageInfo{hasNextPage endCursor}}}    | 

          ^

  SyntaxError: Syntax Error: Invalid number, expected digit but got: "W". (1:831)
  > 1 |  query NODE_LIST_QUERY($first:Int!  3m,$after:String,){mediaItems(first:$first,after:$a  fter,where:{parent:null}){nodes{altText ancestors(first:100  39m){nodes{id}}author{node{id}}authorDatabaseId authorId caption wpChildren:children(first:  100){nodes{id}}commentCount commentStatus comments(first:100){nodes{id}}contentType{node{id  }}databaseId date dateGmt description desiredSlug enclosure guid id lastEditedBy{node{id}}link mediaDetails{file hei  ght meta{aperture camera caption copyright createdTimestamp credit focalLength iso keywords orientation shutterSpeed   title}sizes{file height mimeType name sourceUrl width}width}mediaItemUrl mediaType mimeType modified modifiedGmt wp  Parent:parent{node{id __typename}}parentDatabaseId parentId sizes slug sourceUrl srcSet status template{__  typename ... on DefaultTemplate{templateName}... on 100WidthTemplate  9m{templateName}... on BlankPageTemplate{templateName}... on ContactTemplate  {templateName}... on SideNavigationTemplate{templateName}}terms(first:100){n  odes{id}}title uri __typename}pageInfo{hasNextPage endCursor}}}`

**Comment by jasonbahl** [comment]
@MussadiqKhan this looks like it's the same issue as reported in #1346 

Right now WPGraphQL isn't preventing invalid field and type names from being registered. . .but it should. 

@TylerBarnes, @CodeProKid and I have discussed this a bit and I think the plan going forward is to catch these invalid field/type names and prevent them from being added to the Schema in the first place, then outputting debug messages in GraphQL requests to help show _why_ they are not in in the Schema. 

this way, invalid fields will not break the Schema and existing queries can continue to work, but information can be output to help developers/site owners understand why fields they registered are not showing in the Schema. 

So, let's say we had something like: 

```
register_graphql_field( 'RootQuery', '111222', [
  'type' => 'String',
  'description' => __( 'some field named 111222', 'your-textdomain' ),
] );
```

WPGraphQL would detect that `111222` is an invalid field name and would create a Debug error and _not_ be added to the Schema. 

Then, when GraphQL Introspection or any query is executed, along with the `data` would be a `debug` log where messages would show that `field 111222 was not added to the schema because the field name is invalid. GraphQL field names must not start with a number` or something along those lines. 

```
{
  data: ...
  errors: ...
  extensions: {
     debug: [
       {
          type: "INVALID_FIELD_NAME",
          description: "Field 111222 was not added to the schema because the field name is invalid. GraphQL field names must not start with a number"
       },
     ],
  },
},
```

This might change a bit, but overall this is the direction we will head to allow developers the chance to change how fields/types are registered to the Schema while also allowing existing queries to execute.

**Comment by MussadiqKhan** [comment]
So, what is the solution for me? I am working on a client's website. What should I do now to make it work?

**Comment by jasonbahl** [comment]
Right now, we need to make sure there are now fields in the Schema that start with an integer. 

It looks like there are some page templates such as `100WidthTemplate` that seem to be causing the error. 

If there aren't other side-effects that you can't overcome, a quick-win would be to change the templates to start with a string instead of a number, such as `Template100Width` or something like that.

**Comment by jasonbahl** [comment]
@MussadiqKhan is your WPGraphQL endpoint public?

**Comment by MussadiqKhan** [comment]
@jasonbahl Check: http://www.sellerlift.com/graphql

**Comment by MussadiqKhan** [comment]
Thanks. I updated the name as you mentioned. However, I am facing another issue now. Please check.


`success  gatsby-source-wordpress  writing GraphQL queries to disk at ./WordPress/GraphQL/ - 0.523s
success  gatsby-source-wordpress  ingest WPGraphQL schema - 3.874s
success createSchemaCustomization - 5.836s
⠙ source and transform nodes
⠙ source and transform nodes
⠋  gatsby-source-wordpress  fetching nodes — 0 total
⠙ source and transform nodes
⠋  gatsby-source-wordpress  fetching nodes — 0 total
⠋  gatsby-source-wordpress  Category
⠹ source and transform nodes
⠋  gatsby-source-wordpress  fetching nodes — 0 total
⠋  gatsby-source-wordpress  Category
⠹ source and transform nodes
⠙  gatsby-source-wordpress  fetching nodes — 0 total
⠋  gatsby-source-wordpress  Category
⠹ source and transform nodes
⠙  gatsby-source-wordpress  fetching nodes — 0 total
⠙  gatsby-source-wordpress  Category
⠹ source and transform nodes
⠙  gatsby-source-wordpress  fetching nodes — 0 total
⠙  gatsby-source-wordpress  Category
⠹ source and transform nodes
⠙  gatsby-source-wordpress  fetching nodes — 0 total
⠙  gatsby-source-wordpress  Category
⠹ source and transform nodes
⠙  gatsby-source-wordpress  fetching nodes — 0 total
⠙  gatsby-source-wordpress  Category
⠹ source and transform nodes
⠙  gatsby-source-wordpress  fetching nodes — 0 total
⠙  gatsby-source-wordpress  Category
⠹ source and transform nodes
⠙  gatsby-source-wordpress  fetching nodes — 0 total
⠙  gatsby-source-wordpress  Category
⠹ source and transform nodes
⠙  gatsby-source-wordpress  fetching nodes — 0 total
⠙  gatsby-source-wordpress  Category
⠹ source and transform nodes
⠙  gatsby-source-wordpress  fetching nodes — 0 total
⠙  gatsby-source-wordpress  Category
⠹ source and transform nodes
⠙  gatsby-source-wordpress  fetching nodes — 0 total
⠙  gatsby-source-wordpress  Category
⠹ source and transform nodes
⠙  gatsby-source-wordpress  fetching nodes — 0 total
⠙  gatsby-source-wordpress  Category
⠸ source and transform nodes
⠙  gatsby-source-wordpress  fetching nodes — 0 total
⠙  gatsby-source-wordpress  Category
⠸ source and transform nodes
⠹  gatsby-source-wordpress  fetching nodes — 0 total
⠙  gatsby-source-wordpress  Category
⠸ source and transform nodes
⠹  gatsby-source-wordpress  fetching nodes — 0 total
⠹  gatsby-source-wordpress  Category
⠸ source and transform nodes
⠹  gatsby-source-wordpress  fetching nodes — 0 total
⠹  gatsby-source-wordpress  Category
⠸ source and transform nodes
⠹  gatsby-source-wordpress  fetching nodes — 0 total
⠹  gatsby-source-wordpress  Category
⠸ source and transform nodes
⠹  gatsby-source-wordpress  fetching nodes — 0 total
⠹  gatsby-source-wordpress  Category
⠸ source and transform nodes
⠹  gatsby-source-wordpress  fetching nodes — 0 total
⠹  gatsby-source-wordpress  Category
⠸ source and transform nodes
⠹  gatsby-source-wordpress  fetching nodes — 0 total
⠹  gatsby-source-wordpress  Category
⠸ source and transform nodes
⠹  gatsby-source-wordpress  fetching nodes — 0 total
⠹  gatsby-source-wordpress  Category
⠸ source and transform nodes
⠹  gatsby-source-wordpress  fetching nodes — 0 total
⠹  gatsby-source-wordpress  Category
⠸ source and transform nodes
⠹  gatsby-source-wordpress  fetching nodes — 0 total
⠹  gatsby-source-wordpress  Category
⠸ source and transform nodes
⠹  gatsby-source-wordpress  fetching nodes — 0 total
⠹  gatsby-source-wordpress  Category
⠼ source and transform nodes
⠹  gatsby-source-wordpress  fetching nodes — 0 total
⠹  gatsby-source-wordpress  Category
⠼ source and transform nodes
⠸  gatsby-source-wordpress  fetching nodes — 0 total
⠹  gatsby-source-wordpress  Category
⠼ source and transform nodes
⠸  gatsby-source-wordpress  fetching nodes — 0 total
⠸  gatsby-source-wordpress  Category
⠼ source and transform nodes
⠸  gatsby-source-wordpress  fetching nodes — 0 total
⠸  gatsby-source-wordpress  Category
⠼ source and transform nodes
⠸  gatsby-source-wordpress  fetching nodes — 0 total
⠸  gatsby-source-wordpress  Category
⠼ source and transform nodes
⠸  gatsby-source-wordpress  fetching nodes — 0 total
⠸  gatsby-source-wordpress  Category
⠼ source and transform nodes
⠸  gatsby-source-wordpress  fetching nodes — 0 total
⠸  gatsby-source-wordpress  Category
⠼ source and transform nodes
⠸  gatsby-source-wordpress  fetching nodes — 0 total
⠸  gatsby-source-wordpress  Category
⠼ source and transform nodes
⠸  gatsby-source-wordpress  fetching nodes — 0 total
⠸  gatsby-source-wordpress  Category
⠼ source and transform nodes
⠸  gatsby-source-wordpress  fetching nodes — 0 total
⠸  gatsby-source-wordpress  Category
⠼ source and transform nodes
⠸  gatsby-source-wordpress  fetching nodes — 0 total
⠸  gatsby-source-wordpress  Category
⠼ source and transform nodes
⠸  gatsby-source-wordpress  fetching nodes — 0 total
⠸  gatsby-source-wordpress  Category
⠴ source and transform nodes
⠸  gatsby-source-wordpress  fetching nodes — 0 total
⠸  gatsby-source-wordpress  Category
⠴ source and transform nodes
⠼  gatsby-source-wordpress  fetching nodes — 0 total
⠸  gatsby-source-wordpress  Category
⠴ source and transform nodes
⠼  gatsby-source-wordpress  fetching nodes — 0 total
⠼  gatsby-source-wordpress  Category
⠴ source and transform nodes
⠼  gatsby-source-wordpress  fetching nodes — 0 total
⠼  gatsby-source-wordpress  Category
⠴ source and transform nodes
⠼  gatsby-source-wordpress  fetching nodes — 0 total
⠼  gatsby-source-wordpress  Category
⠴ source and transform nodes
⠼  gatsby-source-wordpress  fetching nodes — 0 total
⠼  gatsby-source-wordpress  Category
⠴ source and transform nodes
⠼  gatsby-source-wordpress  fetching nodes — 0 total
⠼  gatsby-source-wordpress  Category
⠴ source and transform nodes
⠼  gatsby-source-wordpress  fetching nodes — 0 total
⠼  gatsby-source-wordpress  Category
⠴ source and transform nodes
⠼  gatsby-source-wordpress  fetching nodes — 0 total
⠼  gatsby-source-wordpress  Category
⠴ source and transform nodes
⠼  gatsby-source-wordpress  fetching nodes — 0 total
⠼  gatsby-source-wordpress  Category
⠴ source and transform nodes
⠼  gatsby-source-wordpress  fetching nodes — 0 total
⠼  gatsby-source-wordpress  Category
⠴ source and transform nodes
⠼  gatsby-source-wordpress  fetching nodes — 0 total
⠼  gatsby-source-wordpress  Category
⠦ source and transform nodes
⠼  gatsby-source-wordpress  fetching nodes — 0 total
⠼  gatsby-source-wordpress  Category
⠦ source and transform nodes
⠴  gatsby-source-wordpress  fetching nodes — 0 total
⠼  gatsby-source-wordpress  Category
⠦ source and transform nodes
⠴  gatsby-source-wordpress  fetching nodes — 0 total
⠴  gatsby-source-wordpress  Category
⠦ source and transform nodes
⠴  gatsby-source-wordpress  fetching nodes — 0 total
⠴  gatsby-source-wordpress  Category
⠦ source and transform nodes
⠴  gatsby-source-wordpress  fetching nodes — 0 total
⠴  gatsby-source-wordpress  Category
⠦ source and transform nodes
⠴  gatsby-source-wordpress  fetching nodes — 0 total
⠴  gatsby-source-wordpress  Category
⠦ source and transform nodes
⠴  gatsby-source-wordpress  fetching nodes — 0 total
⠴  gatsby-source-wordpress  Category
⠦ source and transform nodes
⠴  gatsby-source-wordpress  fetching nodes — 0 total
⠴  gatsby-source-wordpress  Category
⠦ source and transform nodes
⠴  gatsby-source-wordpress  fetching nodes — 0 total
⠴  gatsby-source-wordpress  Category
⠦ source and transform nodes
⠴  gatsby-source-wordpress  fetching nodes — 0 total
⠴  gatsby-source-wordpress  Category
⠦ source and transform nodes
⠴  gatsby-source-wordpress  fetching nodes — 0 total
⠴  gatsby-source-wordpress  Category
⠦ source and transform nodes
⠴  gatsby-source-wordpress  fetching nodes — 0 total
⠴  gatsby-source-wordpress  Category
⠧ source and transform nodes
⠴  gatsby-source-wordpress  fetching nodes — 0 total
⠴  gatsby-source-wordpress  Category
⠧ source and transform nodes
⠦  gatsby-source-wordpress  fetching nodes — 0 total
⠴  gatsby-source-wordpress  Category
⠧ source and transform nodes
⠦  gatsby-source-wordpress  fetching nodes — 0 total
⠦  gatsby-source-wordpress  Category
⠧ source and transform nodes
⠦  gatsby-source-wordpress  fetching nodes — 0 total
⠦  gatsby-source-wordpress  Category
⠧ source and transform nodes
⠦  gatsby-source-wordpress  fetching nodes — 0 total
⠦  gatsby-source-wordpress  Category
⠧ source and transform nodes
⠦  gatsby-source-wordpress  fetching nodes — 0 total
⠦  gatsby-source-wordpress  Category
⠧ source and transform nodes
⠦  gatsby-source-wordpress  fetching nodes — 0 total
⠦  gatsby-source-wordpress  Category
⠧ source and transform nodes
⠦  gatsby-source-wordpress  fetching nodes — 0 total
⠦  gatsby-source-wordpress  Category
⠧ source and transform nodes
⠦  gatsby-source-wordpress  fetching nodes — 0 total
⠦  gatsby-source-wordpress  Category
⠧ source and transform nodes
⠦  gatsby-source-wordpress  fetching nodes — 0 total
⠦  gatsby-source-wordpress  Category
⠧ source and transform nodes
⠦  gatsby-source-wordpress  fetching nodes — 0 total
⠦  gatsby-source-wordpress  Category
⠧ source and transform nodes
⠦  gatsby-source-wordpress  fetching nodes — 0 total
⠦  gatsby-source-wordpress  Category

 ERROR 

 gatsby-source-wordpress  Request failed with status code 500

Error occured while fetching nodes of the "Comment" type.    

GraphQL request to http://www.sellerlift.com/graphql failed. 

Please ensure the following statements are true
  - your WordPress URL is correct in gatsby-config.js
  - your server is responding to requests
  - WPGraphQL and WPGatsby are installed in your WordPress backend

⠧ source and transform nodes
⠦  gatsby-source-wordpress  fetching nodes — 0 total
⠦  gatsby-source-wordpress  Category
⠦  gatsby-source-wordpress  fetching nodes — 0 total
⠦  gatsby-source-wordpress  Category
not finished source and transform nodes - 1.974s
⠦  gatsby-source-wordpress  fetching nodes — 0 total
⠦  gatsby-source-wordpress  Category
⠦  gatsby-source-wordpress  Category
not finished  gatsby-source-wordpress  fetching nodes - 1.857s - 0 total
⠦  gatsby-source-wordpress  Category
not finished  gatsby-source-wordpress  Category - 1.898s
not finished  gatsby-source-wordpress  Comment - 1.917s
not finished  gatsby-source-wordpress  ContentType - 1.916s
not finished  gatsby-source-wordpress  MenuItem - 1.921s
not finished  gatsby-source-wordpress  Menu - 1.942s
not finished  gatsby-source-wordpress  Page - 1.940s
not finished  gatsby-source-wordpress  Post - 1.932s
not finished  gatsby-source-wordpress  Tag - 1.921s
not finished  gatsby-source-wordpress  Taxonomy - 1.899s
not finished  gatsby-source-wordpress  User - 1.873s`

It gave me three recommendations and I have already made sure that they are correct.

**Comment by bhardie** [comment]
I believe this was resolved with https://github.com/wp-graphql/wp-graphql/pull/1555.  If this is still a problem, please open a new issue and reference this issue for conext.
