### ISSUE TITLE
`asPreview` doesn't use single autosave when `define( 'WP_POST_REVISIONS', FALSE );` is set

### ISSUE THREAD

**Issue by TylerBarnes** [wp-graphql/wp-graphql#1408]
Some hosts like WPE add `define( 'WP_POST_REVISIONS', FALSE );` by default to new installations. 
https://wordpress.org/support/article/revisions/#revision-options indicates that this setting should store 1 autosave. Previewing with vanilla WP preview shows updated content. Looks like there's a bug here in the resolver with asPreview

**Comment by jasonbahl** [comment]
I've confirmed this behavior. Looking into it.

**Comment by jasonbahl** [comment]
@TylerBarnes #1426 should resolve this.
