### ISSUE TITLE
[Docs] Add Caching to Guides

### ISSUE THREAD

**Issue by henrikwirth** [wp-graphql/wp-graphql#1414]
Since there were some interesting conversations about caching on Slack, I'd like to make sure the info doesn't get lost and add it to the Documentation Guides.

**Jason:**
There are different types of cache.
For client side cache when using GraphQL, I recommend using Apollo. I believe I read that you're using Angular, and Apollo has an Angular integration you can read more about here: https://www.apollographql.com/docs/angular/
For server-side cache, there are many many options for this.
A lot of managed WP hosts (such as WP Engine) take care of at least persistent object caching for you without needing any extra plugins. Persistent Object caching means that objects such as Posts, Users, etc are placed in a cache that persists across sessions, so many requests from different users for Post A will get a cached copy of Post A instead of talking to the SQL database.
If you're not on a managed host that provides object caching, there are many plugins that offer this. I don't have a specific recommendation. If I'm not mistaken, believe WordPress.com VIP uses this plugin or a variation of it: https://wordpress.org/plugins/batcache/
Object cache invalidation is generally straightforward. Whenever an object (Post, User, etc) is created/updated/deleted, update the cache for said object.
Query caching is another beast that's less straight-forward and can get more complicated more quickly, and there's currently no "one size fits all" plugin that solves this.
Even if you have objects in a cache, you still have to run queries to determine what objects to return.
You can store queries in WordPress transients, but you have to figure out how to properly invalidate the queries. This can get pretty complicated, because many variables can affect queries.
A lot of times, I see queries being cached for a random amount of time. For example, 3 minutes. Meaning, anytime a user asks for said query for 3 minutes, they'll get the same results, then at 3 minutes and 1 second, the SQL will re-execute and get new results and cache them for the next 3 minutes.
TTL (time to live) caches based on a timestamp are the easiest to invalidate, but can lead to users being served stale data, so depending on your use case they may or may not be worth the tradeoff.
You could trigger various actions to invalidate caches as well. For example, if you have a query that returns posts, you could just automatically invalidate the cache when certain actions like wp_insert_post / wp_delete_post, etc are run.

**Seagyn Davis**
If you're a Redis fanboy like me then you can use https://wordpress.org/plugins/redis-cache/

**codeprokid**
Yeah there are some good docs on how the WP object cache works here: https://codex.wordpress.org/Class_Reference/WP_Object_Cache I would start by getting that setup and see how far that takes you, since the setup is pretty simple and gets you some nice wins. Custom caching implementations are usually pretty complicated to get setup, and the invalidation logic is a lot of overhead to maintain, so I would only go that route as a last resort.
You could also use something like persisted queries if you go the Apollo client route https://github.com/Quartz/wp-graphql-persisted-queries

I'll make a PR and will attempt to bundle that information somehow.

**Comment by lance-anderson** [comment]
Thank you @henrikwirth for capturing these notes. Super helpful. I wonder if there is a recommended way to leverage Automatic Persisted Queries on the server-side or updated documentation?

I've read the conversation on https://github.com/wp-graphql/wp-graphql/issues/590 and looked at the [wp-graphql-persisted-queries](https://github.com/Quartz/wp-graphql-persisted-queries) and [wp-graphql-lock](https://github.com/valu-digital/wp-graphql-lock) plugins but it's unclear if either are being used/maintained.

**Comment by lance-anderson** [comment]
For others looking, I can confirm that using [wp-graphql-lock](https://github.com/valu-digital/wp-graphql-lock) worked as expected without any more effort than installing the plugin and activating it afterward.

**Comment by jasonbahl** [comment]
There is a conversation here about this topic: https://github.com/wp-graphql/wp-graphql/discussions/1478

I've also started collecting more thoughts on how WPGraphQL can provide better options for caching. 

We'll be exploring native support for Persisted Queries as well as options for whole query and field caching, similar to what @esamattis has done with WPGraphQL Cache: https://github.com/valu-digital/wp-graphql-cache

I'm going to close this issue for now, but some actionable issues will be coming soon!
