### ISSUE TITLE
Move databaseId field to its own interface

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#1417]
In v0.11 the `UniformResourceIdentifiable` Interface was applied to the `ContentType` type. The `UniformResourceIdentifiable` Interface defines the field `databaseId` as a `nonNull Int`., but the `ContentType` type doesn't have a DatabaseId, so when querying for the `databaseId` field on a ContentType we get an error.

## Propose Solution:
The field `databaseId` should be moved out of the `UniformResourceIdentifiable` Interface and into its own `DatabaseId` interface and applied to Types that actually do have a DatabaseId

**Comment by rodrigo-arias** [comment]
Hi @jasonbahl,

I have updated all the dependencies of my Gatsby project and I ran into an error which is probably the one you mention here.

![image](https://user-images.githubusercontent.com/11416255/89449390-5f44ca80-d72f-11ea-8891-c382a2067a92.png)

This is the error on gatsby-source-wordpress-experimental
```Error path: contentTypes.nodes[1].databaseId```

Maybe a temporary workaround for whoever finds the error and doesn't need the field is to [exclude](https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/master/docs/plugin-options.md#excludefieldnames-array) it.
```excludeFieldNames: [`databaseId`]```

Thanks

**Comment by jasonbahl** [comment]
@rodrigo-arias yes, there is a PR to fix this already. It's _technically_ a breaking change to the WPGraphQL Schema so it will become v0.12.0 here shortly.
