### ISSUE TITLE
I didn't get the excerpt of the post normally wp(5.5)

### ISSUE THREAD

**Issue by Hansanghyeon** [wp-graphql/wp-graphql#1430]
I didn't get the excerpt of the post normally

before
WordPress 5.4
wp-graphql 0.10.3

after
WordPress 5.5
wp-graphql 0.12.1

Not working properly in WordPress 5.5

![](https://storage.googleapis.com/wp-ome/2020-08-12-5.41.19.png)

Importing excerpt seems to be different since wordpress 5.5

**Comment by jasonbahl** [comment]
@Hansanghyeon Thanks for the report. 

Is there any difference in the Post Edit page in the WP Admin between 5.4 and 5.5?

**Comment by Hansanghyeon** [comment]
@jasonbahl 

After installing it from the official homepage with WordPress, I installed the wp graphql plugin and tested it.  There is nothing other than these two.

**Comment by riaanlom** [comment]
I have the same issue when updating to WordPress 5.5. It's a WordPress issue. The breaking change seems to be in wp-includes/formatting.php 
function wp_trim_excerpt line 3811
`if ( '' === $text )`

Previous versions of WP used == instead of ===

**Comment by riaanlom** [comment]
> I have the same issue when updating to WordPress 5.5. It's a WordPress issue. The breaking change seems to be in wp-includes/formatting.php
> function wp_trim_excerpt line 3811
> `if ( '' === $text )`
> 
> Previous versions of WP used == instead of ===

I opened a ticked with wordpress. They will fix it in the next release 
[](https://core.trac.wordpress.org/ticket/51042)
