### ISSUE TITLE
Not receiving content or excerpt data

### ISSUE THREAD

**Issue by oliverfeher** [wp-graphql/wp-graphql#1431]
I'm running the following `gatsby-config` :

![Screen Shot 2020-08-12 at 12 45 10 PM](https://user-images.githubusercontent.com/55335331/90043257-dcc18b00-dc99-11ea-9646-e890da438bd0.png)

I'm not receiving any content or excerpt data for WPPages/WPPost.
Getting a warning message like this:

`An empty string was returned instead of a response when making a GraphQL request.`
`This may indicate that you have a WordPress filter running which is causing WPGraphQL`
`to return an empty string instead of a response.`
`Please open an issue with a reproduction at`
`https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/new`
`for more help`
`Error occured while fetching nodes of the "Post" type.`

<img width="1598" alt="Screen Shot 2020-08-12 at 12 45 46 PM" src="https://user-images.githubusercontent.com/55335331/90043373-05498500-dc9a-11ea-8dd4-f688bc7d2eb9.png">

Plugins installed:

`"gatsby-source-wordpress-experimental": "^1.3.6"`

<img width="1063" alt="Screen Shot 2020-08-12 at 12 17 28 PM" src="https://user-images.githubusercontent.com/55335331/90043466-23af8080-dc9a-11ea-853b-eef820b3a5ab.png">

**Comment by ttstauss** [comment]
@oliverfeher, have you found a solution for this? I am getting the same error.

**Comment by ttstauss** [comment]
@oliverfeher, I added the following from the [gatsby-starter-wordpress-twenty-twenty](https://github.com/henrikwirth/gatsby-starter-wordpress-twenty-twenty/blob/master/gatsby-config.js) starter and it seems to work fine for me now.

```
{
      resolve: `gatsby-source-wordpress-experimental`,
      options: {
        url: process.env.WPGRAPHQL_URL,
        verbose: true,
        develop: {
          hardCacheMediaFiles: true,
        },
        debug: {
          graphql: {
            writeQueriesToDisk: true,
          },
        },
        html: {
          fallbackImageMaxWidth: 800,
        },
        // fields can be excluded globally.
        // this example is for wp-graphql-gutenberg.
        // since we can get block data on the `block` field
        // we don't need these fields
        excludeFieldNames: [`blocksJSON`, `saveContent`],
        type: {
          Post: {
            limit:
              process.env.NODE_ENV === `development`
                ? // Lets just pull 50 posts in development to make it easy on ourselves.
                  35
                : // And then we can pull all posts in production
                  null,
          },
          // this shows how to exclude entire types from the schema
          // this example is for wp-graphql-gutenberg
          CoreParagraphBlockAttributesV2: {
            exclude: true,
          },
        },
      },
    },
```
I'll have to mess around with each setting to see which one did it, but it's in there somewhere 😆

**Comment by ManasiRoy** [comment]
wpPage content showing null always. Can't fetch data - a single page of About us content. gatsby-source-wordpress this plugin I'm using.
