### ISSUE TITLE
exclude post from posts list

### ISSUE THREAD

**Issue by vana-dev** [wp-graphql/wp-graphql#1434]
Hi, I can't figure out how exclude specific post(by ID type Slug) from posts list query. It's even possible? I see similar option in categories `where: {exclude: ""}` It's also very easy to do in typical WP_Query, so why it is not yet implemented in wp-graphql?

**Comment by thakkaryash94** [comment]
I don't think, you care exclude by slug, but you can exclude by databaseId.

```graphql
{
  posts(where: {notIn: ["1"]}) {
    nodes {
      id
      databaseId
    }
  }
}
```
Where 1 is databaseId of the post.

**Comment by vana-dev** [comment]
```
add_action( 'graphql_register_types', function() {
	register_graphql_fields( 'RootQueryToPostConnectionWhereArgs', [
		'excludeBySlug' => [
			 'type' => 'ID',
			 'description' => 'Exclude posts by slug',
		]
	] );
} );

add_filter( 'graphql_post_object_connection_query_args', function( $query_args, $source, $args, $context, $info ) {
	if ( isset( $args['where']['excludeBySlug'] )) {
		$query_args['post__not_in'] = array (url_to_postid($args['where']['excludeBySlug']));
	}
	return $query_args;
}, 10, 5 );
```

**Comment by dbertella** [comment]
Can we add the above to the lib? I was look for this exact thing it can be really nice to have a excludeBySlug when you are querying a post by slug I hope to use this to get other posts from same category excluding itself

**Comment by warudin** [comment]
It would be great if excluding posts by slug was possible by default.

Or are we missing an obvious way to exclude the current post by slug when loading more posts?

**Comment by justlevine** [comment]
`RootQueryToPostConnectionWhereArgs.notIn` will let you exclude by post _ID_s, but not slugs. This is in line with the [WP_Query API](https://developer.wordpress.org/reference/classes/wp_query/#post-page-parameters).

Related: https://github.com/wp-graphql/wp-graphql/issues/1385 (tl;dr creating a standard schema for filters that isn't necessarily tied to WP's expectations).

**Comment by opr-inzn** [comment]
@vana-dev how would this work for excluding pages?

**Comment by justlevine** [comment]
@opr-inzn just register the field to RootQueryTo**Page**ConnectionWhereArgs instead of `...ToPostConnection...`.

**Comment by justlevine** [comment]
Closing as the current WPGraphQL pattern is to adhere as much as possible to WP Core, which [as noted](https://github.com/wp-graphql/wp-graphql/issues/1434#issuecomment-1086165372) doesnt support slugs. Plus, [a workaround](https://github.com/wp-graphql/wp-graphql/issues/1434#issuecomment-679606203) has been provided for anyone who wants to make this change locally.

#1385 will revisit this and possibly provide a path for inclusion.
