### ISSUE TITLE
Does WP-Cron get triggered via /graphql requests?

### ISSUE THREAD

**Issue by TylerBarnes** [wp-graphql/wp-graphql#1438]
I haven't taken a look and don't have time to right now but this is a question we had just now. We should make sure cron is triggered.

**Comment by smthomas** [comment]
I can confirm that wp-cron does get triggered if you view /graphql from a browser. I would assume this would still get triggered through any http request to that endpoint. See gif for confirmation:

![image](https://user-images.githubusercontent.com/1393742/95392954-47203180-08bf-11eb-8898-0ce3c3e177a0.png)

**Comment by TylerBarnes** [comment]
Awesome! 😄 
How did you verify?

**Comment by smthomas** [comment]
![wpcron-wpgraphql](https://user-images.githubusercontent.com/1393742/95395438-3aeaa300-08c4-11eb-8d0f-7ccc91416701.gif)

**Comment by TylerBarnes** [comment]
🙌
