### ISSUE TITLE
Saving/Updating any ACF flexible content 

### ISSUE THREAD

**Issue by garryburch** [wp-graphql/wp-graphql#1439]
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/vhosts/NAGUSA/naegeliusa-dev.com/public_html/wp-content/plugins/wp-graphql-0.11.0/src/Data/Connection/AbstractConnectionResolver.php on line 498

wp-graphl 0.11.0

**Comment by bhardie** [comment]
I believe this has been resolved since the issue was created.  If you are still having problems, please create a new issue with enough detail that we can reproduce.
