### ISSUE TITLE
Orderby functionality of terms does not mirror that of posts.

### ISSUE THREAD

**Issue by jeremyProwseYS** [wp-graphql/wp-graphql#1444]
When trying to order terms the functionality that is currently available is limited to the field you want to order by and no more. In the post structure you have the option to choose both the filed to order by and the direction of ordering, ie: ASC, DESC...

Post order options:
![posts-order-options](https://user-images.githubusercontent.com/70550299/91780488-d052a180-ec4b-11ea-9c64-915db839aa11.png)

Term order options:
![terms-order-options](https://user-images.githubusercontent.com/70550299/91780491-d183ce80-ec4b-11ea-9f96-d98a59bd763c.png)

**Comment by jeremyProwseYS** [comment]
Pull request to provide a fix:
#1445

**Comment by justlevine** [comment]
As of writing (v1.7.2) `RootQueryToTermNodeConnectionWhereArgs` have separate `order` and `orderby` arguments, instead of the `orderby { field, order }` object fields have. 

Completing the change (for a consistent API) would require a breaking schema change.

**Comment by jasonbahl** [comment]
In addition to what @justlevine pointed out (about being a breaking change) the WP_Term_Query class doesn't support multiple order/orderby values either: https://core.trac.wordpress.org/browser/tags/6.0.2/src/wp-includes/class-wp-term-query.php#L101

It might be possible to support this with some deeper filters in the WP_Term_Query class and mapping to some SQL statements. I'd recommend exploring that as an extension, and if it works we can consider support in core WPGraphQL.
