### ISSUE TITLE
Trying to get property of non-object in (src/Data/Loader/PostObjectLoader.php) line 114

### ISSUE THREAD

**Issue by MitchEff** [wp-graphql/wp-graphql#1446]
This has happened with every single instance of WP GraphQL for all of our clients. I don't really know what causes it (all have totally separate databases, fields, post types, hosts etc), but we've been fixing it by adding: 

	if(!$post_object){
		continue;
	}

Just before L114. Obviously this breaks every time we update the plugin so it's a bit of a pain. Making an isolated, cloneable repo is probably a bit more effort than it's worth - I just thought I'd point out that this breaks all the time, and that's a reasonable band-aid fix.

**Comment by jasonbahl** [comment]
@MitchEff what version of WPGraphQL are you on? 

I believe the issue you're talking about was resolved several months ago. Here's Line 114 in the current version: https://github.com/wp-graphql/wp-graphql/blob/develop/src/Data/Loader/PostObjectLoader.php#L114

I believe what you're fixing is fixed already here: https://github.com/wp-graphql/wp-graphql/blob/develop/src/Data/Loader/PostObjectLoader.php#L132-L134

**Comment by MitchEff** [comment]
Hmmm I'm on 0.8.3, but I just updated it from within WP. Perhaps WP has the wrong version?

**Comment by jasonbahl** [comment]
WPGraphQL is available on Github or Composer, it isn't on the wordpress.org repository yet so it shouldn't be available for upgrading from WordPress. 

How are you doing the updates from within WordPress? 

Maybe a screenshot of what you see when you upgrade?

**Comment by MitchEff** [comment]
😐

Maybe I'm going crazy, haha. Our local version had the fix I mentioned earlier in it, then we deployed it to production and updated all our plugins and the fix had disappeared. I had to copy the plugin folder back over. 

Leave this with me for now, haha. I'm confused.
