### ISSUE TITLE
ACF Field Group Location Rules by Template Name doesn't query the field name in GraphQL

### ISSUE THREAD

**Issue by r1987** [wp-graphql/wp-graphql#1449]
### An *isolated* way to reproduce the behavior
1. Create a new field group
2. Add new fields
3. Add the Location rule to: Show this field group if Page Template is equal to `<your-template-name>`
4. Activate Show in GraphQL
5. Add your GraphQL Field Name
6. Try to query your field,  get an error "Cannot query field `<your-field-name>`.

### The behavior you expect to see, and the actual behavior
GraphQL should query the field when its shown on a Page Template, but it doesn't. It does show the field if I don't make any conditionals for the Field Group, but this isn't expected.

### Version
WPGraphQL version 0.12.0

### Used plug-ins
- WP GraphQL version 0.12.0
- WP GraphiQL version 1.0.1
- WPGraphQL for Advanced Custom Fields version 0.3.5
- Advanced Custom Fields PRO version 5.9.0

**Comment by magicspon** [comment]
https://github.com/wp-graphql/wp-graphql-acf/issues/135

**Comment by bhardie** [comment]
Resolved by latest version of wp-graphql-acf: https://github.com/wp-graphql/wp-graphql-acf/releases/tag/v0.5.2
