### ISSUE TITLE
Querying pages by URI still having issues

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#1451]
Release v0.12.2 attempted to address some issues with querying pages by URI, but there are still some bugs that need to be addressed. 

### Register Post Type:

```
/**
 * Register Area Profile post type
 */
add_action(
    'init',
    function () {
        $labels = array(
            'name'                  => _x( 'Area Profiles', 'Post type general name', 'leadhome' ),
            'singular_name'         => _x( 'Area Profile', 'Post type singular name', 'leadhome' ),
            'menu_name'             => _x( 'Area Profiles', 'Admin Menu text', 'leadhome' ),
            'name_admin_bar'        => _x( 'Area Profile', 'Add New on Toolbar', 'leadhome' ),
            'add_new'               => __( 'Add New', 'leadhome' ),
            'add_new_item'          => __( 'Add New Area Profile', 'leadhome' ),
            'new_item'              => __( 'New Area Profile', 'leadhome' ),
            'edit_item'             => __( 'Edit Area Profile', 'leadhome' ),
            'view_item'             => __( 'View Area Profile', 'leadhome' ),
            'all_items'             => __( 'All Area Profiles', 'leadhome' ),
            'search_items'          => __( 'Search Area Profiles', 'leadhome' ),
            'parent_item_colon'     => __( 'Parent Area Profiles:', 'leadhome' ),
            'not_found'             => __( 'No area profiles found.', 'leadhome' ),
            'not_found_in_trash'    => __( 'No area profiles found in Trash.', 'leadhome' ),
            'featured_image'        => _x( 'Area Profile Featured Image', 'Overrides the "Featured Image" phrase for this post type. Added in 4.3', 'leadhome' ),
            'set_featured_image'    => _x( 'Set featured image', 'Overrides the "Set featured image" phrase for this post type. Added in 4.3', 'leadhome' ),
            'remove_featured_image' => _x( 'Remove cover image', 'Overrides the "Remove featured image" phrase for this post type. Added in 4.3', 'leadhome' ),
            'use_featured_image'    => _x( 'Use as cover image', 'Overrides the "Use as featured image" phrase for this post type. Added in 4.3', 'leadhome' ),
            'archives'              => _x( 'Area Profile archives', 'The post type archive label used in nav menus. Default "Post Archives". Added in 4.4', 'leadhome' ),
            'insert_into_item'      => _x( 'Insert into area profile', 'Overrides the "Insert into post"/"Insert into page" phrase (used when inserting media into a post). Added in 4.4', 'leadhome' ),
            'uploaded_to_this_item' => _x( 'Uploaded to this area profile', 'Overrides the "Uploaded to this post"/"Uploaded to this page" phrase (used when viewing media attached to a post). Added in 4.4', 'leadhome' ),
            'filter_items_list'     => _x( 'Filter area profiles list', 'Screen reader text for the filter links heading on the post type listing screen. Default "Filter posts list"/"Filter pages list". Added in 4.4', 'leadhome' ),
            'items_list_navigation' => _x( 'Area Profiles list navigation', 'Screen reader text for the pagination heading on the post type listing screen. Default "Posts list navigation"/"Pages list navigation". Added in 4.4', 'leadhome' ),
            'items_list'            => _x( 'Area Profiles list', 'Screen reader text for the items list heading on the post type listing screen. Default "Posts list"/"Pages list". Added in 4.4', 'leadhome' ),
        );
        $args = array(
            'labels'              => $labels,
            'public'              => true,
            'publicly_queryable'  => true,
            'show_ui'             => true,
            'show_in_menu'        => true,
            'query_var'           => true,
            'rewrite'             => [
                'slug' => 'area-profiles',
                'with_front' => false
            ],
            'capability_type'     => 'page',
            'has_archive'         => false,
            'hierarchical'        => true,
            'menu_position'       => null,
            'supports'            => array( 'title', 'editor', 'author', 'thumbnail', 'excerpt', 'page-attributes' ),
            'show_in_rest'        => true,
            'rest_base'           => 'area-profiles',
            'show_in_graphql'     => true,
            'graphql_single_name' => 'areaProfile',
            'graphql_plural_name' => 'areaProfiles',
        );
        register_post_type( 'area_profile', $args );
    }
);
```

### Create some posts in that post type, then query them with WPGraphQL

![Screen Shot 2020-09-04 at 8 04 28 AM](https://user-images.githubusercontent.com/1260765/92248072-5c034280-ee85-11ea-899a-c18f43df9ba6.png)

### Query by URI returns null

Query the posts by URI and they return null

![Screen Shot 2020-09-04 at 8 07 12 AM](https://user-images.githubusercontent.com/1260765/92248316-b9978f00-ee85-11ea-8696-dac2bd11f673.png)

### Expected result:

![Screen Shot 2020-09-04 at 8 08 39 AM](https://user-images.githubusercontent.com/1260765/92248400-d9c74e00-ee85-11ea-8e28-7cc9d1658917.png)

**Comment by tim9009** [comment]
I would also like to add to this a related issue I just encountered. I have two pages with the same slug `karriere`, and they are available at `/karriere/` and `/de/karriere/`. This may be bad practice, but it is an artifact of one word being the same in two languages and the client wanting neat urls.

I would expect a query for `page (id: "/karriere/", idType: URI) {` to return the page with uri `/karriere/` but instead it returns the page with uri `/de/karriere/`. It would be preferable to have the `idType: URI` be an exact match or else I sadly can not use this approach to getting page data, which would complicate my frontend a lot.

**Comment by seagyn** [comment]
@tim9009 how are you achieving get the `/de` prefix?

**Comment by tim9009** [comment]
@seagyn Yes it is a translation made with Polylang. In this case I don't think it matters though as I am just trying to get a page with the matching uri. To clarify: `/karriere/` and `/de/karriere/` are two different pages, though they are translations of each other. When I query for `page (id: "/karriere/", idType: URI) {`I get the page with the uri `/de/karriere/` page and not the expected page with uri `/karriere/`. For other pages this seems to work as intended. The only difference I could think of for these two pages is that they both have the same slug.

**Comment by seagyn** [comment]
@tim9009 thanks for the feedback. I want to check if the latest update fixes this so needed to recreate your setup.

On a side note, have you seen this: https://github.com/valu-digital/wp-graphql-polylang (haven't tested with the latest updates but it's good to know about it).

**Comment by tim9009** [comment]
@seagyn Thank you, I already have `wp-graphql-polylang` installed for this project 😊 Please let me know if you need any more information or if I can contribute somehow. It would be really helpful if a solution to this could be found in the near future.

**Comment by tim9009** [comment]
@seagyn Also as additional context, here is the result of a `pages` query with the slug:

<img width="978" alt="Skjermbilde 2020-09-07 kl  09 55 55" src="https://user-images.githubusercontent.com/2582197/92362545-6ffeac80-f0f0-11ea-8614-ff3780c6e5b8.png">

**Comment by seagyn** [comment]
@jasonbahl so this works locally when we test but as soon as I take it into our test environment it only works without the prefix of `/area-profiles`. Super frustrating to debug :(

**Comment by tim9009** [comment]
I updated to the latest version and tested it out. The issue i mentioned still persists.

**Comment by jasonbahl** [comment]
🤔  I'll look into things a bit more with Polylang

**Comment by jasonbahl** [comment]
@tim9009 when I try to make a translated page with the same slug using PolyLang WordPress automatically adds `-2` to the slug

Like I have: 

`test-polylang` and when I created a translation it created `es/test-polylang-2`

**Comment by jasonbahl** [comment]
@tim9009 I tried to replicate your scenario, but it seems that WordPress prevents you from having the same slug in the first place. 

![polylang-slugs](https://user-images.githubusercontent.com/1260765/93114041-4e18a300-f677-11ea-88e3-b1cf29431c97.gif)

Can you share more details about how you were able to get 2 pages with the same slug?

**Comment by tim9009** [comment]
@jasonbahl Thank you for looking in to it! Yes that is correct. That behaviour can be disabled with the `wp_unique_post_slug` filter which will then allow you to create multiple posts and pages with the same slug. This can probably be considered an edge case, but it would at least in my case be extremely helpful to have this work as intended with duplicate slugs.
