### ISSUE TITLE
Filters to expose just selected WP types

### ISSUE THREAD

**Issue by spiralni** [wp-graphql/wp-graphql#1456]
Currently I am working on WebAPI and I am registering my own CPT. What I want is to hide all the WP default types (posts, taxonomies, etc) and only show my types. Is there any way to tell WPGraphql to NOT to expose some types?

Thanks in advance.

**Comment by jacobarriola** [comment]
@spiralni There are a couple filters that may help with this.

Looking at the source code, looks like there's:

* `graphql_post_entities_allowed_post_types` defined https://github.com/wp-graphql/wp-graphql/blob/develop/wp-graphql.php#L488
* `graphql_term_entities_allowed_taxonomies` defined graphql_term_entities_allowed_taxonomies

**Comment by spiralni** [comment]
@jacobarriola thank you very much! that is exactly what I was looking for.
