### ISSUE TITLE
title(format: RAW) requires authentication when requested server-side

### ISSUE THREAD

**Issue by sven-ra** [wp-graphql/wp-graphql#1457]
Hello!

I am building a website with Nuxt and for the CMS I have Wordpress + WPGraphql.
When I try to query "title(format: RAW)" for the default Post post type it all works fine. It also works fine when the requests are made from the client side. But when I do a request from server-side it returns NULL. I tried to do the request with a refreshToken set in the request headers and then it returned the title as expected.

## Version
WPGraphQL version 0.12.0

## Used plug-ins
WP GraphQL version 0.12.2
WP GraphiQL version 1.0.1
WPGraphQL for Advanced Custom Fields version 0.3.5
Advanced Custom Fields PRO version 5.9.1
WPGraphQL CORS version 1.0.1
WPGraphQL JWT Authentication version 0.4.0

**Comment by jasonbahl** [comment]
This is proper behavior. In WordPress, raw titles are only exposed to authenticated users. Public users see titles after they've been passed through filters. 

> I tried to do the request with a refreshToken set in the request headers and then it returned the title as expected.

So is this an issue with an expired token then? If it works after refreshing the token, then this seems like correct behavior? 🤔

**Comment by sven-ra** [comment]
> This is proper behavior. In WordPress, raw titles are only exposed to authenticated users. Public users see titles after they've been passed through filters.

I see I did not know that. Sometimes we use &shy; inside titles so that's why I need to get the RAW title.

> 
> > I tried to do the request with a refreshToken set in the request headers and then it returned the title as expected.
> 
> So is this an issue with an expired token then? If it works after refreshing the token, then this seems like correct behavior? 🤔

I would use the refreshToken only on Mutations or getting post previews for authenticated users. I don't want to create a refreshToken for every request on the page. The site in question runs on NuxtJS and on Node. So every time somebody visits the site a request for the Posts is being made. I wonder how can I get the titles with &shy; inside them?

**Comment by sven-ra** [comment]
Whoops I actually wrote "\&shy;" there but it parsed it as html in the comment.

**Comment by jasonbahl** [comment]
If you want to expose this field on your own, I would suggest registering a field to the Schema and outputting the title without any filters. 

Something like the following could work: 

```php
add_action( 'graphql_register_types', function() {

	register_graphql_field( 'Post', 'rawTitle', [
		'type' => 'String',
		'description' => __( 'The raw title without filters/decoding applied', 'your-text-domain' ),
		'resolve' => function( \WPGraphQL\Model\Post $post ) {
			$post_object = ! empty( $post->databaseId  ) ? get_post( $post->databaseId ) : null;
			return isset( $post_object->post_title ) ? $post_object->post_title : null;
		}
	]);

});
```

You could then query like so: 

```graphql
{
  post(id: 1757, idType: DATABASE_ID) {
    id
    databaseId
    title
    rawTitle
  }
}
```

![Screen Shot 2020-10-22 at 11 41 54 PM](https://user-images.githubusercontent.com/1260765/96960672-31665b00-14c0-11eb-84ea-0d8af221cfa1.png)

If you wanted to add this to _all_ Post Types that have post_type_support for titles, you could instead register it to the `NodeWithTitle` Interface Type like so:

```php
add_action( 'graphql_register_types', function() {

	register_graphql_field( 'NodeWithTitle', 'rawTitle', [
		'type' => 'String',
		'description' => __( 'The raw title without filters/decoding applied', 'your-text-domain' ),
		'resolve' => function( \WPGraphQL\Model\Post $post ) {
			$post_object = ! empty( $post->databaseId  ) ? get_post( $post->databaseId ) : null;
			return isset( $post_object->post_title ) ? $post_object->post_title : null;
		}
	]);

});
```

And then you could query like so: 

```graphql
{
  contentNodes {
    nodes {
      __typename
      ... on NodeWithTitle {
        title
        rawTitle
      }
    }
  }
}

```

![Screen Shot 2020-10-22 at 11 44 47 PM](https://user-images.githubusercontent.com/1260765/96960831-99b53c80-14c0-11eb-9a1e-1573b145a82f.png)
