### ISSUE TITLE
Feature: Add location to menu idType's

### ISSUE THREAD

**Issue by drewbaker** [wp-graphql/wp-graphql#1458]
Would be great to be able to use the `menu` query using the location as an `idType`. Currently to query by location we need to do this, which is not very intuitive. 

```
    menuItems(first: 99, where: { location: "Main Menu", parentDatabaseId: 0 }) {}
```

This would be way better:

```
     menu(id: "Main Menu", idType: LOCATION) {}
}
```

<img width="291" alt="Screen Shot 2020-09-11 at 1 02 03 PM" src="https://user-images.githubusercontent.com/475015/92918193-7e6e0080-f42f-11ea-8282-1b2a90fd46df.png">

**Comment by jasonbahl** [comment]
Released in v1.8.3
