### ISSUE TITLE
Error when wp-graphql-gutenberg plugin is enabled

### ISSUE THREAD

**Issue by james-wfaa** [wp-graphql/wp-graphql#1460]
When both WP Graphql 0.10.3 and WP Graphql Gutenberg 0.3.4 [https://github.com/pristas-peter/wp-graphql-gutenberg](url) are active, the following error occurs when running `gatsby develop:`

Missing onError handler for invocation 'building-schema', error was 'Error: Type with name "WpBlockAttributesObject" does not exists'. Stacktrace was 'Error: Type with name "WpBlockAttributesObject" does not exists

Earlier in the process, this warning occurs:
warn  gatsby-source-wordpress  Unable to find a single Node query for BlockEditorContentNode
        This type will not be available in Gatsby.

**Comment by jasonbahl** [comment]
@james-wfaa when using WPGraphQL and WPGraphQL Gutenberg are there errors when using WPGraphiQL in the WordPress admin?

If you're not having issues with WPGraphQL directly, then it's likely an issue with the Gatsby Source WordPress plugin. 

There are a few issues related to Gutenberg here: https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues?q=is%3Aissue+gutenberg+

If none of those are relevant, I'd recommend opening a new issue on that repo with as much detail as possible to reproduce.

**Comment by james-wfaa** [comment]
@jasonbahl I was able to circumvent the issue and start getting gatsby develop to work while the wp-graphql-gutenberg plugin is active.  I didn't test thoroughly, but I *think* the problem was with having both wp-graph-gutenberg AND another plugin called atomic blocks active. https://atomicblocks.com/. When I disabled atomic blocks, I was able to run gatsby develop without errors.

**Comment by Kpudlo** [comment]
I am experiencing the same issues. However, after disabling all plugins except WP GraphQL, WP Gatsby, and WP GraphQL Gutenberg, I'm still unable to get `gatsby develop` to work correctly. As soon as I disable WP GraphQL Gutenberg, I am able to run `gatsby develop`.

**Comment by willem-aart** [comment]
Ran into the same issue, solved it for now by putting the following hack in `gatsby-node.js`:

```
exports.createSchemaCustomization = ({ actions }) => {
  const { createTypes } = actions;
  const typeDefs = `
    type WpBlockAttributesObject {
      foobar: String
    }
  `;
  createTypes(typeDefs);
};
```
It's nasty, but better than a broken website.

**Comment by bhardie** [comment]
This appears to be a consumer issue and not a WPGraphQL issue.  If you have more information that suggests otherwise, please open a new issue and include the new info and steps to reproduce.

**Comment by dardub** [comment]
I run into this issue when using WP Gatsby with WP GraphQL and QP GraphQL Gutenberge out of the box.

**Comment by justlevine** [comment]
Hey, @dardub this issue was closed 2 years ago. 

WPGraphQL Gutenberg is no longer maintained, but feel free to see and leave feedback on the linked issue right above your most recent comment.

If you find an issue with WPGraphQL core please feel free to open up a new issue with replication steps. (WPGatsby development is handled by Gatsby in its [own repo](https://github.com/gatsbyjs/wp-gatsby))
