### ISSUE TITLE
Menus returning empty array after 0.9.1 -> 0.10.0 upgrade

### ISSUE THREAD

**Issue by durfee** [wp-graphql/wp-graphql#1463]
## Description
After upgrading from 0.9.1 to any version ^0.10.0, querying for `menus` returns an empty array from non-wpgraphiql sources unless a menu is set to a location

### Using 0.10.0, results from WPGraphiQl, menu *does not* have a location set

<img width="750" alt="Screen Shot 2020-09-17 at 11 40 50" src="https://user-images.githubusercontent.com/4141536/93513580-e82c5580-f8da-11ea-9ffc-27522b8d5cc9.png">
_WPGraphiQL query_

<img width="750" alt="Screen Shot 2020-09-17 at 11 42 06" src="https://user-images.githubusercontent.com/4141536/93513559-e19dde00-f8da-11ea-9780-82d6893a22b3.png">
_GraphiQL query_

### Using 0.10.0, results from WPGraphiQl, menu _has_ location set and results return as expected

<img width="750" alt="Screen Shot 2020-09-17 at 11 46 50" src="https://user-images.githubusercontent.com/4141536/93514286-de572200-f8db-11ea-8f7b-4718c4e53f05.png">

<img width="750" alt="Screen Shot 2020-09-17 at 11 48 40" src="https://user-images.githubusercontent.com/4141536/93514318-e9aa4d80-f8db-11ea-9d03-6fcd85b745cb.png">
_Queried from GraphiQL_

✅ Is reproducible from a fresh install

Let me know if I can provide any other details!

**Comment by jasonbahl** [comment]
@durfee Thanks so much for the detailed issue. Super helpful in identifying issues when this much information is provided up front! Really appreciate it! 

This is actually a correction to previously incorrect access control rights. 

Menus/Menu Items that are not assigned to a location are not public entities in WordPress and WPGraphQL now respects that.

In the [v0.10.0 release notes](https://github.com/wp-graphql/wp-graphql/releases/tag/v0.10.0) are the following bullet points: 

- Menus not associated with a location are now private ([read more](https://github.com/wp-graphql/wp-graphql/issues/778#issuecomment-649814187))
- Menu Items not associated with a public menu are now private ([read more](https://github.com/wp-graphql/wp-graphql/issues/778#issuecomment-649819971))

**Comment by durfee** [comment]
@jasonbahl Ohh gotcha! Understood. I completely missed those two bullet points 😅 . Agreed, that seems like proper behaviour. Thanks for the reply!
