### ISSUE TITLE
nodeByUri for a category returns null for posts when requesting nested categories

### ISSUE THREAD

**Issue by drewbaker** [wp-graphql/wp-graphql#1464]
Given nested categories, `nodeByUri` doesn't work when trying to get posts in a category. It works for at one level deep. Might be related to #1451.

<img width="252" alt="Screen Shot 2020-09-18 at 4 40 51 PM" src="https://user-images.githubusercontent.com/475015/93610716-b9db7280-f9cd-11ea-96e4-7f34491e262a.png">

This returns the right posts:
```
query CAT_TEST {
  nodeByUri(uri: "/news/category/makemake") {
    id
    uri
    ... on Category {
      id
      name
	posts {
          nodes {
            title
          }
      }
    }
  }
}
```

This returns null:
```
query CAT_TEST {
  nodeByUri(uri: "/news/category/makemake/featured") {
    id
    uri
    ... on Category {
      id
      name
	posts {
          nodes {
            title
          }
      }
    }
  }
}
```

Interesting thing I found was this works (categoryName as a path?!):

```
query CAT_TEST {
  posts(where: {categoryName: "/category/makemake/featured"}) {
    nodes {
      title
    }
  }
}

```

**Comment by jasonbahl** [comment]
@drewbaker I've reproduced this on v0.13.1, so we've got some work to do still with the URI queries. I fixed some things with URIs in regards to posts, but some details slipped by for terms it looks like. 

Thanks for the helpful information here. I'll look into getting this resolved shortly.

**Comment by justlevine** [comment]
Getting this in v1.0 

I get the following in debug.log
```
Notice (8): Trying to get property 'term_id' of non-object in /var/www/thegsc/wp-content/plugins/wp-graphql/src/Data/NodeResolver.php on line 335.
```
So went there, and did an error_log of `$this->wp`:
```
[query_vars] => Array
        (
            [category_name] => news/biu-news
        )

[query_string] =>  
[request] => category/news/biu-news
[matched_rule] => category/(.+?)/?$
[matched_query] => category_name=news%2Fbiu-news
```

Low and behold, running a new gql query without the parent in the uri works (note the returned uri _does_ have the parent category).

![Annotation 2020-12-06 160334](https://user-images.githubusercontent.com/29322304/101282248-ad043900-37dc-11eb-83ae-b408563ec246.jpg)

**Comment by jonshipman** [comment]
@justlevine 

Here's a dropin function that will "fix" the issue using what you found. Once a fix gets incorporated, just drop this hook.

```
/**
 * Fixes category requests that are nested.
 *
 * @param array $query_args The Query arguments.
 * @return array
 */
function wpgql_category_param_mangle( $query_args ) {
	if ( ! empty( $query_args['category_name'] ) && false !== strpos( $query_args['category_name'], '/' ) ) {
		$parts                       = explode( '/', $query_args['category_name'] );
		$query_args['category_name'] = end( $parts );
	}

	return $query_args;
}

add_filter( 'request', 'wpgql_category_param_mangle' );
```

**Comment by jasonbahl** [comment]
@drewbaker @jonshipman @justlevine If you have time, please check this PR and let me know if it works for you without custom filters in place. 😄 

https://github.com/wp-graphql/wp-graphql/pull/1809

**Comment by jonshipman** [comment]
> @drewbaker @jonshipman @justlevine If you have time, please check this PR and let me know if it works for you without custom filters in place. 😄
> 
> #1809

Just checked dev build 1.3.3 and it seems to work. Of note: with the request mangle filter in place it'll not return anything. So a heads up to remove that filter to anyone reading post v1.3.3.
