### ISSUE TITLE
Add `isSticky` Boolean field to any post type that can be sticky

### ISSUE THREAD

**Issue by TylerBarnes** [wp-graphql/wp-graphql#1465]
Currently this isn't possible but would be good info to query.

**Comment by jasonbahl** [comment]
@smthomas @duffn ya'll can fight to the death for who gets to implement this one. . .maybe we can do a quick mob-programming here? 🤔

**Comment by duffn** [comment]
I’d love to get in on this with y’all and learn more.

**Comment by smthomas** [comment]
I would be happy to jump in on this as well. Would be a great thing to do as a mob-programming call.

**Comment by pierreavizou** [comment]
Hello guys, this is awesome I just needed the featured and just found out it was merged into `develop` two days ago 🚀
Just a quick question: How much work would it be to add isSticky as a filterable field in `where` conditions? 

I could use this at work so, although my PHP skills are a bit dusty, could definitely lend a hand on this if needed!
