### ISSUE TITLE
Debug 'Internal Server Error'

### ISSUE THREAD

**Issue by MitchEff** [wp-graphql/wp-graphql#1468]
I've asked this a few times but I just can't get to the bottom of it.

A lot of times we try to compile sites and just get "Internal Server Error" with zero other context and we just have to pull random fields out until something works. Today it was just a Select field with basic text values - we removed it and added the identical field back, and suddenly it works again. 

- GRAPHQL_DEBUG is true
- WP_DEBUG is true
- We have wp-graphql-insights installed, but I'm guessing it's not supposed to do anything there
- I've tried `error_log($result)` in `wp-graphql/src/Request.php`

The absolute best I can get is 'path', which told me which field was causing the error, but that's it. 
In v0.8.3 I could occasionally get around it by doing `error_log(json_encode($response))` in `wp-graphql-0.8.3/src/Request.php` line 422, but that also tells me nothing now.

Are we supposed to just yank fields out at random whenever it decides to break? Surely there's some means of actually finding the error, I'm not used to a package being this opaque. 

Anyone?

**Comment by kpratik2015** [comment]
I am facing same problem after updating wordpress :/

**Comment by kpratik2015** [comment]
Latest release (v0.13.1) helped fix my issue. "Enable GraphQL Debug Mode" gave me debug message of Cookie nonce is invalid. Had to re-login to fix it. Not sure if that was the culprit but this release fixes my issue with breaking changes in queries.

**Comment by jasonbahl** [comment]
@MitchEff if `GRAPHQL_DEBUG` is true, you should see more explicit errors than `Internal Server Error`

How are you enabling `GRAPHQL_DEBUG`? It should be in your wp-config.php file _above_ the line that says: `/* That's all, stop editing! Happy blogging. */`. If you put it below that, it won't work.

**Comment by IRediTOTO** [comment]
I got this too, but if logout and login, everything fine. Don't know why
![image](https://user-images.githubusercontent.com/15695252/96373626-f39fc480-1197-11eb-952b-cb6b8baaa274.png)

**Comment by kpratik2015** [comment]
> I got this too, but if logout and login, everything fine. Don't know why
> ![image](https://user-images.githubusercontent.com/15695252/96373626-f39fc480-1197-11eb-952b-cb6b8baaa274.png)

That's because on login a cookie is set in your browser that lets you be logged in even after closing the tab. If the cookie changes by an API or some other means i.e. some other user logs in then the cookie is invalid for graphiql tab (which requires admin login cookie)
