### ISSUE TITLE
nodeByUri not returning post when permalinks set to Custom Structure 

### ISSUE THREAD

**Issue by drewbaker** [wp-graphql/wp-graphql#1469]
Not the way the `nodeByUri` doesn't return a post, but the `post` query does, and returns the same `uri` that `nodeByUri` says doesn't exist:

<img width="964" alt="Screen Shot 2020-09-21 at 1 52 20 PM" src="https://user-images.githubusercontent.com/475015/93763447-bf28ff00-fc11-11ea-80e4-24b2661f2e0e.png">

I suspect it's related to my permalink settings in some way:

<img width="902" alt="Screen Shot 2020-09-21 at 1 53 51 PM" src="https://user-images.githubusercontent.com/475015/93763590-0a431200-fc12-11ea-87fd-9de827ae22bd.png">

**Comment by jasonbahl** [comment]
@drewbaker I did some work recently to address some bugs with uri queries and I think this has been solved. 

I set my permalinks the same as you and then tried on v0.12.0 and have an issue:

![Screen Shot 2020-10-02 at 1 37 41 AM](https://user-images.githubusercontent.com/1260765/94899073-deb0fa80-044f-11eb-9879-c5fd543e029b.png)

But it looks like things are in working order in v0.13.1:

![Screen Shot 2020-10-02 at 1 35 37 AM](https://user-images.githubusercontent.com/1260765/94898918-9691d800-044f-11eb-8910-cedb082b495d.png)

Can you give it a shot on the latest release and confirm?

**Comment by jasonbahl** [comment]
Closing as this seems to be fixed in >= v0.13.1
