### ISSUE TITLE
Querying page by URI when the URI is the same as a postType URI yields an internal server error.

### ISSUE THREAD

**Issue by Mikethekidmyers** [wp-graphql/wp-graphql#1470]
This is reproducible by registering a custom post type like `references`, then creating a page with the slug `references` and querying for that page with the new "page" query:
```
page(id: "references", idType: URI) {
    uri
  }
```

If I do this with the old `pageBy` query it works as expected and returns the correct page:
```
pageBy(uri: "references") {
    uri
  }
```

the post type is registered like this: 
```
function create_post_types()
{
	register_post_type('references', [
        'labels' => [
            'name' => _x('References', 'Post type general name', 'bugreport'),
            'singular_name' => _x('Reference', 'Post type general name', 'bugreport')
        ],
        'public' => true,
        'has_archive' => true,
        'rewrite' => ['slug' => 'references'],
        'show_in_graphql' => true,
        'hierarchical' => true,
        'menu_icon' => 'dashicons-clipboard',
        'graphql_single_name' => 'Reference',
        'graphql_plural_name' => 'References'
    ]);
}

add_action('init', 'create_post_types');
```

Core plugins & versions:
- WPGraphQL : 0.12.2
- WP GraphiQL : 1.0.1
- Wordpress : 5.5.1

Other plugins & versions:
- WPGraphQL SEO : 4.6.0
- Advanced Custom Fields PRO : 5.9.1
- Advanced Custom Fields WP-CLI : 3.0.0
- Safe SVG : 1.9.9
- WPGraphQL for Advanced Custom Fields : 0.3.5
- Yoast SEO : 14.9

**Comment by jasonbahl** [comment]
@Mikethekidmyers ok, so I'm able to replicate what you've reported, however I think the behavior in v0.12.2 was actually possibly a bug. 

Based on the code to register the post type, the uri `/references` is _actually_ not a page, but a post type archive. 

If you visit the url in the browser directly, you can see this is the case:

![Screen Shot 2020-10-02 at 1 16 08 AM](https://user-images.githubusercontent.com/1260765/94897442-de633000-044c-11eb-8af9-ed035dd748ec.png)

If you were to query using the uri `/references` WPGraphQL _should_ recognize that as a ContentType, as it's an archive of the "references" post type, and not as a page. 

Here's a screenshot showing a `nodeByUri()` query for the `/references` uri. And also queries for page and pageBy with the uri, and getting `null` values for the pages. 

![Screen Shot 2020-10-02 at 1 20 40 AM](https://user-images.githubusercontent.com/1260765/94897740-7fea8180-044d-11eb-92d6-7df4a8275a28.png)

I believe this is correct behavior as it matches how WordPress resolves templates when visiting the URI as well. 

I don't want to close this issue without further discussion, as I think it would be valuable to hear your thoughts on this as well.

**Comment by jasonbahl** [comment]
As a sanity check, I also checked permalinks using [Rewrite Analyzer](https://wordpress.org/plugins/monkeyman-rewrite-analyzer/) plugin, and the correct primary response for the `/references` uri should indeed be the `references` post type:

![Screen Shot 2020-10-02 at 1 27 41 AM](https://user-images.githubusercontent.com/1260765/94898252-79103e80-044e-11eb-8338-3c78921bbaf5.png)

**Comment by Mikethekidmyers** [comment]
@jasonbahl I think what you wrote here about this being the correct behaviour as is default in WP is the right answer. I think I just assumed it was the other way around as it worked earlier with the old `pageBy` query. Looking through it again I guess the correct thing to do here would be to set the `'has_archive' => false`, property on the post type and try to have a regular page as the "archive". Which should(?) then work as expected with the `page` query.

Anyway, we managed to resolve the issue by just changing the slug for the page in production and we were golden. Thank you very much for taking the time to answer here and sorry I couldn't get back to you sooner. I appreciate all the work you put in here with this Ecosystem. Cheers!
