### ISSUE TITLE
Error after updating to v0.13: /build/asset-manifest.json missing

### ISSUE THREAD

**Issue by bonovski** [wp-graphql/wp-graphql#1473]
After updating to v0.13 the GraphiqIDE is not loading anymore. 

This is the error:
`home/testing/public_html/wp/wp-content/plugins/wp-graphql-0.13.0/src/Admin/GraphiQL/app/build/asset-manifest.json): failed to open stream: No such file or directory in /home/testing/public_html/wp/wp-content/plugins/wp-graphql-0.13.0/src/Admin/GraphiQL/GraphiQL.php on line 84`

Tried  it on multiple sites and the error is persistent.

**Comment by darrylmorley** [comment]
Same here, the IDE does not load.

**Comment by bonovski** [comment]
Fixed in 0.13.1.
