### ISSUE TITLE
Author field returns null on custom post type query even though CPT is registered with support => 'author'

### ISSUE THREAD

**Issue by Poolshark** [wp-graphql/wp-graphql#1476]
Hi there,

I ran into an issue but im not sure whether it's me or something is wrong with the schema. I have registered a CPT with

```php
$args = [
    'show_in_graphql' => true,
    'graphql_single_name' => 'someCpt',
    'graphql_plural_name' => 'someCpts',
    'graphql_single_type' => 'SomeCpt',
    'graphql_plural_type' => 'SomeCpts',
    'supports' => ['author', 'title', 'custom-fields']
];
```

When I try to query the CPT including the author data I get `NULL` as response.

**Query**
```
query SomeCptQuery {
 someCpts {
   edges {
     id
     authorDatabaseId
     author {
       node {
         firstName
         lastName
      }
    }
  }
 }
}
```

**Response**
```javascript
{
  "data":  {
    "someCpts": {
      "edges": [
        "node": {
          "id": "SOME_HASH"
          "authorDatabaseId": 1
          "author": null
        }
      ]
    }
  }
}
```

Did I do something wrong or is it simply not possible to do that?

Thanks!

**Comment by jasonbahl** [comment]
Is the author with ID 1 an existing user? Was that user deleted but the ID remained associated with the post?

**Comment by Poolshark** [comment]
Thank's for your quick reply!

It's actually a user which was created before creating the post (via a form). The actual ID is 19. The user never has been deleted. Could this have something to do with rights?

**Comment by jasonbahl** [comment]
in your query it shows `"authorDatabaseId": 1` but you're saying the actual author ID is `19`? 🤔 

Can you screenshot the raw data in something like SQL Pro or PHPMyAdmin and also screenshot what you see in the WP Admin when looking at the post and what author it's showing?

I'm not sure why `authorDatabaseId` would return `1`, if the author is actually id `19`. 

You may have found a bug, but I'll need more information to troubleshoot further. My guess is there might be some data that's stored incorrectly in your database.

**Comment by Robak08** [comment]
I'm having similar problem, but with woo-graphql. Since i think it might be connected I'll describe it here. When querying
`products {`
   ` nodes {
      reviews {
        nodes {
          author {
            node {
              name
              email
              databaseId
            }
          }
        }
      }
    }`
  }`
on playground I get author node with properties, but querying from frontend returns author: null.

**Comment by Poolshark** [comment]
Hey!

Sorry for getting back to you that late!

My previous query was only an example. The `authorDatabaseId` in my real case is `19` too. I am pretty sure it has to do with rights since I have read that some fields in a query are protected (such as e.g. `user_email`). Since I am querying from outside the WP environment (external GraphiQL), I guess I am not allowed the author data without authentication.

Sorry that I could not test this but it seems that @Robak08 has answered this question since he can query it from the WP GraphQL Playground (which uses `nonce`) but has no auth implemented in the frontend and thus fails to query `name` and email`.
