### ISSUE TITLE
Post__in and orderby post__in returning the wrong ids (duplicate ids coming down in subsequent fetchMores)

### ISSUE THREAD

**Issue by jonshipman** [wp-graphql/wp-graphql#1477]
Registered connection:
https://gist.github.com/jonshipman/fbd98356fb5aebd860499cb87023c821

Results:
https://gist.github.com/jonshipman/87037bae8fc4fd674b93b1fd5744e213

Logs above in the gist.

**Comment by jasonbahl** [comment]
@jonshipman ok, so I registered a connection locally with the following code:

```php

add_action( 'graphql_register_types', function() {

	register_graphql_connection([
		'connectionTypeName' => 'OrderbyDebug',
		'description' => __( 'debugging', 'wp-graphql' ),
		'fromType' => 'RootQuery',
		'toType' => 'Post',
		'fromFieldName' => 'postOrderbyDebug',
		'resolve' => function( $root, $args, $context, $info ) {

			$ids = [ 541, 531, 506, 457 ];

			$resolver = new \WPGraphQL\Data\Connection\PostObjectConnectionResolver( $root, $args, $context, $info, 'post' );
			$resolver->set_query_arg( 'post__in', $ids );
			$resolver->set_query_arg( 'orderby', 'post__in' );

			return $resolver->get_connection();
		}
	]);

} );
```

That allows me to query like so: 

```graphql
{
  postOrderbyDebug(first: 100, after: null) {
    edges {
      cursor
      node {
        databaseId
      }
    }
  }
}
```

![Screen Shot 2020-09-25 at 3 49 20 PM](https://user-images.githubusercontent.com/1260765/94318867-ae94c380-ff46-11ea-8fdc-9bc68259be29.png)

You can see that my hard-coded array of IDs to `orderby` are the same IDs I'm getting back in my connection. 

When I take one of the cursors, say `YXJyYXljb25uZWN0aW9uOjUzMQ==` for ID 531, and put it in for the value of "after", I appropriately get the nodes 506 and 457. 

![Screen Shot 2020-09-25 at 3 51 05 PM](https://user-images.githubusercontent.com/1260765/94318986-edc31480-ff46-11ea-99c2-c3235c02019c.png)

If I turn on Query Logging and check out the raw SQL query that was executed, I see this query was executed: 

```php
SELECT   wp_posts.ID FROM wp_posts  WHERE 1=1  AND wp_posts.ID IN (541,531,506,457) AND wp_posts.post_type = 'post' AND ((wp_posts.post_status = 'publish')) AND  CAST( wp_posts.post_date as DATETIME ) <= CAST( '2020-05-11 11:28:51' as DATETIME ) AND ( CAST( wp_posts.post_date as DATETIME ) < CAST( '2020-05-11 11:28:51' as DATETIME ) OR (  wp_posts.ID < 531 ) )   ORDER BY FIELD(wp_posts.ID,541,531,506,457), wp_posts.ID DESC  LIMIT 0, 101
```

**Comment by jasonbahl** [comment]
Ok, so after a bit more digging I was able to finally reproduce this. 

I took a hard-coded list of IDs and randomized them (still hard-coded, but not in the default order from WP_Query)

`$ids = [ 693, 620, 661, 697 ];`

Then I used them as the resolver value and the first query is fine: 

![Screen Shot 2020-09-25 at 4 18 38 PM](https://user-images.githubusercontent.com/1260765/94320657-c706dd00-ff4a-11ea-88c5-f94a120201cf.png)

If I take the cursor for the 2nd item (`YXJyYXljb25uZWN0aW9uOjYyMA==`), and use it for the `after` value I would expect it to return: 661, 697, but instead I get no results 😱 

![Screen Shot 2020-09-25 at 4 20 16 PM](https://user-images.githubusercontent.com/1260765/94320779-02091080-ff4b-11ea-8ae1-4e688938bc90.png)

Funky results ensue when I change the order in other ways. 

**Possible Solution**

So, I think what needs to happen is that the "tie breaker" query for connections should not be included when "orderby => post__in" is used.

**Comment by jasonbahl** [comment]
@jonshipman I have a PR in progress. I'm writing a few tests and will push up something shortly for you to check out.

**Comment by jonshipman** [comment]
I updated my gist with your suggestion for outside wp-graphql.

https://gist.github.com/jonshipman/fbd98356fb5aebd860499cb87023c821

Relevant bits are in the headless_wp_post__in_order_prune filter ln98. Probably similar to your solution albeit higher up the chain.

**Comment by grazianodev** [comment]
Hello, 

has this been fixed? 'Cause I am experiencing exactly this same issue with version 1.0 of the plugin: if I use `orderby => post__in`, the first page of results is correct, but then I get no results for the second page. 

Here's my custom connection: 

```
register_graphql_connection([
	"fromType" => "RootQuery",
	"toType" => "Post",
	"fromFieldName" => "bookmarkedPosts",
	"connectionTypeName" => "RootQueryToBookmarkedPostConnection",
	"resolve" => function( $source, $args, $context, $info ) {
		$viewerBookmarksIds = get_user_meta( $context->viewer->data->ID, "user_bookmarks", true ); 
		$resolver = new \WPGraphQL\Data\Connection\PostObjectConnectionResolver( $source, $args, $context, $info, [ "post", "opp" ] );
		$resolver->setQueryArg( "orderby", "post__in" );
		$resolver->setQueryArg( "post__in", $viewerBookmarksIds );
		$connection = $resolver->get_connection();
		return $connection;
	},
	"resolveNode" => function( $bookmark, $args, $context ) {
		return \WPGraphQL\Data\DataSource::resolve_post_object( $bookmark->ID, $context );
	}
]);
```

It works just well if I remove the `orderby` query arg. 

Thanks in advance!
