### ISSUE TITLE
Provide option to remove "GraphiQL IDE" toolbar button

### ISSUE THREAD

**Issue by benknight** [wp-graphql/wp-graphql#1481]
Hey guys, I don't want to have a link to the GraphiQL IDE in my admin toolbar.

![image](https://user-images.githubusercontent.com/786691/94695346-ff9a2280-035f-11eb-99b3-3487207a8fb1.png)

Please provide a way to remove it.

**Comment by jasonbahl** [comment]
@benknight I'll work up a PR to provide a setting to enable/disable this link. 

In the mean time, you can filter it out like so: 

```php
add_action( 'admin_bar_menu', 'remove_graphiql_from_admin_bar_menu', 999 );

function remove_graphiql_from_admin_bar_menu( $wp_admin_bar ) {
	// replace 'updraft_admin_node' with your node id
	$wp_admin_bar->remove_node( 'graphiql-ide' );
}
```

**Comment by benknight** [comment]
Thanks for the quick follow-up!

**Comment by jasonbahl** [comment]
My PR didn't really note this but there's now a setting to turn this off. Noting here for reference.

![Screen Shot 2020-10-02 at 12 37 27 AM](https://user-images.githubusercontent.com/1260765/94894863-73fbc100-0447-11eb-8d8a-2f1682a112fd.png)
