### ISSUE TITLE
Setting for enabling/disabling GraphQL Introspection

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#1489]
WPGraphQL currently supports Introspection Queries by default. 

In production environments, the queries should already be known, so WPGraphQL should disable Introspection Queries for public requests by default and provide the option to enable them.

**Comment by jasonbahl** [comment]
closed by #1490

**Comment by evangelinepapanicola** [comment]
Hi @jasonbahl  - I don't seem to be able to untick Enable Public Introspection on the most recent version of WPGraphQL? The checkbox is greyed out and ticked.
Pretty sure there used to be another checkbox that would allow you to tick/untick this one.

![image](https://user-images.githubusercontent.com/33719860/149515466-1a390aad-d7f0-41f2-8976-5dce48029c7e.png)
