### ISSUE TITLE
createPost: Contributors can publish posts, should only be able to submit for review

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#1493]
WordPress core allows contributors to create a post with a "pending" status, but WPGraphQL lets contributors create posts with a "Publish" status. 

WPGraphQL should modify the `createPost` mutation to follow the core access control rights more closely.

**Comment by jasonbahl** [comment]
closed by #1499

**Comment by tuanfront-end** [comment]
@jasonbahl Hope you will read this comment, this part you are doing right, but the **updatePost** mutation is probably not yet,
When **updatePost** should also change the status to PENDING if the user is a contributor

**Comment by jasonbahl** [comment]
@tuanfront-end can you open this as a new issue so it doesn't get lost?
