### ISSUE TITLE
Way to dump the metas in an array?

### ISSUE THREAD

**Issue by fredy31** [wp-graphql/wp-graphql#1494]
Remember, an issue is not the place to ask general questions. You can use [Slack](https://wp-graphql.slack.com) for that ([join here](https://wpgql-slack.herokuapp.com/)).

Before you open an issue, please check if a similar issue already exists or has been closed before.

### When you open an _issue_ for a feature request, please add as much detail as possible:
- [ x ] A descriptive title
- [ x ] A description of the problem you're trying to solve, including *why* you think this is a problem
- [ x ] An overview of the suggested solution
- [ x ] If the feature changes current behavior, reasons why your solution is better

I'm trying to use GraphQL with NextJS to create the front end of my WP website but I'm hitting a problem.

In the options that I can pass from a page query, I have no way to just get the post meta. I would have to register field after field and really, that would not work for me.

Some websites I work on have 50 or even 100 fields, that depending on the template are used or not.

I've seen there is a plugin to work with ACF, but I'm using Typerocket so that doesn't work.

Wouldn't it be simpler to just have a node I can request that sends back an array with get_post_meta($id) so I can simply have the meta and then be able to work with it?

**Comment by fredy31** [comment]
Any updates?

**Comment by jasonbahl** [comment]
@fredy31 a huge benefit of GraphQL is specifying exactly what you want in the requests. Getting a dump of unpredictable data in your client applications leads to scaling issues and bugs. 

GraphQL best practices would be to register the specific fields you want to expose to the GraphQL Schema and in your client application write queries for the exact fields you need. 

I'd highly recommend registering the fields to the Schema with their appropriate types (string, boolean, integer, other complex Type, etc). 

[WPGraphQL for Advanced Custom Fields](https://github.com/wp-graphql/wp-graphql-acf) does the mapping from ACF to WPGraphQL for fields registered with ACF. You could use code from that as a starting point to figure out how map fields from Typerocket to WPGraphQL, or even see if the team behind Typerocket are interested in supporting GraphQL out of the box for thier fields?

**Comment by fredy31** [comment]
Okay so that might be why there doesn't seem to be a way to simply throw an array.

Is there a good way to send things like repeaters over? Because if I understand right you have to expressly call out every value that has to go through, so thats why an array is not accepted.

If i could ask things of you, the register_graphql_field is not very well documented. https://docs.wpgraphql.com/extending/fields/ Hard to know what does what in this section... how to assign it to a page? What names the field? I've bashed my head all monday trying to just have a simple field added to the graphql visualiser in WP.

**Comment by jasonbahl** [comment]
@fredy31 ya, I'm working on updating docs and this area is a focus we'll be spending time on. 

In the mean time, you can learn a lot by looking at the source code. Both of WPGraphQL itself and plugins like WPGraphQL for ACF, WPGraphQL for WooCommerce, etc. 

For a list of, you can define it like so: 

```php
register_graphql_field( 'Post', 'myListField', [
  'type' => [ 'list_of' => 'String' ],
  'resolve' => function() {
     return [ 'One', 'Two' ];
  }
]);
```

**Comment by fredy31** [comment]
If you could only debug me for a little quick thing (while the docs rework is in progress):

What are the accepted Types? Could an associated array work?, or a list_of arrays? Sometimes I have repeaters, so I would have to pass 2-3 arrays. Like a 'image, title, alt' for each array.

If I'm guessing right, the first argument is the post type requested (weirdly put, because WP usually works in camelcase, so it should not start by a capital), then the field name, and then the object that returns the value.

Also does the 'resolve' function have any attributes? Like if I have to manually do a 'get_post_meta' to return the value, can I know the WP id of the current requested post?
