### ISSUE TITLE
Querying singular entity searches all entities

### ISSUE THREAD

**Issue by durfee** [wp-graphql/wp-graphql#1508]
# Description
Querying for entities via their graphql singular name by URI, ID, or DATABASE_ID returns results from all possible post_types, not just the specified post_type. This also seems to be the case for querying used the depreciated nameBy (e.g. pageBy), but only when querying by URI, not ID or DATABASE_ID. This is a particular issue if two posts happen have the same slug, where only one will correctly return. 

I'm still not totally sure how it decides which one it chooses. I think it's by DATABASE_ID or date created but I'm not totally sure how to test that.

# STR
✅ Reproducible from clean install
1. Create a new page or post
2. Query for it with the wrong post_type
3. Get your results anyway

# Details
- Occurs on ^0.12.3
- Fine on 10.0.0
- This seems to be the case across custom post types as well as generic post types.
- This sounds sort of similar to #1470, but isn't quite the same.

Example:
<img width="1155" alt="Screen Shot 2020-10-14 at 00 27 48" src="https://user-images.githubusercontent.com/4141536/95957091-1c007b00-0db4-11eb-97c5-606ea0e1571c.png">

Query trace that might be useful?

```
 {
  "sql": "\n\t\tSELECT ID, post_name, post_parent, post_type\n\t\tFROM wp_sdnrx3kzmd_posts\n\t\tWHERE 
     post_name IN ('hello-world')\n\t\tAND post_type IN ('post','page','attachment','team','project','service')\n\t",
  "time": 0.0007500648498535156,
  "stack": "require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array('parse_request'),
     WP_Hook->do_action, WP_Hook->apply_filters, WPGraphQL\\Router->resolve_http_request, 
     WPGraphQL\\Router::process_http_request, WPGraphQL\\Request->execute_http, GraphQL\\Server\\StandardServer-
     >executeRequest, GraphQL\\Server\\Helper->executeOperation, GraphQL\\Server\\Helper->promiseToExecuteOperation,
      GraphQL\\GraphQL::promiseToExecute, GraphQL\\Executor\\Executor::promiseToExecute,
      GraphQL\\Executor\\ReferenceExecutor->doExecute, GraphQL\\Executor\\ReferenceExecutor->executeOperation,
      GraphQL\\Executor\\ReferenceExecutor->executeFields, GraphQL\\Executor\\ReferenceExecutor->resolveField,
      GraphQL\\Executor\\ReferenceExecutor->resolveOrError, WPGraphQL\\Utils\\InstrumentSchema::WPGraphQL\\Utils\\
     {closure}, call_user_func, WPGraphQL\\Utils\\InstrumentSchema::WPGraphQL\\Utils\\{closure}, call_user_func,
     WPGraphQL\\Type\\Object\\RootQuery::WPGraphQL\\Type\\Object\\{closure}, WPGraphQL\\Data\\NodeResolver-
     >resolve_uri, get_page_by_path"
},
```

Let me know if there're any other details I can provide!

**Comment by jasonbahl** [comment]
@durfee Thanks for submitting this issue! Appreciate all the details. I'll look into this shortly.

**Comment by durfee** [comment]
Hey @jasonbahl, just following up here! Anything I can do to to help or try and pin this down?

**Comment by jasonbahl** [comment]
@durfee thanks for the patience on this one. 

I've been able to replicate this behavior and have a PR in the works to fix it!

**Comment by durfee** [comment]
👏 Brilliant!! Thanks for gettin' that squared away!
