### ISSUE TITLE
`/?graphql` is returning the html page for the top post (latest or sticky)

### ISSUE THREAD

**Issue by TylerBarnes** [wp-graphql/wp-graphql#1517]
When authenticated via `wp-graphiql` everything is working as expected, but when making a non-authenticated request, html is returned.

**Comment by TylerBarnes** [comment]
On latest `master` using Local by flywheel

**Comment by TylerBarnes** [comment]
Jason says it's related to https://github.com/wp-graphql/wp-graphql/pull/1516

**Comment by jasonbahl** [comment]
Jason needs to take a hike
