### ISSUE TITLE
Can't query hierarchical custom post types by URI

### ISSUE THREAD

**Issue by sadmansh** [wp-graphql/wp-graphql#1524]
I have a custom post type called `events` that has parent-child (hierarchical) relationships between them. I have been trying to fetch child events using the following code:
```
query EventBySlug {
  event(id: "sustainable-ugh-meditation-hexagon-wayfarers-readymade", idType: URI) {
    id
    title
  }
}
```
And this is what it returns: 
```
{
  "data": {
    "event": null
  }
}
```
I have also tried adding the parent slug in the `id` parameter, like this below, but it still returns and error:
```
query EventBySlug {
  event(id: "banjo-lumbersexual-migas-direct-trade/sustainable-ugh-meditation-hexagon-wayfarers-readymade", idType: URI) {
    id
    title
  }
}
```
This is the error this code returns:
```
{
  "data": {
    "event": {
      "id": "cG9zdF90eXBlOmV2ZW50",
      "title": null
    }
  }
}
```
And if I run a query with this Id: `cG9zdF90eXBlOmV2ZW50` and `IdType: ID`, it returns 
```
{
  "errors": [
    {
      "message": "The ID input is invalid. Make sure you set the proper idType for your input.",
      "extensions": {
        "category": "user"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "event"
      ]
    }
  ],
  "data": {
    "event": null
  }
}
```

My WP and WPGraphQL are all latest versions, and the other plugins I am using are ACF, WPGraphQL for ACF, and Pods framework.

Any help with this will be highly appreciated!

**Comment by BernardV** [comment]
After some debugging and reading code I found this:

https://github.com/wp-graphql/wp-graphql/blob/develop/src/Data/NodeResolver.php#L301

So you need to set your custom post type to 'public' => true otherwise it will default to the post type 'post' and nothing will be found.

**Comment by jasonbahl** [comment]
@BernardV is correct that post types need to be registered as public in order to be able to be resolved by `uri`. 

In WordPress, post_types that are not public do not have a public URI and WPGraphQL respects that.
