### ISSUE TITLE
Unable to make changes to Wordpress posts "Update Failed"

### ISSUE THREAD

**Issue by erick-go** [wp-graphql/wp-graphql#1526]
Upon save I get an error "Update Failed". 
This is what's shown in the console
![image (3)](https://user-images.githubusercontent.com/59344617/96903806-95742980-1496-11eb-8580-b8d3dd72a3e2.png)

And these are my server error logs:
`FastCGI: server "/var/run/php74-cgi/php-cgi" stderr: tractConnectionResolver.php on line 498PHP message: PHP Warning: count(): Parameter must be an array or an object that implements Countable in /subdomains/admin/wp-content/plugins/wp-graphql-0.13.3/src/Data/Connection/AbstractConnectionResolver.php on line 498`

`FastCGI: server "/var/run/php74-cgi/php-cgi" stderr: st be an array or an object that implements Countable in /subdomains/admin/wp-content/plugins/wp-graphql-0.13.3/src/Data/Connection/AbstractConnectionResolver.php on line 498PHP message: PHP Warning: count(): Parameter must be an array or an object that implements Countable in /subdomains/admin/wp-content/plugins/wp-graphql-0.13.3/src/Data/Connection/AbstractConnectionResolver.php on line 498PHP message: PHP Warning: count(): Parameter must be an array or an object that implements Countable in /subdomains/admin/wp-content/plugins/wp-graphql-0.13.3/src/Data/Connection/AbstractConnectionResolver.php on line 498PHP message: PHP Warning: count(): Parameter must be an array or an object that implements Countable in /subdomains/admin/wp-content/plugins/wp-graphql-0.13.3/src/Data/Connection/AbstractConnectionResolver.php on line 498PHP message: PHP Warning: count(): Parameter must be an array or an object that implements Countable in /subdomains/admin/wp-content/plugins/wp-graphql-0.13.3/src/Data/Connection/Abs`

 `FastCGI: server "/var/run/php74-cgi/php-cgi" stderr: PHP message: PHP Warning: count(): Parameter must be an array or an object that implements Countable in /subdomains/admin/wp-content/plugins/wp-graphql-0.13.3/src/Data/Connection/AbstractConnectionResolver.php on line 498PHP message: PHP Warning: count(): Parameter must be an array or an object that implements Countable in /subdomains/admin/wp-content/plugins/wp-graphql-0.13.3/src/Data/Connection/AbstractConnectionResolver.php on line 498PHP message: PHP Warning: count(): Parameter must be an array or an object that implements Countable in /subdomains/admin/wp-content/plugins/wp-graphql-0.13.3/src/Data/Connection/AbstractConnectionResolver.php on line 498PHP message: PHP Warning: count(): Parameter must be an array or an object that implements Countable in /subdomains/admin/wp-content/plugins/wp-graphql-0.13.3/src/Data/Connection/AbstractConnectionResolver.php on line 498PHP message: PHP Warning: count(): Parameter must be an array or an object that implements Countable in /subdomains/admin/wp-content/p`

`FastCGI: server "/var/run/php74-cgi/php-cgi" stderr: PHP message: PHP Warning: count(): Parameter must be an array or an object that implements Countable in /subdomains/admin/wp-content/plugins/wp-graphql-0.13.3/src/Data/Connection/AbstractConnectionResolver.php on line 498`

**Comment by jasonbahl** [comment]
@erick-go I'm really curious why WPGraphQL is big executed when you save posts. 

Are you using WPGraphQL within your WP-Admin for meta boxes or anything like that?

**Comment by jasonbahl** [comment]
After pairing with @erick-go on a call, we were able to determine this is an issue with the WPGatsby plugin. 

I'm going to close this issue on this repo and open an issue over there with more info.
