### ISSUE TITLE
Menu path is processed as external resource when using a custom Site Address URL

### ISSUE THREAD

**Issue by rodrigo-arias** [wp-graphql/wp-graphql#1532]
I have noticed that when I use a Site Address URL other than the WordPress Address URL the menus path attribute is processed as external resources.

![image](https://user-images.githubusercontent.com/11416255/97048757-f2341a80-1550-11eb-9947-457ea484595f.png)

In my case, I am using a subdomain for the admin in dev environments, while in production the domain differs from the admin and that is where the attribute is processed differently.

Note that it is processed correctly when a subdomain of Site Address URL is used for WordPress Address URL and not the other way around.

![image](https://user-images.githubusercontent.com/11416255/97048949-40e1b480-1551-11eb-8ebd-950f6a3d73d1.png)

![image](https://user-images.githubusercontent.com/11416255/97048893-2a3b5d80-1551-11eb-925e-510b93701a34.png)

I would expect those resources to be recognized as internal and to get relative paths.

WPGraphQL 0.13.1
WordPress 5.5.1

**Comment by jasonbahl** [comment]
@rodrigo-arias I've confirmed this behavior and will have a PR shortly.

**Comment by rodrigo-arias** [comment]
Thanks @jasonbahl
