### ISSUE TITLE
Search query doesn't return private/protected posts (isRestricted)

### ISSUE THREAD

**Issue by izzygld** [wp-graphql/wp-graphql#1534]
_(make sure your'e not logged in to wp-admin when querying)_
### Regular post query:

```
 {
		posts {
			nodes {
				title
				uri
				id
                                 isRestricted
			}
		}
}

```

Returns all posts including if `isRestricted = true` 

### When querying with the where - search filter:
```

 {
		posts(where: { search: "test" }) {
			nodes {
				title
				uri
				id
                                 isRestricted
			}
		}
}
```
Returns only posts that `isRestricted = false`

**Is this on purpose?
Shouldn't it be the same as the regular post query?**

<img width="1226" alt="post-query" src="https://user-images.githubusercontent.com/12534341/97147671-8a5d1a00-1772-11eb-9288-2093fd514fe0.png">
<img width="911" alt="query-search" src="https://user-images.githubusercontent.com/12534341/97147684-8d580a80-1772-11eb-82de-a24427f37973.png">

**Comment by jasonbahl** [comment]
@izzygld can you provide more information about the post? There could be many reasons why the post isn't showing in public requests.

**Comment by izzygld** [comment]
It's a restricted (password protected) 

Should it really be excluded from the general post query too?

**Comment by jasonbahl** [comment]
Password protected posts are included in the main queries for public users. The content is protected, but the post itself can be seen. Much like if you publish a PW protected post and then visit the front-end of your site, the post will be there, but the content will be hidden. 

![Screen Shot 2020-10-26 at 10 24 22 AM](https://user-images.githubusercontent.com/1260765/97199332-82eb4000-1775-11eb-92c9-f252ce7c1809.png)

**Comment by jasonbahl** [comment]
@izzygld you could do a query like so, to exclude PWs

```
{
  posts(where: {hasPassword: false}) {
    nodes {
      id
      title
    }
  }
}

```

**Comment by izzygld** [comment]
That's what I thought too,
So why does the search term no search private posts too?

(Doesn't it search by title too - which is open)

**Comment by jasonbahl** [comment]
@izzygld ah, I do see that it's not being returned in search queries. I'm looking into whether this is a WPGraphQL thing, or an internal WP thing.

**Comment by jasonbahl** [comment]
@izzygld I believe this is happening deeper in WordPress core vs. WPGraphQL. 

As you can see, running the Twenty Twenty theme, it shows up in regular queries, like "Recent Posts" widget, but does not show in Search Results. 

Investigating a bit more, it appears the behavior comes from WP_Query internals: 

https://core.trac.wordpress.org/browser/tags/5.5.1/src/wp-includes/class-wp-query.php#L1398

![Screen Shot 2020-10-26 at 10 40 01 AM](https://user-images.githubusercontent.com/1260765/97201060-9d261d80-1777-11eb-9c58-0f08e1dfe994.png)

**Comment by izzygld** [comment]
Ok 
Sorry for bothering you
Thank you for clearing it up for us. 👍

**Comment by jasonbahl** [comment]
@izzygld you're certainly not bothering! 

I really appreciate pointing out things that feel like inconsistent behavior. Often there are bugs in WPGraphQL, especially the model layer, that still need to be fleshed out. 

This is a great discussion and will likely help other users in the future as well!

**Comment by izzygld** [comment]
Thank you for taking the time, I know you're a busy man. Appreciated.

Really excited for version 1. 😍
