### ISSUE TITLE
 Uncaught Error: Call to undefined method WPGraphQL\\Types::list_of()

### ISSUE THREAD

**Issue by Alexufo** [wp-graphql/wp-graphql#1541]
Version latest. Downloaded today from https://github.com/wp-graphql/wp-graphql
WP: 5.5.1

Plugin works good for Post type. But then I want to use it with user meta field I copy example from

Register field for user
https://docs.wpgraphql.com/extending/fields/

    add_action( 'graphql_register_types', function() {

		$hobbies = [
			'type'        => \WPGraphQL\Types::list_of( \WPGraphQL\Types::string() ),
			'description' => __( 'Custom field for user mutations', 'your-textdomain' ),
			'resolve'     => function( $user ) {
				$hobbies = get_user_meta( $user->userId, 'hobbies', true );
				return ! empty( $hobbies ) ? $hobbies : [];
			},
		];

		register_graphql_field( 'User', 'hobbies', $hobbies );
		register_graphql_field( 'CreateUserInput', 'hobbies', $hobbies );
		register_graphql_field( 'UpdateUserInput', 'hobbies', $hobbies );
    });

I got error
PHP Fatal error:  Uncaught Error: Call to undefined method WPGraphQL\\Types::list_of() in public_html/wp-content/plugins/xx/xx.php:71

Stack trace:

#0/public_html/wp-includes/class-wp-hook.php(287): {closure}(Object(WPGraphQL\\Registry\\TypeRegistry))
#1 /public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#2 /public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /public_html/wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php(525): do_action('graphql_registe...', Object(WPGraphQL\\Registry\\TypeRegistry))
#4 /public_html/wp-includes/class-wp-hook.php(287): WPGraphQL\\Registry\\TypeRegistry->init_type_registry(Object(WPGraphQL\\Registry\\TypeRegistry))
#5 /public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#6 /public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#7 /public_html/wp-content/pl in /home/a/alexufo/public_html/wp-content/plugins/xx/xx.php.php on line 71

**Comment by jasonbahl** [comment]
@Alexufo docs need to be updated. Sorry. 

Instead of: 
`'type' => \WPGraphQL\Types::list_of( \WPGraphQL\Types::string() )` 

it should be: 
`'type' => [ 'list_of' => 'String' ]`

**Comment by jasonbahl** [comment]
New docs site is also in the works and this example has been updated.
