### ISSUE TITLE
Filter posts by sticky status

### ISSUE THREAD

**Issue by pierreavizou** [wp-graphql/wp-graphql#1543]
It would be nice to be able filter posts by sitcky status, i.e adding a `isSticky` variable to the where condition on Post nodes. 

This is useful for instance when you want to display sticky posts in a different way, and you don't necessarily get all your sticky posts when querying the latest ones.

**Comment by jasonbahl** [comment]
@pierreavizou we have a blog post about how to accomplish this here: https://www.wpgraphql.com/2018/11/16/querying-sticky-posts-with-graphql/
