### ISSUE TITLE
Core fields should be objects, not scalars

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#155]
The core fields that are returned on Posts, Terms, etc should be objects, not scalars, so that plugins, etc can extend and provide rich data. 

For example, currently a query for a post can be executed like so: 

```
post( id: "..." ) {
    id
    title
    content
}
```

The change would make that become: 

```
post( id: "..." ) {
    id
    title {
       value
    } 
    content {
       value
    }
}
```

This will allow the fields to be extended by plugins themes. 

For example, hypothetically I could write a plugin that extends the `content` field and provides rich data about tinyMceSettings. 

So I could filter the `content` field object and return a tinyMceSettings field so that I could do a rich query like: 

```
post( ){
  content {
    value
    tinyMceSettings: {
      buttons: {
        iconUrl
        label
     }
    }
  }
}
```

The use cases are unlimited, really. . .

Some of this data might be useful to build UI, some might be useful to just troubleshoot info about your WP system config, etc. . .the sky is the limit. 

But having fields like `title` and `content` just be scalar fields limits the extendability of the schema and therefore limits the power of GraphQL in the WordPress context.

**Comment by CodeProKid** [comment]
@jasonbahl I definitely see the value in this. Would especially be nice to do something like this:
```
post( ) {
    content {
        rendered
        raw
        embeddedShortcodes
    }
}
```
That way you could get the data, and metadata part of the same object.

To move this forward I would suggest you come up with a list of fields that you would want to convert to objects. Or are you suggesting we convert _everything_ to an object that the core plugin registers?

I would say the only downside to all of this, would be that we would have a bunch of fields with one field within the object, so you would have to write a more verbose query just to get the same field. So something like this just to get a post's title:
```
post( ) {
    title {
        raw
    }
}
```
That extra step might cause some headaches for new users trying to get started with GQL.

I would propose instead of converting *all* fields, maybe just some that we identify as complex enough to need an object out of the box? Then we can let other devs customize as needed when they make the returned data from a field more complex.

**Comment by jasonbahl** [comment]
For further context, one of my main reasons for thinking of this was for plugins like ACF, CMB2, Fieldmanager, etc. 

The fields that are defined for plugins like that could easily add fields to a `post` node, but along with the field's `get_post_meta` value, they could also provide rich data like the field label, description, etc. . .which could be used, if wanted, in React (or Vue or Angular, etc) templates to build out interfaces. Of course, that data could be ignored completely if the UI wanted to be completely decoupled from the server, but I imagine in a lot of cases, if you've done the work to define a field's labels, descriptions, etc on a server, you might as well re-use that on the client, at least in some cases.

**Comment by jasonbahl** [comment]
@CodeProKid ya, I'll do an inventory on the current fields, but I think `most` core fields (other than `id`) would likely benefit from this structure. 

For example, I could extend the `title` to output additional data like `placeholderText` etc. . .

So when I build my UI I have the actual value, but the other rich UI data that might be helpful

**Comment by jasonbahl** [comment]
Also, @BE-Webdesign mentioned that with Guttenberg coming, this would help make the shape of the content blocks easier to query. . .not sure what that would look like yet, but we know it's coming. . .

**Comment by jasonbahl** [comment]
Another non-breaking approach we could go with this is to add a `{fieldName}Field` type (like `content` and `contentField`). 

so you could query: 

```
post() {
   content
}
```
which would return

```
[
  'post' => [
      'content' => "content string"
   ]
]
```

or you could query: 

```
post() {
   contentField {
      fieldLabel
      fieldValue
      fieldDescription
      ...
   }
}
```

That way we don't have to break backward compatibility at all, can keep nice succinct queries if you're just after the content, but provide an optional way to query for that rich field data, which would include the value as well. . .

Need to think about this a bit. 

Something about querying `post() { content }` feels nice compared to `post() { content{ fieldvalue } }`

**Comment by BE-Webdesign** [comment]
Yeah, this is a great idea Jason.

I think maybe instead of `contentField` we could name it `contentMeta`, because it is kind of the data that describes our content much like meta data describes whatever it is describing. In the `contentMeta` could be the rendered, rendered_shortcodes, raw, etc. (these should also be read only and not mutateable.

I like the idea of not breaking back compat, because the current scalar value is probably more expected. We mainly would want to expose whatever content can be edited for post mutations, and then any other content should be in some read only field(s) of some kind.

**Comment by jasonbahl** [comment]
part of where my head is, is how would I build a UI with this. 

Let's say I wanted this (pseudo) React component: 

```
const data = gql`
  fragment on contentField{
     fieldName
     fieldTitle
     fieldValue
     fieldDescription
     tinyMceSettings{
        butons: {
           label
           icon
        }
     }
  }
`;

<div>
  <label for={data.fieldName}>{data.fieldTitle}</label>
  <TinyMce name={data.fieldName} placeholder={data.fieldPlaceholder} value={data.fieldValue} tinyMceSettings={data.tinyMceSettings}/>
  <span className="description">{data.fieldDescripton}</span>
<div>
```

**Comment by jasonbahl** [comment]
having all the data needed for a field in that same query is super powerful, and where the real use cases shine. 

If your UI wants to define things like labels and placeholders on it's own, cool. . .but if you've already done the legwork defining that data on your server and want to make use of it, you can just ask for it and it'll be there

**Comment by CodeProKid** [comment]
I think my only real concern with this approach is that it creates a lot more overhead for us to have to maintain and test 2 versions of each field. Is there a way to alias the scalar field to the value within the object?

Also, how does this compare to other patterns in the GraphQL world? Will this possibly confuse some people?

**Comment by CodeProKid** [comment]
Another thing I just thought of, is how does the schema documentation work for the fields inside the object? Does it carry the same amount of visibility that the scalar version does?

**Comment by jasonbahl** [comment]
@CodeProKid I actually started conversations in both the Apollo slack org and the main graphql.slack org to get feedback, and folks seemed to think either way was fine. . .so really up to us. 

Fwiw, the overhead is pretty small. Here's my current implementation in code (no unit tests yet, but wouldn't be crazy to add tests for that):
 
![screen shot 2017-06-23 at 2 05 37 pm](https://user-images.githubusercontent.com/1260765/27498625-2905af32-581d-11e7-83e5-36423d2e3731.png)

**Comment by jasonbahl** [comment]
@CodeProKid GraphQL Schema documentation is infinitely nested, so I think either would be discoverable. 

The thing about Graphs are that the entry point to any point in the graph could be anywhere, so I kind of like the option of having both entries. . .you can enter to the `post.content` scalar directly, or `post.contentField.value` a little less directly, but with all the rich field data along side it. 

The flexibility this provides is pretty sweet, in my opinion. . .need to think about it a bit more, but I think I like this multiple field approach a lot

**Comment by jasonbahl** [comment]
but now would be the time to do a breaking change, if we were gonna do it. . .

**Comment by jasonbahl** [comment]
in my head, things that have UI elements in WordPress should have a `post.{property}Field` entry point, but things that are raw data should also have a `post.{property}` entry as well. 

Because in some cases you will be building an app that could care less what UI params WordPress has defined (think a native app for a news site, doesn't care about Field placeholders, etc, just cares about the content), but in other cases you might be building an app (think Calypso) that does care what fields are defined on the server. So now you can enter into the Graph for either situation and get what you need. 

And if `post.content` or `post.contentField` still doesn't satisfy your needs, you can still filter in your own type, like `post.awesomeConentFieldDude`

**Comment by jasonbahl** [comment]
I keep going back and forth on this in my head. I think the best approach for now is to leave the fields as-is, resolving as scalar values that return the underlying data ($post->post_content, $post->post_title, etc), then I'm thinking we can experiment with introducing other possible return types with rich data via a plugin. 

I'm just not sure what naming conventions look good, and what common properties should be supported out of the box to make it easy for other plugins to extend/hook into. 

So, I think I'll leave this alone for a few days at minimum while I think about it. . .but if anyone has ideas on potential schema, feel free to comment in here, or better yet, build a plugin that hooks in and registers the new schema shape.

**Comment by BE-Webdesign** [comment]
Could definitely be plugin territory.

**Comment by tonimain** [comment]
Maybe something like splitting visual data and just data for validating or comparing or such other stuff.
And maybe grouping it in a global manner for reuse on components and their logic.
I don't know if it makes sense in graphql universe, but for me context related resolving could be a good way to make things not so complicated. Maybe something like dividing it in the way i will paste the schema.
```
contentfield(maybeSomeParamters: 'you could pass into') {
  presentationLayer {
    yourDesiredValue
    anotherDdisplayableValue
    fieldGroup {
        ...on textField {
        willOnlyReturnValues
        becauseWeAreInPresentationLayer
      }
    }
  }
  fieldSetup {
    hasLabel
    hasDescription
    hasCompareModifier
    hasSomeUsefullStuff
    hasSpecialAttribute
    fieldGroup {
      ...on textField {
            willOnlyReturn
            setupFieldslike
            likeLabels
            orDescriptions
            wichAreNotRelated
            toRawContentOutput
      }
    }
  }
}
```

**Comment by jasonbahl** [comment]
@CodeProKid I'm moving this out of 1.0 milestone. It definitely needs more discussion and probably a P.O.C in form of an extension plugin to see how a pattern might look. 

I think we've decided that the simple names will be scalars though, so `content` is a string, and if this feature did come in the future, it would have a field name like `contentField` or something to that tune.

**Comment by CodeProKid** [comment]
@jasonbahl - that makes sense. If we are going to keep the simple names as scalars, and introduce new names as objects, we can add this after 1.0, and it won't be a breaking change.

**Comment by CodeProKid** [comment]
Lot's of good discussion and potential here. I think this also relates to -> https://github.com/wp-graphql/wp-graphql/issues/410 somewhat. It would be a good way to implement it at least, by adding an unescaped & escaped return for each object.

**Comment by jasonbahl** [comment]
Somewhat related to #782 🤔

**Comment by jasonbahl** [comment]
As lively as this discussion was, I'm going to close this issue. I can't see the core WPGraphQL plugin supporting this out of the box right now. We've done a lot of work to add a robust `register_graphql_*` API to make it easy to register fields and Types to the Schema, so if an application needed something custom like the TinyMCE settings, they should be able to expose those to the Schema easily. Most applications won't need that. If we feel that there's compelling need for some things like this, we can re-visit at that point and reference ideas we had here.
