### ISSUE TITLE
Closures with space

### ISSUE THREAD

**Issue by szepeviktor** [wp-graphql/wp-graphql#1561]
Please write closures like `function () { ...`
`function() { ...` looks like a function called `function` :)

**Comment by markkelnar** [comment]
Is this php, javascript or both?

**Comment by szepeviktor** [comment]
Every language.

**Comment by markkelnar** [comment]
For my own reference:
https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#6-closures

> Closures MUST be declared with a space after the function keyword, and a space before and after the use keyword.
