### ISSUE TITLE
Update docblock for `do_graphql_request` action

### ISSUE THREAD

**Issue by smthomas** [wp-graphql/wp-graphql#1563]
The $variables parameter is documented as a string when it should be documented as an array - https://github.com/wp-graphql/wp-graphql/blob/f801ab10b19c9c44755861ce4216ac0a8c436869/src/Request.php#L524

**Comment by galanggg** [comment]
Hi @smthomas , i created the PR here #1655 . Please kindly to check and review thanks !

**Comment by markkelnar** [comment]
This looks complete.
