### ISSUE TITLE
How to query all categories?

### ISSUE THREAD

**Issue by yaquawa** [wp-graphql/wp-graphql#1566]
For now, I do it like this:
```graphql
query MyQuery {
  categories(where: {parent: 0}, first: 9999999999) {
    nodes {
      categoryId
      name
    }
  }
}
```
Is there a nicer way to query all categories?

**Comment by jasonbahl** [comment]
@yaquawa By default WPGraphQL has limits on how many items it will return to prevent the WordPress server from melting. The limit by default is 100 items per query, and it's recommended that you paginate if you need more than 100 items. 

There's some info about pagination for posts here: https://docs.wpgraphql.com/getting-started/posts/#pagination

And it can be applied to categories or any other connection that supports pagination. 

Alternatively, you could use the filter `graphql_connection_max_query_amount` to allow more than 100 items to be queried by the client, but use with caution as that would allow _any_ client to make requests as large as you allow, and could put your server under high loads that it might not be able to complete. 

see:  https://github.com/wp-graphql/wp-graphql/blob/29cae903dd40739d5bac80d9100ad921089f0127/src/Data/Connection/AbstractConnectionResolver.php#L398

**Comment by yaquawa** [comment]
@jasonbahl Got it, thanks!
