### ISSUE TITLE
What's the best practice for protecting fields by user types ?

### ISSUE THREAD

**Issue by yaquawa** [wp-graphql/wp-graphql#1567]
I'm creating a site that allow user registration on a WordPress site.
User registration is accomplished via the Amazon Cognito service(not the WordPress user registration).

What I want to achieve is 
* Admin user can create post, delete post(all mutation operations), etc.
* logged-in users can create post
* public users can only read the post(only the `content` field and `title` field are public)

Is there any hook I can use to achieve such a requirement ?

For example, assume this query only available to logged in users.
```graphql
query MyQuery {
  __typename
  posts {
    nodes {
      commentCount
    }
  }
}
```

A filter like this could determine if the current user has the ability to issue such a query.
```php
add_filter('wp-graphql/query/posts_nodes_commentCount', function(){
    return (bool)current_logged_in_user();
})
```

**Comment by jasonbahl** [comment]
@yaquawa hello! 

There are many ways you could accomplish this. 

We have some documentation about this topic here: https://www.wpgraphql.com/docs/graphql-resolvers/#overriding-existing-resolvers
