### ISSUE TITLE
API is returning multiple nodes and node containing data keeps changing

### ISSUE THREAD

**Issue by mikeriley131** [wp-graphql/wp-graphql#1569]
WP GraphQL Version 0.12.0

Other plugins:
- ACF Pro
- All-in-One WP Migration
- All-in-One WP Migration File Extension
- Bluehost
- Classic Editor
- Custom Post Type UI
- Find Posts Using Attachment
- WP GraphiQL
- WPGraphQL Custom Post Type UI
- WPGraphQL for Advanced Custom Fields

Expected Behavior:
API returns a single node for a single Custom Field

Actual Behavior:
API returns multiple nodes for a single Custom Field

Not able to create a repo that singles out the issue, but here are some screenshots:

<img width="1233" alt="Screen Shot 2020-11-11 at 10 43 31 AM" src="https://user-images.githubusercontent.com/5115726/98845474-027e3d80-240b-11eb-9c5c-6f64ad012b6b.png">

<img width="1232" alt="Screen Shot 2020-11-11 at 10 43 40 AM" src="https://user-images.githubusercontent.com/5115726/98845486-08741e80-240b-11eb-9e78-9a96b335c7c0.png">

<img width="410" alt="Screen Shot 2020-11-11 at 10 44 31 AM" src="https://user-images.githubusercontent.com/5115726/98845506-1033c300-240b-11eb-815d-39bdafff6be5.png">

<img width="378" alt="Screen Shot 2020-11-11 at 10 43 00 AM" src="https://user-images.githubusercontent.com/5115726/98845527-15910d80-240b-11eb-90e1-cfd0c4fb0860.png">

The node where my data actually exists keeps changing which leads me to have to do this:
```
const sectionsData =
    data.neueamsterdam.pages.nodes[0].aboutPage.aboutSections ||
    data.neueamsterdam.pages.nodes[1].aboutPage.aboutSections ||
    data.neueamsterdam.pages.nodes[2].aboutPage.aboutSections;
```

Let me know if I am doing something wrong or more information is needed.

Thanks.

**Comment by jasonbahl** [comment]
@mikeriley131 from what I can tell, this looks like proper behavior. 

You created a Repeater field and assigned it to the about page, and populated it with 3 rows of repeater data. 

Then you queried for a list of pages, and the about page that has the repeater returned the 3 rows of data while the pages that do not have that data did not return the data. 

> Expected Behavior:
API returns a single node for a single Custom Field

I'm not sure I follow. Your `Custom Field` in this case is `About Sections` which is a repeater, and your query is asking for that on all pages, and in response you're getting a null for the pages that don't have this, and you're getting an array of the repeater values for the page that does have data. 

Can you elaborate more where you expect this to behave differently? 

Are you expecting the root `pages` field to return _just_ the about page?

**Comment by mikeriley131** [comment]
@jasonbahl Ohhhhhhhhhh, I missed that I could query for just the single About page. I suppose I was thinking that if I was only requesting `aboutPage` in my query that I'd get only that but upon further review I see why I was getting the other nodes. Thanks for setting me on the right track.
