### ISSUE TITLE
No JSON response only getting HTML response on  wp-graphql menuitems.

### ISSUE THREAD

**Issue by mohan-neethu** [wp-graphql/wp-graphql#1590]
When I tried to get all "Menuitems" of a language including "connectedNode" I am getting response as HTML (fetch/redirect)
But when I  tried to get all "Menuitems" of a language without "connectedNode" the response is showing correctly.

Could you please provide some inputs  here?

**Comment by jasonbahl** [comment]
@mohan-neethu can you share an example of the query that's not working? 

Did you just upgrade? If so, what version did the query work on and what version did it stop working on? 

One thing that comes to mind is that in the v0.10.0 release we fixed an access control rights leak that now requires menus/menu items to be associated with a nav menu location to be queried publicly. See: https://github.com/wp-graphql/wp-graphql/issues/778#issuecomment-649814187 and https://github.com/wp-graphql/wp-graphql/releases/tag/v0.10.0

Make sure the menu(s) you want to query are assigned to a menu location. 

To register a menu location in WordPress, see: https://developer.wordpress.org/reference/functions/register_nav_menus/

**Comment by mohan-neethu** [comment]
I am using 0.13.3 version.

```
{
  __typename
  menus(where: {slug: "test"}) {
    nodes {
      menuItems(first: 100, where: {location: TEST_NAVIGATION, language: "de"}) {
        nodes {
          menuItemId
          label
          path
          databaseId
          connectedNode {
            node {
              id
              ... on Category {
                id
                name
              }
            }
          }
        }
      }
    }
  }
}
```
using this query I am getting everything correctly but when I change it to another language. Its returning the response as HTML(fetch/redirect).
Also how can we get all menuitems irrespective of languages (for eg: de and en).

**Comment by jasonbahl** [comment]
`language` is not an argument provided by WPGraphQL. Are you using WPGraphQL for Polylang, by chance? 

My guess is there's a conflict of some sort between WPGraphQL for Polylang and the ability to query menu items by language. 

> Also how can we get all menuitems irrespective of languages (for eg: de and en). Currently by default we are getting only the primary language menu items if we didn't specify any language

If you remove the `language` argument from `menuItems` it should return all menu items regardless of language.

**Comment by mohan-neethu** [comment]
Yes I am using WPML (WP GraphQL WPML Extension)  and getting the language filtering.

But I also tried to get all the menu Items regardless of language. 
```
{
  __typename
  menus(where: {slug: "earth-core-test-navigation"}, first: 100) {
    nodes {
      menuItems(first: 100) {
        nodes {
          menuItemId
          label
          path
          parentId
          order
          id
        }
      }
    }
  }
}
```

Then also I am getting only menuItems of primary language

**Comment by jasonbahl** [comment]
@mohan-neethu as mentioned above, menus need to be assigned to a menu location to be publicly queryable. 

Can you confirm that the menu you are trying to query is assigned to a Menu Location? 

Additionally, you can try this snippet to allow Menus and MenuItems to be publicly queryable even when they're not assigned a location: https://www.wpgraphql.com/recipes/making-menus-and-menu-items-public/
