### ISSUE TITLE
wpml with custom post type error

### ISSUE THREAD

**Issue by Cuboctaedro** [wp-graphql/wp-graphql#1593]
I am using wp-graphql on a new WordPress install with WPML. I have also set a custom post type using `register_post_type()` inside functions.php. When I try to query the custom post type from the GraphiQl IDE I get the following error: "SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data". If I deactivate WPML the error disapears and I can see the posts from all languages in the query. Any ides about what may be causing this?

**Comment by tokrima** [comment]
No idea what is causing this but I have the same problem. Looks like the last version that works with WPML is 0.13.3.

**Comment by jasonbahl** [comment]
@Cuboctaedro @tokrima this sounds similar to #1595. Please see the debugging steps listed there. That should hopefully help narrow down the exact issue.
