### ISSUE TITLE
Query childPages and respective page node

### ISSUE THREAD

**Issue by nicolaisimonsen** [wp-graphql/wp-graphql#1597]
Hey guys,

Since updating to 1.0 I'm left with this issue. Querying child pages from the page node.

```
PAGE

childPages {
  edges {
    node {
      id
      uri
      slug
      uri
      title
      menuOrder
      featuredImage {
        sourceUrl
      }
    }
  }
}
```

I realize that the new (?) "children" node will list those edges, but menuOrder & featuredImage, among others, are not available.

How would you proceed? 🙂

**Comment by jasonbahl** [comment]
@nicolaisimonsen is the `childPages` field a field you custom registered? Or are you aliasing? I don't believe the WPGraphQL Schema has a `childPages` field out of the box. 

As far as `menuOrder` goes, it's currently available as a field for any post type that has registered support for `page-attributes` as that's where menuOrder is configured. (see: [post_type_supports](https://developer.wordpress.org/reference/functions/post_type_supports/)). 

Hierarchical data is now returned in a flat-list, meaning parent/child nodes are returned in one array. 

Here's an example of a query for pages, asking for the `id` and the `parentId`. 

<img width="1130" alt="Screen Shot 2020-11-23 at 8 48 24 AM" src="https://user-images.githubusercontent.com/1260765/99983079-a7343f80-2d68-11eb-98b6-21931fce3c3f.png">

This could then be passed to a function (such as the one documented here: https://www.wpgraphql.com/docs/menus/#hierarchical-data) to map the flat list of pages to a hierarchical list on the client. 

Does this help?

**Comment by nicolaisimonsen** [comment]
Hi Jason,

Thanks for helping me out (!) and I'm sorry for not responding sooner.

It seems that before WPGraphQL 1.0 the schema had a childPages field (which can be super helpful):
It would only display the children of the queried page - without the need for functions or filtering on the frontend.

![screen-shot](https://user-images.githubusercontent.com/3502327/101165034-447b5780-3636-11eb-9de8-8625d2352150.jpg)

Maybe I'm just not seeing how to filter in GraphQL and only display the children of the current node.
Am I making any sense? 🙂

**Comment by jasonbahl** [comment]
@nicolaisimonsen ah. So the `childPages` field was deprecated in favor of the field `children`, since Post Types can have parents and children of any post type. You can query now, like so: 

```graphql
{
  pages {
    nodes {
      id
      databaseId
      title
      children {
        nodes {
          ...on Page {
            title
          }
        }
      }
    }
  }
}
```

![Screen Shot 2020-12-08 at 6 26 49 AM](https://user-images.githubusercontent.com/1260765/101489575-5c94f480-391e-11eb-9411-b1b973a68dde.png)
