### ISSUE TITLE
Upgrading from 0.13.3 to 1.0 causes idType: URI to return null

### ISSUE THREAD

**Issue by durfee** [wp-graphql/wp-graphql#1605]
Upgraded to 0.13.3 today and ran into a pesky one that I haven't been able to deeply trouble shoot yet, but I can, if it'd be helpful. 

Previously, I used the `idType: URI` in combination with the slug of a post or custom post type to return the desired element. 
Example:
```
posts { ... } 
```
returns all fields correctly, but 
```
post(id: 'foo-bar-is-my-slug', idType: URI) { ... } 
```
Does not (where it did previously).

Upgrading to 0.14.0 (and onwards) causes this to fail for all post types, default and custom, but not pages. 

If this is a wontfix because 1.0 Works Fine™, how should I change my slug-based queries to conform to the new style, as I can't find any documentation around that. If this is an issue, let me know and I can go through testing on a clean env and provide some stack traces and whatnot

**Comment by durfee** [comment]
Maybe also related to #1397

**Comment by jasonbahl** [comment]
Can you give more info, such as how the post type was registered, what the uri field of the post shows when querying it as part of a list, whether the post is published, etc. 

This sounds like a possible bug, but also could be working properly but may be a data issue or something else. 

I'll need a bit more info.

**Comment by durfee** [comment]
Well, after digging in, it's definitely a me problem as I can't repro from a clean install and only seems to be the case with custom post types. Good news! 🎉 

Bad news for me: Installing from clean and using my theme with 1.0 in a test env works as expected ✅ , but when in prod, I get this:

<img width="967" alt="Screen Shot 2020-11-26 at 20 22 35" src="https://user-images.githubusercontent.com/4141536/100410954-22c21500-3025-11eb-8059-20a2c95927ee.png"> 

Notes
- Post is published
- This is ONLY the case with my custom post types, which are implemented like so
```
'labels' => $labels,
    'description' => "loremipsumdolarsitamet",
    'show_ui' => true,
    'show_in_nav_menus' => true,
    'show_in_menu' => true,
    'show_in_rest' => true,
    'rest_base' => 'projects',
    'supports' => array('title', 'editor', 'thumbnail', 'excerpt'),
    'rewrite' => array('slug'),
    'taxonomies' => array('tags', 'project_categories'),
    'show_in_admin_bar' => true,
    'menu_position' => 20,
    'menu_icon' => 'dashicons-admin-multisite',
    'capability_type' => 'post',
    'hierarchical' => true,
    'show_in_graphql' => true,
    'graphql_single_name' => 'project',
    'graphql_plural_name' => 'projects',
```
All in all I'm pretty stumped why it's fine on local, and busted in prod. Any recommendations of where to poke around or things I could flush or reset? 

Looks like we can probably close this though.

**Comment by jasonbahl** [comment]
Try to flush your permalinks by visiting Settings > Permalinks. 

See if that helps?

**Comment by durfee** [comment]
Gave that one a go already; no dice. I played around with the debug field a bit last night and there's a Schema registry clash on an ACF field that I can't seem to resolve (`You cannot register duplicate fields on the same Type.`). I doubt that's related, but is there a way to regenerate the graphql schema?

**Comment by jasonbahl** [comment]
@durfee I think you need to set `'public' => true` for the post type.

**Comment by durfee** [comment]
Hey @jasonbahl, sorry that took me a minute to test. Looks like we have a winner! That seems to have done the trick. I can't find where the quickstart docs are, but if you point me in that direction I can make a PR to update them to include `'public' => true` for the post type.

**Comment by jasonbahl** [comment]
@durfee in your example you query the slug, then use that as input for the uri. The slug and uri are not the same. 

Your uri is probably something like `/projects/test-project` so I would expect `{ project( id: "test-project" idType: URI ) { ... }}` to return null, as that's not the uri. 

Can you try again and query the `uri` field of the project, then use the `uri` value as the input on the next query?

**Comment by durfee** [comment]
Hey Jason, yeah looks like that does the trick. Thanks for your help + work on this!!

**Comment by jasonbahl** [comment]
@durfee thanks for confirming! 🙌
