### ISSUE TITLE
The menu query don't return more than 10 menuItems as well as the category query

### ISSUE THREAD

**Issue by baoc75** [wp-graphql/wp-graphql#1606]
Hi everyone,
Assume that I have a menu with 16 menuItems (>10), the query will only return the first 10 item. This also happen with category query.
```
query GET_MENU($id: ID!) {
      menu(id: $id, idType: NAME) {
        count
        id
        databaseId
        name
        slug
        menuItems {
          nodes {
            databaseId
            key: id
            title
            url
            cssClasses
            description
            label
            linkRelationship
            target
            parentId
          }
        }
      }
    }
```

query variable
```
{
      "id": "FIRST MENU"
}
```

WP GraphQL plugin version: 1.0
Wordpress version: 5.5.3

Did I miss anything? I think it's kinda weird. 
Thanks for reading!

**Comment by jasonbahl** [comment]
@baoc75 by default WPGraphQL returns 10 items if another quantity is not specified. You can specify how many items you want using the `first` argument, like so: 

```graphql
{
  posts( first: 25 ) {
    nodes {
       id
       title
     }
  }
}
```
