### ISSUE TITLE
Relation between 2 CPTs not working: Need support

### ISSUE THREAD

**Issue by akhilel** [wp-graphql/wp-graphql#1609]
I have 2 Custom Post types and they have a relation between them.
One CP is Teams and the next one is Players. A Player belongs to a Team.

I tried to query the relation via WP-graphql and its returns **"debugMessage": "User Error: expected iterable, but did not find one for field Player.team.",**
       
```
query MyQuery {
 players {
   nodes {
     id
     title     
     team {
       title
     }
   }
 }
```

WP graphql code snippet:
```
register_graphql_fields('Player', [
       
       'team' => [
           'type' =>  ['list_of' => 'Team'],
           'description' => __('team', 'wp-graphql'),
           
           'resolve' => function(\WPGraphQL\Model\Post $post, $args, $context, $info ) {
           
               $teams = get_post_meta($post->ID, 'player_team', true);
     
               $posts = \WPGraphQL\Data\DataSource::resolve_post_object($teams, $context);
         
               return $posts;
           }
       ]
   ]);
```

Could you please support here ?

**Comment by akhilel** [comment]
@jasonbahl : Could you please provide some leads ?

**Comment by jasonbahl** [comment]
@akhilel I'd recommend using a GraphQL Connection to handle the connection between 2 post types, such as Player and Team. 

You can read more about `register_graphql_connection` here: https://www.wpgraphql.com/functions/register_graphql_connection/
