### ISSUE TITLE
Return featured_media_array.sizes

### ISSUE THREAD

**Issue by duffn** [wp-graphql/wp-graphql#161]
I'd like wp-graphql to return the `featured_media_array.sizes` object that is currently available in the REST API.

While there are likely many applications, this would be helpful to developers creating Alexing skills as Amazon recommends to include multiple images in a skill response card: https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/providing-home-cards-for-the-amazon-alexa-app#image_size

**Comment by jasonbahl** [comment]
@duffn the mediaItem sizes can already be queried. See the Gif below: 

![mediaitem-sizes](https://user-images.githubusercontent.com/1260765/27931020-fb9e948a-6255-11e7-9487-095fd6c5525f.gif)

However, this relies on the function `wp_get_additional_image_sizes` (https://github.com/WordPress/WordPress/blob/d6bec79fe72eabd827b677be52c1c95d4f51b801/wp-admin/includes/image.php#L90) which some plugins (like Photonfill) override: https://github.com/alleyinteractive/photonfill/blob/8463bf84592b4a8cfbe58a2287498c73dd5c25c8/php/class-photonfill.php#L153

So the behavior on some systems unfortunately might not be ideal. 

Going to close this for now as it's working as expected for the core plugin. Specific sites with a specific combination of plugins can alter the Schema/Resolvers as needed to meet their system needs for image sizes.
