### ISSUE TITLE
Internal server error after upgrade to 1.0.1

### ISSUE THREAD

**Issue by muhrusdi** [wp-graphql/wp-graphql#1618]
Internal server error after upgrade to v1.0.1

```
{
  "errors": [
    {
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      }
    }
  ]
}
```

WPGraphQL v1.0.1
WPGatsby v0.7.3

**Comment by robkrause** [comment]
I observed that error too and had to revert back to v1.0

Plugins:
* Advanced Custom Fields PRO @ 5.9.3
* WP GraphQL @ 1.0.1
* WPGraphQL for Advanced Custom Fields @ 0.4.0

Wordpress @ 5.6

GraphiQL IDE does of course also not work then.

Which details would be helpful? Can't provide a isolated example unfortunatelly

**Comment by jasonbahl** [comment]
@muhrusdi @robkrause if you have any error logs from your server, that would help quite a bit! 

Also, what version of PHP are you running?

**Comment by jasonbahl** [comment]
@muhrusdi @robkrause One change I'm seeing that might be the culprit here is that if you register a post type or taxonomy with the same single name and plural name, you will now get an InvariantViolation which will show as an "internal_server_error" if you're not running in GraphQL Debug Mode. 

I'd suggest enabling GraphQL Debug mode and trying again. That should give you a better idea of what the underlying error is. 

See: https://www.wpgraphql.com/docs/debugging

**Comment by muhrusdi** [comment]
The problem is WPGraphQL Custom Post Type UI v1.1, when i disable the plugin, graphiql is running normally

**Comment by jasonbahl** [comment]
@muhrusdi thanks for the insight! I will check with these plugins and see what I can find.

**Comment by jasonbahl** [comment]
@robkrause can you provide more info on the queries you're seeing the "Internal Server Error" for?

I'm running the same versions as you: 

- Advanced Custom Fields PRO @ 5.9.3
- WP GraphQL @ 1.0.1
- WPGraphQL for Advanced Custom Fields @ 0.4.0

![Screen Shot 2020-12-16 at 8 33 13 AM](https://user-images.githubusercontent.com/1260765/102369577-571c5780-3f79-11eb-822b-85740db44d07.png)

And running some common queries doesn't return any "internal server error"

![Screen Shot 2020-12-16 at 8 32 21 AM](https://user-images.githubusercontent.com/1260765/102369481-394ef280-3f79-11eb-85d7-9bc551b6a446.png)

There's a chance there was a regression for a specific query path, but I'll need more information. 

Can you make sure to enable GraphQL Debug Mode? From the WordPress Dashboard go to GraphQL > Settings and check " Enable GraphQL Debug Mode" then save the settings, and execute the query in GraphiQL again. 

With GraphQL Debug mode enabled, you should get a more clear error than "Internal Server Error" which might help identify the issue. 

One change that comes to mind is that there's now an error shown if the `graphql_single_name` and `graphql_plural_name` for a Post Type or Taxonomy are the same. They must be different values.

**Comment by muhrusdi** [comment]
The result when GraphQL Debug mode enabled

![Capture2](https://user-images.githubusercontent.com/9457288/102375078-08180600-3ffd-11eb-8c10-e276be4b9d04.PNG)

Btw the same value for `graphql_single_name` and `graphql_plural_name` is not problem in WPGraphQL v1.0.0

![Capture1](https://user-images.githubusercontent.com/9457288/102374913-d69f3a80-3ffc-11eb-81f2-88479d32b840.PNG)

when graphql_plural_name is changed

![Capture3](https://user-images.githubusercontent.com/9457288/102375654-bae86400-3ffd-11eb-84d9-f61a7bcf8c3b.PNG)

was successful

![Capture4](https://user-images.githubusercontent.com/9457288/102375882-fedb6900-3ffd-11eb-8102-fc47fe426689.PNG)

**Comment by muhrusdi** [comment]
Thankyou

**Comment by robkrause** [comment]
Didn't know about the Debugging, and upon activating it I got the same debugMessage as @muhrusdi. Will fix it on my side and of course it is not an issue of wp-graphql

**Comment by jasonbahl** [comment]
Great! Glad we got to the bottom of this! 🙏

**Comment by jasonbahl** [comment]
For added context, for anyone else who comes across this, the `graphql_single_name` and `graphql_plural_name` must be different for Post Types and Taxonomies that are set to `show_in_graphql` as these names are used to add fields and Types to the Schema. 

For example, for a Post Type added to graphql, you get a single entry point to query lists of items, but also a single entry point to get an item by ID. 

Such as:

```graphql
{
  post( id: $id ) { id, title }
  posts( first:100) { nodes { id, title } }
}
```

If the single and plural name were the same, GraphQL would have conflicts building the Schema as it would try and add a field to the schema for both the single and plural entry for the post type using the same name. 

Some Schemas (like Gatsby) just take the Type name and prefix it with a word like `all`, so you have `post` for singular and `allPost` for plural, but for WPGraphQL we've opted for allowing the user registering the type to the Schema to have control over how they refer to singular and plurals.
