### ISSUE TITLE
Normalize html entities

### ISSUE THREAD

**Issue by lnikell** [wp-graphql/wp-graphql#1622]
Currentlyl, when you use Gatsby and WP Graphql you get content with escaped html entities. 

You get this
![image](https://user-images.githubusercontent.com/2697570/102242527-6f00c680-3efa-11eb-88eb-abc9c487d0f9.png)
Instead of this
![image](https://user-images.githubusercontent.com/2697570/102242549-73c57a80-3efa-11eb-99c5-800b3b1a0d90.png)

@TylerBarnes mentioned in that issue https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/19#issuecomment-642113522 that there are plans to handle it on WP Graphql side. Do you have plans for this or it should stay as a part of normalizers on a Gatsby side?

**Comment by jasonbahl** [comment]
we've gone back and forth on this a few times. 

In June, WPGraphQL [v0.10.0](https://github.com/wp-graphql/wp-graphql/releases/tag/v0.10.0) was released and included a change where the content (and other fields) were passed through `html_entity_decode()` before being returned in the GraphQL response. 

However, in [v0.15.0](https://github.com/wp-graphql/wp-graphql/releases/tag/v0.15.0) that was reverted as it was causing more problems than it was solving. 

Along with the revert, a filter was added so you can still opt-in if you want specific fields to pass through `html_entity_decode()` on the WordPress server before being returned. You can read more about this here: https://github.com/wp-graphql/wp-graphql/pull/1550


I've found that using `react-html-parser` to handle the html entities in the client has worked well for me. You can see this in action on wpgraphql.com here: https://github.com/wp-graphql/wpgraphql.com/blob/master/src/templates/WpPost.js#L59

**Comment by lnikell** [comment]
Hi @jasonbahl thank you for the response. Very good explanation. I've just checked the filter and I don't think it works. I added error_log to debug it and understand better  the values inside certain variables, however, it does not show up in logs. Am I doing something wrong?
```
add_filter( 'graphql_html_entity_decoding_enabled', function( $enabled, $string, $field_name, $model ) {
    error_log("Hello World 12");
	if ( $model instanceof \WPGraphQL\Model\MenuItem && 'label' === $field_name ) {
		return true;
	}
	
	return $enabled;

}, 10, 4 );
```

**Comment by jasonbahl** [comment]
@lnikell I don't believe menu item labels are passed through this at the moment. We can for sure change that though!

We'd need to pass the Menu Item label (https://github.com/wp-graphql/wp-graphql/blob/develop/src/Model/MenuItem.php#L126) through `$this->html_entity_decode()` like we do for the post title here: https://github.com/wp-graphql/wp-graphql/blob/develop/src/Model/Post.php#L467

Would you mind opening a PR to add that?

**Comment by lnikell** [comment]
Thank you for the reply @jasonbahl. I will try to add it, however, the filter itself does not work.  So I guess there will be a need to fix that part at first before passing menuItems to it. As in the code snippet above, I execute error_log before `if` condition, but I can't see that message in logs.

**Comment by jasonbahl** [comment]
This is because you're trying to filter a field that's not passed through that filter. We need the fix I suggested for the filter to be applied to the label field of Menu Items.

**Comment by lnikell** [comment]
@jasonbahl hm maybe I don't understand something about how WP works or PHP, but I suppose we should get inside the filter function anyway no matter  which field  do we plan to filter. So for example if I change the filter code  to the one that shown in the example of PR I still can't see error_log message in logs. 

```
add_filter( 'graphql_html_entity_decoding_enabled', function( $enabled, $string, $field_name, $model ) {
    error_log("Hello World 12");
	if ( $model instanceof \WPGraphQL\Model\Post && 'title' === $field_name ) {
		return true;
	}
	return $enabled;

}, 10, 4 );
```

**Comment by jasonbahl** [comment]
@lnikell what GraphQL Query did you execute after adding that filter?

Did you query for a post title?

That filter will run only if you actually query for a field where the filter is applied

**Comment by jasonbahl** [comment]
Here's a slight modification of your filter you tried: 

```php
add_filter( 'graphql_html_entity_decoding_enabled', function( $enabled, $string, $field_name, $model ) {
	graphql_debug("Hello World..." );
	if ( $model instanceof \WPGraphQL\Model\Post && 'title' === $field_name ) {
		return true;
	}
	return $enabled;

}, 10, 4 );
```

Instead of using `error_log` I'm using `graphql_debug()` so we can see the output in GraphiQL. 

When I execute a query for fields that don't pass through this filter, I don't see any output in the debug log: 

![Screen Shot 2020-12-15 at 1 10 27 PM](https://user-images.githubusercontent.com/1260765/102267535-474c3700-3ed7-11eb-9959-8263d23d61fb.png)


But when I query for a field (post.title) that does pass through the filter, I do see output: 

![Screen Shot 2020-12-15 at 1 10 39 PM](https://user-images.githubusercontent.com/1260765/102267555-50d59f00-3ed7-11eb-80b4-c9b80eda6c70.png)

**Comment by jasonbahl** [comment]
@lnikell I've got a PR coming with my suggested change

**Comment by jasonbahl** [comment]
@lnikell I opened a PR for this: https://github.com/wp-graphql/wp-graphql/pull/1624

**Comment by lnikell** [comment]
Thank you @jasonbahl for the clarification, thought that it will try to run filter even if we just query the entity. It error_log works fine when I started to query for the exact field. And thanks for the nice tip regarding graphql_debug, did not know about that option!
