### ISSUE TITLE
WPML and action_monitor fetching

### ISSUE THREAD

**Issue by progital** [wp-graphql/wp-graphql#1626]
WPML redirects when WPGraphQL fetches action_monitor posts

Adding the snippet below fixes the issue.

```
add_filter( 'wpml_is_redirected', function( $is_redirect ) {
  if ( is_graphql_request() ) {
    return false;
  }
  return $is_redirect;
});
```

**Comment by progital** [comment]
I'd add a higher priority (1000 or something) instead of the default. just in case.

**Comment by harrinsonmb** [comment]
It works, thanks a lot!

**Comment by supriome** [comment]
This solution helped me a lot. I was stuck on this problem for a long time, and finally I found out that it was a problem with WPML. I hope the maintainer will add this solution to the documentation @jasonbahl

**Comment by kenfraser** [comment]
Thank you! I was having the same issue with WPML and this fixed it.

**Comment by elskwid** [comment]
It might be a good idea to add this to https://github.com/rburgst/wp-graphql-wpml

**Comment by FatmaMahmoud698** [comment]
@elskwid 
when I install this plugin I got this error [Network error]: ServerError: Response not successful: Received status code 403

**Comment by justlevine** [comment]
Leaving closed since as noted it's an issue with WPML and not this plugin.

**Comment by L422Y** [comment]
Caused me a lot of headaches.
