### ISSUE TITLE
Merging extensions

### ISSUE THREAD

**Issue by cr101** [wp-graphql/wp-graphql#163]
Any plans to merge `wp-graphql-meta-query`, `wp-graphql-tax-query` and `wp-graphql-meta` into `wp-graphql`? Or are there specific reasons and advantages for having these extensions separate?

**Comment by jasonbahl** [comment]
@cr101 hey, Meta Queries can be quite expensive and actually have been known to take sites down when used irresponsibly, so we thought it was best to leave out of the core WP GraphQL and leave it up to system administrators to include it if they want it. 

Tax Queries typically aren't as dangerous, but for now we will keep them separate and leave it up to each project to decide whether they need that functionality or not. 

As a bonus, they also serve as good examples on how to extend WPGraphQL to customize things for your own needs.

**Comment by cr101** [comment]
OK. Good to know. I will need to use both Meta Queries and Tax Queries in my project.
