### ISSUE TITLE
Slack channel sign-up returns 'Failed! token_revoked'

### ISSUE THREAD

**Issue by therealgilles** [wp-graphql/wp-graphql#1635]
I tried to sign up to the slack channel and got 'Failed! token_revoked'.

**Comment by jasonbahl** [comment]
@therealgilles what link did you use to sign up for Slack and where on the web did you find the link? 

I used to use a service called Slackin to allow folks to sign-up for the Slack, but Slack now has this capability built-in so there's a new link to use. I've tried to update all references to the old link with the new one.

This link (https://join.slack.com/t/wp-graphql/shared_invite/zt-3vloo60z-PpJV2PFIwEathWDOxCTTLA) is the one in the README.md and in the footer of wpgraphql.com, and appears to be working.

**Comment by therealgilles** [comment]
Cannot find it anymore, so I guess it's all fixed.

PS: Noticed that the "content for the documentation" link returns 404 on this [page](https://github.com/wp-graphql/wp-graphql/blob/develop/documentation/Overview.md) (2nd link in the file).

**Comment by therealgilles** [comment]
Found an old slack link on this [page](https://github.com/wp-graphql/wp-graphql-woocommerce).

**Comment by jasonbahl** [comment]
@therealgilles ah! Thanks! I opened a PR to fix it on that repo.
