### ISSUE TITLE
wp-graphql generate schema that is compatible only with old version of GraphQL

### ISSUE THREAD

**Issue by bkstorm** [wp-graphql/wp-graphql#1637]
I just copy and paste the issue from graphql-code-generator: https://github.com/dotansimha/graphql-code-generator/issues/5298#issue-771604242

> **Describe the bug**
> I use wordpress with wp-graphql-woocommerce on the server side, next.js on the client side.
> When running yarn generate to generate react hooks, it throws an error: Syntax Error: Unexpected Name "TermNode".
> I check the schema, there is an interface named TermNode, I don't know why the error occurs, perhaps you know.
> 
> **To Reproduce**
> Please check the codesandbox. Run `yarn generate`
> https://codesandbox.io/s/adoring-villani-oez97?file=/schema.graphql

**Reason**

> Hi @bkstorm
> The schema you are using is compatible only with old versions of GraphQL. It's using , as separator for interfaces implementations. In new versions of GraphQL it should be &.

https://github.com/dotansimha/graphql-code-generator/issues/5298#issuecomment-750334769

**Solution**
Export schema with & instead of ,.

**Comment by jasonbahl** [comment]
This seems to have been resolved since the issue was opened. 

Here's a sandbox showing this working: https://codesandbox.io/s/charming-wind-hce9jt?file=/schema.graphql
