### ISSUE TITLE
Querying pages by URI yields unexpected results

### ISSUE THREAD

**Issue by westende** [wp-graphql/wp-graphql#1640]
First of all thank you for your work on this GraphQL interface. I appreciate it a lot.

When running the following queries using a non-existent URI (e.g. foo/bar or existing-page/foo) the query on page yields empty results (title = null) while the query using nodeByUri yields no results (nodeByUri = null). The latter is expected. I would expect the same behavior on the former. It seems the NodeResolver's resolve_uri method results in a false positive.

```graphql
query PageQuery1($path: ID!) {
  page(id: $path, idType: URI) {
    title
  }
}
```

```graphql
query PageQuery2($path: String!) {
  nodeByUri(uri: $path) {
    ... on Page {
      title
    }
  }
}
```

Also when running the queries above on a URI with the former part of the URI being valid and the latter part being numeric  (e.g. existing-page/123) both queries yield empty results (title = null) while this is not expected.

I am running wp-graphql/wp-graphql 1.0.4, wp-graphql/wp-graphql-acf 0.3.5, ashhitch/wp-graphql-yoast-seo 4.10.2 and valu/wp-graphql-lock 0.1.4.

**Comment by jasonbahl** [comment]
@westende thanks for the issue. 

Can you provide more information about the actual results you're getting from these queries and the actual results you're expecting?

Your statement above saying:

> the query on page yields empty results (title = null) while the query using nodeByUri yields no results (nodeByUri = null)

Seems right to me? One is empty, one is null. Can you clarify the difference of your uses of `empty` and `null`? It sounds like things are behaving the same?

**Comment by westende** [comment]
@jasonbahl of course. Hereby the requested data.

### Querying an existing URI

This yields expected results for both queries.

#### Query variables

```json
{
  "path": "test-page"
}
```

#### Results PageQuery1:

```json
{
  "data": {
    "page": {
      "title": "Test page"
    }
  }
}
```

#### Results PageQuery2:

```json
{
  "data": {
    "nodeByUri": {
      "title": "Test page"
    }
  }
}
```

### Querying a non-existing URI which is a child of the test-page

This yields unexpected results for PageQuery1. I would expect the page property to be null. Instead it is an object with null properties. This is what I call empty.
PageQuery2 yields expected results because a page with that URI does not exist (nodeByUri = null).

#### Query variables

```json
{
  "path": "test-page/does-not-exist"
}
```

#### Results PageQuery1:

```json
{
  "data": {
    "page": {
      "title": null
    }
  }
}
```

#### Results PageQuery2:

```json
{
  "data": {
    "nodeByUri": null
  }
}
```

### Querying a non-existing URI which is a child of the test-page and is numeric 

This yields unexpected results in both cases. A page with this URI does not exist, so it should not return any results. Instead it matches the parent.

#### Query variables

```json
{
  "path": "test-page/123"
}
```

#### Results PageQuery1:

```json
{
  "data": {
    "page": {
      "title": "Test page"
    }
  }
}
```

#### Results PageQuery2:

```json
{
  "data": {
    "nodeByUri": {
      "title": "Test page"
    }
  }
}
```

**Comment by justlevine** [comment]
As of writing (v1.7.2), this seems to be fixed.  @westende are you still running into this issue?

```graphql
query PageQuery1 {
  realPage: page(id: "/real-page", idType: URI) {
    title
  }
  fakePage: page(id: "/fake-page", idType: URI) {
    title
  }
  realNodeByURI: nodeByUri(uri: "/real-page") {
    ... on Page {
      title
    }
  }
  realNodeByURI: nodeByUri(uri: "/real-page") {
    ... on Page {
      title
    }
  }
}
```

![image](https://user-images.githubusercontent.com/29322304/161317253-80e8eb97-6e0f-41b6-81e8-d4f03047d4df.png)

**Comment by jasonbahl** [comment]
Closing this as it appears to have been fixed as shown by @justlevine
