### ISSUE TITLE
isFrontPage, isPostsPage throw unexpected errors

### ISSUE THREAD

**Issue by ravewebdev** [wp-graphql/wp-graphql#1641]
We're encountering issues related to single-page queries when including `isFrontPage` and/or `isPostsPage`.

### Expected behavior

Querying page data including `isFrontPage` should return boolean true or false depending on whether the queried page is set as the front page in WP.

### Actual behavior

If the queried page is set as the front page, the query works, returning true for `isFrontPage`; however, if the queried page is _not_ set as the front page, an error is thrown:

```
     "debugMessage": "Cannot return null for non-nullable field \"Page.isFrontPage\".",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 14,
          "column": 5
        }
      ],
      "path": [
        "page",
        "isFrontPage"
      ]
```

### Expected behavior

Querying page data including `isPostsPage` should return boolean true or false depending on whether the queried page is set as the posts page in WP.

### Actual behavior

a) If the queried page is _not_ set as the posts page, the query works, returning false for `isPostsPage`, when queried by either URI or database ID.

b) If the queried page is set as the posts page _and_ the page is queried by database ID, the query works, returning true for `isPostsPage`.

c) If the queried page is set as the posts page _and_ the page is queried by URI, the query fails with an error:

```
      "debugMessage": "Cannot return null for non-nullable field \"Page.databaseId\".",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "page",
        "databaseId"
      ]
```

The same query, on the same page, queried by URI, works fine and returns false for `isPostsPage` as soon as the page is unset as the posts page in WP. This appears potentially related to #1639, except the page in question _does_ exist in this case.

Using WP GraphQL v1.0.3

**Comment by jasonbahl** [comment]
I believe #1627 resolves this. Can you confirm? 

This has been merged and is part of the v1.0.5 release coming today.

**Comment by jasonbahl** [comment]
I've confirmed locally, but would love to have you also confirm that the queries you're running are working with this change. 

## v1.0.3

On v1.0.3 I get the following error:

![Screen Shot 2020-12-30 at 10 35 10 AM](https://user-images.githubusercontent.com/1260765/103371059-be62fd00-4a8b-11eb-86e6-852d18acca9e.png)

## v1.0.5

On v1.0.5 I do not get the error:

![Screen Shot 2020-12-30 at 10 35 16 AM](https://user-images.githubusercontent.com/1260765/103371061-befb9380-4a8b-11eb-9ca8-05f57b931576.png)

**Comment by ravewebdev** [comment]
With the upgrade to v1.0.5, this appears _mostly_ fixed:
- Queries on `isFrontPage` seem to be working as expected
- Queries on `isPostsPage` no longer throw errors, but still don't always return the correct value:
    - Querying the posts page by ID returns true for `isPostsPage`
    - Querying the posts page by URI return _false_ for `isPostsPage` (should also return true)

**Comment by jasonbahl** [comment]
@ravewebdev thanks for the update! I'll check it out further and add tests to ensure we don't have future regressions here.

**Comment by ravewebdev** [comment]
@jasonbahl the last issue noted above seems to be directly related to having that page set as posts page. I'm running the following query:

```
query GET_PAGE_BY_ID {
  page(id: "/post-archive/", idType: URI) {
    databaseId
    isPostsPage
    isFrontPage
    title
    uri
  }
}
```

A) If that page is _not_ set as posts page, it runs fine:
```
{
  "data": {
    "page": {
      "databaseId": 150,
      "isPostsPage": false,
      "isFrontPage": false,
      "title": "Post Archive",
      "uri": "/post-archive/"
    }
  },
  "extensions": {
    "debug": []
  }
}
```

B) If that page _is_ set as posts page, it breaks:
```
{
  "errors": [
    {
      "debugMessage": "Cannot return null for non-nullable field \"Page.databaseId\".",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "page",
        "databaseId"
      ],
      ...
    }
  ],
  "data": {
    "page": null
  },
  "extensions": {
    "debug": []
  }
}
```

And if I remove the `databaseId` field:
```
{
  "data": {
    "page": {
      "isPostsPage": false,
      "isFrontPage": false,
      "title": null,
      "uri": "/post-archive/"
    }
  },
  "extensions": {
    "debug": []
  }
}
```

**Comment by jasonbahl** [comment]
@ravewebdev ok, this is super helpful info! Thanks!

**Comment by jasonbahl** [comment]
Ok, I've been able to replicate this. Working on a fix now.

**Comment by jasonbahl** [comment]
@ravewebdev I opened #1670 which I believe addresses this. can you confirm it works for your particular case? I included a test as well to help reduce the chances of regressions on this.

**Comment by ravewebdev** [comment]
@jasonbahl yes, this seems to fix the issue, thanks!

**Comment by jasonbahl** [comment]
@ravewebdev thanks for confirming! I'll get it released shortly!
