### ISSUE TITLE
Users query does not follow count_user_posts() in case a user is not logged in

### ISSUE THREAD

**Issue by jmartinhoj** [wp-graphql/wp-graphql#1653]
When making a "users" graphql query, the expected result is that the returned list of users contain only the users that the current user has the capability to see. In case it is an unauthenticated request, only the users that have published content must be listed. If I use a filter to  count_user_posts(), the expected wpgraphql behaviour is such that it follows the  count_user_posts()'s new behaviour. However, this is not happening.

This way, if I use a third party plugin that filter count_user_posts() (such as the co-authors plugin), if a user is co-author of some posts, but never the original author, it will never be listed by the wpgraphql users query.

**Comment by jasonbahl** [comment]
closed by #1654
