### ISSUE TITLE
All the query now returns " cannot register duplicate Types to the Schema. The Type 'Template_' already exists in the Schema. Make sure to give new Types a unique name"

### ISSUE THREAD

**Issue by wcube-admin** [wp-graphql/wp-graphql#1658]
Ever since I've changed my WordPress site language from English to Traditional Chinese, All the GraphiQL calls start to return the following error / warning message

`"extensions": {
    "debug": [
      {
        "type": "DUPLICATE_TYPE",
        "message": "You cannot register duplicate Types to the Schema. The Type 'Template_' already exists in the Schema. Make sure to give new Types a unique name.",
        "type_name": "Template_",
        "stack": [
          "/home/public_html/wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php",
          "/home/public_html/wp-content/plugins/wp-graphql/access-functions.php",
          "/home/public_html/wp-includes/class-wp-hook.php",
          "/home/public_html/wp-includes/class-wp-hook.php",
          "/home/public_html/wp-includes/plugin.php",
          "/home/public_html/wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php",
          "/home/public_html/wp-includes/class-wp-hook.php",
          "/home/public_html/wp-includes/class-wp-hook.php",
          "/home/public_html/wp-includes/plugin.php",
          "/home/public_html/wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php",
          "/home/public_html/wp-content/plugins/wp-graphql/src/Registry/SchemaRegistry.php",
          "/home/farcent/web/farcent-wp.wstudio.io/public_html/wp-content/plugins/wp-graphql/wp-graphql.php",
          "/home/farcent/web/farcent-wp.wstudio.io/public_html/wp-content/plugins/wp-graphql/src/Request.php",
          "/home/farcent/web/farcent-wp.wstudio.io/public_html/wp-content/plugins/wp-graphql/src/Router.php",
          "/home/farcent/web/farcent-wp.wstudio.io/public_html/wp-content/plugins/wp-graphql/src/Router.php",
          "/home/farcent/web/farcent-wp.wstudio.io/public_html/wp-includes/class-wp-hook.php",
          "/home/farcent/web/farcent-wp.wstudio.io/public_html/wp-includes/class-wp-hook.php",
          "/home/farcent/web/farcent-wp.wstudio.io/public_html/wp-includes/plugin.php",
          "/home/farcent/web/farcent-wp.wstudio.io/public_html/wp-includes/class-wp.php",
          "/home/farcent/web/farcent-wp.wstudio.io/public_html/wp-includes/class-wp.php",
          "/home/farcent/web/farcent-wp.wstudio.io/public_html/wp-includes/functions.php",
          "/home/farcent/web/farcent-wp.wstudio.io/public_html/wp-blog-header.php",
          "/home/farcent/web/farcent-wp.wstudio.io/public_html/index.php"
        ]
      }
    ]
  }`
![image](https://user-images.githubusercontent.com/66291959/103592036-febbf280-4f45-11eb-90ea-2cedf3bd80c2.png)

**Steps to replicate**
- Install WP in English
- Change Site Language (Under Settings -> General)  to Tradition Chinese

**Plugins Versions :**
WP GraphiQL : 1.0.1
WP GraphQL : 1.0
WPGraphQL for Advanced Custom Fields : 0.3.2
WPGraphQL JWT Authentication : 0.4.1
WPGraphQL WooCommerce (WooGraphQL) : 0.5.0

**Comment by wcube-admin** [comment]
And once I've changed the site language back to English, that error disappeared

**Comment by mikexavier** [comment]
I'm also seeing this when running queries in GraphiQL IDE in WP.

<details>
  <summary>DUPLICATE_TYPE</summary>

```
"extensions": {
    "debug": [
      {
        "type": "DUPLICATE_TYPE",
        "message": "You cannot register duplicate Types to the Schema. The Type 'page_Faqs' already exists in the Schema. Make sure to give new Types a unique name.",
        "type_name": "page_Faqs",
        "stack": [
```  
</details>

<details>
  <summary>...then below that</summary>

```
{
        "type": "DUPLICATE_TYPE",
        "message": "You cannot register duplicate Types to the Schema. The Type 'page_Faqs_Faqs' already exists in the Schema. Make sure to give new Types a unique name.",
        "type_name": "page_Faqs_Faqs",
        "stack": [
```
</details>

<details>
  <summary>...and so on</summary>

```
{
        "type": "DUPLICATE_TYPE",
        "message": "You cannot register duplicate Types to the Schema. The Type 'page_Faqs_Faqs_faq' already exists in the Schema. Make sure to give new Types a unique name.",
        "type_name": "page_Faqs_Faqs_faq",
        "stack": [
```
</details>

It goes on like this for what looks like every field I have on the site.

@jasonbahl I added you to the [repo](https://github.com/jungfrausportsholding/adventurepark), and happy to add you as a user to the WP installation if that helps?

**Comment by jenkin** [comment]
Same here. Errors seem to disappear if all graphql names of field groups are different AND if there are no multiple positions of the same type for a field group.

**Comment by andymark-by** [comment]
Have same problem, someone find a solution? rename all field - it's bad idea

**Comment by HumidBrains** [comment]
@jasonbahl any update on this? For me, it's unfortunately a blocker.

**Comment by OWMC** [comment]
@jasonbahl what's up with this? i've made a settings group for some fields, but in the WP graphiql (and Chromiql) the fields only show up under allSettings (as myGroupMyField). Also when I refresh ChromeIql I get a warning `... fields must be an object with field names as keys or a function which returns such an object`.

Outside of allSettings, I do see MyGroup below, but it has no fields. 

**But either way**, the Gatsby build fails with an error along the lines of "must define one or more fields".

I am able to at least get it working by removing the field group from my custom settings wp plugin. So I end up with a query like:

`allSettings {
settingsSettingsField
}`

while this works, it's not clean. and with debug on i get a warning in the wp graphiql IDE like this

`        "type": "DUPLICATE_TYPE",
        "message": "You cannot register duplicate Types to the Schema. The Type 'Settings' already exists in the Schema. Make sure to give new Types a unique name.",
        "type_name": "Settings",
`

**Comment by justlevine** [comment]
Seems this issue stems from [various name sanitation `preg_replace()` calls](https://github.com/wp-graphql/wp-graphql/search?q=A-Za-z0-9) that strip out non-ASCII characters instead of replacing them, causing them to be registered as a duplicate e.g `Template_`.

Also seems that `WPGraphiQL` at least now throws a more informative error, at least in some cases:

![image](https://user-images.githubusercontent.com/29322304/168139959-db2a99b5-b1ed-4c3d-b547-9045017213eb.png)

I think the way to fix this would be to replace them with a call to a `get_safe_name()` helper (similar to how enums handle underscores) that _replaces_ unsafe characters instead of stripping them entirely.

Related: https://github.com/wp-graphql/wp-graphql/issues/2175

**Comment by justlevine** [comment]
After some research, I think we should be able to do this with `iconv()` (and [symphony's polyfill](https://symfony.com/doc/4.1/components/polyfill_iconv.html) ), but I wonder the performance implications.

I rarely use WP in i18n contexts, so someone with more knowledge about it should weigh in.

**Comment by proweb** [comment]
Same here. If locale RU get error
```
Uncaught (in promise) GraphQLError: Names must only contain [_a-zA-Z0-9] but "Template_Шаблон обложки" does not.
```

**Comment by HarleySalas** [comment]
So, is there a current best solution for this issue? Really would like to keep my site's default locale as none-English.

**Comment by justlevine** [comment]
@HarleySalas probably the best workaround right now is to conditionally use the `gettext` filter to give your templates an ASCII name during WPGraphiQL calls.

**Comment by Dev284** [comment]
I am facing this issue, Invested lots of time and my project is delayed.

<b>Warning</b>:  Could not determine type of attribute "templateLock" in "CoreGroupBlockDeprecatedV4Attributes" in <b>/Applications/MAMP/htdocs/<site-folder>/wp-content/plugins/wp-graphql-gutenberg/src/Schema/Types/BlockTypes.php</b> on line <b>88</b><br />


>File name page_Topctermsacf_HeroFields:


{"type":"**DUPLICATE_TYPE**","message":"You cannot register duplicate Types to the Schema. The Type 'page_Topctermsacf_HeroFields' already exists in the Schema. Make sure to give new Types a unique name.","type_name":"page_Topctermsacf_HeroFields","stack":["\/Applications\/MAMP\/htdocs\/site-name\/wp-content\/plugins\/wp-graphql\/src\/Registry\/TypeRegistry.php:666","\/Applications\/MAMP\/htdocs\/site-name\/wp-content\/plugins\/wp-graphql\/access-functions.php:184","\/Applications\/MAMP\/htdocs\/site-name\/wp-includes\/class-wp-hook.php:308","\/Applications\/MAMP\/htdocs\/site-name\/wp-includes\/class-wp-hook.php:332","\/Applications\/MAMP\/htdocs\/site-name\/wp-includes\/plugin.php:517","\/Applications\/MAMP\/htdocs\/site-name\/wp-content\/plugins\/wp-graphql\/src\/Registry\/TypeRegistry.php:577","\/Applications\/MAMP\/htdocs\/site-name\/wp-includes\/class-wp-hook.php:308","\/Applications\/MAMP\/htdocs\/site-name\/wp-includes\/class-wp-hook.php:332","\/Applications\/MAMP\/htdocs\/site-name\/wp-includes\/plugin.php:517","\/Applications\/MAMP\/htdocs\/site-name\/wp-content\/plugins\/wp-graphql\/src\/Registry\/TypeRegistry.php:267","\/Applications\/MAMP\/htdocs\/site-name\/wp-content\/plugins\/wp-graphql\/src\/Registry\/SchemaRegistry.php:38","\/Applications\/MAMP\/htdocs\/site-name\/wp-content\/plugins\/wp-graphql\/src\/WPGraphQL.php:785","\/Applications\/MAMP\/htdocs\/site-name\/wp-content\/plugins\/wp-graphql\/src\/Request.php:158","\/Applications\/MAMP\/htdocs\/site-name\/wp-content\/plugins\/wp-graphql\/src\/Router.php:465","\/Applications\/MAMP\/htdocs\/site-name\/wp-content\/plugins\/wp-graphql\/src\/Router.php:275","\/Applications\/MAMP\/htdocs\/site-name\/wp-includes\/class-wp-hook.php:308","\/Applications\/MAMP\/htdocs\/site-name\/wp-includes\/class-wp-hook.php:332","\/Applications\/MAMP\/htdocs\/site-name\/wp-



I am getting data in rest end point but not getting in graphql.

Also can any  share where graphql schema is stored?

Thank You

**Comment by jonnydo** [comment]
9:27:32 PM:   Failed to load schema from https://caviar-boutique.ru/graphql:
9:27:32 PM:   GraphQL introspection is not allowed, but the query contained __schema or __type
9:27:32 PM:   GraphQLError: GraphQL introspection is not allowed, but the query contained __schema or __type
9:27:32 PM:   at createGraphQLError (node_modules/@graphql-tools/utils/esm/errors.js:6:12)
9:27:32 PM:   at node_modules/@graphql-tools/wrap/esm/introspect.js:10:71
9:27:32 PM:   at Array.map (<anonymous>)
9:27:32 PM:   at getSchemaFromIntrospection (node_modules/@graphql-tools/wrap/esm/introspect.js:10:58)
9:27:32 PM:   at node_modules/@graphql-tools/wrap/esm/introspect.js:41:32
9:27:32 PM:   at processTicksAndRejections (node:internal/process/task_queues:96:5)
9:27:32 PM:   at async UrlLoader.load (node_modules/@graphql-tools/url-loader/esm/index.js:216:29)
9:27:32 PM:   at async node_modules/@graphql-tools/load/esm/load-typedefs/load-file.js:14:39
9:27:32 PM:   at async Promise.all (index 5)
9:27:32 PM:   at async loadFile (node_modules/@graphql-tools/load/esm/load-typedefs/load-file.js:12:9)
9:27:32 PM:   at async node_modules/@graphql-tools/load/esm/load-typedefs/collect-sources.js:201:25

**Comment by justlevine** [comment]
Hey all, just wanted to provide a quick update on this.

First off, #2808 added a fallback mechanism, where if the Template Name doesnt contain any ASCII characters, the GraphQL name will fallback to using the filename. 
If the file name also isn't ASCII, then you'll get a debug notice telling you exactly which template is throwing the file, _and_ the graphql type will fallback to `DefaultTemplate`, so no more broken schemas 🚀

Even cooler IMO is #2958, which adds the `graphql_pre_format_name` filter, allowing you to provide transliteration maps (or an external transliterator like `iconv`) that will work across the entire WPGraphQL schema (template names, enum values, object types, autogenerated fields names, etc)!!!
There's a basic example over in the PR description, and I'm sure we'll see people releasing fully-fledged recipes soon.

These improvements have already been merged to the `develop` branch, and if all goes well will be included in the next release 🤞. 
I'll make sure to report back here once that happens.

**Comment by justlevine** [comment]
> Hey all, just wanted to provide a quick update on this.
> 
> First off, #2808 added a fallback mechanism, where if the Template Name doesnt contain any ASCII characters, the GraphQL name will fallback to using the filename.
> 
> If the file name also isn't ASCII, then you'll get a debug notice telling you exactly which template is throwing the file (and why), _and_ the GraphQL type will fallback to `DefaultTemplate`, so no more broken schemas 🚀
> 
> Even cooler IMO is #2958, which adds the `graphql_pre_format_name` filter, allowing you to provide transliteration maps (or an external transliterator like `iconv`) that will work across the entire WPGraphQL schema (template names, enum values, object types, autogenerated fields names, etc)!!! This is a huge step to supporting i18n while keeping the schema semantic 🙌🌍💪
> 
> There's a basic example over in the PR description, and I'm sure we'll see people releasing fully-fledged recipes soon.
> 
> These improvements have already been merged to the `develop` branch, and if all goes well will be included in the next release 🤞. I'll make sure to report back here once that happens.

These changes are now live in [v1.17.0](https://github.com/wp-graphql/wp-graphql/releases/tag/v1.17.0)

**Comment by rossjcoop** [comment]
In case this helps anyone, I had this error and it was due to one of my ACF Field groups having the same WPGraphQL type name as the post type itself. So, I named my GraphQL type name "region" when I also have a cpt of "region". If that makes sense.
