### ISSUE TITLE
Add New updateUserPassword Mutation

### ISSUE THREAD

**Issue by kellenmace** [wp-graphql/wp-graphql#1660]
A conversation in the WPGraphQL Slack made me realize that we don't currently have a mutation that can be used to update the password of an already-logged-in user (the `sendPasswordResetEmail` and `resetUserPassword` mutations are for logged-out users who forgot their password). This would be similar to a user visiting their profile page in the wp-admin and updating their own password, but done from a decoupled frontend app instead.

This mutation could also be used on decoupled administrative interfaces where a user like an Administrator wants to manually update the password of another user.

I'm thinking it may make sense to add a new `updateUserPassword` mutation to serve this purpose. It could work like this:

- Accept `login` and `password` input arguments.
- When the mutation executes, check to see if the user is logged in and has the permissions necessary to update the password for that user. This could mean that they either ARE authenticated as that user, or that they have the capabilities required to set the passwords of others, like an Administrator would. If they don't, throw an error and don't perform a password update.
- Call WP's `reset_password()` function to perform the password update and return the ID of the user whose password was updated in the response, similar to what the `resetUserPassword` mutation does.

I'd love some input from others on this. Thanks!

**Comment by ardiewen** [comment]
hey @kellenmace, have you tried the update user mutation? This appears to be possible with the optional password input parameter.

```
mutation UPDATE_USER {
  updateUser(input: {id: ..., password: ...}) {
    user {
      id
    }
  }
}
```

This works for me in the GraphiQL IDE as an admin, but I would wager it works for authenticated users as well. If this works, can you let me know? This is functionality I'll be looking for in the future as well.

**Comment by justlevine** [comment]
I've confirmed this is working for authenticated users in v1.8.7.
