### ISSUE TITLE
Graphql plugin menus endpoint returning empty array. 

### ISSUE THREAD

**Issue by siddhantdante** [wp-graphql/wp-graphql#1661]
I am using v1.0.5.

query MyQuery {
  menus(where: {}) {
    edges {
      node {
        name
        count
        id
      }
    }
  }
}

**Comment by jasonbahl** [comment]
@siddhantdante Do you have any menus assigned to a Menu Location? This is usually the most common cause of menus not being queryable. 

See: https://www.wpgraphql.com/docs/menus/#access-control

This snippet might also be useful: https://www.wpgraphql.com/recipes/making-menus-and-menu-items-public/

**Comment by siddhantdante** [comment]
> @siddhantdante Do you have any menus assigned to a Menu Location? This is usually the most common cause of menus not being queryable.
> 
> See: https://www.wpgraphql.com/docs/menus/#access-control
> 
> This snippet might also be useful: https://www.wpgraphql.com/recipes/making-menus-and-menu-items-public/

thank you
