### ISSUE TITLE
composer require wp-graphql/wp-graphql installs completely different package

### ISSUE THREAD

**Issue by westende** [wp-graphql/wp-graphql#1662]
There seems to be an issue with the repository as I see tags >= 2.0 appear as package versions on packagist.

**Comment by jasonbahl** [comment]
@westende ya, I'm not quit sure what's happened here. I got a DM in Slack about this as well. Looking into it. Seems like possibly a Packagist issue as the plugin seems to bel accurate on wpackagist: https://wpackagist.org/search?q=wp-graphql&type=any&search=

**Comment by westende** [comment]
@jasonbahl AFAIK packagist reads your tags. I am also seeing these versions in this repo. For example https://github.com/wp-graphql/wp-graphql/releases/tag/2.0.3

**Comment by jasonbahl** [comment]
Hmm. Not sure how those tags got here. Checking it out.

**Comment by sboerrigter** [comment]
Same issue here. It works if you specify a correct version in `composer.json` like so:

```
"require": {
  "wp-graphql/wp-graphql": "v1.0.5",
},
```

**Comment by jasonbahl** [comment]
It looks like somehow a bunch of tags were pushed. I must have made some clerical error. I'm working on getting them cleaned up and hopefully we'll have Packagist updated with proper data again here soon.

**Comment by jasonbahl** [comment]
@sboerrigter @westende I believe this has been resolved. I'm not sure what I did, but somehow I had pulled tags from another repo (unrelated to WPGraphQL) to my local install and pushed those tags up to WPGraphQL. 

I cleaned up the tags in Github and Packagist and from what I can tell this is resolved now. 

Packagist shows v1.0.5 as the latest and Github is no longer showing the erroneous tags.
