### ISSUE TITLE
1.1.0 breaks compatibility with idType: SLUG queries (wp-graphql & wp-graphql-yoast-seo)

### ISSUE THREAD

**Issue by davevanhoorn** [wp-graphql/wp-graphql#1668]
1.1.0 seems to break compatibility with wp-graphql-yoast-seo.

I'm not sure whether I should place this issue here or in the repository of WP GraphQL Yoast, but downgrading to 1.0.5 fixes it, so I thought this would be the right place. If it's not, please close it and excuse me for taking your time.

**GraphQL query (in wp-admin Graphiql-ide):**
`query MyQuery {
  productCategory(id: "xxxxxx", idType: SLUG) {
    seo {
      opengraphSiteName
    }
  }
}`

**Partial debug message:**

`"debugMessage": "Argument 1 passed to WPGraphQL\\Data\\DataSource::resolve_post_object() must be of the type int, string given, called in /srv/www/xxx.nl/current/web/app/plugins/wp-graphql-yoast-seo/wp-graphql-yoast-seo.php on line 1071",`

**Complete debug message:**
[Gist can be found here](https://gist.github.com/davevanhoorn/05a0e2d4f3048f70d69f850fc011d7d8)

The error message itself is clear, but if I use SLUG as the ID type, it shouldn't expect an int?

**Reproduce by using:**
- wp-graphql (1.1.0)
- wp-graphql-yoast-seo (4.10.2) 

**Temp fixed by using:**
- wp-graphql (1.0.5)
- wp-graphql-yoast-seo (4.10.2)

**Comment by jasonbahl** [comment]
@davevanhoorn thanks for the issue. looking into this.

**Comment by jasonbahl** [comment]
@davevanhoorn @ashhitch I believe the yoast extension needs to be updated here. 

Prior to this release, the `datasource::resolve_post_object()` method already expected an integer to be passed to it, but now it just enforces it.

**Comment by jasonbahl** [comment]
@davevanhoorn @ashhitch I've opened a PR on WPGraphQL for Yoast SEO to get it updated to the latest: https://github.com/ashhitch/wp-graphql-yoast-seo/pull/79

The `DataSource::resolve_post_object()` method has been deprecated for quite some time, so it should get updated regardless.

@ashhitch happy to help get it over the finish line if needed. Feel free to ping me here or on Slack if you need to chat through it. 

Closing this issue in favor of this existing issue: https://github.com/ashhitch/wp-graphql-yoast-seo/issues/63

**Comment by ashhitch** [comment]
@davevanhoorn v4.11.0 fixes this issue: https://github.com/ashhitch/wp-graphql-yoast-seo/releases/tag/v4.11.0

**Comment by davevanhoorn** [comment]
@jasonbahl and @ashhitch, thanks for picking this up so quick. Awesome. Where can I buy you a beer?

**Comment by jasonbahl** [comment]
Give Gatsby Cloud (https://www.gatsbyjs.com/cloud/) a spin (there's a Free Tier) and we'll call it even. Haha! 

You could write a blog post or tweet about your experiences with WPGraphQL. That's coffee for me!

**Comment by mehidi258** [comment]
@davevanhoorn i am using latest version of yoast and graphql but still getting same error 
![image](https://user-images.githubusercontent.com/34313754/109189945-c951b980-77be-11eb-8154-5aa11576b99e.png)
cc: @jasonbahl
