### ISSUE TITLE
Large post content not returned

### ISSUE THREAD

**Issue by martinosmartinos** [wp-graphql/wp-graphql#1669]
I run into a problem while developing React Native app and Wpgraphql where query to a post with quite large content, returns either error or null.

Example query:
```
query MyQuery {
  post(id: "62256", idType: DATABASE_ID) {
    content(format: RENDERED)
  }
}
```

Nothing fancy as you see and I did try retriving content with different formats like RAW. In GraphiQL IDE such query to quite heavy post (above 20k characters), results in receiving an error "SyntaxError: Unexpected end of JSON input".
 
 Server itself is on a top level side specs wise and it is strange it only happens when above mentioned thereshold is met: above 20k characters.
 
 Tested using **v1.0.5**

 Any ideas or help would much appreciated!

**Comment by jasonbahl** [comment]
@martinosmartinos have you gone through the steps listed on the debugging page? Specifically this section: https://www.wpgraphql.com/docs/debugging/#unexpected-token-in-json-at-position-0

My guess is that something within the content might be having issues resolving. Some code that executes during the `apply_filters( 'the_content' )` filter, perhaps? This is common to shortcodes, page builders and gutenberg among other things. 

There's a chance it's the size of the content, but my guess is there are functions executing to filter the content, and there's an underlying bug there.

**Comment by martinosmartinos** [comment]
@jasonbahl thanks for propmt reply!
I did debug that issue using link provided by you and response to those posts in developer console's network tab is null:
`data: {post: null}`
 The only shortcodes which do exist in those lenghty posts are actually standard figures with captions. Similar to those posts which do not fail but below that 20k characters :/ Not sure if it helps but REST API handles problematic posts with no problem.

**Comment by jasonbahl** [comment]
Do you have a staging site I could get access to and do some debugging?

**Comment by martinosmartinos** [comment]
Unfortunately live only but if you can guide me I could add myself, unless it is super tricky :)

**Comment by martinosmartinos** [comment]
I did more testing and I run similar query on different site which belongs to the same Wordpress multisite network. That network site has less published posts (398) and large posts content comes in response data. Site with 19k published posts fails on the same task. Majority of plugins are network active and the ones which are not I disabled one by one, yet no luck.

**Comment by bhardie** [comment]
Can you share a list of the sites active plugins so we can try to replicate?  Also, if you have any sever logs showing errors, those would be helpful too.  Our hunch is that there is a plugin applying filters on the content that is causing issues with the query response.

**Comment by martinosmartinos** [comment]
@bhardie thanks for coming back. List of enabled plugins is quite extensive and the strangest part is that on sites where published posts count is relevantly small - content comes in. Same plugins enabled network wide. I also do not see any related errors in a server log.

`

Advanced Ads | Version 1.24.2 by Thomas Maier, Advanced Ads GmbH \| Auto-updates enabled
-- | --
Advanced Ads Pro | Version 2.2.1 by Thomas Maier \| Auto-updates disabled
Advanced Ads – Geo Targeting | Version 1.1.10 by Thomas Maier \| Auto-updates disabled
Advanced Ads – Selling Ads | Version 1.2.4 by Thomas Maier \| Auto-updates disabled
Advanced Ads –&nbsp;Ad Tracking | Version 1.8.13 by Thomas Maier \| Auto-updates disabled
Amazon Web Services | Version 1.0.5 by Delicious Brains \| Auto-updates disabled
AMP | Version 2.1.0 by AMP Project Contributors (Latest version: 2.1.2) \| Auto-updates disabled
Andrea Pernici News Sitemap for Google | Version 1.0.16 by Andrea Pernici \| Auto-updates disabled
Bloom | Version 1.3.12 by Elegant Themes \| Auto-updates disabled
Drop Shadow Boxes | Version 1.7.3 by Steven Henty \| Auto-updates disabled
Feedzy RSS Feeds Lite | Version 3.4.3 by Themeisle (Latest version: 3.7.0) \| Auto-updates disabled
Fonts Plugin \| Google Fonts Typography | Version 2.5.7 by Fonts Plugin (Latest version: 2.5.8) \| Auto-updates disabled
Google XML Sitemaps | Version 4.1.1 by Auctollo \| Auto-updates disabled
GTmetrix for WordPress | Version 0.4.4 by GTmetrix \| Auto-updates disabled
HubSpot All-In-One Marketing - Forms, Popups, Live Chat | Version 8.0.1 by HubSpot (Latest version: 8.0.141) \| Auto-updates disabled
HungryFEED | Version 1.6.3 by VerySimple \| Auto-updates disabled
iframe | Version 4.5 by webvitaly \| Auto-updates disabled
Insert HTML Snippet | Version 1.3.2 by xyzscripts.com \| Auto-updates disabled
JotForm Embed Forms | Version 1.2.5 by JotForm.com \| Auto-updates disabled
Multisite User Sync | Version 1.2 by Shamim \| Auto-updates disabled
Nelio External Featured Image | Version 1.2.0 by Nelio Software \| Auto-updates disabled
OneSignal Push Notifications | Version 2.2.1 by OneSignal \| Auto-updates disabled
Paid Memberships Pro - Add Member Admin | Version .4 by Stranger Studios \| Auto-updates disabled
Paid Memberships Pro - Donations | Version .4 by Paid Memberships Pro \| Auto-updates disabled
Paid Memberships Pro - Signup Shortcode | Version .2 by Stranger Studios \| Auto-updates disabled
Paid Memberships Pro - State Dropdowns Add On | Version 0.1 by Stranger Studios \| Auto-updates disabled
PMPro Reason For Cancelling | Version .1.1 by Stranger Studios \| Auto-updates disabled
Pods - Custom Content Types and Fields | Version 2.7.22 by Pods Framework Team (Latest version: 2.7.27) \| Auto-updates disabled
Post Thumbnail Editor | Version 2.4.8 by sewpafly \| Auto-updates disabled
Progressive WordPress (PWA) | Version 2.1.13 by Nico Martin \| Auto-updates disabled
Publish to Apple News | Version 2.1.2 by Alley \| Auto-updates disabled
REST API ALL CORS | Version 0.0.1 by Josh Pollock \| Auto-updates disabled
RSS Via Shortcode for Page &amp; Post | Version 1.2.b by Susanta K Beura \| Auto-updates disabled
Search &amp; Replace | Version 3.2.1 by Inpsyde GmbH \| Auto-updates disabled
Simple Drop Cap | Version 1.2.8 by Yudhistira Mauris \| Auto-updates disabled
Simple Facebook Instant Articles | Version 0.5.3 by Jake Spurlock, Human Made Limited \| Auto-updates disabled
Smush | Version 3.8.4 by WPMU DEV \| Auto-updates disabled
Soliloquy | Version 2.6.0 by Soliloquy Team \| Auto-updates disabled
TablePress | Version 1.13 by Tobias Bäthge \| Auto-updates disabled
Third Column | Version 2.0 by Marcus Downing \| Auto-updates disabled
User Role Editor | Version 4.59 by Vladimir Garagulya (Latest version: 4.59.1) \| Auto-updates disabled
WP External Links | Version 2.48 by WebFactory Ltd \| Auto-updates disabled
WP GraphQL | Version 1.3.8 by WPGraphQL \| Auto-updates disabled
WP Missed Schedule (The Original) | Version 2014.1231.2017.5 by sLaNGjIs Team \| Auto-updates disabled
WP Offload Media | Version 2.4.1 by Delicious Brains \| Auto-updates disabled
WP Scroll Depth | Version 1.5.1 by Lon Koenig (Firebrand LLC) \| Auto-updates disabled
Yoast SEO Premium | Version 15.0 by Team Yoast \| Auto-updates disabled

`

**Comment by justlevine** [comment]
I've tried replicating this on localhost with both `WP External Links` and `Yoast SEO Premium` enabled, and a [character count of `99,999`](https://www.blindtextgenerator.com/lorem-ipsum), and it still comes back fine.

Pretty sure @bhardie's hunch about an errant filter on the content, is/was causing the server to time out, especially considering `that on sites where published posts count is relevantly small - content comes in`.

Recommending to close this (we can always re-open if someone comes forward with a clean reproduction sans other plugins).
