### ISSUE TITLE
Slack signup app shows "Failed! token_revoked" error

### ISSUE THREAD

**Issue by benknight** [wp-graphql/wp-graphql#1672]
Steps to repo:

1. Visit https://wpgql-slack.herokuapp.com/
2. Enter email
3. Receive error (screenshot below)

![image](https://user-images.githubusercontent.com/786691/103971245-9b77cd80-519c-11eb-9109-e3fd1b7f1ffa.png)

**Comment by jasonbahl** [comment]
I've tried to kill all links that I can to that app. The proper link to join is in the Github README and the footer and community page of WPGraphQL.com

I've deleted the Heroku app even but still can't seem to get that link to die.

**Comment by benknight** [comment]
@jasonbahl ah! I found that link when creating a new issue, 

![image](https://user-images.githubusercontent.com/786691/103977874-c407c380-51ac-11eb-8bdd-24403bb04633.png)

I suppose it's as easy as just updating that text and then this issue can be closed :)

**Comment by jasonbahl** [comment]
Ah! Thanks for pointing out that link. I'll get it updated in that template. 

Thanks!

**Comment by jasonbahl** [comment]
Updated the link in the issue template: https://github.com/wp-graphql/wp-graphql/commit/0a72a78f06ad811ec95bd7298a49642d25e5b952
