### ISSUE TITLE
Filter graphql_schema_config documentation is incorrect

### ISSUE THREAD

**Issue by zacscott** [wp-graphql/wp-graphql#1686]
The documentation for the `graphql_schema_config` filter states that the config is an array, however it is actually an instance of `GraphQL\Type\SchemaConfig`

https://www.wpgraphql.com/filters/graphql_schema_config/

I believe this was changed as part of v1.1.0 release - https://github.com/wp-graphql/wp-graphql/commit/640ea27fc8a2c5af0726df7744c8d33c52c4d867

This was an issue on an extension plugin and I figure the documentation should be updated. https://github.com/pristas-peter/wp-graphql-gutenberg/issues/72

**Comment by jasonbahl** [comment]
Updated the doc
