### ISSUE TITLE
nodeByUri does not return ContentType for Posts Page.

### ISSUE THREAD

**Issue by jonshipman** [wp-graphql/wp-graphql#1687]
Performing a query on ``nodeByUri`` for the page_for_posts uri returns the Page type instead of the ContentType type.

With v1.1.0 the below query works correctly:
```
query {
  nodeByUri(uri: "/blog") {
    ... on Page {
      id
      isPostsPage
      title
    }
    ... on ContentType {
      id
      name
      contentNodes(first: 3) {
        nodes {
          id
        }
      }
    }
  }
}
```
It will return 3 posts under contentNodes. When run on v1.1.2 it returns the Page (isPostsPage: true, title: "Blog") instead of the contentNodes.

**Comment by jonshipman** [comment]
See issue https://github.com/wp-graphql/wp-graphql/issues/1670 for details for the changes.

**Comment by jonshipman** [comment]
Just confirmed that changing line 366 of NodeResolver to ``return $this->context->get_loader( 'post_type' )->load_deferred( 'post' );`` will fix the issue.

**Comment by jasonbahl** [comment]
@jonshipman I believe this has been addressed? Can you confirm?

**Comment by jonshipman** [comment]
Sorry for the MIA, but I did manage to check last week and it does not appear to be fixed. Unfortunately my manager had instructed me to stop using wp-graphql 😭 However, this week a client order on an older site came across my desk and I believe it was affected. I'll try and see what's up.

**Comment by jasonbahl** [comment]
@jonshipman super bummed to hear that your manager instructed you to stop using WPGraphQL. Curious what lead that decision and what we can do to change that? 

As far as this bug goes, if you're able to reproduce, and provide proper steps to reproduce, that would be great! 

This feels like possibly could be related to specific permalink / WordPress settings configuration?

**Comment by jonshipman** [comment]
Oh he's just micro-managing I wouldn't worry about that.

**Comment by jasonbahl** [comment]
@jonshipman I opened a PR to address this. https://github.com/wp-graphql/wp-graphql/pull/2464
