### ISSUE TITLE
Missing onError handler for invocation 'building-schema' when site language is set to Russian

### ISSUE THREAD

**Issue by kivils** [wp-graphql/wp-graphql#1697]
Hi!
I'm facing an error: `gatsby develop` fails when site language is set to Russian in wordpress admin panel.
If I switch site language to English (UK) - `gatsby develop` doesn't fail and static site is generated as expected.

`gatsby develop` worked fine with earlier versions of plugins (see below), and stopped working after upgrade.

Created an issue in [gatsby-source-wordpress-experimental](https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/427), but it seems that the issue is related to wp-graphql. You can check comments there for overview.

If I understand correctly, WPGraphQL uses `msgstr` from themes language files for page template, and it's in Cyrillic (in case of Russian, default twenty-twenty). So maybe we could use `msgid` here instead to have alphanumeric symbols only, or add Cyrillic support for all queries.

# Environment:
Wordpress: 5.5.3
wp theme: twenty-twenty 1.5 (default)
Site language: Russian
gatsby: 2.25.0
gatsby-source-wordpress-experimental: 7.0.3
WP Gatsby: 0.9.2
WP GraphQL: 1.1.3

# Error message
```
ERROR

Missing onError handler for invocation 'building-schema', error was 'Names must
match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "WpTemplate_Шаблон обложки" does not.'.
Stacktrace was 'GraphQLError: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but
"WpTemplate_Шаблон обложки" does not.
    at isValidNameError
(C:\projects\artelx\node_modules\graphql\utilities\assertValidName.js:42:12)
    at assertValidName
(C:\projects\artelx\node_modules\graphql\utilities\assertValidName.js:21:15)
    at checkIsAllowedTypeName
(C:\projects\artelx\node_modules\gatsby\src\schema\schema.js:578:3)
    at forEach
(C:\projects\artelx\node_modules\gatsby\src\schema\schema.js:284:9)
    at Array.forEach (<anonymous>)
    at addTypes
(C:\projects\artelx\node_modules\gatsby\src\schema\schema.js:246:9)
    at updateSchemaComposer
(C:\projects\artelx\node_modules\gatsby\src\schema\schema.js:135:9)
    at buildSchema
(C:\projects\artelx\node_modules\gatsby\src\schema\schema.js:62:9)
    at build (C:\projects\artelx\node_modules\gatsby\src\schema\index.js:105:24)
    at buildSchema
(C:\projects\artelx\node_modules\gatsby\src\services\build-schema.ts:19:3)'
```

# Worked in this environment
- Wordpress: 5.5.3 -> same version
- wp theme: twenty-twenty 1.5 (default) -> same version
- Site language: Russian -> the same
- gatsby: 2.24.63
- gatsby-source-wordpress-experimental: 1.4.6
- WP Gatsby: 0.4.*
- WP GraphQL: 0.3.1

**Comment by jasonbahl** [comment]
I'm closing this as I believe this is a Gatsby issue, not a WPGraphQL issue. 

If you believe this is an issue with WPGraphQL directly, please open a new issue with more details to reproduce in WPGraphQL directly.
