### ISSUE TITLE
CORS error when updating to v1.1.3

### ISSUE THREAD

**Issue by Marco-Daniel** [wp-graphql/wp-graphql#1698]
As requested in the slack channel i'm opening an issue here. 
I have a Gatsby e-commerce site, which on the client side connects to the Wordpress instance using Apollo

Everything works great until I update the wp-graphql plugin to v1.1.3 (coming from v1.0.0). After that I'm getting CORS errors ...has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
Tried different methods of getting CORS to work, including the wp-graphql-cors plugin, but nothing seems to make any difference.

The Wordpress plugins i'm using:

- Add WPGraphQL SEO 4.11.0
- Advanced Custom Fields 5.9.4
- Custom Post Type UI 1.8.2
- Facebook for WooCommerce 2.2.0
- JAMstack Deployments 1.1.0
- Limit Login Attempts Reloaded 2.19.1
- Mollie-betalingen voor WooCommerce 5.11.0
- reSmush.it Image Optimizer 0.3.11
- WooCommerce 4.9.0
- WP fail2ban 4.3.0.9
- WP Gatsby 0.9.2
- WP GraphQL 1.0
- WP GraphQL Gutenberg 0.3.4
- WPGraphQL for Advanced Custom Fields 0.3.5 
- WPGraphQL JWT Authentication 0.4.1
- WPGraphQL WooCommerce (WooGraphQL) 0.7.0
- WPvivid Backup Plugin 0.9.49
- Yoast SEO 15.6.2

Wordpress is hosted on a subdomain from the Gatsby front-end.

**Comment by jasonbahl** [comment]
@Marco-Daniel are you still having this issue?

Do you have access to PHP error logs? I'm curious if there might be any server logs showing anything funky happening. 

I browsed the DIFF from WPGraphQL v1.0 -> 1.1.3 and these changes look like they _might_ have some affect: 

https://github.com/wp-graphql/wp-graphql/compare/v1.0...v1.1.3#diff-95fd90c4e82eb78455558373d51bfb443010152c93eb52b9ff9730cff2a80c96R505-R526

If you reverse these on v1.1.3, do the CORS issues go away for you? 

I'm not seeing anything else that seems like it would affect CORS. Possibly one of the plugins you're using is doing something, so it might be worth doing some tests on a stage environment with only WPGraphQL active, then activate the others one-by-one, or de-activate one-by-one.

**Comment by Marco-Daniel** [comment]
@jasonbahl When I click the link I get the message that there is nothing to compare. 

'We couldn’t figure out how to compare these references, do they point to valid commits?'

**Comment by jasonbahl** [comment]
@Marco-Daniel it looks like Github parser is causing the link to show up weird in the comment. Here's the link to the diff: `https://github.com/wp-graphql/wp-graphql/compare/v1.0...v1.1.3#diff-95fd90c4e82eb78455558373d51bfb443010152c93eb52b9ff9730cff2a80c96R505-R526`

**Comment by jasonbahl** [comment]
@Marco-Daniel that link doesn't seem to pull up the highlighted line numbers properly either. 

Here's the specific PR changes that seem like they _could_ be related to what you're experiencing, but they don't seem like they would: 

https://github.com/wp-graphql/wp-graphql/commit/5741ddb830210402e76016f094bfbce92e48a781#diff-95fd90c4e82eb78455558373d51bfb443010152c93eb52b9ff9730cff2a80c96R468

https://github.com/wp-graphql/wp-graphql/commit/cca088d69b2599a29ee1d442f40043fa07e89f47#diff-95fd90c4e82eb78455558373d51bfb443010152c93eb52b9ff9730cff2a80c96R491-R500

https://github.com/wp-graphql/wp-graphql/commit/8c8200ccf4bb44d703d1963eb669a33dfb5790f5#diff-95fd90c4e82eb78455558373d51bfb443010152c93eb52b9ff9730cff2a80c96R179-R193

**Comment by jasonbahl** [comment]
Basically, I would check the history of the Router.php file as that's where WPGraphQL sets headers, etc. 

If you're having CORS issues, and it started after a certain version, it's likely related to that file, or another plugin doing something with filters.

**Comment by jasonbahl** [comment]
@Marco-Daniel Wanted to follow-up here. Do you still believe there's a regression in WPGraphQL or is the issue related to one of the other plugins or some other local configuration you have?

**Comment by Marco-Daniel** [comment]
Sorry I didn't get back to you on this sooner, it slipped my attention. 

I did a little testing today and is seems that if I update above v1.0.5 this starts to happen. See the change in response headers after update. 

This are the response headers on v1.0.0
![wp-graphql-v1 0](https://user-images.githubusercontent.com/48966669/123255784-85628d00-d4f0-11eb-9f73-38c8f8c5300e.png)

And this is on v1.1.3
![wp-graphql-v1 1 3](https://user-images.githubusercontent.com/48966669/123255787-85fb2380-d4f0-11eb-8d7b-dc5e2722a316.png)

**Comment by chriszarate** [comment]
@Marco-Daniel It looks like you are also using wp-graphql-jwt-auth and wp-graphql-woocommerce, which filter the CORS headers for WPGraphQL. Have you also updated those plugins to their latest versions?

**Comment by Marco-Daniel** [comment]
@chriszarate I've tried with wp-graphql-woocommerce@v0.10.0 and wp-graphql-jwt-auth@v0.4.1. I think those are the latest.

After some diggin in my setup I did find something interesting. I'm using Gatsby as an frontend and when running v1.0.0 of wp-graphql, if I let my siteurl (in the wp general settings) point to my front-end (Gatsby) CORS works, but if I leave it pointing to the WP install (the default setting) CORS breaks. 
I'm not sure why as Access-Controll-Allow-Origin is set to * by default.

**Comment by chriszarate** [comment]
@Marco-Daniel We'll need some additional info to troubleshoot further. Could you copy the requests as cURL commands and paste both the request and response here?

> I'm not sure why as Access-Controll-Allow-Origin is set to * by default

The wildcard is basically to help avoid CORS issues out-of-the-box without needing any additional configuration.

**Comment by jasonbahl** [comment]
@Marco-Daniel thanks for the follow-up! Glad you got it resolved!
