### ISSUE TITLE
Namespace containing reserved keyword

### ISSUE THREAD

**Issue by gudmdharalds** [wp-graphql/wp-graphql#1702]
Hi!

I noticed today that `wp-graphql` uses the following namespace in a few places:

> namespace WPGraphQL\Type\Object;

The `object` keyword is [reserved](https://www.php.net/manual/en/reserved.other-reserved-words.php) in PHP 7.2 and later, and cannot be used in namespaces.

While this seems not to affect execution in most situations, it can, for example with this code:

```
use WPGraphQL\Type\Object;
```

as PHP will give a fatal error with this usage:

> Fatal error: Cannot use WPGraphQL\Type\Object as Object because 'Object' is a special class name in Standard input code on line 6

I tested this with PHP 7.4 and PHP 8.0. When `Object` is renamed to `Object2`, it works as expected.

The code in question is found in the `src/Type/Object` folder, for example:

* https://github.com/wp-graphql/wp-graphql/blob/develop/src/Type/Object/Avatar.php#L3
* https://github.com/wp-graphql/wp-graphql/blob/develop/src/Type/Object/Comment.php#L3

I wanted to flag this, as this could potentially become problematic in other contexts in the future. A suggested solution is to rename the namespace.

**Comment by jasonbahl** [comment]
@gudmdharalds thanks for opening the very detailed issue!  

We faced similar issue with the `Interface` keyword, and it's now `InterfaceType`. I agree that we should change this namespace to `ObjectType` or similar.
