### ISSUE TITLE
Pagination with startCursor and endCursor mixed up after a few rounds

### ISSUE THREAD

**Issue by andyvu92** [wp-graphql/wp-graphql#1714]
The issue happens on the pagination demo too: https://codesandbox.io/s/wpgraphql-apollo-forward-backward-pagination-example-spq53?from-embed

Here is a short video: https://www.loom.com/share/fbb7360a94944b11b27d0a0462c02142

When the page is first loaded
![original](https://user-images.githubusercontent.com/29296255/108202617-81ef7b80-7175-11eb-8a15-e30c198a4dfa.png)

After clicking first next
![First next](https://user-images.githubusercontent.com/29296255/108202707-a64b5800-7175-11eb-9c69-97af36df4514.png)

Then click first prev
![First prev](https://user-images.githubusercontent.com/29296255/108202787-c0853600-7175-11eb-826e-9b888063cd80.png)

After click next again
![Second Next](https://user-images.githubusercontent.com/29296255/108203735-0393d900-7177-11eb-9719-9751ad6b2d26.png)

Then click prev again
![Second prev](https://user-images.githubusercontent.com/29296255/108203795-17d7d600-7177-11eb-85d2-301e6b223003.png)

**Comment by andyvu92** [comment]
@jasonbahl @kidunot89 Could you pls look into this? I'm running a project building an e-commerce web application and it's close to the launch day. It would be much appreciated if you guys can look into this asap as I believe it will affect many others. Thanks.

**Comment by andyvu92** [comment]
I figured out the issue. When you use "before" and "last", the return arrays is reversed. So what I do is to reverse that array again and use the cursor coming from edges instead of pageInfo. Like this: 

`
{ after: currentProducts[currentProducts.length - 1].cursor, first: 9 }
{ before: currentProducts[0].cursor, last: 9 }
`

**Comment by ardiewen** [comment]
Unfortunately, this been reported on the following open issues already:

#1552 
#1440 
#1411 

My current workaround is to reverse the order (e.g. from ASC to DESC) when paginating backwards. It's definitely not how it should work according to relay spec, though.

If your use case is eCommerce, you may need to keep track of the sort order in state, as paginating backwards on a sorted list has the reverse implication:

e.g. What happens when...

1. User sorts by Price (high to low)
2. User paginates forwards
3. User changes sort to Price (low to high)
4. User paginates backwards

**Comment by jasonbahl** [comment]
@ardiewen @andyvu92 Please see #1773 which addresses this and includes tests with forward and backward pagination. 

see: https://github.com/wp-graphql/wp-graphql/pull/1773/files#diff-e9fc42ba1f4b498640f9c212a0f768596ae74b0509003e669f23d7886c7bbb31R113-R417

I'm going to close this issue as I believe #1773 resolves it, but if you believe you find that it's not fully working as expected after testing in your environments, please open a new issue and reference this one for context. 

Thanks for your patience on this one, and thanks @ardiewen for the gentle pressure to get this re-prioritized! 🙌

**Comment by mboynes** [comment]
See #2137
