### ISSUE TITLE
.env file may not be our friend in the repo

### ISSUE THREAD

**Issue by szepeviktor** [wp-graphql/wp-graphql#1724]
Please consider removing `.env` file and adding it to all ignore lists.

https://github.com/wp-graphql/wp-graphql/commits/develop/.env

**Comment by CodeProKid** [comment]
Looks like this was closed in version [1.2.4](https://github.com/wp-graphql/wp-graphql/releases/tag/v1.2.4).

**Comment by szepeviktor** [comment]
Yes.
Thank you.
