### ISSUE TITLE
How can I customize the sendPasswordResetEmail email template?

### ISSUE THREAD

**Issue by aresrioja10** [wp-graphql/wp-graphql#1727]
Currently, if I use the `sendPasswordResetEmail` mutation I receive a plain text email with the following content:

```
Someone has requested a password reset for the following account:

Site name: XXX

Username: XXX

If this was a mistake, just ignore this email and nothing will happen.

To reset your password, visit the following address:

```

Inspecting your code, I've found that the email content is set right here:

<img width="786" alt="Captura de pantalla 2021-02-19 a las 14 12 30" src="https://user-images.githubusercontent.com/3605582/108508968-e5d08c00-72bc-11eb-825e-9be881c2a247.png">

It is possible to change this template? In fact, I'm using Woocommerce and I would like to use the Woocommerce lost password template.

Thank you!

**Comment by therealgilles** [comment]
@aresrioja10: You can use the retrieve_password_message filter to customize the email as you like it.

Woocommerce uses the trigger function in woocommerce/includes/emails/class-wc-email-customer-reset-password.php to send the password retrieval email. You could try something like this (no guarantees though, I have not tried it myself):

```php
add_filter('retrieve_password_message', 'my_graphql_retrieve_password_message', 10, 4);
function my_graphql_retrieve_password_message( $msg, $key, $user_login, $user_data ) {
    // create class object
    $email_object = new WC_Email_Customer_Reset_Password();

    // set object parameters
    $email_object->setup_locale();
    $email_object->object = $user_data;
    $email_object->user_id = $user_data->ID;
    $email_object->user_login = $user_login;
    $email_object->reset_key = $key;
    $email_object->user_email = stripslashes( $user_data->user_email );
    $email_object->recipient  = $email_object->user_email;

    // get message content
    $content = $email_object->get_content();
    $email_object->restore_locale();

    // return message content
    return $content;
}
```

**Comment by aresrioja10** [comment]
@therealgilles It works! Thank you so much!

**Comment by aresrioja10** [comment]
@therealgilles  Oops, it works only if I use the lost password form from Wordpress. If I use the mutation sendPasswordResetEmail I get the following error:

`Class 'WC_Email_Customer_Reset_Password' not found`

Any idea?

**Comment by therealgilles** [comment]
The lost password form from Wordpress is controlled by WooCommerce, so it has nothing to do with the code above.
Did you try to run the mutation from the graphiql IDE inside Wordpress?

Either it's not quite the right way to access the class object or the class hasn't been loaded when the mutation runs. Need to figure out which one it is. If it does not work from the IDE, then it would be the former (which is probably an easy fix). If it does, then it would be the latter, which may be trickier to make work.

**Comment by therealgilles** [comment]
You could try to initialize WooCommerce as follows:

```php
...
function my_graphql_retrieve_password_message( $msg, $key, $user_login, $user_data ) {
    // init WooCommerce
    WC();

    // create class object
    $email_object = new WC_Email_Customer_Reset_Password();
```

**Comment by aresrioja10** [comment]
It doesn't work from the IDE either, it returns the same error.

Also, I've tried to initialize WooCommerce as you mentioned but it doesn't work either.

**Comment by aresrioja10** [comment]
Any updates on this?

**Comment by therealgilles** [comment]
I just tried it on my site and it worked when using the IDE in my case.

**Comment by therealgilles** [comment]
If you can add the function below to your functions.php:

```
function get_calling_function_name($index = 1, $args_length = 47) {
  $e = new Exception();
  $trace = $e->getTrace();
  // position 0 would be the line that called this function so we ignore it
  $last_call = '';
  for ($i=1; $i<=$index; $i++) {
    if (!isset($trace[$i]['function'])) continue;
    if ($i > 1)  $last_call .= "\n=> ";
    $last_call .= $trace[$i]['function'];
    $args = json_encode($trace[$i]['args']);
    if (strlen($args) > $args_length) $args = substr($args, 0, $args_length) . '...';
    $last_call .= '('.$args.')';
    $last_call .= ' / '.$trace[$i]['file'].', line '.$trace[$i]['line'];
  }
  return $last_call;
}
```

and then add the following to the above function:

```
function my_graphql_retrieve_password_message( $msg, $key, $user_login, $user_data ) {
    error_log( 'my_graphql_retrieve_password_message' );
    error_log( print_r( get_calling_function_name( 20 ), true ) );
```

to look at the stack trace to see why WC is not getting initialized in your case before the filter is executed.

**Comment by aresrioja10** [comment]
Hi @therealgilles ! 
Thanks for your response. If I add the following line it works:

```
// create class object
    $mailer = WC()->mailer(); <------
    $email_object = new WC_Email_Customer_Reset_Password();
```

Althought it sends the email without rendering the HTML:

<img width="806" alt="Captura de pantalla 2021-03-25 a las 20 04 46" src="https://user-images.githubusercontent.com/3605582/112529256-5c254a00-8da5-11eb-8d57-459a47f3d67e.png">

**Comment by therealgilles** [comment]
Can you compare it with an email that renders? (i.e. sent through the regular password reset form)
Maybe there is a header part that's missing in your case.

**Comment by aresrioja10** [comment]
It seems that Wordpress sends its emails with content-type = plain so you need to add this filter:

```
add_filter('wp_mail_content_type', function () {
    return "text/html";
});
```

Thank you so much for your help!

**Comment by therealgilles** [comment]
Awesome, glad you figured it out. There must be something on my site setting the email type to html.

**Comment by therealgilles** [comment]
Wondering if you checked the HTML checkbox under WooCommerce reset password email type.

**Comment by aresrioja10** [comment]
> Wondering if you checked the HTML checkbox under WooCommerce reset password email type.

Yes, it's already checked
