### ISSUE TITLE
WP-GraphQl stops end-point when adding WP-GraphQl options to Custom Post Types.

### ISSUE THREAD

**Issue by TimurGumarov** [wp-graphql/wp-graphql#173]
Hi! I'm trying connect custom post types with WP-GraphQl with this instruction:
https://edwincromley.gitbooks.io/wp-graphql/content/handling-custom-post-types.html

After this connection to end-point stops and GraphiQL Chrome plugin Crushes. Havin' a lot of errors of React and HTTP-500 from server.

Can you help me with this?

**Comment by BE-Webdesign** [comment]
Hi @TimurGumarov,

The link to that gitbook has nothing to do with this repo. That is a completely different plugin. I will take down that gitbook.

Not sure if @jasonbahl has new docs up. At some point soonish I hope to have some free time to be able to write documentation for the new WP GraphQL.

**Comment by jasonbahl** [comment]
@TimurGumarov Thanks for your interest in the plugin! 

Until we have more time to get some official docs together (hopefully soon, and help appreciated 😉 ), this snippet should help: 

Let's say you have a `foo` post_type registered. You can add it to your GraphQL schema like so:

```
add_action( 'do_graphql_request', function() {

	global $wp_post_types;

	if ( isset( $wp_post_types['foo'] ) ) {
		$wp_post_types['foo']->show_in_graphql     = true;
		$wp_post_types['foo']->graphql_single_name = 'foo';
		$wp_post_types['foo']->graphql_plural_name = 'foos';
	}

} );
```

This will allow you to query it like you can query `posts`, so something like: 

```
{
  foos{
    edges{
      node{
        id
        title
        slug
      }
    }
  }
}
```

Now, let's say your `foo` post type had a `color` field on it that you wanted to be part of the schema. You could add that like so:  

```
add_filter( 'graphql_foo_fields', 'your_callback_function' );

function your_callback_function( $fields ) {

    $fields['color'] = [
        'type' => WPGraphQL\Types::string(),
        'description' => __( 'The color of the post', 'my-graphql-extension-namespace' ),
        'resolve' => function( \WP_Post $foo, array $args, $context, $info ) {
            $color = get_post_meta( $foo->ID, 'color', true );
            return ( ! empty( $color ) && is_string( $color ) ) ? $color : null;
        },
    ];

    return $fields;

}
```

Then you can query for that field on the `foo` type in your schema, like so: 

```
{
  foos{
    edges{
      node{
        id
        color
      }
    }
  }
}
```

There's also more info about extending the schema in the comments on these issues: 
https://github.com/wp-graphql/wp-graphql/issues/118
https://github.com/wp-graphql/wp-graphql/issues/11

**Comment by TimurGumarov** [comment]
@jasonbahl and @BE-Webdesign  Thank you for response!

**Comment by TimurGumarov** [comment]
@jasonbahl Tryed your code. Recieved thus in GraphiQL:
«SyntaxError: Unexpected token < in JSON at position 0»

**Comment by jasonbahl** [comment]
@a-barbieri I updated my comment above to reflect your suggested change as well. Thanks!
