### ISSUE TITLE
documentation about using docker with xdebug is out of date

### ISSUE THREAD

**Issue by rburgst** [wp-graphql/wp-graphql#1737]
The page 
https://github.com/wp-graphql/wp-graphql/blob/master/documentation/UsingDocker.md

references files which are no longer in the repository such as : `run-docker-local-app-xdebug.sh`.

Therefore, its no longer clear how to debug wp-graphql. It would be nice to update the documentation so that people can debug wp-graphql using docker.

**Comment by markkelnar** [comment]
I wonder if these links can be replaced by links to according pages at wpgraphql.com/docs and fill in anything that's missing.
