### ISSUE TITLE
RESOLVED: v1.2.0 -> v1.2.3 Cause installation errors from WordPress.org as the vendor directory wasn't deployed from Github properly

### ISSUE THREAD

**Issue by therealgilles** [wp-graphql/wp-graphql#1743]
Installing v1.2.1 through wordpress.org results in the following error:

```
WPGraphQL has been installed without dependencies. Try installing from WordPress.org or run "composer install" from the plugin directory to install dependencies
```

and breaking WP in the process.

**Comment by jasonbahl** [comment]
@therealgilles thanks! On it. I screwed up something with the new deploy to WordPress.org build script. Working on the fix right now.

**Comment by adithwip** [comment]
How do you get your WordPress running again? @therealgilles 

After I installing the latest release, my WP admin just showing that error message.
How to "undo" it?

**Comment by jasonbahl** [comment]
So sorry for this silly mistake. I had updated some deploy scripts that deploy the plugin from Github to WordPress.org SVN repo upon release, and the vendor directory was being ignored and excluded from deploys. 

I've got this fixed and you can install from WordPress.org now. 

@adithwip, re:

> After I installing the latest release, my WP admin just showing an error message.

You should be able to visit your site at `/plugins.php` and I believe it should let you de-activate wp-graphql and re-install. If it's not letting you, you might need to remove the plugin from the file-system and re-install v1.2.4 (which includes the vendor directory)

**Comment by adithwip** [comment]
No need to apologize after all you've done with this great library 😆
And thank you for responding to my comment.

I was able to fix my WP with the clues you gave.

Here is how I fix it:
- Activate my SFTP Credentials. See [here](https://wordpress.com/support/sftp/#before-beginning)
- Installing FileZilla in macOS and [configure it](https://www.tcd.ie/itservices/internet/kb/filezilla.php#:~:text=Using%20FileZilla&text=To%20add%20a%20new%20site,you%20wish%20to%20connect%20to.).
- Access my WP File System via FileZilla. And go to `/htdocs/wp-content/plugins` for seeing list of installed plugins.
- Deleting my wp-graphql plugins (it can take minutes).
- And then reinstalling v1.2.4 release of wp graphql

In case anyone needs comprehensive steps 🙂

**Comment by therealgilles** [comment]
If you have ssh access, you can follow the instructions, i.e. ssh into your server, navigate to the wp-content/plugins/wp-graphql directory, and run 'composer install' (provided your server has composer).

**Comment by therealgilles** [comment]
Quick pieces of advice when it comes to WP updates and plugin updates:

1) Don't rush to apply them, and especially if they are major releases (unless you've been waiting for a specific update and are using a staging site).
2) If you have ssh access, put your install under git control. Then you can revert updates in one command line.
3) Backup your database.
4) Backup your WP install.
5) Backup your server.

PS: Wordpress allows to download and install previous releases of a plugin but they are really hard to find. I never understood why it's not available through the WP backend UI.

**Comment by CodeProKid** [comment]
If you need to go back in versions instead of forward to 1.2.4 to pick up the fix and have access to SSH on your site with WP-CLI installed, you can run: `wp plugin install wp-graphql --version="1.1.8" --force` to revert back to the last good version.

**Comment by jasonbahl** [comment]
Closing as this has been resolved and no further reports have come in since resolution.
