### ISSUE TITLE
Documentation needs to show WP Permalink set up more clearly as a prerequisite.

### ISSUE THREAD

**Issue by sgnilreutr** [wp-graphql/wp-graphql#1754]
# The page /graphql after installing the WP plugin for graphQL can show a 404 page

The issue arises when installing WP (clean/latest version) and the plugin, followed by simply activating it.
The WP Permalink configuration needs to be altered, to any option besides 'simple'.
There is documentation on this; https://www.wpgraphql.com/docs/wpgraphql-request-lifecycle/#graphql-endpoint - but there is:
1. No indicative error, when visiting the /graphql page on your WP installation, as to why this problem is there - only 404 is too broad.
2. There is no indication of the permalink set up as being a prerequisite for the page /graphql to load.

## Suggestions:
1. Update the error logs, if possible.
2. Update the documentation to put the setting under more attention.

**Comment by stevenabadie** [comment]
Came here to make a similar ticket. I wonder if this would be best to add as an alert on the [Quick Start](https://www.wpgraphql.com/docs/quick-start/) or [Intro to Wordpress](https://www.wpgraphql.com/docs/intro-to-wordpress/) page.

**Comment by sgnilreutr** [comment]
Good question, I would write it out in the intro and provide a link on the QuickStart, since the alteration of the config didn’t seem to be needed on every clean WP install.

**Comment by markkelnar** [comment]
Would this cover the setup instructions for permalinks?

On https://www.wpgraphql.com/docs/quick-start/#install-from-your-wordpress-dashboard, instructions about selecting permalink structure.
![Screen Shot 2021-03-02 at 3 06 52 PM](https://user-images.githubusercontent.com/749603/109715810-b3027f80-7b69-11eb-8c0f-9113f66e5b06.png)

And under interacting with WPGraphql https://www.wpgraphql.com/docs/interacting-with-wpgraphql/#http-post-requests, mentioning both endpoints and the permalink settings
![Screen Shot 2021-03-02 at 3 11 25 PM](https://user-images.githubusercontent.com/749603/109715957-db8a7980-7b69-11eb-8137-f78a6e7d5dd4.png)

**Comment by markkelnar** [comment]
I didn't add details about what to do when encountering the 404. If remains a common issue for people, we can address that in FAQs or some error logging.
