### ISSUE TITLE
How can we add data to custom fields while creating a post using mutation in wp-graphql?

### ISSUE THREAD

**Issue by JayakrishnanJK** [wp-graphql/wp-graphql#176]
Can you please help on this @jasonbahl ?

**Comment by jasonbahl** [comment]
@JayakrishnanJK Adding custom fields to mutations takes a few parts: 

- Add the Input to the mutation
- Do something with the input

Let's look at an example.

Let's say you had a postmeta field `color` that stored a string. 

You could add that to the `post` mutation like so: 

```
add_filter( 'graphql_post_object_mutation_input_fields', 'your_prefix_add_fields_to_post_object_mutation', 10, 2 );

function your_prefix_add_fields_to_post_object_mutation( $fields, $post_type_object ) {
   if ( 'post' === $post_type_object->name ) {
      $fields['color'] = [
           'type' => Types::string(),
           'description' => __( 'Description of your field here', 'your-text-domain' ),
       ]
   } 
}
```

This will now add a field to the input for the mutation for posts. . .but the input won't actually do anything yet. We have to tell WPGraphQL what to do with that input. . .in this case, we want to save it to postmeta.

So we can hook in like so: 

```
add_action( 'graphql_post_object_mutation_update_additional_data', ' your_prefix_save_post_object_mutation_fields', 10, 4 );

function( $post_id, $input, $post_type_object, $mutation_name ) {
    // If you need to do any validation, like make sure the input is a valid hex, 
    // or something to that tune, do it here.
    if ( ! empty( $input['color'] ) ) {
        update_post_meta( $post_id, '$input['color']', $input['color'] );
    } 
}
```

**Comment by jasonbahl** [comment]
@JayakrishnanJK keep in mind though, that we are still in a pretty early version of the plugin, so some of these hook and filter names _could_ potentially be changed at some point between now and a stable 1.0 release. . .so just make sure to keep an eye on release details, etc, and I'd suggest adding unit tests for your own code so that _if_ something does cause a breaking change in a future version you know right away

**Comment by jasonbahl** [comment]
@JayakrishnanJK additionally, you could add a mutation as a rootMutation as well. . .

For example, if you wanted a mutation like: 

```
mutation( id:ID!, color:String! ) {
    setPostColor( id: $postId, color: $color ) {
       post {
           id
           color
       }
    }
}
```

It's kind of up to you how you want your application data graph to be shaped, so just throwing this out as another option. . .you can look at how the other rootMutations are built in the source code for how to implement something similar on your own 😉

**Comment by towfiqi** [comment]
@jasonbahl adding this code, breaks the graphql server:
```
add_filter( 'graphql_post_object_mutation_input_fields', 'your_prefix_add_fields_to_post_object_mutation', 10, 2 );

function your_prefix_add_fields_to_post_object_mutation( $fields, $post_type_object ) {
   if ( 'post' === $post_type_object->name ) {
      $fields['color'] = [
           'type' => \WPGraphQL\Types::string(),
           'description' => __( 'Description of your field here', 'your-text-domain' ),
       ]
   } 
}
```

And I get this PHP error:

`[08-Dec-2017 08:47:47 UTC] PHP Warning:  array_merge(): Argument #2 is not an array in C:\xampp2\htdocs\wpd\wp-content\plugins\wp-graphql-develop\src\Type\PostObject\Mutation\PostObjectUpdate.php on line 172`

**Comment by nikosolihin** [comment]
@towfiqi You forgot the `return` statement.
