### ISSUE TITLE
menuitem childItems does not properly respect wp_term_relationships

### ISSUE THREAD

**Issue by rburgst** [wp-graphql/wp-graphql#1768]
The logic on how to determine child menu items is different from the wordpress logic which can result in invalid child menu items being returned (especially in case you have an older wp instance which has been upgraded and might include no longer visible menu items).

This is the query that gets executed when wordpress looks up child menu items (in this case menu 117): 
```sql
SELECT tr.object_id
FROM wp_term_relationships AS tr
         INNER JOIN wp_term_taxonomy AS tt ON tr.term_taxonomy_id = tt.term_taxonomy_id
WHERE tt.taxonomy IN ('nav_menu')
  AND tt.term_id IN ('117')
ORDER BY tr.object_id ASC;
```

see also https://developer.wordpress.org/reference/functions/wp_get_nav_menu_items/

However, for a query such as this

```graphql
query MyQuery {
  menu(id: 117, idType: DATABASE_ID) {
    menuItems {
      nodes {
        label
        title
        parentId
        url
        parentDatabaseId
        databaseId
        childItems {
          nodes {
            url
            title
            parentDatabaseId
            databaseId
          }
        }
      }
    }
  }
}
```
the following query gets executed in order to find childItems for a specific menu item: 

```sql
SELECT wp_posts.ID
FROM wp_posts
         INNER JOIN wp_postmeta ON (wp_posts.ID = wp_postmeta.post_id)
WHERE 1 = 1
  AND (
    (wp_postmeta.meta_key = '_menu_item_menu_item_parent' AND wp_postmeta.meta_value = '30842')
    )
  AND wp_posts.post_type = 'nav_menu_item'
  AND ((wp_posts.post_status = 'publish'))
GROUP BY wp_posts.ID
ORDER BY wp_posts.menu_order ASC, wp_posts.ID DESC
LIMIT 0, 11
```

This is invoked here: https://github.com/wp-graphql/wp-graphql/blob/develop/src/Connection/MenuItems.php#L42

IMHO the code should also respect `wp_term_relationships` as the original WP source does.

I tried to produce this problem with a fresh database and I didnt manage it (yet). I am guessing the db inconsistency was introduced by upgrading the WP version some time in the last 2 years.

**Comment by jasonbahl** [comment]
@rburgst the first query is to get the Menu (a term) with ID 117:

```php
SELECT tr.object_id
FROM wp_term_relationships AS tr
         INNER JOIN wp_term_taxonomy AS tt ON tr.term_taxonomy_id = tt.term_taxonomy_id
WHERE tt.taxonomy IN ('nav_menu')
  AND tt.term_id IN ('117')
ORDER BY tr.object_id ASC;
```

The 2nd query you pasted is to get Menu Items (a post_type) that are children of a specific Menu Item (also another post of the nav_menu_item post_type)

 ```php
 SELECT wp_posts.ID
FROM wp_posts
         INNER JOIN wp_postmeta ON (wp_posts.ID = wp_postmeta.post_id)
WHERE 1 = 1
  AND (
    (wp_postmeta.meta_key = '_menu_item_menu_item_parent' AND wp_postmeta.meta_value = '30842')
    )
  AND wp_posts.post_type = 'nav_menu_item'
  AND ((wp_posts.post_status = 'publish'))
GROUP BY wp_posts.ID
ORDER BY wp_posts.menu_order ASC, wp_posts.ID DESC
LIMIT 0, 11
 ```
 
 My guess, though, is that there's possibly some orphaned menu items. Somehow your database has some menu items set to have a parent menu item, but _not_ set to exist in the same menu. 
 
So the latter query for child menu items could probably benefit _also_ from a tax query. 

So, instead of looking up child items, it would look up child items that are _also_ connected to the same Menu (term). 

Does that sound like it would solve the problems you've had?

**Comment by rburgst** [comment]
> My guess, though, is that there's possibly some orphaned menu items. Somehow your database has some menu items set to have a parent menu item, but _not_ set to exist in the same menu.

This is exactly the problem.

> So the latter query for child menu items could probably benefit also from a tax query.

Yes, that was my proposal.

> Does that sound like it would solve the problems you've had?

I definitely think so. 

However, I do know that the DB should be cleaned from those orphaned items. I just think that it would be good if wp-graphql used the same strategy as wordpress itself when it comes to menu handling.

**Comment by jasonbahl** [comment]
Ok, I have a PR coming that adds a tax query to the connection so if there are child menu items of a menu item, but are not associated with the same menu as the parent, they'll be ignored.

**Comment by jasonbahl** [comment]
@rburgst Check out #1775
