### ISSUE TITLE
The latest plugin is not working in new WP site created.

### ISSUE THREAD

**Issue by JayakrishnanJK** [wp-graphql/wp-graphql#177]
A new site with default Wp theme and no additional plugins added. It returns an error in wp-graphql endpoint "SyntaxError: Unexpected token < in JSON at position 0" . Please help @jasonbahl .

Thank you @jasonbahl  for quick responses for other questions regarding mutation.

**Comment by jasonbahl** [comment]
If you're on a new site, did you flush your permalinks?

**Comment by jasonbahl** [comment]
@JayakrishnanJK can you confirm that flushing permalinks fixes the issue? 

If that didn't fix it, can you try using the GraphiQL app here: https://github.com/skevy/graphiql-app

Then in the app, open Chrome Dev Tools on it (command+option+i), and go to the network tab, then refresh the app and tell me what output you see the "response" tab of the request?

![screen shot 2017-07-26 at 3 49 43 pm](https://user-images.githubusercontent.com/1260765/28645283-2f5c7ee4-721a-11e7-8a81-126a4476ca0b.png)

**Comment by JayakrishnanJK** [comment]
tried after changing the permalink settings to  postname and still not working.

we have tested with Graphiql app and getting response as 
"[{message: "Syntax Error GraphQL request (28:1) Unexpected <EOF>??27: ?28: ? ^?",…}]"


![error](https://user-images.githubusercontent.com/13433842/28653663-76070412-72ac-11e7-8339-6bba11979b92.png)

**Comment by jasonbahl** [comment]
Can you make sure the method is set to POST instead of GET? Graphiql doesn't sent GET requests properly encoded

**Comment by JayakrishnanJK** [comment]
@jasonbahl its in POST request only. still getting same error

"{errors: [{message: "Syntax Error GraphQL request (28:1) Unexpected <EOF>↵↵27: ↵28: ↵ ^↵",…}]}"

**Comment by JayakrishnanJK** [comment]
@jasonbahl  
Now in the newly installed GraphiQl App its working fine. But we are not able write queries on chrome extension of GraphiQl . ie "ChromeiQL" . May be its an chrome extension issue.

Thanks for your valuable time and support.

**Comment by cr101** [comment]
After I installed and started up the GraphiQL app I got the same error message. 
Flushing the permalinks (i.e Step 1: In the main menu find "Settings > Permalinks", Step 2: Scroll down if needed and click "Save Changes".) fixed the issue.

**Comment by jasonbahl** [comment]
Also note that permalinks must be a custom permalink structure, not the default that WP comes with out of the box.
