### ISSUE TITLE
Missing terms field in custom post types

### ISSUE THREAD

**Issue by toriphes** [wp-graphql/wp-graphql#1771]
Hello everybody,

I created two custom post types `cpt1` and` cpt2` and assigned a custom taxonomy to `cpt2`.
I noticed that there is no `term` field in `cpt2` so I went to look at the wp-graphql code and found something strange at the line 180 in:
https://github.com/wp-graphql/wp-graphql/blob/develop/src/Connection/TermObjects.php#L180

There is a `return` statement but I think it should be replaced with a `continue` statement otherwise in some cases the field `term` will not be registered for all subsequent post types.

Is this a mistake or intentional? Can I open a pull request?

Thanks for the great job you're doing with wp-graphql 👍

**Comment by jasonbahl** [comment]
@toriphes this might indeed be a bug. 👀 

Let me see if I can replicate.

**Comment by jasonbahl** [comment]
@toriphes I've confirmed. A continue should fix this. 😄

**Comment by jasonbahl** [comment]
Fwiw, replicated with this code: 

```php
add_action( 'init', function() {

	register_post_type( 'cpt_one', [
		'show_in_graphql' => true,
		'graphql_single_name' => 'CptOne',
		'graphql_plural_name' => 'CptOnes',
	] );

	register_post_type( 'cpt_two', [
		'show_in_graphql' => true,
		'graphql_single_name' => 'CptTwo',
		'graphql_plural_name' => 'CptTwos',
	] );

	register_taxonomy( 'tax_one', 'cpt_two', [
		'show_in_graphql' => true,
		'graphql_single_name' => 'taxOne',
		'graphql_plural_name' => 'taxOnes',
	] );
} );
```

@toriphes please do open a PR! 🙌
