### ISSUE TITLE
Filter Plugins by Status

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#178]
It would be nice to be able to filter plugins by status, like the wp-admin plugins.php does. 

Stati that can be filtered: `active`, `recently active`, `inactive`, `must-use`, `drop-ins`

**Comment by CodeProKid** [comment]
Moving this into 1.0, since the query already exists in the plugin. Would be good to add this functionality before the 1.0 release. I also think it would be a good first issue for an outside contributor to pickup. We can always punt it later if no one picks it up though.

**Comment by jasonbahl** [comment]
closed by #2298
