### ISSUE TITLE
Every mediaItem raises an Internal Server Error

### ISSUE THREAD

**Issue by Kallirroi** [wp-graphql/wp-graphql#1783]
While fetching `MediaItem` nodes, the following error shows up during development as well as build. I have recently upgraded to Gatsby 3.0, but this error is not new. I first encountered it in January and posted here: https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/449 where the verdict was that it's not a `gatsby-source-wordpress` problem, but a `wp-graphql` one, hence why I'm posting here.

 
```
 ERROR

 gatsby-source-wordpress  Error category: undefined

Error:
  Internal server error

 Debug message:
  Call to a member function then() on null

 Error path: mediaItem__index_7
```

**`gatsby info` output:**
```
  System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.4 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.5.2 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.82
    Firefox: 85.0.2
  npmPackages:
    gatsby: ^3.0.4 => 3.0.4
    gatsby-cli: ^3.0.0 => 3.0.0
    gatsby-image: ^3.0.0 => 3.0.0
    gatsby-plugin-breakpoints: ^1.2.2 => 1.3.3
    gatsby-plugin-manifest: ^3.0.0 => 3.0.0
    gatsby-plugin-modal-routing: ^1.2.0 => 1.2.0
    gatsby-plugin-netlify: ^3.0.0 => 3.0.1
    gatsby-plugin-netlify-cache: ^1.2.0 => 1.2.0
    gatsby-plugin-netlify-redirect: ^1.0.0 => 1.0.0
    gatsby-plugin-offline: ^4.0.0 => 4.0.0
    gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0
    gatsby-plugin-sharp: ^3.0.1 => 3.0.1
    gatsby-recipes: ^0.2.16 => 0.2.38
    gatsby-remark-social-cards: ^0.4.1 => 0.4.1
    gatsby-source-filesystem: ^3.0.0 => 3.0.0
    gatsby-source-wordpress: ^5.0.0 => 5.0.0
    gatsby-transformer-remark: ^3.0.0 => 3.0.0
    gatsby-transformer-sharp: ^3.0.0 => 3.0.0
  npmGlobalPackages:
    gatsby-cli: 3.0.0
```

**What I have done to get this to build**
Setting `panicOnError: false` and `allow404images: true` has helped with the build not failing. Both dev and build do succeed, eventually.  In addition, setting 
```
            showQueryOnError: true,
            writeQueriesToDisk: true,
            showQueryVarsOnError: true,
```
produces following output. Notice that [https://icd.wordsinspace.net/wp-content/uploads/2020/10/955000_2-scaled.jpg](https://icd.wordsinspace.net/wp-content/uploads/2020/10/955000_2-scaled.jpg) does NOT exist on Wordpress image Library.

```
info  gatsby-source-wordpress  GraphQL vars: {"first":100,"after":null}

 ERROR

 gatsby-source-wordpress  GraphQL query: query MEDIA_ITEMS {
  mediaItem__index_0: mediaItem(
    id: "https://icd.wordsinspace.net/wp-content/uploads/2020/10/955000_2.jpg"
    idType: SOURCE_URL
  ) {
    ...MediaItemFragment
  }

  mediaItem__index_1: mediaItem(
    id: "https://icd.wordsinspace.net/wp-content/uploads/2020/10/955000_2-scaled.jpg"
    idType: SOURCE_URL
  ) {
    ...MediaItemFragment
  }
}

fragment MediaItemFragment on MediaItem {
  altText

  ancestors(first: 100) {
    nodes {
      id
      __typename
    }
  }

  author {
    node {
      id
    }
  }

  authorDatabaseId
  authorId
  caption

  wpChildren: children(first: 100) {
    nodes {
      id
      __typename
    }
  }

  commentCount
  commentStatus

  comments(first: 100) {
    nodes {
      id
    }
  }

  contentType {
    node {
      id
    }
  }

  databaseId
  date
  dateGmt
  description
  desiredSlug
  enclosure
  fileSize
  guid
  id

  lastEditedBy {
    node {
      id
    }
  }

  link

  mediaDetails {
    file
    height

    meta {
      aperture
      camera
      caption
      copyright
      createdTimestamp
      credit
      focalLength
      iso
      keywords
      orientation
      shutterSpeed
      title
    }

    sizes {
      file
      fileSize
      height
      mimeType
      name
      sourceUrl
      width
    }

    width
  }

  mediaItemUrl
  mediaType
  mimeType
  modified
  modifiedGmt

  wpParent: parent {
    node {
      id
      __typename
    }
  }

  parentDatabaseId
  parentId
  sizes
  slug
  sourceUrl
  srcSet
  status

  template {
    templateName

    __typename
  }

  title
  uri
  __typename
}
```

**Comment by jasonbahl** [comment]
@Kallirroi I've confirmed that this is an issue. If an external (non WordPress) uri is passed in, this does indeed return an error. 

WPGraphQL should return a null, not an error. 

I also believe the Gatsby Source WordPress plugin should update to not ask WordPress for images if the images are not hosted by WordPress. 

I messaged @TylerBarnes to get his thoughts as well, but I think there needs to be an issue opened on the Gatsby Source Plugin if it's not already a known issue.

**Comment by Kallirroi** [comment]
> @Kallirroi I've confirmed that this is an issue. If an external (non WordPress) uri is passed in, this does indeed return an error.
> 
> WPGraphQL should return a null, not an error.
> 
> I also believe the Gatsby Source WordPress plugin should update to not ask WordPress for images if the images are not hosted by WordPress.
> 
> I messaged @TylerBarnes to get his thoughts as well, but I think there needs to be an issue opened on the Gatsby Source Plugin if it's not already a known issue.

That explains it - thanks so much for looking into it @jasonbahl 👍

**Comment by TylerBarnes** [comment]
If this is fixed in WPGQL it will work as-is for the source plugin.

The source plugin tries to guess the correct url for an image when it finds one in html fields.
`https://icd.wordsinspace.net/wp-content/uploads/2020/10/955000_2.jpg` is the right url but before querying we don't know that so the query also includes a request for `https://icd.wordsinspace.net/wp-content/uploads/2020/10/955000_2-scaled.jpg`. The first link works, the second doesn't and the source plugin will just use the one that worked.

**Comment by Kallirroi** [comment]
> If this is fixed in WPGQL it will work as-is for the source plugin.
> 
> The source plugin tries to guess the correct url for an image when it finds one in html fields.
> `https://icd.wordsinspace.net/wp-content/uploads/2020/10/955000_2.jpg` is the right url but before querying we don't know that so the query also includes a request for `https://icd.wordsinspace.net/wp-content/uploads/2020/10/955000_2-scaled.jpg`. The first link works, the second doesn't and the source plugin will just use the one that worked.

That explains all the `scaled` calls I saw failing while trying to debug...thanks @TylerBarnes! Is there a way I could have known this detail via documentation? Searching between (the now two) repos has me wondering if I am missing out on useful info 😄

**Comment by TylerBarnes** [comment]
No, this internal logic that you shouldn't need to know - there are a bunch of other things like this in that part of the code (can't remember them off the top of my head). Once this doesn't throw errors it should just work 👍
