### ISSUE TITLE
Querying for Commenter.databaseId throws errors

### ISSUE THREAD

**Issue by TylerBarnes** [wp-graphql/wp-graphql#1799]
This query fails:
```graphql
query NODE_LIST_QUERY($first: Int!, $after: String) {
  comments(first: $first, after: $after) {
    nodes {
      author {
        node {
          databaseId
        }
      }
    }
  }
}
```

But this query succeeds:
```graphql
query NODE_LIST_QUERY($first: Int!, $after: String) {
  comments(first: $first, after: $after) {
    nodes {
      author {
        node {
          id
        }
      }
    }
  }
}
```

As a result of the failing field `Comment.author.node` returns null in the above query even though data exists. This is problematic for `gatsby-source-wordpress` as it means the comment author can't be fetched programatically for authors that are Commenter nodes instead of User nodes.

See https://github.com/gatsbyjs/gatsby/issues/30311

**Comment by TylerBarnes** [comment]
I guess Commenter.databaseId shouldn't be part of the interface 🤔 so that it can only be queried like:

```graphql
query NODE_LIST_QUERY($first: Int!, $after: String) {
  comments(first: $first, after: $after) {
    nodes {
      author {
        node {
          ... on User { databaseId }
        }
      }
    }
  }
}
```

**Comment by jasonbahl** [comment]
@TylerBarnes the issue is that the databaseId is a non-null field, but the CommentAuthor Model was missing the field.

This PR (https://github.com/wp-graphql/wp-graphql/pull/1806) fixes it.

**Comment by TylerBarnes** [comment]
Dope, thanks @jasonbahl !!
