### ISSUE TITLE
Support for Rank Math SEO ?

### ISSUE THREAD

**Issue by tsrCodes** [wp-graphql/wp-graphql#1803]
Can We expect a plugin for Rank Math SEO ??? : (

**Comment by jasonbahl** [comment]
@tsrCodes I would recommend reaching out to Rank Math and see if they'd be interested in providing WPGraphQL integration for the data managed in their plugin. 

We don't have any plans of providing a plugin, but would be happy to work with them to bring GraphQL support to the data in their plugin!

**Comment by justlevine** [comment]
Development on a rank math extension is happening here: https://github.com/axewp/wp-graphql-rank-math
