### ISSUE TITLE
WP Graphql Polylang throws error after update

### ISSUE THREAD

**Issue by adel0559** [wp-graphql/wp-graphql#1807]
Hi! After updating wp-graphql to v1.3.2 I am getting a crash in wp-graphql-polylang:

```
PHP Fatal error:  Uncaught Error: Call to undefined function WPGraphQL\Extensions\Polylang\is_graphql_http_request() in /var/www/html/wp-content/plugins/wp-graphql-polylang/src/Loader.php:145
/var/www/html/wp-content/plugins/wp-graphql-polylang/src/Loader.php(79): WPGraphQL\Extensions\Polylang\Loader->is_graphql_request()
/var/www/html/wp-includes/class-wp-hook.php(292): WPGraphQL\Extensions\Polylang\Loader->__filter_pll_model('PLL_Model')
/var/www/html/wp-includes/plugin.php(212): WP_Hook->apply_filters('PLL_Model', Array)
/var/www/html/wp-content/plugins/polylang-pro/vendor/wpsyntex/polylang/include/class-polylang.php(190): apply_filters('pll_model', 'PLL_Model')
/var/www/html/wp-includes/class-wp-hook.php(292): Polylang->init('')
/var/www/html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array)
/var/www/html/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
/var/www/html/wp-settings.php(423): do_action('plugins_loaded')
phar:///usr/local/bin/wp/vendor/wp-cli/w in /var/www/html/wp-content/plugins/wp-graphql-polylang/src/Loader.php on line 145
```

Looks like a function that wp-graphql-polylang depends on has been removed.

Plugins:
wp-graphql - v.1.3.2
wp-graphql-polylang - v.0.5.0
Polylang Pro - v.2.8.4

**Comment by jasonbahl** [comment]
@adel0559 what version of WPGraphQL last worked for you?

**Comment by jasonbahl** [comment]
@adel0559 I just pulled down v0.5.0 of WPGraphQL for Polylang with WPGraphQL v1.3.2 and I'm not getting this error. 

The error actually makes it seem like this function was deleted from your install of wp-graphql-polylang: https://github.com/valu-digital/wp-graphql-polylang/blob/master/src/Loader.php#L130-L146

Did you remove that function for any reason? Maybe try re-installing WPGraphQL for Polylang?

**Comment by adel0559** [comment]
I just tried reinstalling both plugins in my docker container and now it works so it seems like there is some issue with how I'm installing these plugins. Feel free to close this issue, and thank you for the quick response!

**Comment by jasonbahl** [comment]
Thanks for the follow-up @adel0559! Closing this issue.
