### ISSUE TITLE
Empty excerpts produce "SyntaxError: Unexpected token < in JSON at position 0"

### ISSUE THREAD

**Issue by e10jc** [wp-graphql/wp-graphql#182]
This query
```
{
  posts  {
    edges {
      node {
        id
        excerpt
      }
    }
  }
}
```
produces a `SyntaxError: Unexpected token < in JSON at position 0` error for posts that don't have an excerpt. The error goes away if I manually enter an excerpt.

**Comment by jasonbahl** [comment]
I'll check this out. Thanks for reporting!

**Comment by jasonbahl** [comment]
@e10jc I'm not getting any issues with posts that have excerpts or posts that have no excerpt.

Can you use this GraphiQL app: https://github.com/skevy/graphiql-app

Then make sure the request type is set to POST, open dev tools (command+option+i) and go to the network tab and click on the request and see what's showing in the response after you run the query. (GIF below showing how to debug the request with the dev tools)

![graphiql-dev-tools-debugging](https://user-images.githubusercontent.com/1260765/28679008-21e09b52-72af-11e7-8efb-ba8814307bf6.gif)


You might consider trying the query with the twenty-seventeen theme active and no other plugins, just to make sure another plugin isn't doing something it shouldn't be doing.

**Comment by jasonbahl** [comment]
@e10jc what ended up being the issue?

**Comment by e10jc** [comment]
It had to do with WP_DEBUG being set to true, which produced messages like this:

```<b>Notice</b>:  Trying to get property of non-object in <b>/var/www/html/wp-includes/post-template.php</b> on line <b>298</b><br />```

I'm not sure what the fix is yet, but disabling WP_DEBUG is just fine for me now.

**Comment by e10jc** [comment]
I'm still getting `null` excerpts by the way. My assumption is the `excerpt` field would return a shortened version of `content`, like the Wordpress default behavior.

If anyone is looking for that, here's my quick solution:

```
add_action( 'graphql_init', function () {
  add_filter( 'get_the_excerpt', function ( $excerpt, $post ) {
    return !empty( $excerpt ) ? $excerpt : wp_trim_words( $post->post_content );
  }, 10, 2 );
} );
```

**Comment by mdstevens044** [comment]
Also getting null excerpts when there is one.

**Comment by jasonbahl** [comment]
@e10jc I think the excerpt field does need some fine-tuning to be able to get the expected output. . .either the manually entered excerpt _or_ a trimmed version of the `post_content`, so we'll definitely discuss how it should evolve and what it should support. 

I wanted to point out that your filter as implemented will actually filter the excerpt in all contexts (such as your theme), not just GraphQL requests.

The `graphql_init` action fires once the plugin is loaded, but not necessarily on GraphQL requests.

The hook you probably want, if you want your filter to apply _only_ to GraphQL requests, would be `do_graphql_request` or you could use your existing code, and just wrap your filter with `if ( defined( 'GRAPHQL_REQUEST' ) && GRAPHQL_REQUEST )`

**Comment by jasonbahl** [comment]
@mdstevens044 I'm not seeing `null` excerpts for posts that actually do have an excerpt filled out, so that's a curious issue. Have you tested in an environment with just WPGraphQL and a _twenty-something_ theme installed to make sure no other plugins or theme filters are causing unexpected behavior with your excerpts?

**Comment by jasonbahl** [comment]
@mdstevens044 if it is a legit issue, let's create a new issue to track that in as this one is closed, and it's original reporting is a different issue.
