### ISSUE TITLE
No schema showing instead shows `fetch@[native code]`

### ISSUE THREAD

**Issue by Suljam** [wp-graphql/wp-graphql#1826]
### No schema showing instead shows `fetch@[native code]`

- No schema and error showing
- WPGraphQL ver: 1.3.3
- Other plugins: None
- Expecting to see Schema options out output
- Hosting: Linode
- Web panel: VestaCP

Tried various installs and has the same problem.

<img width="1249" alt="CleanShot 2021-03-28 at 12 14 19@2x" src="https://user-images.githubusercontent.com/14997459/112750552-28bf0700-8fc1-11eb-9135-ac6f8d5a6fae.png">

Output shows this:

```
fetch@[native code]
u@https://suljam.work/wp/wp-content/plugins/wp-graphql/src/Admin/GraphiQL/app/build/static/js/main.b7d08b5b.js?ver=5.7:1:597816
value@https://suljam.work/wp/wp-content/plugins/wp-graphql/src/Admin/GraphiQL/app/build/static/js/main.b7d08b5b.js?ver=5.7:1:620567
https://suljam.work/wp/wp-content/plugins/wp-graphql/src/Admin/GraphiQL/app/build/static/js/main.b7d08b5b.js?ver=5.7:1:606977
https://suljam.work/wp/wp-content/plugins/wp-graphql/src/Admin/GraphiQL/app/build/static/js/main.b7d08b5b.js?ver=5.7:1:675660
a@https://suljam.work/wp/wp-content/plugins/wp-graphql/src/Admin/GraphiQL/app/build/static/js/main.b7d08b5b.js?ver=5.7:1:479971
u@https://suljam.work/wp/wp-content/plugins/wp-graphql/src/Admin/GraphiQL/app/build/static/js/main.b7d08b5b.js?ver=5.7:1:480054
l@https://suljam.work/wp/wp-content/plugins/wp-graphql/src/Admin/GraphiQL/app/build/static/js/main.b7d08b5b.js?ver=5.7:1:480109
s@https://suljam.work/wp/wp-content/plugins/wp-graphql/src/Admin/GraphiQL/app/build/static/js/main.b7d08b5b.js?ver=5.7:1:480269
p@https://suljam.work/wp/wp-content/plugins/wp-graphql/src/Admin/GraphiQL/app/build/static/js/main.b7d08b5b.js?ver=5.7:1:480708
f@https://suljam.work/wp/wp-content/plugins/wp-graphql/src/Admin/GraphiQL/app/build/static/js/main.b7d08b5b.js?ver=5.7:1:480534
d@https://suljam.work/wp/wp-content/plugins/wp-graphql/src/Admin/GraphiQL/app/build/static/js/main.b7d08b5b.js?ver=5.7:1:480872
Le@https://suljam.work/wp/wp-content/plugins/wp-graphql/src/Admin/GraphiQL/app/build/static/js/main.b7d08b5b.js?ver=5.7:1:492870
Ve@https://suljam.work/wp/wp-content/plugins/wp-graphql/src/Admin/GraphiQL/app/build/static/js/main.b7d08b5b.js?ver=5.7:1:493458
Ve@[native code]
https://suljam.work/wp/wp-content/plugins/wp-graphql/src/Admin/GraphiQL/app/build/static/js/main.b7d08b5b.js?ver=5.7:1:595634
yr@https://suljam.work/wp/wp-content/plugins/wp-graphql/src/Admin/GraphiQL/app/build/static/js/main.b7d08b5b.js?ver=5.7:1:534285
Me@https://suljam.work/wp/wp-content/plugins/wp-graphql/src/Admin/GraphiQL/app/build/static/js/main.b7d08b5b.js?ver=5.7:1:493142
Me@[native code]
```

**Comment by jasonbahl** [comment]
@Suljam Hmm. I've not seen this before. What browser are you using?

**Comment by Suljam** [comment]
> @Suljam Hmm. I've not seen this before. What browser are you using?

@jasonbahl - I tried it in Brave (Chrome) and Safari both the latest version on Mac. I even did various installs to try and nail down the issue but always the same out come :/

**Comment by jasonbahl** [comment]
@Suljam how did you install the plugin? Did you install it from WordPress.org, download a Zip and upload it? Clone from Github? 

Perhaps one of the install methods is missing some dependencies or something? 🤔

**Comment by Suljam** [comment]
> @Suljam how did you install the plugin? Did you install it from WordPress.org, download a Zip and upload it? Clone from Github?
> 
> Perhaps one of the install methods is missing some dependencies or something? 🤔

Installed it via the WP Plugin panel. Gonna' give the other options a shot see if that changes anything :)

**Comment by Suljam** [comment]
Still didn't work :(

Some other info if this may help:

Apache2 - Server version: Apache/2.4.29 (Ubuntu)
MySQL - Server version: 5.7.33-0ubuntu0.18.04.1 (Ubuntu)
PHP - PHP 7.4.16 (cli) (built: Mar  5 2021 07:54:20) ( NTS )

**Comment by jasonbahl** [comment]
@Suljam are you able to query with GET requests by visiting your site like so: `http://site.com/graphql?query={posts{nodes{id,title,date}}}`

**Comment by Suljam** [comment]
@jasonbahl Ok that worked.

```
{
  "data": {
    "posts": {
      "nodes": [
        {
          "id": "cG9zdDo4",
          "title": "Test Post 2",
          "date": "2021-03-30T06:59:48"
        },
        {
          "id": "cG9zdDox",
          "title": "Hello world!",
          "date": "2021-03-29T21:58:56"
        }
      ]
    }
  },
  "extensions": {
    "debug": []
  }
}
```

So it's just a case of the GraphiQL part not working then I guess :/

**Comment by Suljam** [comment]
Now in Brave/Chrome it is saying
`TypeError: Failed to fetch`
in GraphiQL

**Comment by Suljam** [comment]
I have the weirdest feeling it's a server issue. I just can't pinpoint it just yet.

**Comment by jasonbahl** [comment]
@Suljam there is a setting under GraphQL > Settings to "Enable Public Introspection"

If you check that, do things work properly?

**Comment by Suljam** [comment]
> @Suljam there is a setting under GraphQL > Settings to "Enable Public Introspection"
> 
> If you check that, do things work properly?

That's checked and can not be changed. Still no luck though. This is so odd :/ 

<img width="1216" alt="CleanShot 2021-03-30 at 16 37 43@2x" src="https://user-images.githubusercontent.com/14997459/113016377-539e8c00-9176-11eb-8cb3-421d52948c05.png">

**Comment by Suljam** [comment]
OK started again, set up a new server. The last time I used Ubuntu 18, this time Cent OS 7 and it all works fine. I have no idea why, but that's what happened :/ 

Thank you so much @jasonbahl for all the help through this.

**Comment by Suljam** [comment]
Ok I come back to this even though it's closed as it wasn't the server. I thought it was but it wasn't. It was the domain going through Cloudflare. I have no idea why that messed it up, but once I removed Cloudflare everything worked perfectly. 

Just adding this here for others that fall down this hole so they don't lose a weekend like I did :P
