### ISSUE TITLE
Taxonomy Queries Using Orderby Count No Longer Sort Correctly

### ISSUE THREAD

**Issue by graphenedigital** [wp-graphql/wp-graphql#1827]
Hey everyone, I am dead-lining (Betas On 1st) a large web-app project and ran updates to wpgraphql plugin core today. I then jumped to frontend to check and make sure all was good and realized all queries based on order (COUNT) are returning least to greatest... 

The example would be cities, I have a dropdown, it populates a list of suggested popular cities within the network... Plus it generates the live autocomplete as users are typing in their location of interest, again attempting to show most popular as they type... 

Unless I am missing a new "order" param by chance, all was certainly running great until the update today. 

**RELATED PLUGINS:**
I am using the metaquery plugin & taxquery plugin to achieve my search request. I also have created many custom routes, fields, etc that are following all guides... again all working great till right before update... 

Not quite sure if anyone else is having this same issue.. Any advice for quick Band-Aid would suffice, maybe a quick fix but just not sure if its something I need to just mod the query around or its hardcoded within one of your plugins... Love the plugins, def need a solution ASAP tho... 

Thanks in advance!!!

**Comment by jasonbahl** [comment]
@graphenedigital can you share some examples of the exact GraphQL Query(s) you're executing to see the incorrect results? 

And what the expected results are? And maybe a screenshot of the Taxonomy Terms in your wp-admin so we can see the raw data from WordPress to compare with what you're seeing in the results. 

The more information you can provide so we can replicate the situation, the better.

**Comment by graphenedigital** [comment]
Hey Jason, Thanks for the extremely fast reply & what appears to be a possible solution already in the works.... 

Not sure if you even need this anymore but..

`query MyQuery {
  cities(last: 5, where: {orderby: COUNT, search: "Charlotte"}) {
    nodes {
      count
      slug
    }
  }
}`

`{
  "data": {
    "cities": {
      "nodes": [
        {
          "count": 2,
          "slug": "charlottesville"
        },
        {
          "count": 2,
          "slug": "charlotte-county"
        },
        {
          "count": 3,
          "slug": "port-charlotte"
        },
        {
          "count": 37,
          "slug": "charlotte"
        }
      ]
    }
  },
  "extensions": {
    "debug": [
      {
        "type": "DEBUG_LOGS_INACTIVE",
        "message": "GraphQL Debug logging is not active. To see debug logs, GRAPHQL_DEBUG must be enabled."
      }
    ]
  }
}`

**Comment by jasonbahl** [comment]
@graphenedigital I made some adjustments to the PR I opened and added some test coverage for it. 

If you have a chance to check out that branch and see if it works for you, that would be great: https://github.com/wp-graphql/wp-graphql/pull/1828

Thanks!

**Comment by graphenedigital** [comment]
Hey Jason, I hate to sound like a git noob... I have no idea how to test this branch.. I tried downloading as plugin direct and installing... that installed but clearly seamed to be missing all dependencies... I also compiled a version via composer after setting my machine up to do so, and finally compiled successfully... With that said, once installed, nothing at all works within graphQL... there is no IDE, plus all request to graphql fail on frontend completely.

Chances are I did most of this wrong... A little guidance could be useful for sure. Thanks in advance!

**Comment by jasonbahl** [comment]
@graphenedigital no worries! 

I'm fairly confident that this resolves the issue. I'll get it released, you can test with the next release and if, for some reason, you notice things not working as expected, we can open a new issue and reference this one for context.

**Comment by graphenedigital** [comment]
Awesome thanks Jason, I appreciate it. Do we have an eta on the release? Asking per my client I need to have his site ready by the first. Just asking for directional purposes. Thanks again!

**Comment by jasonbahl** [comment]
@graphenedigital released today with WPGraphQL v1.3.4!
