### ISSUE TITLE
Warning message when activating wp-graphql plugin from master branch

### ISSUE THREAD

**Issue by markkelnar** [wp-graphql/wp-graphql#1831]
Experiencing the following when activating or deactivating wp-graphql.

PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, function 'graphql_activation_callback' not found or invalid function name in /var/www/html/wp-includes/class-wp-hook.php on line 287
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'graphql_activation_callback' not found or invalid function name in /var/www/html/wp-includes/class-wp-hook.php on line 287

To reproduce, install the plugin found at https://github.com/wp-graphql/wp-graphql/archive/master.zip
Steps to reproduce:
1. Download plugin zip from https://github.com/wp-graphql/wp-graphql/archive/master.zip
2. Open wp-admin.
2. Go to plugins
3. Click Add New
4. Select upload file.
5. Select the file and upload.
6. Find the apache error log for the WP and notice the warning.

Steps to reproduce using wp-cli:
1.  Deactivate the plugin if it is active. `wp --allow-root plugin deactivate wp-graphql`
2. Delete the pliugin if it is installed. `wp --allow-root plugin delete wp-graphql`
3. Install and activate the plugin `wp --allow-root plugin install https://github.com/wp-graphql/wp-graphql/archive/master.zip --activate`

You will see the message in standard error output.

I do not see the error when installed the tagged version 1.3.3 from https://github.com/wp-graphql/wp-graphql/releases/download/v1.3.3/wp-graphql.zip or https://github.com/wp-graphql/wp-graphql/releases/tag/v1.3.3.

**Comment by markkelnar** [comment]
![Uploading Screen Shot 2021-03-30 at 9.22.33 PM.png…]()

**Comment by markkelnar** [comment]
I was seeing this when running wp-graphql-acf docker-compose environment locally and now I understand. What it is downloading from wp-graphql master as a zip has not run `composer install` and therefore the plugin code isn't ready to run in the WP.  

I think the answer is to fix that docker-compose command to download an actual built/bundled zip version of wp-graphql that it is dependent on.  Also make a note in wp-graphql docs somewhere that downloading from a tag or branch from github requires `composer install` to function.

**Comment by markkelnar** [comment]
Using zip file from a path like this with a vX.Y.Z release number works.
https://github.com/wp-graphql/wp-graphql/releases/download/v1.3.3/wp-graphql.zip

**Comment by bhardie** [comment]
- Add warning to CLI
- Add link to latest release to README

**Comment by bhardie** [comment]
@markkelnar can you verify that this is still an issue?

**Comment by josephfusco** [comment]
This is still an issue in the sense that there are no helpful messages within wp-admin that inform a user to run `composer install` if cloning down the project to contribute. I personally experienced a fatal error.

<img width="1366" alt="Screenshot 2023-09-14 at 10 02 03 AM" src="https://github.com/wp-graphql/wp-graphql/assets/6676674/ddcdfb77-683a-4dce-b6bf-20dc8eff8c0f">

It would be nice if a WordPress admin notice was thrown in this scenario.
