### ISSUE TITLE
Feature Request: comment status on createComment mutation

### ISSUE THREAD

**Issue by moonmeister** [wp-graphql/wp-graphql#1839]
# description
Currently you only get a success message. Even if the comment is held for moderation.

I would like to be able to provide that information back to the user. At least being able to query status but also any other information on the comment might be helpful in the mutation.

Currently a user might be inclined to resubmit when their comment if it successfully submitted but is not immediately shown. I've thought about just showing the comment on their side but short of stuffing it into browser storage this easily disappears.  I'm not sure if user auth affects this but I'm currently using un-authenticated fetches for comments so a user would just see no comment as apposed to one marked as awaiting review.

**Comment by moonmeister** [comment]
I've since realized you can request the comment on the mutation. This returns null if the comment is held for moderation and populates fields if it's not. something more explicit could be valuable but this works.

**Comment by justlevine** [comment]
Closed by #2540
