### ISSUE TITLE
No type error on wrong return type ( int -> string ) 

### ISSUE THREAD

**Issue by Poolshark** [wp-graphql/wp-graphql#1840]
I have registered a simple `Object Type` with a simple field `'fieldOne' => 'String'`. In the resolve function I have set the return value to `Integer`. I don't get an error but the result is of type `String`.

**The custom field**
```php
add_action('graphql_register_types', function () {
    register_graphql_field('RootQuery', 'MyCostomField', [
        'type' => 'MyFirstType',
        'description' => 'Testing',
        'resolve' => function () {
            return [ 'fieldOne' => 1 ];
         }
     ]);
});
```

**The Type**
```php
add_action( 'graphql_register_types', function() {
    register_graphql_object_type( 'MyFirstType', [
         'description' => 'This is an Object Type',
         'fields' => [
             'fieldOne' => [
                 'type' => 'String',
                 'description' => 'This field should be a string',
              ]
         ]
    ]);
});
```

**The Query**
```
query MyQuery {
  myCustomField {
    fieldOne
  }
}
```

**The Result**
```json
{
  "data": {
    "myCustomField": {
      "fieldOne": "1"
    }
  },
  "extensions": {
    "debug": []
  }
}
```

I would have expected to get an error since `Integer !== String`

**Comment by jasonbahl** [comment]
This is proper behavior according to the GraphQL Spec: https://spec.graphql.org/June2018/#sec-String

> GraphQL servers may coerce non‐string raw values to String when reasonable without losing information, otherwise they must raise a field error. Examples of this may include returning the string "true" for a boolean true value, or the string "1" for the integer 1.

If you want to guard against this further, you could put your own logic in your resolvers, or possibly [register a custom scalar](https://www.wpgraphql.com/functions/register_graphql_scalar/) with custom validation logic.
