### ISSUE TITLE
Excerpt blog can't be fetched from code

### ISSUE THREAD

**Issue by RodrigoTomeES** [wp-graphql/wp-graphql#1853]
## To reproduce
Select posts, edges, node and excerpt(format: RAW)

## What should be obtained
The blog excerpt

## Actual behavior
null

![imagen](https://user-images.githubusercontent.com/13077343/114388987-b5a6ba80-9b94-11eb-9e7b-8ce348e40f44.png)

![imagen](https://user-images.githubusercontent.com/13077343/114388972-afb0d980-9b94-11eb-9112-d9f73751c00f.png)

## Plataform
 - Wordpress: 5.7
 - Linux 3.10.0-1160.15.2.el7.x86_64 x86_64
 - nginx/1.18.0
 - PHP version: 7.3.27
 - BD: mysqli 5.5.68-MariaDB

## Plugins
- **WP GraphQL  Versión 1.3.5 por WPGraphQL**
- **WPGraphQL for Advanced Custom Fields    Versión 0.4.1 por WPGraphQL, Jason Bahl**
- **WPGraphQL JWT Authentication    Versión 0.4.0 por WPGraphQL, Jason Bahl**
- **WPGraphQL WooCommerce (WooGraphQL)  Versión 0.8.1 por kidunot89**
- Add WPGraphQL SEO   Versión 4.13.1 por Ash Hitchcock
- Admin Columns   Versión 4.2.5 por AdminColumns.com
- Advanced Custom Fields PRO  Versión 5.9.0 por Elliot Condon (Última versión: 5.9.5)
- All-in-One WP Migration Versión 7.40 por ServMask (Última versión: 7.40)
- Classic Editor  Versión 1.6 por WordPress Contributors
- Contact Form 7  Versión 5.4 por Takayuki Miyoshi
- Duplicate Page  Versión 4.4 por mndpsingh287
- Permalink Manager Pro | VestaThemes.com Versión 2.2.1.4 por Maciej Bis (Última versión: 2.2.9.7)
- Post Types Order    Versión 1.9.5.6 por Nsp Code
- Safe SVG    Versión 1.9.9 por Daryll Doyle
- WooCommerce Versión 5.1.0 por Automattic
- WooCommerce Stripe Gateway  Versión 5.1.0 por WooCommerce
- WP-REST-API V2 Menus    Versión 0.8.1 por Claudio La Barbera
- WP All Export Pro   Versión 1.6.3 por Soflyy
- WP All Import - WooCommerce Add-On Pro  Versión 3.2.5 por Soflyy
- WP All Import Pro   Versión 4.6.5 por Soflyy
- Yoast SEO  Versión 16.1.1 por Team Yoast

**Comment by jasonbahl** [comment]
the raw excerpt and raw content is returned only to authenticated users. Much like WordPress itself, you can view/edit the raw content, but public users see the formatted version after it's been passed through `apply_filters( 'the_content' )`. This is expected behavior. I do think the description of the `RAW` Enum should be updated to include mention of this.

**Comment by RodrigoTomeES** [comment]
Oh thank you, I was unaware of this behavior
