### ISSUE TITLE
Move FAQs page from .com to github docs.

### ISSUE THREAD

**Issue by markkelnar** [wp-graphql/wp-graphql#1857]
Convert one documentation page from sourcing from content.wpgraphql.com to github.com/wp-graphql/wp-graphql/docs. Ex https://www.wpgraphql.com/docs/faqs/

* In the gatsby project, clone the wp-graphql repo from github
* Add template to create pages from the markdown files in /docs/
* Use same styling as existing documentation.

**Comment by jasonbahl** [comment]
closed by https://github.com/wp-graphql/wpgraphql.com/pull/18
