### ISSUE TITLE
Term order issues

### ISSUE THREAD

**Issue by web-programmer-here** [wp-graphql/wp-graphql#1868]
When displaying the categories using the [playground](https://playground.wpgraphql.com/#/list-of-categories): 

```graphql

query CategoryList {
  categories (where:{slug: ["post-format-chat" , "post-format-audio" ]}) {
    edges {
      node {
        id
        name
        slug
      }
    }
  }
}

```

we get: 

```
{
  "data": {
    "categories": {
      "edges": [
        {
          "node": {
            "id": "Y2F0ZWdvcnk6NA==",
            "name": "Audio",
            "slug": "post-format-audio"
          }
        },
        {
          "node": {
            "id": "Y2F0ZWdvcnk6Ng==",
            "name": "Chat",
            "slug": "post-format-chat"
          }
        }
      ]
    }
  }
}
```

the order is based on the name, how can I change this order so it orders based on the input? so `post-format-chat` should be first and then `post-format-audio`

**Comment by web-programmer-here** [comment]
@jasonbahl can the orderby parameter have an option to order based on the input?

**Comment by jasonbahl** [comment]
@web-programmer-here you can use the `order` filter like so: 

```graphql
{
  categories(where: {order: ASC, orderby: TERM_ORDER}) {
    nodes {
      id
      name
    }
  }
}

```

**Comment by web-programmer-here** [comment]
@jasonbahl I cant order them based on my own input? so I want chat to be first and then audio or if I want to reverse the order
```graphql
where:{slug: ["post-format-chat" , "post-format-audio" ]}
```

**Comment by jasonbahl** [comment]
@web-programmer-here you can also order by slug like: 

```graphql
{
  categories(where: {slug: ["alignment", "captions"], order: ASC, orderby: SLUG}) {
    nodes {
      name
      slug
    }
  }
}
```

See it in action:

![Screen Shot 2021-05-05 at 10 46 00 AM](https://user-images.githubusercontent.com/1260765/117178395-35d4d000-ad8f-11eb-8143-8220c6e6e3fb.png)
![Screen Shot 2021-05-05 at 10 46 17 AM](https://user-images.githubusercontent.com/1260765/117178401-366d6680-ad8f-11eb-9ef4-b52bb457810a.png)

**Comment by web-programmer-here** [comment]
@jasonbahl thanks but this is not what I mean. Using this method, it orders based on slug but I want to order based on the input I am passing the slug. 

For example if I pass ["alignment", "captions"] I want to get "alignment" and "captions", I dont want to use orderby SLUG and order DESC or ASC because I want to pass the terms as variable and they can be different names which if I use slug, they will not be the same order. Maybe have an orderby but for the same input order?
