### ISSUE TITLE
Latest update broke WooCommerce GraphQl

### ISSUE THREAD

**Issue by Jonofat** [wp-graphql/wp-graphql#1883]
I just updated this plugin to the latest version and it broke my website when I try to fetch products from WooCommerce using the wp-graphql woocommerce plugin. Basically 'products' is missing from the query explorer. You can only now choose 'product' which requires an ID or slug etc. But before the update I was listing all the products using 'products'

I wanted to add a screenshot here but don't know how. This is really urgent (well, for me anyway) 

Rolling back to 1.3.5 makes it work again

**Comment by andymark-by** [comment]
Same problem, no answer yet?

**Comment by spiralni** [comment]
It seems like if the new release is unable to register custom connections. I have problem creating a custom connection in v1.3.6 and it works perfectly in v1.3.5

**Comment by Unknownymous** [comment]
Yes, same problem here, 

![image](https://user-images.githubusercontent.com/6735081/116800541-ab912f80-ab34-11eb-91e8-2b95e7bd8f0b.png)

**Comment by jasonbahl** [comment]
Found the bug. #1885 fixes it. Will get this released shortly.
