### ISSUE TITLE
Custom post menu order doesn't work as expected

### ISSUE THREAD

**Issue by indie-ridge-dev** [wp-graphql/wp-graphql#1884]
Version 1.3.6

I'm not sure if this is a bug or a fundamental misunderstanding on my part but is has me tearing my hair out at the moment.

I have a custom post type which I want to be able to reorder the items in with a re-ordering plugin such as Intuitive Custom Post Order.

Registering the post type without support for page attributes means that Menu Order is not available as a field in Graph QL

Adding support for page attributes gives access to Menu Order but with the following quirks:

1) If I change the post order on the post edit screen it changes the menu_order column in the post table and will show in the Graph QL query

2) If I re-order the menu_order column manually with mySQL or with the re-order plugin the menu_order column changes BUT the Menu Order field in GraphQL still retains the original order I put in through the page attributes metabox.

3) The other strange thing is that the value is retained also in the page attribute metabox in WordPress even though this value no longer seems to exist at all in the database (I tried a value of 1234566 and then searched the database after a re-order and it didn't exist even though it still showed up in the metabox)

So it looks like GraphQl is not taking the Menu Order from the menu_order column in the posts table?

How would I be able to query my custom post type based on the order they exist in the database via the menu_order?

**Comment by justlevine** [comment]
Hey @indie-ridge-dev ,

WPGraphQL uses the native WP_Query to sort posts by menu order ([source](https://github.com/wp-graphql/wp-graphql/blob/7fe5cc0024afe6b8d4e12d56349589f774f8313d/src/Data/Connection/PostObjectConnectionResolver.php#L331)).

>The other strange thing is that the value is retained also in the page attribute metabox in WordPress even though this value no longer seems to exist at all in the database (I tried a value of 1234566 and then searched the database after a re-order and it didn't exist even though it still showed up in the metabox)

This makes me believe that the issue is with your config( aggressive caching maybe?), or something with WordPress itself.

What happens if you use WP_Query to fetch your sorted posts? Do the results respect your new menu order?

```php
$query = new WP_Query( [ 'orderby' => 'menu_order' ] );

error_log( print_r( $query->get_posts(), true ) ); // Output the array of returned posts to debug.log
```

**Comment by justlevine** [comment]
possibly related: https://github.com/wp-graphql/wp-graphql/issues/2300

**Comment by justlevine** [comment]
> Adding support for page attributes gives access to Menu Order but with the following quirks:
> 
> 1. If I change the post order on the post edit screen it changes the menu_order column in the post table and will show in the Graph QL query
> 2. If I re-order the menu_order column manually with mySQL or with the re-order plugin the menu_order column changes BUT the Menu Order field in GraphQL still retains the original order I put in through the page attributes metabox.
> 3. The other strange thing is that the value is retained also in the page attribute metabox in WordPress even though this value no longer seems to exist at all in the database (I tried a value of 1234566 and then searched the database after a re-order and it didn't exist even though it still showed up in the metabox)

I tried and could not reproduce the MySQL issue:
1. I changed the order in the backend on three posts (to `1`, `2`, and `3` ). The correct `post.order` came back.
2. I opened up mysql, and changed `1` to `17`. For good measure, I also manually added an order (`99999`) to a different post:
![image](https://user-images.githubusercontent.com/29322304/167182466-0b0f6a8c-a042-411b-bfbd-befa8653ab58.png)

And here's the results:
![image](https://user-images.githubusercontent.com/29322304/167182801-e36b03e8-564f-4868-b252-dbf0567eae0f.png)

That leaves `Intuitive Custom Post Order` as the culprit, which I'm [betting is using an incompatible filter](https://github.com/wp-graphql/wp-graphql/issues/2300#issuecomment-1111245585).

**Comment by jasonbahl** [comment]
I agree with @justlevine that this seems to be a conflict between plugins. There's some information on how to resolve this issue with the "Post Type Order" plugin: https://github.com/wp-graphql/wp-graphql/issues/2300#issuecomment-1111245585, and users have reported success with the "Simple Custom Post Order" plugin as well. 

If there's more evidence that this can/should be fixed in WPGraphQL core, please open a new issue and reference this one for context.
