### ISSUE TITLE
Hook up Travis CI with Schema Linting 

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#190]
see: https://github.com/cjoudrey/graphql-schema-linter

**Comment by CodeProKid** [comment]
Put this in the 1.1 release for now. Doesn't seem like this needs to be in there for 1.0. Feel free to move it into 1.0 if you think it needs to be though.

**Comment by jasonbahl** [comment]
I was thinking that 1.0 made sense because that’s when we’re essentially saying it’s ready to go, and a tool like this will help us validate that it is ready to go and will help us keep it stable long term. . .so I think we should hook this up, and probably even make some breaking changes to adhere to the best practices it identifies, like capitalized type names (ours are all lowercase now)

**Comment by jasonbahl** [comment]
addressed by #310
