### ISSUE TITLE
pageBy(uri: 'parent-page') doesn't work 

### ISSUE THREAD

**Issue by Obvio** [wp-graphql/wp-graphql#1900]
Vanilla installation with no plugins.
Version 1.3.7

I have 2 pages:  "sample-page" and its child "sample-page/child", when querying using `pageBy(uri: 'sample-page')` the returned result is `null`, when querying for the child using `(uri: 'parent-page/child')` it returns fine.

One issue I noticed in the debug object is that for  the `parent-page` the SQL query looks for `post_type IN ('post','attachment')` while for the `child` page it looks correctly for `post_type IN ('page','attachment')`.

Screenshots for both queries (sql is highlighted):

✅ Child page:

<img width="1190" alt="Screen Shot 2021-05-05 at 20 04 25" src="https://user-images.githubusercontent.com/300232/117220748-39dc0e80-adde-11eb-8abc-68006d1696c3.png">

💔 Parent page (this is the issue):

<img width="1183" alt="Screen Shot 2021-05-05 at 20 05 05" src="https://user-images.githubusercontent.com/300232/117220771-47919400-adde-11eb-8e5b-0332e536b708.png">

Lastly, since its my first steps with this, I'll be happy if you can also point me to the query generation location in the plugin and i'll try to fix this..

Thanks!

**Comment by jasonbahl** [comment]
@Obvio the `pageBy` entry into the graph has been deprecated for some time. 

Can you try the following and report back? 

```graphql
{
  page( id: "sample-page/child" idType: URI ) {
    id
    title
    content
  }
}
```

**Comment by Obvio** [comment]
@jasonbahl that worked, thanks!

**Comment by Obvio** [comment]
I do face another issue with this.. I suppose you could also do:
```graphql
{
  page( id: "sample-page" idType: URI ) {
    id
    title
    content
  }
}
```

but this doesn't work, the return values are empty (tried: `/sample-page`, `/sample-page/`, `sample-page/`).

**Comment by jasonbahl** [comment]
@Obvio is `sample-page` the uri of the page? is that the url you see for the page in the admin when you click "View Page"? 

This could be a permalink setting issue. 

One thing you could try is to query a list of pages and ask for the URI of the pages, like so: 

```graphql
{
  pages {
    nodes {
      id
      uri
    }
  }
}
```

You should get results similar to the following: 

![Screen Shot 2021-06-22 at 11 21 46 AM](https://user-images.githubusercontent.com/1260765/122971214-0a607180-d34c-11eb-89f0-352cdc4d58fd.png)

You should then be able to take one of the `uri` values and use it to query with the query you provided: 

```graphql
{
  page( id: "/sample-page-2/" idType: URI ) {
    id
    title
    content
    uri
  }
}
```

![Screen Shot 2021-06-22 at 11 23 06 AM](https://user-images.githubusercontent.com/1260765/122971380-3a0f7980-d34c-11eb-9e73-69f109413f76.png)

I can also create a child page:

![Screen Shot 2021-06-22 at 11 24 37 AM](https://user-images.githubusercontent.com/1260765/122971593-717e2600-d34c-11eb-871b-1e61704987a2.png)

Which has the uri of `/sample-page-2/child-page/`

And I can also use that URI to query that page directly: 

```graphql
{
  page( id: "/sample-page-2/child-page/" idType: URI ) {
    id
    title
    content
    uri
  }
}
```

And we can see that the child page is also returned as expected. 

![Screen Shot 2021-06-22 at 11 26 29 AM](https://user-images.githubusercontent.com/1260765/122971810-b43ffe00-d34c-11eb-8b47-a15d3c0afc09.png)
