### ISSUE TITLE
Return `post_content_filtered` in Queries

### ISSUE THREAD

**Issue by spetrey** [wp-graphql/wp-graphql#1918]
Howdy y'all! Plugins like Jetpack and [other Markdown editors](https://github.com/terrylinooo/githuber-md) store Markdown content in the `post_content_filtered` table. It would be really neat if that data could be returned in graphql queries.

Proposal:

<img width="828" alt="Screen Shot 2021-05-14 at 11 43 12 AM" src="https://user-images.githubusercontent.com/6411509/118295299-abd0e980-b4a9-11eb-8a4e-fea3e953d209.png">

Is this possible? Is there filter I can drop-in to achieve this? Is this low-hanging fruit, or a pain-in-the-rear? Would love to get everyone's thoughts on this idea 😅

**Comment by chriszarate** [comment]
It's pretty low-hanging fruit with the access functions WPGraphQL provides. See [the docs on `register_graphql_field`](https://www.wpgraphql.com/functions/register_graphql_field/#register-a-post-field) for some examples.

**Comment by spetrey** [comment]
Thanks @chriszarate! super helpful, thanks for directing me to the `register_graphql_field` doc.
I'll go ahead and close this out then 🎉  If anyone is looking for something similar, this got me exactly what I needed:

```
add_action( 'graphql_register_types', function() {
	register_graphql_field( 'Post', 'contentFiltered', [
	  'type' => 'String',
	  'description' => __( 'post_content_filtered field added to the Post Type', 'post-content-filtered-graphql' ),
	  'resolve' => function( \WPGraphQL\Model\Post $post, $args, $context, $info ) {
		  return get_post_field( 'post_content_filtered', $post->databaseId );
	  }
	]);
});
```
