### ISSUE TITLE
Querying for page with ID type URI returns custom post type instead

### ISSUE THREAD

**Issue by benknight** [wp-graphql/wp-graphql#1919]
Steps to reproduce:

1. Create a new page with slug `test`
2. Register a post type in functions.php as follows
  ```php
  function custom_register_post_types()
  {
      register_post_type("block", [
          "exclude_from_search" => true,
          "graphql_single_name" => "block",
          "graphql_plural_name" => "blocks",
          "labels" => [
              "edit_item" => "Edit Block",
              "name" => "Blocks",
              "new_item" => "New Block",
              "singular_name" => "Block",
          ],
          "menu_icon" => "dashicons-screenoptions",
          "menu_position" => 20,
          "public" => false,
          "show_ui" => true,
          "show_in_graphql" => true,
          "show_in_menu" => true,
          "show_in_nav_menus" => false,
          "supports" => ["custom-fields", "revisions", "title"],
      ]);
  }
  
  add_action("init", "custom_register_post_types");
  ```
3. Create a post for this custom post type with the same slug as the page you created: `test`
4. Query for the page in the GraphQL IDE as follows:
```graphql
query MyQuery {
  page(id: "test", idType: URI) {
    id
    content
    databaseId
  }
}

```
5. Observe that the result returned is for the "block" post type, not the page, even though you are querying for a page.

Reduced test case sandbox set up here:
https://wpgraphql-sandbox.vietnamcoracle.com/wp-admin/

Login: `testuser` / `113$hO5~fj(@`

**Comment by bhardie** [comment]
After registering the custom post type, did you flush your permalinks?  Please try flushing permalinks and test again and let us know if it's still an issue.

**Comment by benknight** [comment]
@bhardie no dice. Per your suggestion I did the following:

1. Go to Settings > Permalinks
2. Click "Save changes"

I then went back and tested my query and got the same result.

**Comment by bhardie** [comment]
We were able to reproduce this by creating a page and a block with the same slug and querying by URI.  We will take a look into this.
![image](https://user-images.githubusercontent.com/777730/124642637-ec633880-de44-11eb-839b-7f5d5601bfcd.png)
