### ISSUE TITLE
actionMonitorActions do not show updated menus

### ISSUE THREAD

**Issue by rburgst** [wp-graphql/wp-graphql#1921]
Menus do not appear in the `actionMonitorActions` query. 

Given the this query
```graphql

  query GET_ACTION_MONITOR_ACTIONS($since: Float!, $after: String) {
    actionMonitorActions(
      where: {
        sinceTimestamp: $since
        orderby: { field: MODIFIED, order: DESC }
      }
      first: 100
      after: $after
    ) {
      nodes {
        id
        title
        actionType
        referencedNodeID
        referencedNodeStatus
        referencedNodeGlobalRelayID
        referencedNodeSingularName
        referencedNodePluralName
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
```
and the following variables
```
{
  "since": 1621599254307
}
```
( you will want to use the current timestamp for this)

Then go to Appearance->Menus and change a menu title (or make any other modification to the menus).

Now run the query again.

## Expected
i would have expected to see updates to the menus.

## Actual

The result is empty
```json
{
  "data": {
    "actionMonitorActions": {
      "nodes": [],
      "pageInfo": {
        "hasNextPage": false,
        "endCursor": null
      }
    }
  },
```
see also https://github.com/gatsbyjs/gatsby/issues/31522

**Comment by bhardie** [comment]
@rburgst The actionMonitorActions are defined in [wp-gatsby](https://github.com/gatsbyjs/wp-gatsby/issues/new).  Could you please open this issue [there](https://github.com/gatsbyjs/wp-gatsby/issues/new)?

**Comment by rburgst** [comment]
created https://github.com/gatsbyjs/wp-gatsby/issues/172
