### ISSUE TITLE
Relay::fromGlobalId( $input['id'] ) returns nothing, even though input ID was set in request

### ISSUE THREAD

**Issue by davevanhoorn** [wp-graphql/wp-graphql#1922]
I might've found a `wp-graphql` or `wp-graphql-woocommerce` bug. Sorry @jasonbahl and @kidunot89 for taking your time.

I'm using the `updateCustomer` mutation with success, but I had to fork and change the `wp-graphql` plugin for it to work. The following line of code doesn't seem to return the expected `$id_parts`, even though I *am* sending the `$input['id']` with the request.

**Code in `wp-graphql`:**
https://github.com/wp-graphql/wp-graphql/blob/b24716fc0904a2e51cdf9ad6aa7f32531972ccdd/src/Mutation/UserUpdate.php#L66

It seems like the Relay global ID for `customer` was never set and thus never returns the expected value.

@kidunot89, in the test you've written for `wp-graphql-woocommerce` you set the global ID for `customer` manually, see line 653 in the linked code below:

**Code in `wp-graphql-woocommerce`:**
https://github.com/wp-graphql/wp-graphql-woocommerce/blob/29a60a82521242aaadcd27491473516a3fac0ddb/tests/wpunit/CustomerMutationsTest.php#L653

**My question**
Where or how is the global ID for `customer` set in the non-test code? Not sure if it's got anything to do with it, but I'm sending both a WordPress cookie and WooCommerce session.

**My temporary fix**
I've made a fork and replaced `Relay::fromGlobalId( $input['id'] )`. It's using the ID sent with the request which for now works as expected. 

**Related issues**
- https://github.com/wp-graphql/wp-graphql-woocommerce/issues/436
- https://github.com/wp-graphql/wp-graphql-woocommerce/issues/290

**Comment by bhardie** [comment]
@davevanhoorn You said you are passing input['id'].  Can you share what id you are passing as well as it's type.  fromGlobalId expects a hashed global id.

**Comment by jasonbahl** [comment]
@davevanhoorn I'm going to close this issue due to lack of activity after @bhardie asked some clarifying questions. 

If you're experiencing issues still, please open a new issue, reference this one, and provide additional details to help us debug.
