### ISSUE TITLE
Using `post__in` with an empty array always returns everything

### ISSUE THREAD

**Issue by gavinhenderson** [wp-graphql/wp-graphql#1927]
When you use the `post__in` argument on the `PostObjectConnectionResolver` and give it an empty array it will return all the posts of that type.

## Reproduction

Add a new connection using the `PostObjectConnectionResolver` and add a `post__in` arg with an empty array. If you pass it an empty array it will return every post of that type.

```php
register_graphql_connection([
        'fromType' => 'Product',
        'toType' => 'MoodleCourse',
        'fromFieldName' => 'moodleCourses',
        'connectionArgs' => \WPGraphQL\Connection\PostObjects::get_connection_args(),
        'resolve' => function (\WPGraphQL\Model\Post $source, $args, $context, $info) {
            $resolver   = new \WPGraphQL\Data\Connection\PostObjectConnectionResolver($source, $args, $context, $info, 'eb_course');

            // This sometimes returns an empty array
            // When it does return an empty array I would expect nothing to match
            $myIds = myFunctionThatReturnsIds();

            $resolver->set_query_arg('post__in', $myIds);

            $connection = $resolver->get_connection();
            return $connection;
        },
    ]);
```

## Expected results

If I pass an empty array to `post_in` I expect it to yield no results because no posts match no ids.

## Temporary Fix

I have managed to fix it with the following code:

```php
            // If there is an empty array it just returns everything which we dont want
            // so we trick it by giving it an array with an id that nothing matches
            if (count($myIds) == 0) {
                $myIds = array(-1);
            }
```

**Comment by jacobarriola** [comment]
@gavinhenderson since wpgraphql uses the WP_Query class under the hood to retrieve posts, I _think_ that's the standard behavior for that class. https://developer.wordpress.org/reference/classes/wp_query/#post-page-parameters

**Comment by jasonbahl** [comment]
@gavinhenderson, @jacobarriola is correct that this is how WP_Query works under the hood: https://core.trac.wordpress.org/browser/tags/5.7.1/src/wp-includes/class-wp-query.php#L1649

If the `post__in` array is empty, it doesn't affect the order. 

What you might consider is changing your resolver to not even execute the query at all.

Like so: 

```php
$myIds = myFunctionThatReturnsIds();

// If there are no IDs, no need to execute the underlying WP_Query to find out there are no posts associated with no IDs.
if ( empty( $myIds ) ) {
  return null;
}

$resolver->set_query_arg('post__in', $myIds);

$connection = $resolver->get_connection();
return $connection;
```

**Comment by jasonbahl** [comment]
@gavinhenderson I've closed this as I believe this can be solved within your resolver. 

Thanks for opening the issue and starting a conversation around it! This will surely help others facing similar situation!

**Comment by RavanH** [comment]
Hi, just to let anyone arriving here know: it is a known issue in the WP_Query component for years but set to WONTFIX about 8 years ago because fixing it, sadly, would break too many plugins... See https://core.trac.wordpress.org/ticket/28099
