### ISSUE TITLE
Orderby date

### ISSUE THREAD

**Issue by dre1080** [wp-graphql/wp-graphql#193]
Hi. Thanks for the great plugin. Is it possible to order posts by published date or ID?

**Comment by jasonbahl** [comment]
@dre1080 you can orderby date, but cannot order by ID (at least yet). 

There was a bug with cursor pagination and ordering by ID, but I _think_ that's been resolved so we _should_ probably be able to add ID sorting back. 

Here's an example of sorting by Date though:

![graphql-orderby-date](https://user-images.githubusercontent.com/1260765/29302781-48d92f8c-8144-11e7-8b26-754dd2b244f1.gif)

**Comment by dre1080** [comment]
@jasonbahl I get the following error:

```
{
  "errors": [
    {
      "message": "Argument \"where\" has invalid value {orderby: {field: DATE, order: ASC}}.\nIn field \"orderby\": In field \"field\": Expected type \"orderby\", found DATE.",
      "locations": [
        {
          "line": 2,
          "column": 15
        }
      ]
    }
  ]
}
```

**Comment by jasonbahl** [comment]
@dre1080 what's you're exact query?

**Comment by dre1080** [comment]
@jasonbahl ahh I see the issue. I should be on master branch, didn't realize I was on `0.0.16` tag.

Thanks

**Comment by jasonbahl** [comment]
0.0.16 _should_ have had that as well. 🤔
