### ISSUE TITLE
help me!!!

### ISSUE THREAD

**Issue by vb147** [wp-graphql/wp-graphql#1939]
ERROR #gatsby-source-wordpress_111007

 gatsby-source-wordpress  Request failed with status code 500

Your WordPress server is either overloaded or encountered a PHP error.

Error occurred while fetching nodes of the "Post" type.

Enable WordPress debugging by adding the following to your wp-config.php file:

define("WP_DEBUG", true);
define("WP_DEBUG_LOG", true);
define("GRAPHQL_DEBUG", true);

(See https://wordpress.org/support/article/debugging-in-wordpress/ for more info)

Then run another build before checking your WordPress instance's debug.log file for errors.

If you don't see any errors in debug.log:

Try reducing the requestConcurrency for content updates or the previewRequestConcurrency for previews, and/or reducing
the schema.perPage option:

{
  resolve: 'gatsby-source-wordpress',
  options: {
    schema: {
      perPage: 20, // currently set to 100
      requestConcurrency: 5, // currently set to 15
      previewRequestConcurrency: 2, // currently set to 5
    }
  },
}

**Comment by vvasiloud** [comment]
Hello,

Could you provide additional information for your issue? 
Your issue title and the content seems incomplete for anyone to understand and possibly assist you.

What steps did you do to re-produce this issue? 
Which version of wp-graphql are you using?
Have you tried to limit the requests to the minimum as of the error message to e.g requestConcurrency: 1
and so on...

**Comment by jasonbahl** [comment]
I would recommend trying what the output of Gatsby Source WordPress is suggesting and limit the number of items being fetched per page, limit the request concurrency, etc. 

Different WordPress servers handle concurrent API requests differently, and those options allow your WordPress server to "breathe" between requests. 

If you try adjusting those settings and following other troubleshooting tips from Gatsby and still have issues, please provide more details and a reproducible codebase so we can troubleshoot further.
