### ISSUE TITLE
Gatsby build error when WordPress CMS has moved uploads folder

### ISSUE THREAD

**Issue by paulstroot** [wp-graphql/wp-graphql#1941]
I tried posting this issue on the gatsby-source-wordpress issues page, but have not gotten a response. I am hoping somebody could help me here. Here is a description of my issue. I'm not sure if the issue is with how the data is being sent to graphQL, or how the data is being received by Gatsby.

## Description

When updating an image in WordPress, my Gatsby build (production or development) throws the error. "url passed to create-remote-file-node is either missing or not a proper web uri". If I run the build again it is successful. It seems as if this only happens the first time a remote image is pulled into Gatsby. There are no special characters in the file name and responsive images is turned off in WordPress.

### Steps to reproduce

Set the url of your wordpress CMS to a wordpress site that has the "uploads" directory set to "media". i.e/ _define('UPLOADS','media');_

Run "Gatsby Develop" or "Gatsby Build" on your gatsby site.

If I am running a development build, updating an image in the "media" section of WordPress will cause Gatsby to automatically update the development build, and the updated image will crash the development build throwing the error.

In a production build, If I update the image in WordPress, the next build causes the error. Subsequent builds are successful.

### What Happens
Gatsby returns the error 
`"Error: url passed to create-remote-file-node is either missing or not a proper web uri: [IMAGE URL]", `
where [IMAGE URL] is the url of the image that was just updated.

### What should happen?
successful build with no errors. The new media item pulled into the gatsby public folder.

### gatsby-config.js

```
module.exports = {
  plugins: [
    {
      resolve: `gatsby-source-wordpress`,
      options: {
        url: `http://wp-base-install.paulstroot.com/graphql`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `assets`,
        path: `${__dirname}/content/assets`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    `gatsby-plugin-react-helmet`,
  ],
}

```

### Environment
```
  npmPackages:
    "gatsby": "^3.3.0",
    "gatsby-image": "^3.3.0",
    "gatsby-plugin-manifest": "^3.3.0",
    "gatsby-plugin-offline": "^4.3.0",
    "gatsby-plugin-react-helmet": "^4.3.0",
    "gatsby-plugin-sharp": "^3.3.0",
    "gatsby-source-filesystem": "^3.3.0",
    "gatsby-source-wordpress": "^5.3.0",
    "gatsby-transformer-sharp": "^3.3.0",
    "html-react-parser": "^1.1.1",
    "lodash": "^4.17.20",
    "postcss": "^8.2.10",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-helmet": "^5.2.1",
    "typeface-merriweather": "1.1.13",
    "typeface-montserrat": "1.1.13"
```

### Wordpress
```
    Version 5.7

Installed Plug-ins:
    WP Gatsby 1.0.10
    WP GraphQL 1.3.9
    
Only edit to wp-config.php:
    define('UPLOADS','media');
```

I found the code that throws this error. It can be found in [create-nodes/create-remote-file-node/index.js:424-430](https://github.com/gatsbyjs/gatsby/blob/54d4721462b9303fed723fdcb15ac5d72e103778/packages/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/create-remote-file-node/index.js#L424-L430)
```
  if (!url || isWebUri(url) === undefined) {
    return Promise.reject(
      new Error(
        `url passed to create-remote-file-node is either missing or not a proper web uri: ${url}`
      )
```

A minimal reproduction has been set up at this branch. It's basically just a single page with gatsby-source-wordpress.
https://github.com/ocupop/librestream/tree/develop_minimal_reproduction.

I think I've narrowed down the issue to the WordPress install moving the uploads folder to a new location. In my case, the uploads were being saved to "/media".  When I remove the setting in wp-config **define('UPLOADS','media')**, I stop getting the error message. Has anybody else encountered this? If this is an issue, is there a fix? (moving all the media back into the "wp-content/uploads" folder may not be an option)

I have tested this with a clean install of WordPress (v5.7), and a clean installation of "gatsby-wordpress-starter-blog". As soon as I change the uploads folder to "media" in the wp-config file, I get an error whenever I update an image in WordPress. I have updated my original post to reflect this minimal environment setup.

I suspect that it is throwing an error because it is being passed a relative URL instead of an absolute URL for some reason, which is why it is not passing the "isWebUri()" function.
https://www.npmjs.com/package/valid-url

I also suspect that the image does get saved to the cache, which is maybe why it only throws an error the first build after the image is updated.

**Comment by jasonbahl** [comment]
@paulstroot If I'm reading this correctly, WPGraphQL is making the data queryable, but Gatsby is having trouble understanding the data? 

Like, if we take Gatsby out of the equation, can you query your media items from WPGraphQL directly and get the data you would expect for media items? 

Or is there an issue with WPGraphQL outputting data that's incorrect after changing the upload directory?

If there are specific queries or fields in WPGraphQL that are not behaving as expected when making the upload directory change, please list those queries/fields here so we can help work toward a fix. 

Thanks!

**Comment by paulstroot** [comment]
Yes, I can query the items from GraphQL without issue. The problem comes when Gatsby tries to retrieve the image from WordPress. I suspect that the issue is happening on the Gatsby end of things, but hoping somebody would have an answer here since WP GraphQL is so often used with Gatsby. 

If anybody happens to know exactly which graphql element gatsby-source-wordpress references to download the images, I could doublecheck to make sure it's formatted properly as an absolute URL and not a relative one. (allWpMediaItem > nodes > sourceUrl does appear to be absolute). This would tell us if the URL is being converted to relative on the WordPress side or the Gatsby side.

**Comment by jasonbahl** [comment]
@paulstroot Since WPGraphQL appears to be working as expected I'm going to close this issue in this repo. 

I'd recommend opening an issue on the Gatsby Source WordPress repo (https://github.com/gatsbyjs/gatsby-source-wordpress-experimental) and/or asking in the `#gatsby` channel of the WPGraphQL Slack ([join here](https://join.slack.com/t/wp-graphql/shared_invite/zt-3vloo60z-PpJV2PFIwEathWDOxCTTLA)) or the Headless WordPress Discord ([join here](https://discord.com/invite/J2khkF9XYK))

**Comment by paulstroot** [comment]
Thank you for the suggestions, I will try that.

FYI, The repo you linked to is the depreciated one. I did open an issue with the Gatsby Source WordPress repo that I am using and still no response after a month and a half. That's why I've been reaching out to other forums like this one in hopes that I'll find somebody who might be able to help.
https://github.com/gatsbyjs/gatsby/issues/31335
