### ISSUE TITLE
createComment mutation failing via Apollo but succeeding via external graphiql interface

### ISSUE THREAD

**Issue by dmbrooking** [wp-graphql/wp-graphql#1952]
I am running the follow mutation from my front end:

```
mutation createComment($commentOn: Int!, $content: String!, $author: String!, $authorEmail: String!, $parent: ID) {
  createComment(
    input: {commentOn: $commentOn, content: $content, author: $author, authorEmail: $authorEmail, parent: $parent}
  ) {
    success
    __typename
  }
}
```

It fails within the frontend, giving the standard unexpected end of JSON output error.

![image](https://user-images.githubusercontent.com/128946/121918686-4cfacc00-cd04-11eb-84a0-47dfbb6fa1df.png)

What I have been doing is going into dev tools to networking tab and grab the mutation from the request payload:

![image](https://user-images.githubusercontent.com/128946/121918879-74519900-cd04-11eb-9ebd-3502423f5961.png)

Then I take that and run it in the standalone GraphiQL UI tool (I don't want to run in graphiql ide because I've had issues in the past with things working due to being authenticated in the graphiql ide but not auth'd in the frontend). In the standalone tool, it works fine.

![image](https://user-images.githubusercontent.com/128946/121919100-ae229f80-cd04-11eb-8a3b-072865b9d3c1.png)

I don't know how one could reproduce this as I've searched and it does not seem to be a common issue so my assumption is I am doing something wrong? Hoping someone can point me in the right direction.

**Comment by dmbrooking** [comment]
Does anyone have any idea on this? If I'm posting in the wrong spot, please let me know and I'll go elsewhere. We are quickly heading towards a production launch and this is one of the last big hurdles we need to get past so any help is appreciated.

**Comment by CoderPrans** [comment]
Hi @dmbrooking Its hard to tell what might be wrong just with this. Please share the actual server response shown in the Network tab. Unexpected end of JSON input means the server encountered some kind of issue when processing the request and returned an error message instead of a JSON object. 
However it looks likely that it has to do with CORS same origin policy. You can try setting "Access-Control-Allow-Origin" to "*" in the response header.

**Comment by justlevine** [comment]
👋 @dmbrooking were you ever able to sort this out?

**Comment by dmbrooking** [comment]
Yes I did get it fixed. For posterity sake, I honestly don’t remember exactly what the issue was or how I fixed it but the comment about CORS does jostle something in my memory so it most likely was that.
