### ISSUE TITLE
uri field on taxonomy empty @v1.4

### ISSUE THREAD

**Issue by Marco-Daniel** [wp-graphql/wp-graphql#1959]
After updating to v1.4 the uri field on (custom) taxonomies always returns null.

I've created a custom taxonomy for a custom post type using CPT UI. Before 1.4 it always returned something like: /{taxonomy-archive-path}/{taxonomy-slug}/

**Comment by benknight** [comment]
Same thing happened to me.  Downgrading to 1.3.10 fixed it.

**Comment by jasonbahl** [comment]
I've reproduced. PR with test coming.

**Comment by jasonbahl** [comment]
@benknight @Marco-Daniel I've got a PR with a fix and test for this here: https://github.com/wp-graphql/wp-graphql/pull/1963

**Comment by jasonbahl** [comment]
@benknight @Marco-Daniel the fix has been released in v1.4.2: https://github.com/wp-graphql/wp-graphql/releases/tag/v1.4.2

**Comment by jasonbahl** [comment]
Fyi, I botched the release process, so the change is actually in v1.4.3

**Comment by Marco-Daniel** [comment]
@jasonbahl I can confirm that its fixed, thanks for the fast response!
