### ISSUE TITLE
Custom Post issue with WP GraphQL

### ISSUE THREAD

**Issue by atexzonate** [wp-graphql/wp-graphql#1960]
In my custom post type, when I set  "show in graphQL" to "true" and also singular and plural name.  

I get an error in GraphiQL IDE and also in the endpoint (path) for the GraphQL API on the site. 
![image](https://user-images.githubusercontent.com/20685411/122235381-fe665100-cf00-11eb-9380-5c1f25848176.png)
![image](https://user-images.githubusercontent.com/20685411/122235771-4eddae80-cf01-11eb-9484-baa898c8ad1f.png)

If the go back to my custom post type and unset  "show in graphQL" to "false"  the error go away.
I have tried everything possible. Can someone please help me out 

Plugin Stack:
WP GraphQL version 1.4.0 
Custom Post Type UI version 1.9.1
Advanced Custom Fields PRO version 5.9.5
WPGraphQL for Advanced Custom Fields version 0.5.2

**Comment by jasonbahl** [comment]
@atexzonate there was a regression in WPGraphQL v1.4.0. I've released v1.4.1. Can you update and report back if it's working?

**Comment by atexzonate** [comment]
@jasonbahl after updating to WPGraphQL v1.4.2 the outcome still remains the same

**Comment by jasonbahl** [comment]
@atexzonate do you have access to your server's php error logs? Can you check those and see what's reported there?

I'll try and reproduce with the versions you shared.

**Comment by jasonbahl** [comment]
@atexzonate I just tried with the versions you specified and I'm not able to reproduce. I was able to create a post type with Custom Post Type UI then see it in the GraphQL Schema. 

Can you maybe get the code for the post_type using the "Get Code" tool of Custom Post Type UI (`{yoursite.com}/wp-admin/admin.php?page=cptui_tools&action=get_code`) 

Additionally, if you can enable GraphQL Debug mode from your WordPress Admin GraphQL > Settings page, and check your PHP server error logs, that would be helpful.

**Comment by ardiewen** [comment]
hey @jasonbahl i noticed something strange while troubleshooting another issue actually... when I go to CPT UI 1.9.1 and generate the code, the plurals is actually missing... maybe it's an issue with the CPT UI plugin?


For example, a freshly created CPT called "Notes" generates this output:
```
function cptui_register_my_cpts_notes() {

	/**
	 * Post Type: Notes.
	 */

	$labels = [
		"name" => __( "Notes", "twentytwentyone" ),
		"singular_name" => __( "Note", "twentytwentyone" ),
		"menu_name" => __( "Notes", "twentytwentyone" ),
		"all_items" => __( "All Notes", "twentytwentyone" ),
		"add_new" => __( "Add new", "twentytwentyone" ),
		"add_new_item" => __( "Add new Note", "twentytwentyone" ),
		"edit_item" => __( "Edit Note", "twentytwentyone" ),
		"new_item" => __( "New Note", "twentytwentyone" ),
		"view_item" => __( "View Note", "twentytwentyone" ),
		"view_items" => __( "View Notes", "twentytwentyone" ),
		"search_items" => __( "Search Notes", "twentytwentyone" ),
		"not_found" => __( "No Notes found", "twentytwentyone" ),
		"not_found_in_trash" => __( "No Notes found in trash", "twentytwentyone" ),
		"parent" => __( "Parent Note:", "twentytwentyone" ),
		"featured_image" => __( "Featured image for this Note", "twentytwentyone" ),
		"set_featured_image" => __( "Set featured image for this Note", "twentytwentyone" ),
		"remove_featured_image" => __( "Remove featured image for this Note", "twentytwentyone" ),
		"use_featured_image" => __( "Use as featured image for this Note", "twentytwentyone" ),
		"archives" => __( "Note archives", "twentytwentyone" ),
		"insert_into_item" => __( "Insert into Note", "twentytwentyone" ),
		"uploaded_to_this_item" => __( "Upload to this Note", "twentytwentyone" ),
		"filter_items_list" => __( "Filter Notes list", "twentytwentyone" ),
		"items_list_navigation" => __( "Notes list navigation", "twentytwentyone" ),
		"items_list" => __( "Notes list", "twentytwentyone" ),
		"attributes" => __( "Notes attributes", "twentytwentyone" ),
		"name_admin_bar" => __( "Note", "twentytwentyone" ),
		"item_published" => __( "Note published", "twentytwentyone" ),
		"item_published_privately" => __( "Note published privately.", "twentytwentyone" ),
		"item_reverted_to_draft" => __( "Note reverted to draft.", "twentytwentyone" ),
		"item_scheduled" => __( "Note scheduled", "twentytwentyone" ),
		"item_updated" => __( "Note updated.", "twentytwentyone" ),
		"parent_item_colon" => __( "Parent Note:", "twentytwentyone" ),
	];

	$args = [
		"label" => __( "Notes", "twentytwentyone" ),
		"labels" => $labels,
		"description" => "",
		"public" => true,
		"publicly_queryable" => true,
		"show_ui" => true,
		"show_in_rest" => true,
		"rest_base" => "",
		"rest_controller_class" => "WP_REST_Posts_Controller",
		"has_archive" => false,
		"show_in_menu" => true,
		"show_in_nav_menus" => true,
		"delete_with_user" => false,
		"exclude_from_search" => false,
		"capability_type" => "post",
		"map_meta_cap" => true,
		"hierarchical" => false,
		"rewrite" => [ "slug" => "notes", "with_front" => true ],
		"query_var" => true,
		"supports" => [ "title", "editor", "thumbnail" ],
		"show_in_graphql" => true,
		"graphql_single_name" => "Note",
		"show_in_graphql" => "Notes",
	];

	register_post_type( "notes", $args );
}

add_action( 'init', 'cptui_register_my_cpts_notes' );

```

Notice how `"show_in_graphql"`  is shown twice? The second one probably should be "graphql_plural_name" instead.

That being said, I am unable to replicate @atexzonate 's issue in my minimal environment running WpGraphQL 1.4.2

**Comment by ardiewen** [comment]
Strangely enough, the plural name seemed to be have registered fine in the UI, so maybe its just an export tool issue:
<img width="1552" alt="Screen Shot 2021-06-16 at 4 34 31 PM" src="https://user-images.githubusercontent.com/39966887/122290041-5b421700-cec1-11eb-8277-883948f4d7fc.png">

**Comment by jasonbahl** [comment]
@ardiewen good catch! 

It looks like a typo in the Custom Post Type UI plugin. I opened a PR there to fix: https://github.com/WebDevStudios/custom-post-type-ui/pull/814

**Comment by tw2113** [comment]
Coincidentally I was just looking at this too, as @ardiewen opened some forum support for it as well. Great timing.

**Comment by atexzonate** [comment]
> 
> Can you maybe get the code for the post_type using the "Get Code" tool of Custom Post Type UI (`{yoursite.com}/wp-admin/admin.php?page=cptui_tools&action=get_code`)
> 
> Additionally, if you can enable GraphQL Debug mode from your WordPress Admin GraphQL > Settings page, and check your PHP server error logs, that would be helpful.

 Get Code Action 

`
function cptui_register_my_cpts() {

	/**
	 * Post Type: lesson.
	 */

	$labels = [
		"name" => __( "lesson", "twentytwentyone" ),
		"singular_name" => __( "lesson", "twentytwentyone" ),
		"menu_name" => __( "Lessons", "twentytwentyone" ),
		"all_items" => __( "All Lessons", "twentytwentyone" ),
		"add_new" => __( "Add new", "twentytwentyone" ),
		"add_new_item" => __( "Add new lesson", "twentytwentyone" ),
		"edit_item" => __( "Edit lesson", "twentytwentyone" ),
		"new_item" => __( "New lesson", "twentytwentyone" ),
		"view_item" => __( "View lesson", "twentytwentyone" ),
		"view_items" => __( "View lessons", "twentytwentyone" ),
		"search_items" => __( "Search lesson", "twentytwentyone" ),
		"not_found" => __( "lesson not found", "twentytwentyone" ),
		"not_found_in_trash" => __( "lesson not found in Trash", "twentytwentyone" ),
	];

	$args = [
		"label" => __( "lesson", "twentytwentyone" ),
		"labels" => $labels,
		"description" => "",
		"public" => true,
		"publicly_queryable" => true,
		"show_ui" => true,
		"show_in_rest" => true,
		"rest_base" => "",
		"rest_controller_class" => "WP_REST_Posts_Controller",
		"has_archive" => false,
		"show_in_menu" => true,
		"show_in_nav_menus" => true,
		"delete_with_user" => false,
		"exclude_from_search" => false,
		"capability_type" => "post",
		"map_meta_cap" => true,
		"hierarchical" => false,
		"rewrite" => [ "slug" => "lesson", "with_front" => true ],
		"query_var" => true,
		"menu_position" => 5,
		"supports" => [ "title", "editor", "thumbnail" ],
		"show_in_graphql" => true,
		"graphql_single_name" => "Lesson",
		"show_in_graphql" => "Lesson",
	];

	register_post_type( "lesson", $args );
}

add_action( 'init', 'cptui_register_my_cpts' );

`


Error log shows 

`#0 test.app.rccgaustraliapacific.org/wp-includes/class-wp-hook.php(292): WPGraphQL\Registry\TypeRegistry->init_type_registry(Object(WPGraphQL\Registry\TypeRegistry))
#1 test.app.rccgaustraliapacific.org/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array)
#2 test.app.rccgaustraliapacific.org/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#3 test.app.rccgaustraliapacific.org/wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php(198): do_action('init_graphql_ty...', Object(WPGraphQL\Registry\TypeRegistry))
#4 test.app.rccgau in /home/feastofesther18/public_html/test.app.rccgaustraliapacific.org/wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php on line 411
`

I hope this information can help

**Comment by atexzonate** [comment]
Thanks, guys for your help and support. After displaying the Log with WP_DEBUG_DISPLAY in my wp.config file. 

I found out that GraphQL Single Name and GraphQL Plural Name * can not be the same.

**Comment by tw2113** [comment]
Interesting.

Would make things interesting if someone ever made post types out of these words though: https://www.wordexample.com/list/words-same-plural however I won't claim most of those as necessarily good for a post type, but other people have their own needs.

**Comment by jasonbahl** [comment]
Yep, you could name them something like `fish` and `allFish` or `fishNodes` or something to that tune. 

Gatsby defaults to `$word` and `all$Word` so you have `post` and `allPost` or `sheep` and `allSheep`. 

WPGraphQL lets you set them to what you want, but it is important to have them be different because there are different references in the Schema for single objects and lists of objects.
