### ISSUE TITLE
How to specify "variables" parameter in query string with GET method?

### ISSUE THREAD

**Issue by yaquawa** [wp-graphql/wp-graphql#1969]
Hi, I'm trying to cache the GraphQL response returned by **wp-graphql** via CDN(fastly).

I noticed that wp-graphql allows "http-get-requests"
https://www.wpgraphql.com/docs/interacting-with-wpgraphql/#http-get-requests

The example on the doc is fairly simple one:
```
https://www.wpgraphql.com/graphql?query={generalSettings{url}}
```

So how could I specify the "variables" in the query parameter?
for instance:
```gql
  query GetContentPost($id: ID!) {
    contentPost(id: $id, idType: DATABASE_ID) {
      databaseId
      title
      date
      content
    }
  }
```

how could I transform the above to a valid query string?

**Comment by jasonbahl** [comment]
@yaquawa you should be able to make a query with variables like so: 

`/graphql?query=query%20GetPosts($first:Int){posts(first:$first){nodes{id,title,content}}}&variables={"first":1}`

**Comment by yaquawa** [comment]
Thanks @jasonbahl ! That works! but if there is no such a post, the payload of the response is completed empty, where the POST method will get a JSON response that tell me there is no result. is this a bug?

**Comment by chriszarate** [comment]
@yaquawa I can't replicate this, can you provide an example request?
