### ISSUE TITLE
Single Post by IdType Slug giving an Internal server error 

### ISSUE THREAD

**Issue by Hamza-Liaqat1** [wp-graphql/wp-graphql#1979]

**Comment by jasonbahl** [comment]
@Hamza-Liaqat1 can you provide some information in this issue so we can reproduce the issue?

Provide examples of the data you have in your database, the GraphQL queries you tried to execute, the expected results and the actual results? 

Right now it's difficult for us to help without information about the issue.

**Comment by Hamza-Liaqat1** [comment]
Yes, sure here in this screenshot you can see all posts data. 
![image](https://user-images.githubusercontent.com/61942838/124202472-da576200-daf3-11eb-9977-96559ebf987c.png)

Now When I get a single post by IdType SLUG it's giving an error here you can see error below
![image](https://user-images.githubusercontent.com/61942838/124202638-39b57200-daf4-11eb-9a7b-d3def46d28b3.png)

And it's working fine with IdType Id, I can get post only by Id
![image](https://user-images.githubusercontent.com/61942838/124202721-6e292e00-daf4-11eb-9fad-56d446a35897.png)

**Comment by Hamza-Liaqat1** [comment]
@jasonbahl

**Comment by bhardie** [comment]
@Hamza-Liaqat1 Can you please share what your permalink settings are?

**Comment by Hamza-Liaqat1** [comment]
@bhardie I don't now about it these settings and where i can find these settings

**Comment by jasonbahl** [comment]
@Hamza-Liaqat1 in your WordPress dashboard you can visit `Settings > Permalinks`. 

Take a screenshot of that page to start. 

Also, in `GraphQL > Settings` is a setting to enable GraphQL Debug mode. Turn that on and you should have a more detailed error than `Internal Server Error`

**Comment by Hamza-Liaqat1** [comment]
![image](https://user-images.githubusercontent.com/61942838/124650824-9679a980-deb3-11eb-9cd8-4667cc9e4cab.png)

**Comment by Hamza-Liaqat1** [comment]
@jasonbahl

**Comment by Hamza-Liaqat1** [comment]
Here it is

**Comment by jasonbahl** [comment]
@Hamza-Liaqat1 can you enable the GRAPHQL Debug mode also then run the query again and see what the error message is?

**Comment by Hamza-Liaqat1** [comment]
ok let me check

**Comment by Hamza-Liaqat1** [comment]
![image](https://user-images.githubusercontent.com/61942838/124651360-40f1cc80-deb4-11eb-81ec-fe8b7765218f.png)

**Comment by Hamza-Liaqat1** [comment]
@jasonbahl  here it is

**Comment by jasonbahl** [comment]
@Hamza-Liaqat1 can you follow that error and see what's happening with the `AmpWP\PairedRouting::restore_path_endpoint_in_environment()` function?

This appears to be a conflict with that plugin, but I'm not familiar with that plugin or what it's trying to do with that function.

**Comment by jasonbahl** [comment]
@Hamza-Liaqat1 thanks for the back and forth on this issue. 

I was able to find the cause and opened a PR #1992 to resolve this conflict.
