### ISSUE TITLE
HP Fatal error:  Uncaught TypeError: Argument 4 passed to WPGraphQL\Utils\Preview::filter_post_meta_for_previews() must be of the type bool, null given

### ISSUE THREAD

**Issue by zolon4** [wp-graphql/wp-graphql#1983]
Hey all, getting this weird issue that was supposedly fixed in this [issue](https://github.com/wp-graphql/wp-graphql/issues/1864)

Let me know if there's any other information you need! 
### Steps to reproduce 
Install wp GraphQL and navigate to the home page

### WPGraphQl Version

1.5.0

### Expected Behavior
Looking for my site to not crash.

### Other Plugins
ACF: Better Search Version 3.8.1, Advanced Custom Fields Version 5.9.7, Advanced Custom Fields PRO Version 5.9.6, Autoptimize Version 2.8.4,
Better Search Replace Version 1.3.4, Breadcrumb NavXT Version 6.6.0, CB Change Mail Sender Version 1.2.2, Classic Editor Version 1.6, Contact Form 7 Version 5.4.1,
Contact Form CFDB7 Version 1.2.5.9, Custom Fonts Version 1.3.2, Custom Post Type Editor Version 1.4.2, Custom Post Type Maker Version 1.1.15, Custom Post Type Permalinks Version 3.4.4,
Disable Comments Version 2.1.2 , Duplicate Page Version 4.4, Enable Media Replace Version 3.5.0, Envira Gallery Version 1.9.3.6, Envira Gallery - Albums Addon Version 1.7.8.5, Envira Gallery - CSS Addon Version 1.3.4,
Select Envira Gallery - Gallery Themes Addon Version 2.0.4, Select Envira Gallery - Videos AddonVersion 1.6.2, Error Log Monitor Version 1.7, Select Error Log Viewer by BestWebSoft Version 1.1.1,
Select Favicon by RealFaviconGenerator Version 1.3.20, Select Forms: 3rd-Party Integration Version 1.8, GDPR Cookie Consent Version 2.3.4, Geo Maxmind Version 1.0.1, Geolocation IP Detection Version 4.1.0,
GeoTargeting Lite Version 1.3.5, Gravity Forms Version 2.5.6, Gravity Forms Mailchimp Version 4.9, Insert Headers and Footers Version 1.6.0,  Insert PHP Code Snippet	Version 1.3.2,
Instagram Feed Pro Personal Version 5.3.1, Invisible reCaptcha addon for Gravity Forms Version 1.0.11, Latest Post Shortcode Version 9.6.5,
Luxe Addons Version 1.0, MEC Fluent-view Layouts Version 1.2.1, Media from FTP Version 11.14, Modern Events Calendar Lite Version 5.20.6, My Database Admin Version 1.1.22,
Read More Without Refresh Version 3.1, Redux Version 4.1.29, Redux Addons Version 1.0,Reject Urls And Emails In Textarea For (Gravity Forms) Version 1.1 | By 8pecxstudios | View details
Schema & Structured Data for WP & AMP Version 1.9.80, ShortPixel Image Optimizer Version 4.22.2,  Simple Custom CSS and JS Version 3.36, smart Archive Page Remove Version 5.0.3,
Smart Slider 3 Pro Version 3.4.1.14, Smush Version 3.8.7, Social Snap Version 1.1.15, Table Generator Extension: Themes Version 1.0.0, TableGen - Data Table Generator Version 1.0.5,
User Role Editor Version 4.60, User Switching Version 1.5.7, Websitescanner Custom Schema Version 1.3.4, WordPress Importer Version 0.7, WP Engine Automated Migration Version 4.62, WP GraphQL Version 1.5.0, WP Hotel Booking Version 1.10.5, WP Hotel Booking Authorize Payment Version 1.7.4,
WP Hotel Booking Block Room Version 1.7.7, WP Hotel Booking Coupon Version 1.7.3, WP Hotel Booking Report Version 1.7.2, WP Hotel Booking Stripe Payment Version 1.7.6, WP Instagram Widget Version 2.0.3,
WPBakery Page Builder Version 6.0.5, WPML Multilingual CMS Version 4.4.10, WPML String Translation Version 3.1, WPML Translation Management Version 2.10.6, Yoast SEO Version 16.6.1

**Comment by jasonbahl** [comment]
@zolon4 do you have full error log you can share? Also, if you go through the old classic "de-activate each plugin and try again" are you able to pinpoint which plugin has the conflict?

**Comment by zolon4** [comment]
@jasonbahl 


[06-Jul-2021 21:08:51 UTC] PHP Notice:  Trying to access array offset on value of type bool in /nas/content/live/devcasa/wp-content/plugins/wp-hotel-booking-authorize-payment/inc/class-hb-payment-gateway-authorize-sim.php on line 77
#5 /nas/content/live/devcasa/wp-content/plugins/webtoffee-gdpr-cookie-consen in /nas/content/live/devcasa/wp-content/plugins/wp-graphql/src/Utils/Preview.php on line 23
#4 /nas/content/live/devcasa/wp-includes/post.php(2226): get_metadata('post', 51456, '_cli_cookie_hea...', NULL)
#3 /nas/content/live/devcasa/wp-includes/meta.php(506): get_metadata_raw('post', 51456, '_cli_cookie_hea...', NULL)
#2 /nas/content/live/devcasa/wp-includes/meta.php(564): apply_filters('get_post_metada...', NULL, 51456, '_cli_cookie_hea...', NULL, 'post')
#1 /nas/content/live/devcasa/wp-includes/plugin.php(212): WP_Hook->apply_filters(NULL, Array)
#0 /nas/content/live/devcasa/wp-includes/class-wp-hook.php(294): WPGraphQL\Utils\Preview::filter_post_meta_for_previews(NULL, 51456, '_cli_cookie_hea...', NULL)
Stack trace:
[06-Jul-2021 21:08:46 UTC] PHP Fatal error:  Uncaught TypeError: Argument 4 passed to WPGraphQL\Utils\Preview::filter_post_meta_for_previews() must be of the type bool, null given, called in /nas/content/live/devcasa/wp-includes/class-wp-hook.php on line 294 and defined in /nas/content/live/devcasa/wp-content/plugins/wp-graphql/src/Utils/Preview.php:23



This is the full stack. Also seeing some issues with WPML?

**Comment by zolon4** [comment]
I'm seeing this issue with a handful of plugins

**Comment by jasonbahl** [comment]
@zolon4 can you share the function found at: `class-hb-payment-gateway-authorize-sim.php line 77`?

**Comment by jasonbahl** [comment]
@zolon4 if you change the function in WPGraphQL `wp-graphql/src/Utils/Preview.php on line 23` from:

```php
public static function filter_post_meta_for_previews( $default_value, int $object_id, ?string $meta_key, bool $single ) {
```

to: 

```php
public static function filter_post_meta_for_previews( $default_value, int $object_id, ?string $meta_key, ?bool $single ) {
```

Do the errors stop?

**Comment by zolon4** [comment]
@jasonbahl the errors do stop if I change that line

**Comment by jasonbahl** [comment]
@zolon4 want to make a PR with that change? 😄

**Comment by zolon4** [comment]
@jasonbahl 100p I got you my dude

**Comment by jasonbahl** [comment]
@zolon4 sweet! Looking forward!
