### ISSUE TITLE
Add `is$interfaceName` fields to each Interface

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#1989]
When querying for Types that implement many interfaces, there's often a need to route to a specific component based on implementing interface. 

For example, let's say I have a Custom Post Type called "Books" 

I might want to query like so: 

```graphql
{
  nodeByUri( uri: "/books/some-title" ) {
    __typename
    id
  }
}
```

In this response, I will know that the `__typename` is a `Book` but I will not know that it's also a ContentNode. 

In the WordPress template hierarchy there's a fallback template for all post types (ContentNodes in WPGraphQL) and to accomplish this in a headless context we will need to know the specific type (`__typename: "Book"`) but also the "fallback" generic type (ContentNode).

That way a generic `ContentNode` template can exist for _all_ post types, and a more specific `Book` or `CustomPostType` template can exist for specific Types. 

If each Interface provided a `Boolean!` field `is$interfaceName` we could accomplish this. 

For example, we could do something like so: 

```php
{
  nodeByUri( uri: "/books/some-title" ) {
    __typename
    id
    ...on ContentNode {
       isContentNode
    }
  }
}
```

Now the response would include: 

```json
"__typename": "Book"
"isContentNode": true
```

Which would give enough information to route to a fallback "ContentNode" template, but also a more specific "Book" template, should it exist.

**Comment by eihsan94** [comment]
does this means if we use word press as headless we should set isContentNode and isTermNode to false as headless has not templates?

**Comment by eihsan94** [comment]
i see thank you for your reply.
