### ISSUE TITLE
Updating version 1.2.5 to 1.5.1

### ISSUE THREAD

**Issue by jmursuadev** [wp-graphql/wp-graphql#1995]
WpGraphQL version 1.5.1

I got an error when updating to latest version of the plugin

Call to undefined method WPGraphQL\Types::post_object()

![image](https://user-images.githubusercontent.com/37826165/125062689-42540c80-e0e1-11eb-827c-05e669c30539.png)

**Comment by jasonbahl** [comment]
@jmursuadev the `WPGraphQL\Types::post_object()` method was removed from the codebase in v0.6.0 in January 2020. 

It wasn't there in v1.2.5. Are you upgrading from `0.2.5`, perhaps?

My guess is that you have a plugin or custom code that was extending the Schema and needs to be updated?

**Comment by jmursuadev** [comment]
> @jmursuadev the `WPGraphQL\Types::post_object()` method was removed from the codebase in [v0.6.0](https://github.com/wp-graphql/wp-graphql/pull/1112) in January 2020.
> 
> It wasn't there in v1.2.5. Are you upgrading from `0.2.5`, perhaps?
> 
> My guess is that you have a plugin or custom code that was extending the Schema and needs to be updated?

Yes that's correct We have custom code on the theme.

**Comment by jasonbahl** [comment]
You will need to update to the latest APIs for extending the Schema. 

I would recommend checking the docs here to start:

https://www.wpgraphql.com/functions

If you're struggling with migrating old code to work with newer versions of WPGraphQL, paste some of the code you have and we can walk through what the upgrade path would be.

**Comment by jmursuadev** [comment]
> You will need to update to the latest APIs for extending the Schema.
> 
> I would recommend checking the docs here to start:
> 
> https://www.wpgraphql.com/functions
> 
> If you're struggling with migrating old code to work with newer versions of WPGraphQL, paste some of the code you have and we can walk through what the upgrade path would be.

Here's the sample code
 register_graphql_field('RootQuery', 'projectCategoryBy', [
        'type' => \WPGraphQL\Types::term_object('project_category'),
        'description' => __('Project category by slug', 'yd'),
        'args' => [
            'slug' => [
                'type' => \WPGraphQL\Types::string(),
            ],
        ],
        'resolve' => function ($root, $args, $context, $info) {
            $slug = isset($args['slug']) ? $args['slug'] : null;
            if (!$slug) {
                return null;
            }
            $term = get_term_by('slug', $slug, 'project_category');
            return $term ? $term : null;
        }
    ]);
    register_graphql_field('RootQuery', 'themePreview', [
        'type' => \WPGraphQL\Types::post_object('project_theme'),
        'description' => __('ProjectTheme preview by themeId', 'yd'),
        'args' => [
            'themeId' => [
                'type' => \WPGraphQL\Types::string(),
            ],
        ],
        'resolve' => function ($root, $args, $context, $info) {
            $themeId = isset($args['themeId']) ? $args['themeId'] : null;
            if (!$themeId) {
                return null;
            } else if (!is_user_logged_in()) {
                return null;
            }
            return get_post($themeId);
        }
    ]);

**Comment by jasonbahl** [comment]
@jmursuadev this should be a pretty quick update! 

Instead of `WPGraphQL\Types::string()` you can replace that with `'String'`

And instead of: `\WPGraphQL\Types::term_object('project_category')` you can replace that with `'ProjectCategory'`. 

Like so: 

```php
register_graphql_field('RootQuery', 'projectCategoryBy', [
        'type' => 'ProjectCategory',
        'description' => __('Project category by slug', 'yd'),
        'args' => [
            'slug' => [
                'type' => 'String',
            ],
        ],
        'resolve' => function ($root, $args, $context, $info) {
            $slug = isset($args['slug']) ? $args['slug'] : null;
            if (!$slug) {
                return null;
            }
            $term = get_term_by('slug', $slug, 'project_category');
            return $term ? $term : null;
        }
    ]);
    register_graphql_field('RootQuery', 'themePreview', [
        'type' => 'ProjectTheme',
        'description' => __('ProjectTheme preview by themeId', 'yd'),
        'args' => [
            'themeId' => [
                'type' => 'String',
            ],
        ],
        'resolve' => function ($root, $args, $context, $info) {
            $themeId = isset($args['themeId']) ? $args['themeId'] : null;
            if (!$themeId) {
                return null;
            } else if (!is_user_logged_in()) {
                return null;
            }
            return get_post($themeId);
        }
    ]);
```

**Comment by jasonbahl** [comment]
Also, in the resolvers, you'll want to pass the WordPress objects through the WPGraphQL Model layer, which does checks to make sure the user requesting the data has proper capabilities to see the data. 

So you can change that first resolver from: 

```php
'resolve' => function ($root, $args, $context, $info) {
            $slug = isset($args['slug']) ? $args['slug'] : null;
            if (!$slug) {
                return null;
            }
            $term = get_term_by('slug', $slug, 'project_category');
            return $term ? $term : null;
        }
```

to: 

```php
'resolve' => function ($root, $args, $context, $info) {
            $slug = isset($args['slug']) ? $args['slug'] : null;
            if (!$slug) {
                return null;
            }
            $term = get_term_by( 'slug', $slug, 'project_category' );
            return $term ? new \WPGraphQL\Model\Term( $term ) : null;
        }
```

And you could change that 2nd resolver to: 

```php
$post = get_post( $themeId );
return $post ? new \WPGraphQL\Model\Post( $post ) : null;
```

**Comment by jasonbahl** [comment]
@jmursuadev I'm going to close this issue as I don't believe there's an issue with the codebase that needs to be addressed. 

If you're having issues upgrading, I recommend joining the WPGraphQL Slack ([join here](https://join.slack.com/t/wp-graphql/shared_invite/zt-3vloo60z-PpJV2PFIwEathWDOxCTTLA)) where many folks can assist you with upgrading from older versions.
