### ISSUE TITLE
Widget Queries

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#20]
fwiw, here's where the REST API team ended up with Widget support: https://github.com/WP-API/wp-api-menus-widgets-endpoints

**Comment by jasonbahl** [comment]
Relevant Slack discussion here: https://wp-graphql.slack.com/archives/C3NM1M291/p1548183242930100

And thread here: https://wp-graphql.slack.com/archives/C3NM1M291/p1548184977978200

**Comment by jasonbahl** [comment]
Long story short, I think Widgets have a _lot_ more discussion to be had before we can support them in a meaningful way in WPGraphQL.

**Comment by itwasmattgregg** [comment]
Any movement on this?

**Comment by jasonbahl** [comment]
@itwasmattgregg I'm thinking this feature would probably be best explored as an extension plugin for now. 

I'm not sure where Widgets are going with Gutenberg, and the current state of Widgets don't lend to proper exposure to an API as there's no registry for fields that can be added to a widget. 

Ideal implementation would expose widgets with their fields, not the rendered HTML, because not all clients care about the rendered HTML. Most clients, I would argue, want the data that was input so they, the client, can handle the rendering in HTML, or React Native, or whatever other format their client needs to output. 

Because of the lack of a proper registry for all properties of widgets (fields, namely) it's difficult to expose to WPGraphQL in a very meaningful way. 

And Gutenberg taking over widgets complicates things further.

**Comment by itwasmattgregg** [comment]
I totally agree and that all makes sense. Thanks for the update.

**Comment by siddhantdante** [comment]
i am working on widgets. So that we can do drag and drop widgets to sidebar and can send whatever inside of widget on wpqraphql making a root query as 'getSidebar' doing this is will send all widgets data as in array widget-1, widget-2..... but couldn't figuring out howto query wp_options and making a custom query inwpgraphql.   any help or suggestion would be very helpful.  Thanks.

**Comment by jrmcdona** [comment]
Does this not help with this issue?   https://github.com/wp-graphql/wp-graphql/pull/485   Sorry I am new to WP Graph QL and WordPress in general but I am currently trying to rebuild my blog in React with WP Graph QL and trying to rebuild side bar widgets.

**Comment by jasonbahl** [comment]
Closing per discussion above: https://github.com/wp-graphql/wp-graphql/issues/20#issuecomment-554426933

If anyone is interested in creating an extension for this, you can probably use PR #485 as inspiration.

**Comment by idesignzone** [comment]
A good solution found here https://github.com/benada002/wp-graphql-widgets
