### ISSUE TITLE
Fix "return_statements" issue in src/Registry/TypeRegistry.php

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#2005]
Avoid too many `return` statements within this method.

https://codeclimate.com/github/wp-graphql/wp-graphql/src/Registry/TypeRegistry.php#issue_60edb10e6a95f700010001e0

**Comment by justlevine** [comment]
@jasonbahl I'm not seeing that particular code smell anymore. Is this still relevant?

**Comment by jasonbahl** [comment]
@justlevine we can close it. 💪🏻
