### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by mishushakov** [wp-graphql/wp-graphql#2030]
hello,
i'm building a new website using Gridsome and Wordpress with WPGraphQL and everything runs well, but unfortunately, i don't know php and can't contribute these features myself, so far i have only managed to hack them together in frontend

- Query theme settings, such as website favicon, theme colors
- Stripped HTML format for post excerpt and page content for text-version of posts and pages
- Query next and previous post relative to current post

**Comment by moonmeister** [comment]
next/previous related to #1133
