### ISSUE TITLE
Large plugin size due to bundled docs

### ISSUE THREAD

**Issue by mindctrl** [wp-graphql/wp-graphql#2034]
The plugin zip file is approximately 25MB when downloaded from wp.org. Unzipped the plugin folder is approximately 33MB. 23MB of that is in the `docs` folder, most of which is large images that aren't necessary for the plugin to run. As far as I can tell from a quick glance, these docs and images aren't exposed in the plugin UI anywhere.

Thoughts on excluding the docs folder from the zip and svn deploy?

**Comment by jasonbahl** [comment]
@mindctrl ah, yes, we should ignore that directory indeed. I believe we need to update the `.distignore` and `.gitattributes` files to exclude this directory from WordPress.org and Github respectively

**Comment by jasonbahl** [comment]
@mindctrl I got this updated and released as v1.5.8 and now the download from WordPress.org is 2.6mb

Thanks for bringing this up!
