### ISSUE TITLE
Querying Template names broken on v 1.6.0+

### ISSUE THREAD

**Issue by SeanMee86** [wp-graphql/wp-graphql#2046]
When querying for template name using `gatsby-source-wordpress` I get an error --> `"Abstract type \"WpContentTemplate\" was resolve to a type \"Wp*INSERT GENERIC TEMPLATE NAME*\" that does not exist inside schema."`

This has been tested on multiple sites, with and without auth, and OS's, Windows and Mac.

Query to reproduce:

`query MyQuery {
  allWpPage {
    edges {
      node {
        template {
          templateName
        }
      }
    }
  }
}`

Issue found with WPGraphQL 1.6.0 & 1.6.1. Issue resolved by rolling back to 1.5.5.  There is also an open issue on wordpress.org that is probably related. --> https://wordpress.org/support/topic/latest-update-1-6-1-is-broken/

P.S. This is my first time opening an issue on GitHub so if any advice for improvement is welcome.

**Comment by H-Nguyenx** [comment]
I encountered the same issue
`{"errors":[{"debugMessage":"Return value of GraphQL\\Type\\Schema::resolveType() must be an instance of GraphQL\\Type\\Definition\\Type, null returned","message":"Internal server error","extensions":{"category":"internal"},"locations":[{"line":8,"column":9}],"path":["__schema","types"]}],"extensions":{"debug":[]}}`

**Comment by jasonbahl** [comment]
@SeanMee86 thanks for this issue! 

I wonder if this is an issue with Gatsby Source WordPress. 

I'm able to query this in WPGraphQL directly using this query: 

```graphql{
  pages {
    nodes {
      template {
        templateName
      }
    }
  }
}
```

And get results like so: 

![Screen Shot 2021-08-02 at 10 48 13 AM](https://user-images.githubusercontent.com/1260765/127896246-3b656dad-2eac-4132-bda8-6f42f170a34d.png)

**Comment by jasonbahl** [comment]
@TylerBarnes any thoughts here? 

I think this _might_ come down to Gatsby needing to maybe do some extra work to get Types that are only exposed as ResolveTypes of Unions/Interfaces, but not exposed elsewhere in the Schema?

**Comment by jasonbahl** [comment]
I think this _might_ need to be moved to a Gatsby Source WordPress issue, as I believe Gatsby will need to adjust how it uses GraphQL Introspection to build the Schema on the Gatsby side.

**Comment by DanielRiveraHQ** [comment]
@jasonbahl You are right, this is a Gatsby Source Wordpress

**Comment by jasonbahl** [comment]
Gah!!!

@valikwork thanks for the details. Your comment helped me find the issue. I have a PR coming, and I think after talking with @TylerBarnes this actually is _not_ a Gatsby Source WordPress issue like I originally thought it might be. 

PR incoming.

**Comment by jasonbahl** [comment]
@valikwork @DanielRiveraHQ @H-Nguyenx @SeanMee86 can ya'll see if applying this one-line change in this PR (https://github.com/wp-graphql/wp-graphql/pull/2072) fixes things for you?

**Comment by valikwork** [comment]
@jasonbahl

**Comment by DanielRiveraHQ** [comment]
Seems to be working! Thank you @jasonbahl
