### ISSUE TITLE
[Bug] UserRoleConnectionResolver breaks `graphql_connection_query_args` filter.

### ISSUE THREAD

**Issue by justlevine** [wp-graphql/wp-graphql#2048]
When using `graphql_connection_query_args` filter, queries that rely on `UserRoleConnectionResolver.php ` throw a fatal error.
This is because the filter expects the first argument to be an array, however `UserRoleConnectionResolver.php::get_query_args()` returns `null`.

Unsure if the ideal solution is to have `get_query_args()` return an empty array instead of `null`, or to [change the docs](https://www.wpgraphql.com/filters/graphql_connection_query_args/) to `array | null $query_args`.

## Screenshot
![image](https://user-images.githubusercontent.com/29322304/127776693-bbc8ddcb-eb15-43cd-a9eb-fc2406a16a63.png)

## Steps to Reproduce.

1. Add the following code to functions.php:
```php
add_filter( 'graphql_connection_query_args', 'my_custom_filter', 10, 2 );
function my_custom_filter( array $query_args, \WPGraphQL\Data\Connection\AbstractConnectionResolver $resolver ){
	return $query_args;
}
```

2. Visit WPGraphiQL, and run the following query:
```graphql
{
  users {
    nodes {
      roles {
        nodes {
          displayName
          id
        }
      }
    }
  }
}
```

3.  See the following error in the response.
`Argument 1 passed to my_custom_filter() must be of the type array, null given, called in /incompetentstamp/wordpress/wp-includes/class-wp-hook.php on line 303`.

A working example can be seen at:
URL: https://incompetentstamp.tastewp.com
Username: admin
Password: -NkGNtlChIs

**Comment by jasonbahl** [comment]
@justlevine thanks for opening this issue! I've reproduced and have a PR on the way.
