### ISSUE TITLE
Missing pages after update

### ISSUE THREAD

**Issue by mishushakov** [wp-graphql/wp-graphql#2056]
I've noticed something unusual, my static site started missing pages after recent update of WpGraphQL, version 1.6.1

first my contact page was missing, but i was able to restore it after deleting and creating it from scratch
then my Posts page went missing

<img width="1680" alt="Screenshot 2021-08-04 at 15 36 33" src="https://user-images.githubusercontent.com/10400064/128190795-28735641-e8f5-4847-b17f-02093d7039d0.png">

<img width="1680" alt="Screenshot 2021-08-04 at 15 36 48" src="https://user-images.githubusercontent.com/10400064/128190871-7aa2ffa9-8771-4b62-9658-b9be36035a5b.png">

**Comment by jasonbahl** [comment]
Are you querying WPGraphQL directly or using something else like Gatsby?

If you're querying WPGraphQL directly, your query:

```graphql
{
  pages {
    nodes {
      slug
      title
    }
  }
}
```

Will only query 10 pages by default, and will query them ordered by date, by default. 

You can pass arguments to the query to query more items, and order them differently if needed. 

For example: 

```graphql
{
  pages(first:100) {
    nodes {
      slug
      title
    }
  }
}
```

Or: 

```graphql
{
  pages(first: 100, where: {orderby: {field: TITLE, order: ASC}}) { 
    nodes {
      slug
      title
    }
  }
}
```

I believe your pages were disappearing and re-appearing when you deleted and re-published because you're only asking for the default which is 10 items. So, deleting and re-publishing would add that page to the top of the list, as it's ordered by publish date by default, but that would also mean the last page on your list would be disappearing.

**Comment by jasonbahl** [comment]
I'm going to close this issue as I don't believe there's an issue with WPGraphQL that needs to be addressed here.

**Comment by mishushakov** [comment]
thanks for your help again, @jasonbahl 
is there any way to get all the pages or say a default setting so that it will always return all the pages/posts?

**Comment by jasonbahl** [comment]
The query arguments are there so the client can ask for how many the client wants. The server always has the right to return fewer than asked for whatever the server determines safe/responsible. 

It's best practice to structure your queries to support pagination if you want to get all records. 

You can read more about pagination in WPGraphQL here: https://www.wpgraphql.com/2020/03/26/forward-and-backward-pagination-with-wpgraphql/

----

That said, if you _really_ feel like the best option is to have your server return more records by default, you can. 

Just move forward here at your own risk. Querying and Returning too many records can cause performance issues and sometimes even tank a WordPress server and make it unresponsive, so proceed carefully.

You can set the default with a filter like so: 

```php
add_filter( 'graphql_connection_amount_requested', function( $amount, $connection_resolver ) {

  // If the query doesn't specify a first or last argument, default to 1000
  if ( ! isset( $connection_resolver->args['first'] && ! isset( $connection_resolver->args['last'] ) {
    $amount = 1000;
  }

  return $amount;

} );
```

There's also a max amount the server sets to help prevent your server from melting (returning _everything_ is usually not a good idea). 

So you'd also need to filter that: 

```php
// Set the max amount of items to return per connection to 1000 (do at your own risk!!)
add_filter( 'graphql_connection_max_query_amount', function( $max_amount ) {
  return 1000;
} );
```
