### ISSUE TITLE
How to update featuredImage sourceUrl in graphql_resolve_field?

### ISSUE THREAD

**Issue by 8ctopotamus** [wp-graphql/wp-graphql#2070]
We are using a CDN in our Wordpress site and would like to replace the site URL with the Image CDN's URL in our graphql output. The plugin takes care of replacing the media URLs in the `content`, but it does not affect the output of the featuredImage's sourceUrl.

The sourceUrl is nested in the featuredImage node. I have been trying to modify the $result's properties, but to no avail! Any guidance as to how update a node's field would be much appreciated!

![image](https://user-images.githubusercontent.com/17594101/129229537-8d4466b4-14be-4336-b3b8-0e91146e8cac.png)

```
add_filter( 'graphql_resolve_field', function( 
	$result, 
	$source, 
	$args, 
	$context, 
	$info, 
	$type_name, 
	$field_key, 
	$field, 
	$field_resolver 
) {
   if ( 'featuredImage' === $field_key ) {
                // not working :(
		// $result->node->fields->sourceUrl = 'https://example.com';
		// $result->sourceUrl = 'https://example.com';
		// graphql_debug($result);
    }
    return $result;

}, 10, 9 );
```

**Comment by jasonbahl** [comment]
@8ctopotamus hey!

So the filter in your example is trying to filter the `featuredImage` field: 

`if ( 'featuredImage' === $field_key ) {`

but if you want to filter `sourceUrl` you would need to change it to: 

`if ( 'sourceUrl' === $field_key ) {`

And when filtering the `sourceUrl` field, the `$source` variable would be an instance of the MediaItem `Post` Model that gets passed down to that resolver. 

We can use `graphql_debug()` like you were, to see the `$source` being passed down: 

```php
add_filter( 'graphql_resolve_field', function( $result, $source, $args, $context, $info, $type_name, $field_key, $field, $field_resolver  ) {
	if ( 'sourceUrl' === $field_key ) {
		graphql_debug( $source );
	}
	return $result;
}, 10, 9 );
```

![Screen Shot 2021-08-13 at 12 35 08 PM](https://user-images.githubusercontent.com/1260765/129404059-c6523a98-2274-4f88-85e9-9a484e5e099a.png)

And now we can override the results like so: 

```php
add_filter( 'graphql_resolve_field', function( $result, $source, $args, $context, $info, $type_name, $field_key, $field, $field_resolver  ) {
	if ( 'sourceUrl' === $field_key ) {
		return 'testing...';
	}
	return $result;
}, 10, 9 );
```

And see that this field is now filtered: 

![Screen Shot 2021-08-13 at 12 35 39 PM](https://user-images.githubusercontent.com/1260765/129404214-0afb8488-606d-4cb5-8932-e666572a083e.png)

**Comment by 8ctopotamus** [comment]
Amazing, @jasonbahl. Thank you for the explanation and examples!  👍 🙏
