### ISSUE TITLE
Quering Page's Template Name (gatsby-source-graphql) Returns Error If Template Isn't "Default"

### ISSUE THREAD

**Issue by valikwork** [wp-graphql/wp-graphql#2071]
Recently I have an issue with gatsby-source-graphql package, when quering pages templateNames from my app. Same query in WPGraphiQL works fine.

This query
`pages(first: 5000) { nodes { id uri template { templateName } } }`
returns **null** in "template" field for every page, that has template picked as something other then "Default".

I.e. if page has "New Home Page" template, query breaks with message ""Abstract type "WPGraphQL_ContentTemplate" was resolve to a type "Template_NewHomePage" that does not exist inside schema.""

Haven't had this issue ever before.
Any suggestions to how to solve it or where to look.

Versions:
WPGraphQL - 1.6.2
WPGraphQL for Advanced Custom Fields - 0.5.3
"gatsby": "^3.11.1",
"gatsby-source-graphql": "^3.11.0",

Thanks!

**Comment by rossluebe** [comment]
@valikwork Oddly enough, I'm bumping into a similar issue right now. Assuming you solved it what was causing the issue for you?

**Comment by valikwork** [comment]
@rossluebe 
It was solved here:
[https://github.com/wp-graphql/wp-graphql/issues/2046](https://github.com/wp-graphql/wp-graphql/issues/2046)
