### ISSUE TITLE
NO SCHEMA AVAILABLE in GraphiQL version 1.6.3 IDE explorer when Webstories is activated

### ISSUE THREAD

**Issue by igorluiza4d** [wp-graphql/wp-graphql#2075]
When the Webstories plugin is active, the error below occurs
I tested this by disabling this plugin and the explorer works as expected.

Console error is noted here:
Uncaught (in promise) Error: Invalid or incomplete introspection result. Ensure that you are passing "data" property of introspection response and no "errors" was returned alongside: undefined

**Comment by benknight** [comment]
I'm having the same issue.

**Comment by igorluiza4d** [comment]
Thank's @TorinAsakura .... I did a test and installed the version you said and it really worked.

**Comment by igorluiza4d** [comment]
@bhardie and @jasonbahl ,

I don't know if it helps, but I did the test on possible versions and started giving this error after version 1.5.9.

Version 1.5.9 works normally, in my case, with Google's Web Stories Plugin.

**Comment by TorinAsakura** [comment]
Tested on latest version with WP latest version - all working

**Comment by justlevine** [comment]
> Tested on latest version with WP latest version - all working

@igorluiza4d if you update WP and WPGraphQL to latest is it fixed for you?

**Comment by igorluiza4d** [comment]
@justlevine . I tested it here and it really works again. Thank you!
