### ISSUE TITLE
Querying menus / menu items by unset location returns ALL menu items

### ISSUE THREAD

**Issue by ravewebdev** [wp-graphql/wp-graphql#2084]
### Expected

When querying `menus` or `menuItems` using `where: {location: <LOCATION>}`, if the location selected does not currently have a menu assigned to it, those queries should return an empty array or null.

### Actual

The queries currently return _all_ records: all menus for `menus` query and all menu items for `menuItems` query.

Tested using the following query:

```
query getMenus {
  menuItems(where: {location: FOOTER}) {
    nodes {
      label
      locations
    }
  }
  menus(where: {location: FOOTER}) {
    nodes {
      name
      locations
    }
  }
}
```

...where the menu location "Footer" does not have a menu assigned to it. If a menu is assigned to that location, the query will work as expected (returning records relevant to the "Footer" menu).

Originally noted in https://github.com/wpengine/atlas-starter/issues/290

Running WP GraphQL v1.6.4.

**Comment by dam6pl** [comment]
@jasonbahl are you going to solve this problem?

**Comment by justlevine** [comment]
@dam6pl I'm working on a PR now.

It seems that as of v1.7.2 (if not earlier), the issue is only for `menus` and not `menuItems`.  Can you confirm `menuItems` currently works as expected?

**Comment by dam6pl** [comment]
@justlevine thanks! Yes, I checked on my instance (v1.6.12), and the `menuItems` resource is empty when nothing is added.
