### ISSUE TITLE
`asPreview` does not resolve preview data for queries using `URI` as the `idType`

### ISSUE THREAD

**Issue by blakewilson** [wp-graphql/wp-graphql#2091]
When querying for page/post preview data with `asPreview` set to `true` and the `idType` is of type `URI`, preview data is not returned as expected.

Take the following query:

```
query MyQuery {
  page(id: "/new-page", idType: URI, asPreview: true) {
    id
    databaseId
    content
    isPreview
  }
}

```

It appears the issue is being encountered here:
https://github.com/wp-graphql/wp-graphql/blob/develop/src/Type/ObjectType/RootQuery.php#L177

When the `$idType` in the resolve function is `uri`, it returns early. Whereas when the `idType` is `database_id` or `global_id`, additional logic is encountered when the `asPreview` argument exists.

Current behavior:
Queries Page/Post with `asPreview` set to `true` and `idType` set to `URI` will result in no preview data being displayed.

Expected behavior
Queries Page/Post with `asPreview` set to `true` and `idType` set to `URI` will result in preview data being displayed.

**Comment by josephfusco** [comment]
Note that `post_name` (used for the WordPress URI) will always be empty when a post is saved as pending or draft, unless

- the post URI was explicitly set in it's unpublished state
- the post was previously published

**Comment by justiny** [comment]
I'm experiencing the same issue.  

This returns null.

```
query NewQuery {
  post(id: "123", idType: DATABASE_ID, asPreview: true) {
    preview {
      node {
        title
      }
    }
  }
}
```

**Comment by bhardie** [comment]
This is a likely duplicate of #1673

**Comment by blakewilson** [comment]
@bhardie Yep, seems to be

**Comment by justlevine** [comment]
Closing in favor of #1673
