### ISSUE TITLE
Query children on any custom post type

### ISSUE THREAD

**Issue by ltroya-as** [wp-graphql/wp-graphql#2092]
I was wondering if there is a way to query children of any custom post type. Right, we can query pages with its children like this:

```
{
  pages {
    nodes {
      slug
      uri
      children {
        nodes {
          slug
          uri
        }
      }
    }
  }
}
```
Since pages are post types, is there some way to use the same query for any post type? For example, for posts like this:

```
{
  posts {
    nodes {
      slug
      uri
      children {
        nodes {
          slug
          uri
        }
      }
    }
  }
}
```

I am using the download monitor plugin and it handles two CPT: `dlm_download` and `dlm_download_version`

- `dlm_download` is the CPT
- `dlm_download_version` is a child CPT where the file info is managed

The query above will allow me to get all `dlm_download` posts and show all the files attached to that parent.

**Comment by jasonbahl** [comment]
WordPress core doesn't support the ability to define what post_types can be children of other post types. So, WPGraphQL exposes a `children` connection on hierarchical post types and returns a connection of the `ContentNode` type (which is posts of any post type). 

So, on any hierarchical post type, you can query the `children` field as a connection, and any child, regardless of post_type, can be returned in that connection. 

For example, I created a page with ID 35 titled "Parent"

Then, I created a post in the post_type "book" titled "Book" which had id of 39. 

I then had to go directly to the database and set the `post_parent` of post 39 as `35`. 

This created a parent/child relationship where: 

- **parent**: page, id 35
- **child**: book, id 39

I could then query like so: 

```graphql
{
  pages(where: {parent: 0}) {
    nodes {
      __typename
      id
      title
      children {
        nodes {
          id
          ... on NodeWithTitle {
            title
          }
          databaseId
        }
      }
    }
  }
}
```

And I get results: 

```json
{
  "data": {
    "pages": {
      "nodes": [
        {
          "__typename": "Page",
          "id": "cG9zdDozNQ==",
          "title": "Parent",
          "children": {
            "nodes": [
              {
                "id": "cG9zdDozOQ==",
                "databaseId": 39
              },
              {
                "id": "cG9zdDozNw==",
                "title": "Child",
                "databaseId": 37
              }
            ]
          }
        },
        }
      ]
    }
  },
}
```

Here, we can see that I can query for child objects of other post types using GraphQL. 

The trick, is that WordPress doesn't provide any native User Interfaces for setting these types of relationships. 

If your plugin let's you set parent/child relationships across post_types, you should be able to query this data like shown above. 

## Custom Connections
If you prefer to have a specific connection for the relationship between post types, for example, `Download -> Download Version` connection, you might want to use the `register_graphql_connection()` API directly and expose this connection to the Schema.

see: https://www.wpgraphql.com/functions/register_graphql_connection/
