### ISSUE TITLE
resetUserPassword returns null sometimes

### ISSUE THREAD

**Issue by web-programmer-here** [wp-graphql/wp-graphql#2100]
I am trying to use `resetUserPassword` mutation and sometimes it returns null when trying the update the password for the user. So something like this: 

```graphql
mutation RESET_USER_PASSWORD {
  resetUserPassword(input: {
    key: "n4hyZzDW9Of4zbTs",
    login: "user@user.com",
    password: "123456"
  }) {
    user {
      id
    }
  }
}
```

and I get this in response 

```
{
    "data": {
        "resetUserPassword": {
            "user": null
        }
    },
    "extensions": {
        "debug": [
            {
                "type": "DEBUG_LOGS_INACTIVE",
                "message": "GraphQL Debug logging is not active. To see debug logs, GRAPHQL_DEBUG must be enabled."
            }
        ]
    }
}
```

however, the password actually changes, and I get the email that the password has been changed but returned data is null. I am also facing same issue with `sendPasswordResetEmail` where the email is sent but the response is null. Any idea why this is happening?

**Comment by web-programmer-here** [comment]
I noticed I dont see this issue when running this query in GraphQL IDE, here is a postman screenshot: 

<img width="906" alt="image" src="https://user-images.githubusercontent.com/81479051/133913638-3de85c3e-e8cc-4d7e-8571-562d38309963.png">

and here is another password reset using IDE: 

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/81479051/133913678-025d85a6-9158-4a96-8a7c-44c594ec9423.png">

so when using the IDE, we dont face this issue (as far as I know when testing) - is there some settings I have to change?

**Comment by jasonbahl** [comment]
@web-programmer-here The reason the response is `null` when you run the mutation outside of the IDE is because the request is not authenticated and the current user object cannot be returned in the payload. 

When executing in the GraphQL IDE in WordPress, the GraphQL request is authenticated, so the current user is returned.

**Comment by web-programmer-here** [comment]
@jasonbahl but the password gets updated, it just returns null for the response, there is no way to fix this?

**Comment by grazianodev** [comment]
+1 for this. I usually rely on looking at the data in the response to verify that the query/mutation worked as expected, so if the `sendPasswordResetEmail` and `resetUserPassword` mutations could return the user object even if not authenticated, or even just a flag such as `resetEmailSuccess` and `passwordResetSuccess` would be nice.

**Comment by justlevine** [comment]
@grazianodev 
> if the `sendPasswordResetEmail` and `resetUserPassword` mutations could return the user object even if not authenticated, or even just a flag such as `resetEmailSuccess` and `passwordResetSuccess` would be nice.

I would suggest continuing to **not return** anything on `sendPasswordResetEmail` so it cant be abused by malicious actors trying to verify if a username is valid.

@jasonbahl 
> The reason the response is `null` when you run the mutation outside of the IDE is because the request is not authenticated and the current user object cannot be returned in the payload.

I believe we can nevertheless try to return the user object for `resetUserPassword`, since if they're getting any response that isnt an error, that means they successfully authenticated with the `login` + `key` + new `password`. Or am I being shortsighted?

**Comment by justlevine** [comment]
For the above reason I think the simplest way to implement this would be to just `wp_set_current_user( $user );` [after the password is successfully reset](https://github.com/wp-graphql/wp-graphql/blob/b89a31fd35e619b65b5dd85acaac182ed6fd61c5/src/Mutation/ResetUserPassword.php#L102).

**Comment by justlevine** [comment]
Was easy enough to throw together a PR with this approach (#2505), but @jasonbahl still needs to decide if this way is best.

**Comment by justlevine** [comment]
#2505 adds the user to `resetUserPassword`, but we need a decision on `sendPasswordResetEmail` to proceed.

**Comment by jasonbahl** [comment]
@justlevine i think the change makes sense. If the user has gotten to that point, they've verified they are who they say they are.

**Comment by justlevine** [comment]
@jasonbahl for `sendPasswordResetEmail` no validation is required. We def should _not_ return the user in that case. 
Where I'm more hesitant is whether to add a flag for success, as I can see the benefit, but I also worry about the potential for abuse (eg checking a user exists before logging in with a leaked lassword db)

**Comment by jasonbahl** [comment]
got my wires crossed. 

Yes, I actually think perhaps the way to go here would be to deprecate the `user` field on the output (https://github.com/wp-graphql/wp-graphql/blob/develop/src/Mutation/SendPasswordResetEmail.php#L33), and introduce another field to indicate that the mutation succeeded.

**Comment by jasonbahl** [comment]
so instead of something like: 

```graphql
mutation {
  sendPasswordResetEmail(input: {username: "admin"}) {
    user {
      name
    }
  }
}
```

the mutation could instead be something like: 

```graphql
mutation {
  sendPasswordResetEmail(input: {username: "admin"}) {
    emailSent
  }
}
```

where `emailSent` is a boolean field.

**Comment by justlevine** [comment]
So my question is whether we even want `emailSent` to be returned, or a just generic `isSuccess` that doesn't expose whether the username/email is valid, but just that the mutation didn't throw any errors.

**Comment by jasonbahl** [comment]
🤔 

Ya, that's a good point. Right now, the logic will expose if a username is _not_ valid: https://github.com/wp-graphql/wp-graphql/blob/develop/src/Mutation/SendPasswordResetEmail.php#L128

And not getting that error will indicate that the username _is_ valid. 

It probably makes sense to have a generic field like `isMutationComplete` that we can return `true`, even if the underyling logic decided _not_ to send the email. 

Some of these `UserError` messages should maybe be converted go `graphql_debug()` messages so developers can find what's going on when GRAPHQL_DEBUG mode is enabled, but we're not leaking things like users exist or not 🤔 

For example: https://github.com/wp-graphql/wp-graphql/blob/develop/src/Mutation/SendPasswordResetEmail.php#L45-L47

We could change this to: 

```php
if ( ! $user_data ) {
  graphql_debug( self::get_user_not_found_error_message( $input['username'] ) );
  
  return [
    'isMutationComplete' => true
  ];
}
```

**Comment by jasonbahl** [comment]
We could also continue to throw errors, but make the message more generic if not in GRAPHQL_DEBUG mode

like: `sendPasswordReset Mutation failed`. 

That way it's masked _why_ it failed. Doesn't expose that the username is or is not valid, just that the mutation could not complete.
