### ISSUE TITLE
Is there any hooks or filter for RegisterUser mutation?

### ISSUE THREAD

**Issue by web-programmer-here** [wp-graphql/wp-graphql#2101]
Is there any hooks or filter for `RegisterUser` mutation to prevent weak passwords or certain usernames? there are many plugins out there but none of them work to prevent user registration with weak password using `RegisterUser` mutation.

**Comment by web-programmer-here** [comment]
I tried this but doesnt work

```php
function check_pass($login, $email, $errors) {
    if ( strlen( $_POST['password'] ) < 6 ) {
        $errors->add( 'password_too_short', "Passwords must be at least six characters long";
    }
}
add_action( 'register_post', 'check_pass', 10, 3 );
```

**Comment by justlevine** [comment]
Hey @web-programmer-here,

If you're looking for a WPGraphQL specific filter, you can use [`graphql_user_insert_post_args`](https://www.wpgraphql.com/filters/graphql_user_insert_post_args/), to throw a `UserError`.

For example:

```php
function graphql_enforce_password_strength_on_register_user( array $user_args, array $input, string $mutation_name ) : array {
  // Only enforce when registering, not updating.
  if( 'registerUser' !== $mutation_name ){
    return $user_args;
  }

  
  // Throw GraphQL error if password is too short.
  if ( isset( $user_args['user_pass'] ) && strlen( $user_args['user_pass'] ) < 6 ) {
    throw new \GraphQL\Error\UserError( __( 'Passwords must be at least six characters long.', 'my-text-domain' ) );
  }
  
  return $user_args;
}
add_filter( 'graphql_user_insert_post_args', 'graphql_enforce_password_strength_on_register_user', 10, 3 );
```

I'm going to close this issue for now, but if you're running into any trouble with the `graphql_user_insert_post_args` filter, please comment here and I'll reopen 😎
