### ISSUE TITLE
my queries not working after install plugin WPGraphQL WPML

### ISSUE THREAD

**Issue by FatmaMahmoud698** [wp-graphql/wp-graphql#2110]
I want to make queries on custom post type ui  so I install plugin WPGraphQL WPML
but I get this error in all queries for postman testing
![postman1](https://user-images.githubusercontent.com/75572871/135488067-27cf987e-8e1f-4eef-b161-34ffc80fc2c1.PNG)

**Comment by jasonbahl** [comment]
Closing as I believe https://github.com/wp-graphql/wp-graphql/issues/1626#issue-769089073 contains the solution
