### ISSUE TITLE
wp-graphql vulnerabilities

### ISSUE THREAD

**Issue by ilibilibom** [wp-graphql/wp-graphql#2113]
Hi
I'm having some vulnerability issues with wp-graphql yarn.lock file.
This is the vulnerability report I'm getting from Dependabot:

![image (7)](https://user-images.githubusercontent.com/12745414/136380719-2d35fa74-4100-4568-8616-0887da69018d.png)

I'm using the latest version of the plugin.
I can't go live with these vulnerabilities, any idea how do I solve this ?

**Comment by alexghirelli** [comment]
Opened a PR #2115 that can fix this.

**Comment by ilibilibom** [comment]
Thanks @alexghirelli!
Hopefully this can be merged sooner that later.
