### ISSUE TITLE
allItems in addition to connections?

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#212]
Right now most relationships are handled via connections, which is great. But sometimes you just want a list of allItems without the edge/node shape and no need for pagination. 

For example:

posts { allAuthors{ name, email } } vs posts{ authors{ edges{ node{ name, email } } } }

Or

posts{ allTags{ id, name } } vs posts { tags{ edges{ node{ is, name } } } }

**Comment by CodeProKid** [comment]
Hmmm, yeah this is an interesting concept. I definitely see how this could be useful. I'm curious how we could apply this across types without too much work. We should talk about this some more.

**Comment by jasonbahl** [comment]
The more I’ve used the edge/node shape, the more I actually like it and it really makes sense, _especially_ when there is actual edge data...for example “comment_author_ip” which is being worked on now...that’s edge data. It’s the IP of the author in connection to the comment. Comments don’t have IP addresses, users do...but it’s not a propert of the user as the user can comment from any device/location, so that’s a property that lives on the edge of a specific comment/author connection. 

I think we’ll be able to take advantage of the “edges” more if we keep our eyes open for it. 

So, I think at the moment I would lean toward suggesting that adding something like this is plugin territory where folks can filter it into their schema as needed for their app. 

I’m down to discuss more though.

**Comment by jasonbahl** [comment]
@CodeProKid so this is actually treading 2 different issues. . .one is getting items without the extra `edge` part of the query, and the other is getting `all` items (as in not having to paginate through sets of data). 

I think #248 addresses the first part, and I think that providing `all` items of a connection without limits should be up to the particular system if they have a need for it and feel like they could provide `all` items without limits. . .

I think we can probably close this now that #248 is out there. . .if anyone has a compelling argument we can re-open
