### ISSUE TITLE
WP-GraphQL is returning HTML instead JSON

### ISSUE THREAD

**Issue by RodrigoTomeES** [wp-graphql/wp-graphql#2129]
## To reproduce
Select a product

## What should be obtained
A JSON with the product

## Actual behavior
JSON.parse: unexpected character at line 1 column 1 of the JSON data

![imagen](https://user-images.githubusercontent.com/13077343/138148998-03a23656-eabe-4f43-9e81-1b931bfe29da.png)
![imagen](https://user-images.githubusercontent.com/13077343/138149068-cf7b7c74-3345-4d68-a3e7-bba136775883.png)

## Plataform
 - Wordpress: 5.8.1
 - Linux 3.10.0-693.17.1.el7.x86_64 x86_64
 - Apache
 - PHP version: 7.3.31
 - BD: mysqli 5.5.65-MariaDB

## Plugins
- Add WPGraphQL SEO | Versión 4.15.0 por Ash Hitchcock (Última versión: 4.16.0)
- Admin Columns | Versión 4.3.2 por AdminColumns.com (Última versión: 4.4.1)
- Advanced Custom Fields PRO | Versión 5.9.8 por Delicious Brains (Última versión: 5.10.2)
- Ajax Cart AutoUpdate for WooCommerce | Versión 1.5.5 por taisho
- All-in-One WP Migration | Versión 7.47 por ServMask (Última versión: 7.49)
- Bulk Edit Products, Prices & Attributes for Woocommerce | Versión 1.0.3 por ELEX
- CDN Enabler | Versión 1.0.9 por KeyCDN (Última versión: 2.0.4)
- Contact Form 7 | Versión 5.4.2 por Takayuki Miyoshi (Última versión: 5.5.1)
- Contact Form CFDB7 | Versión 1.2.5.9 por Arshid
- Easy WP SMTP | Versión 1.4.7 por wpecommerce, alexanderfoxc
- Multi-Step Checkout for WooCommerce (Pro) | Versión 1.1.7 por ThemeHigh (Última versión: 2.0.1)
- Multiple Addresses for Woocommerce | Versión 1.0.9 por ThemeHigh (Última versión: 2.0.0)
- Permalink Manager Pro \|  VestaThemes.com | Versión 2.2.1.4 por Maciej Bis (Última versión: 2.2.13)
- Preview E-mails for WooCommerce | Versión 1.6.8 por Digamber Pradhan
- PW Woocommerce Advanced Gift Rules | Versión 4.7 por Proword
- Qty Increment Buttons for WooCommerce | Versión 2.7.5 por taisho
- Redirection | Versión 5.1.3 por John Godley
- Repeat Order for Woocommerce | Versión 1.2.0 por polyres
- Safe SVG | Versión 1.9.9 por Daryll Doyle
- Variation Swatches for WooCommerce | Versión 1.1.18 por Emran Ahmed (Última versión: 1.1.19)
- WooCommerce | Versión 5.5.2 por Automattic (Última versión: 5.8.0)
- Woocommerce Add to cart Ajax for variable products | Versión 2.2 por Rishi Mehta - Rcreators Websolutions
- WooCommerce Bookings | Versión 1.10.8 por Automattic
- WooCommerce Checkout Field Editor Pro | Versión 2.6.6 por ThemeHiGH
- WooCommerce Stripe Gateway | Versión 5.4.1 por WooCommerce (Última versión: 5.6.2)
- WooCommerce Subscriptions | Versión 3.0.1 por WooCommerce
- Woo Discount Rules | Versión 2.3.7 por Flycart
- Woo Discount Rules PRO 2.0 | Versión 2.3.7 por Flycart
- WooGraphQL Subscriptions | Versión 0.0.1 por kidunot89
- WP GraphQL | Versión 1.6.6 por WPGraphQL
- WPGraphQL for Advanced Custom Fields | Versión 0.4.1 por WPGraphQL, Jason Bahl
- WPGraphQL JWT Authentication | Versión 0.4.0 por WPGraphQL, Jason Bahl
- WPGraphQL WooCommerce (WooGraphQL) | Versión 0.10.4 por kidunot89
- WPML Multilingual CMS | Versión 4.3.12 por OnTheGoSystems
- WPML String Translation | Versión 3.0.9 por OnTheGoSystems
- WPML Translation Management | Versión 2.9.6 por OnTheGoSystems
- Yoast SEO | Versión 17.0 por Team Yoast (Última versión: 17.4)

**Comment by millette** [comment]
Link: <https://github.com/rburgst/wp-graphql-wpml>

More info: <https://www.wpgraphql.com/extenstion-plugins/wpgraphql-wpml/>
