### ISSUE TITLE
Respect `publicly_queryable` setting for post types

### ISSUE THREAD

**Issue by kellenmace** [wp-graphql/wp-graphql#2134]
Currently, if a post type in WordPress has `publicly_queryable` set to `false`, its posts are still accessible to unauthenticated users. WPGraphQL should respect the `publicly_queryable` setting.

It's easy to conflate `publicly_queryable` with `public` and/or `show_in_graphql` settings. Here is the breakdown that @jasonbahl and I came up with for remembering what effect each setting has:

- `show_in_graphql` —> add to GraphQL schema
- `public` —> Give this a URI
- `publicly_queryable` —> accessible to all unauthenticated users

I'll submit a PR so that a post is considered private if `publicly_queryable` is set to `true` (whether explicitly, or implicitly by inheriting the `public => true` value for the post type).

## End Result

So the end result of this change should be this behavior:

- If `publicly_queryable` is `true` for a post type, its posts should be accessible to unauthenticated users.
- If `publicly_queryable` is `false` for a post type, its posts should be accessible only to authenticated users who have the required capability.

**Comment by jasonbahl** [comment]
@kellenmace It's possible for a post_type to be set as:

```php
[
  'public' => true,
  'publicly_queryable' => false
]
```

This is the case with the Page post_type as registered in WordPress core: https://github.com/WordPress/WordPress/blob/8447683474ebdee773fc4fca7b3e44dea45060f4/wp-includes/post.php#L45-L68

I think we should have a minor adjustment to the rules. 

If a post_type is set to public, then publicly queryable shouldn't matter. The entity is already accessible via URL and public, so GraphQL should respect that. 

If public is set to false, then WPGraphQL should look to see if the post_type is publicly queryable. 

A non-public  post type (one with no public URL for each entry) can still be publicly queryable even if `public => false`. 
 
So, I think the rules should be: 

`public=true, publicly_queryable=true`: content is publicly queryable in GraphQL
`public=false, publicly_queryable=true`: content is publicly queryable in GraphQL
`public=true, publicly_queryable=false`: content is publicly queryable in GraphQL
`public=false, publicly_queryable=false`: content is private / not publicly queryable in GraphQL
