### ISSUE TITLE
Advanced Custom Fields Support

### ISSUE THREAD

**Issue by ads1018** [wp-graphql/wp-graphql#214]
How would I go about quering advanced custom field data attached to a post?

**Comment by ads1018** [comment]
ah I've just stumbled on the acf repo: https://github.com/wp-graphql/wp-graphql-acf

**Comment by jasonbahl** [comment]
@ads1018 we've started an ACF plugin (super-beta, not ready for use: https://github.com/wp-graphql/wp-graphql-acf), but you can check it out to get ideas on how you could filter in support for your app. 

One quick example to get you started (off the top of my head, might need some adjusting): 

```
add_filter( 'graphql_post_fields', function( $fields ) {
   $fields['myCustomField'] => [
        'type' => \WPGraphQL\Types::string(),
        'resolve' => function( $post ) {
              $field = get_field( 'your_acf_field', $post->ID );
              return ! empty( $field ) ? $field : null; 
        },
    ];
} );
```

**Comment by jasonbahl** [comment]
@ads1018 if you're interested in contributing to the ACF plugin, that would be sweet! but if you just want to add some quick fields, I'd suggest just filtering them in for now. . .not sure when I'll have more time to work on that as I don't use ACF at my day job, so it's not as high of a priority to work on at the moment.

**Comment by ads1018** [comment]
ah gotcha. Thanks!

**Comment by cr101** [comment]
@ads1018 You might also want to look at [graphql-wp](https://github.com/tim-field/graphql-wp) which allows you to add custom post types ( which have custom fields ) without having to use an add-on.

**Comment by towfiqi** [comment]
I am using ACF and you dont need any special support for it. just register you custom fields like this:

```
add_filter( 'graphql_post_fields', function( $fields ) {
    $fields['downloads'] = [
      'type' => \WPGraphQL\Types::string(),
      'description' => __( 'The Downloads field of the post', 'xxx' ),
      'resolve' => function( \WP_Post $post, array $args, $context, $info ) {
          $downloads = get_post_meta( $post->ID, 'downloads', true );
          return ( ! empty( $downloads ) && is_string( $downloads ) ) ? $downloads : null;
      }];
} );
```

**Comment by cr101** [comment]
@towfiqi I'm using ACF as well and I have two CPTs (Companies and Addresses) which use a two-way field (com_addr) to create a bidirectional relationship between the two CPTs.

I'm trying to figure out how to connect the two CPTs so I can do a query like below:
```
{
  companyBy(slug: "com-slug") {
    companyId
    content
    excerpt
    Address {
      edges {
        node {
          addressId
          streetName1
          streeName2
          city
        }
      }
    }
  }
}
```
Is there any example on how to do this?

**Comment by towfiqi** [comment]
Sorry, not sure how you can achieve that. Maybe @jasonbahl can help.

**Comment by nikosolihin** [comment]
@cr101  If you're talking about the Post Object field, you can do the following to the Company CPT, of course after registering the Address CPT beforehand:

```
add_action( 'graphql_company_fields', function( $fields ) {
$fields['address'] = [
    'type' => \WPGraphQL\Types::list_of(\WPGraphQL\Types::post_object('address')),
    'resolve' => function( \WP_Post $post ) {
      $arr = array();
      $addresses = get_post_meta( $post->ID, 'address', true );
      foreach ($addresses as $address) { 
        $post = get_post( absint( $address ) );
        array_push($arr, $post);
      }
      return $arr;
    },
  ];
  return $fields;
} );
```

**Comment by cwahlfeldt** [comment]
Any updates on support for ACF fields?

**Comment by nobrefelipe** [comment]
Anyone managed to add support for the repeater custom field? Thanks!

**Comment by izzygld** [comment]
@nobrefelipe yes!
take a look here: [https://gist.github.com/izzygld/df0445396ca708ec53296cfcdf30ba0a](https://gist.github.com/izzygld/df0445396ca708ec53296cfcdf30ba0a) 

Took sometime to get it working. but perseverance paid!

**Comment by nobrefelipe** [comment]
@izzygld 
Thank you!!!!
I wasn't managing to get the fields using `get_post_meta` 
so I just and up using ACF's `get_field('field-name', $post->ID)`

**Comment by dsabatier** [comment]
@izzygld @nobrefelipe I am also trying to get acf repeater fields working, maybe you can help me out? I tried using the gist above as reference but still running into issues (WP and php are not tools I use regularly :( ).

Here is an example value I get out the API currently and a screenshot of my repeater field:
`

sessions |  
-- | --
[0] |  
uid | "594afece726c4"
day | "20190728"
start_time | "12:00"
end_time | "13:00"
map_space | {…}
followed | "0"
[1] |  
uid | "594afece726c4"
day | "20190728"
start_time | "12:00"
end_time | "13:00"
map_space | {…}
followed | "0"
`
![screen shot 2018-06-28 at 2 50 12 pm](https://user-images.githubusercontent.com/16840628/42060118-f9fe3da0-7ae2-11e8-8eff-498c5b472466.png)

And the code I have been clumsily slapping at, sorry for the weird formatting and variable names:

```
add_action('graphql_exhibit_fields', function($fields) {

        $statsType = new ObjectType([
        'name' => 'Session',
        'description' => __( 'One session row', 'your-textdomain' ),
        'fields' => [
             'uid' => [
                              'type' => \WPGraphQL\Types::string(),
                        ]
        	]
        ]);

        $fields[ 'sessions' ] = [
        'type' => Type::listOf($statsType),
        'description' => __( 'Sessions field in GraphQL', 'your-textdomain' ),
        'resolve' => function( \WP_Post $post ) {
            $fp_metabox_process_group = get_post_meta( $post->ID, 'fp_metabox_exhibit_group', true );
            return ! empty( $fp_metabox_process_group ) ? $fp_metabox_process_group : null;
        },
        ];
        return $fields;
},99 );
```
A few questions: 
1) Do I need to set up each field (uid, day, etc) to get this to work properly?  I was trying to keep it simple and get one string, since Location is a post object and I have a feeling that will take some extra work to get going.
2) What is going on the example where fields are set up as `project__Label`? Is that a required format I am misunderstanding?
3) What is going on with this bit:`fp_metabox_process_group`?  Is that a required format similar to how `graphql_exhibit_fields` is generated?
4) Anything else I'm missing?

Thanks in advance, I appreciate all the help I've gotten out of this thread so far!

**Comment by nobrefelipe** [comment]
Hi @dsabatier 

1. I  had to set up each field, on my project they all return a String, so wasn't so bad. You can try nikosolihin's solution for your post_object field.

2. Project__Label refers to your Sub Fields names so (uid, start_time, etc...)

3. Try this:
```
'resolve' => function( \WP_Post $post ) {
        $session = get_field(  'sessions',  $post->ID); // using ACF's get_field() instead of get_post_meta()
         return ! empty( $session ) ? $session : null;
}
```
Hope that can be useful

**Comment by dsabatier** [comment]
I will try all of these things later today or tomorrow morning and let you know how it goes! Thanks!

**Comment by cr101** [comment]
@dsabatier This is something I will need to do on a new project I will be starting in a few weeks. So please post back with your solution.

**Comment by dsabatier** [comment]
@cr101 @nobrefelipe I got this working this morning.  A few notes:

1) I did not need to define every field, you can expose only the fields you want to.
2) Make sure you have exposed all of the custom post types involved in your query to graphql
3) Use acfs get_field() when referring to an acf field.
4)  The code might make more sense with some context.  In this app we have Exhibits ('white_exhibit' custom post type), which can have a list of Sessions (repeater field attached to Exhibits).  Sessions have some string fields and a field for a map space ('white_mapspace' custom post type)

Thanks again for the help.  Really happy I found this repo!  Sorry for the code quality, I am doing this really quickly in between other tasks :)

```
add_action('graphql_exhibit_fields', function($fields) {
// create a new type representing each row in a repeater
        $sessionsType = new ObjectType([
        'name' => 'Session',
// description for graphql docs
        'description' => __( 'One session row', 'your-textdomain' ), 
        'fields' => [  // define your fields
             'uid' => [
                              'type' => \WPGraphQL\Types::string(),
                        ],
             'name' => [
                              'type' => \WPGraphQL\Types::string(),
                        ],
	  
	     'map_space' => [
				'type' => \WPGraphQL\Types::post_object('white_mapspace'), // resolve a custom post type, make sure this is exposed to graphql
			]
	     ]
        ]);
// define the field containing your repeater
        $fields[ 'sessions' ] = [ 
// return a list, because repeaters are lists :p
        'type' => Type::listOf($sessionssType), 
        'description' => __( 'Sessions field in GraphQL', 'your-textdomain' ),
        'resolve' => function( \WP_Post $post ) {
            $session = get_field( 'sessions', $post->ID );
            return ! empty( $session ) ? $session : null;
        },
        ];
        return $fields;
},99 );
```

**Comment by nikosolihin** [comment]
I was thinking of using this project to interface Wordpress with graphql but switched to Gatsby's WP plugin which pulled ACF's repeater and flex content items via graphql quite nicely out of the box.

https://www.gatsbyjs.org/packages/gatsby-source-wordpress/

**Comment by jasonbahl** [comment]
@nikosolihin awesome! I LOVE Gatsby! 

fwiw, wpgraphql.com is a Gatsby site 😀

**Comment by JesseRWeigel** [comment]
Has anyone been able to get the Post Object field working? I am trying to implement the solution from @nikosolihin but I can't get it to work. I think my php skills may not be good enough, but it may help to see other examples.

**Comment by ivanjuras** [comment]
Hey, guys, just dropping by.

It would be amazing if we could get this working. ACF is coming out with Gutenberg fields now, so being able to fetch stuff with GraphQL will be essential.

**Comment by cr101** [comment]
ACF 5.8 will allow developers to create Gutenberg custom block types and use any ACF fields within your block. `Gutenberg Blocks` save their data within the `post_content` value (as JSON within HTML comments) while `Metaboxes` save data as “meta” (individual bits of data connected to the post via the `wp_postmeta` table).

Gutenberg Blocks are no good if you want to use a plugin like [MetaBox Custom Table](https://metabox.io/plugins/mb-custom-table/) or  [ACF Custom Database Tables](https://hookturn.io/downloads/acf-custom-database-tables/) to store your fields data in custom database tables for faster search queries and structured data.

It would be great if Gutenberg had a fields API.

**Comment by jasonbahl** [comment]
@cr101 I would LOVE if Gutenberg had an actual server side field API. I’ve been advocating for it for quite a while. 

See: https://github.com/WordPress/gutenberg/issues/2751

And:
https://make.wordpress.org/mobile/2018/03/21/gutenberg-on-mobile/#comment-19383

I’d be down to expose the work ACF is doing in GraphQL, but unfortunately Gutenberg Core still has no respect for the WordPress server making it very difficult to provide a solid GraphQL for core Gutenberg blocks, or third party blocks that are completely built with custom client side JS and little-to-no server awareness. 

The API that ACF is building to make Gutenblocks is the API Gutenberg Core desparately needed a year ago before they steered the community toward writing custom JS for every little thing. 

Anyway, if folks have thoughts on how they envision using ACFs new Block features with GraphQL I’d love to hear them. Maybe some example queries and/or mutations you would expect to be available after creating a block 🤷‍♂️

**Comment by thisischrisj** [comment]
For anyone that wants a quick win with repeater / flexible content type fields:

Add this to functions.php
```
add_filter('graphql_post_fields', function($fields)
{
	$fields['acf'] = [
		'type' => \WPGraphQL\Types::string(),
		'resolve' => function($post)
		{
			$fields = get_fields($post->ID);
			return !empty($fields) ? json_encode($fields) : null;
		},
	];

	return $fields;
});
```

And convert back on your frontend:
```
if(data.hasOwnProperty('acf') && typeof data.acf === 'string')
{
	data.postBy.acf = JSON.parse(data.postBy.acf);
}
```

Not really in the spirit of graphQL but it'll do the job if you just want the data and not object connectivity thereafter

**Comment by jasonbahl** [comment]
Hey all, I spent some time on the WPGraphQL-ACF plugin last night and made some good progress! 

I think I have a pretty good vision for getting support for all the core ACF fields in the very beast future (hopefully within 2 weeks). 

Stay tuned 😀

**Comment by bdevo1896** [comment]
> Hey all, I spent some time on the WPGraphQL-ACF plugin last night and made some good progress!
> 
> I think I have a pretty good vision for getting support for all the core ACF fields in the very beast future (hopefully within 2 weeks).
> 
> Stay tuned 😀

Hey Jason! What's the progress on that plugin looking like? Very interested to know!

**Comment by bdevo1896** [comment]
Can't wait! Thanks for getting back to me so quickly! This is such a great plugin already!

**Comment by towfiqi** [comment]
Great to hear that! :)

**Comment by jasonbahl** [comment]
Hey, just a quick update for those following. 

I’ll be traveling this week for WordCamp US. Hoping to squeeze some more time in on this plugin and get it to a solid stage sometime in the next week or so. 

I’ll announce here when I’ve got something to checkout.

**Comment by mrbarletta** [comment]
For those who come here googling for custom fields, I am leaving my working function.php extract for PODS custom type with a date, an image and a text field.


```
add_action('pods_register_post_type', function ($options, $post_type) {

    if ($post_type == "notification") {
        return array_merge($options, [
            'description' => 'HI',
            'show_in_graphql' => true,
            'supports' => ['title', 'id', 'image', 'description', 'valid_from'],
            'hierarchical' => true,
            'public' => true,
            'graphql_single_name' => 'notification',
            'graphql_plural_name' => 'notifications',
        ]);
    } else {
        return $options;
    }
}, 10, 2);
add_action('graphql_init', function () {
    add_filter('graphql_notification_fields', function ($fields) {
        
        $fields['image'] = [
            'type' => \WPGraphQL\Types::string(),
            'resolve' => function (\WP_Post $post) {
                $image = get_post_meta($post->ID, 'image', true);
                if (isset($image['ID'])) {
                    $image_url = wp_get_attachment_url($image['ID']);
                }
                return $image_url;
            },
            
        ];
        $fields['description'] = [
            'type' => \WPGraphQL\Types::string(),
            'resolve' => function (\WP_Post $post) {
                $description = get_post_meta($post->ID, 'description', true);
                return $description;
            },
            
        ];
        $fields['valid_from'] = [
            'type' => \WPGraphQL\Types::string(),
            'resolve' => function (\WP_Post $post) {
                $description = get_post_meta($post->ID, 'valid_from', true);
                return $description;
            },
            
        ];

        return $fields;
    });
});```

**Comment by jasonbahl** [comment]
@mrbarletta awesome! Thanks for sharing!

**Comment by mrbarletta** [comment]
> @mrbarletta I'm not super familiar with Pods. . .is the `'valid_from'` arg in the `post_type_supports()` a Pods thing? Not sure I've seen that before

No, is a custom field I created for that specific custom post type, sorry if it was confusing!

**Comment by mrbarletta** [comment]
I am leaving this note here as it took me a while to figure out how to mutate custom post type with (obviously) custom fields.
Its a mix of using  `graphql_post_object_mutation_update_additional_data`  and `graphql_input_fields`.
There are comments that gave me a hint but as the library evolved the method names are not the same.

```
add_action('graphql_post_object_mutation_update_additional_data', function ($post_id, $input, $post_type_object, $mutation_name, $context, $info, $default_post_status, $intended_post_status ) {
    if($post_type_object->name == "messaging"){ // messaging is the custom post type name
        if ( ! empty( $input['fcm_token'] ) ) { //fcm_token is the custom field in the custom post type
            update_post_meta( $post_id, 'fcm_token', $input['fcm_token'] );
        } 
    }
},10,8);
add_action('graphql_input_fields', function ($fields, $type_name, $config) {
    if ($type_name == "createMessagingInput") {
        $fields = array_merge($fields, [
            'fcm_token' => [
                'type' => \WPGraphQL\Types::string(),
                'description' => "Firebase Push Token",
            ],
                
                ]);
    }

    return $fields;
}, 10, 3);


```

**Comment by mrbarletta** [comment]
> @mrbarletta that's brilliant, thanks for sharing. I'm building a repo for examples of plugins which have been extended to work with the GraphQL schema (e.g. WooCommerce). Would you like to contribute?

Sure thing! let me know how!

@adamsoffer  - do you mean native ACF support or that the approach referenced in this issue ain't working with ACF plugin?

**Comment by adamsoffer** [comment]
@mrbarletta yeah I mean getting ACF to work with wpgraphql plugin out of the box. I haven't attempted any of the workarounds described in this issue. Appears brittle and unsure if worth the effort, but if it's just a few lines of code to get this working until acf is supported natively I'd be interested.

**Comment by mrbarletta** [comment]
@adamsoffer  its very simple once you nail the correct naming after that is just kind of copy paste for new types or fields.

The downside is that if you add more fields you have to manually update the code and yes, thats a pain and if you work with a team someone will not understand why the new field is showing up on REST but not in the graphql endpoint.

**Comment by adamsoffer** [comment]
Gotcha. Thanks. Yeah, that makes it a non-starter for me personally.

**Comment by bovas85** [comment]
is there a way to show all the acf fields like in the rest api? Would someone be able to show me the code to show a 'acf' object back from graphql in pages? I have no idea of what to write in PHP

**Comment by jasonbahl** [comment]
Hey everyone, I know I've said this before, but I'm getting really close to an initial release of WPGraphQL for Advanced Custom Fields!

The codebase is making use of some new features in the core WPGraphQL plugin that are coming in v0.3.0, which is slated for release next week. 

Once that's released, I will finalize a few things in the initial version of the WPGraphQL ACF Plugin and get that out for ya'll to check out. 

It will be a licensed plugin, and proceeds will help fund updates, maintenance and new features to both WPGraphQL for ACF _and_ the core WPGraphQL plugin. 

Keep an eye out on our blog, Twitter, and Slack for more updates. 😄

**Comment by adamsoffer** [comment]
Exciting! Thanks for the update @jasonbahl

**Comment by bovas85** [comment]
Really cool, you got one license right here

**Comment by mishingo** [comment]
+1 here for a license

**Comment by jasonbahl** [comment]
Howdy folks! It's finally here!

![Screen Shot 2019-04-19 at 10 53 19 AM](https://user-images.githubusercontent.com/1260765/56437931-73488c80-629e-11e9-8302-301b63a4c1ad.png)

Looking forward to what ya'll create with this!

Learn more here: [https://wpgraphql.com/acf](https://wpgraphql.com/acf)

**Comment by adamsoffer** [comment]
Wow! Incredible work congrats! Excited to dig in.

**Comment by bovas85** [comment]
Got one, will refactor one site next week

**Comment by jasonbahl** [comment]
Awesome! Appreciate the support. If you run into anything weird, please let me know. 😀

**Comment by mbrowne** [comment]
This thread was helpful, but I wasn't able to get my resolver working using `get_post()`. The correct way appears to be to use `resolve_post_object()`, e.g.:
```php
    'type' => [
        'list_of' => 'Post'
    ],
    'resolve' => function($post, $args, $context, $info) {
        ...
        $post_ids = // some code to get post IDs
        $posts = [];
        foreach ($post_ids as $id) {
            $posts[] = \WPGraphQL\Data\DataSource::resolve_post_object($id, $context);
        }
        return empty($posts) ? null: $posts;
    }
```

And if you want to support pagination on your custom field (which you should definitely do if you expect that you might be returning more than a few posts), there's now a better way: `register_graphql_connection()`.

See https://docs.wpgraphql.com/extending/connections

**Comment by bovas85** [comment]
Are we able to use nested ACF now? Like acf only appearing in specific pages / post types

**Comment by bovas85** [comment]
thanks, will try this out then as that was the issue initially

**Comment by ivanjuras** [comment]
@jasonbahl Any plans on adding mutations for ACF fields?

**Comment by loganstellway** [comment]
I see this is a closed issue, but it was the most helpful for me while integrating my custom field to the GraphQL API.
So why not place it here for reference? 

I have a plugin that adds the custom ACF field `nav_menu`. 

I found the fields are registered in the [`\WPGraphQL\ACF\Config::register_graphql_field()`](https://github.com/wp-graphql/wp-graphql-acf/blob/a19bd33b7ad8a970aacf168ca40a45d94a48fca3/src/class-config.php#L355) method and a [`wpgraphql_acf_register_graphql_field`](https://github.com/wp-graphql/wp-graphql-acf/blob/a19bd33b7ad8a970aacf168ca40a45d94a48fca3/src/class-config.php#L368-L375) hook is provided for integrating other types of fields. 

Here is the code I used to resolve my `nav_menu` ACF field type to the [native GraphQL Menu object](https://github.com/wp-graphql/wp-graphql/blob/develop/src/Type/Object/Menu.php) type. 
```
<?php
// ...

add_filter('wpgraphql_acf_register_graphql_field', function ($field_config, $type_name, $field_name, $config) {
    $acf_field = isset($config['acf_field']) ? $config['acf_field'] : null;
    $acf_type  = isset($acf_field['type']) ? $acf_field['type'] : null;

    if ($acf_type == "nav_menu") {
        // Reference native WPGraphQL "Menu" type
        $field_config['type'] = 'Menu';

        // Preserve original resolve function to get ACF value
        $resolve = $field_config['resolve'];

        $field_config['resolve'] = function ($root, $args, $context, $info) use ($acf_field, $resolve) {
            // Get ACF value (nav_menu Term ID)
            $term_id = $resolve($root, $args, $context, $info);

            // Resolve with a new menu or NULL if not set
            return $term_id
                ? new \WPGraphQL\Model\Menu(
                    // Get WP_Term object
                    wp_get_nav_menu_object($term_id)
                )
                : null;
        };
    }

    return $field_config;
}, 10, 4);
```

**Comment by andrerds** [comment]
> For those who come here googling for custom fields, I am leaving my working function.php extract for PODS custom type with a date, an image and a text field.
> 
> ```
> add_action('pods_register_post_type', function ($options, $post_type) {
> 
>     if ($post_type == "notification") {
>         return array_merge($options, [
>             'description' => 'HI',
>             'show_in_graphql' => true,
>             'supports' => ['title', 'id', 'image', 'description', 'valid_from'],
>             'hierarchical' => true,
>             'public' => true,
>             'graphql_single_name' => 'notification',
>             'graphql_plural_name' => 'notifications',
>         ]);
>     } else {
>         return $options;
>     }
> }, 10, 2);
> add_action('graphql_init', function () {
>     add_filter('graphql_notification_fields', function ($fields) {
>         
>         $fields['image'] = [
>             'type' => \WPGraphQL\Types::string(),
>             'resolve' => function (\WP_Post $post) {
>                 $image = get_post_meta($post->ID, 'image', true);
>                 if (isset($image['ID'])) {
>                     $image_url = wp_get_attachment_url($image['ID']);
>                 }
>                 return $image_url;
>             },
>             
>         ];
>         $fields['description'] = [
>             'type' => \WPGraphQL\Types::string(),
>             'resolve' => function (\WP_Post $post) {
>                 $description = get_post_meta($post->ID, 'description', true);
>                 return $description;
>             },
>             
>         ];
>         $fields['valid_from'] = [
>             'type' => \WPGraphQL\Types::string(),
>             'resolve' => function (\WP_Post $post) {
>                 $description = get_post_meta($post->ID, 'valid_from', true);
>                 return $description;
>             },
>             
>         ];
> 
>         return $fields;
>     });
> });```
> ```

Hey, buddy how did you use this all? added in the funcitons file?
