### ISSUE TITLE
WP-graphql refuse connections with Gatsby JS

### ISSUE THREAD

**Issue by aggelosV1982** [wp-graphql/wp-graphql#2153]
Hi, i´m trying Gatsby Js and Wordpress Headless cms. Reading the Gatsby documentation,  the file gatsby-config.js has a config to access wpgraphql:

```
resolve: `gatsby-source-wordpress`,
      options: {
        // the only required plugin option for WordPress is the GraphQL url.
        url:
          process.env.WPGRAPHQL_URL ||
          `http://localhost.local/graphql`,
        
      },
```

only have to change localhost for my server url, but when run gatsby develop, it show me this error:

ERROR #gatsby-source-wordpress_111002 

 gatsby-source-wordpress  Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)

GraphQL request to http://localhost.local/graphql failed.

Please ensure the following statements are true
  - your WordPress URL is correct in gatsby-config.js 
  - your server is responding to requests   
  - WPGraphQL and WPGatsby are installed and active in your WordPress backend 
  - Your WordPress debug.log does not contain critical errors

not finished createSchemaCustomization - 0.291s
not finished  gatsby-source-wordpress  ensuring plugin requirements are met - 0.248s

  ---> your WordPress URL is correct in gatsby-config.js // this is correct
  ---> your server is responding to requests    // i try with GraphiQL in Wordpress and i can see the data request
  ---> WPGraphQL and WPGatsby are installed and active in your WordPress backend // this is correct

how i can resolve  the init config in Gastby JS?

**Comment by TylerBarnes** [comment]
Are you able to make requests to your GraphQL endpoint (http://localhost.local/graphql) from an external GraphQL client (not wp-graphiql)?

**Comment by TylerBarnes** [comment]
I guess my question is have you tried the steps in the error message?

"Please ensure the following statements are true

your WordPress URL is correct in gatsby-config.js
your server is responding to requests
WPGraphQL and WPGatsby are installed and active in your WordPress backend
Your WordPress debug.log does not contain critical errors"
