### ISSUE TITLE
GraphQL IDE stops working when wp-graphql-wpml plugin is active

### ISSUE THREAD

**Issue by wbertolo** [wp-graphql/wp-graphql#2154]
Hi, I have installed the wp-graphql-wpml plugin yesterday, and whenever this plugin is active, /wp-admin/admin.php?page=graphiql-ide stops showing the schema. I get the 'NO SCHEMA AVAILABLE' screen and these are some of the relevant errors:

XHR Call (on the inspector): /index.php?graphql
Response: {"code":"internal_server_error","message":"

There has been a critical error on this website. Please check your site admin email inbox for instructions.</p>

<a href="https://wordpress.org/support/article/faq-troubleshooting/">Learn more about troubleshooting WordPress.</a></p>","data":{"status":500},"additional_errors":[]}

Console:
devAssert.mjs:5 Uncaught (in promise) Error: Invalid or incomplete introspection result. Ensure that you are passing "data" property of introspection response and no "errors" was returned alongside: { status: 500 }.
at r (devAssert.mjs:5)
at m (buildClientSchema.mjs:27)
at App.js:181

Does anyone know how to solve this?

**Comment by jasonbahl** [comment]
@wbertolo can you see if the filter mentioned here resolves this issue for you? 

https://github.com/wp-graphql/wp-graphql/issues/1626#issue-769089073

**Comment by wbertolo** [comment]
Hi, sorry, I tried to close this at the time. I have all my issues solved. Thanks, Jason.

**Comment by jasonbahl** [comment]
@wbertolo ok, sounds good! Thanks for the follow-up.
