### ISSUE TITLE
Return warnings in some cases

### ISSUE THREAD

**Issue by CodeProKid** [wp-graphql/wp-graphql#216]
I believe some of the exceptions we are throwing are a bit heavy handed. I think in some instances we need to return some _warning_ data, but still run the query. The convo in the slack channel actually got me thinking about this. 

For instance; if someone queries for 200 posts, and the limit is still set to 100, ideally I think we should return the 100 posts, but also return a warning that says what was requested was over the hard limit.

I think the response data could look something like the following:
```
{
  "warnings": [
    {
        "message": "Too many posts queried, we've limited the results to the maximum number allowed...",
        "locations": [
        {
          "line": 10,
          "column":10,
        }
        ]
  ],
  "data": {
    "posts": {
      "edges": [
        {
          "node": {
            "id": "cG9zdDo0MTg="
          }
        },
        {
          "node": {
            "id": "cG9zdDo0MTc="
          }
        }
      ]
    }
  }
}
```
I think adding varying degrees of exceptions as a whole will be good for the codebase, and would allow us to give good debugging info without bombing out an app. Could also be good data for an optics like product that tracks all of the GraphQL queries.

**Comment by jasonbahl** [comment]
Part of the first/last after/before and pageInfo partly solves this issue (the max query amount)  

When you ask for data you're never guaranteed to get back as much as you asked for, but the pageInfo will return wether there is more pages or not. 

So a consuming client will query first 1,000, they will receive 100 items (or whatever the sys admin deems an acceptable amount to allow without causing performance issues), and will be able to see in the pageInfo wether there hasNextPage is true and if so they can use the endCursor to query for more items. 

That said, I do think varying levels of warnings/errors should be explored more. I believe the GraphQL spec actually has more kinds of errors than we're currently making use of. Haven't explored a ton yet though. 

I do know I want to reorganize some of our mutations for sure though. We block full mutations to throw an error when we probably should capture the potential errors, do the partial mutation with what data we can, and throw an exception/warming for the parts we couldn't fulfill

Like user update for example. If I update first name, last name and email, but my email had a typo, we could update the first and last name, and throw a warning/exception about the email being invalid. 🤔

Def think we should explore the GraphQL spec re: warnings more in general though. 

At the moment I'm not sold that the max number of pages example should be a warning...Not completely against it but not completely for it either. I'll let it stew in my head for a bit.

**Comment by jasonbahl** [comment]
The top answer here kinda does what I'm suggesting. Captures "errors" within the resolver, allows the database edit to partly go through and return errors for what didn't go through. https://stackoverflow.com/questions/32662437/graphql-and-form-validation-errors

**Comment by CodeProKid** [comment]
Yeah, the posts_per_page max just kinda got my brain thinking about it, I think there are a bunch more examples. Would definitely be good to explore the other methods of error logging and warnings though. 👍

**Comment by jasonbahl** [comment]
Just adding some links related to this conversation: 
https://facebook.github.io/graphql/#sec-Errors
https://github.com/webonyx/graphql-php/blob/df1b575469cb005b17088f0dcdf4d4543f7abac4/docs/error-handling.md#custom-error-handling-and-formatting

**Comment by CodeProKid** [comment]
This probably needs more discussion, and should be lower priority than many other issues here.

**Comment by jasonbahl** [comment]
Ok, so the GraphQL spec has settled on errors. 

We should for sure focus on the error messages we return in various places to be as helpful as possible, and can even consider different categories of errors to make it easier to debug, but I don' thtink we'll be handling anything related to warnings at the top level as suggested here.
