### ISSUE TITLE
Retrieving a `contentNode` as preview for draft posts results in `null`

### ISSUE THREAD

**Issue by blakewilson** [wp-graphql/wp-graphql#2166]
When retrieving a `contentNode` with `asPreview` set to `true` for a draft post, the response will be `null`.

## Versions:
- WP GraphQL: 1.6.7
- WordPress: 5.8.2

## Other Plugins Installed:

None

## Current Behavior

The response is `null`

## Expected Behavior

The response should include the proper content node

## How to reproduce

1. Create a draft page
2. Create a query with the following content:
   ```graphql
    query MyQuery {
      contentNode(id: "xxxx", idType: DATABASE_ID, asPreview: true) {
        id
      }
    }
   ```
3. Replace "xxxx" with the draft post ID
4. Notice the response:
     ```json
     {
       "data": {
         "contentNode": null
       }
     }
    ```

## Screenshots
Draft Page:

![draft-page](https://user-images.githubusercontent.com/5946219/144921286-d3a3563a-65ac-4e09-84e6-ce51036cc1e0.png)

`contentNode` with `asPreview`:

![with-as-preview](https://user-images.githubusercontent.com/5946219/144921305-f661b517-16a9-4eef-8bcb-80e86d4a3fe7.png)

`contentNode` without `asPreview`:

![without-as-preview](https://user-images.githubusercontent.com/5946219/144921352-49b59e9a-aa51-420a-8156-a2764feb0499.png)

**Comment by jasonbahl** [comment]
@blakewilson did you click the "Preview Button" before trying to query in GraphiQL? 

Clicking the "Preview" button stores the preview revision. If you don't do that, there will be nothing to preview. 

I didn't see this in your steps to reproduce, so I want to confirm.

**Comment by jasonbahl** [comment]
@blakewilson following your steps, but also clicking the "Preview" button seems to work for me. 

Users must click the preview button in order for WordPress to generate the preview data in the database. Without this action, there's nothing to preview. 

Here's a quick recording showing the steps I took: 

https://www.youtube.com/watch?v=HRIs_zG9nO4

Let me know if I'm missing something. Happy to hop on a zoom or whatever too.

**Comment by jasonbahl** [comment]
@blakewilson fwiw, I just tried with Gutenberg active, and same results as I shared in the video.

**Comment by blakewilson** [comment]
@jasonbahl Hmm, odd. You're right, following the steps again yeilded the correct results. However, I have some draft posts from the past that still show this behavior on. I assume then this is an instance of a draft post being auto-saved, thus, the preview data was never generated.

Thanks for following up on this. I'll close for now.

**Comment by jasonbahl** [comment]
@blakewilson ya, that sounds right. You'd have to click "preview" on an older post to see the preview for it. 

That being said, I wonder if we should support a mutation like: `mutation createPreviewForContentNode(...)` or something

That way a headless client could provide it's own UI for creating the preview? Then the user wouldn't have to be in the WordPress admin to actually generate the preview? 🤔

**Comment by jasonbahl** [comment]
I created this issue to open a discussion around this possible feature: https://github.com/wp-graphql/wp-graphql/issues/2170

**Comment by blakewilson** [comment]
Clicking "preview" does in fact populate the correct response.

That would be an awesome feature. I'll follow along there.

**Comment by apmatthews** [comment]
I was doing some testing with CPT previews in Faust.js and I ran into this issue. What I found is that it's only a problem on custom post types that do not declare support for revisions. It's not reproducible with built in post types like `post` and `page` since they _do_ support revisions.

The resolver for `asPreview` uses the `wp_get_post_revisions` function, which only returns DB rows where `post_type=revision`. Custom post types that don't support revisions don't have these rows, but they might still have a draft or auto-draft saved in the DB (whether as a result of clicking "Preview" or "Save Draft"). In this case, I think we should still get the preview data that's saved as draft.

**Comment by jasonbahl** [comment]
@apmatthews ah! Good digging. 

I'll re-open this now that we have more context on how to reproduce! 🙏🏻

**Comment by jasonbahl** [comment]
@apmatthews can you share how you reproduced setting a specific post type to not support revisions?

Are you simply leaving out `revisions` from the `supports` argument for the post_type, or are there any other things you were doing to reproduce this?

**Comment by apmatthews** [comment]
Yes, exactly. Just leaving out `revisions` from the `supports` should do it. More specifically though, I used ACM to create an Event model (ACM custom post types do not include revision support) with a single field called `name` that was set to be used as the entry title. Here's a query that should help demonstrate the difference between revision preview data vs draft preview data:

```gql
query DraftPreviewBug($pageId: ID!, $eventId: ID!) {
  page: contentNode(id: $pageId, idType: DATABASE_ID) {
    ... on Page {
      title
      status
      databaseId
      parentDatabaseId
      isPreview
    }
  }
  pagePreviewRevision: contentNode(
    id: $pageId
    idType: DATABASE_ID
    asPreview: true
  ) {
    ... on Page {
      title
      status
      databaseId
      parentDatabaseId
      isPreview
    }
  }
  eventDraft: contentNode(id: $eventId, idType: DATABASE_ID) {
    ... on Event {
      title
      status
      databaseId
      isPreview
    }
  }
  eventPreviewDraft: contentNode(
    id: $eventId
    idType: DATABASE_ID
    asPreview: true
  ) {
    ... on Event {
      title
      status
      databaseId
      isPreview
    }
  }
}

```

**Comment by apmatthews** [comment]
It seems like returning the original `$post_id` [in the false condition here](https://github.com/wp-graphql/wp-graphql/blob/6084ed03bda8af758eb6dd07dc9eba685dad08a7/src/Type/ObjectType/RootQuery.php#L200) would give us the right result.

I'm not sure how this impacts things like `isPreview` though. It seems to be tied to whether a node is a revision or not. If we acknowledge that a preview can be a revision OR a draft, there may be a few things to update in the Post model.
