### ISSUE TITLE
Requires PHP >5.5 - "Can't use method return value in write context"

### ISSUE THREAD

**Issue by irelandpaul** [wp-graphql/wp-graphql#217]
If you get this error:
Fatal error: Can't use method return value in write context in /PATH/TO/wp-content/plugins/wp-graphql-develop/src/Data/Config.php on line 69

Then you are probably running on PHP 5.5 or lower. My test site was using PHP 5.4 (not sure why) and I got that error. Changing to 5.6 resolved it.

**Comment by jasonbahl** [comment]
@irelandpaul I'll update the readme and main plugin file to indicate that php5.5+ is required. The unit test coverage we run is ran for 5.5-7.1. Currently no plans to support anything older than 5.5 either. And the focus is really on 7+
