### ISSUE TITLE
PHP Notice for missing clientMutationId

### ISSUE THREAD

**Issue by oskarmodig** [wp-graphql/wp-graphql#2176]
After the requirement of clientMutationId was removed in issue #1123 and fix #1573 I'm getting a lot of PHP Notices when not inputting clientMutationId:  
`PHP Notice:  Undefined index: clientMutationId in /wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php on line 1161`

**Comment by bhardie** [comment]
Thank you @oskarmodig
