### ISSUE TITLE
Inconsistent terms query results when using cursor based pagination after re-ordering terms

### ISSUE THREAD

**Issue by nino-vrijman** [wp-graphql/wp-graphql#2180]
We're getting inconsistent results when querying terms using cursor based pagination after terms have been re-ordered using the [Advanced Taxonomy Terms Order plug-in](https://www.nsp-code.com/wordpress-plugins/category-order-and-taxonomy-terms-order/). Our site has 100+ terms but when using the largest page size of 100 and fetching 2 pages of terms we reliably get a total of 160 terms of which 105 are unique (based on their id). When using smaller page sizes like the total amount and unique amount returned get more inconsistent, a page size of 50 resulted in 123 terms of which 73 were unique, a page size of 25 resulted in 35 terms of which 31 were unique and a page size of 10 resulted in 40 terms of which 23 were unique. So the amount of terms returned is both inconsistent and often contains duplicates.

The behaviour we're expecting is that the GraphQL API returns the right amount of terms regardless of the page size without duplicates.

#2137 might be a related issue because I supsect the re-order plug-in we're using will cause the re-ordered terms to get the same timestamps. Would the terms query also benefit from the same cursor stabilization technique that was used in #2145 ?

A selection of the plug-ins we're using:
- WPGraphQL 1.6.10
- [Advanced Taxonomy Terms Order plug-in](https://www.nsp-code.com/wordpress-plugins/category-order-and-taxonomy-terms-order/) 2.8.8
- ACF Pro 5.11.4
- WP GraphiQL 1.0.1
- WPGraphQL for ACF 0.5.2
- WPGraphQL JWT Authentication 0.4.0

I hope this is enough information to reproduce the problem we're experiencing. I would've loved to provide use some kind of CodeSandbox but that doesn't seem possible. If required I could free up some time to make a video or a reproduction of some sorts.

**Comment by jasonbahl** [comment]
> I supsect the re-order plug-in we're using will cause the re-ordered terms to get the same timestamps

Terms don't have timestamps, so we can't use timestamps to stablize cursors for terms in the same way we can for data in the posts table.

----

Can you share steps to reproduce?

I see the plugins you have active, but can you share steps such as: 

1. insert xx terms (maybe even provide an export file so I can have the exact same terms as you)
2. query with xx query `ex: { categories { nodes { id, name } } }`
3. expected results should be: 
4. actual results are:

----

The closer I'm able to get to being in the same state as your environment, the better chance I'll have of debugging. 

In the mean time, I'd recommend checking out the SQL query logs. you can enable them by going to GraphQL > Settings, then clicking "Enable GraphQL Query Logs"

This will add query logs to the GraphQL responses. There you can see what SQL is being generated which should help diagnose the issue. 

My guess is the "Advanced Taxonomy Terms Order" plugin is modifying queries but either might not be impacting queries that WPGraphQL is making, or something along those lines?

Anyway, the more info you can provide to help me get into the same state you're in, the better.

**Comment by justlevine** [comment]
@nino-vrijman just following up - you still running into this?
(Im assuming the underlying issue and solution are similar to #2300)

**Comment by jasonbahl** [comment]
I'm going to close this issue, as I believe it's documented how to overcome this. I don't believe it's WPGraphQL core responsibility to maintain this snippet in the core WPGraphQL codebase, as it would be nearly impossible to take the responsibility of owning and maintaining perfect compatibility with the wide world of WordPress plugins.
