### ISSUE TITLE
SourceUrl for media is not set properly into the post content using Cloudinary

### ISSUE THREAD

**Issue by thekage91** [wp-graphql/wp-graphql#2192]
Hi
I'm experiencing a problem using Cloundinary + WpGraphql. I installed the Cloudinary plugin to automatically sync our media into the CDN and everything works well, all medias into posts has been correctly updated, if I inspect an image's url I can see the Cloudinary url instead of local WordPress url. 

If I retrieve the post with WP-JSON API the content has the correct link from Cloundinary but the problem is If I retrieve the same post using GraphQL (with the IDE) the links are from the local WordPress and not from the CDN. 

We use Gatsby to build the static site and WordPress as CMS. We installed the WP Graphql plugin to pull the data with Gatsby and build the pages for our site. The problem is that our WordPress instance isn't very fast and to improve the performance during the build process (especially in the development environment) we would like use the CDN's links in all posts and not the link from local WordPress. I don't know why the content retrieved with Graphql has the wrong link even if the content of the post retrieved with the WP API has the link from the CDN.

We use WordPress 5.8.2 and we have this plugins installed:
- Cloudinary version 3.0.0  (latest)
- WpGatsby version 2.1.1 (latest)
- WP Graphql version 1.6.10 (latest)
- WP GraphiQL IDE version 1.0.1 (latest)
- Smush Version 3.9.4 (latest)

Gatsby version is 4.4.0 to use incremental build and preview content with Gatsby Cloud 

Anyone can help me to understand the problem and find a possible solution?
Anyone know where and how the WP Graphql plugin get the media's links into the post?

Thank you very much :)

**Comment by robclancy** [comment]
I reverted to cloudinary_wordpress 2.7.6 and it works. Looks like a similar issue with https://github.com/cloudinary/cloudinary_wordpress/issues/625

**Comment by thekage91** [comment]
Thank you very much @robclancy! I downgraded the plugin as you suggested and now seems return the url from Cloudinary.
