### ISSUE TITLE
Fieldname Audit

### ISSUE THREAD

**Issue by CodeProKid** [wp-graphql/wp-graphql#221]
Now that we have a lot more coverage with mutations & queries, we should do an audit to make sure that things are named logically. We should additionally make sure that field names are consistent between queries and mutations within Types.

**Comment by jasonbahl** [comment]
@CodeProKid do you have notes to share from the Audit you did for this?

**Comment by jasonbahl** [comment]
What the field Audit should accomplish:

- Does the REST API have a field that WPGraphQL doesn't?
 
- **Types**
  - Name: 
    - `ucfirst`, camelCase, like `Post`, `Tag`, `PostConnection`
    - Is the name too valuable? 
    - Is the name too vague?
    - Unions and Enum should be suffixed with `Enum` and `Union`, like `PostTypeEnum` and `PostObjectUnion`
  - Description:
    - Description should exist and be accurate
  - Fields
    - Does the Type expose all the Fields that are needed to get the necessary data for the Type?
    - Do Field Audit on each field
     
- **Fields**
  - Boolean fields start with `is`, `has` or `can`? 
    - (should research how Twitter, etc are standardizing this)
  - Field name should be `lcfirst`, camelCase, like `posts` or `firstName`
  - Is the field name appropriate? 
    - Is the name too valuable? 
    - Is the name too vague?
  - Field should have a description
    - description should make sense and be accurate for what/how it resolves.
    - description should mention if it's marked `isPrivate` or has a custom `authCallback`
    - sprintf() should actually return something (see descriptions for )
  - Auth?
    - Should the field be marked `isPrivate`?
    - Should the field have a custom `authCallback?`
  - Resolving Type
    - Does the Type the field resolves to make sense?
      - Is the Type a scalar or an Object Type?
      - Does the Type have the proper fields to access what's needed?
       
- **Field Args**
 - Connections should have: `first`, `last`, `after`, `before`, and `where`
   - Where args should make sense
   - Where args should do something
   - Naming conventions should be consistent across all field args
     - for example, if 2 fields have a way to order them, use the same fieldname `orderby` or whatever, instead of `order` for one and `orderBy` for the other. . .just make it consistent. 
   - Args that WordPress allows to have a string or array should probably just accept a `listOf` in WPGraphQL, or 2 options, like `status: StatusEnum` and `stati: [StatusEnum]`
     
- **Mutations**
 - Input
    - Input fields should be consistently named with the fields that can be queried.
        - doesn't have to be exactly the same, because mutations are different, but they should use similar terminology, etc
 - Output
    - Output fields should provide enough info to update the state when a mutation occurs
        - Like mutating a Post by changing it's terms needs to update the state for the Post and the Term, and potentially the list(s) of items they belong in

**Comment by jasonbahl** [comment]
@CodeProKid I'm closing this as we've undergone many changes in the mean time and have seen a lot of cleanup along the way
