### ISSUE TITLE
Can't disable public Introspection

### ISSUE THREAD

**Issue by evangelinepapanicola** [wp-graphql/wp-graphql#2217]
Hi @jasonbahl  - I don't seem to be able to untick Enable Public Introspection in the most recent version of WPGraphQL? The checkbox is greyed out and ticked.
Pretty sure there used to be another checkbox that would allow you to tick/untick this one.

![image](https://user-images.githubusercontent.com/33719860/149515466-1a390aad-d7f0-41f2-8976-5dce48029c7e.png)

_Originally posted by @evangelinepapanicola in https://github.com/wp-graphql/wp-graphql/issues/1489#issuecomment-1013078004_

**Comment by theodesp** [comment]
Hello @evangelinepapanicola how are you? Did you enable debug mode because as long as you have it enabled then the checkbox is enabled?
<img width="1570" alt="Screenshot 2022-01-14 at 13 26 13" src="https://user-images.githubusercontent.com/328805/149522542-36a65d99-6b87-4397-93c1-1117bd700c41.png">

**Comment by evangelinepapanicola** [comment]
@theodesp Ah yes! That was it, thank you 🤦‍♀️  Might be a good idea to add "Also enables public introspection" to the Debug Mode description, I'm probably just stupid but I was wracking my brains for ages wondering what I was doing wrong haha

**Comment by jasonbahl** [comment]
@evangelinepapanicola I think it's a good idea to add a note that it's force enabled when debug mode is on. good call!

**Comment by jasonbahl** [comment]
Opened a PR to add a note: 
https://github.com/wp-graphql/wp-graphql/pull/2218
