### ISSUE TITLE
Query posts by category slug

### ISSUE THREAD

**Issue by IlirBajrami** [wp-graphql/wp-graphql#2226]
I was reading [here](https://github.com/wp-graphql/wp-graphql/issues/1100#issuecomment-573188852) that you can query posts by categorySlug but i dont see that option.
How can i do this?

**Comment by jasonbahl** [comment]
@IlirBajrami can you share some details on what you've tried so far?

Or what you're hoping to do but not able to?

**Comment by IlirBajrami** [comment]
I found a workaround to achieve the same like this:
`
query MyQuery {
  posts(
    where: {taxQuery: {taxArray: {field: SLUG, terms: "grid", taxonomy: CATEGORY}}}
  ) {
    edges {
      node {
        id
        title
      }
    }
  }
}
`
but that would be a cleaner solution

**Comment by justlevine** [comment]
Hey @IlirBajrami have you looked into the other `RootQueryToPostConnectionWhereArgs`?

Querying posts by a category slug can be done with `categoryName`, as follows:

```graphql
query MyQuery {
  posts( where: { categoryName: "grid" } ) {
    edges {
      node {
        id
        title
      }
    }
  }
}

```

And here it is in action:
![image](https://user-images.githubusercontent.com/29322304/161092123-b83d5a6b-f711-4de2-b5df-a78c9303e5ee.png)

**Comment by IlirBajrami** [comment]
Hi @justlevine Thanks for the neat solution. Even thought my solution works as expected for now, i will keep this in mind for the next project. Definitely will use it.

**Comment by maxyudin** [comment]
Hi, @IlirBajrami , your query works perfectly for me with custom post types and taxonomies. Thanks a lot!

**Comment by madfcat** [comment]
> Hey @IlirBajrami have you looked into the other `RootQueryToPostConnectionWhereArgs`?
> 
> Querying posts by a category slug can be done with `categoryName`, as follows:
> 
> ```graphql
> query MyQuery {
>   posts( where: { categoryName: "grid" } ) {
>     edges {
>       node {
>         id
>         title
>       }
>     }
>   }
> }
> ```
> 
> And here it is in action: ![image](https://user-images.githubusercontent.com/29322304/161092123-b83d5a6b-f711-4de2-b5df-a78c9303e5ee.png)

Nice! It would be cool to have `categorySlugIn` in addition to `tagSlugIn`.
I used `categoryIn` and ids array. But is it possible to filter buy slugs from several categories?
