### ISSUE TITLE
srcset and sizes for images not returning all sizes like it should

### ISSUE THREAD

**Issue by drewbaker** [wp-graphql/wp-graphql#2232]
I'm still not sure that the way `srcset` works is correct. This image is 5000px+ wide, but the srcset only returns a default group of sizes and then the biggest one. It should be returning all sizes up to the max. At least, that's how I think it should work, srcset's are pretty confusing.

![Screen Shot 2021-12-08 at 6 58 12 PM](https://user-images.githubusercontent.com/475015/152842538-e11a8e9e-f7e3-403b-97a0-f51f6ebcc11e.png)
![Screen Shot 2021-12-08 at 6 58 31 PM](https://user-images.githubusercontent.com/475015/152842547-a030b58f-edcf-4796-94d5-e7e7ba6be0db.png)

I asked this on slack and someone mentioned that perhaps this was due to WordPress "big image" filter, but that is turned off: https://github.com/funkhaus/fuxt-backend/blob/4dc1e90f4f7db58720981cb1579fcbb54cc9f485/functions/wp-functions.php#L14

If I had to guess, WP-GQL is only generating srcset's based on the sizes set in the GUI, not the custom sizes defined in code.

**Comment by justlevine** [comment]
hey @drewbaker,

WPGraphQL [uses the WP native `wp_get_attachment_image_srcset`](https://github.com/wp-graphql/wp-graphql/blob/f2a9e4d8852e1f6af5a0e8fed3d0422b587b9ff7/src/Type/ObjectType/PostObject.php#L144), so WPGraphQL shouldn't be the source of the problem.

Looking at the core WP code, it doesnt seem that `big_image_size_threshold` is used when generating `srcset`s . Does it work if you use [`max_srcset_image_width`](https://developer.wordpress.org/reference/hooks/max_srcset_image_width/) instead?

**Comment by drewbaker** [comment]
That did it! I updated the fuxt boilerplate with it now: https://github.com/funkhaus/fuxt-backend/blob/master/functions/wp-functions.php#L15
