### ISSUE TITLE
Add to WordPress.org Plugin Repo

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#224]
This plugin should be available on the WordPress.org plugins repository. 

In order for that to happen, we should have an automated build process that prepares the plugin for SVN. 

Ideally, the vendor dependencies _should not_ be versioned in Git like they are now, but they _will_ need to be versioned in SVN. 

So, I'd like to have some sort of automated process around releases that prepares the plugin for SVN. . .runs composer install, moves files to the proper /trunk directory (or whatever needs to happen for SVN. . .been a while since I used it), makes sure tags/version numbers are updated properly, etc. . .

Could draw some inspiration from a script like: https://github.com/thenbrent/multisite-user-management/blob/master/deploy.sh

**Comment by timneutkens** [comment]
@jasonbahl would you mind publishing the repo to packagist too? We're using something similar to roots bedrock which supports composer installed wordpress plugins. Thanks! 👌

**Comment by jasonbahl** [comment]
@timneutkens this is the first thing I've put on packagist (https://packagist.org/packages/wp-graphql/wp-graphql), so please let me know if I need to adjust anything to make it work better/correctly, etc.

**Comment by timneutkens** [comment]
Awesome @jasonbahl, looks Great! Thanks ❤️

**Comment by jasonbahl** [comment]
@0aveRyan if you're interested in working on some sort of build script that prepares the plugin for the .org repo, this is probably the issue to track it to. Thanks!

**Comment by homerjam** [comment]
@jasonbahl Hi! One suggestion for Packagist would be the [update hook](https://packagist.org/about#how-to-update-packages) this would allow us to automatically obtain the latest versions on push (right now 0.3.0 is missing. Thanks!

**Comment by jasonbahl** [comment]
@homerjam I thought I had this wired up. Let me check 🤔

**Comment by jasonbahl** [comment]
I'm getting the ball rolling on this now that we're getting close to the [1.0 release](https://github.com/wp-graphql/wp-graphql/issues/1357). 

I tried to submit the plugin to the WordPress.org repo and was met with the following message: 

![Screen Shot 2020-07-07 at 8 08 29 AM](https://user-images.githubusercontent.com/1260765/86817644-85008600-c042-11ea-8e5d-58643a69438d.png)

I've emailed plugins@wordpress.org and they've denied the request to have WPGraphQL on the repo. 

I've emailed again with _more_ context explaining that the plugin I'm submitting is the _same_ plugin that has a significant userbase outside of the .org repo referenced in their message. 

Hopefully we can work it out. Otherwise we'll need to change the slug for the 1.0 release from `wp-graphql` to something like `wpgraphql` perhaps? 🤷‍♂️  🤔 

We'll see what they say.

**Comment by bahiirwa** [comment]
While submitting names like those that need manual review like you did, it helps using an email with the domain name attached to the brand they are speaking of i.e tech@wpgraphql.com or something similar along with the context you shared. Manual review will sort that out. No need to look for other slugs yet.

**Comment by CodeProKid** [comment]
@jasonbahl since we're already using github actions for all of our CI, we could use something like: https://github.com/10up/action-wordpress-plugin-deploy to handle it.

**Comment by jasonbahl** [comment]
@CodeProKid ya, that's the plan. We just implemented it on the WPGatsby plugin and it works great!

https://github.com/gatsbyjs/wp-gatsby/blob/master/.github/workflows/main.yml#L13

Deploys to: 

https://wordpress.org/plugins/wp-gatsby/

**Comment by jasonbahl** [comment]
I need to write a blog post to inform users of the change. 

Folks will start seeing the Update button in WordPress and that has potential to screw up some workflows that have been using Composer, etc to handle versioning. 

I think with this change, we can also stop versioning the composer dependencies (graphql-php/graphql-php-relay) within this repo and have a build step that adds them back in before deploying to WordPress.org

And for folks pulling from packagist, that _might_ mean they need to start pulling from https://wpackagist.org/ instead?

Not sure. 🤔 

Some details to think through. 

I think the quickest win is to simply start deploying as-is, then work through the other details (no longer versioning composer dependencies) separately?
