### ISSUE TITLE
Does nodeByUri support getting the frontpage in several languages?

### ISSUE THREAD

**Issue by krishaamer** [wp-graphql/wp-graphql#2249]
Hi @jasonbahl thanks for your fantastic work! I was wondering if nodeByUri should be able to retrieve the frontpage for each language if only given a language slug such as /de or /en ?

If this is officially supported?

(I'm currently using PolyLang and PolyLang GraphQL but I'm only able to retrieve the default language and the frontpages in other languages result in null.)

Thanks
Kris

**Comment by jasonbahl** [comment]
@krishaamer I'm not certain how WPGraphQL will work when used along with plugins such as Polylang. I know the wp-graphql-polylang extension (https://github.com/valu-digital/wp-graphql-polylang) does a lot to enable certain things with Polylang to work well with WPGraphQL, but I'm not sure how it handles situations like this. 

My guess is that there's certain filters that Polylang has in place to have homepages work with different languages in "normal" WordPress, and likely similar filters would need to be applied to work within the context of WPGraphQL queries, but I'm not well enough versed in the internals of Polylang to offer specific answers here.
