### ISSUE TITLE
Adjust hooks to provide support for Tracing

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#225]
In order for Tracing to be properly supported, some hooks need some adjustments.

See the proposed Tracing spec: https://github.com/apollographql/apollo-tracing

**Comment by CodeProKid** [comment]
Fixed by #226

**Comment by amay** [comment]
@jasonbahl @CodeProKid did either of you end up writing any php code to implement the [tracing extension](https://github.com/apollographql/apollo-tracing) for a wordpress install? I'm investigating using apollo-engine for response caching and getting tracing info back is a necessary step.

**Comment by jasonbahl** [comment]
@amay check out https://github.com/wp-graphql/wp-graphql-insights

It has tracing, and if you have query monitor active will provide helpful query logs as well. 

It doesn’t yet have support for engines Cache Control stuff. Would be interested in adding support at some point though.
