### ISSUE TITLE
Querying non-existant pages with custom permalinks returns a valid `page` object with `id` instead of `null`

### ISSUE THREAD

**Issue by blakewilson** [wp-graphql/wp-graphql#2260]
When querying for a non-existant page with a custom permalink structure (eg `/posts/%postname%/`), the `page` object is present with a valid ID instead of `null`. The base 64 ID decoded is `post_type:page`.

## Screenshots

🟢 Permalinks set to "post name"
<img width="1426" alt="Screen Shot 2022-02-28 at 12 52 45 PM" src="https://user-images.githubusercontent.com/5946219/156042200-c554cab5-954d-4b4d-8e14-623442f6bd12.png">

<img width="1426" alt="Screen Shot 2022-02-28 at 12 52 49 PM" src="https://user-images.githubusercontent.com/5946219/156042215-b7a02dfa-d4ed-4d3d-8f36-84092a3a1024.png">

🔴 Permalinks set to "Custom Structure"
<img width="1426" alt="Screen Shot 2022-02-28 at 12 53 17 PM" src="https://user-images.githubusercontent.com/5946219/156042272-d61546be-350e-488c-849a-2652716c5a21.png">

<img width="1426" alt="Screen Shot 2022-02-28 at 1 01 26 PM" src="https://user-images.githubusercontent.com/5946219/156042679-6067e459-2ae9-4c75-847b-b239f57f3885.png">

WordPress version: 5.9.1
WP GraphQL version: 1.6.12

No other plugins active.

**Comment by jasonbahl** [comment]
@blakewilson what's the behavior in normal WordPress, here?

If you visit the url in your browser, do you get a 404 or does WordPress try to resolve this url?

**Comment by blakewilson** [comment]
Yep, WordPress will throw a 404:
<img width="1388" alt="Screen Shot 2022-02-28 at 2 12 30 PM" src="https://user-images.githubusercontent.com/5946219/156051930-cf4ca20d-2b8a-4084-8729-db532a8ee43a.png">

**Comment by jasonbahl** [comment]
@blakewilson, since WPGraphQL is bug-free, this must be a core WordPress bug. 🤣

JK. I'll look into this

**Comment by blakewilson** [comment]
Perhaps line 464 of `NodeResolver.php` should be:

```php
```

**Comment by jasonbahl** [comment]
PR would be 🔥 . I'll look into it more as well
