### ISSUE TITLE
Cannot pull data for 'grandchild routes'

### ISSUE THREAD

**Issue by jhochgrevetsd** [wp-graphql/wp-graphql#2266]
Hello and thanks for such a great plugin! 

When querying a page by URI such as: "/personal/savings/share-savings-account/"

I am not able to get anything to return in the "page" data. I do seem to be able to get an id back, but it does not seem to be the correct ID, as I attempt to query by the ID and receive the following error: "The ID input is invalid. Make sure you set the proper idType for your input."

For the above URI here is the ID I receive: cG9zdF90eXBlOnBhZ2U= which seems incorrect even in length when compared to other valid queries. 

All of our child routes such as "/personal/savings" seem to work just fine when queried by URI or ID. 

This seems to also be affecting any WPGraphQL plugin data also...such as ACF. 

Any help would be GREATLY appreciated!

**Comment by jhochgrevetsd** [comment]
Looks like the latest update fixed the issue! Thanks so much, guys...wow crazy timing :)

**Comment by jasonbahl** [comment]
@jhochgrevetsd Thanks for opening the issue and following up with confirmation that it's resolved! 🙌🏻 

Super glad it's working for you now.

I hadn't even seen this issue before the release was published, so it's awesome to hear that it was resolved in the 1.7 release!  

I believe this PR (https://github.com/wp-graphql/wp-graphql/pull/2261) from @blakewilson is what resolved the issue. 

Thanks again for taking the time to report the bug and confirm it's no longer a bug 😄

**Comment by blakewilson** [comment]
Woohoo 🎉 Crazy timing
