### ISSUE TITLE
[v1.7.0] New WPGraphiQL pollutes browser history with url param changes

### ISSUE THREAD

**Issue by justlevine** [wp-graphql/wp-graphql#2268]
The new version of WPGraphiQL bundled with v1.7.0 adds every single state change to the browser history. In past versions, while changes updated the browser string, it wasn't part of the browser history.

Not sure if this change was intentional, as a way to undo changes by going 'back' in the browser (I'll leave it to you to decide if the browser history is the best way to do that vs storing the history in a separate WPGraphQL undo/redo feature), but even if it was, the back button still only changes the url in the address bar, and you would need to manually reload the page to get the old query information.

Also, other state changes pollute the Browser history that definitely shouldnt, such as `isQueryComposerOpen`.

![image](https://user-images.githubusercontent.com/29322304/156708091-f0d45309-7fdb-44fd-a957-56a98e8c51ae.png)

## Expected behavior

_Either_ don't store changes to the url's query parameters in the browser history _or_ reload the GraphiQL state when going back/forward in the browser.

## Actual behavior

Every update to the url's query parameter is stored in the browser history, but navigating back/forward in the browser doesnt change the code to reflect the changed parameters.

### When reporting a _bug_, please be sure to include the following:
- [x] A descriptive title
- [x] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)
- [x] What version of `WPGraphQL` you're using, and the platform(s) you're running it on
- [x] What other plugins you're using
- [x] The behavior you expect to see, and the actual behavior

**Comment by jasonbahl** [comment]
@justlevine thanks for opening this issue and providing excellent detail! 

I've successfully reproduced this behavior and confirmed that it indeed is a change in behavior compared to the previous version of GraphiQL included in 1.6.12 and below.

I believe it comes down to the `useQueryParams` package pushing to history instead of replacing history. 

I'm looking into this 👀

**Comment by jasonbahl** [comment]
@justlevine I have a PR open to address this #2269 

To test, you can pull that branch and run `composer install` and `npm install && npm run build`

I tested in an incognito window. 

I was able to confirm the bug in the v1.7 release and confirm that this fix does not add a new entry into the browser history for every change to GraphiQL
