### ISSUE TITLE
Return 403 for anauthenticated requests

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#227]
When requests are not authenticated, a 403 status should be returned. 

Some resources might be public and some might be private, so we don't want to block the entire API for unauthenticated requests, but we do want to respond in some way to let the consumer know that  the request wasn't properly authenticated. 

When a request is made without proper authentication (no valid user is identified with the request) the public data will still be resolved properly and returned in the response. Private data will throw exceptions and return errors (Sorry, you're not allowed to do that), etc. . .

A 403 status can be used by clients to clear out the current user. 

For example, let's say we're in a Single Page App, and we make a query and we get a 403 response back (for whatever reason). We can use that response to clear the current users cached auth tokens, and essentially wipe out that user's "session" and ask them to re-authenticate. . .and we can re-render hiding parts of the app they shouldn't see if they're not authenticated, etc. 

See: http://www.east5th.co/blog/2017/05/15/graphql-authentication-with-apollo-and-react/

**Comment by rcstr** [comment]
Hi, @jasonbahl  - Couldn't find anything on the specs but based on the previous APIS and what I have seen people do when the user is not allowed to look some information the response is just a null object.

**Comment by jasonbahl** [comment]
@rcstr Ya, so for `unauthorized` resolvers, it will resolve as null, catch an error and return the error in the responses `errors`, but for `unauthenticated` requests, the same will happen, _but_ a 403 status will also be returned, along with the normal data/errors. 

The 403 status is just a way to signify back to the consumer that the request isn't properly authenticated. . .could be due to a password reset, an expired auth token, deleted user, etc. . .

That way the client can recognize that authentication needs to happen again. 

See the blog post I linked to in the description which describes things in more detail.

**Comment by jasonbahl** [comment]
addressed by #231
