### ISSUE TITLE
[v1.7.0] ContentType `labels` returning null.

### ISSUE THREAD

**Issue by justlevine** [wp-graphql/wp-graphql#2270]
As of v1.7.0,  querying for labels on a `contentType` returns null. In v1.6.12 it was working correctly.

## To Test

```graphql
{
  contentTypes{
    nodes{
      label
      labels{
        allItems
      }
    }
  }
}
```

I've also set up a clean testing instance. You can visit Settings > Plugins to toggle between v1.7.0 and v1.6.12 of the plugin.
```
 Admin area URL: https://combboot.tastewp.com/wp-admin 
 Username: admin 
 Password: LLQvK0BUdFc 
```
## Expected behavior
(v1.6.12)
![image](https://user-images.githubusercontent.com/29322304/156830270-8114f754-0129-42a0-ba73-cdd59c23129e.png)

## Actual behavior
(v1.7.0)
![image](https://user-images.githubusercontent.com/29322304/156830358-3002d7c6-6328-428b-9e78-3289b0c01397.png)

## Environment
- WP: 5.9.1
- WPGraphQL: 1.7.0
- tested both on localhost (wsl2 Ubuntu 20.04 + devilbox, php 8), and on tastewp (no server details available).

**Comment by jasonbahl** [comment]
@justlevine this might be a model layer / permissions thing. 

In 1.7.0, GraphiQL changed to execute as a public non-authenticated user by default, but you can toggle to execute as an authenticated user by clicking the user icon (or avatar) button in the GraphiQL Toolbar

Labels aren't exposed publicly by WordPress, just in administrative contexts, so WPGraphQL also does not expose them publicly.

I believe this is not a regression, but rather surfacing the value of the ability to toggle between public/authenticated requests in GraphiQL starting with v1.7.0

**Comment by justlevine** [comment]
gosh I really got to remember to check auth, it gets me every time!
