### ISSUE TITLE
Add composer postinstall script to install npm dependencies so developers only have to run one command

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#2273]
As a contributor to WPGraphQL, I would like to only run one command `composer install` to have the plugin ready for local development. 

As of the 1.7.0 release, I also need to run `npm install && npm run build` in order to use GraphiQL

**Comment by jasonbahl** [comment]
@ArmandPhilippot ah! Thanks for calling this out. Yes, the `packages` directory does indeed look like it's not included in the downloads. I've got a PR to address this here: #2278

**Comment by jasonbahl** [comment]
@ArmandPhilippot I just opened another issue with additional context: https://github.com/wp-graphql/wp-graphql/issues/2282

**Comment by jasonbahl** [comment]
> Without being a contributor, a Composer install using [Packagist](https://packagist.org/packages/wp-graphql/wp-graphql) has the same issue. And npm run build fails because packages directory is missing.

The v1.7.2 release does send the `packages` directory to packagist, so you should be able to install wp-graphql via composer, then add a post-install-cmd to _your_ project that changes directories to the WPGraphQL plugin and runs `npm ci && npm run build`, or you could update to use `wpackagist` as the repo (as mentioned above), which includes the built files.

**Comment by ArmandPhilippot** [comment]
@jasonbahl Thanks for this very detailed explanation! I know WPackagist but don't ask why I always use Packagist first as long as it works...

I had just tested the version 1.7.2 and I was just thinking that I might do well to change although now it works by running `npm i && npm run build`. I hadn't thought of `post-install-cmd` but using WPackagist seems like a better solution to me.

Thanks again for the responsiveness and the time given to this long answer!
