### ISSUE TITLE
Multisite generalSettings url field missing in 1.7.x

### ISSUE THREAD

**Issue by ashhitch** [wp-graphql/wp-graphql#2274]
When upgrading a multisite instance to `1.7.1` generalSettings >`url` field is now missing, I see this was being added as its non-standard for multisites.

I had a quick look and looks like this started happening after to change to pass the `TypeRegistry` through  `get_allowed_settings_by_group`.

**Comment by jasonbahl** [comment]
@ashhitch thanks for reporting this! Looking into it now 👀

**Comment by jasonbahl** [comment]
@ashhitch I was able to reproduce this, and I have a fix coming.

**Comment by jasonbahl** [comment]
@ashhitch could you confirm the changes in #2275 work for you? I've tested locally and things are 👌🏻, but would love to have your confirmation as well 😄

**Comment by jasonbahl** [comment]
@ashhitch I had a typo in my last comment. the PR is: https://github.com/wp-graphql/wp-graphql/pull/2276

**Comment by jasonbahl** [comment]
@ashhitch thanks for the confirmation. Got it merged and will get it released shortly!
