### ISSUE TITLE
Pagination cursor not working with meta clauses due to missing meta_type

### ISSUE THREAD

**Issue by andrewmumblebee** [wp-graphql/wp-graphql#2280]
I've been trying to get multiple metakey ordering to work with this plugin.

The only way i've managed to so far is to use meta clauses, as the underlying code breaks if the meta key is used to sort with directly, as when using a cursor it trys to build the query using wp_posts.meta_key rather than the wp_postsmeta table.

To get this working i had to use the below filters.

```php
add_filter(
	'graphql_PostObjectsConnectionOrderbyEnum_values',
	function( $values ) {
		$values['EVENT_DATETIME'] = [
			'value'       => 'event_datetime',
			'description' => 'Datetime of the event.',
		];

		return $values;
	}
);

/**
* change key in place so that order of keys is unaffected.
*/
function change_key( $array, $old_key, $new_key ) {

	if ( ! array_key_exists( $old_key, $array ) ) {
			return $array;
	}

	$keys                                    = array_keys( $array );
	$keys[ array_search( $old_key, $keys ) ] = $new_key;

	return array_combine( $keys, $array );
}


add_filter(
	'graphql_post_object_connection_query_args',
	function ( $query_args, $source, $args, $context, $info ) {

		$time_now    = gmdate( 'Y-m-d H:i:s' );
		$is_upcoming = $args['where']['isUpcoming'];

		if ( isset( $args['where']['orderby'] ) && is_array( $args['where']['orderby'] ) ) {

			foreach ( $args['where']['orderby'] as $orderby ) {

				if ( isset( $orderby['field'] ) && 'event_datetime' === $orderby['field'] ) {
					// have to change the key or it will break pagination, due to trying to map to wp_posts.
					$query_args['orderby']                          = change_key( $query_args['orderby'], 'event_datetime', 'event_datetime_clause' );
					$query_args['orderby']['event_datetime_clause'] = $orderby['order'];

					if ( isset( $args['last'] ) ) {
						// reverse ordering with cursor
						$query_args['orderby']['event_datetime_clause'] = $orderby['order'] === 'ASC' ? 'DESC' : 'ASC';
					}

					/**
					 * Essentially checks for something that won't exist, so we can use the meta key in the query
					 */
					$query_args['meta_query']['event_datetime_clause'] = [
						'key'     => 'event_datetime',
						'compare' => '!=',
						'value'   => '1980-01-01 00:00:00',
						'type'    => 'DATETIME',
					];
				}
			}
		}

		return $query_args;
	},
	10,
	5
);

```

This should allow for multiple meta keys to be using in query sorting, so i could register more orderby enum values, i.e. a boolean to sort by first, etc.

However, when cursor pagination is involved in the query it seems to break and returns no nodes after the first page sometimes, or other results, as the cursor doesn't get built using the meta_clause meta_key.

I managed to fix this by altering the wp-graphql code here. 

https://github.com/wp-graphql/wp-graphql/blob/0a8e902a83c745ef565c688997ca78d156ac565a/src/Data/Cursor/PostObjectCursor.php#L271

The $meta_type is undefined as it trys to grab it from the query rather than using the type that is defined within the meta_clause.

To fix it i had to change the following methods.

```php
/**
	 * Get AND operator for given order by key
	 *
	 * @param string $by    The order by key
	 * @param string $order The order direction ASC or DESC
	 *
	 * @return void
	 */
	private function compare_with( $by, $order ) {

		switch ( $by ) {
			case 'author':
			case 'title':
			case 'type':
			case 'name':
			case 'modified':
			case 'date':
			case 'parent':
				$by = 'post_' . $by;
				break;
		}

		$value = $this->get_cursor_post()->{$by};

		/**
		 * Compare by the post field if the key matches an value
		 */
		if ( ! empty( $value ) ) {

			$this->builder->add_field( "{$this->wpdb->posts}.{$by}", $value, null, $order );

			return;
		}

		/**
		 * Find out whether this is a meta key based ordering
		 */
		$meta = $this->get_meta_key( $by );
               
		if ( $meta ) {
			$this->compare_with_meta_field( $meta , $order );

			return;
		}

	}

	/**
	 * Compare with meta key field
	 *
	 * @param array $meta post meta
	 * @param string $order    The comparison string
	 *
	 * @return void
	 */
	private function compare_with_meta_field( array $meta, string $order ) {
		$meta_type  = $meta['type'];
		$meta_value = get_post_meta( $this->cursor_offset, $meta['key'], true );

		$key = "{$this->wpdb->postmeta}.meta_value";

		/**
		 * WP uses mt1, mt2 etc. style aliases for additional meta value joins.
		 */
		if ( 0 !== $this->meta_join_alias ) {
			$key = "mt{$this->meta_join_alias}.meta_value";

		}

		$this->meta_join_alias ++;

		$this->builder->add_field( $key, $meta_value, $meta_type, $order, $this );
	}

       /**
	 * Get the actual meta key if any
	 *
	 * @param string $by The order by key
	 *
	 * @return array|null
	 */
	private function get_meta_key( $by ) {

		if ( 'meta_value' === $by || 'meta_value_num' === $by ) {
			return [
                             "key" => $this->get_query_var( 'meta_key' ),
                             "type" => $this->get_query_var( 'meta_type' )
                        ];
		}

		/**
		 * Check for the WP 4.2+ style meta clauses
		 * https://make.wordpress.org/core/2015/03/30/query-improvements-in-wp-4-2-orderby-and-meta_query/
		 */
		if ( ! isset( $this->query_vars['meta_query'][ $by ] ) ) {
			return null;
		}

		$clause = $this->query_vars['meta_query'][ $by ];

		return $clause;
	}
```

I'm not sure if i'm using a convoluted way to order by multiple meta_keys, but I've only seen examples that work with one meta_key for the ordering in examples.

Happy to put in a PR if you'd like, thanks!

**Comment by jasonbahl** [comment]
@andrewmumblebee thanks for the detailed issue! 

I typically avoid (and recommend users avoid) meta queries, as they're expensive and have even been known to take sites down, so it makes sense that there's places in the codebase that could better support users that need to use meta queries, even if recommended against. 

I don't want to make meta querying so easy with WPGraphQL that folks are taking their servers down and blaming WPGraphQL, but at the same time, I want to enable folks that have decided it's necessary for their application to be able to do it. 

> Happy to put in a PR if you'd like, thanks!
Ya, please do. 

If you're comfortable adding a test under the `tests/wpunit` directory, even better! Would be good to have a tested scenario. 

Something like: 

- create some posts with some meta values
- filter the schema to support querying by the meta
- execute a graphql query with said meta query
- assert that we're getting the expected results

**Comment by jasonbahl** [comment]
@andrewmumblebee also, if you could provide detailed steps to reproduce the issue in the first place, that would be 🔥 

Something like: 

- create and publish a post
- attach x meta value to y meta_key on the post
- add x field to the schema
- query x query
- see that x post is not in the results

etc. 

The more info I have on being able to get my local WordPress to the same state as you, the better I can understand the situation, and the better I can help get to a resolution. 🙏🏻

**Comment by justlevine** [comment]
Hey @andrewmumblebee ,

Are you still facing this issue? Recent plugin releases have fixed a lot of issues with pagination cursors, so it's possible this got fixed as well, but without a replicable test case, I have no way to confirm.

If we don't hear back from you, I'm going to assume things are working and mark this as closed.
