### ISSUE TITLE
GraphiQl not working in Safari

### ISSUE THREAD

**Issue by Bowriverstudio** [wp-graphql/wp-graphql#2285]
The GraphiQL interface for the same site works well on chrome but not safari.
<img width="1782" alt="Screen Shot 2022-03-08 at 11 01 40 AM" src="https://user-images.githubusercontent.com/36542929/157302039-4810c878-3de5-4cc9-8074-cfc8352c32f7.png">

Safari Version: Version 14.0.3 (16610.4.3.1.7)
WordPress: Current version: 5.9.1
GraphQL API: Version 1.7.2

**Comment by mindctrl** [comment]
I'm not seeing this on:
Safari Version 15.3 (17612.4.9.1.8)
WP 5.9.1
WPGraphQL 1.7.2

![image](https://user-images.githubusercontent.com/1254870/157330842-77604e85-39aa-48ad-bcaa-6448267c49fe.png)

**Comment by Bowriverstudio** [comment]
@mindctrl  Must be something specific to my setup then.  I'll close this and thanks for looking into it.

**Comment by mindctrl** [comment]
Could be the different Safari version.

Also worth noting I see multiple warnings in the console with:

> Each child in a list should have a unique "key" prop

Not sure if that would break the app in a previous version of Safari, but wanted to mention it just in case.
