### ISSUE TITLE
Post Types Order by Nsp Code prevents GraphQL pagination on import into Gatsby

### ISSUE THREAD

**Issue by justinradomski** [wp-graphql/wp-graphql#2300]
When using the Post Types Order plugin by Nsp Code on posts types with more than 100 posts, you'll notice that only the first 100 posts are pulled into Gatsby's GraphQL and they come in with a bunch of duplicate post errors in the console. 

Initially it will appear that 200 posts are pulled in `success  gatsby-source-wordpress  Post - 14.561s - fetched 200`, but that's only because of the duplicates.

For now I have switched to Simple Custom Post Order by Colorlib which does not seem to have the same issue.

**Comment by justlevine** [comment]
It shouldn't be assumed that 3rd party plugins are compatible with WPGraphQL 
Putting aside any possible issues with `graphql_max_connection_limit`(https://www.wpgraphql.com/filters/graphql_connection_max_query_amount/), my guess is that Post Types Order is doing something weird when it updates the menu order, possibly due to [how late they're hooking their filters](https://plugins.trac.wordpress.org/browser/post-types-order/trunk/include/class.cpto.php#L25), but I havnt contacted them myself.

I'd suggest you contact Nsp Code support if you wish to use their plugin in the future.

**Comment by jasonbahl** [comment]
@justinradomski Hey! I see that you've already switched to the "Simple Custom Post Order" plugin and it seems to be working well for you. 👏🏻 

# Using Post Type Order plugin with WPGraphQL

For anyone else that stumbled upon this issue that wants to use "Post Type Order" with WPGraphQL, I dug into the conflict and have a working solution.

Adding the following snippet to your `functions.php` (or wherever you put your custom code) should work: 

```php
add_action( 'pre_get_posts', function () {

	// access the custom post type order class
	global $CPTO;

	// if WPGraphQL isn't active or CPTUI isn't active, carry on and bail early
	if ( ! function_exists( 'is_graphql_request' ) || ! is_graphql_request() || ! $CPTO ) {
		return;
	}

	// Remove the Post Type Order plugin's "posts_orderby" filter for WPGraphQL requests
	// This filter hooks in too late and modifies the SQL directly so WPGraphQL
	// can't properly map the orderby args to generate the SQL for proper pagination
	remove_filter( 'posts_orderby', [ $CPTO, 'posts_orderby' ], 99 );

	// Add a filter
	add_filter( 'graphql_post_object_connection_query_args', function ( $args, $source, $input_args, $context, $info ) {

		$orderby = [];

		// If the connection has explicit orderby arguments set,
		// use them
		if ( ! empty( $input_args['where']['orderby'] ) ) {
			return $args;
		}

		// Else use any orderby args set on the WP_Query
		if ( isset( $args['orderby'] ) ) {
			$orderby = [];

			if ( is_string( $args['orderby'] ) ) {
				$orderby[] = $args['orderby'];
			} else {
				$orderby = $args['orderby'];
			}
		}

		$orderby['menu_order'] = 'ASC';
		$args['orderby']       = $orderby;

		return $args;
	}, 10, 5 );

});
```

### What this does

First, this hooks into `pre_get_posts` which fires when WP_Query is executing. 

This then checks to see if the request is a GraphQL request and whether Post Types Order plugin class is available as a global. If these conditions are not met, nothing happens. If these conditions are met, we carry on. 

Next, we remove the "posts_orderby" filter from the Post Types Order plugin, as it was overriding WPGraphQL's ordering which is needed for cursor pagination to work properly. 

Then, we add our own filter back to WPGraphQLs Post Object Connection query args and set the orderby to be `menu_order => 'ASC'` 

----

I've published this solution as a "recipe" on the WPGraphQL website as well: 

https://www.wpgraphql.com/recipes/fix-pagination-conflict-with-the-post-type-order-plugin/
