### ISSUE TITLE
The filter commentType for commets doesn't work 

### ISSUE THREAD

**Issue by Talented-Business** [wp-graphql/wp-graphql#2308]
query MyQuery {
  comments(
    where: {commentType: "custom_comment", contentId: "67"}
  ) {
    edges {
      node {
        content
        type
        databaseId
      }
    }
  }
}
When usign above query, it doesn't filter the comments, it returns all comments.
Please fix it.

**Comment by jasonbahl** [comment]
This functionality appears to be working. 

I inserted 3 comments into the database related to post id `1074`

2 are of the comment_type: `comment` and one is `pingback`

![Image](https://user-images.githubusercontent.com/1260765/182487797-6d4f54ac-24a9-4bca-9523-36eefa4527fc.png)

I can filter by `commentType: "comment"` and get just the comments:

![Image](https://user-images.githubusercontent.com/1260765/182487865-28b5bde8-2734-487a-ae4f-2ee8331e54cd.png)

Or I can filter by `commentType: "pingback"` and get just the pingback:

![Image](https://user-images.githubusercontent.com/1260765/182487942-0e31eacc-c491-4f0b-8bae-eb880a83c7f0.png)
