### ISSUE TITLE
The Filter hook comment_text should contain 3 params such as apply_filters( 'comment_text', $comment_text, $comment, $args )

### ISSUE THREAD

**Issue by Talented-Business** [wp-graphql/wp-graphql#2309]
In 168 line of /src/Model/Comment.php, 

return $this->html_entity_decode( apply_filters( 'comment_text', $content ), 'contentRendered', false );

This comment_text hook generates an error because it has only one param.

In 1028 line wp-includes/comment-template.php, you can find the following code.
       /**
	 * Filters the text of a comment to be displayed.
	 *
	 * @since 1.2.0
	 *
	 * @see Walker_Comment::comment()
	 *
	 * @param string          $comment_text Text of the current comment.
	 * @param WP_Comment|null $comment      The comment object. Null if not found.
	 * @param array           $args         An array of arguments.
	 */
      echo apply_filters( 'comment_text', $comment_text, $comment, $args );

**Comment by justlevine** [comment]
Per [#24913](https://core.trac.wordpress.org/ticket/24913#comment:1):
>In the first (`/wp-includes/comment.php`), the `$comment` variable contains just the comment text. In the second (`/wp-includes/comment-template.php`), the `$comment` variable contains the actual comment object itself (based on the return of get_comment( $comment_ID )).
>
>So the filters are filtering the same fields. The issue then becomes the number of parameters and that, too, is not a bug.
>
>The first comment text filter is used specifically to filter the text of the comment before things like inserting it into the database. **The second is used when filtering the text of the comment before displaying it on a page - this follows the pattern of not trusting data before inserting it in the DB and also not trusting the data when pulling it back out.** Using the same filter here helps us use exactly the same rules to filter the content both pre and post DB.

(emphasis mine)

Following the text I bolded, we should indeed be passing `$this->data` to the filter. `WP_REST_Comments_Controller::prepare_item_for_reponse()` does this as well ([line 1090](https://developer.wordpress.org/reference/classes/wp_rest_comments_controller/prepare_item_for_response/))
