### ISSUE TITLE
Wordpress Error: Undefined property: WP_Post_Type::$graphql_single_name	

### ISSUE THREAD

**Issue by esilverman682** [wp-graphql/wp-graphql#2315]
Getting this error when opening up ACF custom fields.

wp-content/plugins/faustwp/includes/replacement/callbacks.php:151

WPE\F\R\post_preview_link()wp-includes/class-wp-hook.php:307apply_filters('preview_post_link')wp-includes/link-template.php:1428

get_preview_post_link()wp-admin/edit-form-advanced.php:121

All custom fields are filled out correctly. Sorry Im bit of a novice with this.

**Comment by justlevine** [comment]
Hey @esilverman682 ,

At first glance this seems to be an issue with FaustJS, which was [fixed 2 weeks ago](https://github.com/wpengine/faustjs/commit/a90eff5c8c224c7bbbc15cec9ae1bcb931021a0a) and I'd assume will be in the next release.

Can you disable the FaustWP plugin temporarily and open up ACF to confirm?

**Comment by esilverman682** [comment]
1. Turned FaustWP plugin off
2. Clicked Custom Field (ACF) -> no error was found

**Comment by justlevine** [comment]
@esilverman682 glad to hear it!

If you dont want to wait for the next FaustWP plugin release ( and assuming you're not running in production yet), I suggest you download the plugin from the [`canary` branch](https://github.com/wpengine/faustjs/tree/canary/plugins/faustwp).

Alternatively, you could also leave the faust plugin disabled while you configure ACF, and reenable when you're done. From my understanding of the code throwing the issue, it shouldnt affect anything on the frontend.
