### ISSUE TITLE
setting `wp_block` to `show_in_graphql` (reusable blocks post type) creates the graphql type but querying its nodes always returns `[]` or `null` for specific items

### ISSUE THREAD

**Issue by tsdexter** [wp-graphql/wp-graphql#2344]
Remember, an issue is not the place to ask general questions. You can use [Slack](https://wp-graphql.slack.com) for that ([join here](https://join.slack.com/t/wp-graphql/shared_invite/zt-3vloo60z-PpJV2PFIwEathWDOxCTTLA)).

Before you open an issue, please check if a similar issue already exists or has been closed before.

### When reporting a _bug_, please be sure to include the following:
- [x] A descriptive title
- [x] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)

1. create a new WP install with only WPGraphQL plugin and add code to your themes `functions.php` file:

```
function custom_post_type_args( $args, $post_type ) {
    if ( $post_type == "wp_block" ) {
      $args['show_in_graphql'] = true;
      $args['graphql_single_name'] = 'reusableBlock';
      $args['graphql_plural_name'] = 'reusableBlocks';
    }

    return $args;
}
add_filter( 'register_post_type_args', 'custom_post_type_args', 20, 2 );
```
2. create a new post and add a block to it, then save that block as a reusable block
3. Query for `reusableBlocks` in GraphiQL:

```
query NewQuery {
  reusableBlocks {
    nodes {
      id
      title
    }
  }
}
```

which returns: 

```
"data": {
    "reusableBlocks": {
      "nodes": []
    }
  },
```

- [x] What version of `WPGraphQL` you're using, and the platform(s) you're running it on
1.8.0
- [x] What other plugins you're using
none
- [x] The behavior you expect to see, and the actual behavior
I should see the reusable block data. This was working previously but when I came back to work on the project after a few months it was no longer. Wordpress was auto-updated since then, but I'm not sure which version it was working on.

**Comment by justlevine** [comment]
hey @tsdexter 
IIRC, the `WP_Block` post type is not publicly queryable by default. What happens if you add `$args['publicly_queryable'] = true;` to your `custom_post_types()` function?

**Comment by tsdexter** [comment]
@justlevine that is working, weird though...I didn't have that previously and it was working - I still have the gatsby site from an old build running with reusable block content in it

**Comment by jasonbahl** [comment]
@tsdexter this was actually a bug in WPGraphQL (exposing data that it shouldn't). It was fixed in v1.6.7. 

Sadly, a lot of folks were using this bug as a feature, and the bugfix broke their experiences. In retrospect, I probably should have made more noise about this change. 

But ya, @justlevine solution should work if you do indeed want that post type to be publicly queryable. The default rule, though, is that those entries are only available to logged in users. Once a block is added to WordPress content, it's accessible via querying the content, but the raw re-usable blocks are still only something logged in users can interact with in a standard WordPress install.

**Comment by tsdexter** [comment]
@jasonbahl thanks for the background...I was searching through commits for a related change but didn't find it.

I am using the raw `wp_block` content, combined with an ACF field on `menuItem` to build a "mega menu" with HTML content. 

<img width="425" alt="image" src="https://user-images.githubusercontent.com/4126987/164315556-d00024c7-c33a-4cf4-9b6d-966d29a174a1.png">

I can't think of a security or other reason to not have reusable block data public - I would guess it's simply because they hide the `wp_block` type from all other UI as well, it's essentially a "hidden" post type. 

If you know of/can think of another reason, I could easily refactor with a dedicated post type. Thoughts?

**Comment by tsdexter** [comment]
@jasonbahl come to think of it... I could be wrong, I haven't dug too far into the gutenberg/graphql integrations yet, but I'll likely still need the `ReusableBlock` type available in the future anyway as when we eventually move to retrieving gutenberg data instead of HTML, any of the reusable blocks will just give me an ID attribute and I'll have to look up the blocks/content that make up the reusable block separately to render?

**Comment by jasonbahl** [comment]
@tsdexter ya, I don't think there's anything wrong (most likely) with exposing it for your site. 

But in general, WPGraphQL needs to follow this default "access control" as post types that are registered as non publicly queryable might indeed contain sensitive information. It's all extendable, so individual sites can override these rules as you have. If you don't have information in that post type that you want hidden, what you've done should be fine!

**Comment by jasonbahl** [comment]
>  I haven't dug too far into the gutenberg/graphql integrations yet, but I'll likely still need the ReusableBlock type available in the future anyway as when we eventually move to retrieving gutenberg data instead of HTML, any of the reusable blocks will just give me an ID attribute and I'll have to look up the blocks/content that make up the reusable block separately to render?

So, this is kind of similar to `content` vs `raw content` in both the WP REST API and WP GraphQL. 

The reusable blocks will remain something that logged in users can see and interact with, but public facing users will only see the results of the blocks _after_ they've been passed through filters. 

So yes, some information of re-usable blocks will end up being output to public users, but not all information. 

Like, in a traditional WordPress, the rendered HTML will be returned to public facing users, _but_ not all information will be exposed. Public users won't know the database Id of the reusable block, they won't even know that the reusable block, on its own, is another post_type, etc. 

Again, there's likely nothing "wrong" with exposing this information for this post_type for your site. Just dropping some more context on the topic.

**Comment by tsdexter** [comment]
@jasonbahl thanks again for the context

Are you referring to how a future gutenberg integration would return reusable blocks? what I would expect from an ideal gutenberg integration would be to get the list of blocks with their attributes, just the way they are received in gutenberg. I wouldn't want to get anything pre-rendered, innerHTML, etc... I would expect to never have to use `dangerouslySetInnerHTML` but rather render them myself with react components so I can add in frontend functionality such as `useState` etc instead of still relying on jQuery or other front end libraries.

So for a post with a paragraph and a reusable block I would expect something like below with a `ref` attribute for the ID  which I then look up it's content/list of blocks via the `ref` attribute. (this could also be in a flat list with `parentId`s instead of nested `innerBlocks` to determine the hierarchy.

```json
blocks: [
  {
    "name": "core/heading",
    "className": "",
     "attributes": {
         "content": "Some Heading",
         "level": 2
     },
     "innerBlocks": []
  },
  {
    "name": "core/block",
    "className": "",
    "attributes": {
        "ref": 145964
    },
    "innerBlocks": []
  }
] 
```

This way I could use my same (or similar) react `save` and/or `edit` components in the front end that I use in gutenberg.  As well as possibly using core wordpress `save` components or map some custom 'frontend core blocks` component library. 

Is this a part of the current discussions or is it going in a different direction?

**Comment by jasonbahl** [comment]
@tsdexter your idea is the same as mine! 

The difference being a reusable block only becomes publicly queryable when it's used within an already publicly queryable context. 

For example, a published post. 

You would be able to query the blocks of the published post, but not be able to query a list of all possible reusable blocks (as you've made possible with your filter). Of course, you could also make all reusable blocks public with that filter but default WPGraphQL will keep them private but expose just the ones used in public contexts.

**Comment by tsdexter** [comment]
@jasonbahl  OK great. I was worried for a minute you were planning to build it out with something like `parse_blocks()` which, iirc, only returns attributes with no `source` defined - for example, none of the attributes that are sourced from the HTML such as `content` on a `core/paragraph` or `level` on a `core/heading`. 

Do you have any ideas yet on how to retrieve _**all**_ of the attributes server side - I would assume you'd have to have some combination of getting the blocks attributes definition and parsing the HTML? 

I've only just started playing around with it but for now my experiments to get all blocks attributes ahead of your integration are essentially saving the blocks JSON to post_meta on every change in gutenberg as a string and then add a custom field to the graphql `Page` type that returns the string which I can then loop over in react and render accordingly. 

Here's the code I have to get the JSON - it doesn't save to the database yet on publish/update yet, but it works in the frontend to get all the attribute data required. As far as I can tell, you've got a big task ahead trying to get the data server side and make Types out of it to get proper graphql support. Good luck 🍺 !

```js
wp.data.subscribe(async () => {
  console.log("subscribeToChanges");
  const blocks = wp.data.select("core/editor").getBlocks();
  // console.time("stringifyBlocks");
  const blocksJson = JSON.stringify(blocks);
  // console.timeEnd("stringifyBlocks");
  const savedBlocks = wp.data
    .select("core/editor")
    .getEditedPostAttribute("meta").blocks; // this needs to compare the saved value not edited
  // console.time("compareBlocks");
  if (blocksJson !== savedBlocks) {
    // console.time("saveBlocks");
    wp.data.dispatch("core/editor").editPost({ meta: { blocks: blocksJson } }); // this isn't currently saving to db
    // console.timeEnd("saveBlocks");
  }
  // console.timeEnd("compareBlocks");
});
```

ps. where is the proper discussion for gutenberg integration happening?
