### ISSUE TITLE
Restrict Endpoint to Authenticated Users

### ISSUE THREAD

**Issue by Kosyarik** [wp-graphql/wp-graphql#2347]
Hi there. I use WPGraphQL JWT Authentication + WP GraphQL. When I restrict access to an endpoint, how do I access the token from another service. I'm trying to configure a node server.

**Comment by jasonbahl** [comment]
I believe this is covered here: https://www.wpgraphql.com/recipes/allow-login-mutation-to-be-public-when-the-endpoint-is-fully-restricted/
