### ISSUE TITLE
Question: Can't get user information when not authorized

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#2348]
----
This was emailed to me. I'm opening it as a Github issue for public reference.
----

Hello Jason. I'm using your software for my Ecommerce site. While trying to get products one issue occurs - I can't get Reviews Author's information if I'm not authorized, it returns null. But when I send the same request with the Authorization header it works fine.

I found a similar question and also your comments there: https://github.com/wp-graphql/wp-graphql/issues/1476 but nobody answered properly.

Here is the screenshots if you need:
one with authentication :

![image](https://user-images.githubusercontent.com/1260765/164735004-1e9aa9a0-3f82-4d5e-9e5f-e990487f146c.png)

and other without auth:

![image-1](https://user-images.githubusercontent.com/1260765/164735053-66774268-1378-4cdc-9a5a-bafb92a4d452.png)

My question is: is there some way to bring the author data without authorization ? Customers need to know the product's reviews and without author's verification it will seem fake.

I would be very glad if you responded to me.

**Comment by jasonbahl** [comment]
Further digging into how WordPress core handles this situation. 

Users are still only _partly_ public if they've not published posts. 

If a User has an approved comment, some information is returned in the WP REST API with the comment, including the ID of the author. 

![CleanShot 2022-04-22 at 10 29 52](https://user-images.githubusercontent.com/1260765/164756278-6d2e5dcc-6b7e-49a1-8d0a-979dd207e28f.png)

But, the ID cannot be used to query the User directly. 

![CleanShot 2022-04-22 at 10 30 52](https://user-images.githubusercontent.com/1260765/164756389-9021c420-60ee-4ce6-bc10-69de0bf79034.png)

Nor will the user show up in a list of users: 

here we're seeing only 1 user listed at the `users` endpoint, even though user with ID 4 has a published comment and has some data publicly visible already.

![CleanShot 2022-04-22 at 10 24 16](https://user-images.githubusercontent.com/1260765/164755994-29408223-109e-4a42-aa4b-b9f7e9d01298.png)

-----

## Recommendation for WPGraphQL

I believe we can resolve this by adjusting how the Comment.author connection resolves. 

Currently, this connection attempts to load the `User` if it was authored by a user, and the Model Layer ends up restricting the node from returning, because the user is not considered public. 

I believe we can adjust the resolver for the `Comment.author` connection to load the public `CommentAuthor` node by default, but return the `User` node if the request is from an authenticated user with permission to view User nodes.

**Comment by jasonbahl** [comment]
@datomezz: I've opened a PR that resolves this issue: https://github.com/wp-graphql/wp-graphql/pull/2350

**Comment by datomezz** [comment]
@jasonbahl thanks for response. Can you show example how you update resolver and change **User** to **CommentAuthor** ?
