### ISSUE TITLE
Mutations report required fields to unauthenticated users

### ISSUE THREAD

**Issue by nickcernis** [wp-graphql/wp-graphql#2365]
When sending a mutation with missing `'non_null'` input fields, WPGraphQL reports the names of the missing fields in the error response to unauthenticated users.

It only reveals a partial schema so the impact is very low. But it allows people to obtain information about field names and types that's normally only available if “Enable Public Introspection” is enabled.

### To reproduce

Create and activate this plugin:

```php
<?php
/* Plugin Name: Test Issue 2365 */

add_action( 'init', function() {
	register_post_type( 'athlete', [
		'label' => 'Athletes',
		'show_ui' => true,
		'public' => true,
		'show_in_graphql' => true,
		'show_in_rest' => true,
		'graphql_single_name' => 'Athlete',
		'graphql_plural_name' => 'Athletes',
	] );
} );

add_action( 'graphql_register_types', function() {
	$fields = [
		'dateOfBirth' => [
			'type' => [ 'non_null' => 'String' ]
		],
		'passedDopingTest' => [
			'type' => [ 'non_null' => 'Boolean' ],
		],
		'homeAddress' => [
			'type' => [ 'non_null' => 'String' ]
		],
		'phoneNumber' => [
			'type' => [ 'non_null' => 'String' ]
		],		
	];	

	foreach ( $fields as $name => $args ) {
		register_graphql_field( 'Athlete', $name, $args );
		register_graphql_field( 'CreateAthleteInput', $name, $args );
		register_graphql_field( 'UpdateAthleteInput', $name, $args );
	}
} );
```

Send this query without authenticating:

```
mutation {
  createAthlete(input: { title: "test" }) {
    athlete { id }
  }
}
```

### Observed behavior

You'll see this response:

```
{
  "errors": [
    {
      "message": "Field CreateAthleteInput.dateOfBirth of required type String! was not provided.",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 2,
          "column": 24
        }
      ]
    },
    {
      "message": "Field CreateAthleteInput.homeAddress of required type String! was not provided.",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 2,
          "column": 24
        }
      ]
    },
    {
      "message": "Field CreateAthleteInput.passedDopingTest of required type Boolean! was not provided.",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 2,
          "column": 24
        }
      ]
    },
    {
      "message": "Field CreateAthleteInput.phoneNumber of required type String! was not provided.",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 2,
          "column": 24
        }
      ]
    }
  ],
  "extensions": {
    "debug": [
      {
        "type": "DEBUG_LOGS_INACTIVE",
        "message": "GraphQL Debug logging is not active. To see debug logs, GRAPHQL_DEBUG must be enabled."
      }
    ]
  }
}
```

Normally we can't get any such field data because public introspection is disabled by default:

```
query AthleteFields {
  __type(name: "Athlete") {
    fields {
      name
    }
  }
}
```

```
"message": "GraphQL introspection is not allowed, but the query contained __schema or __type",
```

### Expected behavior

I expected a response that matches the one when the same fields are not 'non_null':

```php
	$fields = [
		'dateOfBirth' => [
			'type' => 'String',
		],
		'passedDopingTest' => [
			'type' => 'Boolean',
		],
		'homeAddress' => [
			'type' => 'String',
		],
		'phoneNumber' => [
			'type' => 'String',
		],		
	];	
```

Response to same query as above (unauthenticated):

```
{
  "errors": [
    {
      "message": "Sorry, you are not allowed to create Athletes",
      "extensions": {
        "category": "user"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createAthlete"
      ]
    }
  ],
  "data": {
    "createAthlete": null
  },
  "extensions": {
    "debug": [
      {
        "type": "DEBUG_LOGS_INACTIVE",
        "message": "GraphQL Debug logging is not active. To see debug logs, GRAPHQL_DEBUG must be enabled."
      }
    ]
  }
}
```

### Potential fix

Perhaps add a `permissionCallback` arg to the `register_graphql_mutation` config (to mirror `permission_callback` from Core's `register_rest_route`)?

The callback could run before input fields are checked and avoid the need for `mutateAndGetPayload` to double as an authentication function.

It might also make mutation permissions more hookable to help devs adjust them at the CPT-level. Changing mutation permissions for one CPT is awkward today because permission checks are baked into the `mutate_and_get_payload` anonymous function in `wp-graphql/src/Mutation/PostObjectCreate.php` so they're not very hookable:

https://github.com/wp-graphql/wp-graphql/blob/c1c2255762394b5ec56ce6b8f6e56cbb212433b7/src/Mutation/PostObjectCreate.php#L200-L206

### Environment
- WPGraphQL 1.8.1
- WP 5.9.3

**Comment by justlevine** [comment]
Hey @nickcernis 

I believe this is by design. If the mutation _itself_ is public, the user needs to know what inputs are required. @jasonbahl can you confirm?

You could _possibly_ work around this by setting the mutation inputs as nullable, and then throwing a custom error message if theyre not included (using the `graphql_post_object_insert_post_args` filter).

```php
add_action( 'graphql_register_types', function() {
	// register fields on Athlete as non_null
	register_graphql_fields( 'Athlete', [
		'dateOfBirth' => [
			'type' => [ 'non_null' => 'String' ]
		],
		'passedDopingTest' => [
			'type' => [ 'non_null' => 'Boolean' ],
		],
		'homeAddress' => [
			'type' => [ 'non_null' => 'String' ]
		],
		'phoneNumber' => [
			'type' => [ 'non_null' => 'String' ]
		],		
	] );
	
	// Register the mutation inputs as nullable.
	$fields = [
		'dateOfBirth' => [
			'type' => 'String'
		],
		'passedDopingTest' => [
			'type' => 'Boolean'
		],
		'homeAddress' => [
			'type' => 'String'
		],
		'phoneNumber' => [
			'type' => 'string'
		]
	];
	register_graphql_fields( 'CreateAthleteInput', $fields );
	register_graphql_fields( 'UpdateAthleteInput', $fields);
} );

// Throw error mutations with generic messages.
add_filter( 'graphql_post_object_insert_post_args' function( $post_args, $input, $post_type_object ) {
	if ( 'athlete' !== $post_type_object->name ) {
		return $post_args;
	}
	
	if ( empty( $input['dateOfBirth'] ) || empty( 'passedDopingTest' ) || ... ) {
		throw new UserError( __( 'Some generic error message, 'my-text-domain' );
	}
	
	$post_args['date_of_birth'] = $input['dateOfBirth'];
	...
	return $post_args;
}, 10, 3 );
```
> ### Potential fix
> Perhaps add a permissionCallback arg to the register_graphql_mutation config (to mirror permission_callback from Core's register_rest_route)?
>
>The callback could run before input fields are checked and avoid the need for mutateAndGetPayload to double as an authentication function.
>
>It might also make mutation permissions more hookable to help devs adjust them at the CPT-level. Changing mutation permissions for one CPT is awkward today because permission checks are baked into the mutate_and_get_payload anonymous function in wp-graphql/src/Mutation/PostObjectCreate.php so they're not very hookable:

Even if the original issue falls into the 'feature-not-a-bug' category, these are great suggestions. Mutation hooks definitely need some tlc😇.

**Comment by nickcernis** [comment]
Thanks for the thoughts, @justlevine!

>  If the mutation itself is public, the user needs to know what inputs are required

But surely only if they have permission to make the mutation? If they can't create/update posts, knowing what fields they're omitting won't help them.

It seems fine to report missing fields, but only to users who can make the mutation.

**Comment by justlevine** [comment]
That's a great point about order of operations - thanks for clarifying!

**Comment by jasonbahl** [comment]
So, Schema validation runs _before_ execution. 

If a submission isn't valid (doesn't include a required field, for example), this is known before any execution begins and can return quickly before attempting to execute. 

This seems to be proposing that we flip and execute before validating if the request was even valid to start 🤔

**Comment by justlevine** [comment]
> This seems to be proposing that we flip and execute before validating if the request was even valid to start 🤔

At it's extreme yes, but a middle ground approach would be breaking the input _content_ validation out of `mutate_and_get_payload()`, so we could better show/obfuscate those errors based on permissions, and more easily than my workaround example using `graphql_post_object_insert_post_args`.

**Comment by jasonbahl** [comment]
What's the _actual_ concern here?

It feels like we're assuming there's some sort of security vulnerability if public users know about fields in the Schema?

Public introspection can be disabled to reduce the risk of bad actors enumerating the schema and _more easily_ making batch requests, but nothing is preventing a bad actor from making bulk requests without knowing the Schema. 

Preventing public introspection isn't a true security feature, it's more security through obscurity. 

The resolvers and the execution layer are where _actual_ security really needs to be handled. 

If a public user was able to submit arbitrary mutations (because they didn't know the schema) until they got one to work, but it returned an error that a specific field was required, what's the threat? What's the harm in a public user knowing that xx field is required?

I can publicly introspect just about any WordPress site's REST API and find out what fields are required for any given POST operation, but I still can't do anything with that information if I don't have permission to do something with it. 

Ex: https://wordpress.org/wp-json/wp/v2, https://wpengine.com/wp-json/wp/v2, https://ma.tt/wp-json/wp/v2, https://techcrunch.com/wp-json/wp/v2/

I don't think there's real value in flipping GraphQL on its head and trying to execute requests _before_ validating the validity of the request before execution, and I don't think there's an actual security issue returning an error that a required field is missing, even if public introspection is missing. 

I'd be curious to learn more as to why this is perceived to be a real issue. 

I do think there's room to improve hooks around mutations, but I think "leaking" required fields is probably not something we need to optimize for.

**Comment by nickcernis** [comment]
Thanks for the review and feedback on this, @jasonbahl and @justlevine!

> What's the actual concern here?

Some potential concerns from exposing data before auth checks, from lower to higher concerns:

- I'm a competitor trying to figure out how you structure data or what data you store.
- I'm an attacker profiling thousands of WP sites. I can use this leak to see what data you store about your models to determine if you're a high-value target or not.
- As WPGraphQL grows in complexity, not performing auth checks on requests as the very first step increases the risk that we'll accidentally expose other data to users who shouldn't have access to it.

I understand if the response to all of this is, “reworking WPGraphQL to do auth before type/input checking is more work than these concerns justify”. I just wanted to file this anyway because IMO the ideal design would be to do auth checks up front.

Happy to file a separate issue around mutation hooks if you want to consider that separately.

**Comment by jasonbahl** [comment]
Yes mutation hooks/filters would be a separate consideration for sure! Let's treat that as a different issue. 

I don't believe there's any vulnerability in exposing the schema and even less of one if only bits are exposed when a bad actor tries to submit an operation that would be rejected. 

Like I pointed out, I can already introspect almost any WP site and see what POST arguments are allowed for arbitrary data sets. I can see that WPEngine has "affiliates" and I can see that TechCrunch has "battlefield companies", both of which support writes via POST requests. 

But knowing these companies have these data sets isn't a vulnerability in itself. 

I think I'd need more convincing arguments (and likely the wider API ecosystem as well) to consider making a change here. 

It would actually cause more of an attack surface if execution occurred before schema validation. 

There's almost no cost to validating that the request is of an allowed shape. But, determining whether the requestor has permission to do xx thing requires database lookups and overhead, so a bad actor hitting your site when execution came before validation could exhaust your server in a way that validation before execution will not, or would have less of a chance to.

**Comment by nickcernis** [comment]
> Like I pointed out, I can already introspect almost any WP site and see what POST arguments are allowed for arbitrary data sets.

Right, but only if fields are registered for REST (which a lot of CPT plugins do, but I don't think “REST endpoints expose data that users might have wanted to be private so it's fine if we do” is necessarily sound — we should strive to be better!).

> But knowing these companies have these data sets isn't a vulnerability in itself.

Agreed, it's more of a privacy concern than a security one.

> There's almost no cost to validating that the request is of an allowed shape. But, determining whether the requestor has permission to do xx thing requires database lookups and overhead, so a bad actor hitting your site when execution came before validation could exhaust your server in a way that validation before execution will not, or would have less of a chance to.

Putting auth checks up front doesn't make a site more vulnerable to DDOS attempts via triggering database reads for auth checks because I can already force auth checks to "exhaust your server" in the current WPGraphQL version if I want to: I just send a payload that passes input validation. (Try a mutation against a core post type like `mutation { createPost( input: { title: "test" } )  { post { id } } }`. You'll see that the `current_user_can()` check fires in `mutate_and_get_payload` in `PostObjectCreate.php`, hitting the database and running the auth check even if I'm logged out.)

I appreciate you taking a look, though, and if the risk is too small or not compelling let's just close this out. I'll file a separate issue on mutation hooks to make those even more extensible and awesome. 😄

**Comment by jasonbahl** [comment]
Ya, let's open another issue to discuss hooks/fitlers for mutations. 

If there's compelling info to open this again in the future, we certainly can.

**Comment by justlevine** [comment]
> Putting auth checks up front doesn't make a site more vulnerable to DDOS attempts via triggering database reads for auth checks because I can already force auth checks to "exhaust your server" in the current WPGraphQL version.

@nickcernis If anything I think that means the current model is the best of both worlds. Shape validation prevents random trolling (the script needs to be tailored to WPGraphQL and any custom mutation fields, before it can hit your database. While input content validation happens after to prevent them from do things they shouldnt (supported by good DX so you can do your own hardening Eg. a pre_input_validation that limits requests per second, or obfuscates error messages, or aborts because of a "required" nullable input before a db hit can happen).
