### ISSUE TITLE
Schema Linter is failing

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#2367]
The Schema linter is failing. See: https://github.com/wp-graphql/wp-graphql/runs/6327416860?check_suite_focus=true

It looks related to the latest release of the Schema linter: https://github.com/cjoudrey/graphql-schema-linter/releases/tag/v3.0.0

We need to update the Workflow to install GraphQL as well.

**Comment by justlevine** [comment]
We might also want to specify a major version to the [install command](https://github.com/wp-graphql/wp-graphql/blob/c1c2255762394b5ec56ce6b8f6e56cbb212433b7/.github/workflows/schema-linter.yml#L42), to prevent a future breaking release from doing the same.
