### ISSUE TITLE
Warning: Parameter 1 to Route::{closure}() expected to be a reference, value given

### ISSUE THREAD

**Issue by izzygld** [wp-graphql/wp-graphql#2377]
[https://github.com/wp-graphql/wp-graphql/blob/develop/src/Data/NodeResolver.php#L350](https://github.com/wp-graphql/wp-graphql/blob/develop/src/Data/NodeResolver.php#L350)

<img width="1162" alt="Screen Shot 2022-05-15 at 17 20 49" src="https://user-images.githubusercontent.com/12534341/168477691-513b3000-7d76-49b1-ba2c-11b3cb48c4b9.png">

ErrorException /share/public/content/plugins/wp-graphql/src/Data/NodeResolver.php in WPGraphQL\Data\NodeResolver::resolve_uri

**Warning: Parameter 1 to Route::{closure}() expected to be a reference, value given**

**Comment by justlevine** [comment]
Hey @izzygld can you provide some information about your setup? Ideally a reproducible test case (with all non-offending 3rd-party plugins/custom code disabled), but at the very least a list of what's activated, and the relevant version numbers.

`Route` is neither a WPGraphQL nor a WP native class, which means something else is [improperly hooking onto the `parse_request` action](https://developer.wordpress.org/reference/hooks/parse_request/)

**Comment by jasonbahl** [comment]
It looks like [core](https://core.trac.wordpress.org/browser/tags/5.9/src/wp-includes/class-wp.php#L396) passes it like so:

```php
do_action_ref_array( 'parse_request', array( &$this ) );
```

@izzygld if you change the line you highlighted in NodeResolver.php to: 

```php
do_action_ref_array( 'parse_request', [ &$this->wp ] );
```

Does it resolve the error?

**Comment by justlevine** [comment]
I stand corrected 😇, good reminder to check the source and not rely on the documentation.
(Related #2366 )

**Comment by jasonbahl** [comment]
PR coming. Thanks for confirming.

**Comment by izzygld** [comment]
I'm wondering if it's worth going through some of the code with sentry debugging to remove other warnings..

**Comment by jasonbahl** [comment]
@izzygld it most likely is very much worth it indeed!

In the mean time, I've got this PR opened for this specific issue: https://github.com/wp-graphql/wp-graphql/pull/2380
