### ISSUE TITLE
Term mutations adding extra slashes to names, descriptions, slugs

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#2378]
When using a WPGraphQL mutation to update/create a taxonomy term that contains an apostrophe, WPGraphQL is saving the slashes to the database. This is not consistent with other core behaviors for creating/inserting terms (Admin Dashboard, WP REST API)

## Steps to reproduce:

As an authenticated user, execute the following mutation:

```graphql
mutation {
  createTag( input: { name: "What's up!" } ) {
    tag {
      name
    }
  }
}
```

This will give us the tag name `What\\'s up!` in the response.

![CleanShot 2022-05-16 at 09 28 05](https://user-images.githubusercontent.com/1260765/168628688-15af4a1d-e9c9-4213-9dcc-0054a5be9afd.png)

And if we look at the database we see the raw value `What\'s up!` was stored. 

![CleanShot 2022-05-16 at 09 29 48](https://user-images.githubusercontent.com/1260765/168629065-174e10e4-6da4-4275-81f0-ce4eacbe2ca9.png)

## Expectation

> I expect the value in the database to not be stored with the slash, as seen when doing Tag mutations with the WP REST API.

If we create a term using the WP REST API

This gives us the expected name in the response:

![CleanShot 2022-05-16 at 09 30 18](https://user-images.githubusercontent.com/1260765/168629152-8b96e194-97a4-4855-bb74-e2368c8d5874.png)

And stores as expected in the database:

![CleanShot 2022-05-16 at 09 31 36](https://user-images.githubusercontent.com/1260765/168629441-30002e4a-357c-460a-989c-12eda16b5a43.png)

## Quick Solution

Until this is fixed in WPGraphQL, users should be able to use the following filter: 

```php
add_action('graphql_term_object_insert_term_args', 'clean_tag_name');

function clean_tag_name($args) {
	$args['name']        = stripslashes($args['name']);
	$args['description'] = stripslashes($args['description']);
	$args['slug']        = stripslashes($args['slug']);
	return $args;
}
```

**Comment by justlevine** [comment]
For the actual PR, we might want to use [`sanitize_title()`](https://developer.wordpress.org/reference/functions/sanitize_title/). Not sure the implications for multilingual (or how WP handles non-ASCII titles-to-slugs in general), but I'm pretty sure this is what WP itself uses under the hood.

**Comment by jasonbahl** [comment]
@justlevine the wp_insert_term and wp_update_term methods use `sanitize_title()` under the hood: 

- https://core.trac.wordpress.org/browser/tags/5.9/src/wp-includes/taxonomy.php#L3165
- https://core.trac.wordpress.org/browser/tags/5.9/src/wp-includes/taxonomy.php#L2394

I updated my test to use it on the expected value for the slug, to ensure the output matches core behavior
