### ISSUE TITLE
Use instanceof instead of is_a

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#238]
For slight performance gains and consistency, `Instanceof` should be used instead of `is_a` here:

https://github.com/wp-graphql/wp-graphql/blob/8441649abde54a7cb4c95d191e9339250df6f43f/src/Type/PostObject/PostObjectQuery.php#L109

See: https://stackoverflow.com/questions/3017684/what-is-the-difference-between-is-a-and-instanceof#answer-20870004

**Comment by luchianenco** [comment]
is it still opened?

**Comment by jasonbahl** [comment]
@luchianenco yes! Feel free to take it. Create your branch off the `develop` branch and open your PR back to `develop`

You _shouldn't_ need to add or adjust unit tests for this change either.

Thanks!

**Comment by luchianenco** [comment]
@jasonbahl as I understan WP_Post class is from Worpress Core https://core.trac.wordpress.org/browser/tags/4.8/src/wp-includes/class-wp-post.php#L0

The update line would look like this
if ( !$post_object instanceof WP_Post )

**Comment by jasonbahl** [comment]
@luchianenco `if ( ! $post_object instanceof \WP_Post )` should work. . .note the space after the `!` and the slash before the `WP_Post` (because we're namespaced)

**Comment by jasonbahl** [comment]
addressed by #250
