### ISSUE TITLE
Add helper method for retrieving the Frontend base URL

### ISSUE THREAD

**Issue by justlevine** [wp-graphql/wp-graphql#2384]
## What

We should add a filterable helper method to WPGraphQL for retrieving the site's frontend URL (and possibly the relative URI).

## Why
The `home_url()` method is used in many different contexts, both by WP core and 3rd-party plugins. That makes things like url replacements (a common need in headless environments where the actual frontend and the "wp frontend" aren't the same) a major pain, and can cause inconsistencies and edge cases that often require additional code to handle.

Creating a helper method would both make WPGraphQL DRY-er and more testable, and make it easier for devs trying to support 3rd-party plugins by providing a single consistent source of truth to alter.

Two recent examples of this issue (I'm sure there's more if I did a deep dive):
- #2324
- #2341

## How
Im thinking something along the lines of
```php

public static function get_home_url() : string {
   $home_url = home_url();
   
   return apply_filters( 'graphql_home_url', $home_url );
}
```

We could even DRY out the `str_replace()` used [throughout the plugin](https://github.com/wp-graphql/wp-graphql/search?home_url) with the following:

```php

public static function get_relative_uri( string $url ) {
  $home_url = WPGraphQL::get_home_url();
  
  return str_ireplace( $home_url, '', $url );
}
```

Extension authors (and core) could then use the above methods without needing to worry about possible side effects from `home_url()`, and users/plugin authors who want to reference a headless frontend instead of WP's can just use the filter once, instead of having to handle the various schema use cases separately. 

E.g. for FaustJS - a significant amount of [their replacements code](https://github.com/wpengine/faustjs/tree/1762188abddeef809916b31d415851da3dfcb826/plugins/faustwp/includes/replacement) (which currently doesn't  account for all possible edge cases) could be reduced to a single filter call:

```php

add_filter( 'graphql_home_url', 
  function( string $url ) {
    return  faustwp_get_setting( 'frontend_uri' );
  }
);
```

<!--
### When you open an _issue_ for a feature request, please add as much detail as possible:
- [x] A descriptive title
- [x] A description of the problem you're trying to solve, including *why* you think this is a problem
- [x] An overview of the suggested solution
- [x] If the feature changes current behavior, reasons why your solution is better
--!>

**Comment by renatonascalves** [comment]
I'd argue that `home_url` is that source of truth. It has a function and a hook: https://developer.wordpress.org/reference/hooks/home_url/

Why introduce another layer of functions/methods and hooks?

**Comment by justlevine** [comment]
@renatonascalves fundamentally I agree (see my note on [the pr](https://github.com/wp-graphql/wp-graphql/pull/2386) and my comment on [this one](https://github.com/wp-graphql/wp-graphql/pull/2341#issuecomment-1128719980) ).

But.... if the consensus on #2341 is to provide a way for customization of the base url _without_ relying on `home_url`, then this provides a path forward 🤷‍♂️

**Comment by renatonascalves** [comment]
In that case, let me read those links further...
