### ISSUE TITLE
Broken GraphiQL IDE UI after upgrading to Version 1.8.2

### ISSUE THREAD

**Issue by zewas-digital** [wp-graphql/wp-graphql#2385]
I just upgreaded to version 1.8.2 of WP GraphQL and wanted to use the GraphiQL interface, but the height of the field where the Query is show is only a fraction of the Screen height.

Yesterday i worked with version 1.8.1 and it worked fine.
Since yesterday I did not change any of my code and i did not upgrade any of my other Plugins.

![grafik](https://user-images.githubusercontent.com/91801756/168980789-1179a7c4-66e7-4586-945a-7ba3699f1296.png)

Other Plugins I use:
- WPGraphQL for Advanced Custom Fields
- WPGraphQL JWT Authentication
- WPGraphQL Upload#
- Add WPGraphQL SEO

**Comment by justlevine** [comment]
Hey @zewas-digital

A few questions:
- What browser (+ version) are you using, and have you tried opening it up in a different one?
- Are you getting any errors/warnings in the dev console?
- Have you tried clearing your browser cache?
- Are all users facing this issue or just one?
- Whats happens if you double-click on `QUERY VARIABLES`?
- How did you install WPGraphQL: the Plugin Directory, Composer (and from what source - wp-graphql/ or wpackagist-plugin/), downloading the Release .zip, downloading the `master` branch, etc)?

**Comment by zewas-digital** [comment]
I'm using
-  Firefox v101.0b8 (64bit)
- Also tested on Chrome v101.0.4951.67 (64bit), same problem
Other Questions
- I do not get any errors or warnings
- I cleared my browser cache just now but the problem remains
- I only have one user on my WordPress site so I did not test that
- When I double-click on `QUERY VARIABLES` it shows the `QUERY VARIABLES` field
- I downloaded the zip file on https://wordpress.org/plugins/wp-graphql/  and manually extracted it into the plugins folder, and today I updated it via the WordPress plugin tab
![grafik](https://user-images.githubusercontent.com/91801756/169017086-a90d89cd-9547-4f04-b1fe-b6131955730d.png)

**Comment by justlevine** [comment]
🤔

Can you inspect the CodeMirror `textarea` element and share a screenshot with the properties + css rules?

E.g. (from Chrome)
![image](https://user-images.githubusercontent.com/29322304/169029974-39004d8c-47ea-4970-afc8-956c15cf23f6.png)

**Comment by zewas-digital** [comment]
This is the screenshot of the `textarea`
![grafik](https://user-images.githubusercontent.com/91801756/169039912-020598ba-622d-4295-a15d-4710963fd44c.png)
I inspectet a little further and found out, that the parent div `CodeMirror` has a `height` property which is overwritten by some othre CSS rule. (red mark)
![grafik](https://user-images.githubusercontent.com/91801756/169040706-84293cf1-af0a-4013-866c-6a2ed51e2219.png)

**Comment by jasonbahl** [comment]
Can you share what plugin that admin.css is coming from?

**Comment by zewas-digital** [comment]
Sorry for the late response, I tested my other plugins that I had installed (I did not think that one of those would interfere with wp-graphql, that’s why I don't listed them), and at the and it was the Plugin `WP Query Console` https://wpfavs.com/plugins/wp-query-console it is an outdated plugin, that I use to test my meta queries.

**Comment by jasonbahl** [comment]
@zewas-digital oh nice! Thanks for this. I think we can get a bit more specific with our CSS to help guard against these types of conflicts 🤔
