### ISSUE TITLE
New post doesn't show unless the permalink field is touched

### ISSUE THREAD

**Issue by robertschneiderman** [wp-graphql/wp-graphql#2392]
Using version 1.6.11. When I create a new post, the permalink field autofills based on the title:

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/16520011/170131392-a57ff2d2-f0b6-43dd-8aee-c6275ffc2f6a.png">

The GraphQL API does not pick up the new post unless I click inside (touch) the permalink field and save again. This is before touching the field:
<img width="1016" alt="Screen Shot 2022-05-24 at 4 46 21 PM" src="https://user-images.githubusercontent.com/16520011/170131560-72048ab6-183e-449f-97b1-fcbdc9ac7728.png">

And this is after:
<img width="975" alt="Screen Shot 2022-05-24 at 4 46 42 PM" src="https://user-images.githubusercontent.com/16520011/170131614-cfcdcdbe-82eb-46dc-bae5-8dc1a4b788da.png">

Is there a reason this happens this way?

**Comment by justlevine** [comment]
Hey @robertschneiderman I cannot replicate this in WPGraphQL v1.8.2 (tried against both WP5.9 and WP6.0). Maybe it has to do with you supplying `temp` is to an `idType:` **`URI`** and not `SLUG`, but that also seems to be working for me...

Can you please test against a latest version, and if it's still happening provide a detailed list of activated plugins + versions + wp version + php version?

#### Create Post with autogenerated permalink:
![image](https://user-images.githubusercontent.com/29322304/170809546-43053dea-bd7e-436e-96d0-e8eea92330d8.png)
#### Querying immediately without 'touching' and resaving permalink:
![image](https://user-images.githubusercontent.com/29322304/170809764-fa89e0d5-5dd8-4434-beea-541477f608a3.png)

**Comment by robertschneiderman** [comment]
@justlevine Thanks for following up. Two clarifications:
1. This is only happening with drafts... not published posts
2. I have wp-graphql-jwt-auth installed to pull drafts

I setup a brand new Wordpress 6.0 install and installed `WP GraphQL 1.8.2` and `WPGraphQL JWT Authentication 0.4.0`

I followed the instructions on logging in a user: https://github.com/wp-graphql/wp-graphql-jwt-authentication

Here is a video of me replicating the bug: https://www.loom.com/share/319b4440073b49eea3ae1d0918e6a1a9 . Note that saving draft multiple times does not make the post appear. It only appears after I click into the autofilled permalink field.

**Comment by justlevine** [comment]
Thanks @robertschneiderman for the clarifications.

Could simply be another issue with [NodeByUri](#2366), or perhaps _draft_ posts dont set a pretty-permalink by default, and its instead only generated on publish or if a URI is set explicitly. (Could be a gutenberg bug or expected behavior.)
I'm assuming providing a `URI` of `"?p=24"` would work?

Depending on the cause we'd either need a fix or a workaround. Will do more research and report back.

**Comment by jasonbahl** [comment]
This appears to be working as intended. 

In non-headless WordPress, if you have a draft post, you cannot visit the url for that post and see the post. 

WPGraphQL is behaving the same. 

If the post is a draft, it doesn't yet have a public url, thus `nodeByUri` shouldn't resolve it. 

For example, I've created a draft post:

![CleanShot 2023-04-25 at 11 45 06](https://user-images.githubusercontent.com/1260765/234359313-1d1928c3-c70d-4b7a-af25-4bcaa7f4e275.png)

WordPress shows what the url _will_ be, but if I try and visit that url, WordPress will 404: 

![CleanShot 2023-04-25 at 11 45 12](https://user-images.githubusercontent.com/1260765/234359377-2999c665-90b9-417e-94bd-a68ef0f23d80.png)

I would expect `nodeByUri` to also return no results. 

If you click the link to the url, it _actually_ takes you to a link with the post id: 

![CleanShot 2023-04-25 at 11 46 51](https://user-images.githubusercontent.com/1260765/234359708-6ec702a7-60b7-49df-8ca1-e8af1070b054.png)

That post ID could be used to query a preview of the post, like so: 

![CleanShot 2023-04-25 at 11 50 13](https://user-images.githubusercontent.com/1260765/234360469-56a75dbe-46ba-4680-bccf-407a323e0515.png)

I'm going to close this issue, as I believe it's intended behavior.
