### ISSUE TITLE
function "graphql_activation_callback" not found

### ISSUE THREAD

**Issue by nguyenquanghuy-hdws** [wp-graphql/wp-graphql#2398]
I get this error when activating wp-graphql plugin which is installed plugins via `composer install`, but when installing via `Plugins > Add new` activate does not fail

<img src="https://user-images.githubusercontent.com/85088597/170813380-8fb4aa93-134c-4e53-b611-302b7a0299ec.png" width="800" />

At first I thought it was permission, but when I checked it was not, it belongs to the same user

<img src="https://user-images.githubusercontent.com/85088597/170813749-15d80544-c3f7-4cfa-8997-8c75bb6a5e0f.png" width="500" />

There is a strange thing that the folder `vendor/wp-graphql` is empty (I also tried `composer dump-autoload`, `composer update`)

```
# composer.json

{
	"minimum-stability": "dev",
	"prefer-stable": true,
	"repositories": [
		{
			"type": "composer",
			"url": "https://wpackagist.org"
		}
	],
	"require": {
		"composer/installers": "~1.0",
		"wp-graphql/wp-graphql": "1.8.2",
		"wp-graphql/wp-graphql-jwt-authentication": "0.4.0",
		"valu/wp-graphql-offset-pagination": "^0.2",
		"wpackagist-plugin/advanced-custom-fields": "5.12.2",
		"wpackagist-plugin/custom-post-type-ui": "1.12.1"
	},
	"extra": {
                "installer-paths": {
                        "wp-content/themes/{$name}/": ["type:wordpress-theme"],
                        "wp-content/plugins/{$name}/": ["type:wordpress-plugin"]
                }
	},
	"config": {
		"allow-plugins": {
			"composer/installers": true
		}
	}
}
```

Maybe it's symlinking to packages in `vendor` folder, but i don't know how to fix it? please help me

#### Environments
```
php: 8.0.19
composer: 2.1.12
wp-graphql: 1.8.2
```

**Comment by justlevine** [comment]
Hey @nguyenquanghuy-hdws ,

For a while now, wp-graphql hasn't stored _its own_ composer deps in the GitHub repo, which can lead to some funny behavior.

In general, we recommend Composer installs use WPackagist (`composer require wpackagist-plugin/wp-graphql` ) unless you are trying to contribute to the plugin. 

If you still wish to install directly from `wp-graphql/wp-graphql`, then after install/version update, you need to `cd` into `path/to/wp-content/plugins/wp-graphql` and then run `composer update --no-dev --optimize-autoloader`.

Please let us know if that works or if you're still running into trouble.

Related: #1831

**Comment by nguyenquanghuy-hdws** [comment]
@justlevine I tried installing `wp-graphql` by adding line `"wpackagist-plugin/wp-graphql": "1.8.2"` to `composer.json`  and no longer getting that error. Thank you very much
