### ISSUE TITLE
Taxonomy called "location" causes menuItems not to work

### ISSUE THREAD

**Issue by cristobalbahe** [wp-graphql/wp-graphql#2409]
Hello everyone,

I don't know if this is the place to publish this, but I've just come across the following problem and finally learned why.

In my installation I had a custom taxonomy with a slug of "location" which caused this query to return an empty array.
```graphql
menuItems(where:{location:PRIMARY_MENU}) {
    nodes {
      id
    }
}
```

When I changed the slug of the taxonomy, everything worked again. 

Just in case someone has the same problem :)

Cheers everyone

**Comment by jasonbahl** [comment]
@cristobalbahe thanks for reporting this! I've been able to reproduce and I have a pull request coming to fix it.

**Comment by jasonbahl** [comment]
@cristobalbahe PR opened: https://github.com/wp-graphql/wp-graphql/pull/2411
