### ISSUE TITLE
searchColumns parameter in users Query doesn't work.

### ISSUE THREAD

**Issue by developerfan1219** [wp-graphql/wp-graphql#2419]
I would like to query users by email and nickname.
query will be like this:

```
Where
   email like '%test%' OR
   nickname like '%test%'
```

**To Test**

```
query NewQuery {
  users(where: {search: "test", searchColumns: [NICENAME, EMAIL]}) {
    edges {
      node {
        firstName
        lastName
        name
        nickname
        email
      }
    }
  }
}

```
In get_query of UserConnectionResolver, `$this->query_args` before running query is below:

`{ ["count_total"]=> bool(false) ["graphql_args"]=> array(1) { ["where"]=> array(2) { ["search"]=> string(4) "test" ["searchColumns"]=> array(1) { [0]=> string(8) "nicename" } } } ["graphql_cursor_offset"]=> int(0) ["graphql_cursor_compare"]=> string(1) "<" ["graphql_after_cursor"]=> NULL ["graphql_before_cursor"]=> NULL ["number"]=> int(11) ["search"]=> string(6) "*test*" ["search_columns"]=> array(1) { [0]=> string(8) "nicename" } ["fields"]=> string(2) "ID" ["has_published_posts"]=> bool(true) ["orderby"]=> string(10) "user_login" ["order"]=> string(3) "ASC" }`

the query string after running query:

`SELECT wp_users.ID FROM wp_users WHERE 1=1 AND wp_users.ID IN ( SELECT DISTINCT wp_posts.post_author FROM wp_posts WHERE wp_posts.post_status = 'publish' AND wp_posts.post_type IN ( 'post', 'page', 'attachment' ) ) AND (user_login LIKE '%test%' OR user_url LIKE '%test%' OR user_email LIKE '%test%' OR user_nicename LIKE '%test%' OR display_name LIKE '%test%') ORDER BY user_login ASC, wp_users.ID DESC LIMIT 0, 11`

![image](https://user-images.githubusercontent.com/54286458/175447418-98b679b6-c121-4200-81e9-491113f912b3.png)

I would like to get the query string like this.

`SELECT wp_users.ID FROM wp_users WHERE 1=1 AND wp_users.ID IN ( SELECT DISTINCT wp_posts.post_author FROM wp_posts WHERE wp_posts.post_status = 'publish' AND wp_posts.post_type IN ( 'post', 'page', 'attachment' ) ) AND (user_email LIKE '%test%' OR user_nicename LIKE '%test%') ORDER BY user_login ASC, wp_users.ID DESC LIMIT 0, 11`

**Comment by justlevine** [comment]
Confirmed on a clean install (PHP 7.4, WP 6.0.1. , WPGraphQL 1.8.7 via TasteWP).
![image](https://user-images.githubusercontent.com/29322304/182336760-aac1cbc1-8daa-4c04-9347-065180cd8c91.png)

At first glance, I don't see anything in the codebase ( [wp](https://developer.wordpress.org/reference/classes/wp_user_query/get_search_sql/), [wpgraphql](https://github.com/wp-graphql/wp-graphql/blob/836729190e07dfff6d239dfa077dcd2237d7b605/src/Data/Connection/UserConnectionResolver.php#L109) )that would add those `LIKE` conditionals if theyre not explicit in `searchColumns`...

**Comment by justlevine** [comment]
Bad stalebot
