### ISSUE TITLE
Param `$info->fieldNodes->...` in `graphql_register_types` action just returns `NULL`;

### ISSUE THREAD

**Issue by RuanMoreiraOfc** [wp-graphql/wp-graphql#2429]
- Windows 10
- Wordpress 6.0
- WPGraphql 1.8.6
- No Additional Plugins

In debug mode using `XDebug` I can access the value inside, but when I try to access the variable in code it just returns `NULL`;

#### 1 - Create a PHP file in `/wp-content/plugins/`
```bash
echo "" > ./wp-content/plugins/plugin-test.php
```

#### 2 - Paste this in it
```php
<?php
/**
 * Plugin Name: WPGraphql Field `startPos`
 */

add_action('graphql_register_types', function() {
    register_graphql_field('RootQuery', 'startPos', [
        'type' => 'INT',
        'resolve' => function( $root, $args, $context, $info ) {
            return $info->fieldNodes->storage[0]->loc->start;
        }
    ]);
});
```

#### 3 - Execute this query 
```graphql
{
  startPos # desired output: 4; actual output: null
}
```

**Comment by justlevine** [comment]
Hey @RuanMoreiraOfc,

> In debug mode using XDebug I can access the value inside, but when I try to access the variable in code it just returns `NULL;`

Not sure I understand what you mean by `access the value inside`. Do you mean that `$info->fieldNodes->storage[0]->loc->start` has an int value in the _resolver callback_, but the _query itself_ comes back as `null`?

[It seems](https://github.com/wp-graphql/wp-graphql/blob/e0588e7253b4e21678d22c3d551331a012fd5574/src/Registry/TypeRegistry.php#L217) that type should be `Int` or `Integer` and not `INT`, but that should throw an error, not fail silently 🤔. If you fix the case, does the issue go away?

**Comment by RuanMoreiraOfc** [comment]
Hi @justlevine, sorry for being late, but I just realize the reply now!

I even try with `Int` type but same result!

![image](https://user-images.githubusercontent.com/36450847/178124401-2f1cfdc1-e177-47a2-a6db-ba5b5e7bb5ff.png)

![image](https://user-images.githubusercontent.com/36450847/178124299-a175409f-014c-4200-b165-e7d2c73f0faf.png)

**Comment by RuanMoreiraOfc** [comment]
If I return any actual integer, like `return 1;` with `"type" => "INT"` it works fine!

**Comment by jasonbahl** [comment]
@RuanMoreiraOfc so it looks like the `storage` is a private field on the ArrayObject (FieldNode) so it's value cannot be used outside of the class itself. 

You can see this if you update the resolver like so: 

```php
add_action('graphql_register_types', function() {
	register_graphql_field('RootQuery', 'startPos', [
		'type' => 'Int',
		'resolve' => function( $root, $args, $context, \GraphQL\Type\Definition\ResolveInfo $info ) {
			var_dump($info->fieldNodes);
		}
	]);
});
```

Then re-execute in GraphiQL and inspect the response: 

![CleanShot 2022-07-26 at 16 57 29](https://user-images.githubusercontent.com/1260765/181126238-8f6130a6-e7cf-4a84-b9c8-981aca38fc12.png)

I'm curious what you're trying to accomplish with this data from the ResolveInfo.

Can you provide more context on what you're trying to accomplish and perhaps we can come up with some ideas on how to resolve it.

There are some public methods to get data, such as `$info->getFieldSelection()` and `$info->lookAhead()` which might help, depending on what you're trying to do.

**Comment by RuanMoreiraOfc** [comment]
@jasonbahl `$info->getFieldSelection()` was exactly what I was trying to achieve with the `storage[0]->loc`, this solved the problem thanks!

Basically, I'm using `add_filter('graphql_resolve_field')` I wanted to skip some cases when there are no correspondent children inside of it.
