### ISSUE TITLE
Add custom post types with custom fields

### ISSUE THREAD

**Issue by cr101** [wp-graphql/wp-graphql#243]
Is it possible to register custom post types and add the custom fields for each CPT like in [graphql-wp](https://github.com/tim-field/graphql-wp)?

I'm using the ACF plugin and I have 8 different CPTs where each CPT has 15 custom fields on average.
I'd like to add the custom fields for each custom post type without each CPT inheriting each other's custom fields. Then I can run a query like below:
```
query {
	author(id: 4452) {
		id
		name,
		books(isbn: a4545x) {
			title,
			isbn
		}
	}
}
```

**Comment by jasonbahl** [comment]
@cr101 hey, sorry for the delayed response. 

You can find more info about Custom Post Types and Custom Fields here: 
https://github.com/wp-graphql/wp-graphql/wiki/Extending-and-Customizing
https://github.com/wp-graphql/wp-graphql/issues/173#issuecomment-315247481
https://github.com/wp-graphql/wp-graphql/issues/146
https://github.com/wp-graphql/wp-graphql/issues/11
