### ISSUE TITLE
Get page by uri doesn't find by new permalink manager uri

### ISSUE THREAD

**Issue by tobiasorosa** [wp-graphql/wp-graphql#2430]
When updating a post uri through Permalink Manager (plugin), I can't query a post by its new uri, only able to get the post with its original uri. However when I query it successfully, it actually returns the updated uri in response.

![image](https://user-images.githubusercontent.com/68042466/176082621-025fb5f9-1fe5-4ba9-b171-5e27d85d8f0a.png)

I'm using WP GRAPHQL v1.8.6 and Permalink Manager Lite v2.2.19.1

To reproduce this, create any post, change its uri through permalink manager, and then try to query by with its new uri.

The expected behaviour is being able to get the post with the updated uri.

**Comment by justlevine** [comment]
@tobiasorosa Permalink Manager works by [modifying the `request`](https://plugins.trac.wordpress.org/browser/permalink-manager/trunk/includes/core/permalink-manager-core-functions.php#L52) in a way that is essentially dependent on the PHP `$_SERVER[`REQUEST_URI`], and thus likely incompatible with WPGraphQL (where the request URI is the graphql endpoint).

It _may be possible_ that #2366 might open up a path for us to handle this in-plugin, but more likely than not any desire for compatibility is going to need to come from Permalink Manager's side of things.

**Comment by justlevine** [comment]
Confirming the issue is permalink manager's use of `pre_get_posts` and `template_redirect` to handle redirects, instead of using the WP_Rewrite api or hooking into WP_Query internals.

As such I see no path forward for supporting this plugin in core WPGraphQL.
