### ISSUE TITLE
Wpgraphql resover for WoGraphql missing

### ISSUE THREAD

**Issue by pairviewwebmaster** [wp-graphql/wp-graphql#2447]
I create a relationship using ACF between a custom post type (store) has a product. So the store has products.  But keep getting this error when trying to query the related products under the Store.

```
Abstract type Store_StoreListing_RelateProduct must resolve to an Object type at runtime for field  Store_StoreListing.relateProduct with value \"instance of WPGraphQL\\Model\\Post\", received \"Product\". Either the  Store_StoreListing_RelateProduct type should provide a \"resolveType\" function or each possible type should provide an \"isTypeOf\" function.
```

**Query is**

```
 Store{
    nodes {
      StoreListing{
        fieldGroupName
        relateProduct {
          ... on Product {
            id
            name
          }
        }
      }
    }
  }

```

**Comment by justlevine** [comment]
Per the additional information shared on [Slack](https://wp-graphql.slack.com/archives/C3NM1M291/p1658352161431699, this is a downstream issue with either WPGraphQL for Woocommerce _or_ WPGraphQL for ACF. It can probably already be handled there but #2399 will make it much easier to implement a fix.
