### ISSUE TITLE
Author information is not retrieved when pulling post comments.

### ISSUE THREAD

**Issue by mertosman** [wp-graphql/wp-graphql#2448]
Hi, 

first of all thanks for your plugin, it's a great plugin.

https://github.com/wp-graphql/wp-graphql/issues/1139 I saw the error here, the issue was closed, but it was closed without being resolved. Looking at the last comment https://github.com/wp-graphql/wp-graphql/issues/1139#issuecomment-580963408 I am having the same error here.

I have a few custom fields for my User type. But **... on User** doesn't work at all. Only .**..on CommentAuthor** data is coming, I have never been able to solve this problem.

I am sharing a sample screenshot of my application below. I made all users public from the "graphql_object_visibility" section. It just gives me the information on **... on CommentAuhor.** I commented and tested as **2 visitors** and **2 registered members**. However, the result is negative.

![Wpgraphql-comment-user-connection](https://user-images.githubusercontent.com/9094446/180183741-833e65eb-d67a-42f1-9905-ab43a3953d09.png)

Can you please help with this?

**Comment by justlevine** [comment]
Hey @mertosman 👋,

Can you please provide answers to the the following from the GitHub Issue Template, so we can attempt to replicate and figure out your issue?

Specificially: 
- [ ] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)
- [ ] What version of `WPGraphQL` you're using, and the platform(s) you're running it on
- [ ] What other plugins you're using

> `I have a few custom fields for my User type. But ... on User doesn't work at all.[...] I made all users public from the "graphql_object_visibility" section.`

Does the query work correctly if you run it as authenticated (the user icon next to the `Run` button will have a green dot on it)?
Can you also please provide the snippet you're using for `graphql_object_visibility`?

**Comment by mertosman** [comment]
Hey @justlevine, 

First of all, thank you for the quick response.



> "Does the query work correctly if you run it as authenticated (the user icon next to the Run button will have a green dot on it)?"

When I turned green in the part you said, my code worked, but this works in the Admin panel. I want to make this query publicly on the product detail page. In other words, non-members should be able to see previously written comments and member details.

![CleanShot 2022-07-21 at 14 48 24@2x](https://user-images.githubusercontent.com/9094446/180206715-d3aeb50c-25a7-47c5-8597-43eb6fdd0fd9.png)

It is working now as shown in the picture. However, I need to publicly display the information I want here. In other words, when normal users visit the site, they should be able to read the comments of a product, see the avatar of the comment owner and the private information I want.

> "Can you also please provide the snippet you're using for **graphql_object_visibility**?"

I answer your questions below.

"Does the query work correctly if you run it as authenticated (the user icon next to the Run button will have a green dot on it)?"

When I turned green in the part you said, my code worked, but this works in the Admin panel. I want to make this query publicly on the product detail page. In other words, non-members should be able to see previously written comments and member details.

It is working now as shown in the picture. However, I need to publicly display the information I want here. In other words, when normal users visit the site, they should be able to read the comments of a product, see the avatar of the comment owner and the private information I want.

I am sharing the screenshot of this item below.

```php
<?php 

/**
 * Register Types
 */
add_action('graphql_register_types', function () {
    // Custom Avatar
    register_graphql_object_type(
        'CustomAvatar',
        [
            'description' => __( 'Custom avatar for user', 'dr' ),
            'fields'      => [
                'isExist' => [
                    'type' => 'Boolean',
                    'description' => 'Avatar has found exist'
                ],
                'src' => [
                    'type'        => 'String',
                    'description' => 'Source url'
                ],
                'srcSet'  => [
                    'type'        => 'String',
                    'description' => 'Srcset for retina'
                ],
                'sizes'       => [
                    'type'        => 'String',
                    'description' => 'Image sizes'
                ]
            ],
        ]
    );



    register_graphql_field('User', 'CustomAvatar', [
        'type'        => 'CustomAvatar',
        'args' => [
            'size' => [
                'type' => 'MediaItemSizeEnum',
                'description' => __('Size of the MediaItem to return', 'wp-graphql'),
            ],
        ],
        'description' => __('The author custom avatar', 'wp-graphql'),
        'resolve' => function ($source, $args) {
            $user_id = intval($source->userId);
            if(!$user_id) return null;

            $size = isset($args['size']) && !empty($args['size']) ? $args['size'] : null;
            $image_sizes = get_image_sizes();

            $result = [
                'isExist' => false
            ];

            if ($avatar = get_field('avatar', 'user_' . $user_id)) :
                $result['isExist'] = true;
                $result['src'] = wp_get_attachment_image_url($avatar, ($size ?: 'mob-avatar'));
                $result['srcSet'] = wp_get_attachment_image_srcset($avatar, ($size ?: 'mob-avatar'));
                $result['sizes'] = wp_get_attachment_image_sizes($avatar, ($size ?: 'mob-avatar'));
            elseif (validate_gravatar($user_id)) :
                $result['isExist'] = true;
                $result['src'] = get_avatar_url($user_id, array('size' => (intval($image_sizes[$size]['width']) ?: 48)));
                $result['srcSet'] = get_avatar_url( $user_id, array( 'size' => (intval($image_sizes[$size]['width']) * 2 ?: 96) ) );
                $result['sizes'] = null;
            endif;

            return !empty($result) ? $result : null;
        }
    ]);
});

// All Users Set Public
add_filter('graphql_object_visibility', function ($visibility, $model_name) {
    if ('UserObject' === $model_name) {
        $visibility = 'public';
    }
    return $visibility;
}, 10, 5);
?>
```

**Comment by justlevine** [comment]
Thanks for the details response.

> When I turned green in the part you said, my code worked, but this works in the Admin panel.

This seems to confirm that the `graphql_object_visibility` filter isn't being respected for the _custom field_ you created ( from the first screenshot, it looks like the default `User` fields _are_ visible when unauthenticated).

If you enable GraphQL debugging, are you getting any error messages? Same question for WordPress' `debug.log`.

Nothing from the code snippet seems fishy at first glance. 🤔

**Comment by mertosman** [comment]
@justlevine Thanks for your answer. 

I enabled Debug mode in WPGraphql, but unfortunately I couldn't find where to see the errors. I looked at the console and there is no error.

<img width="799" alt="CleanShot 2022-07-22 at 11 20 39@2x" src="https://user-images.githubusercontent.com/9094446/180396616-45171ba2-376a-4407-aca3-cc876b7fe510.png">

**Comment by jasonbahl** [comment]
When querying a comment author, the node can either be a `User` or a `CommentAuthor`

If the email address associated with the author of a comment is associated with a user that's a public entity (has published posts of public post types), then a `User` will be returned, otherwise a `CommentAuthor` will be returned. 

To identify which type is being returned, you can query the `__typename` field. 

Like so: 

```graphql
...
author { 
  node {
    __typename
    ...
  }
}
...
```

It appears to me that the `CommentAuthor` type is being returned and the `avatar` field is not being asked for on the `CommentAuthor` type. 

You should be able to also ask for `avatar` on the `CommentAuthor` type like you are on the `User` type.

**Comment by jasonbahl** [comment]
The resolver for the `CommentToCommentAuthor` connection is here: https://github.com/wp-graphql/wp-graphql/blob/cff4758f62213299085343509fb566407998d57a/src/Type/ObjectType/Comment.php#L32-L48

Maybe do some debugging there to see whether a `User` or a `CommentAuthor` is being returned. 

If the comment in the database doesn't have a `user_id` in the database, then the `User` won't be loaded and a `CommentAuthor` object will instead be loaded.

**Comment by jasonbahl** [comment]
@mertosman can you confirm that your comments have `user_id` associated with them or not? If so, they're users, and you can enter the "Graph" and ask for more information about the user, but if they're not users, or not public users, then they're treated as a `CommentAuthor` and you're a bit more limited on what you can ask for, but both do support the avatar field, I believe.

**Comment by jasonbahl** [comment]
Ok, I believe I've reproduced this issue. It does appear that the `User` type is only being resolved when authenticated 🤔 

Looking into this further 👀

**Comment by jasonbahl** [comment]
ok! I think I found the issue within the resolver I linked to above. 

Working on a PR.

**Comment by jasonbahl** [comment]
@mertosman @justlevine I've opened this PR: https://github.com/wp-graphql/wp-graphql/pull/2452

Can ya'll confirm if this fixes the reported issue for ya'll? 🙏🏻

**Comment by mertosman** [comment]
@jasonbahl Thank you for your attention, sorry to be back late, I will test it as soon as possible.
