### ISSUE TITLE
Consider adding capability checks to queries

### ISSUE THREAD

**Issue by CodeProKid** [wp-graphql/wp-graphql#245]
Currently, we are only doing user capability checks in mutations, but there are probably some spots in queries where we should be doing `current_user_can()` checks.

For example, unpublished drafts should only be viewable by users who can `edit_others_posts`. We should probably account for these sorts of things within the plugin, so we don't expose data to people who shouldn't have access to it.

I know we have also talked about wrapping all of GQL in auth to circumvent this, but I still think there needs to be levels of access we can control. Like when creating an application for slack, you have to define what the application has access to. It only seems natural to rely on user capabilities to manage this sort of access control, and then depending on the capabilities associated with the user with the application tied to it's account, that will define what it has access to.

Once we flesh this out we should probably create separate issues for each query that we think needs capability checks added to it for simpler tracking, and smaller PR's.

**Comment by jasonbahl** [comment]
Yes, this needs addressed sooner than later for sure!

**Comment by CodeProKid** [comment]
Cool, yeah I'd be happy to wrangle this one, I've got a pretty good handle on the roled & caps. 

One thing to think about is when doing a query for objects with "any" status, and then filtering out the ones the user doesn't have access to, that may mess up paging which might get extra weird with our custom setup...

**Comment by jasonbahl** [comment]
So the framework is in place to add Field-level resolver auth checks, so now
We just gotta figure out the logic for all the fields.  

I think we can look at the schema statically and make some easy decisions but some other things could get tricky, like handling posts of “any” status, etc. 

Let’s see if we can come up with a solid list and figure some things out.

**Comment by CodeProKid** [comment]
This should be handled with the model layer initiative. #280

**Comment by jasonbahl** [comment]
Closed by #280 and it's associated stories
