### ISSUE TITLE
How to Preview a Scheduled post?

### ISSUE THREAD

**Issue by izzygld** [wp-graphql/wp-graphql#2458]
When setting a post to be scheduled - `nodeByUri`, `contentNode(asPreview: true)`, `post(asPreview: true)` all return null.

How do we retrieve data from a scheduled post?

(Yes - even authenticated)

![Screen Shot 2022-07-26 at 9 52 30](https://user-images.githubusercontent.com/12534341/180943641-316b77c3-2018-4dd3-ba78-3cf4f43c7b5e.png)

**Comment by justlevine** [comment]
Hey @izzygld 👋

I just ran this and it worked fine using v1.8.7 of WPGraphQL. Its null when unauthenticated and returns data when authenticated:

### Unauthenticated
![image](https://user-images.githubusercontent.com/29322304/182252600-68aa0292-5327-42cb-953a-335e271ada28.png)


### Authenticated
![image](https://user-images.githubusercontent.com/29322304/182252354-716ec92d-3982-4488-a81a-76915c994934.png)

Small note - a scheduled post isnt a 'preview', its a regular post with a publish date in the future. Of course a scheduled post, like a published one can have an unpublished preview. But that wouldnt cause your queries to return null: 

![image](https://user-images.githubusercontent.com/29322304/182253151-3a3c9764-e46c-4dce-8a3d-2585a46e4be0.png)


You cut off the top part of the IDE, so if you're indeed authenticated (green dot on the user avatar), then you should start by disabling any plugins or custom code until you find the culprit, and then share a reproducible test case here so it can be investigated and patched.

**Comment by izzygld** [comment]
yes thanks i can confirm updating wp graghql worked.

thanks
