### ISSUE TITLE
GraphiQL IDE fails to load if invalid JSON is stored in local storage for "variables"

### ISSUE THREAD

**Issue by NicolasdRa** [wp-graphql/wp-graphql#2467]
### Description

After updating to v 1.8.7 the GraphiQL IDE would not start.

### Steps to reproduce

1. Update Wordpress to v. 6.0 / 6.0.1
2. Update WP Graphql to v. 1.8.7
3. Go to GraphQL tab
4. Click on Graphql IDE Tab
5. Graphql IDE would not start. It freezes on a white screen.

### WPGraphQL Version

1.8.7

### WordPress Version

6.0

### PHP Version

7.4.30

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Hey @NicolasdRa 👋

What version of WPGraphQL were you upgrading from, and how did you upgrade (composer, the WP Dashboard 'Updates Page', WPackagist, downloading the _release_ from github, downloading a _branch_ from GitHub, etc).

Also, are you getting any notices in WP's `debug.log` or in your browser's console?

**Comment by NicolasdRa** [comment]
HI @justlevine 

I was upgrading from v. 1.8.6 to which I rolled back for the IDE to begin working again. The update was done from the WP Dashboard. This is the current plugin setup

![imagen](https://user-images.githubusercontent.com/54933005/183294011-76e007f3-08d0-4fb8-a256-06b73350c981.png)

**Comment by justlevine** [comment]
> Also, are you getting any notices in WP's debug.log or in your browser's console?

You forgot to share this.

The GraphiQL interface will fail to load in one of the following circumstances:
- If the composer/npm dependencies fail to build.
- A PHP Fatal Error. 
- A Javascript conflict.

We ruled out the first one (The WP Plugin Directory version includes the built dependencies). 

The most common cause for the other two is a conflict with a different WP plugin or custom code, but your issue report says you disabled all that and the problem persisted. I also just tried replicating it myself on a clean install (downloading v1.8.6 from WPackagist and then upgrading from the WP dashboard to v1.8.7), but couldn't. 🤔

Either way, your `debug.log` / browser console log will point us to the culprit.

**Comment by NicolasdRa** [comment]
Hi @justlevine, no error is logged in the debug file but I get this error in the browser console:

![imagen](https://user-images.githubusercontent.com/54933005/183379953-8f0894d3-7d16-4661-897c-4088ee627057.png)

**Comment by jasonbahl** [comment]
@NicolasdRa can you try clearing your local storage for this site and then refresh the page with GraphiQL. 

If that works (or doesn't) let us know 🙏🏻 

I think there might be a bug with invalid JSON in the "variables" stored in localStorage causing GraphiQL not to load.

**Comment by NicolasdRa** [comment]
@jasonbahl  I've cleared the local storage as you suggested and voilà, the IDE finally loaded in v. 1.8.7! 

Thanks!!!!

**Comment by jasonbahl** [comment]
@NicolasdRa I think we should leave this open as we've confirmed a bug. GraphiQL _should_ still load even if there was invalid JSON in local storage.
