### ISSUE TITLE
GatsbyJS only showing typename and ID for relationship field in gatsby-node build process. 

### ISSUE THREAD

**Issue by cordial** [wp-graphql/wp-graphql#2468]
### Description

Relationship field only returns typename and ID (even if you select post object)

### Steps to reproduce

1. Create relationship field in ACF. Select 'post object' rather than 'post id' for the return format. 
2. Query in the WP GraphQL - it shows post Object data as expected (using ...PostType { ... } format)
3. console.log the retruned data inside onCreateNode in gatsbyJS for the 'Wp<PostType>' nodes - all that is ever shown is 'typename' and 'id'. I would expect the whole custom post object, as I have selected that in the return format?

### Additional context

I'm trying to display Related posts for a CPT custom post type. ie. display related posts of the same type as the post article page itself. 

### WPGraphQL Version

1.8.7

### WordPress Version

6.0.1

### PHP Version

8.0.0

### Additional enviornment details

GatsbyJS
Advanced Custom Fields 5.12.2

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [x] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
@cordial Thanks for opening this issue. 

Can you provide a bit more information about what data you're creating a relationship to?

This sounds like it _might_ be related to a permissions issue. Not all content in WordPress is fully public. For example, a "private" post would expose certain fields like the `id` and `title`, but would not expose the content to public users (and Gatsby is a public client of WPGraphQL)

The more information we have about what data you have, what relationship(s) you're trying to create, etc, the better. 

Right now there's not enough information provided to really start narrowing down the issue.

**Comment by cordial** [comment]
hey, thanks for the prompt reply. 

So I'm creating Expert article pages inside of onCreateNode in GatsbyJS, which are a custom Post type using the Custom Post Type UI plugin. Each of the expert pages has 4 related experts (also of type Expert), which you can click on to display another Expert. 
<img width="820" alt="Screenshot 2022-08-09 at 17 54 54" src="https://user-images.githubusercontent.com/419893/183711511-724b9346-68a4-484e-9ba8-80234d4118c8.png">

Ive attached a picture of the design to show it visually. 

So to do this, each of those related Experts are an acf field of type relationship (to their own type of Expert). They have 3 fields that i want to get out, title, image and slug, as u can see from the design. However, when i console.log the node when i come to create the page, i only get '[
  { __typename: 'Expert', id: 'cG9zdDo4Mzg=' },
  { __typename: 'Expert', id: 'cG9zdDoxNTk=' },
  { __typename: 'Expert', id: 'cG9zdDoxNTU=' },
  { __typename: 'Expert', id: 'cG9zdDo4MzQ=' }
].

**Comment by cordial** [comment]
Also, if I then try and use getNode with the expertID, it isn't found as i'm creating pages for expert nodes and related expert nodes won't have been created yet.

**Comment by jasonbahl** [comment]
Have you tried running `gatsby clean && gatsby develop` after making data changes in WordPress?

There's a chance that some of the data doesn't exist in Gatsby yet and you might need to have Gatsby refetch things from WordPress.

**Comment by cordial** [comment]
yea, various times.

**Comment by cordial** [comment]
regarding the public / private potential issue, is there a way to change what is available or made public? Or at least see what is.

**Comment by jasonbahl** [comment]
> However, when i console.log the node when i come to create the page, i only get '[
{ __typename: 'Expert', id: 'cG9zdDo4Mzg=' },
{ __typename: 'Expert', id: 'cG9zdDoxNTk=' },
{ __typename: 'Expert', id: 'cG9zdDoxNTU=' },
{ __typename: 'Expert', id: 'cG9zdDo4MzQ=' }
] 

@cordial where in your code are you console logging this? Did you make a GraphQL query for only that data? Or did you ask for more data? 

Is your Gatsby codebase in a repo we can look at? Or are you able to create a reproduction in another public repo?

**Comment by jasonbahl** [comment]
> regarding the public / private potential issue, is there a way to change what is available or made public? Or at least see what is.

If you're using the latest version of WPGraphQL (or pretty recent) you should be able to make public or authenticated requests using GraphiQL. There's an avatar icon in the GraphiQL toolbar that lets you toggle public/authenticated. 

If you're able to get the data in GraphiQL as a public user, then it's not a privacy issue. Gatsby would also get that data. Which likely means it's a Gatsby data issue. 

If you're unable to get all data in GraphiQL in the WordPress admin, then it might indeed be a privacy issue and you could make sure that the post type(s) registered are registered as public, and make sure the individual post entries for the "experts" post type are published and not in another state like draft or private.

**Comment by cordial** [comment]
Experts are a custom post type.

**Comment by jasonbahl** [comment]
@cordial are you able to query data just fine in the GraphiQL UI in WP Dashboard as a public user?

**Comment by cordial** [comment]
https://github.com/gatsbyjs/gatsby-starter-wordpress-homepage-ts/blob/main/gatsby-node.js

I'm using this starter from gatsbyJS. Then I have added the below for Expert type nodes...


if (node.internal.type === "WpExpert") {
    const { expertDetails, related } = node.expert

    console.log(node.expert.related)
    if (expertDetails.courses) {
      // const mappedRelated = related.map(async (item) => {
      //   if (node.experience) return node.experience
      //   else if (node.expert) return node.expert
      //   else return null
      // })

      const expertDetailsContent = {
        details: expertDetails.courses
          .filter(Boolean)
          .map(createItemNode(node, "ExpertCourse")),
        related: related.filter(Boolean).map(createItemNode(node, "Related")),
      }

      const detailsBlocks = {
        expertDetails: {
          id: createNodeId(`${node.id} >>> ExpertDetails`),
          ...expertDetails,
          content: expertDetailsContent.details,
          title: node.title,
        },
        expertRelated: {
          id: createNodeId(`${node.id} >>> ExpertRelated`),
          ...related,
          content: expertDetailsContent.related,
        },
      }

      actions.createNode({
        ...detailsBlocks.expertDetails,
        blocktype: "ExpertDetails",
        internal: {
          type: "ExpertDetails",
          contentDigest: node.internal.contentDigest,
        },
      })

      actions.createNode({
        ...detailsBlocks.expertRelated,
        blocktype: "ExpertRelated",
        internal: {
          type: "ExpertRelated",
          contentDigest: node.internal.contentDigest,
        },
      })

      actions.createNode({
        ...node.expert,
        id: createNodeId(`${node.id} >>> ExpertsPage ${node.slug}`),
        internal: {
          type: "ExpertsPage",
          contentDigest: node.internal.contentDigest,
        },
        parent: node.id,
        slug: node.slug,
        title: node.title,
        description: node.page?.description,
        image: node.expert.image?.id,
        related: related,
        content: [
          detailsBlocks.expertDetails.id,
          detailsBlocks.expertRelated.id,
        ],
      })
    } else {
      actions.createNode({
        ...node.expert,
        id: createNodeId(`${node.id} >>> ExpertsPage ${node.slug}`),
        internal: {
          type: "ExpertsPage",
          contentDigest: node.internal.contentDigest,
        },
        parent: node.id,
        slug: node.slug,
        title: node.title,
        description: node.page?.description,
        image: node.expert.image?.id,
      })
    }
  }

**Comment by cordial** [comment]
> @cordial are you able to query data just fine in the GraphiQL UI in WP Dashboard as a public user?

yea I can see the data in the GraphQL UI as you can see from the image, it shows the right fields and their data (i.e. not just title and id)..


<img width="1037" alt="Screenshot 2022-08-09 at 18 12 39" src="https://user-images.githubusercontent.com/419893/183714754-0aff332d-d2dd-4589-b25d-56fcb35f25e3.png">

**Comment by jasonbahl** [comment]
Ah, ya, this sounds pretty specific to Gatsby and not WPGraphQL then. 

@TylerBarnes might be able to help here. 

This issue should probably be transferred to a Gatsby repo as I'm not sure this is relevant directly to WPGraphQL.

**Comment by jasonbahl** [comment]
If I'm not mistaken (I likely am 😆) when Gatsby creates nodes from WordPress it creates the nodes with the id and typename, then comes back and adds the data to the nodes. 

So if you're hooking into `actions.createNode` the id and typename might be all that's available at that time. 

So this might be expected behavior in Gatsby, but I'll let @TylerBarnes confirm or deny and expand. 

Maybe some more info on what you're trying to accomplish by hooking into the `actions.createNode` hooks could help as well?

If working properly, Gatsby Source WordPress should be fetching the nodes from WPGraphQL, and ideally you'd just be querying said data in your templates and outputting it.  🤷🏻‍♂️

**Comment by cordial** [comment]
"Maybe some more info on what you're trying to accomplish by hooking into the actions.createNode hooks could help as well?

If working properly, Gatsby Source WordPress should be fetching the nodes from WPGraphQL, and ideally you'd just be querying said data in your templates and outputting it. 🤷🏻‍♂️"

I was mainly following the patterns used in the gatsby WP starter homepage, it might be what they're (and now I am) doing is overkill/unnecessary. But that is where and how they were creating pages, inside onCreateNode (rather than inside createPages, which is how i used to do it/what most of their docs seem to use).

**Comment by jasonbahl** [comment]
ah ya, I think I'm going to defer to @TylerBarnes or someone on the Gatsby team here. He's actually on vacation this week if I'm not mistaken, though. I'll see if I can get anyone else from Gatsby to chime in here.

**Comment by cordial** [comment]
ok, cheers. thanks for all your replies.

**Comment by smthomas** [comment]
@cordial The homepage starters are a little more complicated than is often necessary for a standard Gatsby site. We did this to allow us to share components across all of our homepage starters easily.

In most cases, using createPages (or even the FileSystemRoute API) is the simpler way to create pages on your Gatsby site. The onCreateNode function runs before createPages, so I think the data you need might be available if you use that when creating your "Expert article pages".

**Comment by jasonbahl** [comment]
Closing this as I don't believe there's an actual issue here with WPGraphQL
