### ISSUE TITLE
MenuItem doesn't apply graphql_resolve_menu_item filter in connectedNode like it does for connectedObject

### ISSUE THREAD

**Issue by stephenchai** [wp-graphql/wp-graphql#2484]
### Description

The filter doesn't fire as expected.

### Steps to reproduce

1. Add a `graphql_resolve_menu_item` with some debug code to see if it's being called.
2. Query a menu.
3. Note the debug code is not called.

### Additional context

See [Slack thread](https://wp-graphql.slack.com/archives/C3NM1M291/p1660918809618809).

When looking at the `MenuItem.php` source, you can see the `apply_filters` is only called in the (deprecated) `connectedObject`

### WPGraphQL Version

1.9.1

### WordPress Version

6.0.1

### PHP Version

7.4.30

### Additional enviornment details

- Gatsby / WP Gatsby
- ACF Pro / ACF GraphQL latest
- Yoast / Yoast GraphQL latest

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [ ] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
The logic will need to be a little different, since `connectedNode` returns a connection, but the use case is the same.

https://github.com/wp-graphql/wp-graphql/blob/17d39bfddbfc38da644b790ea213a716b192d00f/src/Type/ObjectType/MenuItem.php#L186
