### ISSUE TITLE
mutation create<PostObject> returns "Sorry, you are not allowed to create <PostObject>"

### ISSUE THREAD

**Issue by MvS-IT** [wp-graphql/wp-graphql#2500]
### Description

create mutation of PostObject in production returns databaseid irregularly

### Steps to reproduce

I've setup an Atlas Content Model called Bestelling (which is the Dutch equivalent of an order), a.k.a. the PostObject.
The mutation query is as follows and is written in PHP:
 ```php
$graphql = graphql(['query' => 'mutation createBestelling
{
     createBestelling(
        input: {
              besteldatum: "'.$besteldatum.'", 
              lidmaatschapid: "'.$lidmaatschapid.'", 
              naam: "'.$naam.'", 
              emailadres: "'.$emailadres.'", 
              bestelstatus: "'.$bestelstatus.'",
              totaalbedrag: "'.$totaalbedrag.'",
              termijnbedrag: "'.$termijnbedrag.'",
              molliepaymentid: "tr_",
              betaalmodus: "'.$betaalmodus.'"
         }
     ) 
     {
        bestelling {
           databaseId
        }
    }
  }'
])
```

In order to be able to execute this mutation, I've setup a user which has the required capabilities for execution. This user is logged in programmatically in PHP with this login mutation (see WPGraphQL JWT Authentication):

```php
graphql([
    'query' => 'mutation {
      login(
        input: {password: "xxxxxxx", username: "xxxxxxx", clientMutationId: "xxxxxxx"}
      ) {
        clientMutationId
      }
    }'
])
```

I've tested this rather thoroughly on a subdomain and for 120 Bestellingen a databaseId was always received in this environment. I've made a custom Wordpress/PHP plugin for it.
Then it was time to install this plugin on the main domain. The same user with the required capabilities for the mutation execution was setup, **I imported the Atlas Content models from the subdomain into the main domain**.

Most of the time in the main domain env. the mutation createBestelling is not executed, because the error message in the log file says:
```php
[message] => Sorry, you are not allowed to create bestellingen
                    [extensions] => Array
                        (
                            [category] => user
                        )
```
The problem is: it is not consistent, sometimes a databaseid is returned but most of the times it is not. I just can't see why, especially because in the subdomain this phenomenon does not occur at all.

My only guess is that by importing models from the subdomain into the main domain, the postobject type does not get the required capabilities?????

### WPGraphQL Version

1.9.1

### WordPress Version

WordPress 6.0.2

### PHP Version

7.4.30

### Additional enviornment details

**(Frontend) framework:** 
Genesis (genesis) 3.3.5
**Plugins:** 
Atlas Content Modeler: 0.20.0
WPGraphQL JWT Authentication: 0,4.1

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [ ] Yes
- [X] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by MvS-IT** [comment]
Ok, I created a Model called Order in Atlas Content Modeler with the same properties as the Bestelling PostObject. Then I called the mutation createOrder. The same issue as above happened: no databaseid is returned and the error_log keeps mentioning:
[message] => Sorry, you are not allowed to create orders

Then I decided to setup a new plugin in which only 2 functions call are implemented:

First a connection between user and order is registered:
add_action( 'graphql_register_types', 'register_bestelling_klant_connection', 99 );

function register_bestelling_klant_connection() { 
    $config = [
                'fromType' => 'Order',
                'toType' => 'User',
                'fromFieldName' => 'klant',
                'oneToOne'      => true,
                'connectionTypeName' => 'klant',
                'connectionArgs' => ['emailadres' => [
                    'type' => 'String',
                    'description' => __( 'input data voor een klant via emailadres', '<>' ),
                ]],
                'resolve' => function( $bestelling, $args, $context, $info ) {
                    
                    $email_to_check = get_post_meta( $bestelling->ID, 'emailadres', true );

                    $resolver   = new \WPGraphQL\Data\Connection\UserConnectionResolver( $bestelling, $args, $context, $info);
                    error_log( 'emailadres: ' . $args['where']['emailadres'] . ', email opgegeven: ' . $email_to_check);
                    if( $args['where']['emailadres'] == $email_to_check ){
                        $resolver->set_query_arg( 'search', $email_to_check );
                        $resolver->set_query_arg( 'search_columns', ['user_email'] );
                        
                        $connection = $resolver->one_to_one()->get_connection();

                        return $connection;
                    }
                    return 'onjuist connectie id';
                },
            ];
    register_graphql_connection( $config );
}

Second is the wrapper for createOrder:

private function maakBestellingAan() {
            
        $besteldatum = date('Y-m-d');
        $lidmaatschapid = "3051";
        $naam = "test bestelling " . $lidmaatschapid;
        $emailadres = "info@huppeldepup.nl";
        $bestelstatus = "open";
        $totaalbedrag = "€ 300,00";
        $termijnbedrag = "€ 100,00";
        $betaalmodus = "termijn";

        $loginStatus = graphql([
            'query' => 'mutation login{
              login(
                input: {password: "xxxxxx", username: "xxxxxxxx", clientMutationId: "ingelogd"}
              ) {
                clientMutationId
                user {
                    email
                }
              }
            }'
        ]);
        error_log( 'maakBestellingAan, login: ' . $loginStatus['data']['login']['clientMutationId'] );
        error_log( 'maakBestellingAan, login: ' . $loginStatus['data']['login']['user']['email'] );
        error_log( print_r($loginStatus, true));
        if(  $loginStatus['data']['login']['clientMutationId'] == 'ingelogd' ){
            
   
            $order = graphql(['query' => 'mutation createOrder 
              {
                createOrder(
                  input: {
                    besteldatum: "'.$besteldatum.'", 
                    bestelstatus: "'.$bestelstatus.'",
                    betaalmodus: "'.$betaalmodus.'",
                    emailadres: "'.$emailadres.'", 
                    lidmaatschapid: "'.$lidmaatschapid.'", 
                    molliepaymentid: "tr_",
                    naam: "'.$naam.'", 
                    termijnbedrag: "'.$termijnbedrag.'",
                    totaalbedrag: "'.$totaalbedrag.'", 
                }
                ) {
                  order {
                    databaseId
                  }
                }
              }'
            ]);
           
            if(  empty( $order['data']['createOrder']['order']['databaseId'] ) ){
                error_log('maakBestellingAan: bestel id is leeg' );
                error_log( print_r($order, true));
            }else{
                error_log('maakBestellingAan: '. $order['data']['createOrder']['order']['databaseId'] );
            }
        }
        
    }


The remarkable thing now is the following:

the database id is returned, however a FATAL ERROR is reported:
 Fatal error:  Uncaught Error: Call to undefined function wp_get_current_user() in /home/customer/www/yogamontfoort.nl/public_html/wp-content/plugins/wp-graphql/src/WPGraphQL.php:790

[05-Sep-2022 07:50:36 UTC] {
"query":"mutation login{\n              login(\n                
input: {password: \" <xxx>\", username: \"<xxxx>\", clientMutationId: \"ingelogd\"}\n              ) 
{\n                clientMutationId\n                user {\n                    email\n                }\n              }\n            }","operation":null,"variables":null,"params":{
"queryId":null,"query":"mutation login{\n              login(\n                input: {password: \"<xxxx>\", username: \"<xxx>\", clientMutationId: \"ingelogd\"}\n              )
 {\n                clientMutationId\n                user {\n                    email\n                }\n              }\n            }","operation":null,"variables":null,"extensions":null
}}
[05-Sep-2022 07:50:36 UTC] maakBestellingAan, login: ingelogd
[05-Sep-2022 07:50:36 UTC] maakBestellingAan, login: <yyyyyyyy@yyyyy.nl>
[05-Sep-2022 07:50:36 UTC] Array
(
    [data] => Array
        (
            [login] => Array
                (
                    [clientMutationId] => ingelogd
                    [user] => Array
                        (
                            [email] => yyyyyyyy@yyyyy.nl
                        )

                )

        )

    [extensions] => Array
        (
            [debug] => Array
                (
                )

        )

)

[05-Sep-2022 07:50:36 UTC] 
{"query":"mutation createOrder 
\n              {
\n                createOrder(
\n               input: {
\n                    besteldatum: \"2022-09-05\", 
\n                    bestelstatus: \"open\",
\n                    betaalmodus: \"termijn\",
\n                    emailadres: \"info@huppeldepup.nl\", 
\n                    lidmaatschapid: \"3051\", 
\n                    molliepaymentid: \"tr_\",
\n                    naam: \"test bestelling 3051\", 
\n                    termijnbedrag: \"\u20ac 100,00\",
\n                    totaalbedrag: \"\u20ac 300,00\", 
\n                }\n                ) 
{\n                  order {\n                    databaseId\n                  }\n                }\n              }",
"operation":null,"variables":null,"params":
{"queryId":null,"query":
"mutation createOrder \n              {
\n                createOrder(
\n                  input: {
\n                    besteldatum: \"2022-09-05\", 
\n                    bestelstatus: \"open\",
\n                    betaalmodus: \"termijn\",
\n                    emailadres: \"info@huppeldepup.nl\", 
\n                    lidmaatschapid: \"3051\", 
\n                    molliepaymentid: \"tr_\",
\n                    naam: \"test bestelling 3051\", 
\n                    termijnbedrag: \"\u20ac 100,00\",
\n                    totaalbedrag: \"\u20ac 300,00\", 
\n                }
\n                ) {
\n                  order {
\n                    databaseId\n                  }\n                }\n              }",
"operation":null,"variables":null,"extensions":null}}

**[05-Sep-2022 07:50:36 UTC] maakBestellingAan: 3146**

[05-Sep-2022 07:50:37 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function wp_get_current_user() in /home/customer/www/yogamontfoort.nl/public_html/wp-content/plugins/wp-graphql/src/WPGraphQL.php:790
Stack trace:
#0 /home/customer/www/yogamontfoort.nl/public_html/wp-content/plugins/wp-graphql/src/WPGraphQL.php(748): WPGraphQL::get_app_context()
#1 /home/customer/www/yogamontfoort.nl/public_html/wp-content/plugins/wp-graphql/src/Request.php(148): WPGraphQL::get_type_registry()
#2 /home/customer/www/yogamontfoort.nl/public_html/wp-content/plugins/wp-graphql/access-functions.php(67): WPGraphQL\Request->__construct(Array)
#3 /home/customer/www/yogamontfoort.nl/public_html/wp-content/plugins/ym-graphql-tests/ym-graphql-tests.php(718): graphql(Array)
#4 /home/customer/www/yogamontfoort.nl/public_html/wp-content/plugins/ym-graphql-tests/ym-graphql-tests.php(65): Ym_Graphql_Tests_Plugin->maakBestellingAan('2022-09-05', '3051', 'test bestelling...', 'info@huppeldepup...', 'open', '\xE2\x82\xAC 300,00', '\xE2\x82\xAC 100,00', 'termijn')
#5 /home/custo in /home/customer/www/yogamontfoort.nl/public_html/wp-content/plugins/wp-graphql/src/WPGraphQL.php on line 790


Any suggestions?

**Comment by justlevine** [comment]
Hey @MvS-IT - would you mind editing your above messages using Markdown? It's kinda hard to understand what's going on like that.

On the line before a codeblock, write ` ```php` and on a new line after the code, write ` ``` `.

**Comment by MvS-IT** [comment]
> Hey @MvS-IT - would you mind editing your above messages using Markdown? It's kinda hard to understand what's going on like that.
> 
> On the line before a codeblock, write `` ```php `` and on a new line after the code, write `` ``` ``.

I'm sorry, just adjusted the messages. newbie....

**Comment by justlevine** [comment]
thanks @MvS-IT  - thats much clearer 😎.

There's still a lot of stuff going on, and the use of multiple plugins. Let's see if we can rule some things out:

1. When is `maakBestellingAan()` called? Usually a ` Call to undefined function wp_get_current_user()...` error is because the method was called _before_ the plugins finished loaded (i.e. before the `plugins_loaded` hook was called).

2. Assuming this code is being called on your WP server, why are you using jwt to log in the user, instead of WP's native functions? For testing purposes at least, would you be able to disable the WPGraphQL JWT, and replace that part of `maakBestellingAan()` with the following:

```php
...
$betaalmodus = "termijn";

// Manually include pluggable.php . IRL the method should be hooked on/after `plugins_loaded`.
if ( ! function_exists( 'wp_get_current_user' ) ) {
    include( ABSPATH . 'wp-includes/pluggable.php' ); 
}

wp_set_current_user( $user_id );

error_log( print_r( wp_get_current_user(), true ); // This will print the WP_User Object to debug.php. Please share the output here.

$order = graphql(['query' => 'mutation createOrder .... // IE the rest of your code.
 ```
 
 Then share the WP_User that gets saved to `debug.log`, so we can inspect the permissions.

**Comment by MvS-IT** [comment]
H Just thanks for your suggestion, here is the output you were asking for:
```php
[06-Sep-2022 15:36:15 UTC] WP_User Object
(
    [data] => stdClass Object
        (
            [ID] => 328
            [user_login] => xxxxxxxxx
            [user_pass] => yyyyyyyyyyyyy
            [user_nicename] => xxxxxxxxx
            [user_email] => someone@mydomain.com
            [user_url] => 
            [user_registered] => 2022-08-31 07:33:34
            [user_activation_key] => 
            [user_status] => 0
            [display_name] => xxxxxxxxx
        )

    [ID] => 328
    [caps] => Array
        (
            [graphql_user] => 1
            [administrator] => 1
        )

    [cap_key] => xyz_capabilities
    [roles] => Array
        (
            [0] => graphql_user
            [1] => administrator
        )

    [allcaps] => Array
        (
            [delete_others_pages] => 1
            [delete_others_posts] => 1
            [delete_pages] => 1
            [delete_posts] => 1
            [delete_private_pages] => 1
            [delete_private_posts] => 1
            [delete_published_pages] => 1
            [delete_published_posts] => 1
            [edit_others_pages] => 1
            [edit_others_posts] => 1
            [edit_pages] => 1
            [edit_posts] => 1
            [edit_private_pages] => 1
            [edit_private_posts] => 1
            [edit_published_pages] => 1
            [edit_published_posts] => 1
            [publish_pages] => 1
            [publish_posts] => 1
            [read] => 1
            [read_private_pages] => 1
            [read_private_posts] => 1
            [switch_themes] => 1
            [edit_themes] => 1
            [activate_plugins] => 1
            [edit_plugins] => 1
            [edit_users] => 1
            [edit_files] => 1
            [manage_options] => 1
            [moderate_comments] => 1
            [manage_categories] => 1
            [manage_links] => 1
            [upload_files] => 1
            [import] => 1
            [unfiltered_html] => 1
            [level_10] => 1
            [level_9] => 1
            [level_8] => 1
            [level_7] => 1
            [level_6] => 1
            [level_5] => 1
            [level_4] => 1
            [level_3] => 1
            [level_2] => 1
            [level_1] => 1
            [level_0] => 1
            [delete_users] => 1
            [create_users] => 1
            [unfiltered_upload] => 1
            [edit_dashboard] => 1
            [update_plugins] => 1
            [delete_plugins] => 1
            [install_plugins] => 1
            [update_themes] => 1
            [install_themes] => 1
            [update_core] => 1
            [list_users] => 1
            [remove_users] => 1
            [promote_users] => 1
            [edit_theme_options] => 1
            [delete_themes] => 1
            [export] => 1
            [restrict_content] => 1
            [list_roles] => 1
            [create_roles] => 1
            [delete_roles] => 1
            [edit_roles] => 1
            [copy_posts] => 1
            [wpseo_manage_options] => 1
            [manage_woocommerce] => 1
            [view_woocommerce_reports] => 1
            [edit_product] => 1
            [read_product] => 1
            [delete_product] => 1
            [edit_products] => 1
            [edit_others_products] => 1
            [publish_products] => 1
            [read_private_products] => 1
            [delete_products] => 1
            [delete_private_products] => 1
            [delete_published_products] => 1
            [delete_others_products] => 1
            [edit_private_products] => 1
            [edit_published_products] => 1
            [manage_product_terms] => 1
            [edit_product_terms] => 1
            [delete_product_terms] => 1
            [assign_product_terms] => 1
            [edit_shop_order] => 1
            [read_shop_order] => 1
            [delete_shop_order] => 1
            [edit_shop_orders] => 1
            [edit_others_shop_orders] => 1
            [publish_shop_orders] => 1
            [read_private_shop_orders] => 1
            [delete_shop_orders] => 1
            [delete_private_shop_orders] => 1
            [delete_published_shop_orders] => 1
            [delete_others_shop_orders] => 1
            [edit_private_shop_orders] => 1
            [edit_published_shop_orders] => 1
            [manage_shop_order_terms] => 1
            [edit_shop_order_terms] => 1
            [delete_shop_order_terms] => 1
            [assign_shop_order_terms] => 1
            [edit_shop_coupon] => 1
            [read_shop_coupon] => 1
            [delete_shop_coupon] => 1
            [edit_shop_coupons] => 1
            [edit_others_shop_coupons] => 1
            [publish_shop_coupons] => 1
            [read_private_shop_coupons] => 1
            [delete_shop_coupons] => 1
            [delete_private_shop_coupons] => 1
            [delete_published_shop_coupons] => 1
            [delete_others_shop_coupons] => 1
            [edit_private_shop_coupons] => 1
            [edit_published_shop_coupons] => 1
            [manage_shop_coupon_terms] => 1
            [edit_shop_coupon_terms] => 1
            [delete_shop_coupon_terms] => 1
            [assign_shop_coupon_terms] => 1
            [graphql_user] => 1
            [administrator] => 1
        )

    [filter] => 
    [site_id:WP_User:private] => 1
)

[06-Sep-2022 15:36:16 UTC] {"query":"mutation createOrder \n              {\n                createOrder(\n                  input: {\n                    besteldatum: \"2022-09-06\", \n                    bestelstatus: \"open\",\n                    betaalmodus: \"termijn\",\n                    emailadres: \"info@huppeldepup.nl\", \n                    lidmaatschapid: \"3051\", \n                    molliepaymentid: \"tr_\",\n                    naam: \"test bestelling 3051\", \n                    termijnbedrag: \"\u20ac 100,00\",\n                    totaalbedrag: \"\u20ac 300,00\", \n                }\n                ) {\n                  order {\n                    databaseId\n                  }\n                }\n              }","operation":null,"variables":null,"params":{"queryId":null,"query":"mutation createOrder \n              {\n                createOrder(\n                  input: {\n                    besteldatum: \"2022-09-06\", \n                    bestelstatus: \"open\",\n                    betaalmodus: \"termijn\",\n                    emailadres: \"info@huppeldepup.nl\", \n                    lidmaatschapid: \"3051\", \n                    molliepaymentid: \"tr_\",\n                    naam: \"test bestelling 3051\", \n                    termijnbedrag: \"\u20ac 100,00\",\n                    totaalbedrag: \"\u20ac 300,00\", \n                }\n                ) {\n                  order {\n                    databaseId\n                  }\n                }\n              }","operation":null,"variables":null,"extensions":null}}
[06-Sep-2022 15:36:16 UTC] maakBestellingAan: 3159
[06-Sep-2022 15:36:16 UTC] WP_User Object
(
    [data] => stdClass Object
        (
            [ID] => 328
            [user_login] => xxxxxxxxx
            [user_pass] => yyyyyyyyyyyyy
            [user_nicename] => xxxxxxxxx
            [user_email] => someone@mydomain.com
            [user_url] => 
            [user_registered] => 2022-08-31 07:33:34
            [user_activation_key] => 
            [user_status] => 0
            [display_name] => xxxxxxxxx
        )

    [ID] => 328
    [caps] => Array
        (
            [graphql_user] => 1
            [administrator] => 1
        )

    [cap_key] => xyz_capabilities
    [roles] => Array
        (
            [0] => graphql_user
            [1] => administrator
        )

    [allcaps] => Array
        (
            [delete_others_pages] => 1
            [delete_others_posts] => 1
            [delete_pages] => 1
            [delete_posts] => 1
            [delete_private_pages] => 1
            [delete_private_posts] => 1
            [delete_published_pages] => 1
            [delete_published_posts] => 1
            [edit_others_pages] => 1
            [edit_others_posts] => 1
            [edit_pages] => 1
            [edit_posts] => 1
            [edit_private_pages] => 1
            [edit_private_posts] => 1
            [edit_published_pages] => 1
            [edit_published_posts] => 1
            [publish_pages] => 1
            [publish_posts] => 1
            [read] => 1
            [read_private_pages] => 1
            [read_private_posts] => 1
            [switch_themes] => 1
            [edit_themes] => 1
            [activate_plugins] => 1
            [edit_plugins] => 1
            [edit_users] => 1
            [edit_files] => 1
            [manage_options] => 1
            [moderate_comments] => 1
            [manage_categories] => 1
            [manage_links] => 1
            [upload_files] => 1
            [import] => 1
            [unfiltered_html] => 1
            [level_10] => 1
            [level_9] => 1
            [level_8] => 1
            [level_7] => 1
            [level_6] => 1
            [level_5] => 1
            [level_4] => 1
            [level_3] => 1
            [level_2] => 1
            [level_1] => 1
            [level_0] => 1
            [delete_users] => 1
            [create_users] => 1
            [unfiltered_upload] => 1
            [edit_dashboard] => 1
            [update_plugins] => 1
            [delete_plugins] => 1
            [install_plugins] => 1
            [update_themes] => 1
            [install_themes] => 1
            [update_core] => 1
            [list_users] => 1
            [remove_users] => 1
            [promote_users] => 1
            [edit_theme_options] => 1
            [delete_themes] => 1
            [export] => 1
            [restrict_content] => 1
            [list_roles] => 1
            [create_roles] => 1
            [delete_roles] => 1
            [edit_roles] => 1
            [copy_posts] => 1
            [wpseo_manage_options] => 1
            [manage_woocommerce] => 1
            [view_woocommerce_reports] => 1
            [edit_product] => 1
            [read_product] => 1
            [delete_product] => 1
            [edit_products] => 1
            [edit_others_products] => 1
            [publish_products] => 1
            [read_private_products] => 1
            [delete_products] => 1
            [delete_private_products] => 1
            [delete_published_products] => 1
            [delete_others_products] => 1
            [edit_private_products] => 1
            [edit_published_products] => 1
            [manage_product_terms] => 1
            [edit_product_terms] => 1
            [delete_product_terms] => 1
            [assign_product_terms] => 1
            [edit_shop_order] => 1
            [read_shop_order] => 1
            [delete_shop_order] => 1
            [edit_shop_orders] => 1
            [edit_others_shop_orders] => 1
            [publish_shop_orders] => 1
            [read_private_shop_orders] => 1
            [delete_shop_orders] => 1
            [delete_private_shop_orders] => 1
            [delete_published_shop_orders] => 1
            [delete_others_shop_orders] => 1
            [edit_private_shop_orders] => 1
            [edit_published_shop_orders] => 1
            [manage_shop_order_terms] => 1
            [edit_shop_order_terms] => 1
            [delete_shop_order_terms] => 1
            [assign_shop_order_terms] => 1
            [edit_shop_coupon] => 1
            [read_shop_coupon] => 1
            [delete_shop_coupon] => 1
            [edit_shop_coupons] => 1
            [edit_others_shop_coupons] => 1
            [publish_shop_coupons] => 1
            [read_private_shop_coupons] => 1
            [delete_shop_coupons] => 1
            [delete_private_shop_coupons] => 1
            [delete_published_shop_coupons] => 1
            [delete_others_shop_coupons] => 1
            [edit_private_shop_coupons] => 1
            [edit_published_shop_coupons] => 1
            [manage_shop_coupon_terms] => 1
            [edit_shop_coupon_terms] => 1
            [delete_shop_coupon_terms] => 1
            [assign_shop_coupon_terms] => 1
            [graphql_user] => 1
            [administrator] => 1
        )

    [filter] => 
    [site_id:WP_User:private] => 1
)

[06-Sep-2022 15:36:17 UTC] PHP Notice:  Undefined property: WP_Post_Type::$graphql_single_name in /home/customer/www/yogamontfoort.nl/public_html/wp-content/plugins/wp-graphql/src/Mutation/MediaItemUpdate.php on line 47
[06-Sep-2022 15:36:17 UTC] {"query":"mutation createOrder \n              {\n                createOrder(\n                  input: {\n                    besteldatum: \"2022-09-06\", \n                    bestelstatus: \"open\",\n                    betaalmodus: \"termijn\",\n                    emailadres: \"info@huppeldepup.nl\", \n                    lidmaatschapid: \"3051\", \n                    molliepaymentid: \"tr_\",\n                    naam: \"test bestelling 3051\", \n                    termijnbedrag: \"\u20ac 100,00\",\n                    totaalbedrag: \"\u20ac 300,00\", \n                }\n                ) {\n                  order {\n                    databaseId\n                  }\n                }\n              }","operation":null,"variables":null,"params":{"queryId":null,"query":"mutation createOrder \n              {\n                createOrder(\n                  input: {\n                    besteldatum: \"2022-09-06\", \n                    bestelstatus: \"open\",\n                    betaalmodus: \"termijn\",\n                    emailadres: \"info@huppeldepup.nl\", \n                    lidmaatschapid: \"3051\", \n                    molliepaymentid: \"tr_\",\n                    naam: \"test bestelling 3051\", \n                    termijnbedrag: \"\u20ac 100,00\",\n                    totaalbedrag: \"\u20ac 300,00\", \n                }\n                ) {\n                  order {\n                    databaseId\n                  }\n                }\n              }","operation":null,"variables":null,"extensions":null}}
[06-Sep-2022 15:36:17 UTC] maakBestellingAan: bestel id is leeg
[06-Sep-2022 15:36:17 UTC] Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [message] => Cannot query field "createOrder" on type "RootMutation". Did you mean "createUser"?
                    [extensions] => Array
                        (
                            [category] => graphql
                        )

                    [locations] => Array
                        (
                            [0] => Array
                                (
                                    [line] => 3
                                    [column] => 17
                                )

                        )

                )

        )

    [extensions] => Array
        (
            [debug] => Array
                (
                )

        )

)
```
I took over the code in the test plugin and activated it. This was the direct output. The WPGraphQL JWT was disabled, as you requested.
It seems that the mutation query is executed twice. Maybe I should prevent that in the plugin, but how?

**Comment by justlevine** [comment]
@MvS-IT First, I dont see `edit_bestelling` or something similar in the array of user capabilities.

Second, the errors seem to confirm that  `maakBestellingAan()` is getting called before the `plugins_loaded` action, as I suggested in my previous reply...

**Comment by MvS-IT** [comment]
> @MvS-IT First, I dont see `edit_bestelling` or something similar in the array of user capabilities.
> 
> Second, the errors seem to confirm that `maakBestellingAan()` is getting called before the `plugins_loaded` action, as I suggested in my previous reply...

Hi @justlevine, the bestelling and order are  post objects "brought to live" with Atlas Content Modeler. I would suspect that this plugin takes care of the 'edit_bestelling' capability, but since the user is an admin user, this user should be able to edit a bestelling or order.
The `maakBestellingAan()` function is called from the constructor in this test plugin, but in the original plugin it was not. It is still a strange phenomenon that in the subdomain after 120 bestellingen/orders made this way, the original error with not returning a databaseid never occured. The subdomain should be an exact copy of the main domain, but apparently it is not. Siteground hosted btw.
I'm out of clues, if you think it's invalid, then so be it.

**Comment by justlevine** [comment]
@MvS-IT The `invalid?` label just means this is likely not due to a bug in the WPGraphQL plugin, but rather an issue with your code implementation.

> the bestelling and order are post objects "brought to live" with Atlas Content Modeler. I would suspect that this plugin takes care of the 'edit_bestelling' capability, but since the user is an admin user, this user should be able to edit a bestelling or order.

It _would_ take care of the capability, if it was allowed to run before `maakBestellingAan()` was called.

I cant speak to differences to codebases I cannot see, but it shouldnt matter if its in the class constructor or somewhere else, so long as whatever initiated the lifecycle, did so on `add_action( 'plugin_loaded'... )`.

e.g. (pseudocode)

```php

// this is one way
Bestelling::__construct() {
  add_action( 'plugins_loaded', [ $this->maakBestellingAan ] );
}

// this is another way
Bestelling::__construct() {
  $this->maakBestellingAan();
}
add_action( 'plugins_loaded', function() {
  $bestelling = new Bestelling();
}
```

**Comment by MvS-IT** [comment]
@justlevine Thank you very very much! I opted for 
```php
Bestelling::__construct() {
  add_action( 'plugins_loaded', [ $this->maakBestellingAan ] );
}
```

And with a slight modification the databaseid is returned and no further error messages are logged:

```php
add_action( 'plugins_loaded', [$this, 'maakBestellingAan '] );
```

Also the use of wp_set_current_user helped me in this case.

Thanks again!
