### ISSUE TITLE
CreatePost mutation silently fails to create a post

### ISSUE THREAD

**Issue by joshglenn** [wp-graphql/wp-graphql#2501]
### Description

When trying to create a post from the Graphql IDE, CreatePost appears to work, but does not create a post in the database

### Steps to reproduce

1. Go to the Graphql IDE from within the wordpress admin.
2. Enter the following query:
![Screen Shot 2022-09-04 at 1 50 20 PM](https://user-images.githubusercontent.com/6953274/188327163-f3a80d94-b12e-4d68-aa92-61be1b24679f.png)
with this input: 
![Screen Shot 2022-09-04 at 2 06 42 PM](https://user-images.githubusercontent.com/6953274/188327476-cfb6789f-d29d-44e7-a191-e5d8e05c00e5.png)

3. See the following "apparent" result: 
![Screen Shot 2022-09-04 at 1 50 25 PM](https://user-images.githubusercontent.com/6953274/188327184-38851329-21b3-46ca-a921-0ccf35aed8d6.png)

Note: When I try this in debug mode, no debug output appears

4. Query all posts to see if the post _really_ was created...
![Screen Shot 2022-09-04 at 1 50 46 PM](https://user-images.githubusercontent.com/6953274/188327248-8eb7fb5b-4e13-4e60-a3cb-017e543a9386.png)
![Screen Shot 2022-09-04 at 2 01 07 PM](https://user-images.githubusercontent.com/6953274/188327457-9bfbb8b3-1a8d-4c00-9a44-4457662aa109.png)

Notice that only the original "Hello World" post shows in the list.

Any idea why this could be happening?

### WPGraphQL Version

1.9.1

### WordPress Version

6.0.2

### PHP Version

7.4

### Additional enviornment details

Clean install using the docker compose settings contained in wpgraphql-acf repo

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Hey @joshglenn - can you confirm the post doesn't exist in the WordPress backend, perhaps as a draft?

By default the `posts` query only returns published posts (you need to set `where.status` if you want to include pending/draft), and depending on your site config, it's possible the create mutation isn't publishing the post without an explicit input arg as well.

**Comment by joshglenn** [comment]
@justlevine  Thanks for the response.... Yes, excuse my mistake. It was creating draft posts and I didn't realize it.
