### ISSUE TITLE
Error: Server response was missing for query 'IntrospectionQuery'.

### ISSUE THREAD

**Issue by jonathonbauer** [wp-graphql/wp-graphql#2529]
### Description

Visiting the GraphQL IDE generates the error 'Uncaught (in promise) Error: Server response was missing for query 'IntrospectionQuery'.' in the console.

### Steps to reproduce

1. Go to GraphQL IDE
2. Error is generated in the console

### Additional context

- GraphQL IDE does not display the Schema, or allow us to write queries due to this error
- When we try to generate our schema with GQTY locally, we get a similar error "Error: Could not obtain introspection result"
- We have deactivated all other plugins, and still encounter the error
- We have a separate site with the same plugin configuration and WP version, and we do not encounter the error
- We downgraded WPGraphQL back to 1.8.6 to rule out a plugin version issue, and we encountered the same error

Screenshot of the Error:

![image](https://user-images.githubusercontent.com/43574065/191490668-f348e7a6-ce1b-47dd-a4db-a1120c89cd45.png)

### WPGraphQL Version

1.11

### WordPress Version

6.0.2

### PHP Version

8

### Additional enviornment details

- The site is hosted within WP Engine

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jonathonbauer** [comment]
While writing this issue, I found that downgrading PHP to 7.4 solved the issue.

I chose to still open this issue, just to close it with the fix in case someone else runs into the issue.

**Comment by justlevine** [comment]
@jonathonbauer WPGraphQL is fully compatible with PHP 8.0 (its working fine for me on 8.0.19 as we speak), so if changing the PHP version truly fixed it, its likely caused by something else.

If you dont want to stay on PHP 7.4, feel free to reopen (and share both a copy of `debug.log`, and the network response to the `\graphql` endpoint in the IDE, so we can see whats causing the error).
