### ISSUE TITLE
regression: Querying for Menu Items with parentId = 0 returns all menu items

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#2530]
### Description

Previously, querying for menuItems with parentId=0 only returned top level items. Now it's returning all items.

### Steps to reproduce

see: https://github.com/wp-graphql/wp-graphql/pull/2523#issuecomment-1253642196

### Additional context

This is a regressions with release v1.11.0

### WPGraphQL Version

v1.11.0

### WordPress Version

6.0

### PHP Version

8.0

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Is this the same as #2531 ?
