### ISSUE TITLE
`UserRoleEnum` should use all roles instead of `editible_roles`

### ISSUE THREAD

**Issue by jydmnd** [wp-graphql/wp-graphql#2537]
### Description

Since WPGraphQL 1.11, trying to access the template property on a page or post throws an internal server error

### Steps to reproduce

Theses queries will return a 500 internal server error on WPGraphQL version 1.11 and 1.11.1. If I roll back to 1.10, the queries will work as expected.

```
query getPages {
  pages {  
    nodes  {
      template {
      __typename
      }
    }
  }
}

query getPage($id:ID!) {
  page(id:$id,idType:DATABASE_ID) {    
      template {
      __typename
      }
  }
}

````

### WPGraphQL Version

1.11 and 1.11.1

### WordPress Version

6.0.2

### PHP Version

8.0

### Additional enviornment details

Wordpress setup based on Bedrock

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Hey @jydmnd 

With `WP_DEBUG_LOG` and WPGraphQL Debugging enabled, what do you see in your `debug.log` file?

**Comment by jydmnd** [comment]
[23-Sep-2022 19:30:00 UTC] PHP Fatal error:  Uncaught TypeError: GraphQL\Type\Schema::resolveType(): Return value must be of type GraphQL\Type\Definition\Type, null returned in /Users/######/vendor/webonyx/graphql-php/src/Type/Schema.php:406
Stack trace:
#0 /Users/######/vendor/webonyx/graphql-php/src/Type/Definition/InputObjectField.php(121): GraphQL\Type\Schema::resolveType(Object(Closure))
#1 /Users/######/vendor/webonyx/graphql-php/src/Utils/TypeInfo.php(218): GraphQL\Type\Definition\InputObjectField->getType()
#2 /Users/######/vendor/webonyx/graphql-php/src/Utils/TypeInfo.php(222): GraphQL\Utils\TypeInfo::extractTypes(Object(WPGraphQL\Type\WPInputObjectType), Array)
#3 /Users/######/vendor/webonyx/graphql-php/src/Type/Schema.php(222): GraphQL\Utils\TypeInfo::extractTypes(Object(WPGraphQL\Type\WPObjectType), Array)
#4 /Users/######/vendor/webonyx/graphql-php/src/Type/Schema.php(208): GraphQL\Type\Schema->collectAllTypes()
#5 /Users/######/vendor/webonyx/graphql-php/src/Type/Schema.php(448): GraphQL\Type\Schema->getTypeMap()
#6 /Users/######/vendor/webonyx/graphql-php/src/Type/Schema.php(437): GraphQL\Type\Schema->collectImplementations()
#7 /Users/######/vendor/webonyx/graphql-php/src/Type/Schema.php(425): GraphQL\Type\Schema->getImplementations(Object(WPGraphQL\Type\WPInterfaceType))
#8 /Users/######/web/app/plugins/wp-graphql/src/Utils/QueryAnalyzer.php(255): GraphQL\Type\Schema->getPossibleTypes(Object(WPGraphQL\Type\WPInterfaceType))
#9 /Users/######/vendor/webonyx/graphql-php/src/Language/Visitor.php(470): WPGraphQL\Utils\QueryAnalyzer->WPGraphQL\Utils\{closure}(Object(GraphQL\Language\AST\FieldNode), 0, Object(GraphQL\Language\AST\NodeList), Array, Array)
#10 /Users/######/vendor/webonyx/graphql-php/src/Language/Visitor.php(277): GraphQL\Language\Visitor::GraphQL\Language\{closure}(Object(GraphQL\Language\AST\FieldNode), 0, Object(GraphQL\Language\AST\NodeList), Array, Array)
#11 /Users/######/web/app/plugins/wp-graphql/src/Utils/QueryAnalyzer.php(274): GraphQL\Language\Visitor::visit(Object(GraphQL\Language\AST\DocumentNode), Array)
#12 /Users/######/web/app/plugins/wp-graphql/src/Utils/QueryAnalyzer.php(146): WPGraphQL\Utils\QueryAnalyzer->set_list_types(Object(WPGraphQL\WPSchema), 'query getPages ...')
#13 /Users/######/web/wp/wp-includes/class-wp-hook.php(307): WPGraphQL\Utils\QueryAnalyzer->determine_graphql_keys('query getPages ...', 'getPages', Array, Object(GraphQL\Server\OperationParams))
#14 /Users/######/web/wp/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#15 /Users/######/web/wp/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#16 /Users/######/web/app/plugins/wp-graphql/src/Request.php(605): do_action('do_graphql_requ...', 'query getPages ...', 'getPages', Array, Object(GraphQL\Server\OperationParams))
#17 /Users/######/web/app/plugins/wp-graphql/src/Request.php(300): WPGraphQL\Request->do_action(Object(GraphQL\Server\OperationParams))
#18 /Users/######/web/app/plugins/wp-graphql/src/Request.php(701): WPGraphQL\Request->before_execute()
#19 /Users/######/web/app/plugins/wp-graphql/src/Router.php(489): WPGraphQL\Request->execute_http()
#20 /Users/######/web/app/plugins/wp-graphql/src/Router.php(284): WPGraphQL\Router::process_http_request()
#21 /Users/######/web/wp/wp-includes/class-wp-hook.php(307): WPGraphQL\Router::resolve_http_request(Object(WP))
#22 /Users/######/web/wp/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#23 /Users/######/web/wp/wp-includes/plugin.php(524): WP_Hook->do_action(Array)
#24 /Users/######/web/wp/wp-includes/class-wp.php(398): do_action_ref_array('parse_request', Array)
#25 /Users/######/web/wp/wp-includes/class-wp.php(770): WP->parse_request('')
#26 /Users/######/web/wp/wp-includes/functions.php(1330): WP->main('')
#27 /Users/######/web/wp/wp-blog-header.php(16): wp()
#28 /Users/######/web/wp/index.php(17): require('/#####...')
#29 {main}
  thrown in /Users/######/vendor/webonyx/graphql-php/src/Type/Schema.php on line 406

**Comment by justlevine** [comment]
I cant replicate this on a new site with v1.11.1, WP 6.0.2 and PHP 8.0.19.

You sure you disabled all custom code and plugins besides WPGraphQL core?
Also what do you see in the network response? (With GraphQL debugging enabled, sometimes this provides a more detailed trace to the type thats throwing the error)

![image](https://user-images.githubusercontent.com/29322304/192093445-990c0456-18ce-40be-92f5-47aa6c02a54b.png)

**Comment by jydmnd** [comment]
@justlevine I did disable all plugins, but did not remove all our custom code yet, so I did more digging. I found that an authenticated request did not cause the problem, and that it was a filter from our site that caused the issue. Network tab was not of any help.

We're using the `editable_roles` filter to limit which other user roles certain of our custom roles can edit. Since it's an unauthenticated request, the filter would return an empty array. You can essentially use this : 
```
add_filter( 'editable_roles', 'empty_editable_roles' );
function empty_editable_roles( $roles )
{
    return array();
}
````

I'm seeing that the UserRoleEnum type is registered only if there are some editable_users available, so the type would not be declared, but it is used in the Users connections. I'm not sure what changed between 1.10 and 1.11 that would change the behaviour here.

I can probably just bypass the filter from my end if I'm coming from an unauthenticated request as a fix for now.

**Comment by justlevine** [comment]
🤔

@jasonbahl is there a reason we use `editable_roles` instead of registering _all_ roles to the Enum?

[From the docs](https://developer.wordpress.org/reference/functions/get_editable_roles/#description):
> Simple function whose main purpose is to allow filtering of the list of roles in the $wp_roles object so that plugins can remove inappropriate ones depending on the situation or user making edits.
> Specifically because without filtering anyone with the edit_users capability can edit others to be administrators, even if they are only editors or authors. This filter allows admins to delegate user management.

Since we dont want the enum to change based on user _and_ `editable_roles` serves a specific use case, maybe we should just be using `wp_roles()->get_names()`?

**Comment by jasonbahl** [comment]
How does the editable_roles filter fit into querying templates?

I'm glad this was found but not sure how they relate?

@justlevine my guess is I was trying to just make sure whatever list we use was filterable? If we can use the names and get the same outcome I imagine it's fine.

**Comment by jydmnd** [comment]
@jasonbahl The only thing I can think of right now is that the template field is the only one that is not a primitive type or a connection on a Post object. But I've looked into the ContentTemplate class, everything looks fine and the type is properly defined in the documentation, so that's not it...

**Comment by betweenbrain** [comment]
Hello,

We've just run into this issue ourselves and would be happy to help pinpoint the cause.

**Comment by betweenbrain** [comment]
> ```
> [23-Sep-2022 19:30:00 UTC] PHP Fatal error:  Uncaught TypeError: GraphQL\Type\Schema::resolveType(): Return value must be of type GraphQL\Type\Definition\Type, null returned in /Users/######/vendor/webonyx/graphql-php/src/Type/Schema.php:406
> Stack trace:
> #0 /Users/######/vendor/webonyx/graphql-php/src/Type/Definition/InputObjectField.php(121): GraphQL\Type\Schema::resolveType(Object(Closure))
> #1 /Users/######/vendor/webonyx/graphql-php/src/Utils/TypeInfo.php(218): GraphQL\Type\Definition\InputObjectField->getType()
> #2 /Users/######/vendor/webonyx/graphql-php/src/Utils/TypeInfo.php(222): GraphQL\Utils\TypeInfo::extractTypes(Object(WPGraphQL\Type\WPInputObjectType), Array)
> #3 /Users/######/vendor/webonyx/graphql-php/src/Type/Schema.php(222): GraphQL\Utils\TypeInfo::extractTypes(Object(WPGraphQL\Type\WPObjectType), Array)
> #4 /Users/######/vendor/webonyx/graphql-php/src/Type/Schema.php(208): GraphQL\Type\Schema->collectAllTypes()
> #5 /Users/######/vendor/webonyx/graphql-php/src/Type/Schema.php(448): GraphQL\Type\Schema->getTypeMap()
> #6 /Users/######/vendor/webonyx/graphql-php/src/Type/Schema.php(437): GraphQL\Type\Schema->collectImplementations()
> #7 /Users/######/vendor/webonyx/graphql-php/src/Type/Schema.php(425): GraphQL\Type\Schema->getImplementations(Object(WPGraphQL\Type\WPInterfaceType))
> #8 /Users/######/web/app/plugins/wp-graphql/src/Utils/QueryAnalyzer.php(255): GraphQL\Type\Schema->getPossibleTypes(Object(WPGraphQL\Type\WPInterfaceType))
> #9 /Users/######/vendor/webonyx/graphql-php/src/Language/Visitor.php(470): WPGraphQL\Utils\QueryAnalyzer->WPGraphQL\Utils\{closure}(Object(GraphQL\Language\AST\FieldNode), 0, Object(GraphQL\Language\AST\NodeList), Array, Array)
> #10 /Users/######/vendor/webonyx/graphql-php/src/Language/Visitor.php(277): GraphQL\Language\Visitor::GraphQL\Language\{closure}(Object(GraphQL\Language\AST\FieldNode), 0, Object(GraphQL\Language\AST\NodeList), Array, Array)
> #11 /Users/######/web/app/plugins/wp-graphql/src/Utils/QueryAnalyzer.php(274): GraphQL\Language\Visitor::visit(Object(GraphQL\Language\AST\DocumentNode), Array)
> #12 /Users/######/web/app/plugins/wp-graphql/src/Utils/QueryAnalyzer.php(146): WPGraphQL\Utils\QueryAnalyzer->set_list_types(Object(WPGraphQL\WPSchema), 'query getPages ...')
> #13 /Users/######/web/wp/wp-includes/class-wp-hook.php(307): WPGraphQL\Utils\QueryAnalyzer->determine_graphql_keys('query getPages ...', 'getPages', Array, Object(GraphQL\Server\OperationParams))
> #14 /Users/######/web/wp/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
> #15 /Users/######/web/wp/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
> #16 /Users/######/web/app/plugins/wp-graphql/src/Request.php(605): do_action('do_graphql_requ...', 'query getPages ...', 'getPages', Array, Object(GraphQL\Server\OperationParams))
> #17 /Users/######/web/app/plugins/wp-graphql/src/Request.php(300): WPGraphQL\Request->do_action(Object(GraphQL\Server\OperationParams))
> #18 /Users/######/web/app/plugins/wp-graphql/src/Request.php(701): WPGraphQL\Request->before_execute()
> #19 /Users/######/web/app/plugins/wp-graphql/src/Router.php(489): WPGraphQL\Request->execute_http()
> #20 /Users/######/web/app/plugins/wp-graphql/src/Router.php(284): WPGraphQL\Router::process_http_request()
> #21 /Users/######/web/wp/wp-includes/class-wp-hook.php(307): WPGraphQL\Router::resolve_http_request(Object(WP))
> #22 /Users/######/web/wp/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
> #23 /Users/######/web/wp/wp-includes/plugin.php(524): WP_Hook->do_action(Array)
> #24 /Users/######/web/wp/wp-includes/class-wp.php(398): do_action_ref_array('parse_request', Array)
> #25 /Users/######/web/wp/wp-includes/class-wp.php(770): WP->parse_request('')
> #26 /Users/######/web/wp/wp-includes/functions.php(1330): WP->main('')
> #27 /Users/######/web/wp/wp-blog-header.php(16): wp()
> #28 /Users/######/web/wp/index.php(17): require('/#####...')
> #29 {main}
>   thrown in /Users/######/vendor/webonyx/graphql-php/src/Type/Schema.php on line 406
> ```

Hello,

We've just run into a similar issue, with the same error, when upgrading to v1.13.7 and have traced it back to v1.11.0.

**Comment by barticus** [comment]
We ran into this issue too after updating. I have rolled back to version 1.10 which appears to have resolved it.

**Comment by justlevine** [comment]
> We ran into this issue too after updating. I have rolled back to version 1.10 which appears to have resolved it. We were seeing it when querying for gravity forms data.

@barticus a 500 internal server error usually means a fatal PHP error. If you're getting one when querying GF data, it's probably a different issue than this ticket caused by the WPGraphQL for GF plugin. If you [open a bug report in that repo](https://github.com/harness-software/wp-graphql-gravity-forms/issues/new?assignees=&labels=&template=bug_report.yml) with the requested information and a copy of your `debug.log`, I'd be happy to look into it.

**Comment by barticus** [comment]
Thanks @justlevine , I think it's this issue, because the stack trace is the same.


> TypeError: Return value of GraphQL\Type\Schema::resolveType() must be an instance of GraphQL\Type\Definition\Type, null returned #28 /wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Type/Schema.php(406): GraphQL\Type\Schema::resolveType #27 /wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Type/Definition/FieldDefinition.php(208): GraphQL\Type\Definition\FieldDefinition::getType #26 /wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/TypeInfo.php(213): GraphQL\Utils\TypeInfo::extractTypes

**Comment by barticus** [comment]
@justlevine yeah, apologies, it's just a generic error.

Unfortunately the network trace didn't reveal much - it was my starting point. I'm not sure what is being used on top (it's a nextjs app), but embedded in the json response is just that there was a 500 error retrieving the GF data. 
I'll need to do some more digging to find what exactly is making it unhappy, and don't want to do that in the prod environment.

But, rolling back was the workaround for now.

**Comment by justlevine** [comment]
Discussed in triage:

We should use all the roles instead of filterable ones to build the enum, instead of changing the enum per user (the intent of the of `editable_roles` filters). Users wishing to filter the enum values can make use of the pre-existing filters.

All usage of `UserRoleEnum` should be audited when this change is made to ensure that permissions are being checked correctly.
