### ISSUE TITLE
Preflight OPTIONS requests are returning 500 status

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#256]
HTTP clients such as Apollo and Axios send "pre-flight" requests, and we're not respecting those, but instead are returning a 500. 

We need to respect the pre-flight requests.

see: https://wp-graphql.slack.com/archives/C3NM1M291/p1507650342000560
see: https://apollographql.slack.com/archives/C10HTKHPC/p1507649812000123
see: https://apollographql.slack.com/archives/C10HTKHPC/p1507650789000675

**Comment by CodeProKid** [comment]
This was handled in #257
