### ISSUE TITLE
updating from 1.9 -> 1.11.2 results in Error: Request failed with status code 520

### ISSUE THREAD

**Issue by tsdexter** [wp-graphql/wp-graphql#2561]
### Description

I'm getting these errors using gatsby after updating WP GraphQL... I haven't sorted out the exact underlying error, but I am noticing in WP Engine error logs I'm getting notices like: 

`KILLED QUERY (19031 characters long generated in /nas/content/live/sitename/wp-content/plugins/wp-graphql/src/Data/Loader/PostObjectLoader.php:118)`

Adding `WPE_GOVERNOR=false` did seem to stop the `KILLED_QUERY` notice, but didn't solve the unresponsive graphql. See: https://searchwp.com/v3/docs/kb/attention-wp-engine-customers-no-results-long-query-killed-query-notices/

Can you point me in the right direction as to when/where you made significant changes to the queries between 1.9 -> 1.11.2 and I can start doing upgrades to earlier versions and other debugging to try to isolate the issue and create a reproduction

### Steps to reproduce

- Build a large site on 1.11.2 using WP Engine and Gatsby

### WPGraphQL Version

1.11.2

### WordPress Version

6.0.2

### PHP Version

7.4

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
@tsdexter I've not seen this error before 🤔 

The 1.11.0 release did introduce some changes to the headers being returned, and that has caused some issues, typically with an error such as `Parse Error: Header overflow`. 

See: https://github.com/wp-graphql/wp-graphql/issues/2548 & https://github.com/wp-graphql/wp-graphql/issues/2535

I'm not sure if this is related to what you're experiencing or not. 

Can try this suggestion [here](https://github.com/wp-graphql/wp-graphql/issues/2535#issuecomment-1260156227) and see if the error goes away?

**Comment by justlevine** [comment]
@tsdexter alternatively, can you check if #2562 fixes things for you _without_ the above workaround? 🤞🤞🤞

**Comment by jasonbahl** [comment]
I have a feeling the header changes are unrelated. The error is related to long SQL query strings generated from WP_Query. 🤔

**Comment by tsdexter** [comment]
I'll update to the version before 1.11.0 and check if that works, then I'll try each of the fixes. Will report back

**Comment by jasonbahl** [comment]
@tsdexter just released v1.11.3 as well that _should_ fix the header overflow issue. 

But, I still have a hunch there's something different happening for you, unrelated to this known-bug with header size. 

That error seems to be related to the string size generated for SQL queries within the WP_Query calls. 

My hunch is that another plugin that filters WP_Query is at play here.

**Comment by tsdexter** [comment]
@jasonbahl ok, I'll check that too... we are using https://publishpress.com/permissions/ which does a lot of query filtering iirc, so I'll go down that route as well.

**Comment by jasonbahl** [comment]
@tsdexter you should be able to enable Query Logging from WPGraphQL > Settings (you might also need Query Monitor active)

But then you will get logs in your GraphQL output that have the underlying SQL queries. Like so: 

![CleanShot 2022-10-06 at 08 12 51](https://user-images.githubusercontent.com/1260765/194336537-b193ffc5-3cbb-4a5b-82cb-511585e88ee3.png)

From there, you should be able to start identifying all the underlying SQL queries executed during a WPGraphQL request, and then narrow down the _really long_ ones that. 

From there you probably will be able to identify what plugin(s) are affecting the queries.

**Comment by tsdexter** [comment]
@jasonbahl  it looks like the killed_query and header overflow were related... I re-built on local and got the header overflow errors. 1.12 is working 👍

**Comment by tsdexter** [comment]
fyi for others: the error showing in WP Engine dashboard was not header overflow, rather `Error: Request failed with status code 520`

**Comment by jasonbahl** [comment]
@tsdexter thanks for the follow-up! Glad to hear it's working again.
