### ISSUE TITLE
Where parameter for Menu Items returns ALL values

### ISSUE THREAD

**Issue by TomDoFuture** [wp-graphql/wp-graphql#2567]
### Description

if you do Where parentId : null then you will get every menu item

Where parentDatabaseId works as intended:

ParentDatabaseid works as intended
![image](https://user-images.githubusercontent.com/108644869/194473700-f1da0a20-538b-4bf9-beb2-da5bbcf324ec.png)

parentid?????
![image](https://user-images.githubusercontent.com/108644869/194473808-3a8d7481-59f3-4fbc-8ed6-d1dce3fc14fe.png)

Note that I have tried both with "null" and null

### Steps to reproduce

query MenuTest {
  menu(id: "your header menu name", idType: NAME) {
    id
    menuItems(first: 200, where: {parentId: null}) {
      nodes {
        parentId
        parentDatabaseId
      }
    }
  }
}

### WPGraphQL Version

1.11.3

### WordPress Version

6.0.2

### PHP Version

8.0

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [ ] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Hey @TomDoFuture ,

Per the [WPQuery API](https://developer.wordpress.org/reference/classes/wp_query/#post-page-parameters), you should explicitly set `0` if you want _only_ top-level items, as you did with `parentDatabaseId` in the first query.

(In most contexts, `null` input arg values are the equivalent to it being `unset`, to allow dynamic query building with `$variables` to work as expected.)

**Comment by TomDo1234** [comment]
Interesting.... Alright Closing

**Comment by TomDo1234** [comment]
@justlevine Feel free to close it, this is my personal account, the TomDoFuture was company
