### ISSUE TITLE
Pagination Returning same startCursor and endCursor values 

### ISSUE THREAD

**Issue by flyingkitlets** [wp-graphql/wp-graphql#2570]
### Description

Pagination Returning same startCursor and endCursor values. This makes pagination impossible for me.

### Steps to reproduce

When I make my first query, of first 10 with null after, I get the expected response: 

```
"pageInfo": {
          "hasNextPage": true,
          "endCursor": "YXJyYXljb25uZWN0aW9uOjI4NzQx",
          "startCursor": "YXJyYXljb25uZWN0aW9uOjI4NzM1",
          "hasPreviousPage": false
}
```

When I use the endCursor value to populate the after param, I get a response with the same start and end cursors: 

```
"pageInfo": {
          "hasNextPage": false,
          "endCursor": "YXJyYXljb25uZWN0aW9uOjI4NzQy",
          "startCursor": "YXJyYXljb25uZWN0aW9uOjI4NzQy",
          "hasPreviousPage": true
}
```

I know for a fact there are around 1700 posts that should appear here, so I can't be at the end of the expected output. It feels as if the endCursor I used has taken me to the end of the entire data set, not the end of my request, which was asking for the first 10. 

### Additional context

Using WooCommerce GraphQL, this is searching for a product's variations via slug. The query is as follows:

```
query VariationsByProject($slug: ID!, $first: Int, $last:Int, $before:String, $after:String) {
  product(id: $slug, idType: SLUG) {
    ... on VariableProduct {
      id
      name
      variations(first:$first, last:$last, before: $before, after: $after) {
        nodes {
          sku
          uri
          id
          regularPrice(format: FORMATTED)
          salePrice(format: FORMATTED)
          price(format: FORMATTED)
          name
          attributes(first: 100) {
            nodes {
              id
              label
              name
              value
            }
            edges {
              node {
                id
              }
            }
          }
          databaseId
          description
        }
        pageInfo {
          hasNextPage
          endCursor
          startCursor
          hasPreviousPage
        }
      }
    }
  }
}
```

### WPGraphQL Version

1.11.3

### WordPress Version

6.0.2

### PHP Version

7.2.34

### Additional enviornment details

I have tried disabling all I can. Since it's using WooComm, the only plugins I left were WooCommerce 6.6.0 and WPGraphQL WooCommerce (WooGraphQL) 0.11.2

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [ ] Yes
- [X] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Hey @flyingkitlets 👋,

Does the pagination issue only happen with nested Product Variations, or also nested core types? (E.g. `categories { nodes { posts( $post_args ) { ...Frag } } }` )?

(Possibly related: https://github.com/wp-graphql/wp-graphql-woocommerce/issues/447)

**Comment by justlevine** [comment]
@flyingkitlets I'm trying to understand whether the issue is Woo-specific or with the core WPGraphQL plugin. By core types, i mean the types that are created by the latter e.g. `Post`, `Page`, `Category` etc.

Please try the following query (if you dont have any Posts or Post categories, create a few for the test):
```graphql

query PostsByCategory($id: ID!, $first: Int, $last:Int, $before:String, $after:String) {
  category(id: $id, idType: DATABASE_ID) {
    id
    name
    posts(first:$first, last:$last, before: $before, after: $after) {
      nodes {
       id
       title
      }
      pageInfo {
        hasNextPage
        endCursor
        startCursor
        hasPreviousPage
      }
    }
  }
}

**Comment by justlevine** [comment]
Closing this since we never heard back, and there's been a significant number of fixes/changes to cursor handling in the various releases of WPGraphQL/ WooGraphQL since this was opened.

@flyingkitlets if you're still running into this issue, please comment here with the previously requested information so we can try to replicate and address it.
