### ISSUE TITLE
CDN is not working in graphQL

### ISSUE THREAD

**Issue by jignam** [wp-graphql/wp-graphql#2578]
### Description

Hi There,

We are using GraphQL and we are happy with it but recently we are facing issue with CDN. CDN was working fine before but in recent update, it stopped working it. 

I can see CDN URL in WP frontend but i can;t see in frontend project or graphQL query response.  Please refer below screen shots for the same.

API Frontend :: https://www.screencast.com/t/8adTEcvL
CDN response :: https://www.screencast.com/t/hTlUhIfh8H

We have used "CDN Enabler" plugin for CDN. First it was working with CDN Enabler and W3 total cache but not it is not working with any of this. 

### Steps to reproduce

API Frontend :: https://www.screencast.com/t/8adTEcvL
CDN response :: https://www.screencast.com/t/hTlUhIfh8H

### WPGraphQL Version

 1.11.2

### WordPress Version

6.0.2

### PHP Version

7.4

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [ ] Yes
- [X] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Hey @jignam 

> CDN was working fine before but in recent update, it stopped working it.

Can you please clarify _what_ actually updated? Which plugin, what version was last working and what are you using now?

Also, I see you're using v1.11.2. Can you please update to the latest v1.12.0 and confirm the problem persists?

**Comment by jignam** [comment]
Hi @justlevine 

Thanks for quick response!

if i update latest version of graphQL, my website is stop working. please refer below two screen shot for the same.

Backend GraphQL IDE is stop working :: https://www.screencast.com/t/DhmWqPTQEJ
Frontend ::  https://www.screencast.com/t/Re06ccV4Q

I think, it is returning any error. 

I have downgrade graphQL version and website is running well.

**Can you please clarify what actually updated? Which plugin, what version was last working and what are you using now?**

 My all plugin and WP is updated except latest graphQL.  Please refer below screen shot which plugin we are using for the website.  Actually, i don't have proper data when it stopped working. let me know if you need any further details from myend. But CDN is working fine if you i have review API URL in frontend and everything is coming through CDN, but i am not getting CDN URL in graphQL response. 
 
 https://www.screencast.com/t/A4kYqru6nNv

Thanks for your help!

**Comment by justlevine** [comment]
There's too many things here to accurately diagnose and/or replicate this bug. If this CDN Enabler was compatible with WPGraphQL in the past, then there are two possibilities: either CDN Enabler changed how it hooks into WordPress, or there is an uncaught regression / change of behavior in WPGraphQL. 

Your first step should be getting WPGraphQL up and running on the latest version. You can follow [these steps](https://www.wpgraphql.com/docs/debugging/#checking-the-response) to diagnose and fix whatever conflict is preventing you from running it.

Once that is done, you should disable _all plugins_ except for WPGraphQL and CDN Enabler, and confirm the issue persists. 

Finally, you should downgrade WPGraphQL version by version until you find one that previously worked with CDN Enabler, and share that version.

Only once we have that can we provide an accurate diagnosis and if possible provide a workaround/ ship a fix

**Comment by justlevine** [comment]
Hey @jignam just following up - were you able to get this sorted?

**Comment by justlevine** [comment]
Hey @jignam ,

Never heard back from you, so Im going to assume you were able to address the conflict and close this out.

If you're still having issues, please comment back with the previous requested troubleshooting steps completed, and we'll reopen and investigate.
