### ISSUE TITLE
Errors to never return status 200 ?

### ISSUE THREAD

**Issue by cantoute** [wp-graphql/wp-graphql#2585]
### What problem does this address?

In production world, it's common to use some form of proxy cache.

One nice feature is `Stale-If-Error`

Error detection is based on response STATUS

So if errors return status 200... proxy will cache the error... and your nice varnish setup falls to bits when trying to prevent wp crash from affecting visitors.

With several thousands visitors, losing varnish is not what we want right?

I'm happy to give a hand, but this is probably something to implement deep in the logic, it would take someone with a wide view of the code to guide me where I should implement it.

PHP isn't my favorite language, but with over 10 years of practice I should be able to propose a descent pull request.

**Comment by justlevine** [comment]
Hey @cantoute 👋,

To my knowledge, GraphQL implementations use a status code of 200 to refer to when the server is able to _successfully read and respond to_ a request, not whether the underlying query was successful. Here's a couple articles on the topic:

- [How Apollo GraphQL handles errors](https://www.apollographql.com/docs/react/data/error-handling/)
- [The differences between REST and GraphQL error handling](https://blog.graphqleditor.com/graphql-vs-rest-errors)

I'm not perfectly familiar as how/when WPGraphQL specifically sends 40x/50x errors, but if you can provide a specific list of cases where you believe the status code should be changed (while keeping in line with ecosystem patterns), then we could advance this ticket by evaluating each one.

Thanks!

**Comment by jasonbahl** [comment]
@cantoute I'd be open to exploring ideas here more, but I think we'd need more of a detailed plan on what you have in mind before we consider this actionable. 

I'm going to close this issue as I don't think there's enough information to do anything at the moment, but if you want to write up a plan we can discuss, that would be great!
