### ISSUE TITLE
DocBlock param types should use Fully-Qualified Class Names

### ISSUE THREAD

**Issue by justlevine** [wp-graphql/wp-graphql#2588]
### What problem does this address?

In working on [WPGraphQL Stubs](https://github.com/AxeWP/wp-graphql-stubs), I noticed that the param doc-types were not getting stubbed correctly.

The [reason for this](https://github.com/php-stubs/generator/issues/10#issuecomment-1025089584) is the PHPDoc expectation that types use fully-qualified classnames (FQCN).

### What is your proposed solution?

Change all class references in doc-blocks to FQCN

### What alternatives have you considered?

Someone could manually override the doc-block params in their local code. IMO this is bad DX.

### Additional Context

Example code:
```php
<?php
/**
 * @package MyPackage
 * @since 0.0.1
 */

namespace Me\MyNamespace;

use GraphQL\Type\Definition\ResolveInfo;
use WPGraphQL\AppContext;
use WPGraphQL\Data\Connection\AbstractConnectionResolver;

/**
 * Class - MyResolver
 */
class MyResolver extends AbstractConnectionResolver {
  /**
   * {@inheritDoc}
  */
  public function __construct( $source, array $args, AppContext $context, ResolveInfo $info ) {
   /// do something.

    parent::__construct( $source, $args, $context, $info );
  }
}
```

PHPstan shows me the following errors:
```console
- Parameter $context of method Me\MyNamespace\MyResolver::__construct() has invalid type WPGraphQL\Data\Connection\AppContext.  
- Parameter $info of method Me\MyNamespace\MyResolve::__construct() has invalid type WPGraphQL\Data\Connection\ResolveInfo. 
```

Indeed, if I go to the [generated stubfile](https://github.com/AxeWP/wp-graphql-stubs/blob/main/wp-graphql-stubs.php#L1120-L1132), while the actual method parameters get stubbed correctly, the doc-block parameters go unchanged, causing PHPStan to believe the `AppContext` and `ResolveInfo` classes are colocated in the `WPGraphQL\Data\Connection` namespace.

**Comment by szepeviktor** [comment]
Slevomat must have a sniff for that.

**Comment by justlevine** [comment]
And so they do: https://github.com/slevomat/coding-standard/blob/master/doc/namespaces.md#slevomatcodingstandardnamespacesfullyqualifiedclassnameinannotation-
