### ISSUE TITLE
Add Multisite (Network) Support

### ISSUE THREAD

**Issue by CodeProKid** [wp-graphql/wp-graphql#259]
Currently, the plugin is only built to support a single site instance, but I think it would be really powerful to add some support for multisite. Behind the scenes, I think this could potentially be pretty simple...

We could essentially have a "site" query to select a site to perform an operation for, and then just use `switch_to_blog()` behind the scenes.

Would be great to get some community involvement on this issue, since none of us maintainers are actively using multisite.

**Comment by blocka** [comment]
Why wouldn't this Just Work :tm: when you access the graphql endpoint from the multisites url? Unless i'm misunderstanding the issue.

**Comment by jasonbahl** [comment]
@blocka depending on how you expect it to work, it already does. 

If you simply want an endpoint for each site of a multisite install, you have that. 

For example, on subdirectory installs you have: `https://site.com/site1/graphql` and for subdomain installs you would have `https://site1.site.com/graphql`

Right now, there's not really a concept of a network endpoint, where you can get introspection into your entire networks "graph" from a single spot. 

It would be cool to potentially hit one endpoint and be able to query something like: 

```
{
  networkSettings {
     defaultLanguage
  }
  site( id:"site1" ) {
     posts {
        ...postInfo
     }
  }
  site2: site( id:"site2" ) {
     posts {
        ...postInfo
     }
  }
}
```

Where you are able to query data from your network settings and individual sites all in a single GraphQL request. 

The use cases are pretty far and wide.

**Comment by malfborger** [comment]
@jasonbahl What's the status here? I've got a multisite platform that i'd love to set up with gatsbyjs but I guess that I need it to be up and running with one enpoint with the various sites posts etc.

**Comment by jasonbahl** [comment]
@malfborger I don’t personally use multisite often so it hasn’t been a super high priority for me. Would love to collaborate with folks that do use multisite often to get an idea of what the vision for multisite support should be. 

If you have thoughts on what you’d like to see, even initially I’d love to hear more.

**Comment by jasonbahl** [comment]
@malfborger would Slack work? We have a WPGraphQL Slack already. 

You can join here if you’re not already in: https://wpgql-slack.herokuapp.com/

**Comment by sanderploegsma** [comment]
@malfborger not sure if you still need this a year later, but I ran into the same issue. I ended up creating a separate source plugin for Gatsby that uses schema delegation to combine sources with the same schema into one: https://github.com/XebiaStudio/gatsby-source-graphql-multiple

**Comment by mehha** [comment]
Hi. whats status here, do you plan adding multisite support?

**Comment by jasonbahl** [comment]
@mehha is there anything specific you're looking to be able to query? 

Right now, when using WPGraphQL, each multisite site will have its own `/graphql` endpoint, so you can use it with multisite in that way. 

If you're looking for the ability to query things like Network Settings, etc that's not on my personal near-term roadmap, but if you have specific ideas for what you think should be supported that would be helpful to get a more serious discussion going.

**Comment by mehha** [comment]
My multisite has been set up with sub-directories (languages), example.com/en, example.com/et etc, which are basically different languages. So my intrest is same as you already proposed here  - ability to query individual sites all in a single GraphQL request. See your 19 Mar 2018 comment @jasonbahl

**Comment by sanky72** [comment]
> @malfborger not sure if you still need this a year later, but I ran into the same issue. I ended up creating a separate source plugin for Gatsby that uses schema delegation to combine sources with the same schema into one: https://github.com/XebiaStudio/gatsby-source-graphql-multiple

This is not working for me, please check this [issue](https://github.com/XebiaStudio/gatsby-source-graphql-multiple/issues/2)

**Comment by ehabdevel** [comment]
Following the example here: [https://www.wpgraphql.com/recipes/register-object-and-field-for-custom-list-of-users](https://www.wpgraphql.com/recipes/register-object-and-field-for-custom-list-of-users) .

Here is a small solution for getting some basic info: 

`add_action('graphql_register_types', function() {
    register_graphql_object_type(
            'StuntPage',
            [
                'description' => __('Stunt Page', 'text-domain'),
                'fields' => [
                    'page_id' => [
                        'type' => 'Int',
                        'description' => 'blog id'
                    ],
                    'page_path' => [
                        'type' => 'String',
                        'description' => 'path'
                    ],
                    'page_name' => [
                        'type' => 'String',
                        'description' => 'blog name'
                    ],
                ],
            ]
    );
    register_graphql_field(
            'RootQuery',
            'stuntPages',
            [
                'description' => __('Return stunt pages', 'text-domain'),
                'type' => ['list_of' => 'stuntPage'],
                'resolve' => function() {
                    $stunt_pages = [];
                    $args = array('limit' => 0, 'public' => true, 'spam' => false, 'deleted' => false);
                    $pages = get_sites($args); // get the sites into an object
                    foreach ($pages as $p) {
                        $page = [
                            'page_id' => $p->blog_id,
                            'page_path' => $p->path,
                            'page_name' => $p->blogname,
                        ];
                        $stunt_pages[] = $page;
                    }
                    return $stunt_pages;
                }
            ]
    );
});`

Hope it help.

**Comment by jasonbahl** [comment]
I don't think there's anything actionable here right now. 

The concept of multisite support is nice, but we'd need much more concrete use cases to justify pursuing this in any meaningful way. 

For now I think this is extension plugin territory but would love to see some examples, if anyone is doing anything interesting to add "network" support via the graph.
