### ISSUE TITLE
updateUser mutation returns 'TypeError' when updating password

### ISSUE THREAD

**Issue by PR91** [wp-graphql/wp-graphql#2592]
### Description

Using the updateUser mutation to change user password returns a "TypeError".

`{
  "name": "TypeError",
  "message": "NetworkError when attempting to fetch resource.",
  "stack": ""
}`

The password changes, and I receive the email but it sill returns a TypeError.

### Steps to reproduce

I am using JWT plugin and I am sending this mutation:

`mutation UpdateUser($input: UpdateUserInput!) {
  updateUser(input: $input) {
    user {
      name
    }
  }
}`

with the following input:

`{
  "input": {
    "id": "1",
    "password": "new_password",
  }
}`

### WPGraphQL Version

1.12.0

### WordPress Version

6.0.3

### PHP Version

7.4.3

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [ ] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
@PR91 I don't believe this is an error in WPGraphQL, but an error in your client making the fetch. 

Do you have concrete steps to reproduce?

Can you do the mutation successfully in the GraphiQL IDE in the WordPress dashboard?

**Comment by justlevine** [comment]
Hey @PR91 - just following up. Were you able to sort this out?

**Comment by justlevine** [comment]
@PR91 havnt heard back in a while, so I'm going to assume you got this sorted.

If not, please let us know and we'll reopen the issue .
