### ISSUE TITLE
Can only query media that is used in a post

### ISSUE THREAD

**Issue by gbe-trackunit** [wp-graphql/wp-graphql#2595]
### Description

I'm only able to query media that is used in a wordpress post.  If I remove the image from a post it becomes unavailable through graphql.

### Steps to reproduce

Add an image to a post, and notice it is available in Graphql.
Remove the image from all posts, and note that it is no longer available to query.

### WPGraphQL Version

1.12.0

### WordPress Version

6.0.3

### PHP Version

7.4.1

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
If I'm not mistaken, that's standard WP behavior, where Attachment post types inherit the post status of their attached post (unless set explicitly), and WPGraphQL only exposes _published_ items to unauthenticated users.

You can change this behavior with the `graphql_restricted_data_cap` filter... but first, can you confirm that the query in GraphiQL works if you run it as an authenticated user?

**Comment by MohammadSabbagh** [comment]
I run on the same problem.
It seems not possible to get post attachments without using it in post content.

anyway as workaround I added gallery shortcode as following

[gallery link="none"] 

then using react to remove its content for ex.

`parse(page.content.slice(0,page.content.indexOf('<div')))`

**Comment by justlevine** [comment]
> All media added through the post content shows correctly, but media added through ACF does not. If I hook into 'acf/save_post' and change the post parent to the current post, it works until I clear the Gatsby cache. At that point, it continues to show in WP GQL, but not in Gatsby GQL.

Sounds like an issue with Gatsby not recognizing ACF data, and probably not something we can 'fix' in WPGraphQL core.

@TylerBarnes waddya think?

**Comment by TylerBarnes** [comment]
Yeah sounds like an issue with source-wordpress. @gbe-trackunit or @MohammadSabbagh can you open an issue on the Gatsby repo and include specific steps on how to reproduce? (and/or include a reproduction repo)

thanks :)
