### ISSUE TITLE
SEO field not showing in GraphQL IDE with RankMath Plugin.

### ISSUE THREAD

**Issue by aryanrajput** [wp-graphql/wp-graphql#2596]
### Description

I have installed
WordPress version =>  6.0.3
WP GraphQL version =>  1.12.0
Rank Math SEO PRO =>  3.0.22
and unable to get seo data in GraphQL IDE.

![image](https://user-images.githubusercontent.com/26869121/199107099-ebfc971b-9065-4030-887d-08d354ed0f96.png)
![image](https://user-images.githubusercontent.com/26869121/199107206-10dd4564-3414-45fe-9463-94d5b867cbf9.png)
![image](https://user-images.githubusercontent.com/26869121/199107248-58f63620-7665-4ec3-8292-c3523a369701.png)
![image](https://user-images.githubusercontent.com/26869121/199107292-960aad51-3f61-408f-a141-e12c09444a32.png)

### Steps to reproduce

SEO head field not showing in GraphQL IDE

### WPGraphQL Version

1.12.0

### WordPress Version

6.0.3

### PHP Version

7.4.30

### Additional enviornment details

"gatsby": "^4.19.2",
"gatsby-source-wordpress": "^6.24.0",

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [ ] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Hey @aryanrajput ,
Most 3rd party plugins don't usually include WPGraphQL support automatically.

For Rank Math, check out https://github.com/AxeWP/wp-graphql-rank-math

**Comment by aryanrajput** [comment]
Hi @justlevine thank you for that.
now I'm able to get seo field on WordPress GraphQL IDE.

But after installing wp-graphql-rank-math gatsby develop giving another error.

![image](https://user-images.githubusercontent.com/26869121/199180968-82400fdb-1f6b-4e05-8948-549a2889b5a8.png)

**Comment by justlevine** [comment]
> now I'm able to get seo field on WordPress GraphQL IDE.

Glad to hear, I'm going to mark this issue as resolved as resolved 🚀

> But after installing wp-graphql-rank-math gatsby develop giving another error.

Sorry to hear you're having trouble. To diagnose and resolve we need significantly more information than what's been provided so far. My gut tells me [it's not related to Rank Math](https://www.reddit.com/r/gatsbyjs/comments/m8ncbj/need_help_with_gatsby_and_wp/).

To get you started: 
1. Do what the error message says and lower `GATSBY_CONCURRENT_DOWNLOAD` to `1`, see if it works, and than slowly raise that number until the error comes back.

2. Disable WPGraphQL for Rank Math, and see whether the error persists. 
   - **If the error goes away**, then open up a bug report _in the `wp-graphql-rank-math` repo_, so it can be addressed quickly and efficiently. 
   - **If the error still shows up**, please open a new bug report in **this** repo, and make sure to include all the requested information, in particular your version numbers for both your WP plugins (with all other 3rd party-plugins that don't affect the error message disabled) and your frontend deps.
