### ISSUE TITLE
Plugin doesn´t activate after installation

### ISSUE THREAD

**Issue by paulonova** [wp-graphql/wp-graphql#2597]
### Description

I'm having trouble installing the WP GraphQl plugin.
I'm using Wordpress 6.1 and I've disabled all other plugins to make sure they're not conflicting, but the plugin still refuses to activate and shows this error message:

*******************************************************************************************************************
Plugin could not be activated because it triggered a fatal error.

Fatal error: Uncaught Error: Call to undefined method Appsero\Insights::add_plugin_data() in /home/st01apptechlovese/st01.app.techlove.se/wp-content/plugins/wp-graphql/wp-graphql.php:78 Stack trace: #0 /home/st01apptechlovese/st01.app.techlove.se/wp-content/plugins/wp-graphql/wp-graphql.php(81): graphql_init_appsero_telemetry() #1 /home/st01apptechlovese/st01.app.techlove.se/wp-admin/includes/plugin.php(2314): include_once('...') #2 /home/st01apptechlovese/st01.app.techlove.se/wp-admin/plugins.php(192): plugin_sandbox_scrape() #3 {main} thrown in /home/st01apptechlovese/st01.app.techlove.se/wp-content/plugins/wp-graphql/wp-graphql.php on line 78
*******************************************************************************************************************

### Steps to reproduce

1. Select the plugin from admin page i Wordpress 
2. In Plugins i found the plugin by name WP GraphQl and installed it.
3. After installation I tried to ACTIVATE the plugin
4. And then the error message above apears..

### Additional context

Plugins Installed: 
Advanced Custom Field Pro
All-In_one WP Migration
Custom Post Type UI
Duplicate Page
Oh My SVG
Rest API Feature Image
WP Maximum Upload File Size
WP-Rest-API V2 Menus
Yoast

### WPGraphQL Version

1.12.0

### WordPress Version

6.1

### PHP Version

8

### Additional enviornment details

![Skärmavbild 2022-11-01 kl  16 54 22](https://user-images.githubusercontent.com/5539347/199502996-78a3928e-e2b9-4c0d-8bac-12042a12cd12.png)

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [X] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
I just tried to replicate on a _clean_ install (PHP 8, WP 6.1) using a TasteWP spinup, and it's worked fine.

I'm betting this is due to a plugin conflict with one of the above _installed_ plugins, since `Appsero\Insights::add_plugin_data()` [was only added in v1.2.1](https://github.com/Appsero/client/pull/16).

Possible solutions as I see them are to either:

1. use [Strauss]https://github.com/BrianHenryIE/strauss) or something similar to namespace the Appsero dependency so we're always using our version.
2. Shim `add_plugin_data()`. 
3. Check if `add_plugin_data()` is accessible before attempting to call it.

Cant do a full eval of the pros/cons of each since I don't know what/how the insights are used internally.

@jasonbahl ?

**Comment by jasonbahl** [comment]
@paulonova what are the steps you took to install WPGraphQL? Did you install it from the WordPress.org repository or did you download it or clone it from Github? Or did you install via Composer?

My hunch is that you installed a non-built version of the plugin, and would need to run `composer install` or `composer install --no-dev` to install dependencies.

Can you confirm the steps you took to install the plugin?

**Comment by jasonbahl** [comment]
Ah, my bad. you stated you installed from the WordPress admin panel? 🤔

**Comment by jasonbahl** [comment]
@paulonova if you apply the changes I made in this PR (https://github.com/wp-graphql/wp-graphql/pull/2599), does the error go away?

**Comment by paulonova** [comment]
Hi everyone! 
I wanna thank you gays for help, I solved the problem.. 
I uninstalled all plugins and installed the WP GraphQl first and then activation worked, then I re installed all plugins again and 
got no conflicts att all. Now it is working fine! 

Thank you  Jason and Justlevine! 

Best regards

Paulo
