### ISSUE TITLE
Querying page by URI stop working after updating page slug

### ISSUE THREAD

**Issue by freyja-anh** [wp-graphql/wp-graphql#2601]
### Description

When I update the slug for a page, then change it back to the previous slug, querying the page with URI using the old slug stop working and return null, though page uri remains the same. Querying by DATABASE_ID works normally. However in getStaticProps I don't have DATABASE_ID context so this is a trouble.

### Steps to reproduce

1. Create a page with slug 'page-1'.
2. These two queries return the same result
```
query Page1ById {
  page(id: "<Page_1_ID>", idType: DATABASE_ID) {
    title
  }
}
query Page1ByUri {
  page(id: "<Page_1_URI>", idType: URI) {
    title
  }
}
```

3. Change slug from 'page-1' to 'page-2', save. Then change back to 'page-1', save.
4. This query now returns null
```
query Page1ByUri {
  page(id: "<Page_1_URI>", idType: URI) {
    title
  }
}
```

### Additional context

Also in use: ACF Pro and Polylang Pro.

### WPGraphQL Version

1.8.7

### WordPress Version

6.0.2

### PHP Version

8.0

### Additional enviornment details

- NextJS
- WPgraphQL Polylang
- WPgraphQL ACF

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [ ] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by freyja-anh** [comment]
And same issue also happen when I change page language from one language to the other, save, then switch it back and save. URI is also changed and changed back and stop working.

**Comment by justlevine** [comment]
Hey @freyja-anh 

- I see you're using v1.8.7 of WPGraphQL. Does the error persist if you use the latest version of the plugin (v1.12.0 as of writing).

- You also note that you have extensions for ACF and Polylang. Can you please disable _all plugins besides for WPGraphQL core_ and check if the problem persists?

If it goes away, please enable the plugins one by one and let us know which plugin causes the issue to return.

**Comment by justlevine** [comment]
Hey @freyja-anh , 
We havnt heard back from you, so I'm going to assume that either the issue was fixed in later versions of the plugin or you were able to pinpoint and resolve the specific conflict.

If you still have the issue, please let us know (with the requested information), and we'll open this issue back up to investigate.
