### ISSUE TITLE
Querying page asPreview: true returns null with using database_id

### ISSUE THREAD

**Issue by sirichards** [wp-graphql/wp-graphql#2602]
### Description

Sending a post request to the graphql endpoint for a page like so using asPreview: true

Query
```
  query page($pageId: ID!) {
    page(idType: DATABASE_ID, id: $pageId, asPreview: true) {
        title
        content
    }
  }
```

Variables
```
{
    "pageId": 2
}
```

Return:
```
[
    "data": {
        "page": null
    },
]
```

### Steps to reproduce

Fresh install of WP and wp-graphql, query the endpoint using postman or similar.
Create a new page, make changes hit preview etc always comes back as null.

### WPGraphQL Version

1.12.0

### WordPress Version

6.1.0

### PHP Version

8.1.10

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by finleyjchen** [comment]
Also running into a similar issue. Did you find a solution here @sirichards?

**Comment by finleyjchen** [comment]
Nevermind, I see the issue exists here: #1673
