### ISSUE TITLE
Custom blocks query

### ISSUE THREAD

**Issue by ps221494** [wp-graphql/wp-graphql#2607]
### What problem does this address?

I wanted to make a custom block in wordpress using ACF to reach from a next.js application, but i cannot make a 'block' query.

### What is your proposed solution?

Add a block query or option

### What alternatives have you considered?

just make a ACF page instead of a block, but my 'boss' does not want that

**Comment by justlevine** [comment]
Hey @ps221494 

The [wp-graphql-content-blocks extension](https://gihub.com/wpengine/wp-graphql-content-blocks), should provide you a way to query your blocks, with forthcoming work to make ACF Blocks supported as well.

Regarding core support, I'm going to mark this as a duplicate of #1764 , so feel free to track progress over there.
