### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by wirsing** [wp-graphql/wp-graphql#261]
Thanks for working on this great Plugin! Could you confirm pagination is working as expected?
This query returns `false` for `hasNextPage` even if there are more then 10 posts. If I add a (first:10) it is working as expected:

```
{
  posts {
    edges {   
      node {
        id
      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      endCursor
    }
  }
}
```

I was also wondering about totalCount

```
{
  posts {
    totalCount
    edges {   
      node {
        id
      }
    }
  }
}
```

This query returns an error for totalCount, it doesn't seem to be available. Is there a way to return the total counts in a connection?

**Comment by jasonbahl** [comment]
@wirsing hey, so per the Relay spec (https://facebook.github.io/relay/graphql/connections.htm#sec-undefined.PageInfo.Fields) `hasPreviousPage` and `hasNextPage` should only return `true` for paginated requests, and since you're not sending a paginated request they return false. 

Try sending your request with pagination args, such as `first`, `last`, `after`, `before`. 

For example: 

```
{
  posts( first: 10, after: null ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    edges {
      cursor
      node {
        id
        title
        date
      }
    }
  }
}
```

====

**totalCount for connections**

 I'm not opposed to adding a `totalCount` field to the connections, but it doesn't exist currently because the queries that are used behind the scenes don't do a total count for performance reasons, so the total count data isn't available to return. 

If I were to implement this, I'd do it by looking ahead at the requested fields to see if `totalCount` were asked for, and if so modify the SQL query to select a count with the query so that the count could be returned with the query. 

I don't think this will be on the official roadmap in the near future. . .but If you do have time to work on the feature, you could open a PR or better yet, I suggest a "feature plugin" approach, where you make a `wp-graphql-connection-total-count` plugin, or something to that tune that provides the appropriate filters to the Schema and applies any necessary filters, etc to have the SQL calculations run and return the count to the resolvers, then folks can use that feature plugin and I can further evaluate if it makes sense to merge to core.

**Comment by wirsing** [comment]
Hey @jasonbahl Thanks for getting back on this! I am just confused on why I always only get the first 10 items of a collection when sending a request without including `first`. So if I get only 10 items of a collection but the collection is >10 I have no way of knowing how large the actual collection is. That's why I also would strongly advocate for `totalCount`. I'll definitely submit a PR if I find the time to work on this, pretty slammed right now.

**Comment by jasonbahl** [comment]
@wirsing hey, so if you don't pass in any arguments for how many items you're requesting, the default is 10 (conceptually similar to how WP_Query works on it's own without passing a posts_per_page param). . .but you can set the default to be whatever you want via filters. 

For example, if you want to set a default `posts_per_page`, for when `first` or `last` are NOT sent through in the `$args` you could do something to this tune (untested, but _should_ work): 

```
add_filter( 'graphql_post_object_connection_query_args', function( $query_args, $source, $args, $context, $info ) {
    
    // Make sure we don't override the first/last input which sets the amount to request
    if ( ! isset( $args['first'] ) && ! isset( $args['last'] ) ) {
        $query_args['posts_per_page'] = 500;
    }

    return $query_args;

}, 10, 5 );
```

Also note that the max is set to 100, so if you queried for: 

```
{
  posts( first: 500 ) {
     edges {
       node {
          id
          title
       }
     }
  }
}
```

You would only have 100 returned. The max is also filterable though, so you can change the max to whatever you feel is responsible and "safe" for your servers to execute and respond with. 

Here's an example of filtering the max amount for certain users with certain privileges, but leaving it default for everyone else: 

```
add_filter( 'graphql_connection_max_query_amount', function( $amount, $source, $args, $context, $info  ) {

    if ( current_user_can( 'manage_options' ) ) {
         $amount = 1000;
    }

    return $amount;

}, 10, 5 );
```

**Comment by vana-dev** [comment]
This is not working anymore, graphql now returns default 100 posts.

**Comment by RangerCoder99** [comment]
Is there still not any way to get the total pages for pagination? Like a lot of people want that number style links...

**Comment by jasonbahl** [comment]
@RangerCoder99 I've written about pagination with WPGraphQL here, including reasons for why total counts has been excluded by default: https://www.wpgraphql.com/2020/03/26/forward-and-backward-pagination-with-wpgraphql/

**Comment by znwhite** [comment]
I wrote a blog post summarizing how to fix this issue here: https://www.devtwins.com/blog/wpgraphql-increase-post-limit

It simply takes @jasonbahl 's solution and removes the `if` statement, but I figured it could be helpful to give a thorough overview.

**Comment by jasonbahl** [comment]
@znwhite good stuff! Thanks for sharing. 

Maybe include a disclaimer that fetching too many things in one request can cause slow downs for the client and possibly server performance issues as well. 

There's no magic number to what the right amount of posts to return for optimal performance, but the more data the server is processing and the more the client is downloading, the  worse the performance tends to be. Sometimes you can get better performance from more, but smaller, requests.

**Comment by znwhite** [comment]
@jasonbahl Awesome, thanks for the feedback! This is a great point, I'll add this to the post 👍

**Comment by travisanderson** [comment]
This is so strange, and so is the solution to work around the plugin.  Maybe a productive suggestion would be in the plugin, to add a small settings page, and have an input field where the person can change the limit there, without having to work around the plugin?  Also, error reporting would tell you "only returning the first 100 of n records...you can raise the limit in settings"...and if you are really concerned with letting people do this, include the obligatory warning about performance, etc....

I would argue in 2022, lots of people are starting to use this type of thing for static generated sites, where they only need to run the graphQL query at build time, anyways.  So constantly bogging down the server with queries is not really a concern, right?

**Comment by justlevine** [comment]
@travisanderson the performance issue isnt about when the query is made (putting aside that lengthy build times are also not great) but rather the database performance of trying to get all that data in one request. It's really easy to crash a server if you not careful about how you design your query.

IMO pagination should be encouraged, and I think a soft limit of 100 is pretty reasonable. It's fairly simple to add a WordPress filter (esp considering plugin users are devs), and the pattern encourages users to only raise limits on specific types and not schema-wide.

It's that latter reason why I'm not sure exposing the number in the backend settings is a good idea, but maybe it's a decent compromise. If so, I encourage you to open a new issue with the feature request.
