### ISSUE TITLE
PHP v7.4.x Compatibility 

### ISSUE THREAD

**Issue by robindevitt** [wp-graphql/wp-graphql#2610]
### Description

When running [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) against `PHP7.4` the plugin generates a handful of warnings and 2 errors.

```php
FILE: content/plugins/wp-graphql/vendor/appsero/client/src/Client.php
-------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
-------------------------------------------------------------------------------------------------------------------------------------------------
 228 | WARNING | Method name "Client::__trans" is discouraged; PHP has reserved all method names with a double underscore prefix for future use.
-------------------------------------------------------------------------------------------------------------------------------------------------


FILE: content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Utils/Utils.php
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 328 | WARNING | Since PHP 7.0, functions inspecting arguments, like func_get_args(), no longer report the original value as passed to a parameter, but will instead provide the current value. The parameter "$test" was used, and possibly changed (by reference), on line 326.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Language/Visitor.php
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 4 WARNINGS AFFECTING 4 LINES
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 414 | WARNING | Since PHP 7.0, functions inspecting arguments, like func_get_args(), no longer report the original value as passed to a parameter, but will instead provide the current value. The parameter "$node" was used, and possibly changed (by reference), on line 406.
 439 | WARNING | Since PHP 7.0, functions inspecting arguments, like func_get_args(), no longer report the original value as passed to a parameter, but will instead provide the current value. The parameter "$node" was used, and possibly changed (by reference), on line 434.
 470 | WARNING | Since PHP 7.0, functions inspecting arguments, like func_get_args(), no longer report the original value as passed to a parameter, but will instead provide the current value. The parameter "$node" was used, and possibly changed (by reference), on line 466.
 486 | WARNING | Since PHP 7.0, functions inspecting arguments, like func_get_args(), no longer report the original value as passed to a parameter, but will instead provide the current value. The parameter "$node" was used, and possibly changed (by reference), on line 484.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: content/plugins/wp-graphql/src/Utils/Utils.php
-----------------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
-----------------------------------------------------------------------------------------------------------
 68 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0; Use mysqli instead
 76 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0; Use mysqli instead
-----------------------------------------------------------------------------------------------------------
```

### Steps to reproduce

1. Install PHP_CodeSniffer - https://github.com/squizlabs/PHP_CodeSniffer#installation
2. I use the following to run PHP_CodeSniffer:
```
./vendor/bin/phpcs -p --standard=PHPCompatibility \
  --runtime-set testVersion 7.4 \
  --extensions=php \
  -d memory_limit=1G \ .
```
3. Observe the errors identified above.

### WPGraphQL Version

1.8.2

### WordPress Version

5.8.5

### PHP Version

7.4

### Additional enviornment details

At the time of creating this I notice the plugin only has a required php version of 7.1 which is potentially why these errors have not been picked up, will the required php version be changing?

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Hey @robindevitt , 

Not sure why you're not scanning with the included PHPCS ruleset, but you dont need to / shouldn't be scanning the `\vendor` files, since they're not part of our project.

For the Utils notice, yes that's indeed because your setting the min PHP version to 7.4, when this plugin is currently required to support earlier versions. 
And yes, a future update will bump the minimum PHP versions, but only in a breaking release to ensure back-compat. You can rest assured the plugin has automated testing all the way up to PHP 8.1 though.

**Comment by jasonbahl** [comment]
Thanks for opening this issue @robindevitt!

I appreciate the time and effort you put into making this plugin better for everyone! 🙌🏻 

Based on @justlevine response, I'm going to close this issue. 

Looking forward to seeing what you create with WPGraphQL!

**Comment by robindevitt** [comment]
Thanks @justlevine & @jasonbahl 

Noted around the vendor files.

I note the initial reported PHP compatibility:
```php
FILE: content/plugins/wp-graphql/src/Utils/Utils.php
-----------------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
-----------------------------------------------------------------------------------------------------------
 68 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0; Use mysqli instead
 76 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0; Use mysqli instead
-----------------------------------------------------------------------------------------------------------
```

Is still going to occur in the latest version of the plugin, 1.12.2.

Is it on the roadmap to make the plugin compatible via PHPCS?

**Comment by justlevine** [comment]
Hey @robindevitt - thanks for the quick followup!

The `mysql_to_rfc3339()` function is [allowlisted](https://github.com/WordPress/WordPress-Coding-Standards/blob/9544c7e0e78fc85405b32076ec2949c2e59854d1/WordPress/Sniffs/DB/RestrictedFunctionsSniff.php#L60) in the official WordPress Coding Standards (and therefore [our own CI](https://github.com/wp-graphql/wp-graphql/actions/workflows/wordpress-coding-standards.yml)) as it is used by the WP REST API.
@jasonbahl can confirm, but my guess is we use that method as well for parity/predictability with core WP.

I highly suggest you use the [included PHPCS ruleset](https://github.com/wp-graphql/wp-graphql/blob/develop/phpcs.xml.dist) when running your own lints of the WPGraphQL plugin, which uses [WPCS](https://github.com/WordPress/WordPress-Coding-Standards) and [Automattic's VIP](https://github.com/Automattic/VIP-Coding-Standards) rule sets, in addition to our own project coding guidelines. Easiest way is to install the projects' dev dependencies with `composer install` and then  run `composer lint`

**Comment by robindevitt** [comment]
Thanks @justlevine 🙌🏼
