### ISSUE TITLE
wp-graphql limits results to 10 when quering Menus

### ISSUE THREAD

**Issue by NaqibAli** [wp-graphql/wp-graphql#2612]
### Description

**HI**

i am using headless cms with nextjs,  when i try to query menus from mysite Wpgraphql returns only first 10.

This worked perfectly for posts but not the menus:
[(https://www.devtwins.com/blog/wpgraphql-increase-post-limit)]

Hope you will help me soon.

### Steps to reproduce

 query GET_MENUS {
          menu(id: "Primary", idType: NAME) {
            id
            databaseId
            name
            slug
            menuItems(where: { parentId: null }) {
              edges {
                node {
                  id
                  label
                  url
                  childItems {
                    nodes {
                      id
                      label
                      uri
                    }
                  }
                  parentId
                }
              }
            }
          }
        }

### WPGraphQL Version

1.12.2

### WordPress Version

6.1

### PHP Version

7.4

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
@NaqibAli the default value is `10`. You need to use the `first` argument to fetch more items, like so: 

```graphql
query GET_MENUS {
  menu(id: "Primary", idType: NAME) {
    id
    databaseId
    name
    slug
    menuItems( first: 100, where: {parentId: null}) {
      edges {
        node {
          id
          label
          url
          childItems {
            nodes {
              id
              label
              uri
            }
          }
          parentId
        }
      }
    }
  }
}
```

**Comment by jasonbahl** [comment]
If you need more than 100 items, you might need to do a paginated request. 

You can learn more about pagination here: https://www.wpgraphql.com/2020/03/26/forward-and-backward-pagination-with-wpgraphql
