### ISSUE TITLE
Pagination is broken for some node types

### ISSUE THREAD

**Issue by TylerBarnes** [wp-graphql/wp-graphql#2618]
### Description

While paginating the same nodes are sometimes returned multiple times. I couldn't repro this when setting first to 100, just when setting it to a lower number. Setting first to different values causes it to return more or less duplicate nodes. first 10 returns 3 duplicates, first 20 14 duplicates, first 30 7 duplicates. Any first value above the total number of nodes doesn't cause the problem (naturally 😛)

### Steps to reproduce

Clone this repo https://github.com/TylerBarnes/wpgraphql-pagination-repro

Run `yarn && yarn find-dupes` to see a list of duplicate ID's for the ExtensionNode type on WPGraphQL.com

https://github.com/wp-graphql/wp-graphql/issues/2570 might be related, not sure.

### WPGraphQL Version

wpgraphql.com

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [ ] Yes
- [X] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by TylerBarnes** [comment]
I pushed another commit to that repo showing it happens for ExtensionPlugin and Document nodes on wpgraphql.com

**Comment by TylerBarnes** [comment]
Seems like this is probably an issue with custom re-order plugin

**Comment by jasonbahl** [comment]
see: https://github.com/wp-graphql/wp-graphql/issues/2300#issuecomment-1111245585

**Comment by jasonbahl** [comment]
Ya, from what I can tell this is related to https://github.com/wp-graphql/wp-graphql/issues/2300#issuecomment-1111245585. 

I've put that snippet in a GIST here: https://gist.github.com/jasonbahl/c23095d0fb4f25fd9023d5d69ceea6ce
