### ISSUE TITLE
403 Forbidden when accessing the graphql server

### ISSUE THREAD

**Issue by towfiqi** [wp-graphql/wp-graphql#262]
Hi,

I am pretty new to all this. My wordpress site is hosted locally : http://localhost/wpd/graphql

And I am trying to accesss the graphql server with apollo like this from a react project that is located in another folder:

`const networkInterface = createNetworkInterface({
    uri: 'http://localhost/wpd/graphql'
});`

I am getting a 403 forbidden error. Do  I have to place the folder inside the wordpress installation? 

It works fine with the Graphiql chrome client without any issues.

Thanks

**Comment by jasonbahl** [comment]
@towfiqi Hey, if you are seeing 403 but the queries are still executing and returning data, then things are working as expected. The 403 header is returned by default when GraphQL requests are not authenticated. The request will still resolve and return any results for public data, but the 403 indicates to the client that the request is not authenticated. 

If you send Authenticated requests the status code will be 200.

**Comment by jasonbahl** [comment]
@towfiqi are you getting any 500 errors as well? If so, make sure you're updated to the latest version of master as there was a bug fixed that was causing issues with the Apollo "pre-flight" OPTIONS request it makes that WPGraphQL wasn't playing nice with.

**Comment by towfiqi** [comment]
@jasonbahl  Thanks for getting back to me this quick. 

> but the 403 indicates to the client that the request is not authenticated.

Can you kindly point any to any guides or tuts that explains how to authenticate the request? Do I have do it with Apollo?

**Comment by towfiqi** [comment]
I have taken a few steps:

1. Installed oAuth1.0 server plugin.
2. created a new Application from the plugin's interface and received a Client Key & Client Secret.
3. Used postman to post to http://localhost/wpd/oauth1/request with the client key & Secret to generate the auth token and token secret.
4. generated user token by visiting http://localhost/wpd/oauth1/authorize?oauth_token=<token_here>&oauth_token_secret=<secret_here>
5. Copid the user token and pasted it in my apollo's networkInterface middleware like so:

```
networkInterface.use([{
    applyMiddleware(req, next) {
      if (!req.options.headers) {
        req.options.headers = {};  // Create the header object if needed.
      }
      // get the authentication token from local storage if it exists
      const token = 'u51sAc8x0w2Dq0BEJnTdG3YD';
      req.options.headers.authorization = token ? `Bearer ${token}` : null;
      next();
    }
  }]);
```

**But Still getting 403 Forbidden Error.**

**Comment by jasonbahl** [comment]
FWIW, Authentication is _not_ a requirement to interact with WPGraphQL. . .depending on your needs and what you're building, you may not need authentication at all.

That said, I believe oAuth requests require additional dynamic details in the token such as a timestamp and a nonce. . .so I'm not sure that request will work. I can't offer support for oAuth though, so make sure you check out their docs, etc.

What I would suggest to **get started** with WPGraphQL and Authentication would be to use the WP API Basic Auth plugin (https://github.com/WP-API/Basic-Auth), and pass `req.options.headers.authorization = 'Basic ' + $base64encodedAuth;` where `$base64encodedAuth` is a base64 encoded string made up of `username:password`.

Let me know if you get it working with Basic Auth. Thanks!

**Comment by towfiqi** [comment]
Ok. Thanks for your suggestion. It worked. :) I will have to look into the oAuth authentication soon, since the app lets users save posts.

**Comment by jasonbahl** [comment]
@towfiqi I'm going to close this as 403 is expected behavior and you've confirmed that Auth works with Basic Auth, so at this point you should be able to refer to docs for any of the WordPress Auth mechanisms. FWIW, I have a JWT Auth plugin for GraphQL that I'm hoping to work on more in the coming weeks.

**Comment by towfiqi** [comment]
Jason, I am trying to make authenticated graphql request and pulling my hair out. Stuck for a 4 days and cannot make sense on how to make an authenticated request with oauth1 token. Most graphql authentication tutorial I see online is using authenticating in graphql or with graphql-express. I have a server with express which handles the client app routes with passport oauth1 middleware. The access token are being created fine, but I am not sure how I can implement the whole thin apollo client. The apollo client doc doesnt have much info on this too.

So, Is it possible to add a oauth authentication (not cookie based) in your [WordFlix ](https://github.com/wp-graphql/wordflix-single-page-app/)app and make simple  POST request so we can understand how the whole process works. It would be great if you could make the WordFlix app a CRUD app.

Many Thanks

**Comment by jasonbahl** [comment]
Good news! I pushed an update to `wp-graphql-jwt-auth` Yesterday so you can now authenticate via a `login` mutation and ask for a token, then use that token in your Apollo headers for subsequent requests. 

I need to clean up some code and write unit tests and documentation, but it’s working pretty well. 

Check it out: https://github.com/wp-graphql/wp-graphql-jwt-authentication 

I’ll try and write up some quick docs as well

**Comment by towfiqi** [comment]
Many Many thanks :joy: :joy: 

I just tied to install the plugin and received this error upon activation:

```

Warning: require_once(C:\xampp2\htdocs\wpd\wp-content\plugins\wp-graphql-jwt-authentication-master/vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp2\htdocs\wpd\wp-content\plugins\wp-graphql-jwt-authentication-master\wp-graphql-jwt-authentication.php on line 132

Call Stack:
    0.0010     278536   1. {main}() C:\xampp2\htdocs\wpd\wp-admin\plugins.php:0
    0.0010     322120   2. require_once('C:\xampp2\htdocs\wpd\wp-admin\admin.php') C:\xampp2\htdocs\wpd\wp-admin\plugins.php:10
    0.0020     334864   3. require_once('C:\xampp2\htdocs\wpd\wp-load.php') C:\xampp2\htdocs\wpd\wp-admin\admin.php:31
    0.0020     343992   4. require_once('C:\xampp2\htdocs\wpd\wp-config.php') C:\xampp2\htdocs\wpd\wp-load.php:37
    0.0030     441112   5. require_once('C:\xampp2\htdocs\wpd\wp-settings.php') C:\xampp2\htdocs\wpd\wp-config.php:96
    0.2540   19520776   6. do_action() C:\xampp2\htdocs\wpd\wp-settings.php:432
    0.2540   19521200   7. WP_Hook->do_action() C:\xampp2\htdocs\wpd\wp-includes\plugin.php:453
    0.2540   19521248   8. WP_Hook->apply_filters() C:\xampp2\htdocs\wpd\wp-includes\class-wp-hook.php:323
    0.2570   19687224   9. call_user_func_array() C:\xampp2\htdocs\wpd\wp-includes\class-wp-hook.php:298
    0.2570   19687424  10. graphql_init() C:\xampp2\htdocs\wpd\wp-includes\class-wp-hook.php:298
    0.2570   19687560  11. WPGraphQL::instance() C:\xampp2\htdocs\wpd\wp-content\plugins\wp-graphql-develop\wp-graphql.php:564
    0.2720   20064608  12. do_action() C:\xampp2\htdocs\wpd\wp-content\plugins\wp-graphql-develop\wp-graphql.php:110
    0.2720   20064984  13. WP_Hook->do_action() C:\xampp2\htdocs\wpd\wp-includes\plugin.php:453
    0.2720   20065032  14. WP_Hook->apply_filters() C:\xampp2\htdocs\wpd\wp-includes\class-wp-hook.php:323
    0.2720   20065536  15. call_user_func_array() C:\xampp2\htdocs\wpd\wp-includes\class-wp-hook.php:298
    0.2720   20065736  16. WPGraphQL\graphql_jwt_authentication_init() C:\xampp2\htdocs\wpd\wp-includes\class-wp-hook.php:298
    0.2720   20065832  17. WPGraphQL\JWT_Authentication::instance() C:\xampp2\htdocs\wpd\wp-content\plugins\wp-graphql-jwt-authentication-master\wp-graphql-jwt-authentication.php:141
    0.2720   20066232  18. WPGraphQL\JWT_Authentication->includes() C:\xampp2\htdocs\wpd\wp-content\plugins\wp-graphql-jwt-authentication-master\wp-graphql-jwt-authentication.php:46


Fatal error: require_once(): Failed opening required 'C:\xampp2\htdocs\wpd\wp-content\plugins\wp-graphql-jwt-authentication-master/vendor/autoload.php' (include_path='.;C:\xampp2\php\PEAR') in C:\xampp2\htdocs\wpd\wp-content\plugins\wp-graphql-jwt-authentication-master\wp-graphql-jwt-authentication.php on line 132

Call Stack:
    0.0010     278536   1. {main}() C:\xampp2\htdocs\wpd\wp-admin\plugins.php:0
    0.0010     322120   2. require_once('C:\xampp2\htdocs\wpd\wp-admin\admin.php') C:\xampp2\htdocs\wpd\wp-admin\plugins.php:10
    0.0020     334864   3. require_once('C:\xampp2\htdocs\wpd\wp-load.php') C:\xampp2\htdocs\wpd\wp-admin\admin.php:31
    0.0020     343992   4. require_once('C:\xampp2\htdocs\wpd\wp-config.php') C:\xampp2\htdocs\wpd\wp-load.php:37
    0.0030     441112   5. require_once('C:\xampp2\htdocs\wpd\wp-settings.php') C:\xampp2\htdocs\wpd\wp-config.php:96
    0.2540   19520776   6. do_action() C:\xampp2\htdocs\wpd\wp-settings.php:432
    0.2540   19521200   7. WP_Hook->do_action() C:\xampp2\htdocs\wpd\wp-includes\plugin.php:453
    0.2540   19521248   8. WP_Hook->apply_filters() C:\xampp2\htdocs\wpd\wp-includes\class-wp-hook.php:323
    0.2570   19687224   9. call_user_func_array() C:\xampp2\htdocs\wpd\wp-includes\class-wp-hook.php:298
    0.2570   19687424  10. graphql_init() C:\xampp2\htdocs\wpd\wp-includes\class-wp-hook.php:298
    0.2570   19687560  11. WPGraphQL::instance() C:\xampp2\htdocs\wpd\wp-content\plugins\wp-graphql-develop\wp-graphql.php:564
    0.2720   20064608  12. do_action() C:\xampp2\htdocs\wpd\wp-content\plugins\wp-graphql-develop\wp-graphql.php:110
    0.2720   20064984  13. WP_Hook->do_action() C:\xampp2\htdocs\wpd\wp-includes\plugin.php:453
    0.2720   20065032  14. WP_Hook->apply_filters() C:\xampp2\htdocs\wpd\wp-includes\class-wp-hook.php:323
    0.2720   20065536  15. call_user_func_array() C:\xampp2\htdocs\wpd\wp-includes\class-wp-hook.php:298
    0.2720   20065736  16. WPGraphQL\graphql_jwt_authentication_init() C:\xampp2\htdocs\wpd\wp-includes\class-wp-hook.php:298
    0.2720   20065832  17. WPGraphQL\JWT_Authentication::instance() C:\xampp2\htdocs\wpd\wp-content\plugins\wp-graphql-jwt-authentication-master\wp-graphql-jwt-authentication.php:141
    0.2720   20066232  18. WPGraphQL\JWT_Authentication->includes() C:\xampp2\htdocs\wpd\wp-content\plugins\wp-graphql-jwt-authentication-master\wp-graphql-jwt-authentication.php:46

```

**Comment by jasonbahl** [comment]
@towfiqi ok let me check. I must not have versioned the vendor files. 

Try to run `composer install —no-dev` from the plugin directory to install the dependencies. 

I’ll add those files to the github repo as well though

**Comment by jasonbahl** [comment]
@towfiqi any luck with composer install? Or still having issues?

**Comment by towfiqi** [comment]
Thanks. working now. :smile:

**Comment by jasonbahl** [comment]
@towfiqi I updated the `wp-graphql-jwt-authentication` plugin to include the necessary vendor dependencies in the repo so you don't need to install via composer anymore.

**Comment by towfiqi** [comment]
Great :+1: 

There is another issue though, activating the plugin breaks the graphql server with error:

`Notice: Trying to get property of non-object in C:\xampp2\htdocs\wpd\wp-content\plugins\wp-graphql-jwt-authentication-master\src\Config.php on line 149`

**Comment by towfiqi** [comment]
@jasonbahl Did you have a chance to look into this issue?

**Comment by jasonbahl** [comment]
Not yet. Can you just make sure your updates with the most recent master?

**Comment by jasonbahl** [comment]
(Most recent master of the auth plugin)

**Comment by towfiqi** [comment]
Just did. Same issue.

**Comment by jasonbahl** [comment]
Ok. I’ll check tomorrow. Possibly didn’t push up the latest code like I thought I did 🤔

**Comment by jasonbahl** [comment]
@towfiqi I created an issue over on the JWT Auth plugin about this: https://github.com/wp-graphql/wp-graphql-jwt-authentication/issues/2
