### ISSUE TITLE
regression: Connection classes were moved, causing fatal errors 

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#2628]
### Description

v1.13.0 moved some classes from the `WPGraphQL\Connection` namespace to the `WPGraphQL\Type\Connection` namespace, and plugins (WPGraphQL for WooCommerce, for example) that were referencing the previous namespace now don't work and cause a fatal. 

### Steps to reproduce

1. Activate WPGraphQL v1.13.0
2. Activate WPGraphQL for WooCommerce v0.11.2
3. Witness the mayhem.

### Additional context

Screenshot below shared by a user in Slack. 

![Screen Shot 2022-11-28 at 3 28 10 PM](https://user-images.githubusercontent.com/1260765/204431867-8ba2b327-f790-49bd-a59b-67f8961ef61f.jpg)

### WPGraphQL Version

1.13.0

### WordPress Version

6.1

### PHP Version

8.0

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [X] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Believe this is closed by #2627
