### ISSUE TITLE
Get Single Nodes (posts, terms, users, etc) by more than ID

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#263]
We should be able to fetch a single term by it's slug, possibly other attributes?

Similar to how we can now get post objects by URI, ID and Global ID.

**Comment by CodeProKid** [comment]
We should also think about what other objects we should be able to get by something other than ID. I think Users would probably be another good candidate. The way I'm thinking about it, is anything that would have it's own route in an SPA should be able to be retrieved by slug.

**Comment by jasonbahl** [comment]
@CodeProKid agreed. Which also makes me think the singular queries for nodes just need to be more flexible. Right now we have `post( id: "someId" )` or `postBy()` which has the following args: `id`, `postId`, `slug`, `uri`. . .

Ideally, I'd like one singular entry point per node, instead of post(), and postBy(), especially if we're going to add it for each type of node. . .might be best to make a breaking change and make the existing singular entries more flexible where `id` is not a required input `$arg`. 

I think it would be good to instead support a single `where` field, similar to how we do connections, and can nest other inputs on it. . .like: 

```
query getNodes ( $postWhere: postWhere!, $userWhere: userWhere ) {  
  post( where: $postWhere ) {
    id
    title
  }
  user ( where: $userWhere ) {
    id
    firstName
    lastName
  }
}
```

```
$variables = {
  'postWhere': {
    id: null,
    slug: "some-post",
    uri: null,
    postId: null
  },
  'userWhere': {
      id: null,
      username: null,
      email: "email@something.com"
  }
};
```

This shape brings some consistency to the shape of the `args` for singular nodes and connections now, and it gives more flexibility to using variables individually or in combination to narrow the resulting node, and more flexibility to plugins to extend the shape with their own fields. 

I imagine all sorts of ways folks would want to get a users (or other nodes) by some unique value, like `user(where: {wooCommerceOrderNumber: 123} )` or something to that tune.  

Changing the shape of the root singular entries will be a breaking change, but I think now is the time to do it. 

Also, the `postBy()` field only makes semantic sense if there are no additional fields in the schema. . .for example, posts _can_ have passwords, so we will need to add a `password` input arg, and `postBy( password: "123", slug: "some-slug")` isn't as nice (to me) as `post( where: { slug: "some-slug" }, password: "123456" )`

**Comment by chrisfullman** [comment]
Definitely looking forward to this one! I agree that it feels like a good time to introduce this breaking change ahead of 1.0.

**Comment by matiasalvarez87** [comment]
Hi, I wonder if you're still working on this feature?

I'm implementing a SPA of my Wordpress website using WPGraphQL and React. When I go to the blog page I'm trying to filter posts by categories. So I can have the same functionality as in Wordpress. 

I haven't found an equivalent to `postBy` (I thought it would be something like `categoryBy`), so I ended up using the ID field to filter posts, which works ok but it makes the URL not so friendly :) 

This is what I'm currently doing:
`/blog/category/mobile?id=Y2F0ZWdvcnk6Mw%3D%3D`

This is what I'd like to have.
`/blog/category/mobile`

This is my current query:

```
query GetPostsByCategory($categoryId: ID!) {
    category(id: $categoryId) {
      id
      name
      link
      slug
      posts {
        edges {
          node {
            id
            title
            date
            excerpt
            slug
            author {
              name
            }
            featuredImage {
              sourceUrl
            }
          }
        }
      }
    }
  }
```

Is there any alternative to do this? Or should I wait until this issue is resolved?

**Comment by jasonbahl** [comment]
@matiasalvarez87 I do plan on working on this at some point, but I don't have an ETA right now. 

For what you're trying to do, you could do this: 

```
query GetCategoryPosts($first: Int, $where: RootCategoriesTermArgs!) {
  categories(first: $first, where: $where) {
    edges {
      node {
        id
        name
        slug
        count
        posts {
          edges {
            node {
              id
              title
            }
          }
        }
      }
    }
  }
}
```

and variables

```
{
  "first": 1,
  "where": {
    "slug": "alignment"
  }
}
```

You can actually test this over at https://playground.wpgraphql.com 😄

**Comment by matiasalvarez87** [comment]
Hi @jasonbahl! I was not aware of the WPGraphQL playground, it looks really nice! 
The query you sent works. Thanks for your comments.

**Comment by CorneliusIV** [comment]
@jasonbahl I was having a similar issue, and I am using a query close to what you suggested. Which worked perfectly.  However, I am not getting any results when I query with a slug that is a child of another term.  Any ideas on what I could be missing?

**Comment by jasonbahl** [comment]
@CorneliusIV can you provide the exact query you're trying (along with variables, if any) and provide some info on the term hierarchy so I can try and replicate the scenario and see what I can find.

**Comment by CorneliusIV** [comment]
@jasonbahl Sure
I have custom Taxonomy called `Regions`
Under `Regions`, I have a parent term `North America` and a child `Canada`
So:
```
North America
-- Canada
```
Using a query very similar to what you suggested 
```
query GetRegionsSlug($first: Int, $where: RootRegionsTermArgs!) {
  regions(first: $first, where: $where) {
    edges {
      node {
        id
        name
        slug
        count
        posts {
          edges {
            node {
              id
              title
              date
              content
            }
          }
        }
      }
    }
  }
}
```
Variable
```
{
  "first": 1,
  "where": {
    "slug": "canada"
  }
}
```

Result:
```
{
  "data": {
    "regions": {
      "edges": []
    }
  }
}
```

If I try to search for North America

Variable
```
{
  "first": 1,
  "where": {
    "slug": "north-america"
  }
}
```

I get somewhat of an expected result, but `posts` returns a post that is tagged with `Canada`

```
{
  "data": {
    "regions": {
      "edges": [
        {
          "node": {
            "id": "cmVnaW9uczo1NQ==",
            "name": "North America",
            "slug": "north-america",
            "count": null,
            "posts": {
              "edges": [
                {
                  "node": {
                    "id": "cG9zdDo2NzY=",
                    "title": "Test Post",
                    "date": "2018-06-27 15:07:16",
                    "content": ""
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
```

**Comment by jasonbahl** [comment]
@CorneliusIV thanks for the info!

So, `Test Post` is tagged with `Canada` but _not_ tagged with `North America`?

**Comment by CodeProKid** [comment]
@jasonbahl this seems like something that should happen relatively soon. I know we have talked about changing the shape of the single object queries pretty radically.

Also, fwiw I think the args for getting a single object should be limited to those that are considered "unique" for the object. I know that technically a lot of them aren't, but querying by something like slug (aka guid) seems legit to me.

I think there will also have to be some performance considerations when implementing this. I'm not crazy about doing some of these queries with `WP_Query` and the like, but I'm not sure that there is a better option.

**Comment by TylerBarnes** [comment]
I think being able to get nodes by permalink/URL would be a really useful feature. For example I'm looking at pulling MediaItem nodes based on URL's found in post content or other html, but I'm not sure I can reliably use the URL to get the URI to make the query.

**Comment by TylerBarnes** [comment]
Sorry, just realized I actually mean looking MediaItem nodes up by sourceUrl which is a totally different thing than what I wrote

**Comment by jasonbahl** [comment]
The next release I'm working on (#1086) addresses this (the ability to fetch single nodes by various forms of unique identifiers).

## Posts
We're deprecating the `$postType.'By'` entry points, and have added a new `idType` field and enum for single entry points. 

This means queries such as the following will still work, but will not show in the Schema documentation, and may be formally removed from the codebase at a later date:

### Deprecated Queries

```
{
  postBy( slug: "some-slug" ) {
    id
    title
  }
}
```
```
{
  pageBy( uri: "some-uri" ) {
    id
    title
  }
}
```

These are deprecated in favor of existing single entry points for each post type, and the newly added `idType` field on those entry points.

### New Singular Post Object Queries

With the added `idType` field on the singular post object entry points, below is a series of example queries now made possible:

#### Query Single Post By Database ID

```
{
  post(id: 1739, idType: DATABASE_ID) {
    id
    title
    uri
    slug
    postId
  }
}
```

![Screen Shot 2019-12-31 at 3 34 28 PM](https://user-images.githubusercontent.com/1260765/71635570-15b55f80-2be3-11ea-8931-6e5c608cfba6.png)


#### Query Single Post by URI

```
{
  post(id: "/test-5/", idType: URI) {
    id
    title
    uri
    slug
    postId
  }
}
```

![Screen Shot 2019-12-31 at 3 35 31 PM](https://user-images.githubusercontent.com/1260765/71635600-34b3f180-2be3-11ea-80f9-c3a5f4707f41.png)


#### Query Single Post by Global Hashed ID

```
{
  post(id: "cG9zdDoxNzM5", idType: ID) {
    id
    title
    uri
    slug
    postId
  }
}
```
![Screen Shot 2019-12-31 at 3 34 06 PM](https://user-images.githubusercontent.com/1260765/71635636-70e75200-2be3-11ea-8b8d-26484b9dd8a8.png)


or without specifying `idType` as the default is the hashed ID

```
{
  post(id: "cG9zdDoxNzM5") {
    id
    title
    uri
    slug
  }
}
```

![Screen Shot 2019-12-31 at 3 33 53 PM](https://user-images.githubusercontent.com/1260765/71635630-6af17100-2be3-11ea-93a1-dbf3c3120348.png)


#### Query Post (non-hierarchical post type) by Slug

```
{
  post(id: "test-5", idType: SLUG) {
    id
    title
    uri
    slug
  }
}
```

![Screen Shot 2019-12-31 at 3 36 46 PM](https://user-images.githubusercontent.com/1260765/71635625-62009f80-2be3-11ea-8b01-ae2b9595b7d3.png)

### ContentNodeInterface
This release also introduces the `ContentNode` Interface that is implemented by all Post Object types (posts, pages, custom post types). 

This Interface allows for new types of queries to be executed that span many post types. 

#### Content Nodes Connection
Here's an example of a new query: 

```
{
  contentNodes {
    nodes {
      __typename
      id
      title
      link
      uri
      isRevision
      ... on Page {
        isFrontPage
      }
    }
  }
}
```

![Screen Shot 2019-12-31 at 3 49 33 PM](https://user-images.githubusercontent.com/1260765/71635842-66c65300-2be5-11ea-8ec0-9280ad24a1ee.png)

In the results above, we can see that a mix of Posts and Pages have been returned.

We can also pass arguments to do things like search across multiple post types: 

```
{
  contentNodes(where: {search: "test"}) {
    nodes {
      __typename
      id
      title
      link
      uri
      isRevision
      ... on Page {
        isFrontPage
      }
    }
  }
}
```

![Screen Shot 2019-12-31 at 3 53 04 PM](https://user-images.githubusercontent.com/1260765/71635870-bb69ce00-2be5-11ea-83a1-cfdb72022e59.png)

#### ContentNode single entry point

We can now also fetch single Content (post) nodes like so: 

```
{
  contentNode(id: "cG9zdDoxNzM5") {
    __typename
    id
    title
    link
    uri
    isRevision
    ... on Page {
      isFrontPage
    }
  }
}
```

![Screen Shot 2019-12-31 at 3 59 15 PM](https://user-images.githubusercontent.com/1260765/71635946-c5400100-2be6-11ea-9f01-48dbb18bb321.png)

But, we can fetch single nodes of any Post type by other unique identifiers as well, such as the URI: 

```
{
  contentNode(id: "/2019/12/05/test-5/", idType: URI) {
    __typename
    id
    title
    link
    uri
    isRevision
    ... on Page {
      isFrontPage
    }
  }
}
```
![Screen Shot 2019-12-31 at 4 02 25 PM](https://user-images.githubusercontent.com/1260765/71635963-03d5bb80-2be7-11ea-945b-3afb3e1a772d.png)


or

```
{
  contentNode(id: "/test/", idType: URI) {
    __typename
    id
    title
    link
    uri
    isRevision
    ... on Page {
      isFrontPage
    }
  }
}
```

![Screen Shot 2019-12-31 at 4 02 38 PM](https://user-images.githubusercontent.com/1260765/71635967-09cb9c80-2be7-11ea-8614-a7a312ee8207.png)

This is a SUPER powerful feature as it allows for fragments to be more easily shared and re-used across queries and components.

## Terms 

Prior to this release, there wasn't really great ways of fetching singular term objects. You could do a query for a connection of terms and limit it to the `first: 1`, and in some cases that worked fine, but it wasn't always ideal. 

This release adds better support for fetching individual Term Nodes. 



### Example Term Node Queries

Instead of only fetching by the hashed global ID, we can now fetch by other unique identifiers using the `idType` field.

#### Query Tag by Hashed Global ID

```
{
  tag(id: "cG9zdF90YWc6Mw==") {
    id
    name
    slug
    tagId
  }
}
```

![Screen Shot 2019-12-31 at 4 09 37 PM](https://user-images.githubusercontent.com/1260765/71636023-f79e2e00-2be7-11ea-951b-ba294f5c3d5e.png)

#### Query Tag by Database ID

```
{
  tag(id: 3, idType: DATABASE_ID) {
    id
    name
    slug
    tagId
  }
}
```

![Screen Shot 2019-12-31 at 4 12 14 PM](https://user-images.githubusercontent.com/1260765/71636049-56fc3e00-2be8-11ea-951f-90d37f7b6718.png)

#### Query Tag by Name

```
{
  tag(id: "Another Test", idType: NAME) {
    id
    name
    slug
    tagId
  }
}
```

![Screen Shot 2019-12-31 at 4 12 47 PM](https://user-images.githubusercontent.com/1260765/71636064-71ceb280-2be8-11ea-8340-af901a0d2d63.png)

#### Query Tag by Slug

```
{
  tag(id: "another-test", idType: SLUG) {
    id
    name
    slug
    tagId
  }
}
```

![Screen Shot 2019-12-31 at 4 14 06 PM](https://user-images.githubusercontent.com/1260765/71636074-99257f80-2be8-11ea-86ff-f20f3d583cd7.png)


#### Query Tag by URI

```
{
  tag(id: "tag/another-test/", idType: URI) {
    id
    name
    slug
    tagId
    uri
  }
}
```

![Screen Shot 2019-12-31 at 4 14 46 PM](https://user-images.githubusercontent.com/1260765/71636079-b1959a00-2be8-11ea-9274-4334b505b70a.png)

### TermNode Interface

This release also introduces the TermNode interface, which allows for querying terms across Taxonomy types. 

For example: 

#### Query TermNodes Connection

```
{
  terms {
    nodes {
      id
      __typename
      name
      uri
    }
  }
}
```
![Screen Shot 2019-12-31 at 4 22 31 PM](https://user-images.githubusercontent.com/1260765/71636180-e22a0380-2be9-11ea-95bd-3e655582a459.png)

This enables us to do things, like search terms across multiple taxonomies and get both Categories and Tags (and custom taxonomies) back in the same query: 

```
{
  terms(where: {search: "test"}) {
    nodes {
      id
      __typename
      name
      uri
      ... on Tag {
        tagId
      }
      ... on Category {
        categoryId
      }
    }
  }
}
```

![Screen Shot 2019-12-31 at 4 24 38 PM](https://user-images.githubusercontent.com/1260765/71636192-10a7de80-2bea-11ea-896d-b06092a94995.png)

### Query Single Terms by Unique Identifiers
We can also query single term nodes by various identifiers, such as `Database ID`, `ID`, `Name`, `Slug` or `URI`: 

#### Query Single Term Node by (hashed) ID

```
{
  termNode(id: "cG9zdF90YWc6Mw==") {
    __typename
    id
    name
    link
    slug
    uri
  }
}
```

![Screen Shot 2019-12-31 at 4 28 01 PM](https://user-images.githubusercontent.com/1260765/71636235-8b70f980-2bea-11ea-8a26-c070e87a9541.png)

#### Query Single Term Node by Database ID

```
{
  termNode(id: 3, idType: DATABASE_ID) {
    __typename
    id
    name
    link
    slug
    uri
    databaseId
  }
}
```

<img width="1022" alt="Screen Shot 2020-01-01 at 3 53 24 PM" src="https://user-images.githubusercontent.com/1260765/71647102-e1a77080-2cae-11ea-93f3-8632ecb698e1.png">


#### Query Single Term Node by Name

```
{
  termNode(id: "Another Test", idType: NAME, taxonomy: TAG) {
    __typename
    id
    name
    link
    slug
    uri
    databaseId
  }
}
```
<img width="1022" alt="Screen Shot 2020-01-01 at 3 53 24 PM" src="https://user-images.githubusercontent.com/1260765/71647118-36e38200-2caf-11ea-9761-45b33c62a40e.png">


#### Query Single Term Node by Slug

```
{
  termNode(id: "another-test", idType: SLUG, taxonomy: TAG) {
    __typename
    id
    name
    link
    slug
    uri
    databaseId
  }
}
```

<img width="1026" alt="Screen Shot 2020-01-01 at 3 56 32 PM" src="https://user-images.githubusercontent.com/1260765/71647130-54185080-2caf-11ea-9e6d-c30551f3842f.png">


#### Query Single Term Node by URI

```
{
  termNode(id: "tag/another-test/", idType: URI) {
    __typename
    id
    name
    link
    slug
    uri
    databaseId
  }
}
```

<img width="1031" alt="Screen Shot 2020-01-01 at 3 57 44 PM" src="https://user-images.githubusercontent.com/1260765/71647144-7b6f1d80-2caf-11ea-9dc7-e0eac435c414.png">

## Node By URI

Another thing this release provides is a way to get any node by URI, across types. This comes in handy because in many cases when a URI is provided, the type of content it is isn't always known ahead of time. By having an entry point for _all_ Types that implement the 1UniformResourceIdentifiable` Interface, we can create a main entry point for entire applications. 

Below is an example. This is showing many queries at once, but this could easily be one query with fragments for each Type, controlled by their appropriate component for rendering said type of content:

```
{
  page: nodeByUri(uri: "about/") {
    ...URI
  }
  post: nodeByUri(uri: "2019/12/05/test-5/") {
    ...URI
  }
  tag: nodeByUri(uri: "tag/8bit/") {
    ...URI
  }
  category: nodeByUri(uri: "category/alignment/") {
    ...URI
  }
  user: nodeByUri(uri: "author/jasonbahl/") {
    ...URI
  }
}

fragment URI on UniformResourceIdentifiable {
  __typename
  ... on Page {
    pageId
  }
  ... on Post {
    postId
  }
  ... on Category {
    categoryId
  }
  ... on Tag {
    tagId
  }
  ... on User {
    userId
  }
}
```

<img width="1119" alt="Screen Shot 2020-01-01 at 4 05 25 PM" src="https://user-images.githubusercontent.com/1260765/71647226-b1f96800-2cb0-11ea-9b10-07565a1641d0.png">

**Comment by m-muhsin** [comment]
Beautiful! Thanks @jasonbahl

**Comment by TylerBarnes** [comment]
So stoked for this. This is a really great feature!
