### ISSUE TITLE
Not Able To Upload Media

### ISSUE THREAD

**Issue by KanhaHelp** [wp-graphql/wp-graphql#2639]
### Description

  I am not able to upload media .
  I want to create a mutation with something like **uploadMedia** , but how can I specify the input type to **Upload** ??

### Steps to reproduce

Not found any input type as Upload/media

### WPGraphQL Version

1.13.4

### WordPress Version

6.1.1

### PHP Version

8.1.2

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [ ] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Hey @KanhaHelp you can use https://github.com/dre1080/wp-graphql-upload to add an `Upload` GraphQL type to the schema, but you will need to register your own mutation to take advantage of it. 

Closing in favor of #311 which is tracking the addition of the `Upload` type (and supported mutation inputs) to WPGraphQL core.
