### ISSUE TITLE
Plugin Version should be String not Float

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#264]
The `version` field on Plugins should by of the String type, not float, as versions can be something like `2.0-beta13.1` which is not a float or an integer.

**Comment by gabriellacerda** [comment]
Can I take this one?

**Comment by jasonbahl** [comment]
Please do! Thanks!

You will need to update the unit tests as well

**Comment by gabriellacerda** [comment]
Ok!

**Comment by gabriellacerda** [comment]
Sorry for the inconvenience @jasonbahl, but it seems that it is not possible to make such modification 😢 .

**Comment by jasonbahl** [comment]
@gabriellacerda can you elaborate on why it's not possible?

**Comment by jasonbahl** [comment]
@gabriellacerda I believe the only change needed would be this line: https://github.com/wp-graphql/wp-graphql/blob/develop/src/Type/Plugin/PluginType.php#L109

Then probably need to update some Unit Tests to go with the change. 

It _will_ be a breaking change to the Schema, but that's fine as this is still beta software.

**Comment by gabriellacerda** [comment]
Oh, ok

**Comment by jasonbahl** [comment]
addressed by #270
