### ISSUE TITLE
Unexpected token '<', \"<html>\r\n<h\"... is not valid JSON

### ISSUE THREAD

**Issue by misbahansori** [wp-graphql/wp-graphql#2640]
### Description

Here is I have a query, basically just get posts with their featured images, tags, and categories. when I do a query like this, the response from the graphql return 404 status (on the network tab)

<img width="1325" alt="Screenshot 2022-11-30 at 09 42 15" src="https://user-images.githubusercontent.com/20674057/204694848-fc547813-e439-4cc8-a042-6f38b0e4c8d9.png">

But when I reduce the limit down to 7 it works fine.
<img width="1326" alt="Screenshot 2022-11-30 at 09 43 17" src="https://user-images.githubusercontent.com/20674057/204695380-612934ff-9ee6-4af9-9715-374324adb442.png">

or when I remove the featured image from the query, it's also working fine.
<img width="1327" alt="Screenshot 2022-11-30 at 09 43 40" src="https://user-images.githubusercontent.com/20674057/204695553-b357e367-7ac0-4de3-a7b8-9cfa8bd99eaf.png">

### Steps to reproduce

This will return error
```
{
  posts(first: 10) {
    nodes {
      databaseId
      slug
      title
      featuredImage {
        node {
          altText
        }
      }
      tags {
        nodes {
          name
          slug
        }
      }
      categories {
        nodes {
          name
          slug
        }
      }
    }
  }
}
```

this will not
```
{
  posts(first: 7) {
    nodes {
      databaseId
      slug
      title
      featuredImage {
        node {
          altText
        }
      }
      tags {
        nodes {
          name
          slug
        }
      }
      categories {
        nodes {
          name
          slug
        }
      }
    }
  }
}
```

this is also fine
```
{
  posts(first: 7) {
    nodes {
      databaseId
      slug
      title
      tags {
        nodes {
          name
          slug
        }
      }
      categories {
        nodes {
          name
          slug
        }
      }
    }
  }
}
```

### Additional context

I have around 103 posts

Installed plugins : 
- Add WPGraphQL SEO                     Version 4.20.0 by Ash Hitchcock
- Advanced Custom Fields                Version 6.0.5 by WP Engine
- Vercel Deploy Hooks                       Version 1.4.2 by Arden de Raaij
- WP GraphQL                                    Version 1.13.4 by WPGraphQL
- WPGraphQL for Advanced Custom Fields  Version 0.6.1 by WPGraphQL, Jason Bahl
- Yoast SEO                                         Version 19.11 by Team Yoast

### WPGraphQL Version

Version 1.13.4

### WordPress Version

WordPress 6.1.1

### PHP Version

8.1.2-1ubuntu2.8 (Supports 64bit values)

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [X] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Hey @misbahansori 👋

First step to diagnosing this would be do disable **all your plugins** besides for WPGraphQL core. If the issue goes away, then enable them one by one until the problem returns and you've found your culprit.

If the issue persists with only WPGraphQL enabled, I'd suggest taking a look at which particular post - or more specifically which media item - is throwing the error. 

If it works for your 7 most recent posts, but not your first 10, then my bet is post 8, 9, or 10, has a bad attachment (and my guess from the error is something like Yoast's redirections isnt being handled by it's WPGraphQL extension).

Please let us know what you find and report back, so if it is a bug with WPGraphQL core we can try to suggest a workaround or implement a fix.

**Comment by misbahansori** [comment]
Hi, @justlevine thanks for the response.

I've tried to disable the plugins one by one. and turned out that we have a custom plugin to filter the posts by ACF. I can confirm that when I deactivated this plugin, the issue is gone.

I think there is something wrong with the plugin but I don't know what is wrong. I still needed this plugin in order to filter the posts by the travel_agency_id.

here is the ACF configuration :
<img width="1282" alt="Screenshot 2022-11-30 at 16 56 33" src="https://user-images.githubusercontent.com/20674057/204765735-21824b35-d8a9-47ae-98ad-30c66012c8ed.png">

and here is the plugin code :
```
add_action('graphql_register_types', function () {
	$customposttype_graphql_single_name = "Post";

    register_graphql_field('RootQueryTo' . $customposttype_graphql_single_name . 'ConnectionWhereArgs', 'travelAgencyId', [
        'type' => 'String',
        'description' => 'Filter post by Travel Agency ID',
    ]);
});

add_filter('graphql_post_object_connection_query_args', function ($query_args, $source, $args, $context, $info) {

    $travel_agency_id = $args['where']['travelAgencyId'];

    if (isset($travel_agency_id)) {
        $query_args['meta_query'] = [
            [
                'key' => 'travel_agency_id',
                'value' => $travel_agency_id,
                'compare' => '='
            ]
        ];
    }

    return $query_args;
}, 10, 5);
```

and here is the result when using the plugin :
<img width="1200" alt="Screenshot 2022-11-30 at 17 00 51" src="https://user-images.githubusercontent.com/20674057/204766587-bfbe72cf-954c-492d-930d-b801d50a5b1e.png">

and here is the reference for writing that plugin :
https://www.wpgraphql.com/2020/04/14/query-posts-based-on-advanced-custom-field-values-by-registering-a-custom-where-argument

**Comment by justlevine** [comment]
The logic in your second filter callback is broken. It's essentially adding a broken meta query to every post object connection (of which an attachment CPT is one.

I'm not by my computer to fix the snippet for you but essentially you want to `if ( ! empty ($args['where']['travelAgencyId'] ) ){ }` _before_ you try to assign it to $travel_agency_id and add the meta query, instead of using `isset ()` on a variable you just set.

**Comment by justlevine** [comment]
@jasonbahl how do we fix the docs, is that backend or an .MD somewhere?

**Comment by misbahansori** [comment]
@justlevine Thanks for the feedback, we've changed the code to look like this, and the query for the first 10 posts is working.

```
add_action('graphql_register_types', function () {
	$customposttype_graphql_single_name = "Post";

    register_graphql_field('RootQueryTo' . $customposttype_graphql_single_name . 'ConnectionWhereArgs', 'travelAgencyId', [
        'type' => 'String',
        'description' => 'Filter post by Travel Agency ID',
    ]);
});

add_filter('graphql_post_object_connection_query_args', function ($query_args, $source, $args, $context, $info) {

	if ( ! empty ($args['where']['travelAgencyId'] ) ){
		$travel_agency_id = $args['where']['travelAgencyId'];
		$query_args['meta_query'] = [
            [
                'key' => 'travel_agency_id',
                'value' => $travel_agency_id,
                'compare' => '='
            ]
        ];	
	}
	
    return $query_args;
}, 10, 5);
```
---
But, I realize that the number is shifting. I mean, now the error is on the first 97 and above. the first 96 and below are fine. In contrast to earlier, when I disabled all of the extensions except for "WP GraphQL" the error still exists.

Here is the screenshot : 
<img width="1201" alt="Screenshot 2022-12-01 at 09 16 33" src="https://user-images.githubusercontent.com/20674057/204950050-f0235c94-96dd-4593-965a-c2db817b91d9.png">

<img width="1325" alt="Screenshot 2022-12-01 at 09 17 32" src="https://user-images.githubusercontent.com/20674057/204950060-3ed5e2e2-a2ca-4e10-b1bf-ea2c5842da32.png">

**Comment by sean0mc** [comment]
Maybe this helps you:

I got the same kind of error due to the lack of memory limit. 

When running the query I got the following error in my debug.log

`Fatal error:  Allowed memory size of 100663296 bytes exhausted (tried to allocate 20480 bytes) in /public_html/theme/wp-content/plugins/wp-graphql/src/Model/Model.php on line 350`

After increasing the memory limit, the query worked.

**Comment by jasonbahl** [comment]
> @jasonbahl how do we fix the docs, is that backend or an .MD somewhere?

I updated the snippet in this blog post: https://www.wpgraphql.com/2020/04/14/query-posts-based-on-advanced-custom-field-values-by-registering-a-custom-where-argument

The blog posts are managed in WordPress. 

Some of the other content (developer reference sections) are also managed in WordPress as well, but a lot of the docs are in Markdwown files here: https://github.com/wp-graphql/wp-graphql/tree/develop/docs

I believe the original issue is resolved with the fix to the snippet, so I'm going to close this issue.
