### ISSUE TITLE
Version 1.13.4 - Forcibly renames user defined fields to camelCase

### ISSUE THREAD

**Issue by Jonathan-Garber** [wp-graphql/wp-graphql#2641]
### Description

Introduced in PR #2625
Forcibly renames custom fields to camelCase.
This breaks anywhere we use mutations or queries.

```
$field_config['name'] = Utils::format_field_name( $field_config['name'] );
```

https://github.com/wp-graphql/wp-graphql/blob/b760dc02b21dafd05552f850f6910b05070ca33a/src/Utils/Utils.php#L112-L127

This is renaming all of our fields registered and removing "_" characters
'first_name' as defined in our custom object type fields is now becoming 'firstName'

### Steps to reproduce

Use 'register_graphql_object_type'

Define any fields with an underscore in their name

```
        'fields'      => [
            'first_name' => [
                'type'        => 'String',
            ],
```

The field will now be renamed to `firstName` though you are expecting it to be `first_name`

### WPGraphQL Version

1.13.4

### WordPress Version

6.1.1

### PHP Version

8.1

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
Thanks for reporting.

Will look into this.

**Comment by Jonathan-Garber** [comment]
You know after doing some research it does appear that general naming conventions for GraphQL do say to use CamelCase

So while this overrides what I specified in my own custom code it does appear to be conventionally correct.

I've got a lot of code using the underscore as it was keeping in line with those fields names on other parts of the system I'm integrated with but we may have to go through updating everything to fall into line with the standard convention. -sigh-

**Comment by Jonathan-Garber** [comment]
I would have to map all third-party reply fields from these 3rd parties im integrated with to camelCase. My custom field definitions used snake_case to match their returned data. Since not everyone follow the same standard as graphql....

**Comment by justlevine** [comment]
@Jonathan-Garber hold off on renaming all your types for now, and revert to `v1.12.x`. While graphql spec recommends using `camelCase`, it does support `snake_case`, and it's a regression that connections and mutations no longer allows for custom names in that format.
