### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by CodeProKid** [wp-graphql/wp-graphql#265]
We should improve the structure & content of the README.md file. We should look at some other popular open source projects, and get some ideas for structure for them. Here is just a rough idea of what I think needs to be done:

- Point to documentation about status codes being returned
- Point to documentation about extending WPGraphQL
- Example queries to get people going
- More concise section on contributing
- Point to documentation on paginating queries

**Comment by cr101** [comment]
Please also show an example on how Custom Post Types and their custom fields can be registered to WPGraphQL. 
For example, I have two CPTs (Companies and Addresses) which are connected to each other via an ACF Relationship field. The relationship between the two CPTs is _one-to-many_ where one address can only belong to one company and one company can have many addresses.

**Comment by jasonbahl** [comment]
@cr101 if you're still looking for examples, there are some in the Wiki and in closed issues. 

The README should definitely point these out in a central place though.

See: 
https://github.com/wp-graphql/wp-graphql/wiki/Extending-and-Customizing
#173 (comment)
#146
#11

**Comment by cr101** [comment]
@jasonbahl Thanks Jason for providing the links. I'm trying to wrap my head around it all. Having more examples in one place would be much appreciated.

Btw, [Create React App](https://github.com/facebookincubator/create-react-app/blob/master/README.md) has a well structured README.md file and a very useful User Guide
