### ISSUE TITLE
No schema available in GraphiQL

### ISSUE THREAD

**Issue by cr101** [wp-graphql/wp-graphql#266]
There is no schema available in the GraphiQL app when I click on the Docs icon. Is there something I'm missing?
![screenshot_41](https://user-images.githubusercontent.com/4064582/31639495-89d7910e-b335-11e7-9526-22676b7ffc43.jpg)

Thank you to everyone who has worked on this awesome plugin.

**Comment by cr101** [comment]
I just worked it out. The schema is only available before executing a GraphQL query.

**Comment by jasonbahl** [comment]
@cr101 that sounds odd that it’s only available for you before executing a query. . .Curious if it’s a bug with the version of the GraphiQL app you’re using 🤔

**Comment by cr101** [comment]
@jasonbahl The version of GraphiQL app installed on my Windows 10 machine is the latest. I will let you know if I came across this issue again.

**Comment by gerhardsletten** [comment]
Had to restart GraphiQL app on mac to get schema

**Comment by mithunmqb** [comment]
Even restarting didn't work in my case.
