### ISSUE TITLE
Interface field WpEdgeType.node expected but WpEnqueuedScriptConnectionEdgeType does not provide it.

### ISSUE THREAD

**Issue by hamiltonbrooke** [wp-graphql/wp-graphql#2660]
### Description

Updated WP GraphQL to Version 1.13.5

After running npm run develop, I get an error while running the process:

error UNHANDLED REJECTION Interface field WpEdgeType.node expected but WpEnqueuedScriptConnectionEdgeType does not provide it.

10:40:53 AM: error UNHANDLED REJECTION Interface field WpEdgeType.node expected but WpEnqueuedScriptConnectionEdgeType does not provide it.
10:40:53 AM: Interface field WpEdgeType.node expected but WpEnqueuedStylesheetConnectionEdgeType does not provide it.
10:40:53 AM: Interface field WpEdgeType.node expected but WpActionMonitorActionConnectionEdgeType does not provide it.
10:40:53 AM: Interface field WpEdgeType.node expected but WpPluginConnectionEdgeType does not provide it.
10:40:53 AM: Interface field WpEdgeType.node expected but WpThemeConnectionEdgeType does not provide it.
10:40:53 AM: 
10:40:53 AM: 
10:40:53 AM:   Error: Interface field WpEdgeType.node expected but WpEnqueuedScriptConnection  EdgeType does not provide it.
10:40:53 AM:   Interface field WpEdgeType.node expected but WpEnqueuedStylesheetConnectionEdg  eType does not provide it.
10:40:53 AM:   Interface field WpEdgeType.node expected but WpActionMonitorActionConnectionEd  geType does not provide it.
10:40:53 AM:   Interface field WpEdgeType.node expected but WpPluginConnectionEdgeType does n  ot provide it.
10:40:53 AM:   Interface field WpEdgeType.node expected but WpThemeConnectionEdgeType does no  t provide it.
10:40:53 AM:   
10:40:53 AM:   - graphql-runner.ts:129 GraphQLRunner.validate
10:40:53 AM:     [repo]/[gatsby]/src/query/graphql-runner.ts:129:14
10:40:53 AM:   
10:40:53 AM:   - graphql-runner.ts:218 GraphQLRunner.query
10:40:53 AM:     [repo]/[gatsby]/src/query/graphql-runner.ts:218:49
10:40:53 AM:   
10:40:53 AM:   - create-graphql-runner.ts:57 
10:40:53 AM:     [repo]/[gatsby]/src/bootstrap/create-graphql-runner.ts:57:8
10:40:53 AM:   
10:40:53 AM:   - create-pages-from-collection-builder.js:45 createPagesFromCollectionBuilder
10:40:53 AM:     [repo]/[gatsby-plugin-page-creator]/create-pages-from-collection-builder.js:    45:13
10:40:53 AM:   
10:40:53 AM:   - create-page-wrapper.js:43 createPage
10:40:53 AM:     [repo]/[gatsby-plugin-page-creator]/create-page-wrapper.js:43:76
10:40:53 AM:   
10:40:53 AM:   - gatsby-node.js:135 
10:40:53 AM:     [repo]/[gatsby-plugin-page-creator]/gatsby-node.js:135:41
10:40:53 AM:   
10:40:53 AM:   - Array.forEach
10:40:53 AM:   
10:40:53 AM:   - gatsby-node.js:134 Object.createPagesStatefully
10:40:53 AM:     [repo]/[gatsby-plugin-page-creator]/gatsby-node.js:134:11
10:40:53 AM:   
10:40:53 AM: 
10:40:53 AM: not finished createPagesStatefully - 0.155s

### Steps to reproduce

1. npm run develop

### WPGraphQL Version

1.13.5

### WordPress Version

6.1.1

### PHP Version

7.4

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Hey @hamiltonbrooke This seems to be an issue with `gatsby-source-wordpress` that @TylerBarnes is actively working to fix. https://github.com/gatsbyjs/gatsby/issues/37114

Closing this issue in favor of that one.
