### ISSUE TITLE
regression: snake_case fields being forced to camelCase

### ISSUE THREAD

**Issue by twobyte** [wp-graphql/wp-graphql#2666]
### Description

Apollo query against WP-GraphQL inexplicably stopped working. Turns out I had to change snake_case to camelCase in the query to get it working. So from this (which used to work fine):
```
{
  indicatorCategories {
    nodes {
      indicator_categoryId
      name
      slug
      description
      indicatorColor
      indicators(first: 100) {
        nodes {
          indicatorId
          menuOrder
          title
          link
          slug
          definitionLevel
        }
      }
    }
  }
}
```
to this:

```
{
  indicatorCategories { 
    nodes { 
      indicatorCategoryId 
      name 
      slug 
      description 
      indicatorColor 
      indicators(first: 100) { 
        nodes { 
          indicatorId 
          menuOrder 
          title 
          link 
          slug 
          definitionLevel 
        } 
      } 
    } 
  } 
} 
```

The thing that made this really difficult to figure out is that the WordPress GraphiQL IDE would not accept the camelCase query, only the incorrect snake_case query, which was not working with the React app any more. 

I reverted to old versions of WP-GraphQL but this didn’t resolve the issue. The document explorer says ERROR FETCHING SCHEMA, but I do not know how I would fix that.

I have attached a screenshot of this for reference.
![Screenshot 2022-12-08 at 14 22 11](https://user-images.githubusercontent.com/971319/206473190-8b1e3c58-2e62-456e-b19e-abf3a1e39aad.png)

### Steps to reproduce

Using Wordpress Version 6.1.1 with WP GraphQL Version 1.13.6.

Create custom post type with 
```
        'show_in_graphql' => true,
        'graphql_single_name' => 'indicator',
        'graphql_plural_name' => 'indicators',
```
and add a taxonomy called `indicator_category`

### WPGraphQL Version

1.6 -> 1.13.6

### WordPress Version

6.1.1

### PHP Version

7.4

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
This should have been fixed in #2645 🤔

**Comment by jasonbahl** [comment]
I've confirmed this is still a regression not _fully_ addressed by #2645.

I have another PR in progress to fix this regression. And some more tests to help prevent this type of regression again.

**Comment by twobyte** [comment]
Thanks @jasonbahl, really great plugin!

**Comment by jasonbahl** [comment]
> Thanks @jasonbahl, really great plugin!

@twobyte thanks! Glad you're enjoying it. Apologies for the regression 😢. Thanks for reporting it quickly and I'm glad we were able to get to a speedy reproduction and resolution.
