### ISSUE TITLE
TypeError: Cannot destructure property 'fields' of 'nodesType' as it is undefined. 

### ISSUE THREAD

**Issue by aryanrajput** [wp-graphql/wp-graphql#2676]
### Description

Getting this error on gatsby develop

### Steps to reproduce

Getting error after run gatsby.

### Additional context

When I deGrade WP GraphQL version to 1.12.2. Project working fine except fullHead that giving duplicate. as example below..

![image](https://user-images.githubusercontent.com/26869121/207069558-b6b73c3a-7b5e-47c9-b3a0-6b9101ffdf86.png)

### WPGraphQL Version

1.13.7

### WordPress Version

6.1.1

### PHP Version

7.4.33

### Additional enviornment details

"gatsby-source-wordpress": "^6.24.0",
"gatsby": "^4.19.2",
"react": "^18.1.0",

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
This is being tracked in Gatsby Source WordPress. https://github.com/gatsbyjs/gatsby/issues/37114#issuecomment-1343387335

**Comment by TylerBarnes** [comment]
@aryanrajput upgrading to the latest v6.x.x or v7.x.x of `gatsby-source-wordpress` should fix it. Let me know in the issue Jason linked if it doesn't
