### ISSUE TITLE
Find objects based on multiple custom fields

### ISSUE THREAD

**Issue by cr101** [wp-graphql/wp-graphql#268]
Is it possible to find post objects based on multiple custom fields like below?

```
{
  authors {
    edges {
      node {
        id
        title
        slug
        books(relation: "AND", publisher: "O'Reilly Media", average_rating: "> 3") {
          edges {
            node {
              id
              title
              isbn
              publisher
            }
          }
        }
      }
    }
  }
}
```

**Comment by jasonbahl** [comment]
@cr101 _most_ of the WPQuery args are supported out of the box via `where` args. 

So you can do something like:

```
{
  posts(where: {authorName: "jasonbahl", categoryName: "uncategorized"}) {
    edges {
      node {
        id
        title
        author {
          name
        }
        categories {
          edges {
            node {
              id
              slug
            }
          }
        }
      }
    }
  }
}

```

If you wanted to support additional args to query by, especially things that are not core WP data (like you publisher / rating fields), you would need to filter in support for your particular systems needs. 

The `where` args are filterable, so you can add in any args you need for your system.

**Comment by jasonbahl** [comment]
@cr101 also, fwiw, we have these extensions that add Meta Query support and Tax Query support: 

https://github.com/wp-graphql/wp-graphql-meta-query
https://github.com/wp-graphql/wp-graphql-tax-query

**Comment by betweenbrain** [comment]
> The where args are filterable, so you can add in any args you need for your system.

@jasonbahl is there any chance you can post an example of this? I can't seem to find one.

Thanks!

**Comment by amie-wilt** [comment]
@betweenbrain did you figure this out?
