### ISSUE TITLE
If an interface attempts to implement itself, infinite recursion can occur

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#2687]
### Description

When registering an Interface, if the interface itself is listed as an Interface to be applied to itself, infinite recursion can occur. 

### Steps to reproduce

Using the following code, register an Interface that implements itself as an Interface: 

```php
add_action(  'graphql_register_types', function() {

	register_graphql_interface_type( 'InterfaceA', [
		'interfaces' => [ 'Node', 'InterfaceA' ],
		'fields' => [ 'fieldA' => [ 'type' => 'String' ] ],
		'resolveType' => function() {
			return 'Post';
		}
	]);


	register_graphql_interfaces_to_types( [ 'InterfaceA' ], [ 'Post' ] );

});
```

See a fatal error: 

```php
Fatal error: Uncaught Error: Maximum function nesting level of '1000' reached, aborting!
in ... on line 164
```

### Additional context

If an interface tries to implement itself (intentionally or accidentally) we should prevent this by unsetting itself as an implemented interface. 

### WPGraphQL Version

1.13.7

### WordPress Version

6.1.1

### PHP Version

7.4.1

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
> If an interface tries to implement itself (intentionally or accidentally) we should prevent this by unsetting itself as an implemented interface.

Considering this is a coding error and not a usage error, would it be better to throw a (more informative) error? 

The more forgiving we are with code patterns, the larger the test area and future code debt...

**Comment by jasonbahl** [comment]
@justlevine I actually caught this when using Advanced Custom Fields, so it was caught while using a UI, not while writing code.

I think because of the nature of WordPress hooks and filters and the ability to modify the schema through non-code methods like this, we can't let an end user action tank the whole schema. 🤷🏻‍♂️

**Comment by justlevine** [comment]
Then it sounds like the code in ACF needs to be fixed to prevent offering the user that option ;)

I didn't mean tank the whole schema though, just the added interface (like how we handle [bad and duplicate](https://github.com/wp-graphql/wp-graphql/blob/develop/src/Registry/TypeRegistry.php#L626-L649) ), instead of silently dedupe-ing.

**Comment by jasonbahl** [comment]
Ah ya, I am outputting a `graphql_debug` message like that already 😄 but not throwing an actual error

**Comment by jasonbahl** [comment]
Here's the commit: https://github.com/wp-graphql/wp-graphql/pull/2689/commits/ca9f50f5a4765e2f7b8ee11280e74cdc80193213#diff-1ef830713e778cfb2bfa9b3f4bd65275fb16da99d624051186143500e33495acR46
