### ISSUE TITLE
Custom post types errors: "Unexpected token '<', \"<meta name\"... is not valid JSON",

### ISSUE THREAD

**Issue by androidealp** [wp-graphql/wp-graphql#2688]
### Description

All custom post type not working in consult.

`
$args = array(
              'supports' => $supports,
              'labels' => $labels,
              'show_in_graphql' => true, //graphql_
              'graphql_single_name' => 'material', //graphql_
              'graphql_plural_name' => 'materiais', //graphql_
              'publicly_queryable' => true, //graphql_
              'public' => true,
              'show_in_admin_bar' => true,
              'query_var' => true,
              'rewrite' => array('slug' => 'materiais'),
              'has_archive' => true,
              'hierarchical' => true,
          );

      register_post_type('materiais', $args);
`

### Steps to reproduce

query NewQuery {
  materiais {
    edges {
      node {
        title
      }
    }
  }
}

### Additional context

Error:

`{
  "errors": {
    "message": "Unexpected token '<', \"<meta name\"... is not valid JSON",
    "stack": "SyntaxError: Unexpected token '<', \"<meta name\"... is not valid JSON"
  }
}`

### WPGraphQL Version

1.13.7

### WordPress Version

6.1.1

### PHP Version

7.4.33

### Additional enviornment details

WP Gatsby:  2.3.3
WPML: 4.4.10

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
@androidealp what is the actual response from the GraphQL endpoint? https://www.wpgraphql.com/docs/debugging#checking-the-response

**Comment by androidealp** [comment]
Running the test above, the response returns the message "Failed to load response data: No content available because this request was redirected"

So I created a test using the CPT UI plugin, and through it I can see the same error on the display but in the debug
and then returns the 301 redirects again

{"data":{"__schema":{"queryType":{"name":"RootQuery","__typename":"__Type"},"mutationType":{
    "name":"RootMutation","__typename":"__Type"},"subscriptionType":null,"types":[{
        "kind":"OBJECT","name":"RootQuery",
        "description":"The root entry point into the Graph",
        "fields":[{"name":"actionMonitorAction",
        "description":"An object of the ActionMonitorAction Type. Used to keep a log of actions in WordPress for cache invalidation in gatsby-source-wordpress.",
        "args":[{
            "name":"id",
            "description":"The globally unique identifier of the object.",
            "type":{"kind":"NON_NULL","name":null,"ofType":{
                "kind":"SCALAR","name":"ID","ofType":null,"__typename":"__Type"},"__typename":"__Type"},
                "defaultValue":null,"__typename":"__InputValue"},{"name":"idType",
                "description":"Type of unique identifier to fetch by. Default is Global ID",
                "type":{"kind":"ENUM","name":"ActionMonitorActionIdType","ofType":null,"__typename":"__Type"},
                "defaultValue":null,"__typename":"__InputValue"},

**Comment by justlevine** [comment]
Hey @androidealp , from the error response it seems you forgot to disable _all_ your plugins (ignoring CPT UI for your second test). Please disable _everything_ (including WPGatsby) and only then report back the logs. (You also forgot to share what, if anything, is in your WP `debug.log` file).

If the error goes away, re-enable your other plugins one at a time until the issue comes back. That will let us know if there's a plugin conflict we need to investigate. (The most common cause for redirect errors is a plugin doing something unconventional).

If the issue persists even with all plugins disabled except for WPGraphQL core, please go to Settings > Permalinks, ensure pretty permalinks are enabled, and click 'Save Permalinks' to force-regenerate. Then retry visiting the IDE, and send the requested logs. If your WP install is nonstandard (e.g. a different frontend/backend url), please share them as well.

**Comment by justlevine** [comment]
There's a lot of issues with WPML (it does a lot of nonstandard stuff to the query, but I've never heard of it getting in the way of loading the backend itself)

**Comment by androidealp** [comment]
I'm going to do the tests above, but I noticed in another installation that version 1.13.6 is functional for me.

**Comment by justlevine** [comment]
> I'm going to do the tests above, but I noticed in another installation that version 1.13.6 is functional for me.

The only production code affected in that bump is #2671 which fixes a regression regarding autoregistered mutation names. Shouldn't affect the issues you're having...🤔

**Comment by androidealp** [comment]
i found the problem, the wpml extension requires another extension to work in graphql.
thank you guys
This extension: WPGraphQL WPML
