### ISSUE TITLE
Querying Subcategories

### ISSUE THREAD

**Issue by towfiqi** [wp-graphql/wp-graphql#269]
I am trying to get all categories with their children. Is it possible in one query? My query looks like this:

```
query{
	categories(first:100, where:{exclude:[1]}){
    nodes{
        categoryId
		name
        description,
        slug
    }
  }
}
```

Thanks

**Comment by towfiqi** [comment]
**Solved** by passing id of each parent category as props to another component which queries subcategories like this:

```
gql `query wpdSubCategories($parentId:Int!){
	categories(first:100, where:{parent:$parentId}){
    nodes{
        categoryId
		name
        description,
        slug
    }
  }
}
```

But it would have been great if it was possible to query with an option to display the subcategories with an option like "showChild:true". You can close the issue.

Thanks

**Comment by jasonbahl** [comment]
@towfiqi hey! So, there's _supposed_ to be a `children` field on hierarchical taxonomies so that you can query terms with children like so: 

```
{
  categories {
    edges {
      node {
        id
        name
        children {
          edges {
            node {
              id
              name
            }
          }
        }
      }
    }
  }
}
```
I'm not sure what happened because it's not there. . .my guess is I have it in a branch I never merged. . .I'll check it out 🤔 


I do like the idea of an argument that allows children to be included in the top level list of categories without having to use the children field though. . .I'll think about how that should look. . .PR welcome as well if you want to work on it 😄

**Comment by towfiqi** [comment]
This looks far better than my idea. But just tried it and got "Cannot query field "children" on type "category".

Thanks

**Comment by jasonbahl** [comment]
@towfiqi ya see my previous comment: 

> I'm not sure what happened because it's not there. . .my guess is I have it in a branch I never merged. . .I'll check it out 🤔

I'll see if I can find it and get it out. . .I definitely remember working on that code so I believe I have it locally on a branch that just never got released.

**Comment by jasonbahl** [comment]
@towfiqi this is now fixed in `develop` and will be part of the next release. 

You can now do a query like this on Hierarchical PostTypes: 

```
{
  categories {
    edges {
      node {
        id
        name
        description
        children {
          edges {
            node {
              id
              name
              description
            }
          }
        }
      }
    }
  }
}
```

**Comment by jasonbahl** [comment]
addressed by #272

**Comment by towfiqi** [comment]
Many Thanks :smile:

**Comment by dev-catalyst** [comment]
![image](https://user-images.githubusercontent.com/38284073/73333627-6080d080-4290-11ea-99fe-aa8c7b799142.png)
Can't find "edges" node in "children".
How can I fetch all the subcategories of a parent category by passing the id of the parent category?

**Comment by jasonbahl** [comment]
@dev-catalyst it appears that you might be using `gatsby-source-wordpress` which uses the WP REST API and not WPGraphQL.
