### ISSUE TITLE
How can I load base64 for placeholder blurDataURL in NextJS

### ISSUE THREAD

**Issue by opr-inzn** [wp-graphql/wp-graphql#2692]
### Description

I'm using the NextJS Image tag and would like to have my Wordpress Images blurred when they're not properly loaded yet. This is fairly easy with Next using placeholder="blur" and blurDataURL= a base64 string of the image. However, I do not know how to retrieve such a string. I’m querying my page content like this 

```
export async function getHomeContent() {
  const data = await fetchAPI(
    `
    query HomeContent {
      page(id: "...") {
        content
      }
    }
  `
  );

  return data;
}
```

but this of course does not return any base64 image attributes. What is a possible solution here?

### WPGraphQL Version

1.13.7

### WordPress Version

6.1.1

### PHP Version

8.1

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by predaytor** [comment]
Using Imagick:
```php
<?php

use Imagick;
use GraphQL\Type\Definition\ResolveInfo;
use WPGraphQL\AppContext;

add_action('graphql_register_types', function () {

    register_graphql_field('MediaItem', 'placeholderDataURI', [
        'description' => __('Encoded base64 placeholder', 'default'),
        'type' => 'String',
        'resolve' => function (\WPGraphQL\Model\Post $source, $args, AppContext $context, ResolveInfo $info) {
            $file_local_abs_path = wp_get_attachment_image_url($source->databaseId);

            if (!isset($file_local_abs_path)) {
                return null;
            }

            $file_relative_path = parse_url($file_local_abs_path)['path'];

            $file_path = $_SERVER['REQUEST_SCHEME'] . '://' . $_SERVER['REMOTE_ADDR'] . $file_relative_path;
            $mime_type = pathinfo($file_path, PATHINFO_EXTENSION);

            $image = new Imagick($file_path);

            $image->resizeImage(128, 128, Imagick::FILTER_CATROM, 1);
            $image->blurImage(100, 20);
            $image->stripImage();

            return 'data:image/' . $mime_type . ';base64,' . base64_encode($image);
        }
    ]);
});
```

**Comment by amcc** [comment]
this is really useful - is there a way without a compiler - i'm assuming thats what the 'use' keyword is doing here. thanks

**Comment by predaytor** [comment]
> this is really useful - is there a way without a compiler - i'm assuming thats what the 'use' keyword is doing here. thanks

I have updated the answer. Use this now instead of the large generated placeholder that was used before. If you're not using a Next.js <Image /> with the `placeholder="blur"` option, I've attached the source code from Next.js that is used to generate the svg based on the provided placeholder data (our small generated `lqip`).

**Comment by amcc** [comment]
Thanks - I am using next.js, however (and i might be wrong) is the "use" bit above for composer, or another compiler. I'm not using that in WP at the moment, so i think this might not work for me. Excuse the ignorance here.

**Comment by predaytor** [comment]
Do you mean the `use Imagick` statement? This is a php namespace declaration.

**Comment by amcc** [comment]
yes thats what i was getting at - sorry must have got that wrong. I was getting an error before with those statements i thought. However the updated code does not error. I've put it in a custom plugin - i'm getting the lqip field in the graphql now, however its returning null.

Done a bit of debugging and it looks like the metadata isn't there, ```isset($attachment_metadata['lqip'])``` returns an empty string. maybe its a Imagick problem, or that isn't installed

**Comment by predaytor** [comment]
it only works for newly uploaded images, maybe you can try to debug errors with `debug.log`? If you want to update existing images to have an `lqip` field, use this script (you can run this in the console using wp-cli (if intalled), executing `wp eval-file` command):
```php
<?php

/** Script for updating images lacking `lqip` metadata field */

// Get a list of image attachments with specific metadata conditions
$attachments = get_posts(
    [
        'post_type' => 'attachment',           // Retrieve attachments
        'posts_per_page' => -1,                // Retrieve all attachments
        'post_mime_type' => 'image',           // Only images
        'fields' => 'ids',                     // Retrieve only IDs
        'meta_query' => [
            [
                'key' => '_wp_attachment_metadata',   // Filter by specific metadata key
                'compare' => 'EXISTS'                // Check if metadata exists
            ],
            [
                'key' => '_wp_attachment_metadata',   // Additional metadata filter
                'value' => 'lqip',                   // Value to compare
                'compare' => 'NOT LIKE',             // Exclude attachments with 'lqip' value
            ],
        ]
    ]
);

// Loop through each attachment to process
foreach ($attachments as $attachment_id) {
    $url = get_attached_file($attachment_id);      // Get file path of the attachment

    // Skip SVG images
    if (strpos($url, '.svg') !== false) continue;

    // Retrieve attachment metadata
    $attach_data = wp_get_attachment_metadata($attachment_id);

    // Update attachment metadata (no actual changes, triggers updates)
    wp_update_attachment_metadata($attachment_id, $attach_data);
}
```

**Comment by amcc** [comment]
ok thanks - i think i have a Image Magick problem though, i put this in the register_graphql_field function to just see what was going on:
```
if (!extension_loaded('imagick')){
    return 'imagick not installed';
}
```
looks like i dont have that installed - i'll see what i can do about that. I thought i might be able to use WPs image editor to do the same thing like this (With code similar to your original:
```
$image = wp_get_image_editor( $file_path );

    if ( ! is_wp_error( $image ) ) {
        $image->resize( 128, 128, true ); // get here fine
        $data = file_get_contents($image); // this line errors
        return 'data:image/' . $mime_type . ';base64,' . base64_encode($data);
}
 ```
 I get an error when i try to get the $data above. Currently on a shared WP server so not sure about ImageMagick

**Comment by predaytor** [comment]
not sure, Imagick should be installed on most shared hosts, I use the official Docker image where it is already packaged (https://github.com/docker-library/wordpress/blob/2eba26f088c12dea179623ee8af5cb52e6f60c4a/latest/php8.3/fpm/ Dockerfile #L47)

**Comment by amcc** [comment]
my bad - was trying to get this to work in MAMP locally - just tried on my online server it works on newly uploaded images - thanks!

Is there a way of simply generating the base64 without needing to save the file?

Thanks for all the help here
