### ISSUE TITLE
`PostObjectConnectionResolver`s `get_query()` function returns new query instead of existing query.

### ISSUE THREAD

**Issue by iWildman1** [wp-graphql/wp-graphql#2696]
### Description

Hello! I'm not too sure whether this is an actual issue or intended behaviour but I thought I'd mention it just in case.

I'm overriding the query of a default post type with the `graphql_connection_query` filter as I've got a custom query class that's making geo-queries based on latitude/longitude. The query itself works fine, but I noticed that when I modified the page info on the connection to return `found_posts`, the number I get back is wrong - It's returning the amount of posts as if it was a normal `WP_Query` call.

I've confirmed that `found_posts` does actually return the correct number on the correct query - Debugging it in the `graphql_connection_query` filter confirms the amount I'd expect to see, as does the same functionality in a REST endpoint.

I may be completely off-target here, but I had a look at the `PostObjectConnectionResolver` class and the `get_query` function is returning a new query every time with the same arguments, not the existing query stored on the class instance.

Would very much appreciate a nudge in the right direction if I'm doing something wrong here!

### Steps to reproduce

1. Override the default query with the `graphql_connection_query` filter.
2. Call `$resolver->get_query()` in the `graphql_connection_query_args` filter
3. Check whether the query is the same instance that was passed in the original step 

### WPGraphQL Version

1.13.7

### WordPress Version

6.1.1

### PHP Version

7.4

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Hey @iWildman1 

So this _is_ intended behavior, but imo it _shouldn't be_. 
The way `graphql_connection_query` (and many other filters in `AbstractConnectionResolver`), is that it filters the _instance parameter_ in the class constructor, and not the results of the actual getter methods.

**Comment by iWildman1** [comment]
Thanks @justlevine!

In the meantime, would you suggest a similar approach to the linked issue of de-registering the post type, then re-registering it with the `queryClass` set to the correct WP_Query subclass, or do you think there's a better approach?

I did try altering `queryClass` with the `graphql_wp_connection_type_config` filter but I think I'm misunderstanding the filter and nothing much happened.

**Comment by justlevine** [comment]
All `query_class` does is say whether `get_query()` should instantiate a WP_Query (default), or a child thereof (e.g. WP_Term_Query or WP_User_Query). Not really sure what you're trying to do, but unless you've created a custom child class for WP_Query, it probably isn't what you're looking for.

Without knowing more about your use case, the best approach would be to reevaluate your code so it doesn't rely on calling any of the `AbstractConnectionResolver` getter methods outside of that connection's constructor but instead only the (sadly limited) filter params.

**Comment by iWildman1** [comment]
That's pretty much what I'm trying to do - Overwrite the default `WP_Query` for a specific root post type connection to use a custom `WP_Geo_Query` child class instead.

 I set `graphql_register_root_connection` to `false` in the post type registration function and re-registered the connection manually, but strangely enough setting the `queryClass` on the connection registration didn't actually do anything. Subclassing the `PostObjectConnectionResolver` for that specific connection seems to have done the trick though!

Thanks for your help and for the nudge in the right direction!
