### ISSUE TITLE
`sprintf()` not interpolating strings properly in some places

### ISSUE THREAD

**Issue by CodeProKid** [wp-graphql/wp-graphql#271]
It seems that `sprintf()` isn't interpolating strings properly in some places... Within documentation, and error messages. Probably need to dig into the problem a bit more to figure out what is actually going on here, and in what contexts this is breaking in order to come up with a solution.

**Comment by jasonbahl** [comment]
@CodeProKid I think I've come across a few where I'm passing an ID (integer) but telling sprintf that it's a string, which might be some of the issues you're seeing. . .would be good to do a sweep though and figure out if that's _THE_ issue, or if there's more at play

**Comment by jasonbahl** [comment]
addressed by #286
