### ISSUE TITLE
documentation non existent for using and querying custom tables

### ISSUE THREAD

**Issue by marketsystems** [wp-graphql/wp-graphql#2727]
### What problem does this address?

https://www.wpgraphql.com/docs/using-data-from-custom-database-tables

doesnt actually tell you anything

"After reading this guide, you should be familiar with how WPGraphQL handles data and have a better understanding of WPGraphQL APIs to [register object types](https://www.wpgraphql.com/functions/register_graphql_object_type), [register connections](https://www.wpgraphql.com/functions/register_graphql_connection), **create custom Data Loaders and custom Connection Resolvers.**"

### What is your proposed solution?

Needs to explain how to extend AbstractConnectionResolver and AbstractDataLoader in order to achieve this with custom tables!

The article seems to stop after the intro and doesnt give any kind of help

**Comment by nazmateo** [comment]
I also need to access wp custom tables using graphql and can't seem to find any articles for this. Did you found one @marketsystems?

**Comment by ausrussell** [comment]
Same issue I'm looking for guidance for. Am trying to work from https://github.com/wp-graphql/wp-graphql/issues/299 and have asked for guidance on the slack channel for this plugin.

**Comment by justlevine** [comment]
Dont have the time to write up an actual tutorial, but here's a bit of an info dump to help people get started.

1. WPGraphQL lets you return data from any source if you know how to use PHP. Data is fetched when the field is resolved (either the code you run in your `resolve` callback, or prefetched data stored in a `Model` or `DataLoader`.
2. You can do custom calls to WordPress 's database using methods on  the `$wpdb` global. The WP API docs will show you how to use it (and best practices regarding sanitization), but if you're doing something complicated, you probably want to create a custom PHP class for interfacing with your custom datatable.
3. On the lowest level, in a field resolver you call and return the value of `$wpdb->query()`. Next step would be to do it in the Model, or even better in the data loader, so you can limit the number of calls to the DB for performance.
4. You need to extend AbstractConnectionResolver, focusing on `get_query()`, which is where you'll tell it to use `$wpdb->query()`  to get the IDs of the objects the connection is requesting.
5. In your custom data loader, you then will have the wpdb query to populate all the data your model needs for your object.

I know these are really broad strokes, but at least it's a starting point.

**Comment by marketsystems** [comment]
extend the classes AbstractConnectionResolver and AbstractDataLoader, easiest way to work it out is to look in the wpgraphql module at the existing classes for post. menu item etc that at least gives something to work from

**Comment by marketsystems** [comment]
also check out https://github.com/wp-graphql/wp-graphql-notifications-connection-example/blob/master/wp-graphql-notifications.php

which gives the general concept and read the associated thread in slack channel https://app.slack.com/client/T3PDM1KRC/C3NM1M291/thread/C3NM1M291-1673523426.972439

**Comment by jasonbahl** [comment]
I did recently publish this guide: https://www.wpgraphql.com/docs/using-data-from-custom-database-tables

Hope it helps anyone looking for info on this topic. 

Of course it's a broad topic and can be tackled in many different ways but I hope the concepts I shared in that guide should at least get you heading in the right direction if you're working with custom tables. 

Would love to see what y'all come up with!

**Comment by HoppGwyn** [comment]
> I did recently publish this guide: [wpgraphql.com/docs/using-data-from-custom-database-tables](https://www.wpgraphql.com/docs/using-data-from-custom-database-tables)
> 
> Hope it helps anyone looking for info on this topic.
> 
> Of course it's a broad topic and can be tackled in many different ways but I hope the concepts I shared in that guide should at least get you heading in the right direction if you're working with custom tables.
> 
> Would love to see what y'all come up with!

Hi Jason,

I followed this guide for creating custom notifications - it was really helpful - a few points/questions on it.

There is a spelling mistake on the snippet for creating a User connection:
```
register_graphql_connection([
	'fromType' => 'User',
	'toType' => 'Noticication',
```
Should be `Notification`, instead of `Noticication`

It took me a while to find out that I had to use `connectionArgs` instead of just `args` when trying to add args to a connection query. I was wondering where this was documented and whether it would be good to include this in the guide.

Finalyy - I'm having issues querying the databaseId on this - I am getting an error `'Cannot return null for non-nullable field "Notification.databaseId".'` so I'm wondering if the databaseId is getting resolved correctly? When trying to manually add it to the schema I get an error about type Int! not existing, and it seems it should be automatically included by using `'interfaces' => [ 'Node', 'DatabaseIdentifier' ],`

Any help is much appreciated.

Thanks,

Gwyn

**Comment by kinnn2** [comment]
If you have time, it would be great if you could create an example, code repository, tutorial video, or anything that includes Pagination for reference.

I was able to implement pagination using [wp-graphql-offset-pagination ](https://github.com/valu-digital/wp-graphql-offset-pagination), but I want to use it properly as a dependency of AbstractConnectionResolver and need cursor-based pagination.

I've searched, but unfortunately I couldn't find anything related, so I apologize if I'm missing something. I'd be grateful for a reference. 
I've also looked at the well-made wp-graphql extensions, but they're customized, so it's hard to figure out how to use them as a beginner. 

PS. Please understand that this article was written using a translator
Thank you.
