### ISSUE TITLE
Capitalize Types

### ISSUE THREAD

**Issue by CodeProKid** [wp-graphql/wp-graphql#273]
@jasonbahl and I had talked about this a little bit ago. Might be worth revisiting/implementing before the 1.0 release, since it will be a breaking change. Essentially things like `posts` should actually be `Posts`. It seems more proper since these are kind of "entities", and I think most people translate that to a proper noun of sorts.

**Comment by jasonbahl** [comment]
FYI, I'm working on this right now.

**Comment by jasonbahl** [comment]
addressed by #291
