### ISSUE TITLE
Debug output is enabled when tests run with DEBUG=0

### ISSUE THREAD

**Issue by markkelnar** [wp-graphql/wp-graphql#2734]
### Description

When setting the Docker environment variable DEBUG to 0 (zero), the debug output is enabled and prints when tests are run using `composer run-test`.  The expectation is that debug output is not printed when DEBUG=0.

### Steps to reproduce

`DEBUG=0 composer run-test`

### Additional context

When `DEBUG=`, behavior acts as expected.

### WPGraphQL Version

1.13.9

### WordPress Version

6.1.1

### PHP Version

8.1

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [ ] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
closed by #2735
