### ISSUE TITLE
Documentation and application validation do not match

### ISSUE THREAD

**Issue by brokentone** [wp-graphql/wp-graphql#2754]
### Description

The documentation lists `graphql_plural_name` as optional: https://www.wpgraphql.com/docs/custom-post-types

> graphql_plural_name | string | (optional): camel case string with no punctuation or spaces. Needs to start with a letter (not a number).

>     $args['graphql_plural_name'] = 'documents'; # Don't set, and it will default to `all${graphql_single_name}`, i.e. `allDocument`.

However, this validation step throws errors pretty aggressively if it is not set:
https://github.com/wp-graphql/wp-graphql/blob/ead0acb6d9ea1ad3eaaf6a36850c33ba0720bb6a/src/WPGraphQL.php#L622-L630

I'm not sure which should be updated, documentation or the validation, but they are currently in conflict with one another.

### Steps to reproduce

Create a post type like so:

```
add_action( 'init', function() {
   register_post_type( 'docs', [
      'show_ui' => true, # whether you want the post_type to show in the WP Admin UI. Doesn't affect WPGraphQL Schema.
      'labels'  => [
        //@see https://developer.wordpress.org/themes/functionality/internationalization/
        'menu_name' => __( 'Docs', 'your-textdomain' ), # The label for the WP Admin. Doesn't affect the WPGraphQL Schema.
      ],  
      'hierarchical' => true, # set to false if you don't want parent/child relationships for the entries
      'show_in_graphql' => true, # Set to false if you want to exclude this type from the GraphQL Schema
      'graphql_single_name' => 'document',
      'public' => true, # set to false if entries of the post_type should not have public URIs per entry
      'publicly_queryable' => true, # Set to false if entries should only be queryable in WPGraphQL by authenticated requests
   ] );
} );
```

And watch all graphQL queries return a fatal error.

### WPGraphQL Version

1.14.0-rc

### WordPress Version

6.1.1

### PHP Version

8.2.3

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
@brokentone thanks for the detailed issue with steps to reproduce! Will check this out and see what my thoughts are re: 

> I'm not sure which should be updated, documentation or the validation, but they are currently in conflict with one another.

My hunch is that if `graphql_plural_name` is not set, but `graphql_single_name` is, we can use that value as the value for `graphql_plural_name` as a fallback. 

Not sure yet if that will have unintended side effects or not, but it seems like that was the intent based on the documentation, and perhaps we didn't finish that functionality (or test it properly 🤦🏻)
