### ISSUE TITLE
Cannot return a resource for an external URI

### ISSUE THREAD

**Issue by youdianfan** [wp-graphql/wp-graphql#2759]
### Description

I defined a Type through the Custom Post Type plug-in and overwrote Slug. The error is as follows through nodeByUri query.

![image](https://user-images.githubusercontent.com/27018910/224229944-5ada36f0-6f44-4810-b509-e357331b55fc.png)

This is the CTP setup
![image](https://user-images.githubusercontent.com/27018910/224230317-6ebbe6d7-ea72-4a82-961d-8a26366f210f.png)

### Steps to reproduce

```
query GetNodeByUri($uri: String!) {
    node: nodeByUri(uri: $uri) {
      ...NodeByUri
    }
  }
  fragment NodeByUri on UniformResourceIdentifiable {
    __typename
    uri
    id
    ...DatabaseIdentifier
    ...ContentType
    ...User
    ...TermNode
    ...ContentNode
    ...MediaItem
    ...Page
  }
  fragment DatabaseIdentifier on DatabaseIdentifier {
    databaseId
  }
  fragment MediaItem on MediaItem {
    id
    mimeType
  }
  fragment ContentType on ContentType {
    name
    isFrontPage
    # This is currently broken. The home page (blog page) can not be
    # resolved when set to a custom page until the below issue is resolved.
    # Link: https://github.com/wp-graphql/wp-graphql/issues/2514
    isPostsPage
  }
  fragment Page on Page {
    isFrontPage
    isPostsPage
  }
  fragment TermNode on TermNode {
    isTermNode
    slug
    taxonomyName
  }
  fragment ContentNode on ContentNode {
    isContentNode
    slug
    contentType {
      node {
        name
      }
    }
    template {
      templateName
    }
  }
  fragment User on User {
    name
    userId
    databaseId
  }
```

### Additional context

![image](https://user-images.githubusercontent.com/27018910/224229944-5ada36f0-6f44-4810-b509-e357331b55fc.png)

### WPGraphQL Version

1.14.0

### WordPress Version

6.1.1

### PHP Version

7.4.33

### Additional enviornment details

![image](https://user-images.githubusercontent.com/27018910/224230890-3b52b895-ce03-429e-bfce-4c2045206ca4.png)

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [ ] Yes
- [X] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by youdianfan** [comment]
Front-end frame usage [faustjs](https://faustjs.org/) ,The WordPress domain is` www.a.com`. The front end is` www.b.com`

**Comment by youdianfan** [comment]
![image](https://user-images.githubusercontent.com/27018910/224234528-7a67ff9d-7476-4150-bf4e-ebce48c0c4b3.png)

Cannot be queried through the full link

**Comment by youdianfan** [comment]
![image](https://user-images.githubusercontent.com/27018910/224234658-3005b09a-9c85-4eb1-8ea4-7051313a87a3.png)

### Delete the domain name, you can query, how to solve this problem?

**Comment by justlevine** [comment]
Hey @youdianfan ,

Throughout the plugin, URIs are _relative_ and do not include the domain name (unlike URLS). 

What you're describing is expected behavior.

**Comment by jasonbahl** [comment]
It should work with full urls as well, as long as the domain is the same domain the WordPress admin can be accessed from. If it's the domain the headless front-end is accessed from, or any other domain other than the domain WordPress admin is accessed from then yes, this is expected behavior.
