### ISSUE TITLE
Support the user's toolbar preference in the viewer model

### ISSUE THREAD

**Issue by blakewilson** [wp-graphql/wp-graphql#2764]
### What problem does this address?

Allows headless frontend apps who may have created a custom admin bar implementation for the frontend and want to dynamically show or hide it.

### What is your proposed solution?

Add a `isToolbarVisible` property to the `viewer`.

**Comment by josephfusco** [comment]
Released in https://github.com/wp-graphql/wp-graphql/pull/2788
