### ISSUE TITLE
The author URL always returns null.

### ISSUE THREAD

**Issue by ikhsanalatsary** [wp-graphql/wp-graphql#2766]
### Description

I added a URL to the profile page, but it doesn't reflect when querying it using WPGraphQL Playground.  As workaround, I requested via WP Rest API, and the result is fine. In conclusion, this is a specific bug in WPGraphQL.
<img width="413" alt="image" src="https://user-images.githubusercontent.com/5897415/227107696-25f09bb1-93f1-4c2c-b9bf-cc5b06c094de.png">

### Steps to reproduce

1. simple query users:
```graphql
{
  users {
    nodes {
      id
      name
      url
    }
  }
}
```

2. Actual results:
```json
{
  "data": {
    "users": {
      "nodes": [
        {
          "id": "dXNlcjox",
          "name": "Abdul Fattah Ikhsan",
          "url": null
        }
      ]
    }
  },
  "extensions": {
    "debug": [],
    "queryAnalyzer": {
      "keys": "5f4a6413d16e4a64590857a011a1f541cd56c8a95968328decf92f17cbe831c5 graphql:Query list:user dXNlcjox",
      "keysLength": 97,
      "keysCount": 4,
      "skippedKeys": "",
      "skippedKeysSize": 0,
      "skippedKeysCount": 0,
      "skippedTypes": []
    }
  }
}
```

3. Expected result:
```json
{
  "data": {
    "users": {
      "nodes": [
        {
          "id": "dXNlcjox",
          "name": "Abdul Fattah Ikhsan",
          "url": "https://linktr.ee/ikhsan.dev"
        }
      ]
    }
  },
  "extensions": {
    "debug": [],
    "queryAnalyzer": {
      "keys": "5f4a6413d16e4a64590857a011a1f541cd56c8a95968328decf92f17cbe831c5 graphql:Query list:user dXNlcjox",
      "keysLength": 97,
      "keysCount": 4,
      "skippedKeys": "",
      "skippedKeysSize": 0,
      "skippedKeysCount": 0,
      "skippedTypes": []
    }
  }
}
```

### Additional context

1. Playground:
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/5897415/227108593-db4e9014-3e7e-4ab1-92d6-a070bb23d7c8.png">

2. Active Plugins
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/5897415/227109119-c1d29e8d-55e6-4df7-978e-3a474f064328.png">

### WPGraphQL Version

1.14.0

### WordPress Version

6.1.1

### PHP Version

8.0.26

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [x] Yes
- [X] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Hey @ikhsanalatsary 

Can you please confirm:
1. You see the url when you run the query as an authenticated user (tap your profile pic next to the Play button so a green dots turns on).
2. You can see the url unauthenticated, _if the user has a published post_. Otherwise it's a user, not an author, and the `url` is this hidden for unauthenticated requests.

**Comment by ikhsanalatsary** [comment]
I confirm, you're right, but Why do I need authentication first to get the URL? From my understanding, it should be public. I've checked with WP Rest API, and it shows up and public.

**Comment by justlevine** [comment]
Confirmed as a bug in triage. `URL` should definitely be public, and others can be audited against what the REST API does.

(note to self: `URL` !== `URI`. The former is a url supplied by the user, the URI is their internal wp link).
