### ISSUE TITLE
Custom post type filter by slug is different to returned slug

### ISSUE THREAD

**Issue by epndavis** [wp-graphql/wp-graphql#2767]
### Description

Slug returned from custom post type is different to the slug needed to filter for that post if `permalink` is changed.

Expect: Setting `permalink` to `/blog/%post_name%/` and created a custom post type `Articles` the filter for all articles returns that articles slug, when using that slug to filter for a single article I would get that article back in return. I would expect both slugs to be the same.

Happened: The articles returned slug `my-article` however I needed to add `/blog/my-article/` to be able to use the slug filter for a single article.

### Steps to reproduce

1. Set permalink custom structure to `/blog/%postname%/`
2. Add the custom post type to functions.php
```
register_post_type( 'articles', [
        'show_ui' => true, # whether you want the post_type to show in the WP Admin UI. Doesn't affect WPGraphQL Schema.
        'labels'  => [
          //@see https://developer.wordpress.org/themes/functionality/internationalization/
          'menu_name' => __( 'Articles' ), # The label for the WP Admin. Doesn't affect the WPGraphQL Schema.
        ],
        'hierarchical' => false, # set to false if you don't want parent/child relationships for the entries
        'show_in_graphql' => true, # Set to false if you want to exclude this type from the GraphQL Schema
        'graphql_single_name' => 'article', 
        'graphql_plural_name' => 'articles', # If set to the same name as graphql_single_name, the field name will default to `all${graphql_single_name}`, i.e. `allDocument`.
        'public' => true, # set to false if entries of the post_type should not have public URIs per entry
        'publicly_queryable' => true, # Set to false if entries should only be queryable in WPGraphQL by authenticated requests
     ] );
```
3. Create an article `my-article`
4. Query for all articles and single article by slug
```
query NewQuery {
  articles {
    edges {
      node {
        id
        title
        uri
        slug
      }
    }
  }
  article(id: "my-article", idType: SLUG) {
    title
  }
}
```

### Additional context

![wpgraphql-slug-example](https://user-images.githubusercontent.com/47059262/227360341-5570d522-30c1-4937-96af-8c76e8d7d143.png)

### WPGraphQL Version

1.14.0

### WordPress Version

6.1.1

### PHP Version

8.1.13

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [X] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
@epndavis I believe this was resolved in WPGraphQL v1.14.3 (https://github.com/wp-graphql/wp-graphql/releases/tag/v1.14.3). 

I'm going to close this, but if you believe it's still an issue on the latest version of WPGraphQL, please open a new issue and reference this one for context. 

Thanks! 🙏🏻
