### ISSUE TITLE
Error in graphql IDE: GraphQL introspection is not allowed

### ISSUE THREAD

**Issue by sinapirani** [wp-graphql/wp-graphql#2768]
### Description

when I open graphql IDE I get this error in console and nothing can be loaded:
 GraphQL introspection is not allowed, but the query contained __schema or __type
    at new t (app.js?ver=029d819e2c38c9f70120:30:39347)

### Steps to reproduce

1. open graphql IDE

### WPGraphQL Version

 1.14.0

### WordPress Version

6.1.1

### PHP Version

8

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by alexkey89** [comment]
same exact issue just now

**Comment by ryntab** [comment]
You can clear your cache or application cookies. Once you login in again the issue should be resolved.

**Comment by justlevine** [comment]
Hey @sinapirani and @alexkey89 , did clearing your Application Cache solve this for you or are you still struggling with this issue?

**Comment by jasonbahl** [comment]
Closing this as there's not been any response to validate this is still an issue
