### ISSUE TITLE
Can't get ACF Data in gatsby graphql

### ISSUE THREAD

**Issue by Dev284** [wp-graphql/wp-graphql#2771]
### Description

![Screenshot 2023-03-27 at 3 12 34 PM](https://user-images.githubusercontent.com/110807735/227906814-8b7d1818-6c9f-4bc6-82b5-b79f187048c6.png)
![Screenshot 2023-03-27 at 3 13 09 PM](https://user-images.githubusercontent.com/110807735/227906854-e2a2c857-c87a-4377-9705-b8e9196ece5b.png)

Can't get ACF Data in gatsby graphql, but can access data in WordPress graphql cli
Gatsby version: 5.6.0
PHP version: 7.4
Advanced Custom Fields PRO Version: 6.0.6
WPGraphQL for Advanced Custom Fields Version: 0.6.1

### Steps to reproduce

I have created a new field but facing same issues.
We are testing this in our existing project.

### WPGraphQL Version

1.14.0

### WordPress Version

6.1.1

### PHP Version

7.4.33

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [ ] Yes
- [X] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Sounds like the issue is either with https://github.com/wp-graphql/wp-graphql-acf or http://github.com/gatsbyjs/wp-gatsby, and the ticket should probably be moved there.

@jasonbahl @TylerBarnes ?

**Comment by Dev284** [comment]
My mistake it should be asked on wp-graphql-acf repo.

Can i delete this question from here and ask there?

@justlevine

**Comment by Dev284** [comment]
> Sounds like the issue is either with [wp-graphql-acf](https://github.com/wp-graphql/wp-graphql-acf) or gatsby-source-wordpress, and the ticket should probably be moved there. @jasonbahl @TylerBarnes ?
> 
> @Dev284 are you also using WPGatsby?

Yes I am using WPGatsby version 2.3.3

**Comment by Dev284** [comment]
I raised this question here https://github.com/wp-graphql/wp-graphql-acf/issues/352
