### ISSUE TITLE
Can not query users by role publicly 

### ISSUE THREAD

**Issue by ryntab** [wp-graphql/wp-graphql#2772]
### Description

It doesnt seem possible to publicly query users by a role, even if all users are made publicly accessible.

### Steps to reproduce

```
query users {
  users(where: {roleIn: VENDOR}) {
    edges {
      node {
        id
        name
        nicename
      }
    }
  }
}
```
The result is `"Sorry, you are not allowed to filter users by role."`

### WPGraphQL Version

1.14.0

### WordPress Version

Version 6.1.1

### PHP Version

PHP 7.4

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
> even if all users are made publicly accessible.

@ryntab how are you making the users 'publicly accessible'? WPGraphQL relies on WP's `list_users` capability, (although a bit more permissive in some places, to allow for getting public author data via the same user connection).

**Comment by ryntab** [comment]
Ok, I see what you are saying. So my issue is not related to WPGraphQL at all, it's just not possible to query users by role without the proper permissions in WordPress.

**Comment by justlevine** [comment]
Hey @ryntab based on your response above, I'm going to go ahead and close this. 

If you're still running into issues with querying users after changing the permissions necessary to make users public, please comment back here with a replicable test case, and we'll happily reopen this.
