### ISSUE TITLE
Taxonomy terms returned incorrectly

### ISSUE THREAD

**Issue by thecodeassassin** [wp-graphql/wp-graphql#2774]
### Description

When retrieving terms for a taxonomy, you are allowed to pass an array of TaxonomyEnum but this doesn't work correctly and it only retrieves a single taxonomy's terms.

### Steps to reproduce

Query:

query 

```graphql
query getAllTaxonomiesAndTerms {
  terms(where: {taxonomies: [META, MISC, CLASS, NUM]}) {
    nodes {
      id
      name
      slug
      taxonomyName
    }
  }
}
```

Expected result: All taxonomy terms of META, MISC etc

Actual result: Only taxonomy terms of one of these taxonomies.

### WPGraphQL Version

14.0

### WordPress Version

6.1.1

### PHP Version

8.2

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
closed by #2775
