### ISSUE TITLE
Posts not updating and Interface field Connection.nodes expects type [Node!]! 

### ISSUE THREAD

**Issue by fantaz-st** [wp-graphql/wp-graphql#2787]
### Description

Updated WPGraphQL from 1.12.0 to latest and now when updating old posts the updates don't show up on Next JS frontend and the post can't be revalidated. No errors are shown in the console.
In development mode a "failed to load static props" error is thrown.
Upon entering GraphiQL IDE in wordpress, with an empty query composer a set of errors is shown:

```
{
  "errors": [
    "Interface field Connection.nodes expects type [Node!]! but BlockEditorContentNodeConnection.nodes is type [BlockEditorContentNode!]!.",
    "Interface field Edge.node expects type Node! but BlockEditorContentNodeConnectionEdge.node is type BlockEditorContentNode!."
  ]
}
```

The same post cannot be queried. A simple query throws a postBy as null.

query postData {
    postBy(slug: "#someslug") {
      title
     id
  }
}

I have several other WPGraphQL plugins, switching them off the errors remain.
Downgrading WPGraphQL back to 1.12.0 fixes the problem. All other plugins are of the latest version.

### Steps to reproduce

Update to latest WpgraphQL

### WPGraphQL Version

1.14.0

### WordPress Version

6.2

### PHP Version

7.4.33

### Additional enviornment details

nextjs
WP GraphQL Gutenberg
WPGraphQL for Advanced Custom Fields
WPGraphQL Tax Query

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by PetterEck** [comment]
We were experiencing the same issue after updating from 1.12.2 to 1.14.3. It seems to be incompatible with wp-graphql-gutenberg 0.3.11 (which we were running before) but after updating to the latest release of the plugin WP GraphQL Gutenberg it seems to work better https://github.com/pristas-peter/wp-graphql-gutenberg/tree/v0.4.1 . I think it is a compatability issue after all

**Comment by justlevine** [comment]
@PetterEck is correct. Support for WPGraphQL 1.13+ was added in [WPGraphQL Gutenberg v0.4.0](https://github.com/pristas-peter/wp-graphql-gutenberg/releases/tag/v0.4.0). If you continue to have issues please make sure you're using the latest version of any extensions - and that those extensions have been updated for compatibility with recent WPGraphQL versions.
