### ISSUE TITLE
featuredImage Argument #2 ($haystack) must be of type array, string given

### ISSUE THREAD

**Issue by ol1s** [wp-graphql/wp-graphql#2797]
### Description

After upgrading to PHP 8 can no longer query `featuredImage`

### Steps to reproduce

```
{
  posts(first: 1) {
    nodes {
      uri
      featuredImage {
        node {
          sourceUrl(size: LARGE)
        }
      }
    }
  }
}
```

```
{
  "errors": [
    {
      "debugMessage": "in_array(): Argument #2 ($haystack) must be of type array, string given",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 5,
          "column": 7
        }
      ],
      "path": [
        "posts",
        "nodes",
        0,
        "featuredImage"
      ]
    }
  ],
  "data": {
    "posts": {
      "nodes": [
        {
          "uri": "/news/2023/03/test-slug",
          "featuredImage": null
        }
      ]
    }
  },
  "extensions": {
    "debug": [],
    "queryAnalyzer": {
      "keys": "76151bf98e20d879c27da29d22a7bac294b8e9fbdf1326a7e40afa0db60e01aa graphql:Query list:post cG9zdDoyOTA0",
      "keysLength": 101,
      "keysCount": 4,
      "skippedKeys": "",
      "skippedKeysSize": 0,
      "skippedKeysCount": 0,
      "skippedTypes": []
    }
  }
}
```

### WPGraphQL Version

1.14.0

### WordPress Version

6.1.2

### PHP Version

8.0.28

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
@ol1s I'm unable to reproduce this on PHP 8.1.9 and latest release of WPGraphQL. 

![CleanShot 2023-04-25 at 09 41 40](https://user-images.githubusercontent.com/1260765/234330798-8afec415-7d3f-4968-9c40-a030e3d6c3ff.png)

Perhaps there's an issue with a plugin?

Could you maybe try de-activating some plugins to see if the behavior goes away? That might help identify the problem. 

Either that, or see if you can reproduce it in a clean WordPress + WPGraphQL install, and if you can, provide us with clear steps to reproduce.
