### ISSUE TITLE
Introduce Model Layer

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#280]
It's common practice in GraphQL to separate the Schema/Type definitions and the resolvers. 

I think we should introduce a Model layer would help separate the Schema and the actual population of Data. 

This would allow the Schema to focus on _defining_ the contract between the Client and the Server and the Model to focus on _fulfilling_ that contract.

This would also centralize any logic we have about how things are resolved. 

This was the original reasoning behind the `DataSource` that currently exists. . .but we've just been inconsistent in utilizing it to its potential

**Comment by CodeProKid** [comment]
I'm curious if this is something you still really want to do @jasonbahl

**Comment by CodeProKid** [comment]
Reopening this as it now has a clearer vision. Creating smaller issues for each object type that needs a model.

**Comment by jasonbahl** [comment]
Closed by #683 (and like 100 other stories)
