### ISSUE TITLE
Conflict Between Custom Post Type and Media Slugs

### ISSUE THREAD

**Issue by tjdunklee** [wp-graphql/wp-graphql#2800]
### Description

We recently ran into an interesting issue with WPGraphQL that only occurs in plugin versions equal or greater to v1.14.0. It seems like the media item slugs and the custom post type slugs are conflicting. This means if they have the same slug and you try and query for a specific post of the custom post type, WPGraphQL returns null even though the post exists. Please note that this only happens when the media item is uploaded first!

Let me know if you need to connect about this, I could show it live or provide a screen recording. Thanks for your help!

### Steps to reproduce

1. Make sure permalinks are set to "Post name"
2. Create a custom post type called `products`
3. Upload an image with the filename of `taco-surprise-cups.jpg`
    > You can use the supplied image attached below
5. Create a post with a title of "Taco Surprise Cups"
6. Try to query your product post with this:
```
query {
  product(id: "taco-surprise-cups", idType: SLUG) {
    title
    slug
  }
}
```
7. Notice it returns null instead of the post data.

**NOTE:** If you delete the image, the above query will work fine.

## Image Asset
![taco-surprise-cups](https://user-images.githubusercontent.com/1714785/234346551-430daa65-bf95-4d86-9862-0f1fc9441757.jpg)

### Additional context

We solved this bug on our live sites by rolling the plugin back to v1.13.10.

## Screenshots

Media Item - https://capture.dropbox.com/kwGXlI23PU6sIv86
Product Post - https://capture.dropbox.com/OoZRBdzVMXnUH6Ve
WPGraphQL Query - https://capture.dropbox.com/nUA26NvICD7N5sWE

### WPGraphQL Version

v1.14.2

### WordPress Version

6.2

### PHP Version

8.1.9

### Additional enviornment details

This was a reduced test case, so it was just the Twenty Twenty-Three theme with no other plugins other than WPGraphQL.

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
@tjdunklee can you see if the change added here: https://github.com/wp-graphql/wp-graphql/pull/2799/files#diff-0ce1667ecf9df36ddd558f3ea8c6227530fdb0fe6aa9eb625950f3df60002f6eR33

Fixes this issue for you?

I'm also going to try and reproduce locally.

**Comment by jasonbahl** [comment]
@tjdunklee ok, so the fix linked above does NOT seem to fix it like I thought it might.

This seems like kind of an edge case / dirty-data situation, but I was able to reproduce it. 

If I publish a product with the slug of `taco-surprise-cups` then upload the image, WordPress is smart enough to prevent the duplicate slugs, and my image gets the slug of `taco-surprise-cups-2`, so WordPress prevents the duplicate slug collision, which is nice. 

However, if I delete both the post and image and start with fresh data, and upload the image first, I have an image with a slug of `taco-surprise-cups`. Then if I publish a product, it assigns the slug `taco-surprise-cups` to the product, instead of `taco-surprise-cups-2` like it did when uploading an image after having a post created. 

And now I'm able to reproduce and query for the custom post type by slug and not get the result I expect: 

![CleanShot 2023-04-25 at 14 46 11](https://user-images.githubusercontent.com/1260765/234399642-d4519c3f-3771-4c16-9415-d8e6f6fd2ae5.png)

I think I've identified the bug. Working on a PR.

**Comment by tjdunklee** [comment]
@jasonbahl - Thank you for jumping on this so quickly! I also tried your fix from earlier today and it sadly didn't solve the issue. 

You are definitely right that the order of operation needs to be exact for this to happen, but we did recently have it happen on a fairly large WordPress site and it caused quite a few 404 errors on our single post pages. It's interesting it didn't happen before v1.14.0.

**Comment by jasonbahl** [comment]
ya, we did some refactoring of the NodeResolver class, and some regressions apparently snuck through. 

It's a bummer that some things like this slipped through, but I'm glad we're able to identify these edge cases and provide better test coverage to prevent regressions like this in the future! 

Thanks for reporting this and helping make WPGraphQL better for everyone 🙌🏻

**Comment by tjdunklee** [comment]
> Thanks for reporting this and helping make WPGraphQL better for everyone 🙌🏻

Thank you for all your work on this project! It has allowed us to use WordPress in ways I never thought I would.

**Comment by jasonbahl** [comment]
@tjdunklee can you confirm the changes in this PR fix things for you? https://github.com/wp-graphql/wp-graphql/pull/2801

I wrote a test that failed and now passes, but would love your confirmation as well 🙏🏻

**Comment by tjdunklee** [comment]
@jasonbahl - Sorry for the delay, I had to get some composer issues sorted. I did test your fix and I can confirm that it has resolved the issue. Thanks for much for jumping on this quickly, we are looking forward to a release.

**Comment by jasonbahl** [comment]
@tjdunklee thanks for confirming! will work on prepping a release today

**Comment by ryanhuffman1** [comment]
Thanks for responding to this so quickly, Jason! We really appreciate your help.
