### ISSUE TITLE
WPGraphQL issue with custom post types and Unicode slugs

### ISSUE THREAD

**Issue by metawise** [wp-graphql/wp-graphql#2804]
### Description

Hello everyone,

I'm having some trouble retrieving custom posts with Unicode slugs using WPGraphQL. Specifically, I'm using custom post types that have Unicode slugs and trying to retrieve them using the nodeByUri query. Unfortunately, this query is returning null and I'm not sure what the issue could be.

I was wondering if anyone else has experienced similar issues with WPGraphQL and custom post types with Unicode slugs. If so, could you please share how you were able to resolve the issue? Any help or advice would be greatly appreciated.

Thank you in advance!

### Steps to reproduce

1. WPGraphQL IDE:  "шинэ" could be any unicode slug under any custom post type. In my case it's called "destinations"

`query NewQuery {
  nodeByUri(uri: "/destinations/шинэ/") {
    __typename
    ... on Page {
      id
      title
      uri
    }
    ... on Post {
      id
      title
      uri
    }
    ... on Destination {
      id
    }
  }
  destinations {
    nodes {
      uri
    }
  }
}`

2. Result always return null. If you use regular latin character slugs. It returns a post without issue. Not working with UNICODE!

### Additional context
![Screenshot 2023-04-29 at 11 44 42 PM](https://user-images.githubusercontent.com/14798623/235338874-bd5abc79-9d7f-47e8-ac38-784ac477496e.jpg)

### WPGraphQL Version

1.14.3

### WordPress Version

6.2

### PHP Version

PHP 8.1.9

### Additional enviornment details

I'm using Custom Post Type UI for custom post type. 

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by metawise** [comment]
![](https://files.slack.com/files-pri/T3PDM1KRC-F055CTMQ5AA/screenshot_2023-04-29_at_11.44.42_pm.jpg)

**Comment by metawise** [comment]
![Screenshot 2023-04-29 at 11 44 42 PM](https://user-images.githubusercontent.com/14798623/235338793-b7e0a2e1-7ea5-402d-a2c6-d0fee23cdd41.jpg)

**Comment by metawise** [comment]
I have tried by changing mysql db's charsets to utf8mb4_general_ci and added following to my config. define('DB_COLLATE', 'utf8mb4_general_ci');

Also, I have tried to forcefully decode the slugs to readable as it is shown below screenshot.

`
add_filter('wp_unique_post_slug', 'modify_post_slug', 10, 6);
function modify_post_slug($slug, $post_ID, $post_status, $post_type, $post_parent, $original_slug)
{
  $new_slug = $slug;
  return urldecode($new_slug);
}
`

None of them worked to pull the content out. So we should update the core to load Unicode slugs. 


![Screenshot 2023-04-30 at 2 19 34 PM](https://user-images.githubusercontent.com/14798623/235338894-651f79b7-eba4-4116-a68a-31029da7e857.jpg)

**Comment by metawise** [comment]
Ended up resolving the issue with following codes:

`add_filter('wp_unique_post_slug', 'modify_post_slug', 10, 6);
function modify_post_slug($slug, $post_ID, $post_status, $post_type, $post_parent, $original_slug)
{
  return urldecode($slug);
}

add_filter('graphql_RootQuery_fields',  function ($fields) {
  if (isset($fields['nodeByUri'])) {
    $fields['nodeByUri']['resolve'] = function ($root, $args, $context) {
      if (empty($args['uri'])) return null;
      if (get_page_by_path($args['uri'])) {
        $extra_query_vars['post_type'] = 'page';
      } else {
        $slug = end(array_filter(explode('/', $args['uri'])));
        global $wpdb;
        $query = "SELECT ID FROM $wpdb->posts WHERE post_name = %s AND post_status = 'publish' LIMIT 1";
        $prepared_query = $wpdb->prepare($query, $slug);
        $post_id = $wpdb->get_var($prepared_query);

        if ($post_id) {
          return $context->get_loader('post')->load_deferred($post_id);
        }
      }
      return $context->node_resolver->resolve_uri($args['uri'], $extra_query_vars);
    };
  }
  return $fields;
}, 20);`

**Comment by lwm-as** [comment]
Having the same issue. 
This also happens when querying for regular posts and pages using "idType: SLUG" and "idType: URI". 

The "solution" that worked was to downgrade to version 1.14.2, so the issue seems to be with the latest update. 
Is there any ETA on a possible solution for this issue? And should we implement the workaround in the meantime?

**Comment by ShahriarKh** [comment]
I also faced the same issue after upgrading to 1.14.3. had to downgrade to 1.14.1 ...

**Comment by benknight** [comment]
We had the same issue on vietnamcoracle.com, causing 404s to appear on our site for any URL with a special character in it, which had the unfortunate effect of many pages getting removed from Google index causing a huge traffic slump.

Instead of downgrading the plugin, I instead use the official WP Rest API to query for posts based on a slug, and then pass the raw database ID into the GraphQL query for the content node.

**Comment by jasonbahl** [comment]
Hello, I've [opened a PR ](https://github.com/wp-graphql/wp-graphql/pull/2851) that resolves this issue. 

Would love if ya'll could confirm it fixes things for your use cases 🙏🏻

**Comment by ShahriarKh** [comment]
Thank you 🔥. I finally upgraded to the latest version after 2 weeks and can confirm this works (also some specific posts had issues and the new version fixed that)
