### ISSUE TITLE
500 internal Server error if query-depth_max left empty

### ISSUE THREAD

**Issue by dgallardox** [wp-graphql/wp-graphql#2809]
### Description

In the settings of GraphQL, you can set a 'max depth to allow for GraphQL Queries' integer. If you remove it and leave it empty, even if query depth limiting is not enabled, it causes a 500 internal server error. The GraphQL endpoint will return 500 and IDE will be infinite loading.

![Screenshot 2023-05-09 at 2 55 47 PM](https://github.com/wp-graphql/wp-graphql/assets/101141475/d37cc86e-b533-4458-8bf4-231e5c070e40)
![Screenshot 2023-05-09 at 2 55 42 PM](https://github.com/wp-graphql/wp-graphql/assets/101141475/93756ca4-1a6f-4d0f-b717-c048ee64faf2)

### Steps to reproduce

1. go to graphql settings
2. Remove all input from 'max depth to allow for graphql queries' field
3. save
4. attempt to load IDE or request data from graphql endpoint
5. check WordPress error logs

### WPGraphQL Version

1.14.3

### WordPress Version

6.2

### PHP Version

8.0

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
I was able to reproduce this and have a PR coming to fix it
