### ISSUE TITLE
get the user Contact Info fields

### ISSUE THREAD

**Issue by alexRicc2** [wp-graphql/wp-graphql#2815]
### What problem does this address?

In the current version I did not find a way to get the user's contact info fields, if there's a way I apologize for this issue, the solution I found it is to install ACF and WPGRAPG for ACF and add new social fields in user, but I think it should be possible to get with standard WPgraphQL

### What is your proposed solution?

IMO the ideal solution it is making it possible to get the contact info fields directly in the users query, something like in the screenshot 
![image](https://github.com/wp-graphql/wp-graphql/assets/81180853/74688404-4c7e-4161-9b4a-240461426980)

### Additional Context

![image](https://github.com/wp-graphql/wp-graphql/assets/81180853/19f98d39-17d9-45c8-8105-2cceb28cf5f8)

**Comment by jasonbahl** [comment]
@alexRicc2 WPGraphQL for ACF is the correct way to bridge ACF Field Groups and Fields to WPGraphQL. 

There are many custom field solutions out there and they all have different opinions on how data is stored, returned and managed. 

WPGraphQL cannot / will not be able to support every possible meta box / custom field solution out there, thus "bridge" plugins such as WPGraphQL for ACF exist to "bridge" the functionality of ACF with WPGraphQL.

There is a new version of WPGraphQL for ACF coming soon. It's in beta now. You can check it out here: https://github.com/wp-graphql/wpgraphql-acf
