### ISSUE TITLE
updateUser mutation where users can edit themselves

### ISSUE THREAD

**Issue by Thomashh2k** [wp-graphql/wp-graphql#2816]
### What problem does this address?

Currently  i am making a Online-Shop as a frontend to Wordpress. I understand that this method is only for users who have the capability 'edit_users'.

So that means a simple user or a customer from woocommerce cant edit themselves

### What is your proposed solution?

It would be really helpful if there could be an updateUser mutation where a user can edit themselves

**Comment by justlevine** [comment]
So in GraphiQL, you're not running the mutation as an authenticated user (you toggle this by clicking on the user avatar between the ▶️ and `Prettify` button, so a green dot appears. I'm assuming thats the same issue in your frontend app.

You can confirm by running ` query { viewer { databaseId } }` and see if an actual user comes back.

As far as `updateCustomer` goes, sounds like the customer needs to be a logged-in user (i.e. not a guest customer) if they want to edit their account, so the same method of authentication will solve it for you.

**Comment by Thomashh2k** [comment]
Ohh i didn't know that with this toggle. Firstly i had many problems that were based on misconfiguration in Wordpress and some problems in my code.

Sorry for wasting youre time

**Comment by justlevine** [comment]
No worries, feel free to open up a discussion or ask in the community Slack channel if you run into any other issues 😎
