### ISSUE TITLE
 wpgraphql when the slug is persian give me null result

### ISSUE THREAD

**Issue by AliNaraghiA** [wp-graphql/wp-graphql#2847]
### Description

I am sure i have a post with slug:سلام/this is works with English and number only .
query POST_WITH_SLUG1 {
  postBy(slug: "سلام") {
    postId
    id
    databaseId
    title
    slug
  }
}     

>>>
{
  "data": {
    "postBy": null
  },
  "extensions": {
    "debug": [
      {
        "type": "DEBUG_LOGS_INACTIVE",
        "message": "GraphQL Debug logging is not active. To see debug logs, GRAPHQL_DEBUG must be enabled."
      }
    ]
  }
}

### Steps to reproduce

1. find post with correct slug

### WPGraphQL Version

last

### WordPress Version

last

### PHP Version

7.4

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [ ] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by AliNaraghiA** [comment]
also i fixed: support UTF-8 encoding

**Comment by jasonbahl** [comment]
@AliNaraghiA is this a valid issue still or did you fix it? I'm not sure based on your last comment.

**Comment by AliNaraghiA** [comment]
No, I still have a problem. I can't call the post with the slug:

query PostBySlugEn($slug: ID!) {
  post(id: $slug, idType: SLUG) {
    title
    content
    postId
    featuredImage {
      node {
        sourceUrl
        altText
      }
    }
  }
}

---------------------------------

{
  "slug": "سلام"
}

---------------------------
{
  "data": {
    "post": null
  },
--------------------
But I have a post with {slug: سلام} in WordPress posts.

**Comment by AliNaraghiA** [comment]
ALSO  i can see slug : with this code 👍 
https://github.com/wp-graphql/wp-graphql/issues/2804#issuecomment-1528961744
{
  "data": {
    "posts": {
      "nodes": [
        {
          "title": "فارسی",
          "slug": "فارسی",
          "id": "cG9zdDo0Mzg="
        },

**Comment by jasonbahl** [comment]
@AliNaraghiA I opened a PR that resolves this. Would love if you could confirm the fix for your use cases 🙏🏻: https://github.com/wp-graphql/wp-graphql/pull/2851 :pr
