### ISSUE TITLE
GraphQL IDE not working on some sites on a multisite

### ISSUE THREAD

**Issue by mikeacre** [wp-graphql/wp-graphql#2850]
### Description

I have a multisite that runs content for a few sites. Each site used CPT, ACF, and WPGraphQl

Recently I have been having issues accessing the IDE, It just forever loads and displays an error in the console. 
```
Uncaught (in promise) Error: Internal server error
    at new t (app.js?ver=2663f617f0b84d60b40c:30:39347)
    at app.js?ver=2663f617f0b84d60b40c:30:78333
    at n (app.js?ver=2663f617f0b84d60b40c:30:32923)
    at app.js?ver=2663f617f0b84d60b40c:30:32848
    at new Promise (<anonymous>)
    at Object.then (app.js?ver=2663f617f0b84d60b40c:30:32814)
    at Object.next (app.js?ver=2663f617f0b84d60b40c:30:32933)
    at rh (app.js?ver=2663f617f0b84d60b40c:30:7097)
    at ih (app.js?ver=2663f617f0b84d60b40c:30:7610)
    at t.next (app.js?ver=2663f617f0b84d60b40c:30:8150)
```

I  created a new site to attempt to debug the issue here..

I took the following actions and checked the IDE at each step it broke on the last step.

Import CPT from site.. 
Import ACF, posts, pages and media from site
Added data into the posts and connected them correctly through ACF. 
At this point when I went back to check the IDE i was no longer loading again.

I can still query the WPGraphQL with no issues. 

I have tried disabling and reenabling everything.. checked names for spaces and even tried trashing all the posts and pages but still can not get the IDE to re appear.. I have no idea what is causing this error.

This is now happening on all my new sites.

### Steps to reproduce

Import from another site.. at some point it breaks. 

Disabling CPT and ACF does not bring IDE back. 

### Additional context

WP multisite 

### WPGraphQL Version

1.14.6

### WordPress Version

6.2.2

### PHP Version

7.4.13

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [X] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Hey @mikeacre 

1. Since this involves external plugins, can you please share the names and versions of _everything_ installed?
2. Can you enable WPGraphQL debugging, and then check and share [the network response](https://www.wpgraphql.com/docs/debugging#checking-the-response) when you load the IDE?
3. What exactly do you mean by import?

**Comment by mikeacre** [comment]
I'm not able to hit the play button as nothing loads 
![image](https://github.com/wp-graphql/wp-graphql/assets/23016911/accf0a6f-b8ec-4baf-bb5b-69cd190118cc)

I'm not seeing any errors within the network responses:
![image](https://github.com/wp-graphql/wp-graphql/assets/23016911/be3c8f50-990b-4fa6-bb07-bdcf82d13d57)

Also please note there are sites on this site where the IDE is loading.. but most of the newer ones will not. They do have the same and or similar ACF and CPT names.. i'm not sure if that's an issue but It doesn't seem to matter for most cases as long its on a different site. 

By Import I mean I have kind of a template for the sites so the ACF and CPT's pages ect are mostly started from the same thing so I will export from one site and import into the other. 

PLUGINS:
Advanced Custom Fields PRO	Version 6.1.7 by WP Engine | Auto-updates disabled
All-in-One WP Migration	Version 7.70 by ServMask (Latest version: 7.76) | Auto-updates disabled
Custom Post Type UI	Version 1.13.6 by WebDevStudios | Auto-updates disabled
Import and export users and customers	Version 1.18.2 by codection (Latest version: 1.22.5) | Auto-updates disabled
Jetpack by WordPress.com	Version 9.5.4 by Automattic (Latest version: 12.3) | Auto-updates disabled
Post Duplicator	Version 2.23 by Metaphor Creations (Latest version: 2.31) | Auto-updates disabled
Prevent Direct Access	Version 2.7.7 by BWPS (Latest version: 2.8.4) | Auto-updates disabled
Profile Extra Fields by BestWebSoft	Version 1.2.7 by BestWebSoft | Auto-updates disabled
TNTCLE-WP	Version 1.0.0 by TNTCLE | Auto-updates disabled
Widgets for Google Reviews	Version 7.2 by Trustindex.io <support@trustindex.io> (Latest version: 10.3) | Auto-updates disabled
WordPress Importer	Version 0.8 by wordpressdotorg (Latest version: 0.8.1) | Auto-updates disabled
WPGraphQL	Version 1.14.6 by WPGraphQL | Auto-updates disabled
WPGraphQL for Advanced Custom Fields	Version 0.4.0 by WPGraphQL, Jason Bahl | Auto-updates disabled
WPGraphQL JWT Authentication	Version 0.4.0 by WPGraphQL, Jason Bahl | Auto-updates disabled
WP Mail SMTP	Version 3.1.0 by WPForms (Latest version: 3.8.0) | Auto-updates disabled

**Comment by mikeacre** [comment]
Hey @justlevine I just tested a different theme and the IDE came back online.

It appears it is an issue with the theme I was using.. though I don't pay much attention because its headless.

**Comment by mikeacre** [comment]
Update: I discovered a missing PHP closing tag in the theme that when fixed it cleared the issue and the IDE is working as expected now. Sorry for the confusion.

**Comment by mikeacre** [comment]
Closing
