### ISSUE TITLE
Cursor pagination not working correctly with Post Types Order plugin

### ISSUE THREAD

**Issue by npazarkoskiktmk** [wp-graphql/wp-graphql#2852]
### Description

The cursor based pagination is not giving correct results when having an older record reorder to higher level with Post Types Order plugin (https://wordpress.org/plugins/post-types-order/).

All the newer records that are "under" the older reordered to higher level record are not displayed when using the `endCursor` from the reordered to higher level record.

### Steps to reproduce

1. Create a record
2. Create second record
3. Reorder the first record to higher level than the second
4. Try to query records after the `endCursor` of the first record (the second record will be not fetched)

### WPGraphQL Version

1.13.8

### WordPress Version

 6.2.2

### PHP Version

7.4.21

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [ ] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by npazarkoskiktmk** [comment]
Thanks for you reply.

I tried the code snippet for fixing the issue but the issue is still there.

In short words how the issue is happening is:
 - create record "A"
 - create record "B"
 - reorder "A" to be before "B" (higher in the list) using Post Types Order plugin
 - try to fetch first 1 record after "A" `endCursor` it gives empty array ("B" is not fetched)
 
 Anyhow,  I will try to replace Post Types Order plugin with another one.

**Comment by jasonbahl** [comment]
Hey if that snippet doesn't fix it we can re-open this. 

Could you share your queries that you've tried so I can attempt to reproduce?

**Comment by npazarkoskiktmk** [comment]
Sure.

Query:

query NewQuery($first: Int!, $after: String, $localeFilter: LanguageCodeFilterEnum!) {
  tests(
    first: $first
    after: $after
    where: {language: $localeFilter}
  ) {
    edges {
      node {
        id
      }
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}

Query vars:

{"first": 1,
  "after": " The End Cursor of 'A' record  (from my previous comment should go here",
  "localeFilter": "EN"}

**Comment by justlevine** [comment]
@npazarkoskiktmk what's adding that `language` argument?

Many multilingual plugins do unholy things to internal WordPress queries, similarly to how Post Types Order works. And most WPGraphQL extensions for those multilingual plugins rely on similar hooks as the one @jasonbahl suggested. It wouldn't be surprising if those hooks conflicted.

To confirm, you can disable _all your other WPGraphQL extensions_ and check to see if the query (i.e. Jason's snippet) is now correctly working. If so, re-enable the extensions one-by-one until the query stops working again, and you've found your conflict.

It's _possible_ that the conflict is easy to resolve by changing the snipped, but also a good chance that it may require a change to that specific extension.

**Comment by justlevine** [comment]
@npazarkoskiktmk I'm not sure I understood your response. Did you disable both `Polylang` and `WPGraphQL Polylang` and test your query without the `language` argument?

**Comment by npazarkoskiktmk** [comment]
Yes and the issue is still there.

The issue can be easy reproduced following the steps I have earlier commented.

**Comment by jasonbahl** [comment]
@npazarkoskiktmk when you de-activated Polylang and WPGraphQL for Polylang, did you modify your query to query without the language filter? Can you share more information about the queries you executed with only WPGraphQL and Post Types Order plugins active (and the linked snippet in place)?

I believe this is most likely a conflict with Polylang / WPGraphQL Polylang.

**Comment by justlevine** [comment]
Hey @npazarkoskiktmk , it's been a few weeks without a response so I'm going to go ahead and close this.

If you're still running into issues with Polylang / WPGraphQL for Polylang **disabled**, please share the updated replication case and we'll reopen this and investigate.
