### ISSUE TITLE
IDE not loading with WooGraphQL and WPGraphQL for ACF enabled

### ISSUE THREAD

**Issue by TheHatcheryLabs** [wp-graphql/wp-graphql#2858]
### Description

When having both WooGraphQL and WPGraphQL for ACF plugins enabled, the GraphQL IDE doesn't load and throws a JS error in console.

### Steps to reproduce

1. Enable ACF Pro 6.1.7, WooCommerce 7.8.2, WPGraphQL 1.14.7, WooGraphQL 0.14.1, WPGraphQL for ACF 0.6.1 
2. Go to GraphQL IDE
3. Editor is stuck with loading icon and throws a JS error in console

`app.js?ver=2663f617f0b84d60b40c:30 Uncaught (in promise) Error: Internal server error
    at new t (app.js?ver=2663f617f0b84d60b40c:30:39347)
    at app.js?ver=2663f617f0b84d60b40c:30:78333
    at n (app.js?ver=2663f617f0b84d60b40c:30:32923)
    at app.js?ver=2663f617f0b84d60b40c:30:32848
    at new Promise (<anonymous>)
    at Object.then (app.js?ver=2663f617f0b84d60b40c:30:32814)
    at Object.next (app.js?ver=2663f617f0b84d60b40c:30:32933)
    at rh (app.js?ver=2663f617f0b84d60b40c:30:7097)
    at ih (app.js?ver=2663f617f0b84d60b40c:30:7610)
    at t.next (app.js?ver=2663f617f0b84d60b40c:30:8150)`A

### Additional context

![Screenshot 2023-07-17 at 2 09 58 PM](https://github.com/wp-graphql/wp-graphql/assets/39837021/a3d2fb22-2202-4b40-be0c-bb7fdb9055e6)

### WPGraphQL Version

1.14.7

### WordPress Version

6.2.2

### PHP Version

8.1.9

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [X] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Hey @TheHatcheryLabs 

Does this only happen when _both_ WPGraphQL for ACF and WPGraphQL for WooCommerce are enabled, or just one of them?

Also, an internal server error is usually a sign of things going wrong on the backend. What do you get if you turn on GraphQL debugging and check the [network response](https://www.wpgraphql.com/docs/debugging#checking-the-response)? Similarly, what do you see if you enable `WP_DEBUG_LOG` and check the generated `debug.log` file?

**Comment by TheHatcheryLabs** [comment]
It only happens when both WPGraphQL for ACF and WPGraphQL for WooCommerce are enabled. When only either one of them is enabled the IDE loads fine.

GraphQL debugging is enabled, but the IDE isn't loading for me to test a network response on a query as per the doc linked to. The app.js files response looks to be fine. Turning on WP_DEBUG_LOG doesn't produce a debug.log file.

Migrating to the beta version of the new [WPGraphQL for ACF](https://github.com/wp-graphql/wpgraphql-acf) plugin has resolved this issue however and the IDE loads fine with both plugins enabled.

**Comment by justlevine** [comment]
Happy to hear that the issue has already been fixed in the beta plugin :)

Going to mark this as resolved.
