### ISSUE TITLE
I get a warning "WPGraphQL\Data\DataSource::resolve_post_object is deprecated" whenever in the query there is a custom field "Image" created by the ACF plugin

### ISSUE THREAD

**Issue by tuanfront-end** [wp-graphql/wp-graphql#2867]
### Description

Hi, have a great day
I hope to get help from everyone

I get a warning "WPGraphQL\Data\DataSource::resolve_post_object is deprecated" whenever in the query there is a custom field "Image" created by the ACF plugin

I use the graphql function in php

I use plugins WPGraphQL for Advanced Custom Fields and Advanced Custom Fields, then create a custom Field Type as Image. I then use the graphql function to query posts. The problem here is whenever I query there is an Image field that is WordPress giving that warning

Appreciate any help from you guys. Thanks so much in advance

### Steps to reproduce

1, Go to ACF -> Field Groups -> Add new -> Add a custom filed with Field Type is Image
2, In PHP, add the code:
<pre>
 <code>
$data = graphql([
            'query' => '
            {
                posts {
                    nodes {
                        id
                        title
                        newFieldGroup {
                            fieldGroupName
                            testImageAcf {
                                id
                              }
                          }
                    }
                }
            }
            '
        ]);
</code></pre>

3, Then, WordPress will giving the warning: WPGraphQL\Data\DataSource::resolve_post_object is deprecated
4, The warning disappears if the testImageAcf field is omitted from the query

### WPGraphQL Version

1.14.8 

### WordPress Version

 6.2.2 

### PHP Version

7.4

### Additional enviornment details

Plugins I'm Using: WPGraphQL, Advanced Custom Fields, WPGraphQL for Advanced Custom Fields

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [X] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Hey @tuanfront-end , this is already resolved in the WPGraphQL for ACF rewrite happening over at https://github.com/wp-graphql/wpgraphql-acf.

It's a deprecation warning, so if you're waiting to migrate an older site over to the new version  until it's officially released, you can safely ignore the error.

**Comment by tuanfront-end** [comment]
@justlevine , Thanks a lot, now I know there is a rewrite plugin available. Thank you so much and hopefully the official release will be out soon
