### ISSUE TITLE
orderby meta value?

### ISSUE THREAD

**Issue by towfiqi** [wp-graphql/wp-graphql#287]
I have a query that looks like this:

```
		 $recent = array(
					   'post_type' => 'post',
					   'paged' => ( get_query_var('paged') ? get_query_var('paged') : 1),
					   'posts_per_page' => '12',
						'orderby' => 'meta_value_num',
						'meta_key' => 'ratings',
						'order' => 'DESC',
						'cat' => $end
						
					   );
		$the_query = new WP_Query( $recent );
```

Is it possible to orderby meta key/value ? currently I am only seeing orderby options is limited to : Date, title, author, parent, slug, in.

Is it possible to extend the orderby options with custom functions of some sort?

Thanks

**Comment by jasonbahl** [comment]
@towfiqi there is an extension plugin that adds meta query support if you need it. It’s not provided in the core plugin as meta queries can be pretty expensive and have even been known to take sites down so I wanted it to be something added very intentionally by the site admin. 

Also, one thing I might suggest is introducing a new connection that masks the internals. So instead of the client doing a `posts(where:{metaQuery:...})` Query, you could introduce something like `topRatedPosts` connection that has the WP_Query args pre-defined the way you want them, but not be exposed to the client. That would allow nice separation from the client and the server so you could change from a meta query to a tax query, or offload to Elasticsearch, or whatever you wanted to do later on if you noticed performance issues but the client wouldn’t know anything about the change. They would just know they’re still getting `topRatedPosts` they don’t need to know _how_ they are getting them. 

Just food for thought. May or may not make sense for what you’re working on. 

Happy to chat more if needed

**Comment by jasonbahl** [comment]
Speaking of this, we need to provide a way to make it easy to register new connections. 

Something like `register_graphql_connection( $args )` would be slick. 

Not sure exactly how that should look but would be super helpful to have an easy way for folks to _not_ have to worry about building out the whole edges/node shape of a response. 

You can extend and modify existing connections to add your own, but I feel like we can make that much easier with an abstracted register connection API 🤔

**Comment by towfiqi** [comment]
I love the connection idea. But browsing through the Post connections files I am not sure how to modify the  to classes to add a custom query. I am not very knowledgeable in PHP. A documentation would be nice.

And do you guys have any plan to add orderby = RAND ?

**Comment by towfiqi** [comment]
The plugin wont work if we cannot set the 'orderby'   => 'meta_value' , Which is not currently possible with wp-graphgql .

**Comment by jasonbahl** [comment]
If you need to query and sort by a value I HIGHLY recommend using terms instead of post meta. You should be able to filter in `$args` to support more specific meta queries, or create your own connection query that has it pre-defined...but I can’t recommend it and I don’t envision having support for it in this plugin itself.

**Comment by jasonbahl** [comment]
But I suppose the meta-query plugin should filter in the orderby option if it also filters in the meta query params

**Comment by towfiqi** [comment]
> But I suppose the meta-query plugin should filter in the orderby option if it also filters in the meta query params

Will you guys add this feature anytime soon? I may have to go with rest api instead of graphql :sob:

**Comment by towfiqi** [comment]
Update: Just modified some files to add the orderby meta_value support.

1. in file `postObjectConnectionArgs.php` appended this in `function fields()` :

```
		'metaKey'     => [
			'type'        => Types::string(),
			'description' => __( 'Show posts with a specific meta_key.', 'wp-graphql' ),
		],
```

2.  in file `postObjectConnectionArgs.php` appended this in `function orderby_enum()` :

```
			[
				'name'        => 'META_VALUE',
				'value'       => 'meta_value',
				'description' => __( 'Order by meta_value', 'wp-graphql' ),
			],
			[
				'name'        => 'META_VALUE_NUM',
				'value'       => 'meta_value_num',
				'description' => __( 'Order by meta_value_num', 'wp-graphql' ),
			]
```

3.  in file `PostObjectConnectionResolver.php` appended this in `function sanitize_input_fields()` :

			`'metaKey'      => 'meta_key',`


Now Its possible to  order posts like this:

```
query{
posts(last:50, where:{orderby:{field:META_VALUE_NUM, order:DESC}, metaKey:"downloads"}) {
        edges {
            cursor
          node {
            id
            postId
            title
          }
        }
    }
}
```

It would be great if you could add this in the next version.

**Comment by cr101** [comment]
Meta queries can be expensive but offloading indexing to Algolia, SOLR or Elasticsearch can greatly improve the performance. 
@towfiqi You might want to take a look at the ElasticPress plugin.

**Comment by jasonbahl** [comment]
@towfiqi I believe everything you customized could have been accomplished via filters without modifying the core plugin code. 

I don’t think we’ll support meta queries in the core plugin, but the plugin does provide quite a few filters/actions that make it pretty easy for you to add custom fields, custom args on fields, and custom ways to resolve fields. 

I’ll confirm in tomorrow, but pretty sure you can filter in everything you need without needing to alter the plugin itself.

**Comment by jasonbahl** [comment]
@towfiqi everything you did here (https://github.com/wp-graphql/wp-graphql/issues/287#issuecomment-340443353) can be done via filters:

Here's an example, based on how you did it, just without touching the core plugin code:

## Filter the query args to add a metaKey field
```
add_filter( 'graphql_queryArgs_fields', function( $fields ) {
	$fields['metaKey'] = [
		'type' => \WPGraphQL\Types::string(),
		'description' => __( 'Show posts with a specific meta_key.', 'your-custom-plugin' ),
	];
	return $fields;
} );
```

## Filter the values for the orderby enum
```
add_filter( 'graphql_orderby_values', function( $values ) {
	$values['META_VALUE'] = [
		'value'       => 'meta_value',
		'description' => __( 'Order by meta_value', 'your-custom-plugin' ),
	];
	$values['META_VALUE_NUM'] = [
		'value'       => 'meta_value_num',
		'description' => __( 'Order by meta_value_num', 'your-custom-plugin' ),
	];
	return $values;
} );
```

## Filter the query args for the PostObjectConnection to translate the `metaKey` arg to an arg usable by WP_Query
```
add_filter( 'graphql_post_object_connection_query_args', function( $query_args, $source, $args, $context, $info ) {
	if ( ! empty( $args['where']['metaKey'] ) ) {
       $query_args['meta_key'] = esc_html( $args['where']['metaKey'] );
    }
    return $query_args;
}, 10, 5 );
```

## Add the field to the Post Schema so we can query for it
```
add_filter( 'graphql_post_fields', function( $fields ) {
	$fields['someNumber'] = [
		'type' => \WPGraphQL\Types::int(),
		'resolve' => function( $post ) {
			$value = get_post_meta( $post->ID, 'some_number', true );
		    return absint( $value );
		}
	];
	return $fields;
} );
```

And now we can query like so: 

![orderby-meta-demo](https://user-images.githubusercontent.com/1260765/32409541-7a85bd92-c173-11e7-8f6b-90b35ceb1601.gif)

====

I don't think I'll be adding support for using Meta values in queries as it's typically not best practice to query by meta and I don't want to advocate that. 

I do understand that some folks will want the ability, which is why there are hooks and filters throughout the plugin to allow folks to customize for their needs, and if your needs are to use meta queries to some degree, you can definitely filter in and add the support, I just don't think it will be part of the core plugin (much like the REST API doesn't support it either: https://developer.wordpress.org/rest-api/reference/posts/#list-posts )

**Comment by towfiqi** [comment]
Thanks. I totally understand.

**Comment by towfiqi** [comment]
Looks like the pagination is not working correctly. I guess a modification of `graphql_wp_query_cursor_pagination_support` function is necessary. Any help would much appreciated. 

Thanks

**Comment by jasonbahl** [comment]
@towfiqi so, I think to make pagination work with custom orderby params, you'd have to filter `posts_where` in the WP_Query and add raw SQL for what you need. 

You can see how I've got cursor pagination working here: 

https://github.com/wp-graphql/wp-graphql/blob/develop/src/Data/Config.php#L40-L103

Someone in the Slack channel (you can join here: https://www.wpgraphql.com/community/) posted some example code of how they got order working with data they have in a custom table, which seems relevant to your situation.

Here's what they did to add "trending" posts where the "trending" data is stored in another table.

```
add_filter( 'graphql_post_object_connection_query_args', function( $query_args, $source, $args, $context, $info ) {
    if ( ! empty( $args['where']['trending'] ) ) {
            add_filter('posts_join', 'graph_join_trending_to_wpquery');
            add_filter('posts_orderby', 'graph_trending_posts_orderby');
    }
}

function graph_join_trending_to_wpquery( $join ) {
    global $wpdb;
    $join .= "LEFT JOIN wp_popularpostsdata ON wp_popularpostsdata.postid = $wpdb->posts.ID";
    return $join;
}

function graph_trending_posts_orderby( $orderby ) {
    global $wpdb;
    $orderby = "(wp_popularpostsdata.pageviews) DESC";
    return $orderby;
}
```

**Comment by towfiqi** [comment]
@jasonbahl Thanks for the snippet. Similar to this, I am trying to get posts sorted by votes post_meta:

```
add_filter( 'graphql_queryArgs_fields', function( $fields ) {
	$fields['mostvoted'] = [
		'type' => \WPGraphQL\Types::string(),
		'description' => __( 'Show most voted posts ', 'wpd' ),
	];
	return $fields;
} );

add_filter( 'graphql_post_object_connection_query_args', function( $query_args, $source, $args, $context, $info ) {
	if ( ! empty( $args['where']['mostvoted'] ) ) {
	        add_filter('posts_join', 'graph_join_mostvoted_to_wpquery');
            add_filter('posts_orderby', 'graph_mostvoted_posts_orderby');
	}
    return $query_args;
}, 10, 5 );


function graph_join_mostvoted_to_wpquery( $join ) {
    global $wpdb;
    $join .= "LEFT JOIN wp_postmeta m ON (m.post_id = $wpdb->posts.ID AND m.meta_key = 'votes')";
    return $join;
}

function graph_mostvoted_posts_orderby( $orderby ) {
    global $wpdb;
    $orderby = "(wp_postmeta.meta_value) DESC";
    return $orderby;
}
```

But Sadly, I am getting this error:

`[14-Dec-2017 15:51:17 UTC] WordPress database error Unknown column 'wp_postmeta.meta_value' in 'order clause' for query SELECT   wp_posts.ID FROM wp_posts LEFT JOIN wp_postmeta m ON (m.post_id = wp_posts.ID AND m.meta_key = 'votes') WHERE 1=1  AND wp_posts.post_parent = 0  AND wp_posts.post_type = 'post' AND ((wp_posts.post_status = 'publish'))  ORDER BY (wp_postmeta.meta_value) DESC LIMIT 0, 11 made by require('C:\xampp2\htdocs\wpd\wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array, WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WPGraphQL\Router->resolve_http_request, WPGraphQL\Router::process_http_request, do_graphql_request, WPGraphQL::do_graphql_request, GraphQL\GraphQL::executeAndReturnResult, GraphQL\GraphQL::promiseToExecute, GraphQL\Executor\Executor::promiseToExecute, GraphQL\Executor\Executor->doExecute, GraphQL\Executor\Promise\Adapter\SyncPromiseAdapter->create, GraphQL\Executor\Executor->GraphQL\Executor\{closure}, GraphQL\Executor\Executor->executeOperation, GraphQL\Executor\Executor->executeFields, GraphQL\Executor\Executor->resolveField, GraphQL\Executor\Executor->resolveOrError, WPGraphQL\Utils\InstrumentSchema::WPGraphQL\Utils\{closure}, call_user_func, WPGraphQL\Type\PostObject\Connection\PostObjectConnectionDefinition::WPGraphQL\Type\PostObject\Connection\{closure}, WPGraphQL\Data\DataSource::resolve_post_objects_connection, WPGraphQL\Data\ConnectionResolver::resolve, WPGraphQL\Type\PostObject\Connection\PostObjectConnectionResolver::get_query, WP_Query->__construct, WP_Query->query, WP_Query->get_posts`

Do you have any idea what I am doing wrong? Thanks

**Comment by epeli** [comment]
@towfiqi Old closed issue but I've worked on making meta query based pagination work correctly here https://github.com/wp-graphql/wp-graphql/pull/721

**Comment by towfiqi** [comment]
Many Thanks :100: :+1:

**Comment by jasonbahl** [comment]
@epeli thanks for following up here. 😄

**Comment by safwan39** [comment]
how pagination sorted for meta_value?

**Comment by Kieran-Hyphen** [comment]
> [@towfiqi](https://github.com/towfiqi) everything you did here ([#287 (comment)](https://github.com/wp-graphql/wp-graphql/issues/287#issuecomment-340443353)) can be done via filters:
> 
> Here's an example, based on how you did it, just without touching the core plugin code:
> 
> ### Filter the query args to add a metaKey field
> ```
> add_filter( 'graphql_queryArgs_fields', function( $fields ) {
> 	$fields['metaKey'] = [
> 		'type' => \WPGraphQL\Types::string(),
> 		'description' => __( 'Show posts with a specific meta_key.', 'your-custom-plugin' ),
> 	];
> 	return $fields;
> } );
> ```
> 
> ### Filter the values for the orderby enum
> ```
> add_filter( 'graphql_orderby_values', function( $values ) {
> 	$values['META_VALUE'] = [
> 		'value'       => 'meta_value',
> 		'description' => __( 'Order by meta_value', 'your-custom-plugin' ),
> 	];
> 	$values['META_VALUE_NUM'] = [
> 		'value'       => 'meta_value_num',
> 		'description' => __( 'Order by meta_value_num', 'your-custom-plugin' ),
> 	];
> 	return $values;
> } );
> ```
> 
> ### Filter the query args for the PostObjectConnection to translate the `metaKey` arg to an arg usable by WP_Query
> ```
> add_filter( 'graphql_post_object_connection_query_args', function( $query_args, $source, $args, $context, $info ) {
> 	if ( ! empty( $args['where']['metaKey'] ) ) {
>        $query_args['meta_key'] = esc_html( $args['where']['metaKey'] );
>     }
>     return $query_args;
> }, 10, 5 );
> ```
> 
> ### Add the field to the Post Schema so we can query for it
> ```
> add_filter( 'graphql_post_fields', function( $fields ) {
> 	$fields['someNumber'] = [
> 		'type' => \WPGraphQL\Types::int(),
> 		'resolve' => function( $post ) {
> 			$value = get_post_meta( $post->ID, 'some_number', true );
> 		    return absint( $value );
> 		}
> 	];
> 	return $fields;
> } );
> ```
> 
> And now we can query like so:
> 
> ![orderby-meta-demo](https://user-images.githubusercontent.com/1260765/32409541-7a85bd92-c173-11e7-8f6b-90b35ceb1601.gif) [ ![orderby-meta-demo](https://user-images.githubusercontent.com/1260765/32409541-7a85bd92-c173-11e7-8f6b-90b35ceb1601.gif) ](https://user-images.githubusercontent.com/1260765/32409541-7a85bd92-c173-11e7-8f6b-90b35ceb1601.gif) [ ](https://user-images.githubusercontent.com/1260765/32409541-7a85bd92-c173-11e7-8f6b-90b35ceb1601.gif)
> 
> ====
> 
> I don't think I'll be adding support for using Meta values in queries as it's typically not best practice to query by meta and I don't want to advocate that.
> 
> I do understand that some folks will want the ability, which is why there are hooks and filters throughout the plugin to allow folks to customize for their needs, and if your needs are to use meta queries to some degree, you can definitely filter in and add the support, I just don't think it will be part of the core plugin (much like the REST API doesn't support it either: https://developer.wordpress.org/rest-api/reference/posts/#list-posts )

@jasonbahl  This doesn't work with the current version, no custom orderby values allowed? - I know you don't want to implement this to the plugin itself, but is it possible at all to achieve this someway?
