### ISSUE TITLE
Custom Post Type featuredImage is null

### ISSUE THREAD

**Issue by troyblakelydc** [wp-graphql/wp-graphql#2877]
### Description

This is a change from 1.14.3 to 1.14.9. In 1.14.3 featuredImage returns results. In 1.14.9 it does not. 

### Steps to reproduce

I have a custom post type with advanced custom fields called "release".  When I query the release object like below, the featuredImage object is null.

`query getreleases {
  releases {
    nodes {
      title
      featuredImage {
        node {
          id
          mediaItemUrl
        }
      }
    }
  }
}`

### Additional context

This is on a multisite

### WPGraphQL Version

1.14.9

### WordPress Version

6.2.2

### PHP Version

7.4

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [ ] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
@troyblakelydc I've tried to reproduce this, and I'm not able to. 

Here's the steps I took to reproduce: 

### Register Post Type

Using ACF PRO v6.1.7, I created a custom post type named "release"

![CleanShot 2023-08-03 at 09 59 19](https://github.com/wp-graphql/wp-graphql/assets/1260765/f3367c98-6468-4d01-9bc0-cfbedc22c6bf)

I set the Post Type to support featured images:

![CleanShot 2023-08-03 at 10 00 27](https://github.com/wp-graphql/wp-graphql/assets/1260765/56ad12d2-ea4b-4e79-8dfe-3b97b329f247)


I set the post type to "Show in GraphQL"

![CleanShot 2023-08-03 at 09 59 52](https://github.com/wp-graphql/wp-graphql/assets/1260765/5324a136-2cb8-41d5-ac64-01b3752ed105)


### Publish Post with Featured Image.

Next, I created a post in the "release" post type, added a featured image, and published it:

![CleanShot 2023-08-03 at 09 57 16](https://github.com/wp-graphql/wp-graphql/assets/1260765/d978cdd2-e5f9-426c-a2e6-db505edfd84e)

### Query the data

Next, I executed the same query you shared:

```graphql
query getreleases {
  releases {
    nodes {
      title
      featuredImage {
        node {
          id
          mediaItemUrl
        }
      }
    }
  }
}
```

And I see the release along with the associated featured image:

![CleanShot 2023-08-03 at 09 57 05](https://github.com/wp-graphql/wp-graphql/assets/1260765/2e2b5353-a99c-47e8-a7ff-71451bbc0fc7)

----

I tried to reproduce with the following environment: 

- WordPress v6.2.2 (on localwp)
- PHP v8.1.9
- ACF PRO v6.1.7
- WPGraphQL v1.14.9
- WPGraphQL for ACF v2.0.0-beta.3.1.0

----

As of right now, I don't have enough information to believe this is a regression between WPGraphQL 1.14.3 -> 1.14.9. It _could_ be, but I'm unable to reproduce, so my only thought is it might be something specific to your data set?

If you're able to consistently reproduce this, please open another issue with steps to reproduce, ideally on a clean environment with minimal plugins active.

**Comment by troyblakelydc** [comment]
Thanks for looking at this. FWIW - I network deactivated and then reactivated the WPGQL plugin which seemed to fix the problem.

**Comment by jasonbahl** [comment]
@troyblakelydc glad to hear you got it fixed!  🙌🏻
