### ISSUE TITLE
Secure Introspection query with token

### ISSUE THREAD

**Issue by dimitriBouteille** [wp-graphql/wp-graphql#2883]
### What problem does this address?

Would it be possible to add a feature that allows to retrieve introspection only if a token exists ?

The idea would be to add a header (ie: `graphql-token`) and allow instrospection only if this token is valid.

![Capture d’écran du 2023-08-06 16-28-24](https://github.com/wp-graphql/wp-graphql/assets/34821762/eb5c1234-70f1-4014-8c0d-e1ae1448a656)

### What is your proposed solution?

- Add new option (ie: Introspection security token) on page /wp-admin/admin.php?page=graphql-settings

If a token is configured, check if the token is passed in the `graphql-token` header, if the token is good allow introspection otherwise display an error.

### Additional Context

In some cases it's mandatory to allow introspection but add additional security to avoid that anyone can perform introspection.

**Comment by justlevine** [comment]
Hey @dimitriBouteille . When _public_ introspection is disabled, it is still available for authenticated requests, which means you should already be able to achieve what you want using the `Authentication` header, no need for a special header.

If this is meant for public client-side consumption, you can create a user in WordPress with limited permissions and then use its Application Password via basic auth.

**Comment by kidunot89** [comment]
@justlevine You beat me to it 🤣.

**Comment by jasonbahl** [comment]
I'm going to close this as this isn't immediately actionable. 

There are various ways to authenticate currently and we have issues, such as "supporting application passwords" where we might more formally tackle authentication/authorization.
