### ISSUE TITLE
Get post object by old slug

### ISSUE THREAD

**Issue by cr101** [wp-graphql/wp-graphql#289]
In WordPress core the old links are automatically redirected. We should be able to fetch a single post object by old slug.
The post old slugs are stored in `wp_postmeta` with the meta_key `_wp_old_slug`

This new feature is related to [#263](https://github.com/wp-graphql/wp-graphql/issues/263)

**Comment by jasonbahl** [comment]
@cr101 accidentally closed this, sorry. Re-opened.

**Comment by jasonbahl** [comment]
I think we can close this. I'm thinking this is probably plugin territory where someone could filter in this functionality if needed. 

If someone has a compelling argument on why this should be core WPGraphQL vs. plugin, I'm open to listen, but feels like something that can/should be filtered in as needed.

**Comment by cr101** [comment]
Anyone building a front-end web app will need to use this functionality so I think it should be in core WPGraphQL as it's a WordPress core functionality (see `function wp_old_slug_redirect`)

As an example, you publish a newly created post and then half an hour later after Google had already indexed that post you change the post slug in the permalink. Now you need to automatically redirect the old slug to the correct permalink otherwise you will end up with a broken page showing a 404 error. Not a great UX.

There should at least be an example of how to redirect old slugs to the correct permalink in the documentation.

**Comment by jasonbahl** [comment]
Closing this as it can be accomplished as a plugin. If you need to do this, you can register a root field that accepts an "old slug" input and returns a post object by the old slug.

Or you could filter the `postBy()` to support another input: `postBy( oldSlug: "your-old-slug" )` and return the post object that way.

**Comment by lightningspirit** [comment]
Shouldn't wp-graphql be as compatible as possible with core functionalities? 🤔
