### ISSUE TITLE
first: 100 doesn't work on postFormats query

### ISSUE THREAD

**Issue by tekfunk** [wp-graphql/wp-graphql#2917]
### Description

I am building a list of Galleries through post formats, and have more than 10.  Setting first: 100 does not have any effect.  Am I doing this wrong?

`query getGalleries {
    postFormats(first: 100, where: { name: "post-format-gallery" }) {
      nodes {
        posts {
          nodes {
            guid
            id
            slug
            title
            featuredImage {
              node {
                altText
                caption(format: RENDERED)
                guid
                srcSet
                sourceUrl
                slug
                title(format: RENDERED)
              }
            }
            excerpt(format: RENDERED)
          }
        }
      }
    }
  }`

### Steps to reproduce

Running that query in the GraphiQL IDE

### WPGraphQL Version

1.15.0

### WordPress Version

6.3

### PHP Version

8.0.29

### Additional enviornment details

GraphiQL IDE, same results from my nextjs/react app

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
@tekfunk your query is asking for 100 postFormats where the postFormat name is `post-format-gallery`

I think what you maybe meant to do is ask for the `postFormat` where the name is `post-format-gallery`, then query 100 posts?

Something like: 

```graphql
query getGalleries {
    postFormats(where: { name: "post-format-gallery" }) {
      nodes {
        posts(first: 100) {
          nodes {
            guid
            id
            slug
            title
            featuredImage {
              node {
                altText
                caption(format: RENDERED)
                guid
                srcSet
                sourceUrl
                slug
                title(format: RENDERED)
              }
            }
            excerpt(format: RENDERED)
          }
        }
      }
    }
  }
```
