### ISSUE TITLE
Assign a post to category while creating using mutation.

### ISSUE THREAD

**Issue by wpgraphqladmin** [wp-graphql/wp-graphql#292]
@jasonbahl How can we assign a post to a category while crating a post using mutation.

```
mutation {
  createPost(input: {
    authorId: 2
    title: "Title" 
    clientMutationId: "12"
    content: "Content"
    status:PUBLISH
  }) {
    clientMutationId
    post {
      postId
    }
  }
}
```

Please guide on how to achieve this.

**Comment by jasonbahl** [comment]
@wpgraphqladmin at the moment there is no input to set the category/tags. . .would love a PR to add this to the plugin though!

For now, you should be able to filter in an input like so: 

```
add_filter( 'graphql_post_object_mutation_input_fields', function( $fields ) {
  return $fields['yourInputFieldName'] => [
     'type' => Types::list_of( Type::string ), // assuming you want to take a list of category names or slugs as the input?
     'description' => __( 'List of categories to assign the object to', 'your-text-domain' ),
  ];
} );
```

Then, to do something with the values that are input, you can hook in like so: 

```
add_action( 'graphql_post_object_mutation_update_additional_data', function( $post_id, $input ) {

    if ( ! empty( $input['yourInputFieldName'] ) && is_array( $input['yourInputFieldName'] ) ) {
       wp_set_object_terms($post_id, $input['yourInputFieldName'], 'category', true)
    }

}, 10, 2 );
```

We will have official support for this in an upcoming release, but no ETA yet. So if you need it now, I suggest filtering it in like this, but probably namespace your input field to avoid potential conflicts when we do ship the feature.

**Comment by CodeProKid** [comment]
I believe this already works. Candidate for closing.

**Comment by jasonbahl** [comment]
This does indeed already work. 

Here it is in action:

![graphql-create-post-with-categories](https://user-images.githubusercontent.com/1260765/45055314-afe7b080-b04c-11e8-98d7-4b52f7871fea.gif)
