### ISSUE TITLE
Unexpected Results While Retrieving Terms via Cursor-Based Pagination, Sorted by Term Name, When Multiple Terms Have Identical Names

### ISSUE THREAD

**Issue by mohjak** [wp-graphql/wp-graphql#2926]
### Context:

I am encountering unexpected behavior when querying for terms with identical names using cursor-based pagination.

#### Data Setup:

Here are the terms that serve as children to the term with `term_id: 39`.

| term_id | name             |
| ------- | ---------------- |
| 62      | Child Category 01|
| 63      | Child Category 02|
| 64      | Child Category 03|
| 65      | Child Category 04|
| 66      | Child Category 05|
| 199     | Child 1          |
| 200     | Child 1          |
| 201     | Child 1          |
| 202     | Child 1          |

#### Initial GraphQL Query:

```graphql
query terms {
  categories(first: 2, after: "", where: {
    parent: 39
    order: ASC
    orderby: NAME
  }) {
    pageInfo {
      endCursor
    }
    nodes {
      name
      databaseId
      slug      
    }
  }
}
```

#### Initial SQL Query:

```sql
SELECT t.term_id
FROM wp_terms AS t
INNER JOIN wp_term_taxonomy AS tt ON t.term_id = tt.term_id
WHERE tt.taxonomy IN ('category') AND tt.parent = '39'
ORDER BY t.name ASC
LIMIT 0, 3
```

#### Expected and Actual Outcome:

The executed GraphQL query returns the following JSON output, which is in line with expectations:

```json
{
  "data": {
    "categories": {
      "pageInfo": {
        "endCursor": "YXJyYXljb25uZWN0aW9uOjIwMQ=="
      },
      "nodes": [
        {
          "name": "Child 1",
          "databaseId": 200,
          "slug": "child-1-2"
        },
        {
          "name": "Child 1",
          "databaseId": 201,
          "slug": "child-1-3"
        }
      ]
    }
  }
}
```

#### Follow-up GraphQL Query:

I then executed another query, using the `endCursor` obtained from the first query:

```graphql
query terms {
  categories(first: 2, after: "YXJyYXljb25uZWN0aW9uOjIwMQ==", where: {
    parent: 39
    order: ASC
    orderby: NAME
  }) {
    pageInfo {
      endCursor
    }
    nodes {
      name
      databaseId
      slug      
    }
  }
}
```

#### Follow-up SQL Query:

```sql
SELECT t.term_id
FROM wp_terms AS t
INNER JOIN wp_term_taxonomy AS tt ON t.term_id = tt.term_id
WHERE tt.taxonomy IN ('category') 
  AND tt.parent = '39'
  AND t.name > "Child 1"
ORDER BY t.name ASC
LIMIT 0, 3
```

#### Unexpected Outcome:

Contrary to expectations, the following data was returned:

```json
{
  "data": {
    "categories": {
      "pageInfo": {
        "endCursor": "YXJyYXljb25uZWN0aW9uOjYz"
      },
      "nodes": [
        {
          "name": "Child Category 01",
          "databaseId": 62,
          "slug": "child-category-01"
        },
        {
          "name": "Child Category 02",
          "databaseId": 63,
          "slug": "child-category-02"
        }
      ]
    }
  }
}
```

I expected to see `term_id: 201, term_id: 202` in the next cursor pagination as I presumed that if the names are identical, the pagination should consider using the next `term_id`.

#### Code Reference:

Upon inspecting the code [here](https://github.com/wp-graphql/wp-graphql/blob/9b4384e3fe0e5f9ac81279deff0cdb37039c88fa/src/Data/Cursor/TermObjectCursor.php#L133), it seems that the `term_id` is only used for ordering if there are no other specified order criteria.

### Suggested Fix:

I propose that `term_id` should act as a secondary sorting parameter when the names are identical, ensuring consistent cursor-based pagination.

### Steps to reproduce

You can replicate this issue at [Test Terms Cursor](https://probable-tendency.localsite.io/wp-admin) with the following credentials:

- Basic Auth:
  - Username: pattern
  - Password: unusual
- Admin:
  - Username: admin
  - Password: password

### WPGraphQL Version

1.16.0

### WordPress Version

6.3.1

### PHP Version

8.1.9

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by mohjak** [comment]
@jasonbahl, I have re-enabled the link for reproduction of the issue. It is a localwp wp that connects online. This needs my machine to be up. Could you please that you can connect to it from your end?
I have prepared a code that resolves this issue, but When I run all unit tests after applying the change there are two tests failed. my change requires to stop the following block of code:
https://github.com/wp-graphql/wp-graphql/blob/9b4384e3fe0e5f9ac81279deff0cdb37039c88fa/src/Data/Cursor/TermObjectCursor.php#L106C1-L115C1
I can't find a solution for it till now.
Maybe I should create the pull request to explain more clearly about the change, what do you think?

**Comment by jasonbahl** [comment]
> Maybe I should create the pull request to explain more clearly about the change, what do you think?

@mohjak yes, open a PR and we can go from there! 

@kidunot89 recently worked on this PR (https://github.com/wp-graphql/wp-graphql/pull/2882) fixing similar issues with pagination for queries for posts, so we can likely take some of the work he did for that and apply it to Term cursors as well!

**Comment by mohjak** [comment]
@jasonbahl you are right I am getting the same result with public users, I was executing queries with a logged in user, since I am debugging and review SQL queries. I didn't figure this out. Nothing special, I've just created an empty wp with wp-graphql and the same result appears when I view the website from a public user. I think the problem is related to localwp online service because the issue is not appearing when I am viewing from the localhost url. Anyways, please if you want to reproduce the issue execute queries for a logged in user.
