### ISSUE TITLE
Wrong data being returned from `EnqueuedAsset.extra` resolve function 

### ISSUE THREAD

**Issue by lubiah** [wp-graphql/wp-graphql#2938]
### Description

If you are trying to query about the extra information of an enqueued asset whether it being a style or a script, you get the wrong results.

Here are the reasons for the error. 
* the resolve function for the `extra` field tries to return a string, meanwhile it's an supposed to be an object.
* the function is also set to return only one property `extra.data` and this property only exists on scripts, making it hard to extract other information.
Also, there are other fields other than extra.data which whiles on the object so by returning only `extra.data`, we are unable to access the other data.

Here's proof.

![image](https://github.com/wp-graphql/wp-graphql/assets/63173187/d3805814-1206-4f6c-b9b2-276217d70b4f)
Over here, you can see it's returning null for the data.

![image](https://github.com/wp-graphql/wp-graphql/assets/63173187/81438ad9-b98a-40eb-a8db-d3ec9093b685)
By using GraphQL debug, we can verify that many properties exist on the extra field but it's being forced to return a string

### Steps to reproduce

1) Use this query on any random posts

```
{
  post(idType:DATABASE_ID, id:43){
    slug,
    enqueuedStylesheets {
      edges{
      	node{
          dependencies {
            id
          },
        	extra  
        }
      }
    }
  }
}
```

### WPGraphQL Version

Version 1.16.0

### WordPress Version

6.3.1

### PHP Version

PHP version 8.2.4

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Source: https://github.com/wp-graphql/wp-graphql/blob/2937585d4f73756535302b0ebe78592e51e23c94/src/Type/InterfaceType/EnqueuedAsset.php#L72

The problem is that `$extra` is `array<string, mixed>`, not sure if we can just encode the value as type `String` 🤔. What sort of data usually gets stored here?

**Comment by lubiah** [comment]
> Source:
> 
> https://github.com/wp-graphql/wp-graphql/blob/2937585d4f73756535302b0ebe78592e51e23c94/src/Type/InterfaceType/EnqueuedAsset.php#L72
> 
> The problem is that `$extra` is `array<string, mixed>`, not sure if we can just encode the value as type `String` 🤔. What sort of data usually gets stored here?

It stores data about about the styles or scripts.
Here's a list of possible values
* after
* path

**Comment by lubiah** [comment]
@justlevine , I suggest we create two new `ObjectTypes` for the extra found in an enqueuedScript and for that found in an enqueuedStyle

**Comment by lubiah** [comment]
@justlevine , there is no documentation though I can provide you with information where you can find them.
If you have the Wordpress codebase downloaded on your computer, a simple search for `wp_style_add_data` or `wp_script_add_data` or `add_data` in your code editor can help you to find where it's being used.

The `WP_Scripts` class and `WP_Styles` class both inherit the `WP_Dependencies` class which has a method called `add_data`. 
The method is responsible for adding data to the `extra` so wherever it's being called can give you a hint of the possible types.
Would you need any more info??
