### ISSUE TITLE
Not returning all menu items

### ISSUE THREAD

**Issue by ct-abdul** [wp-graphql/wp-graphql#2951]
### Description

I have 3 level menu and it has access to public as well.

![image](https://github.com/wp-graphql/wp-graphql/assets/98771665/41b6b341-4131-4d32-b841-d7fb7ba6c1dd)

But when I query it won't return all items and getting break in a certain point.

![image](https://github.com/wp-graphql/wp-graphql/assets/98771665/e11da510-82c9-43f7-a8a2-f1dc4f361707)

I have Latest WP version 6.3.1 and WP Graphql version 1.16.0.

### Steps to reproduce

01. Create menu with 3 level
2. Query as per my above screen shot

### WPGraphQL Version

1.16.0

### WordPress Version

6.3.1

### PHP Version

7.4.26

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Hey @ct-abdul 

Looks like you're missing a `first:50` (or whatever) arg to `menuItems` ? I.e.:  `menuItems( first:20, where: { location: PRIMARY } ) { ...}`, so its returning the first 10 items by default.

Can you confirm that the query works as expected when `first` is set to an explicit value?

**Comment by ct-abdul** [comment]
@justlevine,

Oh that is cool. It worked now. Thank you. One more question is there is a way to query this with infinity value instead of some hard value to first field ?

Thank You.

**Comment by justlevine** [comment]
> One more question is there is a way to query this with infinity value instead of some hard value to first field ?

There is not, and more importantly you shouldn't put a rediculusly large number like '999' (by default, WPGraphQL caps the max returned nodes at 100, but there's a filter you can use to raise it), to avoid overloading the server since GraphQL makes it really easy to write expensive queries.

The ideal approach is to use Cursor-based pagination, using the `pageInfo` object to feed the subsequent queries until you've fetched them all.

**Comment by justlevine** [comment]
I'm going to close this ticket but please feel free to open a Discussion - or even better, join and post in the WPGraphQL Slack - if you have any other usage questions :)
