### ISSUE TITLE
SendPasswordResetEmail Doesn't Display Reset Link in Received Emails Due to Formatting Issue with <> characters

### ISSUE THREAD

**Issue by nestarz** [wp-graphql/wp-graphql#2965]
### Description

The 'SendPasswordResetEmail' feature is not functioning as intended. The reset link included in the body of the received email is not displayed properly due to an HTML formatting issue with `<>` characters. 

Code Reference: [Link to Code](https://github.com/wp-graphql/wp-graphql/blob/5d69454571e2f0f9760547694eed1695be950a91/src/Mutation/SendPasswordResetEmail.php#L244)

Issue Demonstration:
Here's a representative sample of an email received for resetting a password - note the link that should be provided for the recipient to click on and reset their password is not displayed:

```
[hidden]
X-Mailer: PHPMailer 6.8.0 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: text/html; charset=UTF-8

Someone has requested a password reset for the following account:

Site Name: [hidden]

Username: [hidden]

If this was a mistake, just ignore this email and nothing will happen.

To reset your password, visit the following address:

<https://[hidden]/wp-login.php?action=rp&key=[hidden]&login=[hidden]>

```

The link, which is contained within `<>` characters, is not being rendered by the email's HTML engine.

### Steps to reproduce

1. Ensure you have a valid user account set up and the installation and setup of wp-graphql is correctly done.
2. Begin the password reset process for the user account.
3. Request a password reset email by calling the `sendPasswordResetEmail` mutation from your client application.
4. Check the inbox of the email account associated with the user account for the password reset email.
5. Observe that the email is received, but does not display the reset link correctly due to the `<>` characters that encapsulate it. The link appears hidden or not visible at all.

### WPGraphQL Version

1.16.0

### WordPress Version

6.3.1

### PHP Version

8.2

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
I don't believe WPGraphQL modifies anything in the email? It just sends it. 

If something in the email is invalid, I believe it's a core thing, or someone filtering the email. 

If you do a "password reset" from the core WP login page, is the email different than what is sent from `sendPasswordReset` mutation?

**Comment by nestarz** [comment]
I think it's my host provider namecheap's EasyWP who is doing something to my email as I changed the SMTP server and now ok. Really weird scenario.

But maybe its something about the headers. From the reset mail from the core WP login page I have these relevant headers:

X-Mailer: PHPMailer 6.8.0 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 8bit

and from the WpGraphQL

X-Mailer: PHPMailer 6.8.0 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: text/html; charset=UTF-8

And from the WPGraphql plugin I have in the original HTML content of the email the `<>` who I still think prevent the displaying of the link. That's super odd, I don't know who's fault.

**Comment by jasonbahl** [comment]
I'm going to close this as I don't believe there's anything actionable in the WPGraphQL repo to help here. 

If you find further evidence that WPGraphQL is doing something to cause unexepected behavior, and you have steps to reproduce consistently, open a new issue and reference this one and we can take a look.
