### ISSUE TITLE
incompatible with custom field for oder by (mysql aggregated reason)

### ISSUE THREAD

**Issue by idmahbub** [wp-graphql/wp-graphql#2974]
### Description

I have create some custom field for filter order post, i have some issue with sql mode `only_full_group_by` in my DBMS
`1055 - Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'futuriqde.wp_postmeta.meta_value' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by`

### Steps to reproduce

sql mode `only_full_group_by` benefit of those unambiguous cases.
add `ORDER BY clause in GROUP BY clause`

### Additional context

Mysql debug log, native Query from WpGraphql:
`SELECT   wp_posts.ID
FROM wp_posts  INNER JOIN wp_postmeta ON ( wp_posts.ID = wp_postmeta.post_id )
WHERE 1=1  AND (
wp_postmeta.meta_key = 'post_views_count') 
AND wp_posts.post_type = 'post' 
AND ((wp_posts.post_status = 'publish'))
GROUP BY wp_posts.ID
ORDER BY wp_postmeta.meta_value DESC,
wp_posts.ID DESC
LIMIT 0, 3`

### WPGraphQL Version

1.17.0

### WordPress Version

6.3.2

### PHP Version

8.0

### Additional environment details

sql mode `only_full_group_by`

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Thanks for reporting this @idmahbub 

Would you be able to flesh out the reproduction steps so we can efficiently investigate this? Specifically for
> add ORDER BY clause in GROUP BY clause

Could you provide a working PHP snippet that replicates this behavior?

**Comment by jasonbahl** [comment]
@idmahbub I'm going to close this as we need more information to reproduce. 

If you're able to provide that reproducible information, please open another issue with the added info, and reference this one. 

Thanks 🙏🏻
