### ISSUE TITLE
PHP deprecated

### ISSUE THREAD

**Issue by xbd63** [wp-graphql/wp-graphql#2981]
### Description

Hi, I’m getting this error when a GraphQL request is made. This is after updating from PHP 7.3 to PHP 8.2.

Error Level: E_DEPRECATED
Message: Creation of dynamic property WPGraphQL\AppContext::$connection_query_class is deprecated
File: /bitnami/wordpress/wp-content/plugins/wp-graphql/src/Type/WPConnectionType.php
Line: 528

This is the request: /graphql?query=query%20{%20posts(first:%2032,%20where:%20{mpid1:%20%22BBULRDSL000%22})%20{%20nodes%20{%20clientId%20databaseId%20title%20content%20featuredImage%20{%20node%20{%20id%20sourceUrl%20}%20}%20postFields%20{%20fieldGroupName%20galleries%20imageAltText%20isVideo%20matchedProducts%20{%20gbLink%20gbPrice%20gbTitle%20productId%20productName%20productPrice%20productUrl%20sku%20x%20y%20}%20socialNetwork%20sourceUrl%20}%20}%20}%20}

It's a request for some posts using ACF fields.

The correct JSON is returned, but this error persists.

WordPress version 6.3.2
Plugins:
Advanced Custom Fields PRO
Forminator Pro
Really Simple SSL
WooCommerce + related plugins
WP GraphQL
WPMU Dev Dashboard

Thanks

### Steps to reproduce

Execute a query with similar structure to this: /graphql?query=query%20{%20posts(first:%2032,%20where:%20{mpid1:%20%22BBULRDSL000%22})%20{%20nodes%20{%20clientId%20databaseId%20title%20content%20featuredImage%20{%20node%20{%20id%20sourceUrl%20}%20}%20postFields%20{%20fieldGroupName%20galleries%20imageAltText%20isVideo%20matchedProducts%20{%20gbLink%20gbPrice%20gbTitle%20productId%20productName%20productPrice%20productUrl%20sku%20x%20y%20}%20socialNetwork%20sourceUrl%20}%20}%20}%20}

(using ACF fields)

### WPGraphQL Version

1.18.0

### WordPress Version

6.3.2

### PHP Version

8.2

### Additional environment details

Bitnami on AWS

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by xbd63** [comment]
Hi team, do you have an ETA on this one? It's causing my log files to grow quite big. Thanks

**Comment by justlevine** [comment]
> Hi team, do you have an ETA on this one? It's causing my log files to grow quite big. Thanks

@xbd63 have you considered disabling [ deprecation warnings](https://www.php.net/manual/en/function.error-reporting.php) in the interim?

**Comment by xbd63** [comment]
If I did that I wouldn't be able to determine when other deprecation warnings arise.

**Comment by xbd63** [comment]
Hi, I don't know what a PR is?
