### ISSUE TITLE
How to create query/mutation for custom table in WP

### ISSUE THREAD

**Issue by wpgraphqladmin** [wp-graphql/wp-graphql#299]
How can we create query/mutation for custom table in WP?
Is there any hooks or filters we can use?

**Comment by jasonbahl** [comment]
WPGraphQL can work with any data source. It's optimized to work with WordPress core data (Posts, Terms, Comments, Users, etc), but you can easily filter the Schema to provide entry points for data that's not stored in WP core database tables. 

You can check the example plugin WPGraphQL Dad Jokes (https://github.com/wp-graphql/wp-graphql-dad-jokes/blob/master/wp-graphql-dad-jokes.php#L18-L40) that shows how to add a `dadJoke` field to the schema that allows you to get a random Dad Joke from an external source `icanhazdadjokes.com`

You can follow the same methods as that plugin to resolve data from (and write data to) anywhere, including custom tables. 

A super basic example of adding a query and mutation for custom data might look like this:

Assuming you have a DB table with columns `foo` and `bar` you might define a Type like so:

```
class FooBarType extends WPObjectType {

  private static $fields;
  
  public function __construct() {
    $config = [
      'name' => 'FooBarType',
      'fields' => self::fields(),
      'description' => __( 'The description for what a FooBar is', 'your-textdomain' ),
    ];
  }

  protected static function fields() {
    if ( null === self::$fields ) {
       self::$fields = function() {
           $fields = [
             'foo' => [
                 'type' => \WPGraphQL\Types::string(),
                 'description' => __( 'Your description of what a Foo is', 'your-textdomain' ),
              ],
              'bar' => [
                 'type' => \WPGraphQL\Types::string(),
                 'description' => __( 'Your description of what a Bar is', 'your-textdomain' ),
              ],
           ];

           // Pass the field through the filters, etc provided by WPObjectType
           return self::prepare_fields( $fields, 'FooBarType' );
       }
    }
  }
}
```

Then, you could add a Root Query for `fooBars` like so: 

```
add_filter( 'graphql_root_queries', function( $fields ) {

    $fields['fooBars'] => [
       'type' => \WPGraphQL\Types::list_of( new FooBarType() ),
       'description' => __( 'Get a list of FooBars', 'your-textdomain' ),
       'resolve' => function( $root, $args, $context, $info ) {
            // Use whatever methods you have to fetch data from your custom table here. 
            // It should return an array of items that will be passed down to be resolved by the
            // `FooBarType`, so each item should have a `foo` and `bar` property so the `FooBarType`
            // can resolve those properties.
            return MyCustomTableClass::getItems();
       }
    ];

    return $fields;

} );
```

At this point, you'd be able to query like so: 

```
{
  fooBars {
     foo
     bar
  }
}
```

And you might get something like this in return:

```
{
  data: {
    fooBars: [
      {
         "foo": "foo1",
         "bar": "bar1"
      },
      {
         "foo": "foo2",
         "bar": "bar2"
      }
    ]
  }
}
```

Adding a mutation is very similar to adding a query, the only real difference is that the resolver would write data to a data source instead of _just_ query from the data source. 

```
add_filter( 'graphql_rootMutation_fields', function( $fields ) {

    $fields['createFooBars'] => [
       'type' => new FooBarType(),
       'description' => __( 'Get a list of FooBars', 'your-textdomain' ),
       'args' => [
           'foo' => [
              'type' => \WPGraphQL\Types::string(),
              'description' => __( 'Describe the input for the foo field', 'your-textdomain' ),
           ],
           'bar' => [
               'type' => \WPGraphQL\Types::string(),
               'description' => __( 'Describe the input for the bar field', 'your-textdomain' ),
            ],
       ],
       'resolve' => function( $root, $args, $context, $info ) {
            // Use whatever methods you have to create and return data from your custom table.
            // The input fields will come through here as $args['foo'] and $args['bar'] so you can 
            // use those values to write to the database as needed
            return MyCustomTableClass::createAndGetFooBar( $args['foo'], $args['bar'] );
       }
    ];

    return $fields;

} );
```

Now you would be able to create FooBars like so:

```
mutation {
  createFooBars(
    foo: "My Value for Foo"
    bar: "My Value for Bar"
  ) {
     foo
     bar
  }
}
```

And you might get something like this as a result: 

```
{
  data: {
    createFooBar: {
      "foo": "My Value for Foo",
      "bar": "My Value for Bar"
    }
  }
}
```

**Comment by wpgraphqladmin** [comment]
We have created the custom table query as a plugin.
 
For this, We created a plugin, then we added the root query FooBar using the  add filter function, it works perfectly. 

After that we added the foobarType class and added the field 'foo' and 'bar' , it gives error.

**Comment by jasonbahl** [comment]
@wpgraphqladmin can you show your full code for extending the Type?

**Comment by cr101** [comment]
@wpgraphqladmin I'd be interested to see the full code as well. We are storing the post meta data in a custom table instead of _wp_postmeta_ table

**Comment by jasonbahl** [comment]
@cr101 are you in the WPGraphQL Slack? Someone posted code in there yesterday for doing some stuff with posts and custom tables. May be of interest to you. 

can join the Slack from here: https://wpgraphql.com/community

**Comment by cr101** [comment]
@jasonbahl Thank you. I found [the code](https://wp-graphql.slack.com/messages/C3NM1M291/) and it's very useful, thank you.
I love your idea for the new functions: `register_graphql_connection`,  `register_graphql_field`, `register_graphql_type`.
I'm currently trying to figure out a way to get ACF to store the CPTs meta data into custom tables in order to avoid having over 1 million rows in wp_postmeta table. ACF is great but it doesn't scale. WooCommerce is also working on [migrating Orders and Products to custom DB tables](https://github.com/woocommerce/woocommerce/issues/10071)

**Comment by wpgraphqladmin** [comment]
@jasonbahl 

Please find the code

 if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
class FooBarType extends WPObjectType {
  private static $fields;  
  public function __construct() {
    $config = [
      'name' => 'FooBarType',
      'fields' => self::fields(),
      'description' => __( 'The description for what a FooBar is', 'your-textdomain' ),
    ];
  }
  protected static function fields() {
	    if ( null === self::$fields ) {
	       self::$fields = function() {
	           $fields = [
	             'foo' => [
	                 'type' => \WPGraphQL\Types::string(),
	                 'description' => __( 'Your description of what a Foo is', 'your-textdomain' ),
	              ],
	              'bar' => [
	                 'type' => \WPGraphQL\Types::string(),
	                 'description' => __( 'Your description of what a Bar is', 'your-textdomain' ),
	              ],
	           ];

	           // Pass the field through the filters, etc provided by WPObjectType
	           return self::prepare_fields( $fields, 'FooBarType' );
	       }
	    }
  }
}
// custom class
class CustomTableClass{
	public $foo;
	public $bar;

	public function __construct($a,$b) {   
		$this->foo = $a;
		$this->bar = $b;  	}
  	protected static function getItems() {	   
  		$c1[0]=  customClass("a","b");
  		$c1[1]=  customClass("c","d");
    }

}

add_action( 'graphql_root_queries', 'wp_graphql_custom_table_root_query' );
function wp_graphql_custom_table_root_query( $fields ) {
	$fields['userActions'] = [
		'type' => \WPGraphQL\Types::string(),
		'description' => __( 'Returns a random Dad joke', 'wp-graphql' ),
		'resolve' => function() {			
			return CustomTableClass::getItems();
;
		},
	];
	return $fields;
}

Also we need a where condition query to the custom table

**Comment by wpgraphqladmin** [comment]
@jasonbahl  Can you please help on this?

**Comment by jasonbahl** [comment]
@wpgraphqladmin take a look at how other types are registered in the plugin. 

It looks like there are some small pieces missing (the __construct needs to call `parent::__construct( 
$config );` and pass the $config array. . .and you have some general syntax errors as well (missing semi-colons and extra semi-colons). 

Also the filter is actually `graphql_root_query`, not `graphql_root_queries`

**Comment by jasonbahl** [comment]
@wpgraphqladmin here's code that works. . .you need to make sure you're defining things AFTER `graphql_init` as well, as that will ensure the Autoloader is setup. 

```
class FooBarType extends \WPGraphQL\Type\WPObjectType {
		private static $fields;
		public function __construct() {
			$config = [
				'name' => 'FooBarType',
				'fields' => self::fields(),
				'description' => __( 'The description for what a FooBar is', 'your-textdomain' ),
			];
			parent::__construct( $config );
		}
		protected static function fields() {
			if ( null === self::$fields ) {
				self::$fields = function() {
					$fields = [
						'foo' => [
							'type' => \WPGraphQL\Types::string(),
							'description' => __( 'Your description of what a Foo is', 'your-textdomain' ),
						],
						'bar' => [
							'type' => \WPGraphQL\Types::string(),
							'description' => __( 'Your description of what a Bar is', 'your-textdomain' ),
						],
					];

					// Pass the field through the filters, etc provided by WPObjectType
					return self::prepare_fields( $fields, 'FooBarType' );
				};
			}
			return ! empty( self::$fields ) ? self::$fields : null;
		}
	}
	// custom class
	class CustomTableClass{
		public $foo;
		public $bar;

		public function __construct($a,$b) {
			$this->foo = $a;
			$this->bar = $b;
		}
	}

	add_action( 'graphql_root_query', 'wp_graphql_custom_table_root_query' );
	function wp_graphql_custom_table_root_query( $fields ) {
		$fields['userActions'] = [
			'type' => \WPGraphQL\Types::string(),
			'description' => __( 'Returns a random Dad joke', 'wp-graphql' ),
			'resolve' => function() {
				return [];
			},
		];
		return $fields;
	}
```

**Comment by wpgraphqladmin** [comment]
@jasonbahl  

Sorry for the inconvenience, we tried several method to get it done, but still stuck up with errors , Please guide us on this 

We use the code which you send in mail but it  gaves the same error 
"SyntaxError: Unexpected token < in JSON at position 0".  

Also we don't know how to resolve the values  "foo" and "bar" to the values from the custom table.

And we can't extend the class using 
class FooBarType extends \WPGraphQL\Type\WPObjectType {
}

Is need to copy any files from the wp-graplgl plugin for this.

Please find the attached code

**Comment by jasonbahl** [comment]
@wpgraphqladmin see my previous comment:
> you need to make sure you're defining things AFTER graphql_init as well

You could do this like so: 

```
add_action( 'graphql_init', function() {
    require_once( 'path/to/your/file.php' );
} );
```

As far as resolving data from custom tables, that's far beyond the scope of what I can offer help with. If you're storing data in custom tables, you should have methods in place to interact with said data. 

You can use raw SQL queries if you want, but you probably want some sort of API that abstracts that and adds caching, etc.

Unless there's a strong need to use custom tables, I would suggest using core WordPress APIs to store data (custom post types, custom taxonomies, options, etc).

**Comment by wpgraphqladmin** [comment]
@jasonbahl   

its worked.You saved our lot of time. Thanks a lot.

**Comment by wpgraphqladmin** [comment]
**@jasonbahl 

We added below code and its worked for getting values from query.

add_action( 'graphql_init', function() {
    require_once( 'path/to/your/file.php' );
} );

Added mutation query in your previous comment . It throws same error
"SyntaxError: Unexpected token < in JSON at position 0". 


Also can you please help us to write where clause in the query.**
		<?php

		//we cannot extent the class using this
		class FooBarType extends \WPGraphQL\Type\WPObjectType {
			private static $fields;
			public function __construct() {
				$config = [
					'name' => 'FooBarType',
					'fields' => self::fields(),
					'description' => __( 'The description for what a FooBar is', 'your-textdomain' ),
				];
				parent::__construct( $config );
			}
			protected static function fields() {
				if ( null === self::$fields ) {
					self::$fields = function() {
						$fields = [
							'foo' => [
								'type' => \WPGraphQL\Types::string(),
								'description' => __( 'Your description of what a Foo is', 'your-textdomain' ),
							],
							'bar' => [
								'type' => \WPGraphQL\Types::string(),
								'description' => __( 'Your description of what a Bar is', 'your-textdomain' ),
							],
						];

						// Pass the field through the filters, etc provided by WPObjectType
						return self::prepare_fields( $fields, 'FooBarType' );
					};
				}
				return ! empty( self::$fields ) ? self::$fields : null;
			}
		}
		// Custom class for table fileds
		class MyCustomTableClass{
			public function __construct() {
			}
			public static function getItems(){
				//Need to know the foo bar array format
				$a[0]['foo'] = 'helo';
				$a[0]['bar'] = 'helosw';
				return $a;
			}
		 public static function createAndGetFooBar($a,$b) {
				$a[0]['foo'] = $a;
				$a[0]['bar'] = $b;
				return $a;
		 }
		}




		add_action( 'graphql_root_queries', 'wp_graphql_dad_jokes_root_query' );
		function wp_graphql_dad_jokes_root_query( $fields ) {
			$fields['dadJoke'] = [
				// We can't assign the type FoorBarType
				'type' => \WPGraphQL\Types::list_of( new FooBarType() ),
				'description' => __( 'Returns a random Dad joke', 'wp-graphql' ),
				'resolve' => function() {       
					// Need to know how to resolve the foo and bar. Which is the format for     
					 return MyCustomTableClass::getItems(); 
				},
			];
			return $fields;
		}


		//Mutation Query It gives SyntaxError: Unexpected token < in JSON at position 0
		add_filter( 'graphql_rootMutation_fields', function( $fields ) {
			$fields['createFooBars'] => [
			   'type' => new FooBarType(),
			   'description' => __( 'Get a list of FooBars', 'your-textdomain' ),
			   'args' => [
				   'foo' => [
					  'type' => \WPGraphQL\Types::string(),
					  'description' => __( 'Describe the input for the foo field', 'your-textdomain' ),
				   ],
				   'bar' => [
					   'type' => \WPGraphQL\Types::string(),
					   'description' => __( 'Describe the input for the bar field', 'your-textdomain' ),
					],
			   ],
			   'resolve' => function( $root, $args, $context, $info ) {
					// Use whatever methods you have to create and return data from your custom table.
					// The input fields will come through here as $args['foo'] and $args['bar'] so you can 
					// use those values to write to the database as needed
					return MyCustomTableClass::createAndGetFooBar( $args['foo'], $args['bar'] );
			   }
			];

			return $fields;

		} );

**Comment by wpgraphqladmin** [comment]
@jasonbahl 

Did you get a chance to check this issue. We are stiil stuck on this. Please help.

**We added below code and its worked for getting values from query.**

add_action( 'graphql_init', function() {
require_once( 'path/to/your/file.php' );
} );

**Added mutation query in your previous comment . It throws same error**
"SyntaxError: Unexpected token < in JSON at position 0".

**Also can you please help us to write where clause in the query.****
<?php

	//we cannot extent the class using this
	class FooBarType extends \WPGraphQL\Type\WPObjectType {
		private static $fields;
		public function __construct() {
			$config = [
				'name' => 'FooBarType',
				'fields' => self::fields(),
				'description' => __( 'The description for what a FooBar is', 'your-textdomain' ),
			];
			parent::__construct( $config );
		}
		protected static function fields() {
			if ( null === self::$fields ) {
				self::$fields = function() {
					$fields = [
						'foo' => [
							'type' => \WPGraphQL\Types::string(),
							'description' => __( 'Your description of what a Foo is', 'your-textdomain' ),
						],
						'bar' => [
							'type' => \WPGraphQL\Types::string(),
							'description' => __( 'Your description of what a Bar is', 'your-textdomain' ),
						],
					];

					// Pass the field through the filters, etc provided by WPObjectType
					return self::prepare_fields( $fields, 'FooBarType' );
				};
			}
			return ! empty( self::$fields ) ? self::$fields : null;
		}
	}
	// Custom class for table fileds
	class MyCustomTableClass{
		public function __construct() {
		}
		public static function getItems(){
			//Need to know the foo bar array format
			$a[0]['foo'] = 'helo';
			$a[0]['bar'] = 'helosw';
			return $a;
		}
	 public static function createAndGetFooBar($a,$b) {
			$a[0]['foo'] = $a;
			$a[0]['bar'] = $b;
			return $a;
	 }
	}




	add_action( 'graphql_root_queries', 'wp_graphql_dad_jokes_root_query' );
	function wp_graphql_dad_jokes_root_query( $fields ) {
		$fields['dadJoke'] = [
			// We can't assign the type FoorBarType
			'type' => \WPGraphQL\Types::list_of( new FooBarType() ),
			'description' => __( 'Returns a random Dad joke', 'wp-graphql' ),
			'resolve' => function() {       
				// Need to know how to resolve the foo and bar. Which is the format for     
				 return MyCustomTableClass::getItems(); 
			},
		];
		return $fields;
	}


	//Mutation Query It gives SyntaxError: Unexpected token < in JSON at position 0
	add_filter( 'graphql_rootMutation_fields', function( $fields ) {
		$fields['createFooBars'] => [
		   'type' => new FooBarType(),
		   'description' => __( 'Get a list of FooBars', 'your-textdomain' ),
		   'args' => [
			   'foo' => [
				  'type' => \WPGraphQL\Types::string(),
				  'description' => __( 'Describe the input for the foo field', 'your-textdomain' ),
			   ],
			   'bar' => [
				   'type' => \WPGraphQL\Types::string(),
				   'description' => __( 'Describe the input for the bar field', 'your-textdomain' ),
				],
		   ],
		   'resolve' => function( $root, $args, $context, $info ) {
				// Use whatever methods you have to create and return data from your custom table.
				// The input fields will come through here as $args['foo'] and $args['bar'] so you can 
				// use those values to write to the database as needed
				return MyCustomTableClass::createAndGetFooBar( $args['foo'], $args['bar'] );
		   }
		];

		return $fields;

	} );

**Comment by jasonbahl** [comment]
I don’t think I can offer much more help at this time. Take a look at the source code in the plugin and see how things are done and go from there.

**Comment by ashyashoks** [comment]
can add where clause in cutom table of custom query

**Comment by Decruse** [comment]
I need to filter the custom table query so how can i add where claue in the custom root query in the above foobar example

**Comment by ashyashoks** [comment]
@jasonbahl

Please help on this.

**Comment by Helensamuel** [comment]
I am facing the same issue , as @Decruse  had.  Please help

**Comment by jasonbahl** [comment]
@Decruse @Helensamuel can ya'll provide a bit more details so I have more context? 

I don't feel like I have enough info to provide any assistance at the moment. . .maybe open a new issue and provide as much details as you can and I'll see what I can do to help. 

If you're doing stuff with custom tables, you're largely going to be on your own for how to resolve the data, but I can point you in the direction of how to at least register Types & Fields for the Schema.

**Comment by Helensamuel** [comment]
<?php
        class FooBarType extends \WPGraphQL\Type\WPObjectType {
            private static $fields;
            public function __construct() {
                $config = [
                    'name' => 'FooBarType',
                    'fields' => self::fields(),
                    'description' => __( 'The description for what a FooBar is', 'your-textdomain' ),
                ];
                parent::__construct( $config );
            }
            protected static function fields() {
                if ( null === self::$fields ) {
                    self::$fields = function() {
                        $fields = [
                            'foo' => [
                                'type' => \WPGraphQL\Types::string(),
                                'description' => __( 'Your description of what a Foo is', 'your-textdomain' ),
                            ]
                        ];             
                        return self::prepare_fields( $fields, 'FooBarType' );
                    };
                }
                return ! empty( self::$fields ) ? self::$fields : null;
            }
        }
        // Custom class for table fileds
        class MyCustomTableClass{
            public function __construct() {
            }
            public static function getItems(){      
                $resolve[0]['foo'] = 'Hai';       
                $resolve[1]['foo'] = 'Helo';     
                return $resolve;
            }
        }
        add_filter( 'graphql_root_queries', 'wp_graphql_custom_table_query' );
        function wp_graphql_custom_table_query( $fields ) {
            $fields['customTable'] = [      
                'type' => \WPGraphQL\Types::list_of( new FooBarType() ),
                'description' => __( 'Returns a random Dad joke', 'wp-graphql' ),
                'resolve' => function() {             
                     return MyCustomTableClass::getItems(); 
                },
            ];
            return $fields;
        }

**Comment by Decruse** [comment]
@jasonbahl  @Helensamuel 
I  also stuck in filtering the custom table. Is create any schema for this

**Comment by prionkor** [comment]
what are the full list of default `\WPGraphQL\Types` I am looking at the source code, can not seem to find them.
