### ISSUE TITLE
Fatal error in `WPConnectionType` when calling `str_ends_with()` on PHP < 8.0

### ISSUE THREAD

**Issue by jj449** [wp-graphql/wp-graphql#2991]
### Description

after installing  wp-grapthql plugin on wordpress , curl to endpoint or use browser to reach end point https://my-site/grapthql ，
will get internal 500 error .  And if try to run IDE from left side menu , see 500 error too . 

### Steps to reproduce

as mentioned above , If open wordpress debug mode  , then browser  go to end point , will see error as : 

`Fatal error: Uncaught Error: Call to undefined function WPGraphQL\Type\str_ends_with() in /var/www/html/wa.soshow.app/wp-content/plugins/wp-graphql/src/Type/WPConnectionType.php:252 Stack trace: #0 /var/www/html/wa.soshow.app/wp-content/plugins/wp-graphql/src/Type/WPConnectionType.php(398): WPGraphQL\Type\WPConnectionType->get_edge_interfaces(Array) #1 /var/www/html/wa.soshow.app/wp-content/plugins/wp-graphql/src/Type/WPConnectionType.php(647): WPGraphQL\Type\WPConnectionType->register_connection_edge_type() #2 /var/www/html/wa.soshow.app/wp-content/plugins/wp-graphql/src/Type/WPConnectionType.php(198): WPGraphQL\Type\WPConnectionType->register_connection() #3 /var/www/html/wa.soshow.app/wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php(1142): WPGraphQL\Type\WPConnectionType->__construct(Array, Object(WPGraphQL\Registry\TypeRegistry)) #4 /var/www/html/wa.soshow.app/wp-content/plugins/wp-graphql/access-functions.php(515): WPGraphQL\Registry\TypeRegistry->register_connection(Array) #5 /var/www/html/wa.soshow.app/w in /var/www/html/wa.soshow.app/wp-content/plugins/wp-graphql/src/Type/WPConnectionType.php on line 252
There has been a critical error on this website.`

### Additional context

![image](https://github.com/wp-graphql/wp-graphql/assets/58848201/8ba3409b-41b1-4822-b51b-8d4ac3962446)

### WPGraphQL Version

latest - 1.18.2 

### WordPress Version

5.x

### PHP Version

7.x

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jj449** [comment]
I found it's related to php version ， from php error message ， str_ends_with()  undefined , and str_ends_with() start from php 8. 
So if your php version lower than 8.0 , you encounter this  error . 

How to fix it?  Since php 7.x  without  str_ends_with()  , you must make one to php to run correctly : 

in wp-content/plugins/wp-graphql/src/Type/WPConnectionType.php ,  find line 238  , that's where problem from , add a check before this line 
`if (!function_exists('str_ends_with')) {
	function str_ends_with($haystack, $needle)
		{
			return $needle !== '' ? substr($haystack, -strlen($needle)) === $needle : true;
		}
}`

save WPConnectionType.php , then try to reach end point again , or run IDE from wordpress's left side menu. Now it woeks ~ Hope this help someone.

**Comment by jj449** [comment]
the final   get_edge_interfaces function in WPConnectionType.php , should be like this : 

![image](https://github.com/wp-graphql/wp-graphql/assets/58848201/e1513788-2fd5-455c-a8c3-de106a51d605)

**Comment by justlevine** [comment]
WordPress provides this as a polyfill in 5.9+ but looks like WPCS isn't catching it because a different dev-deps is installing symfony's polyfill. 

@jj449
1. Can you please provide the **exact** PHP and WordPress version you are using? I want to make sure other things arent getting by the code sniffs.
2. In the interim, instead of modifying the plugin and sticking that function definition inside a foreach loop, you should put the entire `if ( ! function_exists(.....){ ...}` into your own `functions.php` file.

**Comment by jj449** [comment]
my environment : 

wordpress version : 5.6.10
php 7.3.31

**Comment by jj449** [comment]
**" you should put the entire  bla bla fix codes  into your own functions.php file  "** 
 
 yes , you are right , man ~  thanks ~

**Comment by jj449** [comment]
@justlevine 

I  didn't fork this repo ,  Would  you like to do the PR & fix ?

**Comment by justlevine** [comment]
@jj449 There is already a fix pending in #2992 , feel free to try it out
