### ISSUE TITLE
Querying parent info in preview mode returns the current post info.

### ISSUE THREAD

**Issue by jeremyProwseYS** [wp-graphql/wp-graphql#3001]
### Description

On querying a posts parent info outside of preview mode everything works as expected. However when "asPreview" is passed into the query, or when the preview connection is used in the query the returned parent info equates to the current post.

For example if you have a postId of '2' that is a child of postId '1', when querying the parent of '2' outside of preview mode it returns what would be expected: '1'. When using preview mode and the same query object for postId '2' the parent id returned is now '2'.

I presume this is to do with previews / revisions and their relationship to the post they spawn from, specifically what is being set in terms of the parent information when a preview is requested.

Please see attached screenshots for the current behaviour.

![using-asPreview-param](https://github.com/wp-graphql/wp-graphql/assets/70550299/a722422e-e744-47e8-a4ca-575d7b7a319d)
![using-preview-connection](https://github.com/wp-graphql/wp-graphql/assets/70550299/b3a97faf-5352-47e5-a8ef-4b61b6dad98c)

### Steps to reproduce

If given the above example of page '2' being a child of page '1', the below query should return '1' when targeting `page.parent.id`. Currently it returns the id of the original version of the previewed page.

```
query MyPageQuery {
  page(id: 2, idType: DATABASE_ID, asPreview: true) {
    databaseId
    title
    parent {
      node {
        ... on Page {
          databaseId
          title
        }
      }
    }
  }
}
```

### WPGraphQL Version

1.19.0

### WordPress Version

6.4.2

### PHP Version

8.2.10

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [ ] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Hey @jeremyProwseYS ,

What you're describing is intentional behavior (due to how post revisions are stored, like you mentioned), and is documented as such in the description for the `asPreview` arg (which is sadly not the most discoverable).

You can find the active discussion around this behavior and a workaround in #2876 .

(Closing as duplicate).

**Comment by jeremyProwseYS** [comment]
@justlevine Thanks for your reply, I had already figured a work-around using the `revisionOf` prop to traverse the true parent structure for the post. However this is just that, a "workaround" and I was wondering if there were any plans to reintroduce expected behaviour for the `parent` prop when preview is concerned. Surely the `previewOf` prop suggested by Jason in the [linked post #2876](https://github.com/wp-graphql/wp-graphql/issues/2876) would make more sense to house the info currently returned in the `parent` prop?

**Comment by justlevine** [comment]
> Surely the `previewOf` prop suggested by Jason in the [linked post #2876](https://github.com/wp-graphql/wp-graphql/issues/2876) would make more sense to house the info currently returned in the `parent` prop

Exactly. Please share any feedback you might have on #2876 so we can keep the discussion all in one place 🙏
