### ISSUE TITLE
nodeByUri return null for some custom CPT

### ISSUE THREAD

**Issue by MKlblangenois** [wp-graphql/wp-graphql#3016]
### Description

When I register new CPT's, they are not always returned when I perform a nodeByUri query. 

### Steps to reproduce

1. Register a new CPT
```php
// source : https://faustjs.org/guide/setting-up-custom-post-types-cpts-in-faust#before-you-start
function register_movies_cpt() {
	$args = [
		'label' => esc_html__('Movies', 'twentytwentyone'),
		'public' => true, // If the CPT is not public, it can not be properly resolved in Faust.
		'publicly_queryable' => true,
		'show_ui' => true,
		'show_in_rest' => true,
		'rest_base' => '',
		'rest_controller_class' => 'WP_REST_Posts_Controller',
		'rest_namespace' => 'wp/v2',
		'has_archive' => true, // Important for creating an archive in Faust.
		'show_in_menu' => true,
		'show_in_nav_menus' => true,
		'delete_with_user' => false,
		'exclude_from_search' => false,
		'capability_type' => 'post',
		'map_meta_cap' => true,
		'hierarchical' => false,
		'can_export' => false,
		'rewrite' => ['slug' => 'movies', 'with_front' => true],
		'query_var' => true,
		'supports' => ['title', 'editor', 'thumbnail'],
		'show_in_graphql' => true,
		'graphql_single_name' => 'Movie',
		'graphql_plural_name' => 'Movies',
	];

	register_post_type('movies', $args);
}

add_action('init', 'register_movies_cpt');
```

2. Make a query in you GraphiQL explorer
```graphql
query Archives {
  movieArchive: nodeByUri(uri: "/movies") {
    __typename
    ... on ContentType {
      label
    }
  }
}
```

3. You should get a `null` to your `movieArchive`

### Additional context

For reasons unknown to me, some CPTs work but others don't, like the example below, which uses the exact same register function
<img width="1251" alt="image" src="https://github.com/wp-graphql/wp-graphql/assets/42929225/9285fd57-2563-40f7-b1fb-65d148721220">

### WPGraphQL Version

1.19.0

### WordPress Version

6.4.2

### PHP Version

8.1.23

### Additional environment details

No WPGraphQL extensions enable, only default theme and WPGraphQL

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Hey @MKlblangenois 

From your code snippet, you're setting `rewrite['with_front']` to `true`, which means the URL should be prepended with the prefix slug you set in the permalink settings.

Not sure if this is a bug or a usage issue, but a few things to narrow it down:

- What's the result of `contentTypes.nodes.**url**`?
- What is the permalink structure on your site?
- Do you get the expected if you change `with_front` to `false`?
- Can you share the `$args` you're using to register the custom `Event` type?

**Comment by jasonbahl** [comment]
Also, after registering a post type in code, make sure you flush your permalinks.

**Comment by MKlblangenois** [comment]
In fact, the saving of the permalinks did not completely flush them, I had to, in addition, empty the cache of my hosting (Kinsta). Thank you for your help!
