### ISSUE TITLE
Let's Revamp Our IDE 🚀

### ISSUE THREAD

**Issue by josephfusco** [wp-graphql/wp-graphql#3019]
# Hey WPGraphQL Community! Let's Revamp Our IDE 🚀

## What's Cooking?

We're sprucing up our WPGraphQL IDE - think of it as giving it a fresh coat of paint and some cool new gadgets. Why? Because we want to make your development experience smoother, more intuitive, and totally in sync with the latest in the GraphQL world.

## Why This Rocks

- **Less Hassle, More Hustle**: We're switching to the official GraphiQL package. Less maintenance for us, more cool stuff for you.
- **Keeping Up with the GraphQL Joneses**: We're not just updating; we're aligning ourselves with the latest and greatest in the GraphQL universe.
- **Future-Proofing**: We're setting the stage for awesome new features down the line. Think custom scalars and beyond!
- **Everywhere, All the Time**: Want to use the IDE on the front-end, in wp-admin, or on the moon? (Okay, maybe not the moon). We've got you covered.
- **Test It Like You Mean It**: We know, the current E2E tests are a bit of a bummer. We're on it!

## Who Benefits?

All of us! Whether you're a WPGraphQL newbie or a seasoned pro, these updates are going to make your life easier.

## What's New and What's Going?

- **Goal**: We're not reinventing the wheel. We want to match what we've got, but with the new GraphiQL goodness.
- **Saying Goodbye**: No more `graphiql_explorer_operation_action_menu_items` and the old navy blue sidebar. It's time for something sleeker.
- **Routes and More**: 
    - Your usual GraphQL server settings? They're staying put.
    - The GraphiQL IDE page is getting a major facelift. Think minimalism, more power under the hood.
    - Help pages? Let's just link to the docs and keep things tidy.

## Join the Party 🎉

Got ideas, feedback, or just want to see what's happening? Jump into the [WPGraphQL IDE GitHub repo](https://github.com/wp-graphql/wpgraphql-ide). Your voice matters!

## The Endgame

We merge this baby into the core once we're all happy with it. The old repo gets a fond farewell, and we document any big changes to make your transition smooth.

---

We're super excited about this, and we hope you are too! Let's make WPGraphQL IDE better, together. 🚀💻🎉

**Comment by jasonbahl** [comment]
Comments are locked on this. 

We'll be discussing technical details, feature requests, etc over on the WPGraphiQL IDE repo. 

👉🏻  https://github.com/wp-graphql/wpgraphiql-ide

**Comment by josephfusco** [comment]
We can likely close this once WPGraphQL IDE is approved on WordPress.org (allowing it to be installed inline on the [extension's page](https://github.com/wp-graphql/wp-graphql/issues/3049))

**Comment by josephfusco** [comment]
WPGraphQL IDE has been initially reviewed with feedback tracked here https://github.com/wp-graphql/wpgraphql-ide/issues/189. Closing this as any follow up discussion should happen in their respective issues.

Thanks WordPress.org plugin review team! 🙌

**Comment by justlevine** [comment]
@josephfusco @jasonbahl is the intent 
- to _remove_ the existing GraphiQL from the core plugin once the extension is approved on .org and we release a breaking change here?
- to _eventually_ bring a snapshot of changes from the IDE into WPGraphQL core, and use the WPGraphQL IDE plugin for 'bleeding edge' (similar to the Gutenberg plugin's relationship to Core WP)?

Either way, so long as the _old_ ide is bundled in core, I suggest we either leave this ticket open, or create a new one to track implementing the above decision.
