### ISSUE TITLE
Menu returning wrong items

### ISSUE THREAD

**Issue by rodrigo-martins** [wp-graphql/wp-graphql#3029]
### Description

If there is no `location` menu saved yet, instead of a response being an empty array, it is returning an array of random menu items from another `location`

### Steps to reproduce

1. Register a menu (eg.: functions.php) 
 ```
register_nav_menus(
	  array(
		  'primary' => esc_html__('Primary menu', 'my-blocks'),
           'secondary' => esc_html__('Secondary menu', 'my-blocks'),
		  'contact'  => esc_html__('Contact menu', 'my-blocks'),
	  )
  );
```
3. Create items for primary and secondary menu on wordpress panel
4. ![image](https://github.com/wp-graphql/wp-graphql/assets/11780628/110d9e35-d86b-419a-8cea-13fe1ff1e493)
6. ![image](https://github.com/wp-graphql/wp-graphql/assets/11780628/4130bfa2-8e53-4a17-839a-f99f99ef53b1)
7. Go to GraphQL IDE and run:
```
query NewQuery {
  menuItems(where: {location: CONTACT}) {
    nodes {
      id
      label
    }
  }
}
```
9. The result is an aleatory items  from primary and secondary instead of empty array in "nodes"
```
{
  "data": {
    "menuItems": {
      "nodes": [
        {
          "id": "cG9zdDo0Ng==",
          "label": "Platform"
        },
        {
          "id": "cG9zdDo0Mw==",
          "label": "facebook"
        },
        {
          "id": "cG9zdDozNw==",
          "label": "Privacy Policy"
        },
      ]
    }
  }
}
```

### WPGraphQL Version

Version 1.20.0 

### WordPress Version

6.4.2

### PHP Version

8.2

### Additional environment details

WPGraphQL Blocks  - Version 2.1.1
Wordpress Multsites (directory)

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [ ] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Confirmed on a non-multisite install, no plugins, using TT1 and WPGraphQL 1.20.0. WP 6.4.3 + PHP 8.1.15



![Image](https://github.com/wp-graphql/wp-graphql/assets/29322304/3b33afef-74b9-45cf-83c1-4c40fbb4c972)
