### ISSUE TITLE
Post Author Name node repeats when fetching multiple posts at once

### ISSUE THREAD

**Issue by shipmaal** [wp-graphql/wp-graphql#3030]
### Description

I am trying to add the author's name to the display of my posts. The issue is when I fetch multiple posts. All of the author names take on the author name of the last post. This seems to be a bug but I will admit that I am new to WPGraphQL so it's entirely possible it's something wrong on my end. Thanks for the help!

### Steps to reproduce

Run the following query on your posts:
```
query GetPosts {
  posts(first: 5) {
      nodes {
        id
        author {
          node {
            name
          }
        }
    }
  }
}
```
For me, all 5 author names are the same:
```
"data": {
    "posts": {
      "nodes": [
        {
          "id": "cG9zdDoyMTIyNzE=",
          "author": {
            "node": {
              "name": "Olivia Hahn"
            }
          }
        },
        {
          "id": "cG9zdDoyMTIyNjQ=",
          "author": {
            "node": {
              "name": "Olivia Hahn"
            }
          }
        },
        {
          "id": "cG9zdDoyMTIyNjA=",
          "author": {
            "node": {
              "name": "Olivia Hahn"
            }
          }
        },
        {
          "id": "cG9zdDoyMTIyNTc=",
          "author": {
            "node": {
              "name": "Olivia Hahn"
            }
          }
        },
        {
          "id": "cG9zdDoyMTIyNTA=",
          "author": {
            "node": {
              "name": "Olivia Hahn"
            }
          }
        }
      ]
    }
  },
```

When I try and fetch the author of an individual post, it gives a different name, and fetching the last post returns the author name Olivia Hahn. 

### WPGraphQL Version

1.19

### WordPress Version

6.4.2

### PHP Version

8.2

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
@shipmaal I'm unable to reproduce this. I can query posts and the author and I get the author as expected. 

![CleanShot 2024-01-31 at 11 09 58](https://github.com/wp-graphql/wp-graphql/assets/1260765/41ac1277-5ad0-487a-b8fb-4e8b8120f3d7)

Are you able to reproduce this in an environment with _only_ WPGraphQL active and no other plugins? 

Are you using any plugins like "Co Authors Plus" or similar where the "author" is not actually a WordPress user?

**Comment by shipmaal** [comment]
@jasonbahl It looks like we are, sorry for not checking that beforehand. Is there an extension that allows us to use the Co Authors Plus plugin with WPGraphQL?

**Comment by jasonbahl** [comment]
@shipmaal there's no "official" one that I maintain or have contributed to. We considered exploring it (https://github.com/wp-graphql/wp-graphql-co-authors-plus) many years ago (2017) but didn't end up seriously pursuing it. 

I found this extension that looks like it might work: https://github.com/pascalroget/co-authors-plus-wp-graphql
