### ISSUE TITLE
query with language parameter

### ISSUE THREAD

**Issue by scesini** [wp-graphql/wp-graphql#3075]
### Description

Looks like the where with language condition is not working anymore.
Some idea how to replace this?

### Steps to reproduce

            'query' => '{
                products(last: 10, where: { language: "en" }) {
                    nodes {
                        name
                        link
                    }
                }
            }'

### WPGraphQL Version

1.22.1

### WordPress Version

6.4.3

### PHP Version

8.0.30

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
@scesini 

1. Why is the title in ALL CAPS?

2. You ostensibly chose to fill out a Bug Report, but then you write up what seems to be a usage question. Is this a usage question, and if so have you tried have you tried asking in Slack or GitHub Discussions?

3. You've confirmed that you " disabled ALL plugins except for WPGraphQL.", but then you ask a question about `language` and `products`, _neither_ of which are core WordPress / WPGraphQL features. Are you using Woo, EDD, or your own custom post type for products? And what Plugin/extension are you using to handle the languages? 
Regardless of the answer, you probably are better off asking in the repo for those particular extensions...

If there is a _bug_ somewhere lost in all of this, please update the ticket to elaborate on what it is, provide replication steps, and confirm that you actually searched the existing GitHub issues, and that it's coming from Core WPGraphQL and not an external plugin.

**Comment by scesini** [comment]
I have used the query I shared a few months ago and looks like is not working anymore.
![01](https://github.com/wp-graphql/wp-graphql/assets/52512832/dda3921b-06bd-402f-a29c-19c88c13c1cb)

And I need to have enabled the plugins:
- WPML GraphQL
- WPGraphQL WooCommerce (WooGraphQL)
- WPML Multilingual CMS
- WooCommerce Multilingual & Multicurrency
- WPML GraphQL

**Comment by justlevine** [comment]
Thank you for the follow up, @scesini 

As expected, you are relying on the WPGraphQL for WooCommerce (free) and the WPML GraphQL (paid) extensions. Have you updated either of them recently? If so you found the culprit. Check the changelogs to see if/how the query changed and how you should be querying for products for a certain language.

If not, you can open up the Documentation Explorer on the right side of the GraphQL IDE and search the term "language". That should show you all the fields in your schema that accept the arg or return it as a field. You can use that to redesign your question.

If you still cant get it sorted, I suggest you reach out to WPML's premium support directly, or ask in the `#woocommerce` channel on the WPGraphQL Slack for example GraphQL queries.

**Comment by justlevine** [comment]
Hey @scesini ,

It's been a few weeks with no response, so I'm going to assume you found the culprit among your other plugins in your tech stack stack and close this ticket out.

If you're able to replicate this as a regression in WPGraphQL core (i.e. all your extensions are on the _same versions_, but one version of **WPGraphQL** works and the next version doesn't), please comment back here and we'll reopen this for investigation 🙏
