### ISSUE TITLE
Missing field argument lead to broken Documentation Explorer

### ISSUE THREAD

**Issue by datproto** [wp-graphql/wp-graphql#3115]
### Description

When upgrading the `wpgraphql` to 1.24.0, the document cannot be loaded due to missing some `field argument`.
This lead to the broken of `Documentation Explorer` (please check image attachment below).

### Steps to reproduce

1. Install wpgraphql version 1.24.0
2. Open `GraphiQL IDE`
3. The error appear at the preview window right at the start

![image](https://github.com/wp-graphql/wp-graphql/assets/46285472/6625aae4-d9c3-44a0-b492-1ed00ea9ea57)

### Additional context

Other installed `wpgraphql`:
- WPGraphQL IDE: 1.1.8
- WPGraphQL for ACF: 2.2.0
- WPGraphQL Smart Cache: 1.3.2
- WPGraphQL for Gravity Forms: 0.12.6
- WPGraphQL JWT Authentication: 0.7.0
- WPGraphQL WooCommerce (WooGraphQL): 0.19.0

### WPGraphQL Version

1.24.0

### WordPress Version

6.5.2

### PHP Version

8.1

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
@datproto closing as this is being tracked in #3108. We're close to having a fix ready for release.
