### ISSUE TITLE
Querying Menu Locations are inconsistent

### ISSUE THREAD

**Issue by arcylen-gg** [wp-graphql/wp-graphql#3147]
### Description

I tried querying menus by locations, but the MenuLocationEnum are inconsistent.

### Steps to reproduce

1. On Appearance > Menus -  Added 4 Menus, Primary (Tagged as Primary), Secondary Menu (Tagged as Secondary), Footer and Side Menu.
![image](https://github.com/wp-graphql/wp-graphql/assets/20926518/f9a85067-8aaa-4718-bf0e-fd1d7867ae61)

2. Tried to query them on the IDE, only shows PRIMARY AND FOOTER are the only options for MenuLocationEnum
![image](https://github.com/wp-graphql/wp-graphql/assets/20926518/1a7e7503-a2b3-4ac9-96e8-acae0ef49217)

3. Primary (headersMenu) do have correct result but the secondary menus and footerMenus, I tried querying it as FOOTER, the results are the one from my secondary menu.
![image](https://github.com/wp-graphql/wp-graphql/assets/20926518/14254b1d-65a8-42aa-a0d6-ddc7cbfc42cd)

### WPGraphQL Version

1.26.0

### WordPress Version

6.5.3

### PHP Version

8.1.16

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by gaiousantonio0909** [comment]
Same issue as well

**Comment by justlevine** [comment]
This was closed pretty quickly so I'm assuming the OP figured out the issue - menus are private unless they're assigned to a location, and the query in GraphiQL was run as an unauthenticated user (note the lack of green dot on the user profile pic in the screenshot).

@gaiousantonio0909 if you're still running into issues running this as authenticated (click the profile icon so a green dot is visible) please open up a new issue with all the information requested by the template.
