### ISSUE TITLE
Unexpected token '<', \"<html>\r\n<h\"... is not valid JSON

### ISSUE THREAD

**Issue by olicarignan** [wp-graphql/wp-graphql#3158]
### Description

I have just installed the wp-grapghql and it is constantly in an error state, I made a really basic query to show what the network tab shows on submit (401). I have tired uninstalling all my plugins but nothing seems to fix it.

![Screenshot 2024-06-25 at 1 34 48 PM](https://github.com/wp-graphql/wp-graphql/assets/53198251/5f807ba9-142b-44df-ab10-4cbc17b432b5)

### Steps to reproduce

Any type of query gives me an error, here is another example

![Screenshot 2024-06-25 at 1 42 56 PM](https://github.com/wp-graphql/wp-graphql/assets/53198251/fadbca69-3c01-4446-b4de-f708ff02a042)

### WPGraphQL Version

1.27.0

### WordPress Version

6.5.5

### PHP Version

7.4.33

### Additional environment details

I am planning on using this paired with wp-graphql for ACF and ACF but both are currently disabled

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [X] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Hey @olicarignan 

Please read the debugging steps in [this article](https://www.wpgraphql.com/docs/debugging) and share the [network response](https://www.wpgraphql.com/docs/debugging#checking-the-response) for that red `index.php?graphql` request.

**Comment by olicarignan** [comment]
Oh I just tried a different browser and it appears to be working fine, do you have any known issues with Arc Browser?

**Comment by justlevine** [comment]
> Oh I just tried a different browser (Safari) and it appears to be working fine, do you have any known issues with Arc Browser?

Nope. Usually a 401 Unauthorized like that means your login session is no longer valid Try doing a hard refresh of the screen and logging back into WordPress. If it persists after that and you've already disabled _all_ your plugins besides for WPGraphQL, and share a copy of your Tools > Site Health output so we can rule out an issue with your server config.

**Comment by olicarignan** [comment]
I did a hard refresh as well as logged out and back in but the issue is persisting, here is my Site Health page, I have disabled everything except WPGraphQL, although I see that it says I have 2 active plugins which is odd.

![Screenshot 2024-06-25 at 4 01 09 PM](https://github.com/wp-graphql/wp-graphql/assets/53198251/b354699e-e7d8-49ca-9822-2b2989f73021)

**Comment by jasonbahl** [comment]
@olicarignan do you have an .htaccess password configured on the site? this looks like maybe something related to GraphiQL not being able to communicate because it's blocked by an .htaccess password

**Comment by olicarignan** [comment]
Hi sorry for the delayed response, no we do not have any .htaccess password on the site, we did have basic auth which I now turned off but I am still getting the same error.

**Comment by justlevine** [comment]
Sounds like mu-plugins from the host are what's getting in the way. (Iirc there's been previous  issues or slack/discord messages with this on ionos and a few others)

 @olicarignan instead of sharing the `Status` can u share the health check _Info_ which should have all the mu plugins listed in addition to other config information that might help.

**Comment by olicarignan** [comment]
### wp-core ###

version: 6.5.5
site_language: en_US
user_language: en_US
timezone: America/Los_Angeles
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: closed
environment_type: staging
user_count: 2
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/wp_i338u5/rattlecom.stage.site
wordpress_size: 28.83 GB (30959785225 bytes)
uploads_path: /home/wp_i338u5/rattlecom.stage.site/wp-content/uploads
uploads_size: 113.20 KB (115913 bytes)
themes_path: /home/wp_i338u5/rattlecom.stage.site/wp-content/themes
themes_size: 3.65 MB (3828612 bytes)
plugins_path: /home/wp_i338u5/rattlecom.stage.site/wp-content/plugins
plugins_size: 118.75 MB (124518527 bytes)
database_size: 697.18 MB (731046856 bytes)
total_size: 29.63 GB (31819295133 bytes)

### wp-active-theme ###

name: Reddle Child (reddle-child)
version: undefined
author: undefined
author_website: http://automattic.com/
parent_theme: Reddle (reddle)
theme_features: core-block-patterns, widgets-block-editor, post-thumbnails, automatic-feed-links, menus, post-formats, custom-background, custom-header, jetpack-responsive-videos, infinite-scroll, widgets
theme_path: /home/wp_i338u5/rattlecom.stage.site/wp-content/themes/reddle-child

### wp-parent-theme ###

name: Reddle (reddle)
version: 1.3.5
author: Automattic
author_website: https://wordpress.com/themes/
theme_path: /home/wp_i338u5/rattlecom.stage.site/wp-content/themes/reddle

### wp-themes-inactive (1) ###

Twenty Twenty-Four: version: 1.1, author: the WordPress team

### wp-plugins-active (16) ###

Advanced Custom Fields: version: 6.3.3, author: WP Engine
CoCart API - Decoupling Made Easy for WooCommerce: version: 4.1.1, author: CoCart Headless, LLC
CoCart CORS Support: version: 1.0.6, author: CoCart Headless, LLC
Constant Contact Forms for WordPress: version: 2.6.0, author: Constant Contact
DreamHost Panel Login: version: 1.0.0, author: DreamHost, danielbachhuber
Headless Mode: version: 0.4.0, author: Josh Pollock, Jason Bahl, and Ben Meredith
MWW Scheduled Post Trigger: version: 3.2, author: Moss Web Works
Nginx Helper: version: 2.2.5, author: rtCamp
Side Cart WooCommerce: version: 2.5, author: XootiX
VaultPress: version: 3.0.0, author: Automattic
WooCommerce: version: 9.0.2, author: Automattic
WooCommerce PayPal Payments: version: 2.8.1, author: WooCommerce
Wordfence Security: version: 7.11.6, author: Wordfence
WPGraphQL: version: 1.27.0, author: WPGraphQL
WPGraphQL for ACF: version: 2.2.0, author: WPGraphQL, Jason Bahl
WP Remote: version: 5.56, author: DreamHost

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
imagick_version: 3.6.0
file_uploads: 1
post_max_size: 505M
upload_max_filesize: 500M
max_effective_size: 500 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 768
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
	imagick::RESOURCETYPE_TIME: 1.844674407371E+19
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DNG, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, JBG, JBIG, JNG, JNX, JPE, JPEG, JPG, JPS, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBP, WMV, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.50

### wp-server ###

server_architecture: Linux 5.4.0-1071-kvm x86_64
httpd_software: nginx/1.25.3
php_version: 7.4.33 64bit
php_sapi: fpm-fcgi
max_input_variables: 1500
time_limit: 500
memory_limit: 256M
max_input_time: 500
upload_max_filesize: 500M
php_post_max_size: 505M
curl_version: 7.68.0 OpenSSL/1.1.1f
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: false
current: 2024-07-02T20:30:58+00:00
utc-time: Tuesday, 02-Jul-24 20:30:58 UTC
server-time: 2024-07-02T13:30:57-07:00

### wp-database ###

extension: mysqli
server_version: 8.0.30-0ubuntu0.20.04.2
client_version: mysqlnd 7.4.33
max_allowed_packet: 33554432
max_connections: 200

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/wp_i338u5/rattlecom.stage.site/wp-content
WP_PLUGIN_DIR: /home/wp_i338u5/rattlecom.stage.site/wp-content/plugins
WP_MEMORY_LIMIT: 192M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: staging
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### constant-contact-forms ###

0: 2.6.0
1: No
2: No
3: No
4: No
5: Access token needs refreshed
6: No
7: No
8: No
9: Folder: Writable, File: Writable
10: No
11: Unexpected HTTP response code: 401

### acf ###

version: 6.3.3
plugin_type: Free
ui_field_groups: 2
php_field_groups: 0
json_field_groups: 0
rest_field_groups: 0
graphql_field_groups: 2
post_types_enabled: true
ui_post_types: 11
json_post_types: 0
ui_taxonomies: 10
json_taxonomies: 0
rest_api_format: light
admin_ui_enabled: true
field_type-modal_enabled: true
field_settings_tabs_enabled: false
shortcode_enabled: true
registered_acf_forms: 0
json_save_paths: 1
json_load_paths: 1

**Comment by justlevine** [comment]
Yup, if I had to guess it's `Dreamhost Panel Login` which handles their sso implementation. Bet Iif you look at the code you'll see an ugly use of `global $pagenow`.

Not entirely sure why it's specifically affecting Arc (could be the way theyre setting cookies, or rather in one of the browsers you logged in at some point via their panel and the other you didn't). 

Debugging steps (try in _both_ browsers)
1. Clear the cookies and local storage for the WP admin site.
2. Log in using wp-admin and _not_ Dreamhost's magic link.
3. Try the IDE and check the network response
4. Repeat 1-3, but instead of manually logging in, use the dreamhost panel link.

This will hopefully stop the discrepancy between Arc/other browsers and verify the source of the error and the next steps (be it conditionally unregistering their hook in a GraphQL request, talking to Dreamhost support, or searching for a new culprit).

**Comment by justlevine** [comment]
I also just noticed this is a _staging_ site, not production. You _sure_ Dreamhost isn't enforcing some sort of staging-specific access protection (like @jasonbahl noted) beyond the basic auth you disabled? And does it work on localhost (with _or_ without those Dreamhost mu-plugins)?

**Comment by olicarignan** [comment]
Hey sorry for the delay I ended up changing the setup (no longer in a Dreamhost staging environment) and now everything is working as expected so that was definitely the issue. Thank you for your help

**Comment by jasonbahl** [comment]
Thanks for the follow up @olicarignan!
