### ISSUE TITLE
1.27.1 -- Missing Admin Menu - Missing icon image '/img/wpgraphql-elephant.svg'

### ISSUE THREAD

**Issue by Jonathan-Garber** [wp-graphql/wp-graphql#3164]
### Description

1.27.1 -- Missing Admin Menu - Missing icon image '/img/wpgraphql-elephant.svg'
No such file or directory on upgrading to 1.27.1
Admin menu is now missing

I am not even seeing any svg files in the plugin folders here?
but then again it's late for me here and I am tired.

### Steps to reproduce

Upgrade to latest version 1.27.1
Go to /wp-admin
Note that the GraphQL link is now missing from admin menu.

Note the entry in error logs referencing no such file or directory

### WPGraphQL Version

1.27.1

### WordPress Version

6.5.5

### PHP Version

8.2.20

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by Jonathan-Garber** [comment]
I may be a bit tired as it is very late where I am so maybe I am overlooking some reason for this change.
But the previous version simply used the data URI for the menu icon.

1.27.0

```		// Top level menu page should be labeled GraphQL
		add_menu_page(
			__( 'GraphQL', 'wp-graphql' ),
			__( 'GraphQL', 'wp-graphql' ),
			'manage_options',
			'graphiql-ide',
			[ $this, 'render_graphiql_admin_page' ],
			'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0MDAgNDAwIj48cGF0aCBmaWxsPSIjRTEwMDk4IiBkPSJNNTcuNDY4IDMwMi42NmwtMTQuMzc2LTguMyAxNjAuMTUtMjc3LjM4IDE0LjM3NiA4LjN6Ii8+PHBhdGggZmlsbD0iI0UxMDA5OCIgZD0iTTM5LjggMjcyLjJoMzIwLjN2MTYuNkgzOS44eiIvPjxwYXRoIGZpbGw9IiNFMTAwOTgiIGQ9Ik0yMDYuMzQ4IDM3NC4wMjZsLTE2MC4yMS05Mi41IDguMy0xNC4zNzYgMTYwLjIxIDkyLjV6TTM0NS41MjIgMTMyLjk0N2wtMTYwLjIxLTkyLjUgOC4zLTE0LjM3NiAxNjAuMjEgOTIuNXoiLz48cGF0aCBmaWxsPSIjRTEwMDk4IiBkPSJNNTQuNDgyIDEzMi44ODNsLTguMy0xNC4zNzUgMTYwLjIxLTkyLjUgOC4zIDE0LjM3NnoiLz48cGF0aCBmaWxsPSIjRTEwMDk4IiBkPSJNMzQyLjU2OCAzMDIuNjYzbC0xNjAuMTUtMjc3LjM4IDE0LjM3Ni04LjMgMTYwLjE1IDI3Ny4zOHpNNTIuNSAxMDcuNWgxNi42djE4NUg1Mi41ek0zMzAuOSAxMDcuNWgxNi42djE4NWgtMTYuNnoiLz48cGF0aCBmaWxsPSIjRTEwMDk4IiBkPSJNMjAzLjUyMiAzNjdsLTcuMjUtMTIuNTU4IDEzOS4zNC04MC40NSA3LjI1IDEyLjU1N3oiLz48cGF0aCBmaWxsPSIjRTEwMDk4IiBkPSJNMzY5LjUgMjk3LjljLTkuNiAxNi43LTMxIDIyLjQtNDcuNyAxMi44LTE2LjctOS42LTIyLjQtMzEtMTIuOC00Ny43IDkuNi0xNi43IDMxLTIyLjQgNDcuNy0xMi44IDE2LjggOS43IDIyLjUgMzEgMTIuOCA0Ny43TTkwLjkgMTM3Yy05LjYgMTYuNy0zMSAyMi40LTQ3LjcgMTIuOC0xNi43LTkuNi0yMi40LTMxLTEyLjgtNDcuNyA5LjYtMTYuNyAzMS0yMi40IDQ3LjctMTIuOCAxNi43IDkuNyAyMi40IDMxIDEyLjggNDcuN00zMC41IDI5Ny45Yy05LjYtMTYuNy0zLjktMzggMTIuOC00Ny43IDE2LjctOS42IDM4LTMuOSA0Ny43IDEyLjggOS42IDE2LjcgMy45IDM4LTEyLjggNDcuNy0xNi44IDkuNi0zOC4xIDMuOS00Ny43LTEyLjhNMzA5LjEgMTM3Yy05LjYtMTYuNy0zLjktMzggMTIuOC00Ny43IDE2LjctOS42IDM4LTMuOSA0Ny43IDEyLjggOS42IDE2LjcgMy45IDM4LTEyLjggNDcuNy0xNi43IDkuNi0zOC4xIDMuOS00Ny43LTEyLjhNMjAwIDM5NS44Yy0xOS4zIDAtMzQuOS0xNS42LTM0LjktMzQuOSAwLTE5LjMgMTUuNi0zNC45IDM0LjktMzQuOSAxOS4zIDAgMzQuOSAxNS42IDM0LjkgMzQuOSAwIDE5LjItMTUuNiAzNC45LTM0LjkgMzQuOU0yMDAgNzRjLTE5LjMgMC0zNC45LTE1LjYtMzQuOS0zNC45IDAtMTkuMyAxNS42LTM0LjkgMzQuOS0zNC45IDE5LjMgMCAzNC45IDE1LjYgMzQuOSAzNC45IDAgMTkuMy0xNS42IDM0LjktMzQuOSAzNC45Ii8+PC9zdmc+'
		);
```


1.27.1

```
$svg_file = file_get_contents( WPGRAPHQL_PLUGIN_DIR . '/img/wpgraphql-elephant.svg' );

		if ( false === $svg_file ) {
			return;
		}

		$svg_base64 = base64_encode( $svg_file );

		// Top level menu page should be labeled GraphQL
		add_menu_page(
			__( 'GraphQL', 'wp-graphql' ),
			__( 'GraphQL', 'wp-graphql' ),
			'manage_options',
			'graphiql-ide',
			[ $this, 'render_graphiql_admin_page' ],
			'data:image/svg+xml;base64,' . $svg_base64
		);
```

Why was there a need to make changes here?

Now it requires a separate file to be stored and then read into memory just to be base64 encoded to make the data URI which it was already doing before without the need to store then read in from a separate file?

then returning 'false' if there is no SVG file to encode means no menus will register at all as opposed to maybe passing a generic default icon if the SVG is missing or maybe just pass empty string for no icon at all.

**Comment by fed2310** [comment]
Having the same issue after updating the plugin and also the media library shows a blank view. No images can be seen and also unable to upload any image.

**Comment by decodekult** [comment]
The missing file also raises a warning on `file_get_contents`: `Warning: file_get_contents(/wp-content/plugins/wp-graphql//img/wpgraphql-elephant.svg): failed to open stream: No such file or directory in /wp-content/plugins/wp-graphql/src/Admin/GraphiQL/GraphiQL.php on line 99`

**Comment by richke11y** [comment]
Same for me.  

WP version: 6.5.5
WPGraphQL Plugin version: 1.27.1
WPGraphQL for ACF: 2.2.0

1. Warning now shown at the top of the WP Dashboard: 

`Warning: file_get_contents(/wp-content/plugins/wp-graphql//img/wpgraphql-elephant.svg): Failed to open stream: No such file or directory in /wp-content/plugins/wp-graphql/src/Admin/GraphiQL/GraphiQL.php on line 99`

2. WPGraphQL Plugin Admin menu button has disappeared.
3. Images / files in the Media library have disappeared.

**Comment by justlevine** [comment]
Starting work on this in #3166. The other issue is that `img/` isnt part of our distribution zip.

Not sure if we want to move the non-dist assets into `.wordpress.org` or create a _new_ assets folder (possibly built to optimize the svg?s), but the latter will take more time to implement and this is a critical regression.

**Comment by justlevine** [comment]
As a temporary workaround, you can still access the Admin Screens directly:
- **GraphiQL IDE** `/wp-admin/admin.php?page=graphiql-ide`
- **GraphQL Settings** `/wp-admin/admin.php?page=graphql-settings`

**Comment by decodekult** [comment]
Actually, you can not access `/wp-admin/admin.php?page=graphiql-ide` because the admin page is never registered once the SVG file is declared missing.

**Comment by jasonbahl** [comment]
thanks for reporting this ya'll. Silly mistake on our end but a PR is coming and release will be out shortly

**Comment by jasonbahl** [comment]
Hey ya'll 1.27.2 has been released and published to WordPress.org. I've confirmed updating resolves the issue. 

Thanks all for reporting this so quickly and thanks for the patience as we got it resolved. Apologies for the inconvenience this caused 🙏🏻

**Comment by richke11y** [comment]
Thanks resolving quickly, Jason.  Can confirm the new release fixes the issue.
