### ISSUE TITLE
''WPGraphQL for ACF'' blocks the proper function of ACF

### ISSUE THREAD

**Issue by ChristinaSpyrou98** [wp-graphql/wp-graphql#3175]
### Description

Dear all,
Latelty I'm facing an issue with the ''WPGraphQL for ACF''. Once I'm activating this plug-in, I can't open the settings drop-down of any field inside a field group.

Can I ask for your contribution to the solution of the bug?
Kindly,
Christina

<img width="1432" alt="Screenshot 2024-07-22 114938" src="https://github.com/user-attachments/assets/bef40200-3c77-46b4-9188-348754489891">

### Steps to reproduce

1. Activate ''WPGraphQL for ACF''

### WPGraphQL Version

1.27.2

### WordPress Version

6.6

### PHP Version

8.3.9 (Supports 64bit values)

### Please confirm that you have searched existing issues in the repo.

- [X] #3176

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [X] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by josephfusco** [comment]
Hey @ChristinaSpyrou98, I'd recommend exporting your ACF field groups and uploading them to a [new issue in the WPGraphQL for ACF repo](https://github.com/wp-graphql/wpgraphql-acf/issues/new/choose).

I'm going to close this issue and kindly ask that you create a new issue in that repo with the additional details. Thank you!
