### ISSUE TITLE
Install plugin from WordPress market

### ISSUE THREAD

**Issue by oleksmir** [wp-graphql/wp-graphql#320]
Is there a way to install plugin through wordpress market? It would be more comfortable for end-user.

**Comment by jasonbahl** [comment]
@oleksmir we plan to add the plugin to the .org repo but only once we hit a 1.0 release and no longer consider the plugin beta where breaking changes may be made at any release. 

The plugin works great right now, but we still anticipate breaking changes as we work toward a 1.0 release, and we don’t want to put it on the repo until 1.0

**Comment by jasonbahl** [comment]
@oleksmir I’m going to close this issue as it’s on our roadmap already. Just keep an eye on the plugin and release notes.
