### ISSUE TITLE
Resolve PHPCS issues in extensions page

### ISSUE THREAD

**Issue by josephfusco** [wp-graphql/wp-graphql#3202]

**Comment by justlevine** [comment]
@josephfusco based on the [latest workflow](https://github.com/wp-graphql/wp-graphql/actions/runs/10407983042/job/28824393484?pr=3188), they should all be autofixable by `composer fix-cs`

**Comment by josephfusco** [comment]
Fixed by https://github.com/wp-graphql/wp-graphql/pull/3188/commits/d4021dd383998cbe560cdd30d4177c55c6d3d05d
