### ISSUE TITLE
Query custom content types

### ISSUE THREAD

**Issue by steveRubyRails** [wp-graphql/wp-graphql#322]
I am creating custom content types using Pods. I was wondering about support for querying custom content types. That would be great.

Thanks for the plugin and your hard work

**Comment by jasonbahl** [comment]
hey @steveRubyRails! 

You can add custom post types and custom taxonomies to the WPGraphQL Schema by adding a few fields to their registration. 

Each Custom Post Type and Custom Taxonomy you want to add to the Schema should have the following fields set: 

- show_in_graphql (bool)
- graphql_single_name (string)
- graphql_plural_name (string)

You can see more info in the wiki here: https://github.com/wp-graphql/wp-graphql/wiki/Extending-and-Customizing#post-type

**Comment by steveRubyRails** [comment]
Hi Jason:

I am admittedly very much of a noob with wordpress. Anyway I have for example a “Books” custom type with the fields of “name” and “price”

When you say “add custom field to core wp_schema" is this referring to the functions.php file in the  theme? I know that the wp_post is a table in the wordpress database. Not sure what file to change and where in the file.

This is the method I need to add, I believe.  Added to functions.php and failed

add_action( 'init', function() {
	register_post_type( 'book', [
		'label' => __( 'Books', 'wp-graphql-publishers' ),
		'supports' => [ 'title’,’name’,’price’, 'editor', 'custom-fields' ],
		'public' => true,
		'show_in_graphql' => true,
		'graphql_single_name' => 'book',
		'graphql_plural_name' => 'books',
	] );
} );

If possible is it possible to have a noob step by step on how to do this?

Thanks
Steve

**Comment by jasonbahl** [comment]
@steveRubyRails I believe we got this resolved in slack, eh? Would you mind posting back the code you came up with so other folks looking here can take advantage of what you ended up with?

Thanks!

**Comment by jasonbahl** [comment]
for anyone looking, here's working code:

```
add_action( 'init', function() {
    register_post_type( 'books', [
        'label' => __( 'books', 'wp-graphql-publishers' ),
        'supports' => [ 'title','publisher','editor' ,'custom-fields' ],
        'public' => true,
        'show_in_graphql' => true,
        'graphql_single_name' => 'book',
        'graphql_plural_name' => 'books',
    ] );
} );

add_action( 'graphql_init', function() {
    add_filter( 'graphql_book_fields', function( $fields ) {
        
     
                $fields['high_score'] = [
                        'type' => \WPGraphQL\Types::string(),
                        'resolve' => function( \WP_Post $post ) {
                                return get_post_meta( $post->ID, 'high_score', true );
                        },
                ];
                $fields['used'] = [
                        'type' => \WPGraphQL\Types::boolean(),
                        'resolve' => function( \WP_Post $post ) {
                                return get_post_meta( $post->ID, 'used', true );
                        },
                ];


       return $fields;
    } );
} );
```

**Comment by jasonbahl** [comment]
@themostcolm ya your functions.php or any file required by that should work.
