### ISSUE TITLE
Incorrect slug being returned in authenticated preview request

### ISSUE THREAD

**Issue by samfrank** [wp-graphql/wp-graphql#3220]
### Description

I am return the slug in a standard and basic query to the page under authenticated preview and I am getting an unexpected value.

Lets say that the post is called 'New Page' and has a ID of `82`. The slug returns as `new-page` when in a standard request, however when under authenticated preview mode the slug is returned as `82-autosave-v1`.

### Steps to reproduce

1. Set up authenticated requests to WP GraphQL
2. Pass the asPreview argument as `true` to a query 

```
query PreviewQuery {
  page(
    id: "new-page"
    idType: URI
    asPreview: true
  ) {
    slug
  }
}
```

### Additional context

I have set up an additional resolver below. 

```
        add_action('graphql_register_types', function () {
            register_graphql_field('Post', 'altSlug', [
            'type'        => 'String',
            'description' => 'Link to edit the content',
            'resolve' => function (\WPGraphQL\Model\Post $post, $args, $context, $info) {       
                $template = $post->slug;
                return $template ? $template  : null;
            }
            ]);
        });
```

This still returns the same slug of `82-autosave-v1` under preview

### WPGraphQL Version

1.28.1

### WordPress Version

6.6.2

### PHP Version

8.2.23

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Hey @samfrank , thanks for taking the time to report this.

It _sounds_ like you're running into expected behavior: if you're querying a preview, you're going to get the preview object's data back (hence the revision slug). To get the related post for the preview, you need to query for the `parent` or `connectedPost` (or something similarly named, not by my desk check the docs tab in the IDE).

(Same with your custom resolver, your returning the slug from the modeled revision)

Related #2876

**Comment by samfrank** [comment]
Thank you for replying and apologies for logging a intended bug report

**Comment by jasonbahl** [comment]
Closing this as it's expected (although maybe not super well documented?) behavior.
