### ISSUE TITLE
terms return null if asPreview is set to true

### ISSUE THREAD

**Issue by MKlblangenois** [wp-graphql/wp-graphql#3238]
### Description

When I try to make a preview of my single post type (post or custom), the terms node is returned as null, even if I trigger a "draft" revision from WordPress

### Steps to reproduce

1. Create a post with at least one terms (custom or category)
2. Go to GraphQL and try to request the post with the `asPreview` to `true`
```graphql
query ($postId: ID!, $asPreview: Boolean){
  post(id: $postId, idType: DATABASE_ID, asPreview: $asPreview) {
    terms {
      nodes {
        name
      }
    }
  }
}
```

### Additional context

![image](https://github.com/user-attachments/assets/91f2e1d8-5e5c-4dbb-9cae-b92220a95d2a)

### WPGraphQL Version

1.29.2

### WordPress Version

6.7

### PHP Version

8.1.23

### Additional environment details

- Add WPGraphQL SEO 4.22.5
- JSON Basic Authentication 0.1
- WPGraphQL Content Blocks 4.0.1
- WPGraphQL for ACF 2.4.1
- WPGraphQL Offset Pagination 0.2.0

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
@MKlblangenois I am able to confirm this with the following query: 

```graphql
query ($postId: ID!){
  post(id: $postId, idType: DATABASE_ID, asPreview: false) {
    ...Post
  }
  preview: post(id: $postId, idType: DATABASE_ID, asPreview: true) {
    ...Post
  }
}

fragment Post on Post {
  id
  databaseId
  isPreview
  title
  terms {
    nodes {
      name
    }
  }
}
```

![CleanShot 2024-12-13 at 09 07 08](https://github.com/user-attachments/assets/dc7c7e66-5d91-4641-8fa8-e264d0276e82)

I believe what needs to happen here is that connections to terms from a preview post need to resolve from the parent (the published post) instead of the preview post. 

We do something similar to handle preview meta: https://github.com/wp-graphql/wp-graphql/blob/develop/src/Utils/Preview.php#L7-L57

I believe we might be able to handle this centrally in a similar way, where if a connection is from a Post Object to Term Objects we should be able to detect if the Post Object the connection is coming from is a Preview and if so, return the published posts terms.

**Comment by jasonbahl** [comment]
@MKlblangenois I believe if we update these lines: https://github.com/wp-graphql/wp-graphql/blob/develop/src/Registry/Utils/PostObject.php#L203-L205

to behave more like these lines: https://github.com/wp-graphql/wp-graphql/blob/develop/src/Registry/Utils/PostObject.php#L223C6-L232

Things should work. 

I updated that resolver to be:

```php
'resolve'        => static function ( Post $post, $args, AppContext $context, ResolveInfo $info ) {
	$taxonomies = \WPGraphQL::get_allowed_taxonomies();
	$object_id = true === $post->isPreview && ! empty( $post->parentDatabaseId ) ? $post->parentDatabaseId : $post->ID;

	if ( empty( $object_id ) || ! absint( $object_id ) ) {
		return null;
	}

	$resolver = new TermObjectConnectionResolver( $post, $args, $context, $info, $taxonomies );
	$resolver->set_query_arg( 'object_ids', absint( $object_id ) );
	$resolver->set_query_arg( 'taxonomies', $taxonomies );
	return $resolver->get_connection();
},
```

With this in place, I get the terms from the parent (published) post as expected: 

![CleanShot 2024-12-13 at 09 28 57](https://github.com/user-attachments/assets/5e950f6a-9ffa-4ed5-a537-3c51c65f26ee)

**Comment by jasonbahl** [comment]
We'll need to make sure making this change doesn't have any other negative side-effects as well

**Comment by jasonbahl** [comment]
@MKlblangenois I made a quick PR using Github https://github.com/wp-graphql/wp-graphql/pull/3261

I'll need to follow up with more updates shortly. But wanted to get something started.
