### ISSUE TITLE
WordPress 6.7 changes in translation throw a warning when WP_DEBUG is on

### ISSUE THREAD

**Issue by alexkuc** [wp-graphql/wp-graphql#3239]
### Description

After upgrading WordPress to version 6.7 and enabling `WP_DEBUG`, the following error/warning can be observed in the admin pages (at the very top, right under toolbar). This error/warning also shows up in the frontend.

```
Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the wp-graphql domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see Debugging in WordPress for more information. (This message was added in version 6.7.0.) in wp-includes/functions.php on line 6114
```

### Steps to reproduce

- install WordPress version 6.7 or higher
- install WPGraphQL plugin, latest version (1.29.2 at the time of writing)
- set `WP_DEBUG` to `true` in `wp-config.php`
- observe the error/warning as described earlier

### Additional context

No other plugins are running. Theme is `Twenty Twenty-Four`.

### WPGraphQL Version

1.29.2

### WordPress Version

6.7.1

### PHP Version

8.3.12

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by ioannis-b-dev** [comment]
Has anyone found a solution? Currently it is not possible to login to wordpress as an admin so I need to disable wpgraphql plugin, login then reenable it but this is a very bad solution

**Comment by justlevine** [comment]
> Has anyone found a solution? Currently it is not possible to login to wordpress as an admin so I need to disable wpgraphql plugin, login then reenable it but this is a very bad solution

@ioannis-b-dev per the OP, it's a PHP Notice, not a fatal error. 

1. PHP notices shouldn't prevent you from logging in - or doing anything else.
2. You can disable the visual output of WP debugging messages by setting `define( 'WP_DEBUG_DISPLAY', false );`. (PS: this should be disabled on production, regardless, as a matter of security).

If either of the above aren't true for you, please disable all other plugins to ensure there's no conflicts and share a minimally viable replication. 🙏

**Comment by GaryVoss** [comment]
Thanks @justlevine, setting `define( 'WP_DEBUG_DISPLAY', false );` worked for me.

**Comment by justlevine** [comment]
Per a `debug_backtrace()` the error is being thrown by Appsero:

```bash

    [5] => Array
        (
            [file] => /var/www/html/htdocs/wp-admin/includes/plugin.php
            [line] => 114
            [function] => _get_plugin_data_markup_translate
        )

    [6] => Array
        (
            [file] => /var/www/html/repos/wp-graphql/vendor/appsero/client/src/Client.php
            [line] => 201
            [function] => get_plugin_data
        )

    [7] => Array
        (
            [file] => /var/www/html/repos/wp-graphql/vendor/appsero/client/src/Client.php
            [line] => 110
            [function] => set_basename_and_slug
            [class] => Appsero\Client
            [type] => ->
        )

    [8] => Array
        (
            [file] => /var/www/html/repos/wp-graphql/wp-graphql.php
            [line] => 170
            [function] => __construct
            [class] => Appsero\Client
            [type] => ->
        )

    [9] => Array
        (
            [file] => /var/www/html/repos/wp-graphql/wp-graphql.php
            [line] => 183
            [function] => graphql_init_appsero_telemetry
        )
```

**Comment by justlevine** [comment]
#3245 should hopefully resolve this.
