### ISSUE TITLE
 Unexpected token when creating Post

### ISSUE THREAD

**Issue by towfiqi** [wp-graphql/wp-graphql#324]
Whenever I try to create a post with mutation, I am getting this in Chromeiql:

`SyntaxError: Unexpected token < in JSON at position 0`

And this in Graphiql app:

`{
  "data": null,
  "errors": [
    {
      "message": "I couldn't communicate with the GraphQL server at the provided URL. Is it correct?"
    }
  ]
}`

The weird thing is the post is created and I can see them in wordpress backend but on my frontend app I am getting the unexpected token error.

Flushing the permalinks settings did not work. And no errors in Php error log file.

This is how my mutation looks:

```
mutation {
  createPost(input: {
    clientMutationId: "PyXcYaP6"
		authorId: "dXNlcjox",
    content:"List Description",
    status: PUBLISH,
		title: "NEW Lists GraphiQL"
    }){

    post {
      title

      
    }
  }
}
```

Thanks

**Comment by jasonbahl** [comment]
@towfiqi what GraphiQL app are you using? That error looks like something from a client, not the API

**Comment by towfiqi** [comment]
This one: https://github.com/skevy/graphiql-app

**Comment by towfiqi** [comment]
I am running Running PHP version: 5.6.31 btw.

**Comment by towfiqi** [comment]
Just found out what the issue was, I had a function that was hooked to `save_post` which added some conditions which the above mutation did not fulfill.

You can close this issue as its not related to the plugin. Thanks

**Comment by jasonbahl** [comment]
@towfiqi thanks for the follow-up.
