### ISSUE TITLE
Not getting schedule (future) posts

### ISSUE THREAD

**Issue by elnazmahzoon** [wp-graphql/wp-graphql#3248]
### Description

Although I have so many scheduled posts, I can not get them with this query
query GetFuturePosts {
  posts(first: 500, where: {status: FUTURE}) {
    nodes {
      status
    }
  }
}
and keep getting [] as a result.
I already updated to the latest version and checked the graphql setting and permissions.

### Steps to reproduce

query GetFuturePosts {
  posts(first: 500, where: {status: FUTURE}) {
    nodes {
      status
    }
  }
}

### WPGraphQL Version

Version 1.29.2

### WordPress Version

6.3.1

### PHP Version

8.1.29

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Hey @elnazmahzoon 

Thanks for taking the time to report this.

Your reproduction steps don't mention anything about authentication, and for obvious reasons `FUTURE` (i.e. unpublished) posts are not available publicly.

Can you confirm whether you experience this issue when making an _authenticated_ request in the WPGraphQL IDE ( https://www.wpgraphql.com/docs/wp-graphiql#toggle-between-public-and-authenticated-requests)?

**Comment by jasonbahl** [comment]
@elnazmahzoon I'm going to close this as I believe this is related to authentication as @justlevine pointed out. 

If you are querying for data that you do have proper access to see and it's not being returned correctly, let us know and we can re-open this or create a new issue with further steps to reproduce. 

Thanks! 🙏🏻
