### ISSUE TITLE
"Sorry, you are not allowed to create posts"

### ISSUE THREAD

**Issue by Pizza1** [wp-graphql/wp-graphql#3253]
### Description

When trying to create a post using wpgraphql as an administrator, the following is the response

the mutation

mutation CREATE_POST {
  createPost(input: {content: "hello", status: PUBLISH}) {
    clientMutationId
  }
}

the response 

![image](https://github.com/user-attachments/assets/cbd8386b-795a-4682-b689-bcb60dfea078)

### Steps to reproduce

Go to wpgraphql ide, create a 'create post' mutation, try to create a post

### WPGraphQL Version

1.29.3

### WordPress Version

6.7.1

### PHP Version

7.4.33 

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Hey @Pizza1 - when you say 'As an administrator' , do you mean youre running the IDE while logged into the dashboard as an admin, or that you made an authenticated query [_in the ide_](https://www.wpgraphql.com/docs/wp-graphiql#toggle-between-public-and-authenticated-requests)?

If the mutation fails even while running an authenticated request, please turn on WPGraphQL Debugging and let us know.

**Comment by Pizza1** [comment]
Thank you @justlevine, that fixed it!
