### ISSUE TITLE
Custom post type - search

### ISSUE THREAD

**Issue by Messa1** [wp-graphql/wp-graphql#3255]
### Description

I try to search in custom post type generated by ACF.

```
query GetSearch($serachString: String = "") {
  posts(where: {search: $serachString}) {
    edges {
      node {
        id
        link
        slug
        title
        uri
      }
    }
  }
}
```

```
{
  "serachString": "test"
}
```
![Bildschirmfoto 2024-12-10 um 17 27 00](https://github.com/user-attachments/assets/4891caa2-7b3e-4f07-8deb-40601687d697)

But if I search for
 
```
{
  "serachString": "Fahrradmechatronik"
}
```
![Bildschirmfoto 2024-12-10 um 17 27 14](https://github.com/user-attachments/assets/5da74c97-216d-45b4-a5c7-9ee46d9a121e)
![Bildschirmfoto 2024-12-10 um 17 28 20](https://github.com/user-attachments/assets/e95c595e-1de3-493a-91f3-673427ebb75d)

Exclude From Search is disabled
![Bildschirmfoto 2024-12-10 um 17 29 19](https://github.com/user-attachments/assets/63604e1f-e8c0-4662-bf5c-4804eccbaa46)

### Steps to reproduce

See my description.

### WPGraphQL Version

1.29.3

### WordPress Version

6.7.1 

### PHP Version

8.2.x

### Additional environment details

Local

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [ ] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by justlevine** [comment]
Hey @Messa1 - you skipped the last part of the issue template ;)

GH issues in this repo are used for bug reports/feature requests for WPGraphQL _core_.

To report an issue with ACF please use https://github.com/wp-graphql/wpgraphql-acf.

(Marking as `invalid?`, not to imply that you're not experiencing a real issue but simply that we're unable to fix bugs in code that isn't in this repo, and I personally don't have the org perms to transfer this to a different repo).

**Comment by Messa1** [comment]
@justlevine done -> https://github.com/wp-graphql/wpgraphql-acf/issues/247
