### ISSUE TITLE
Add "findBreakingChanges" check to Travis CI

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#335]
GraphQL JS, and now GraphQL PHP, have a utility to `findBreakingChanges`.

The way it works is that you provide an old schema and a new schema, and it compares any changes to make sure the changes are non-breaking. 

Once we get to 1.0, this would be huge to know how we should version fields. 

See usage in PHP here: https://github.com/webonyx/graphql-php/blob/9c563d5c0006f03a08746b5b3ae3d7167dfe6f57/tests/Utils/FindBreakingChangesTest.php

----

I believe the best way to handle this might be to generate the schema on each release and upload it as a Github Release Asset (much like we're doing for the plugin zip file). 

Then, on future PRs, we can use the schema from the latest release as the "old" schema, and the Schema generated by the state of WPGraphQL in the PR as the "new" schema and run it through `findBreakingChanges` utility and then pass/fail the check based on the outcome.

**Comment by markkelnar** [comment]
Note: https://github.com/actions/upload-release-asset says it is archived and not maintained anymore. Looking into https://github.com/softprops/action-gh-release as replacement.

**Comment by jasonbahl** [comment]
@markkelnar ah. Good to know. I think I'm using it (the archived one) in our deploy workflow, so we probably need to update that too.

**Comment by jasonbahl** [comment]
Closed by #1940
