### ISSUE TITLE
Support multiple Schemas

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#336]
GraphQL is pretty flexible. To execute, you provide the executor a Schema, the query, variables, etc. 

Then GraphQL validates the request against the provided Schema, and executes against said Schema. 

Right now, WPGraphQL provides a single `/graphql` endpoint with a default Schema composed of core data types. . .but I can see a lot of value in folks wanting to provide their own micro schemas for various purposes, either as a subset of the larger WPGraphQL schema, or as their own unique features. 

GraphQL for Laravel provides the ability to define multiple Schemas, then at run time you can set a flag to determine what Schema to use for execution. 

I think it would be sweet if WPGraphQL provided folks with a way to define their own Schema's and use however they wish.

**Comment by jmlallier** [comment]
@jasonbahl Do you have any ideas for how this could be implemented? My team is developing a plugin with several custom tables that we'd like to expose to a GraphQL endpoint. Currently we're just implementing types and providing them to the standard graphql endpoint, but we definitely would be up for implementing a multi-endpoint Schema with permissions protected endpoints. What do you think?

**Comment by jasonbahl** [comment]
@jmlallier I've actually experimented a bit with this locally. I think there's a lot of value in the approach. 

I can see different plugins potentially wanting to define their own endpoints/schemas, but (potentially) take advantage of existing Types in the Schema, or potentially just define completely new types but want the existing infrastructure for validation, etc. 

I'll pull up the branch I had worked on locally and see if I can get a PR together or at least share some ideas at minimum.

**Comment by jmlallier** [comment]
@jasonbahl Awesome! I agree haha.

Absolutely. We're wanting to ship our plugin using WPGraphQL as a composer dep and this feature would be very cool. I'd love to see what you've already done.

**Comment by jasonbahl** [comment]
Support for multiple Schemas was added a while ago. It's not well documented, but it's there. You can check out source code here to see it in action: https://github.com/wp-graphql/wp-graphql/blob/develop/src/SchemaRegistry.php

By default, the plugin makes use of the "core" Schema, but it's possible to register other Schemas and filter the execution to use a different Schema.

This might be useful for one-off features that want to validate things against their own Schema instead of make use of the primary WPGraphQL Schema.
