### ISSUE TITLE
Uri field for homepage 

### ISSUE THREAD

**Issue by gerhardsletten** [wp-graphql/wp-graphql#341]
Should the Page uri field return '/' if a page is set as homepage in wordpress?

**Comment by jasonbahl** [comment]
@gerhardsletten that's a good thought. I need to think about it a bit more to see how we should handle that. 🤔

**Comment by jasonbahl** [comment]
This is addressed by #1112 

See it in action:

![Screen Shot 2020-01-13 at 10 20 15 PM](https://user-images.githubusercontent.com/1260765/72316288-e70f9e00-3652-11ea-8aab-629d092d7d3e.png)
