### ISSUE TITLE
tax query, meta query

### ISSUE THREAD

**Issue by BesoKakulia** [wp-graphql/wp-graphql#342]
Hello everyone, I have a problem with sub plugins **("wp-graphql-tax-query", "wp-graphql-meta-query")**, as i have figured out , the problem is that an action  `add_action( 'graphql_generate_schema', '\WPGraphql\graphql_init_tax_query' );` does not run. 
![z9iymdbls7_fg0ll-exivg](https://user-images.githubusercontent.com/26166174/34335053-3912f6f8-e965-11e7-88a7-02d3d7090bf7.png). This is the error I get. Thank you.

**Comment by BesoKakulia** [comment]
@jasonbahl  Hello, can you help me please? :)

**Comment by jasonbahl** [comment]
@BesoKakulia im checking this out. Will try to have an update for you shortly.

**Comment by BesoKakulia** [comment]
@jasonbahl  thank you

**Comment by chrisfullman** [comment]
I'm also not seeing metaQuery and taxQuery available in the available types/fields after .20. Is there an update on this?

**Comment by dre1080** [comment]
@jasonbahl any updates on this?

**Comment by jasonbahl** [comment]
@BesoKakulia @dre1080 @chrisfullman 

I pushed some updates to this repo as well as both extensions WPGraphQL Meta Query and WPGraphQL Tax Query. 

Things should be working fine for both extensions if you use the latest version of all 3. 

Going to close this out, but if ya'll run into other issues, let me know.
