### ISSUE TITLE
Setup initial Docs site using Gatsby.js

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#343]
Ideally, I'd like to see documentation managed largely in the repo using Markdown files so that folks can easily contribute to maintaining documentation. 

In my brief experience, Gatsby appears to be a perfect platform to build the site on. It's super fast and has a great plugin system that makes it really easy to extend and customized. . .plus it's built on GraphQL + React, so the dev experience is 👌 

I think it would be great to get the initial bones of a docs site up and have it deploying automatically to Github pages whenever we have a release. 

I think initially it makes sense to manage the docs in the same repo as the plugin, but open to moving it to another repo down the road if it makes sense to do so.

**Comment by cr101** [comment]
[Docusaurus by Facebook](https://github.com/facebook/Docusaurus) also looks like a great option

**Comment by jasonbahl** [comment]
@cr101 oooh. . .Docusaurus does look nice! And nearly everything FB puts out is 👌

I have a good start on a Gatsby site though. . .I'll try to get what I have published within the week!

**Comment by jasonbahl** [comment]
closing this. It needs more work for sure, but the site is up on Gatsby here: https://wpgraphql.com and the repo for it is here: https://github.com/wp-graphql/wpgraphql.com
