### ISSUE TITLE
How to query a custom field type image from a custom post type

### ISSUE THREAD

**Issue by freecates** [wp-graphql/wp-graphql#344]
Hi @jasonbahl,
First of all congratulations for your work. Awesome.
I've been reading through your comments and docs and I've have registered a custom post type called persones:

```
add_action( 'init', function() {
	register_post_type( 'persones', [
		'label' => __( 'Persones', 'wp-graphql-persones' ),
		'supports' => [ 'title', 'custom-fields' ],
		'public' => true,
		'show_in_graphql' => true,
		'graphql_single_name' => 'persona',
		'graphql_plural_name' => 'persones',
	] );
} );
```

Each persona has the following custom fiedls: foto, email and social. I've added them like so:

```
add_action( 'graphql_init', function() {
    add_filter( 'graphql_persona_fields', function( $fields ) {
        
     
                $fields['email'] = [
                        'type' => \WPGraphQL\Types::string(),
                        'resolve' => function( \WP_Post $post ) {
                                return get_post_meta( $post->ID, 'email', true );
                        },
                ];
        
     
                $fields['social'] = [
                		'type' => \WPGraphQL\Types::string(),
                        'resolve' => function( \WP_Post $post ) {
                                return get_post_meta( $post->ID, 'social', true );
                		},
                ];
        
     
                $fields['foto'] = [
                		'type' => \WPGraphQL\Types::string(),
                        'resolve' => function( \WP_Post $post ) {
                                return get_post_meta( $post->ID, 'foto', true );
                		},
                ];


       return $fields;
    } );
} );
```

Everything seems fine, but when querying for the foto field I only get de id. Can you help me?

**Comment by renatonascalves** [comment]
Which value is being saved in the database? Are you sure the ID is not being saved in the `foto` metadata?

**Comment by freecates** [comment]
Hi @renatonascalves ,
Actually what I get is the `ID`, but what I want to get is the `url` of the `foto`. This is the query:
 ```
 persones(last:1) {
    edges {
      node {
        id
        foto
      }
    }
  }
}
```
Ahd this is the result:
```
{
  "data": {
    "persones": {
      "edges": [
        {
          "node": {
            "id": "cGVyc29uZXM6MzM5Ng==",
            "foto": "3397"
          }
        }
      ]
    }
  }
}
```
Querying `foto` returns the string of the `ID` field, but I want the `url`. Any ideas?

**Comment by renatonascalves** [comment]
Looking at the code, I can only presume the `foto` value is not the URL. Outside of the grapqh plugin, you can get the url from the `get_post_meta( $post->ID, 'foto', true )`?

**Comment by freecates** [comment]
Hi @renatonascalves , you're right. The problem is as follows: `personas` is a custom post type built with CPT UI pluguin that has a custom field `foto` of type image built with Advanced Custom Fields Pro. When querying `foto` [`get_post_meta( $post->ID, 'foto', true )`] from post type `persona` it returns the id of the post `foto` 3397, that has post meta `_wp_attached_file` that actually has stored the url path of the image `foto`. So, I'm lost.

**Comment by renatonascalves** [comment]
Based on what you telling me above, I guess you should be fetching as such:
```
$fields['foto'] = [
    'type' => \WPGraphQL\Types::string(),
    'resolve' => function( \WP_Post $post ) {
       return get_post_meta( $post->ID, '_wp_attached_file', true );
    },
];
```

If `_wp_attached_file` is the post meta that has the url, fetch as so. Does it work for you?

**Comment by renatonascalves** [comment]
By the way, I would close this issue as it is not a valid bug. It doesn't seem to be a problem with the plugin. :)

**Comment by freecates** [comment]
Hi again @renatonascalves and thanks for your suggestion. I've tried your approach before but it returns an empty string. Again thanks.

**Comment by renatonascalves** [comment]
Let's narrow the bug search.

1st - See if the post has any URL. If there is not, add one, for testing purposes.
2nd - Test outside the graphQL plugin. `var_dump `or `echo `the value somewhere.
3td - If there is a value, query via graphQL as I suggested above. Using the `_wp_attached_file` meta.

What can you see? Is it still the post type ID? Is it an empty string?

**Comment by jasonbahl** [comment]
@freecates so, if the Image ID is stored in post meta `foto`, you could potentially update your resolver like so:

```
$fields['foto'] = [
    'type' => \WPGraphQL\Types::string(),
    'resolve' => function( \WP_Post $post ) {
        $image_id = get_post_meta( $post->ID, 'foto', true );
        $image_src = wp_get_attachment_image_src( $image_id  );
        return ! empty( $image_src[0] ) ? $image_src[0] : null;
    },
];
```

Additionally, if you want to be able to query more info on the image, you could update your resolver like so:

```
$fields['foto'] = [
    'type' => \WPGraphQL\Types::post_object( 'attachment' ),
    'resolve' => function( \WP_Post $post ) {
        $image_id = get_post_meta( $post->ID, 'foto', true );
        return ! empty( $image_id ) ? get_post( absint( $image_id ) ) : null;
    },
];
```

This will allow you to do more advanced queries to get more info about the image, like so: 

```
persones(last:1) {
   edges {
     node {
       id
       foto {
          id
          sourceUrl
          link
       }
     }
   }
 }
}
```

**Comment by freecates** [comment]
@jasonbahl Thanks a lot. The second one is the good one. It works! Perfect. 

So, according to your code, Is there any way to query the subfields of a `repeater` custom field (https://www.advancedcustomfields.com/resources/repeater/)? I meam, field `foto` is a type `post_object('attachment)`. Which one is a repeater? Thanks a lot for your great job you've done with this plugin!
