### ISSUE TITLE
WPGraphQL doesn't play nice with WP-CLI Server

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#355]
When running WordPress using `wp server` from WP-CLI, WPGraphQL requests appear to be getting escaped before making their way to WPGraphQL, so WPGraphQL can't properly parse the request. 

We should look into playing nice with these kinds of alternative WP Servers. 

See this thread: https://wp-graphql.slack.com/archives/C3NM1M291/p1515621738000172

The latest working theory is that Magic Quotes (😬 ) could be causing issues.

**Comment by ginatrapani** [comment]
Dug into this a bit this morning, and here's what I learned:

* this same behavior happens on Pantheon and WP Engine (and the Docker setup I'm using on my current project).
* If I add a call to `stripslashes` in `Router` like so, it resolves the error

```php
				$data = [
					'query'         => isset( $_GET['query'] ) ? sanitize_text_field( stripslashes( $_GET['query'] ) ) : '',
					'operationName' => isset( $_GET['operationName'] ) ? sanitize_text_field( $_GET['operationName'] ) : '',
					'variables'     => isset( $_GET['variables'] ) ? stripslashes( $_GET['variables'] ) : '',
				];
```

But I'm not sure if this is the best solution. Should I go ahead and write tests against this and submit a PR?

**Comment by ginatrapani** [comment]
Changing the request from GET to POST fixes this! Plan is to emphasize that in the docs going forward. Thanks @jasonbahl!

**Comment by jasonbahl** [comment]
@ginatrapani I'll close this issue, but I'll open another to investigate whether we can easily fix GET requests or not. Seems like the issue lies with GET requests that have arguments on fields. 

For example, this request works as a GET request: 

```
{
  users {
    edges {
      node {
        nicename
      }
    }
  }
}
```

But this doesn't:

```
{
  users(first: 1, where: {login: "jasonbahl"}) {
    edges {
      node {
        nicename
      }
    }
  }
}
```
