### ISSUE TITLE
Query batching support

### ISSUE THREAD

**Issue by dre1080** [wp-graphql/wp-graphql#360]
Any plans to support [query batching](https://webonyx.github.io/graphql-php/executing-queries/#query-batching) by using `GraphQL\Server\StandardServer`?

**Comment by jasonbahl** [comment]
@dre1080 I haven’t looked too closely st this yet, but I’m totally interested in supporting it. Any interest in working on a PR to add support?

The whole `StandardServer` looks generally interesting. It didn’t exist when we started this plugin, and I haven’t spent much time looking at how it handles things differently than what we’re doing currently to receive HTTP Reqs and return a response. 

I assume we would need to replace much of our Router.php file if we were to implement the StandardSever? 

Even if we don’t implement the full StandardServer we could probably still implement the Batch support. 

I’m totally open to the feature in some form though. Let me know if you’re interested in helping work on it.

**Comment by dre1080** [comment]
I'm interested, but unsure where to start. Would [`do_graphql_request`](https://github.com/wp-graphql/wp-graphql/blob/develop/wp-graphql.php#L524) also need to be replaced?

Apparently, this is all you need to enable batching:

```
use GraphQL\Server\StandardServer;

$server = new StandardServer([
    'schema' => $mySchema,
    'rootValue' => $myRootValue,
    'context' => $myContext,
    'queryBatching' => true
]);
$server->handleRequest(); // parses PHP globals and emits response
```

**Comment by jasonbahl** [comment]
@dre1080 We have batch support with the latest merge on develop!

**Comment by dre1080** [comment]
@jasonbahl :smile: :+1: Thanks!
