### ISSUE TITLE
GET Requests with field arguments don't work

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#361]
It appears that GET requests that contain Field arguments don't work properly. 

For example, this request works as a GET request: 

```
{
  users {
    edges {
      node {
        nicename
      }
    }
  }
}
```

But this doesn't:

```
{
  users(first: 1, where: {login: "jasonbahl"}) {
    edges {
      node {
        nicename
      }
    }
  }
}
```

We should investigate what is causing the issue (likely something here: https://github.com/wp-graphql/wp-graphql/blob/develop/src/Router.php#L332-L370) and see if we can adjust to support GET requests a bit better

**Comment by jasonbahl** [comment]
@ginatrapani my attempt at resolving this is #362 and things seem to be working ok locally for me. . .but you made it sound like there _may_ still be some issues with your setup?

**Comment by ginatrapani** [comment]
Yes, when I apply that update to `Router` and run a GET query I get an error pictured here: https://jumpshare.com/v/krwfEwTqrpidzhLMAdTw


And I see this in my console:

```
[11-Jan-2018 18:49:43 UTC] PHP Fatal error:  Uncaught Error: Cannot use object of type stdClass as array in 
/wordpress/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/Values.php:266
Stack trace:
#0 
/wordpress/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/Values.php(74): GraphQL\Executor\Values::isValidPHPValue(Object(stdClass), Object(WPGraphQL\Type\User\Connection\UserConnectionArgs))
#1 
/wordpress/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/Executor.php(233): GraphQL\Executor\Values::getVariableValues(Object(WPGraphQL\WPSchema), Object(GraphQL\Language\AST\NodeList), Array)
#2 
/wordpress/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/Executor.php(145): GraphQL\Executor\Executor::buildExecutionContext(Object(WPGraphQL\WPSch in 
/wordpress/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/Values.php on line 266
```

But maybe there's something specific to my setup causing this.
