### ISSUE TITLE
Parsing issue with graphql-tools

### ISSUE THREAD

**Issue by adampash** [wp-graphql/wp-graphql#364]
I'm running into an error trying to parse the wp-graphql generated schema with `graphql-tools` due to a quoting issue. Specifically, the generated GraphQL schema is generating the following:

```
input QueryArgs {
  # ...
  """Find objects connected to the author by the author's "nicename""""
  authorName: String
  # ...
}
```

The quotes around "nicename" are causing the parsing issue. It parses fine if the description looks like:

```
  """
  Find objects connected to the author by the author's "nicename"
  """
```

The issue appears to be the double quotes on the same line. I don't necessarily know if this is a bug in `graphql-tools` or not, but it seems like this would cause a parsing problem, so I thought I'd raise it here first. The line in question is:

https://github.com/wp-graphql/wp-graphql/blob/34336a677b392fbadc8c6cfb40a600e17aefb0f6/src/Type/PostObject/Connection/PostObjectConnectionArgs.php#L89

Let me know what you think, or if I can provide any other context.

**Comment by jasonbahl** [comment]
@adampash to your knowledge is this the only field that's causing trouble with GraphQL tools?

I don't think the quotes are absolutely necessary in that description, so I'm ok with removing them, but want to make sure we don't have other descriptions that aren't playing nice with other tooling in the ecosystem. 

Curious if `\"nicename\"` would solve it as well?

**Comment by adampash** [comment]
> to your knowledge is this the only field that's causing trouble with GraphQL tools?

@jasonbahl Yep, that appears to solve the problem with my schema.

> Curious if \"nicename\" would solve it as well?

Escaping the `"` appears to still throw an error.

**Comment by jasonbahl** [comment]
@adampash any interest in opening a PR to remove those quotes? Thanks!

**Comment by adampash** [comment]
Sure, gladly!

**Comment by jasonbahl** [comment]
@adampash might also be good to add a unit test to check all descriptions in the Schema to make sure they don't have quotes? Do you know if that's a common linter pattern for GQL schemas? "no quotes in descriptions?"

**Comment by adampash** [comment]
@jasonbahl Sorry, I don't have the tools to add the suggested unit test, or I would. (I'm a PHP dabbler at best.)

**Comment by jasonbahl** [comment]
@adampash no worries. Thanks for reporting the issue and the PR to fix it!
