### ISSUE TITLE
Wiki doc on extending the Post schema is incorrect

### ISSUE THREAD

**Issue by ginatrapani** [wp-graphql/wp-graphql#366]
Referencing this page today:

https://github.com/wp-graphql/wp-graphql/wiki/Extending-and-Customizing

I noticed the example in the "Add Custom Field to Core WP_Post Schema (i.e. Post Meta)" section says you should call `add_action( 'graphql_root_queries' ...` but it actually should be `add_action( 'graphql_post_fields' ...`.

**Comment by jasonbahl** [comment]
Updated the wiki. Thanks!
