### ISSUE TITLE
Return a post's visibility in the response

### ISSUE THREAD

**Issue by ginatrapani** [wp-graphql/wp-graphql#375]
Related to #347 

Right now there's no way to see a post's "visibility" (as it's labeled in the WP admin): whether a post is private, password-protected, or public. 

We chatted about this a bit in the Slack: https://wp-graphql.slack.com/archives/C3NM1M291/p1516917534000156

Jason says:

We will likely return a `null` value for the node object if you don't have permission to view it, but we should provide an `edge` field that indicates the visibility. 

Something like: 

```{
  posts {
     edges {
        isProtected
        node {
           id
           title
        }
     }
  }
}
```

or something to that tune  would give a response like:

```{
  "data":{
     "posts": {
         edges: [
               {
                 isProtected: true,
                 node: null,
               },
               {
                 isProtected:false,
                node: {
                   id: "asdfasdfa",
                   title: "Hello World"
                }
            }
        ]
     }
  }
}```

**Comment by CodeProKid** [comment]
This makes a ton of sense. Would be very valuable to know this on the render side of things. This should also be handled with the Model layer initiative. #280

**Comment by CodeProKid** [comment]
One thing that still needs to be fleshed out here, is the verbiage to use for Private, Protected, And Public data. @jasonbahl and I have talked about this a lot, and we think those are essentially the 3 states a piece of data can have (with varying degrees of protected-ness in the protected status).

We just need to firm up what word to use for these statuses. Also, where to output this info in the schema. To me, it makes sense to be on the Node, but I could see how an argument could be made for this to be edge data.
