### ISSUE TITLE
Discuss Multisite Schema

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#403]
Several folks have voiced wanting GraphQL support for Multisite, so I want to open up discussion on what Schema should look like for multisite. 

My initial thoughts are that the network would have it's own endpoint with network specific data, and possibly allow you to iterate over sites and their respective graphs. Something to this tune:

```graphql
/network/graphql

{
  sites {
    edges {
       node {
          id
          url
          plugins {
             ...pluginFields
          }
          themes {
              ...themeFields
          }
          users {
              ...userFields
          }
       }
    }
  }
  site( id:"site.com" ) {
      ...siteFields
  }
}
```

I was also thinking it might be good to have some sort of network entry points from a site, for example:

```graphql
/site/graphql

{
  networkSettings {
     networkName
     networkEmail
     uploadSpace
     ...etc
  }
  posts { 
     edges { 
        node {
           id
           title
        } 
     }
  }
}
```

These are just thoughts off the top of my head. I'd love to get more thoughts on potential use cases folks might have for using GraphQL with multisite and what the shape of the Schema should look like.

**Comment by jasonbahl** [comment]
@jamesshaeffer @0aveRyan ^

**Comment by ed4becky** [comment]
I believe you would need to be able to query each endpoint individually, since security on each site may differ. Similar to how the DB gets carved up

**Comment by sanderploegsma** [comment]
Just to weigh in with my experience: I've used a multisite Wordpress instance in combination with Gatsby by using a fork of the `gatsby-source-graphql` plugin, which merges the GraphQL schema from each instance and adds a parameter to delegate queries to the correct instance. This is the plugin, for reference: https://github.com/XebiaStudio/gatsby-source-graphql-multiple

This approach matches your suggested `site(id: "site.com")` and in our case would fit our needs perfectly.

**Comment by jasonbahl** [comment]
Closing this as each network site has it's own endpoint. If anyone wants to propose ideas for a specific network endpoint, I'd love to hear it, but for now I'm going to close this as there are already numerous multisite + WPGraphQL users in the wild.
