### ISSUE TITLE
PostObject fields should only be included if post_type supports them

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#405]
There are several fields that are "optional" when registering a Post Type: https://codex.wordpress.org/Function_Reference/register_post_type#supports

These fields should only be added to a PostTypeObject in the Schema if the Post Type has registered support for them, and fallback to just the defaults (title/content) if nothing is explicitly defined in the "supports" array of the post_type definition.

**Comment by jasonbahl** [comment]
Related to this conversation: https://wp-graphql.slack.com/archives/C3NM1M291/p1519007240000025

**Comment by jasonbahl** [comment]
We should implement a `ContentTypeInterface` that includes all fields a post type has (id, title, content, etc). 

Types generated by the Post Type Registry (Post, Page, etc) should implement all fields of the interface, _**but**_ if the Post Type _doesn't_ support a field, that field should be marked as deprecated for that type. 

For example we could have this interface:

```
Interface ContentType {
  id
  title
  date
  content
  ...
}
```

Then a post type that _only_ supports `title` but doesn't support date, content, etc could look like:

```
type ExampleType {
  id
  title
  date @deprecated
  content @deprecated  
}

This would allow us to query a connection like so:

```
{
  content {
    nodes {
      __typename
      id
      title
      date
      content
      ...on Page {
         somePageField
      }
      ...on ExampleType {
         someExampleField
      }
    }
  }
}
```

**Comment by jasonbahl** [comment]
After chatting with @CodeProKid this approach has changed. 

Instead of adding all fields to a common interface, then deprecating them for the Post Types that don't support them, we can define many interfaces and _add_ them to the Types that _do_ support the features. 

For example, we can define the following interfaces: 

```
Interface NodeWithTitle {
  title: String # The title of the node
}

Interface NodeWithAuthor {
  author: User # The author of the node
}

Interface NodeWithContentEditor {
  content: String # The content of the node
}

Interface NodeWithExcerpt {
  excerpt: String # The summary excerpt of the node's content
}

etc...
```

Then, for each Post Type that supports these features we can implement the Interface. 

This allows us to query posts, pages, etc the same as we do today, but would slightly change how to query a list of mixed content nodes. 


### Before (with fields deprecated)

Let's say we registered a Post Type with no support for Title and Editor. This would mean that `content` and `title` would be deprecated, so they wouldn't show in the docs, but they would still execute with a query like below:

```
{
  contentNodes {
    nodes {
      __typename
      id
      date
      title
      content
    }
  }
}
```

### Now (with fields added via interfaces)

With this new approach, fields are added via interfaces. So instead of _just working_ you do have to declare in the query that you _want_ them if they are supported, like so: 

```
{
  contentNodes {
    nodes {
      __typename
      id
      date
      ... on NodeWithTitle {
        title
      }
      ... on NodeWithContentEditor {
        content
      }
    }
  }
}
```

### More advanced examples: 

Let's say we register a Post Type with _only_ support for the title field. That means it doesn't support the editor, comments, author, etc (see: https://developer.wordpress.org/reference/functions/post_type_supports/)

```
add_action( 'init', function() {

	register_post_type( 'test_type', [
		'label' => 'Test Type',
		'show_ui' => true,
		'public' => true,
		'show_in_graphql' => true,
		'graphql_single_name' => 'TestPostTypeWithOnlyTitleSupport',
		'graphql_plural_name' => 'TestPostTypeWithOnlyTitleSupports',
		'supports' => [ 'title' ]
	] );

} );
```

The fields not supported by that Post Type shouldn't be in the Schema for said Type, but we should be able to query for many post types at once without breaking things. 

We can query like so: 
```
{
  searchResults: contentNodes(where: {search: "test"}) {
    nodes {
      __typename
      id
      databaseId
      ... on NodeWithTitle {
        title
      }
      ... on NodeWithAuthor {
        author {
          firstName
          lastName
        }
      }
      ... on NodeWithComments {
        comments {
          nodes {
            id
            content
            author {
              __typename
              ... on User {
                firstName
                lastName
              }
              ... on CommentAuthor {
                name
              }
            }
          }
        }
      }
    }
  }
}
```

And get a payload like so: 

```
{
  "data": {
    "searchResults": {
      "nodes": [
        {
          "__typename": "TestPostTypeWithOnlyTitleSupport",
          "id": "a2FubmVyOjE3NTU=",
          "databaseId": 1755,
          "title": "Test"
        },
        {
          "__typename": "Post",
          "id": "cG9zdDoxNzM5",
          "databaseId": 1739,
          "title": "Test",
          "author": {
            "firstName": null,
            "lastName": null
          },
          "comments": {
            "nodes": []
          }
        },
        {
          "__typename": "Page",
          "id": "cGFnZToxNjQw",
          "databaseId": 1640,
          "title": "Test Page Revision",
          "author": {
            "firstName": null,
            "lastName": null
          },
          "comments": {
            "nodes": []
          }
        },
      ]
    }
  }
}
```

Here, we can see that we can fetch different Types in the same query, but explicitly state at the Query level what fields we want if the type of content coming back supports it. 

We can even refactor this in various ways, such as the following, allowing for components to have more granular control over their data: 

```
{
  searchResults: contentNodes(where: {search: "test"}) {
    nodes {
      __typename
      id
      databaseId
      ... on Post {
        ...Title
        ...Author
        ...Comments
      }
      ... on Page {
        ...Title
        ...Author
      }
      ...on TestPostTypeWithOnlyTitleSupport {
        ...Title
      }
    }
  }
}

fragment Title on NodeWithTitle {
  title
}

fragment Author on NodeWithAuthor {
  author {
    firstName
    lastName
  }
}

fragment Comments on NodeWithComments {
  comments {
    nodes {
      id
      content
      author {
        __typename
        ... on User {
          firstName
          lastName
        }
        ... on CommentAuthor {
          name
        }
      }
    }
  }
}
```

**Comment by TylerBarnes** [comment]
That was great thinking, kudos @CodeProKid !
As far as naming the interfaces I vote for `... on SupportsX` as the convention. `... on NodeWithTitle` sounds like it could apply to a post that supports titles but just doesn't have one added.
