### ISSUE TITLE
WP_Query pagination uses post_date and post ID in comparison, which can exclude posts

### ISSUE THREAD

**Issue by chriszarate** [wp-graphql/wp-graphql#406]
The `where` clause returned by `Config.php#graphql_wp_query_cursor_pagination_support` compares against both the `post_date` and the post `ID` of the cursor post. For example, take the following query (using default orderby field of `DATE` and default `order` of `DESC`):

```
query {
  posts(
    after: "cG9zdDoxMA==" // post:10
 ) { ... }
}
```

The pagination `where` clause produced for this GraphQL query looks for posts with a `post_date` less than that of post 10 _and_ a post `ID` greater than `10`. This is helpful in making sure that posts that might have the same `post_date` do not get duplicated across boundaries.

However, a flaw exists around the assumption that posts with a lower post `ID` will also have an earlier `post_date`. It is sometimes the case (often for us) that posts are published out of order (e.g., post 5 lives as a draft for a long time and is published after posts 6 and 7). The current pagination logic will miss posts when the out-of-order post is the cursor post.

This issue is present in all versions of WPGraphQL.

**Comment by jasonbahl** [comment]
closed by #409
