### ISSUE TITLE
Fields should be consistently unescaped

### ISSUE THREAD

**Issue by chriszarate** [wp-graphql/wp-graphql#410]
WordPress generally follows the pattern "sanitize data going into the database, escape (late) on output." However, WP_User and WP_Term fields break this pattern. The simple reason is that `sanitize_user_field` and `sanitize_term_field` call `esc_*` functions, so they go into the database escaped:

https://github.com/WordPress/WordPress/blob/6e665d1f1523a0aeec1769d243ced9c3ff0b1434/wp-includes/user.php#L1256

https://github.com/WordPress/WordPress/blob/6e665d1f1523a0aeec1769d243ced9c3ff0b1434/wp-includes/taxonomy.php#L1538

As far as I can tell, this is a historical quirk/mistake that has been preserved for compatibility reasons. Both the REST API and current versions of WP-GraphQL output field data consistently—which is to say, they preserve the _inconsistency_ of WP Core and output unescaped data for most fields and escaped data for User and and Term fields.

I'd like to suggest that WP-GraphQL correct the inconsistency of WP Core and _unescape_ User and Term field data. That way the consuming app can treat `String` fields of all types consistently, avoiding the need to conditionally escape. Interested in thoughts / counter-arguments.

**Comment by jasonbahl** [comment]
@chriszarate I'm working on a project unrelated to GraphQL (sadly 😢), but we're syncing post_content to a NoSQL database, and we're running into issues with the escaped content. . .making it over to the synced database which is causing issues with search, as words like "here's" get sent over as "here&#8217;s" so searching "here's" in that database shows no matches. . .

So, I wrapped the content with `html_entity_decode( $content, ENT_QUOTES);` and that resolved that issue (I think). I'm not sure if we need to address any other decoding or not, but thought I'd leave this here as I think it's relevant.

**Comment by jasonbahl** [comment]
@chriszarate do you have a list of fields you believe this should apply to? I think it makes sense for WPGraphQL to output content that doesn't need further transformation from the client. 

Trying to decide if this would be a good case for a directive so folks could declare if they want the entities decoded or not 🤔

**Comment by saarnilauri** [comment]
I have runned in issues with title and excerpt fields. For example if title contains & character this is stored in database as &amp; and then I need to register custom field where I return decoded value.

Is this related to the original discussion?

**Comment by CodeProKid** [comment]
related #1035

**Comment by jasonbahl** [comment]
This is being addressed in #1337 👏
