### ISSUE TITLE
Authentication with WPGraphQL from a NextJS app

### ISSUE THREAD

**Issue by cr101** [wp-graphql/wp-graphql#412]
I'd like to build a WordPress-powered web app using NextJS.  

Since the remote request will be outside the WordPress admin, is there a way to create and use an Auth nonce for authentication with WPGraphQL using one of the [authentication plugins](https://wpgraphql.com/docs/advanced/authentication-and-authorization)?

**Comment by jasonbahl** [comment]
WPGraphQL respects the current user regardless of the mechanism used to authenticate and set the user. 

You should be able to use WPGraphQL with any of the Auth Plugins that work with the REST API such as Basic Auth (definitely the easiest to get up and running with, but not advised for production and definitely not advised with a non-secure connection) or the oAuth plugins for REST. 

I also have wp-graphql-jwt-auth that allows you to use GraphQL mutations to authenticate and retrieve tokens for use on subsequent requests. Docs are light for that plugin but you can check out the functional tests in the repo to get the gist for how to use it.

**Comment by cr101** [comment]
Is there a way to prevent people from accessing my WPGraphQL endpoint to view the data as I don't wish to expose the endpoint to the public?
Currently anyone can access my WPGraphQL endpoint on the production webapp, however, I only want my web app to fetch data from the endpoint. So if a third party tried to fetch data directly from `http://mywebsite.com/graphql` they wouldn't get any data hence I was asking about using a nonce in the remote fetch requests.

**Comment by jasonbahl** [comment]
@cr101 hey, so if you want to lock down GraphQL to everyone but certain clients, you can do so like this: 

```
add_action( 'do_graphql_request', function( $request, $operation_name, $variables ) {

	// Make sure we're only affecting requests that are HTTP requests
	if ( defined('GRAPHQL_HTTP_REQUEST') && true === GRAPHQL_HTTP_REQUEST ) { 

		// Whether the request is allowed to execute get data or not
		$allowed = false;
		
                if ( function_exists( 'someFunctionThatAllowsAcccess' ) ) {
			$allowed = someFunctionThatAllowsAcccess();
		}

		if ( true !== $allowed ) {
			wp_send_json( [
				'data' => null,
				'errors' => __( 'Sorry, you are not allowed to access content', 'your-textdomain' ),
			] );
		}

	}

}, 10, 3 );
```

Then, you need to figure out what `someFunctionThatAllowsAcccess()` does. 

You could do something like set up Application Tokens/Secrets that your application sends over in the Headers of each request, and validate the token when and return true if valid, or false if invalid or something along those lines. 

How you want to manage validating the identity of the requesting app is up to you.

**Comment by jasonbahl** [comment]
@cr101 I'm going to assume this is resolved. If you have further issues, let me know.
