### ISSUE TITLE
Field resolvers should use Enum types when available

### ISSUE THREAD

**Issue by chriszarate** [wp-graphql/wp-graphql#413]
Field resolvers (such as `status` on `Post`) often use a `String` type even when there is a corresponding Enum type that enumerates the possible values. It seems like it would make sense to use the Enum type in these situations. This has two potential benefits I can think of:

1. It enumerates the possible field values for the client, who simply has to consume the schema to learn what values to expect. Field values not defined in the Enum cannot be returned by the server (if you try, `null` is returned instead).

2. It allows the implementor to easily rename field values via a `graphql_{$type}_values` filter (instead of overriding the field resolver, a more drastic approach). This would allow an implementor to represent a post status of `future` as `SCHEDULED` or something else that is semantically meaningful to the client.

This would be a very minor change, e.g.:

```diff
'status'            => [
-	'type'        => Types::string(),
+	'type'        => Types::post_status_enum(),
	'description' => __( 'The current status of the object', 'wp-graphql' ),
	'resolve'     => function( \WP_Post $post, $args, AppContext $context, ResolveInfo $info ) {
		return ! empty( $post->post_status ) ? $post->post_status : null;
	},
],
```

Again, in this example, any value returned by the field resolver that is not enumerated by `PostStatusEnumType` would result in `null`.

Potential drawbacks:

1. The field value would immediately change from a lowercase to an uppercase string (e.g., `"PUBLISH"` instead of `"publish"`). This could be a breaking change for some users.

2. It could be confusing for new users why some field values are enums (or, more remedially, uppercase strings) and some are not.

**Comment by justlevine** [comment]
Leaving this closed. A lot of field types have changed since this issue was originally created, and beyond a generalized audit before v2.0 for breaking changes, it's more effective/actionable to open individual issues with proposals for specific changes.
