### ISSUE TITLE
cannot access user info through userId

### ISSUE THREAD

**Issue by ganeshr28** [wp-graphql/wp-graphql#414]
i want to access user through userId but it takes Id which is some random id generated

![test](https://user-images.githubusercontent.com/32222445/37391049-1014321c-2790-11e8-9404-0b7ad46876d5.png)
i want to access user details through userId which is shown in database but with Id the above string which is randomly generated there is no way to check which user has which id

**Comment by jasonbahl** [comment]
@ganeshr28 hey! The IDs are global IDs that are base64 encoded combination of `type:$id`, so in this case the user's ID is `base64encode( 'user::2722' );` which is `dXNlcjoyNzIy`

These IDs are global IDs, a concept that is foreign to WordPress itself, but important to caching clients, such as Apollo. 

Caching clients normalize nodes from the graph and need a globally unique ID to identify the node for future mutations. In WordPress many things can have the same ID. For example, you could have a user with ID 1, a post with ID 1, a taxonomy term with ID 1, and a comment with ID 1. 

In a normalized cache, this would be problematic. 

Having the GraphQL API provide a globally unique ID helps reduce the risk of conflicts in a caching client. 

We do understand that the database ID still may be useful as a paramater to query for information, so we will work on adding support for getting nodes by database ID as well.

**Comment by jasonbahl** [comment]
I'm closing this in favor of #263

**Comment by ganeshr28** [comment]
thankyou so much for the information @jasonbahl
