### ISSUE TITLE
Online schema/API docs

### ISSUE THREAD

**Issue by rektide** [wp-graphql/wp-graphql#415]
Hello. I'm interested in what WordPress and wp-graphql can do for me. I was hoping to get a sense of what kind of APIs would be available. (In particular, I was looking to see whether any kind of "events" capability was a part of the base API or not). Unfortunately, the docs tell me [I have to install WordPress and wp-graphql](https://wpgraphql.com/docs/getting-started/exploring-with-graphiql) to begin to see what is offered.

I and I'm sure others would greatly enjoy having some way to get a sense of the graphql schemas available without needing to have a working wordpress instance we have the liberty of installing untested extensions on.

Please provide some links or other online means to see the schemas that this extension makes available.

**Comment by jasonbahl** [comment]
@rektide There are examples of queries, etc in the docs if you explore a bit more, for example: https://wpgraphql.com/docs/getting-started/queries#list-of-posts

You can also check out https://playground.wpgraphql.com which has various examples of queries, etc to give you an idea of how to consume the data on the client. There's even some examples showing how to use Queries in React and how the components are rendered below, such as: https://playground.wpgraphql.com/#/aliases-in-action and https://playground.wpgraphql.com/#/custom-types-in-action

If you want to add to the docs, the website wpgraphql.com is a Gatsby site and the content is all Markdown files in the repo, so as you learn things, if you want to add to the docs, PRs are welcome. https://github.com/wp-graphql/wpgraphql.com
