### ISSUE TITLE
How to handle frontPage & pageTemplates?

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#428]
It's common for pages to be treated very different based on whether they are the Front Page or of a particular Page Template. 

Right now, you can query a page and it's fields like so:

```
{
  page {
     title
     content
     someMetaField
  }
}
```

But _all_ pages are treated the same here. They all have the same Schema. 

As brought up [here](https://wp-graphql.slack.com/files/U9W6627D0/FA5CTNK3R/screen_shot_2018-04-10_at_19.48.40.png) (and the surrounding conversation) it might be nice to be able to query for things conditionally. 

My initial thought is to introduce some sort of Union for handling pages. 

So, possibly it could become: 

```
{
  page {
     ...on FrontPage {
        someFrontPageField
    }
    ...on CustomPageTemplate {
       someFieldThatExistsOnJustThisTemplate
    }
    ...on DefaultTemplate {
        title
        content
     }
  }
}
```

This would allow for folks to register meta to show up only in the appropriate pieces of their Schema. 

Need to think about use cases more but wanted to get some thoughts out there for discussion while it's fresh in my head.

**Comment by jasonbahl** [comment]
After thinking about this a bit more, I think Post Types that support templates should get a `template` field which returns a `PageTemplateUnion` and each registered page template get's it's own Type.

Then we can query something like: 

```
{
  page {
    id
    title
    template {
        __typename
        name
        ...on HomePageTemplate {
           someHomePageField
        }
        ...on ContactPageTemplate {
           someContactPageField
        }
    }
  }
}
```

See conversation here: https://wp-graphql.slack.com/archives/C3NM1M291/p1550506403167100?thread_ts=1550481491.162000&cid=C3NM1M291

**Comment by izzygld** [comment]
How would we `register_graphql_field` just for that specific page-template and not show up on other pages.

something like:

```
register_graphql_field( 'HomePageTemplate', 'customField1', [
  'description' => __( 'The description of the field that's only intended for use on the HomePageTemplate', 'your-textdomain' ),
  'resolve' => function ( $post ) {
     return get_post_meta( $post->ID, 'customField1', true );
  }
])
```

**Comment by lmounsey** [comment]
Any update on this one @jasonbahl ? 

I'm currently setting up a Nuxt/GraphQL stack and hitting a snag with page templates and custom fields. Currently as a workaround I'm just adding additional fields for stubbing out the template slug and all ACF fields so I can map it to a specific template and bind all this ACF data.

Would be great if we could do something as you mentioned above

**Comment by samburgers** [comment]
If you add this to your `functions.php` you can fetch the page template slug in your queries:

```
add_action('graphql_register_types', function () {
    register_graphql_field('Page', 'pageTemplate', [
        'type' => 'String',
        'description' => 'WordPress Page Template',
        'resolve' => function ($page) {
            return get_page_template_slug($page->pageId);
        },
    ]);
});
```

**Comment by lmounsey** [comment]
I've got something similar to get the page template, but the issue I'm experiencing is trying to query certain fields for certain page templates.

Currently can only query ACF fields that belong to all Page templates, but not ones that only exists on one without building additional functionality

**Comment by justinradomski** [comment]
I'm having the same issue as @lmounsey. Almost all of my custom field groups are configured for specific page templates, but I'm unable to see them.

**Comment by 19h47** [comment]
To check front page, I add a `pageOnFront` field to my schema
```
function graphql_register_page_on_front() {
	register_graphql_field(
		'Page',
		'pageOnFront',
		array(
			'type'        => 'Boolean',
			'description' => 'WordPress page on front option',
			'resolve'     => function( object $page ) {
				$page_on_front_id = (int) get_option( 'page_on_front' );

				return $page->pageId === $page_on_front_id;
			},
		)
	);
}

add_action( 'graphql_register_types', 'graphql_register_page_on_front' );
```

**Comment by bsides** [comment]
Hi @19h47 do you mind elaborate on how to add that and how to query it? Thank you

**Comment by 19h47** [comment]
Hello @bsides, you can add this snippet in your `functions.php`, then you can retrieve in your schema the `pageOnFront` field.

But, since the [0.4.1 version](https://github.com/wp-graphql/wp-graphql/releases/tag/v0.4.1), thanks to @jasonbahl and @zgordon, this is obsolete: the boolean `isFrontPage` field has been added directly to the page schema.

**Comment by bsides** [comment]
> But, since the [0.4.1 version](https://github.com/wp-graphql/wp-graphql/releases/tag/v0.4.1), thanks to @jasonbahl and @zgordon, this is obsolete: the boolean `isFrontPage` field has been added directly to the page schema.

I noticed it, thanks!

I just would like to retrieve it as a filter, like { pages { where: { isFrontPage: true } } } but I don't think I can change what can go in as `RootQueryToPageConnectionWhereArgs`, could I?

**Comment by Twansparant** [comment]
> I just would like to retrieve it as a filter, like { pages { where: { isFrontPage: true } } } but I don't think I can change what can go in as `RootQueryToPageConnectionWhereArgs`, could I?

Don't think you can... That's a shame because now you can't query just the front page without adding a custom field yourself.

**Comment by ssoney200** [comment]
> If you add this to your `functions.php` you can fetch the page template slug in your queries:
> 
> ```
> add_action('graphql_register_types', function () {
>     register_graphql_field('Page', 'pageTemplate', [
>         'type' => 'String',
>         'description' => 'WordPress Page Template',
>         'resolve' => function ($page) {
>             return get_page_template_slug($page->pageId);
>         },
>     ]);
> });
> ```

Nice! 

On top of that, is anyone aware you’re yet how we can add option to RootQueryToPageConnectionWhereArgs so that we can filter pages by pageTemplate, like: 

```
query MyQuery {
  pages(where: {pageTemplate: "page-templates/visit-a-campus.php"}) {
    nodes {
      title
      pageTemplate
}
}
}
```

**Comment by sami616** [comment]
Would be lovely to be able to ask for post type, then template in the same query conditionally. 

Something like:

```graphql
nodeByUri(uri: "/") {
    __typename
    id
    uri
    ... on Post {
      title
    }
    ... on Page {
      title
      ... on HomeTemplate {
          # homepage specific fields
      }
      ... on BlogTemplate {
          # blog specific fields
      }
    }
}
```

**Comment by kiranmarshall** [comment]
> On top of that, is anyone aware how we can add option to RootQueryToPageConnectionWhereArgs so that we can filter pages by pageTemplate, like:
> 
> ```
> query MyQuery {
>   pages(where: {pageTemplate: "page-templates/visit-a-campus.php"}) {
>     nodes {
>       title
>       pageTemplate
> }
> }
> }
> ```
> 
> I have many custom templates which I would like to root via gatsby-node.js to create the pages for any items using these templates. If anyone is aware of an alternate method I'm also all ears

Has there been any progress on this/anyone found a fix? I desperately need something like this, but because I specialise in JS I'm absolutely drowning here trying to write some php which will do this. I don't understand how it's written or the documentation well enough.

**Comment by tayyabkhan720** [comment]
Can we get the content of page in react wp graphql? If yes ...then how?

**Comment by jasonbahl** [comment]
We've added various types of support for understanding what the home page is and querying templates. 

Here are some examples:

## Home Page 

### Homepage: latest posts

If your homepage is set to show your latest posts: 

![Image](https://user-images.githubusercontent.com/1260765/182655078-9b9fd4ca-4500-4542-9220-e1e007e53e14.png)

You can query like so: 

```graphql
query MyQuery {
  nodeByUri(uri: "/") {
    __typename
    ... on ContentType {
      contentNodes {
        nodes {
          __typename
          id
          ... on NodeWithTitle {
            title
          }
        }
      }
    }
  }
}
```

And get results like so:

![Image](https://user-images.githubusercontent.com/1260765/182656806-c4a77e81-f77c-45f0-bc10-50012917db52.png)

### Homepage: static page

If your homepage is set to be a static "page":

![Image](https://user-images.githubusercontent.com/1260765/182656421-b41c9f73-5b0d-4a61-8042-d2093d6ac855.png)

You can query like: 

```graphql
query MyQuery {
  nodeByUri(uri: "/") {
    __typename
    ... on Page {
      id
      title
      uri
      isFrontPage
    }
  }
}
```

And get results like so:

![Image](https://user-images.githubusercontent.com/1260765/182656679-69451301-5fe5-4491-abb2-693f096bac5d.png)

### isFrontPage

The `isFrontPage` field can also help identify if a page is indeed the front page. 

For example, if you were querying a list of pages from WPGraphQL for use in a static site generator, and wanted to know which page in the list is the front page, you could query like so: 

```graphql
{
  pages {
    nodes {
      id
      title 
      uri
      isFrontPage
    }
  }
}
```

And you would get results like so, where the page set as the front page would have a `true` value for the `isFrontPage` field. 

![Image](https://user-images.githubusercontent.com/1260765/182657628-f70c5942-bbc6-420d-8604-97005507c9cc.png)
 

## Page Templates

When querying content nodes (Types that represent post types, i.e. `Page`, `Post`, etc), there's a `template` field that can be queried like so: 

```graphql
{
  pages {
    nodes {
      id
      title
      uri
      isFrontPage
      template {
        __typename
        templateName
      }
    }
  }
}
```

And if I had a page set to use a custom template, for example, maybe my "Home" page was set to use the "Home" template:

![Image](https://user-images.githubusercontent.com/1260765/182659682-34e2dced-21a2-4474-8118-20c13980107c.png)

Then I might see results of the query like so: 

![Image](https://user-images.githubusercontent.com/1260765/182659810-2702f845-9cda-4078-860c-189b7bcc2f67.png)

Each page would return the `DefaultTemplate` type, but if a custom template was selected, it would return that Type, like the `Template_Home` type in this example. 

Since each template is its own Type in the GraphQL Schema, custom fields can also be applied to the Type using plugins such as Advanced Custom Fields, etc.

**Comment by clintvidler** [comment]
> 

This worked for me. 

'facilityTemplate' is the where field in this example.

```
/**
 * Add a 'where' field to query args on the content type
 */
add_action('graphql_register_types', function () {
  $customposttype_graphql_single_name = "Facility";

  register_graphql_field('RootQueryTo' . $customposttype_graphql_single_name . 'ConnectionWhereArgs', 'facilityTemplate', [
    'type' => 'String',
    'description' => __('The facility template to filter by', 'my-theme'),
  ]);
});

/**
 * Apply a filter to the created 'where' arg on the content type
 */
add_filter('graphql_post_object_connection_query_args', function ($query_args, $source, $args, $context, $info) {
  $post_object_id = $args['where']['facilityTemplate'];

  if (isset($post_object_id) && !empty($post_object_id)) {
    $query_args['meta_query'] = [
      [
        'key' => '_wp_page_template',
        'value' => 'templates/' . $post_object_id . '.php',
        'compare' => 'IN',
      ]
    ];
  }

  return $query_args;
}, 10, 5);

```

Put these into your functions.php file or similar.
