### ISSUE TITLE
Add featuredImage field to Post mutation

### ISSUE THREAD

**Issue by hughdevore** [wp-graphql/wp-graphql#435]
We are currently able to query for a post's featured image:

```graphql
{
  posts {
    edges {
      node {
        postId
        title
        featuredImage {
          id
          title
          link
        }
      }
    }
  }
}
```

However, we are not able mutate this field when we create a post. I propose we add this field so that users are able to add/update/delete the featured image of a post. This could look something like:

```graphql
mutation {
  createPost(input: {
    title: "New Post with Fancy Image",
    featuredImage: {
      url: "images.com/sweet-image.jpg"
      title: "Sweet Featured Image",
    }
  }) {
    clientMutationId
    post {
      id
      title
      featuredImage {
        id
        title
        link
      }
    }
  }
}
```

The fields for the featuredImage mutation should match the fields of a mediaItem mutation.

**Comment by jasonbahl** [comment]
@hughdevore do you plan to implement this via sideloading, or via a file upload and multipart form?

**Comment by hughdevore** [comment]
@jasonbahl, planning on adding this via sideloading next sprint. I may have time to do the multipart as well but I think we should make it a separate issue.

**Comment by jasonbahl** [comment]
@hughdevore so, I think for the core plugin we could support a nested `featuredImage` input on post mutations that accepts the ID of the featuredImage and sets the relationship during post creation/upates. . .but I don't think we should support uploading an image as a nested input. 

I believe the most common scenario for most applications would be to have separate mutations for creating images and creating posts, and just set the relationship to each other during their respective mutations. 

So, I think we can add a nested `featuredImage` input field, but it should expect an ID and simply set the relationship (if the ID is a valid media item).

**Comment by hughdevore** [comment]
Agreed, I think that's a solid solution, keeping the mutations separate will help with maintenance in the long run. I'll work on a PR for adding this.

**Comment by DSchau** [comment]
Just to chime in on this -- it's currently impossible to set a featured image on a post with WPGraphQL entirely, correct? Is there a workaround in lieu of this feature continuing to be worked upon?

**Comment by jasonbahl** [comment]
@DSchau you can try using the REST API for the time being?

https://gist.github.com/ahmadawais/0ccb8a32ea795ffac4adfae84797c19a

**Comment by jasonbahl** [comment]
I think the GraphQL ecosystem has settled on some “formal” ways of handling uploads, so I plan to revisit this soon.

**Comment by DSchau** [comment]
@jasonbahl that was gonna be my fallback -- good to know. Thank you!

**Comment by jasonbahl** [comment]
I believe uploading an image and mutating an image should be its own mutation. 

i.e. 

```
mutation createMediaItem { ... }
mutation updateMediaItem { ... }
etc
```

I think associating a featured image to a post should be allowed by passing the ID of an already existing image, but I don't think we should allow a `createPost` mutation to also `create` (upload) an image or mutate data about the image. 

I believe the right approach will be to add `upload` mutations (similar to what exists in this extension: https://github.com/dre1080/wp-graphql-upload

And we can (this can happen separately) add a field that accepts an ID of a mediaItem and associates it with the post. 

something that would allow for a mutation like so: 

```
mutation {
  updatePost( input: {
     id: "123"
     featuredImageId: "456"
  } ) {
     post {
       id
       featuredImage {
         node {
            id
            sourceUrl
         }
       }
     }
  }
}
```
