### ISSUE TITLE
Add userRoles entry point

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#444]
We should add an entry into the Graph for userRoles.

The resolver should limit returning data to authenticated users by default. 

A query like: 
```
{
  userRoles {
    id
    name
    capabilities
  }
}
```

Should return something like: 

```
{
  data: {
    userRoles: [
       {
         id: "cm9sZTphZG1pbg=="
         name: "admin",
         capabilities: [
			"edit_posts",
            "moderate_comments",
            ...
         ],
       }
    ]
  }
}
```

This should also support filtering by specific role: 

```
{
  userRoles( where: { name: "admin" } ) {
    ...RoleFields
  }
}
```

**Comment by CodeProKid** [comment]
@jasonbahl would be cool if this was also a connection on the `User` type.

**Comment by jasonbahl** [comment]
Something like this to get users based on a particular capability: https://stackoverflow.com/a/35347895/5352288?

**Comment by CodeProKid** [comment]
@jasonbahl I'm going to start working on this. What should the `ID` consist of?

**Comment by jasonbahl** [comment]
Maybe `role:{rolename}` 🤔

Needs to be unique to be able to cache it/query for it via a `node` query.

**Comment by CodeProKid** [comment]
ok, makes sense. The name of the role _should_ be unique for each individual site.
