### ISSUE TITLE
How to handle file uploads?

### ISSUE THREAD

**Issue by dre1080** [wp-graphql/wp-graphql#449]
Is there any way to use this with [graphql-upload](https://github.com/Ecodev/graphql-upload)? To implement [GraphQL multipart request spec server](https://github.com/jaydenseric/graphql-multipart-request-spec#server)

**Comment by jasonbahl** [comment]
@dre1080 not yet. we have another issue for this: #311 

Hoping to address it soon, but no concrete timeline yet.
