### ISSUE TITLE
Fix code coverage reports

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#462]
Code coverage reports are broken. Need to get them fixed. 

I believe they stopped working sometime around the time we added functional/acceptance testing because it would require tracking coverage for all types of tests then merging the coverage or something to that tune. 🤔

**Comment by jasonbahl** [comment]
@hughdevore fix this, bro.

**Comment by CodeProKid** [comment]
This was fixed in #530
