### ISSUE TITLE
Excerpts not outputting content as expected

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#464]
The excerpts are not being output properly for posts that don't have an excerpt explicitly saved. 

Typically, if a Post hasn't saved an excerpt explicitly, WordPress truncates the_content and outputs it as the excerpt. 

The REST API respects that behavior, but WPGraphQL doesn't currently respect that. 

You can see a comparison here: 

**WPGraphQL excerpt**
http://api.wpgraphql.com/graphql?query={posts{edges{node{id,title,content,excerpt}}}}

**REST API Excerpt**
http://api.wpgraphql.com/wp-json/wp/v2/posts

**Comment by ChaosExAnima** [comment]
I think I uncovered what's going on. Internally, WPGraphQL calls the `get_the_excerpt` filter in wp-graphql/src/Type/PostObject/PostObjectType.php:230.

Internally, WordPress calls [`wp_trim_excerpt`](https://developer.wordpress.org/reference/functions/wp_trim_excerpt/) on that filter, which in turn calls [`get_the_content`](https://developer.wordpress.org/reference/functions/get_the_content/). That checks the global `$page` and `$pages` variables, which in the case of WPGraphQL are not correctly set, so it fails with a PHP warning.

The fix would be to call `setup_postdata` before the filter is called. A workaround can be done with the following code:
```php
add_filter( 'get_the_excerpt', 'filter_fix_464', 9, 2 );
function filter_fix_464( $excerpt, $post ) {
	setup_postdata( $post );
	return $excerpt;
}
```

**Comment by jasonbahl** [comment]
@ChaosExAnima thanks for digging into this. very helpful information.

**Comment by jasonbahl** [comment]
I've got a fix coming that runs `setup_postdata()` centrally in WPGraphQL in the `DataSource::resolve_post_object()` method so any other fields that need the postdata setup appropriately can take advantage of it, instead of having to `setup_postdata` within individual post resolvers.

**Comment by ChaosExAnima** [comment]
Awesome! Let me know if you need me to test.

**Comment by jasonbahl** [comment]
@chaosexanima can you confirm this works the way you expect now?
