### ISSUE TITLE
Bug: Querying sourceUrl for featuredImage sizes returns filename

### ISSUE THREAD

**Issue by JesseRWeigel** [wp-graphql/wp-graphql#468]
https://github.com/wp-graphql/wp-graphql/blob/0c2f5221b43c2c445cde2a60243c1b29036f24b9/src/Type/MediaItem/MediaItemType.php#L288

I believe the line included above needs to be changed. 

Here is an example of this query in action:
![image](https://user-images.githubusercontent.com/11077930/42655112-083f4f4c-85e9-11e8-9e95-7690ac03fd9f.png)

You can see that sourceUrl and file both return the same value. A full url should be returned for sourceUrl.

**Comment by jasonbahl** [comment]
@JesseRWeigel I just merged a fix for this to the `develop` branch 😄
