### ISSUE TITLE
Filters using `the_title` cause fatal errors

### ISSUE THREAD

**Issue by ChaosExAnima** [wp-graphql/wp-graphql#470]
Using WPGraphQL version 0.0.29. When querying a post title, plugins that expect two parameters for `the_title` filter cause a fatal error. It appears in #230 the filter was applied without specifying the post ID second parameter, as per the WordPress [hook documentation](https://developer.wordpress.org/reference/hooks/the_title/).

To reproduce:
1. In a WordPress installation, have code that expects two parameters for `the_title`. Example:
```php
add_filter( 'the_title', function( $title, $id ) {
    return $title;
}, 10, 2 );
```
2. Query a post via WPGraphQL.

**Results**
* Get PHP error similar to as follows:
```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function [function].
```
* Query returns `title` field as `null`.

**Expected result**
The query returns the post title.

**Comment by jasonbahl** [comment]
@ChaosExAnima Thanks for submitting the issue. Checking this out.

**Comment by jasonbahl** [comment]
@ChaosExAnima this was fixed by @kidunot89 (Thanks! 👏 ) in #471. Merged to `develop` and will be part of the next release.

**Comment by jasonbahl** [comment]
tbh, kind of random right now. 

I can get a release prepared asap though as there are a lot of goodies that have made it to dev that deserve to be released. 

Then I'd like to try and make it more regular like every Friday or something like that.

**Comment by ChaosExAnima** [comment]
A release soonish would be appreciated, as this is breaking some things. If it'll be more than a day or two I can point our Composer to use development for now, though.
