### ISSUE TITLE
Auth / accessing private posts

### ISSUE THREAD

**Issue by almorgan** [wp-graphql/wp-graphql#486]
Hey guys,

I was just exploring the JWT plugin and was just testing a few things out / seeing how it works.

By default though (without the JWT plugin) I seem to be able to access private posts through the graphql queries whilst the default wp-json returns a "rest_forbidden" -> "Sorry, you are not allowed to do that."

Even if I install a plugin such as "Force Login" which redirects every page to the login and blocks all rest endpoints I still seem to be able to access all the sites data through the graphql queries (not logged in nor have I saved a JWT token).

Not sure if I'm missing something or potentially that bit hasn't been done yet?

Loving the plugin so far though!

Many thanks

**Comment by jasonbahl** [comment]
@almorgan ya, we have some open issues to address this still. 

#375 and #245 are 2 that come to mind.

**Comment by jasonbahl** [comment]
@almorgan happy to chat with you more if you're interested in working on helping with the solution. 😄

**Comment by almorgan** [comment]
Hey @jasonbahl 

Thanks for the quick response.

Sure thing! quite new to graphql so can't promise anything but more than happy to have a look if you can point me in the right direction.

**Comment by jasonbahl** [comment]
@almorgan are you in the wp-graphql Slack?
