### ISSUE TITLE
Excerpt is always of the first post

### ISSUE THREAD

**Issue by seimsel** [wp-graphql/wp-graphql#503]
I tried to get the excerpt of all my posts using this query:

```
{
  posts {
    edges {
      node {
        id
        title
        excerpt
      }
    }
  }
}
```

The result was:

```
{
  "data": {
    "posts": {
      "edges": [
        {
          "node": {
            "id": "cG9zdDo1",
            "title": "This is a Test",
            "excerpt": "<p>Welcome to WordPress. This is your first post. Edit or delete it, then start writing!</p>\n"
          }
        },
        {
          "node": {
            "id": "cG9zdDox",
            "title": "Hello world!",
            "excerpt": "<p>Welcome to WordPress. This is your first post. Edit or delete it, then start writing!</p>\n"
          }
        }
      ]
    }
  }
}
```

When I look at it with the normal Wordpress frontend the two post do **not** have the same content.

**Comment by izzygld** [comment]
Try adding this to your function.php file:

`  add_action( 'do_graphql_request', function () {
    add_filter( 'get_the_excerpt', function ( $excerpt, $post ) {

      return !empty( $excerpt ) ? $excerpt : wp_trim_words( strip_shortcodes($post->post_content) );
    }, 10, 2 );
  } );`

**Comment by jasonbahl** [comment]
Sounds like the global post isnt getting set properly as the posts are being resolved. 

I’ll see what I can find out.

**Comment by jasonbahl** [comment]
I beleive this was fixed by #504 but need to confirm

**Comment by CodeProKid** [comment]
@jasonbahl I wonder if we should maybe use this ticket to write a test that asserts this does not happen? Would be pretty easy to do.

**Comment by jasonbahl** [comment]
Ya, good call.

**Comment by CodeProKid** [comment]
This was fixed, we just need to write a test to make sure it doesn't happen in the future. That will happen in #576
