### ISSUE TITLE
postBy behaves in an inconsistent way

### ISSUE THREAD

**Issue by Hellenic** [wp-graphql/wp-graphql#504]
Hey!

I came across a scenario in which postBy returns inconsistent responses. In short, if there's any filters for the post that modify the post's content, then `postBy(id:"cG9zdDox")` works correctly while `postBy(slug:"hello-world")`  does not.

We use WooCommerce Memberships plugin, which basically can be used to restrict post / page content to certain users or user groups. That plugin basically modifies returned `content` for Post and displays full `content` only when logged in with proper user. Out-of-the-box that works good with REST API and mostly with WP GraphQL as well (which is great!). If I try e.g. `posts` or `postBy(id:"xyz")` those work correctly and `content` is properly modified. However, if I do `postBy(slug:"post-slug")` then I receive the post content without any modifications, so that part doesn't seem to be working correctly.

This far I was able to add a work-around for this, but still didn't get to the root cause. Unfortunately I don't have full repo to reproduce this :/ 
Here's my commit for the work-around if it helps at all: https://github.com/Hellenic/wp-graphql/commit/232016da3cd9fca6b5cb494e70416bc046a1e416
With that commit in place, `postBy(slug..)` also properly modifies the content, even though that most likely is not the right way to address this problem.

Versions:
* WordPress 4.9.8
* WP GraphQL - develop branch

**Comment by jasonbahl** [comment]
Hey! Thanks for reporting this. I see what the issue is and should be able to get it fixed today. 

Thanks!

**Comment by Hellenic** [comment]
Glad if that was any help. Thank you!

Also thanks for the great plugin! :)

**Comment by jasonbahl** [comment]
@Hellenic I submitted a PR that I _believe_ will fix the issues you ran into. 

Can you check out #506 and see if it's working better for you?

**Comment by Hellenic** [comment]
Hey @jasonbahl, just tried this out and works great. Thank you!
