### ISSUE TITLE
Menus not returning ChildItems

### ISSUE THREAD

**Issue by hblackett** [wp-graphql/wp-graphql#505]
I've just run into an issue where childItems of a menuItems object were not returning.

<img width="1117" alt="screen shot 2018-08-29 at 14 57 37" src="https://user-images.githubusercontent.com/4136219/44792475-e8dedb80-ab9b-11e8-9deb-49ec7ed3d27d.png">

I changed the menu name in WP (from 'Header Menu' to 'ALW Menu') and suddenly the childItems work as expected:

<img width="983" alt="screen shot 2018-08-29 at 14 59 18" src="https://user-images.githubusercontent.com/4136219/44792644-470bbe80-ab9c-11e8-89cb-2123cb22a21f.png">

<img width="1119" alt="screen shot 2018-08-29 at 14 49 13" src="https://user-images.githubusercontent.com/4136219/44792311-84bc1780-ab9b-11e8-970f-6c052ab7df28.png">

If I change the menu name back to 'Header Menu' it breaks the childItems.

It's a localhost install running WP GraphQL 0.0.34 on WP 4.9.8 with all other plugins disabled. I've tried recreating the issue on a separate install but everything is working as expected – can't seem to find the magical menu name that will break things!

**Comment by izzygld** [comment]
i just came across the same issue.

i had to delete the `Header_menu` and remake the menu.

(i was using [see here](https://gist.github.com/izzygld/287aa48a90d170dabd9ba479196ea695)

But we should definitely look into it.

**Comment by jasonbahl** [comment]
Wait, so you’re saying on a fresh install “Header Menu” does work as expected?

**Comment by hblackett** [comment]
Ha, yes! Things are working as expected on a fresh install.

But on the localhost install where I found the issue, I tried deleting and rebuilding the menu and `childItems` would only work with some menu names ('Header Menu', 'Main Nav' and others didn't work; possibly conflicting with previous menus that I had deleted?).

**Comment by izzygld** [comment]
i found this to be true too.

When renaming the menu and quering to the new menu name things went back to being good 👍

**Comment by jasonbahl** [comment]
Strange. I'll see what I can find out. Curious if this is specifically an issue with WPGraphQL or an underlying issue. Thanks for reporting and thanks for the added details.

**Comment by ElisaMassafra** [comment]
In my experience it works only if it's the first menu in the list. I see that it always returns the items for the first menu (MenuItemConnectionResolver -> probably line 46, where it always returns the childItems for $menus[0]->slug from $menus?

**Comment by ElisaMassafra** [comment]
Created a pull request to fix the issue
 https://github.com/wp-graphql/wp-graphql/pull/522

**Comment by blocka** [comment]
Hopefully not too late for this: but in my opinion, it is better to return all the menus items flattened rather than nested. There is no way, with graphql, to return an infinitely nested structure recursively....you would have to know, for example, that there are three levels of menus, for example.

Returning them flat is trivial, as that's the raw results from get_nav_menu_items, and it's not difficult to "unflatten" it on the client side.

**Comment by jasonbahl** [comment]
@blocka hey! It's definitely not too late! 

We can actually support both. We support both for Categories via the `shouldOutputInFlatList` argument. 

You can read more about it here: https://github.com/wp-graphql/wp-graphql/pull/387#issue-167839697

I think it would be beneficial to support both options. I think there are cases where folks will want to be very explicit about how they query their menus and they will know for sure that they _only_ want to support 3 levels or something, and I think other cases would want to know _all_ items and then decide how to fold them into a hierarchy for presentation on the client.

Let's open a new issue to track this specific request. I don't think it would be _too_ difficult to implement, especially if we follow the prior implementation for hierarchical terms.

**Comment by jasonbahl** [comment]
@blocka created an issue to track this: https://github.com/wp-graphql/wp-graphql/issues/534

I also labeled it #hacktoberfest should anyone want to work on it and [get a t-shirt from Digital Ocean](https://hacktoberfest.digitalocean.com/) 😄

**Comment by jasonbahl** [comment]
closed by #524

**Comment by algebrathefish** [comment]
@hblackett how were you able to find the nested menu items when it worked? I don't know how to find them, so I don't know if it's working or not
