### ISSUE TITLE
graphql_request_data filter is not executed for POST requests

### ISSUE THREAD

**Issue by epeli** [wp-graphql/wp-graphql#509]
It's only applied in this else-if

https://github.com/wp-graphql/wp-graphql/blob/aa69a640b6877292a84a710c7270ac7403680b95/src/Router.php#L359

and twice inside it

https://github.com/wp-graphql/wp-graphql/blob/aa69a640b6877292a84a710c7270ac7403680b95/src/Router.php#L367-L372

and

https://github.com/wp-graphql/wp-graphql/blob/aa69a640b6877292a84a710c7270ac7403680b95/src/Router.php#L398-L403

Which doesn't seem right neither.

**Comment by jasonbahl** [comment]
@epeli ya, this was a mistake for sure. Thanks for pointing it out!

**Comment by CodeProKid** [comment]
This should actually get fixed with #621

**Comment by jasonbahl** [comment]
@CodeProKid since this is addresed by #621 and #621 does introduce a breaking change, let's put this in the next version-bump release milestone with that

**Comment by jasonbahl** [comment]
fixed by #621
