### ISSUE TITLE
Support User Taxonomies

### ISSUE THREAD

**Issue by kellenmace** [wp-graphql/wp-graphql#511]
If you register a taxonomy and assign it to the User object, it currently isn't supported by WPGraphQL.

When I register a User taxonomy and try to add WPGraphQL support by passing in the `show_in_graphql`, `graphql_single_name` and `graphql_plural_name` args like I would for any other taxonomy, I get:
```
    Fatal error: Uncaught TypeError: Argument 1 passed to 
    WPGraphQL\Type\TermObject\Mutation\TermObjectCreate::mutate() must be an instance of 
    WP_Taxonomy, instance of stdClass given, called in /app/public/wp-content/plugins/wp- 
    graphql/src/Type/RootMutationType.php on line 130 and defined in /app/public/wp- 
    content/plugins/wp-graphql/src/Type/TermObject/Mutation/TermObjectCreate.php on line 27
```

**Steps to reproduce:**
1. Activate a plugin like this one to set up User taxonomies: https://wordpress.org/plugins/lh-user-taxonomies/ (or set them up manually with these steps: http://justintadlock.com/archives/2011/10/20/custom-user-taxonomies-in-wordpress)
2. As that plugin's documentation shows, register a new taxonomy and pass in `'user'` for the `$object_type` param.
3. Try to fire off a WPGraphQL query or visit the `example.com/graphql` endpoint in a browser to encounter the error above.

**Expected behavior:**
Should be able to run queries and mutations against a taxonomy that is registered to a User object, just as we can for those registered to post objects.

WPGraphQL version: 0.0.32
WordPress version: 4.9.8

**Comment by jasonbahl** [comment]
Good catch @kellenmace!

**Comment by kellenmace** [comment]
Related WP core ticket: https://core.trac.wordpress.org/ticket/31383

Sounds like currently, `WP_User_Query()` does not support finding users with one or more tax terms. If the taxonomy only applies to the `user` object and nothing else, you can do:
`$users = get_objects_in_term( $term_id, $taxonomy );`
...but if the tax term is applied to other object types as well, then you have to run the line above, then filter the results to remove any that aren't `WP_User` objects.

**Comment by jasonbahl** [comment]
@kellenmace we've decided to close this, as the core WP-Admin and any core Twenty-* theme doesn't make use of this feature. 

I definitely think this would be a RAD feature for use with GraphQL, but let's start by approaching it from a plugin where it filters in the necessary functionality where applicable.

**Comment by kellenmace** [comment]
Thanks @jasonbahl.  The more I thought about this, I came to the same conclusion. Especially since core doesn’t officially support it. 👍🏼
