### ISSUE TITLE
WP-CLI Schema Validation Command

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#512]
GraphQL PHP has a handy Schema Validation function intended for use in CLI tooling. 

We should add a `wp graphql validate` command. 

See: https://webonyx.github.io/graphql-php/type-system/schema/#schema-validation

**Comment by CodeProKid** [comment]
@jasonbahl this sounds tasty. I'll take a look at this if I have some time.

**Comment by jasonbahl** [comment]
Closing this as it's never come up as something any user (including myself) has asked for or needed. Willing to re-open if someone sells the case more.
