### ISSUE TITLE
Theme mods queries and mutations

### ISSUE THREAD

**Issue by CodeProKid** [wp-graphql/wp-graphql#513]
This is mainly to track #489. @kidunot89 did some great work on this, and I just want to make sure it gets tracked, and merged into the next release.

**Comment by jasonbahl** [comment]
Closed #571. You can read why here: https://github.com/wp-graphql/wp-graphql/pull/571#issuecomment-1194625620

I think it's worth exploring supporting Theme Mods in the Schema, but I definitely think it needs to be approached using the Customizer Registry as the source of truth for how Theme Mods are mapped to the WPGraphQL Schema.

**Comment by justlevine** [comment]
My understanding is the customizer API is about adding live previews, but the [options themselves](https://developer.wordpress.org/reference/classes/wp_customize_setting/__construct/) are part of either the Settings API or the Theme Mods API, and I'm not sure we can use it to deduce the types differently than those apis. (Also, the Customizer was never really adopted universally, and is further spiraling with Gutenberg and FSE apis)

I guess we could check the type of value returned and match that to a scalar fairly generically, but there might be outliers to that approach.

**Comment by jasonbahl** [comment]
Ya, perhaps @kidunot89 was onto something by registering specific fields. Folks that need Customizer settings exposed could do this already for their projects using `register_graphql_field`, etc. 

I'd like to have some auto-generation layer, but Customizer definitely wasn't built to be used in non admin contexts, which makes it tough to play nice with the WPGraphQL Schema which is not generated in the context of `is_admin()`
