### ISSUE TITLE
Subcategories aren't resolved by DataSource::resolve_term_objects_connection()

### ISSUE THREAD

**Issue by kidunot89** [wp-graphql/wp-graphql#518]
Only top level terms are resolved by `TermObjectConnection`. You can retrieve them from the Parent Terms `children` field but if you set a post to a sub-category it isn't seen by the `PostObjectType`.

**Comment by jasonbahl** [comment]
AFK, but there’s an argument on that field you can use to output in a flat list, and another to include children. 

If you look in GraphiQL you should be able to find the args. I can help tomorrow if you can’t figure it out.

**Comment by jasonbahl** [comment]
Check my notes here: https://github.com/wp-graphql/wp-graphql/issues/381

**Comment by kidunot89** [comment]
isSelected is not showing up in graphiQL as an argument or a field. I'll go back over it later.

**Comment by jasonbahl** [comment]
Check the latest comment with an example

https://github.com/wp-graphql/wp-graphql/issues/381#issuecomment-363920009

**Comment by jasonbahl** [comment]
Or check the notes on the PR

https://github.com/wp-graphql/wp-graphql/pull/387

**Comment by kidunot89** [comment]
Got it.
```
{
  posts{
    nodes{
      id
      isGutenPost
      selectedCategories: categories(where: {shouldOutputInFlatList: true}) {
        nodes {
          name
        }
      }
    }
  }
}
```

**Comment by jasonbahl** [comment]
@kidunot89 I'm closing this as it appears like it was resolved based on that last note. We can re-open if it's still an issue though.
