### ISSUE TITLE
Menu item connection gets childItems only for the first menu

### ISSUE THREAD

**Issue by ElisaMassafra** [wp-graphql/wp-graphql#520]
If a menu item has child items, the connection resolves them only for the first menu but for the follwing menus the childItems nodes are always empty

**Comment by izzygld** [comment]
@elisaMassafra I think it’s the same issue as issue #505.
 (https://github.com/wp-graphql/wp-graphql/issues/505)

**Comment by jasonbahl** [comment]
closed by #524
