### ISSUE TITLE
Add support for WP_MULTISITE in Dockerized tests

### ISSUE THREAD

**Issue by mngi-arogers** [wp-graphql/wp-graphql#527]
At one point, tests ran multisite configurations when the environment variable, `WP_MULTISITE=1`, was set: https://github.com/wp-graphql/wp-graphql/pull/191#issuecomment-326720630

Since the introduction of Docker to run the tests, the tests don't run multisite configurations anymore, but they should. For example, this should run the functional tests in a multisite configuration (this example is based on v0.1.0 code that is yet to be released)
```
sudo env WP_MULTISITE=1 ./run-docker-tests.sh functional
```

**Comment by jasonbahl** [comment]
This was recently fixed: https://github.com/wp-graphql/wp-graphql/pull/2375
