### ISSUE TITLE
generalSettings.startOfWeek throwing an error

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#528]
The following query: 

```
query {             
    generalSettings {
        dateFormat
        description
        language
        startOfWeek
        timeFormat
        timezone
        title
    }
}
```

Returns an error: 

```
{
      "debugMessage": "Int cannot represent non 32-bit signed integer value: (empty string)",
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 6,
          "column": 5
        }
      ],
      "path": [
        "generalSettings",
        "startOfWeek"
      ]
    }
  ]
```

**Comment by adioe3** [comment]
I'd like to take care of this, will prep a PR this week.

**Comment by jasonbahl** [comment]
@adioe3 thanks! let me know if you need to discuss anything while you're working on it.

**Comment by zilehuda** [comment]
is this open ?

**Comment by jasonbahl** [comment]
@zilehuda Yes. There have not been any pull requests to address this yet.

**Comment by tryvin** [comment]
@jasonbahl Steps to reproduce this? The tests units say it's all ok, no issues with the generalSettings > startOfWeek

**Comment by davidatwhiletrue** [comment]
Hello, I'm able to reproduce this if you set in your WordPress settings Sunday as first day of week. For others, like Monday, it is working fine.

Choosing Sunday leads to option `start_of_week` get value `0`. 

In SettingType.php Ln136, value `0` is substituted with empty string.

I'm preparing a PR to solve this.

**Comment by jasonbahl** [comment]
Thanks @davidatwhiletrue!
