### ISSUE TITLE
Query'ing a number of posts in a category falsely returns hasNextPage: true if number of posts queried is equal to total number of posts in category

### ISSUE THREAD

**Issue by tokewf** [wp-graphql/wp-graphql#533]
## Bug

I have a WP installation with some categories, each category containing a number of posts. A category with an ID of `Y2F0ZWdvcnk6Mw==` (GraphQL ID, not WP post ID) contains 4 posts.

If I query said category for posts via this query (simplified):
```
{
  category(id:"Y2F0ZWdvcnk6Mw==") {
    posts(first:4) {
      pageInfo {
        hasNextPage
      }
      nodes {
        postId
      }
    }
  }
}
```
—where the value for `first` happens to equal the total number of posts in the category, I get:
```
{
  "data": {
    "category": {
      "posts": {
        "pageInfo": {
          "hasNextPage": true
        },
        "nodes": [
          {
            "postId": 238
          },
          {
            "postId": 236
          },
          {
            "postId": 201
          },
          {
            "postId": 6
          }
        ]
      }
    }
  }
}
```
(Tested in ChromeiQL). Even though there are no more posts in the category, the response contains `"hasNextPage": true`.

## Solution

This bug can be fixed by changing `src/Type/PostObject/Connection/PostObjectConnectionResolver.php` from:
```
$has_previous_page = ( ! empty( $args['last'] ) && ( $info['total_items'] >= self::get_query_amount( $source, $args, $context, $info ) ) ) ? true : false;
$has_next_page     = ( ! empty( $args['first'] ) && ( $info['total_items'] >= self::get_query_amount( $source, $args, $context, $info ) ) ) ? true : false;
```
to:
```
$has_previous_page = ( ! empty( $args['last'] ) && ( $info['total_items'] > self::get_query_amount( $source, $args, $context, $info ) ) ) ? true : false;
$has_next_page     = ( ! empty( $args['first'] ) && ( $info['total_items'] > self::get_query_amount( $source, $args, $context, $info ) ) ) ? true : false;
```
(greater than instead of greater than or equal).

Curiously, this is already implemented for `src/Type/Comment/Connection/CommentConnectionResolver.php` and `src/Type/TermObject/Connection/TermObjectConnectionResolver.php`, but not for post objects.

I would state the version of the plugin I am using, but I don't know how to find that information :flushed:

**Comment by jasonbahl** [comment]
resolved by #537
