### ISSUE TITLE
Implement DataLoader

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#55]
We should implement DataLoader to take advantage of the batching/caching functionality as it should boost performance significantly.

https://github.com/overblog/dataloader-php

**Comment by jasonbahl** [comment]
Could be helpful for Post commections Coming from a term object. http://scribu.net/wordpress/sortable-taxonomy-columns.html

**Comment by CodeProKid** [comment]
fwiw, we talked about this yesterday, and I think there may be more performance gains from doing something like hashing query arguments, and using that as a "key", and then storing the results of the query as a "value". Could either cache it just in the session, or in the object cache with `wp_cache_set()`.

**Comment by jasonbahl** [comment]
Initial implementation of Deferred resolvers was implemented in #291 

We should probably open up new issues to address DataLoading for each of the Types / Connections.
