### ISSUE TITLE
APIGen deploys are causing Travis to fail

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#569]
Currently we send APIGen docs to another repo when there are PRs to master. 

This is currently failing. 

We should either fix it or remove this.

**Comment by CodeProKid** [comment]
We decided that we would remove this from the build process. @jasonbahl doesn't think it adds much value, and we can add it back in the future if we miss it.

**Comment by CodeProKid** [comment]
We also may want to just kill this repo as a part of this -> https://github.com/wp-graphql/wp-graphql-api-docs
