### ISSUE TITLE
Feature Request: Orderby Rand

### ISSUE THREAD

**Issue by jkhaui** [wp-graphql/wp-graphql#577]
Hey,

Can we add the 'orderby: RAND' parameter to the core PostObjectsConnectionsOrderByEnum type? Right now i've very easily achieved this by appending the following to the graphql_enum_type array:

        'RAND' => [
			'value'       => 'rand',
			'description' => __( 'Order randomly', 'wp-graphql' ),
		],

And here's an example query that appears to successfully return a list of posts in random order:

query {
  posts(where: {orderby: {field: RAND}}) {
    nodes {
      title
      content
    }
  }
}

Just wondering if there's any reason why RAND isn't already included in the plugin, cheers

**Comment by jasonbahl** [comment]
Hey, orderby rand can cause performance issues so we’ve left it out intentionally. 

Of course the ability to filter in support will remain for those that want to expose it in their API

**Comment by jasonbahl** [comment]
You can use this filter to add it: https://github.com/wp-graphql/wp-graphql/blob/develop/src/Type/WPEnumType.php#L66

**Comment by siddhantdante** [comment]
pagination does not work as expected in orderby => 'rand'.It does not page all posts stops early.

**Comment by jasonbahl** [comment]
@siddhantdante paginating with random order in general doesn't work well because there is no order, it's random. There needs to be proper order for server pagination to work. 

I'd suggest handling random ordered queries on the client by randomizing the query arguments and asking to exclude previously returned IDs. 

Something like:

**First Query**

This queries for 3 posts with no arguments specified. 

```graphql
query GetRandomPosts($where: RootQueryToPostConnectionWhereArgs!) {
  posts(first: 3 where: $where) {
     nodes {
       id
       databaseId
       title
    }
  }
}
```

```json
$args = {
  "where": {
    "notIn": null,
    "orderby": null
  }
}
```

![Screen Shot 2020-09-15 at 7 18 02 AM](https://user-images.githubusercontent.com/1260765/93215408-9a212180-f723-11ea-82f6-ab7bac98b1dd.png)

**Second Query**

Once the data is returned from the first query, you could store the `databaseIds` in an array and use those values in the `notIn` argument for the next query. You could also randomize the values that would be used for the `orderby` argument: 

```json
{
  "where": {
    "notIn": [541,531,506],
    "orderby": null
  }
}
```

![Screen Shot 2020-09-15 at 7 19 09 AM](https://user-images.githubusercontent.com/1260765/93215515-c177ee80-f723-11ea-8fc1-7653ed68ff3f.png)

You could also start randomizing the orderby args on the client as well. Like: 

```json
```json
{
  "where": {
    "notIn": [541,531,506],
    "orderby": [
      {
        "field": "TITLE",
        "order": "ASC"
      }
    ]
  }
}
```

or

```json
{
  "where": {
    "notIn": [541,531,506],
    "orderby": [
      {
        "field": "MENU_ORDER",
        "order": "DESC"
      }
    ]
  }
}
```

etc.

**Third Query, and beyond**

Keep adding already queried IDs to the `notIn` argument and keep changing up the orderby arguments. This will allow you to have random results and paginate through them. 

```json
{
  "where": {
    "notIn": [541,531,506,321,271,263],
    "orderby": [
      {
        "field": "MENU_ORDER",
        "order": "DESC"
      }
    ]
  }
}
```

![Screen Shot 2020-09-15 at 7 22 49 AM](https://user-images.githubusercontent.com/1260765/93215906-45ca7180-f724-11ea-82e4-93d02975fe7b.png)

This will allow you to get random posts over and over.

**Comment by siddhantdante** [comment]
> @siddhantdante paginating with random order in general doesn't work well because there is no order, it's random. There needs to be proper order for server pagination to work.
> 
> I'd suggest handling random ordered queries on the client by randomizing the query arguments and asking to exclude previously returned IDs.
> 
> Something like:
> 
> **First Query**
> 
> This queries for 3 posts with no arguments specified.
> 
> ```graphql
> query GetRandomPosts($where: RootQueryToPostConnectionWhereArgs!) {
>   posts(first: 3 where: $where) {
>      nodes {
>        id
>        databaseId
>        title
>     }
>   }
> }
> ```
> 
> ```json
> $args = {
>   "where": {
>     "notIn": null,
>     "orderby": null
>   }
> }
> ```
> 
> ![Screen Shot 2020-09-15 at 7 18 02 AM](https://user-images.githubusercontent.com/1260765/93215408-9a212180-f723-11ea-82f6-ab7bac98b1dd.png)
> 
> **Second Query**
> 
> Once the data is returned from the first query, you could store the `databaseIds` in an array and use those values in the `notIn` argument for the next query. You could also randomize the values that would be used for the `orderby` argument:
> 
> ```json
> {
>   "where": {
>     "notIn": [541,531,506],
>     "orderby": null
>   }
> }
> ```
> 
> ![Screen Shot 2020-09-15 at 7 19 09 AM](https://user-images.githubusercontent.com/1260765/93215515-c177ee80-f723-11ea-8fc1-7653ed68ff3f.png)
> 
> You could also start randomizing the orderby args on the client as well. Like:
> 
> ```json
> ```json
> {
>   "where": {
>     "notIn": [541,531,506],
>     "orderby": [
>       {
>         "field": "TITLE",
>         "order": "ASC"
>       }
>     ]
>   }
> }
> ```
> 
> or
> 
> ```json
> {
>   "where": {
>     "notIn": [541,531,506],
>     "orderby": [
>       {
>         "field": "MENU_ORDER",
>         "order": "DESC"
>       }
>     ]
>   }
> }
> ```
> 
> etc.
> 
> **Third Query, and beyond**
> 
> Keep adding already queried IDs to the `notIn` argument and keep changing up the orderby arguments. This will allow you to have random results and paginate through them.
> 
> ```json
> {
>   "where": {
>     "notIn": [541,531,506,321,271,263],
>     "orderby": [
>       {
>         "field": "MENU_ORDER",
>         "order": "DESC"
>       }
>     ]
>   }
> }
> ```
> 
> ![Screen Shot 2020-09-15 at 7 22 49 AM](https://user-images.githubusercontent.com/1260765/93215906-45ca7180-f724-11ea-82e4-93d02975fe7b.png)

thanks did not think of this.

**Comment by siddhantdante** [comment]
@jasonbahl thanks did not think of this

**Comment by erikdemarco** [comment]
> You can use this filter to add it: https://github.com/wp-graphql/wp-graphql/blob/develop/src/Type/WPEnumType.php#L66

can you reinclude the link? because the line is not same anymore

**Comment by dazza-dev** [comment]
I had the same need, so I created a small plugin that adds RAND to the PostObjectsConnectionOrderbyEnum using the graphql_{EnumTypeName}_values filter mentioned above.

In case it helps anyone: [wpgraphql-random-orderby](https://github.com/dazza-dev/wpgraphql-random-orderby)
