### ISSUE TITLE
WPInputObjectType::construct doesn't call prepare_fields

### ISSUE THREAD

**Issue by galaxiecruzin** [wp-graphql/wp-graphql#578]
I'm not sure if there is a new way to register input fields with the type registry implementation, so I'm testing registering an input type "lang" to filter posts by language. The following snippet worked prior to 0.1.0. To reproduce add this snippet as a plugin

```
add_filter( 'graphql_input_fields', function( $fields ) {
	$fields['lang'] = [
		'type' => \WPGraphQL\Types::string(),
		'description' => 'Select posts by Polylang language',
	];
	$fields['allLanguages'] = [
		'type' => \WPGraphQL\Types::boolean(),
		'description' => 'Show posts regardless of the Polylang language',
	];
	return $fields;
} );
```

Then run a query like
```
query Posts($lang: String) {
  posts(where: {lang: $lang}) {
    edges {
      node {
        title
      }
    }
  }
}
---
{
  "lang": "en"
}
```
See https://gist.github.com/epeli/87909f92b19a216dc7f5b2b6c204ad31

While digging into this I found in ./src/Type/WpInputObjectType.php

$config['fields'] was an array prior to 0.1.0 so this if condition prevents prepare_fields() from being called.

```
	public function __construct( $config = [] ) {
		if ( ! empty( $config['fields'] ) && is_array( $config['fields'] ) ) {
			$config['fields'] = self::prepare_fields( $config['fields'], $config['name'], $config );
		}
		parent::__construct( $config );
	}
...
```

A print_r of $config['fields'] here gives me

```
Closure Object
(
    [static] => Array
        (
            [config] => Array
                (
                    [description] => Input for the updateSettings mutation
                    [fields] => Array
...
...
```

I haven't yet been able to figure out what this _should_ be accepting... but figured I'd post this to start a thread... If someone can point me in the direction of what this should be expecting... I can take a crack at trying to update.

**Comment by jasonbahl** [comment]
@galaxiecruzin hey, thanks for reporting!

ya, there's a new API for registering Types and Fields. It's fairly backward compatible, but there definitely are some breaking changes.

Here's the recommended way to add fields now (sorry, [the docs](https://www.wpgraphql.com/docs/api-reference/) are still incomplete and have been slow to get together):

```
// hook in here to make sure it's a GraphQL request and the GraphQL registry is available
add_action( 'graphql_register_types', function() {

   // first $arg is the Type you want to add the fields to, second arg is an array of fields
   register_graphql_fields( 'RootQueryToPostConnectionWhereArgs', [
     'lang' => [
        'type' => 'String',
        'description' => 'Select posts by Polylang language',
     ],
     'allLanguages' => [
         'type' => 'Boolean',
         'description' => 'Show posts regardless of the Polylang language',
      ],
   ] );
} );
```

I'll see if there's another issue to address re: `prepare_fields()` though

**Comment by jasonbahl** [comment]
@galaxiecruzin hey! This has been resolved and is getting released today. The `graphql_input_fields` filter is now restored.

**Comment by galaxiecruzin** [comment]
Woot! thanks
