### ISSUE TITLE
visiting /graphql yields ERR_EMPTY_RESPONSE with fresh install on new wordpress

### ISSUE THREAD

**Issue by andrewhl** [wp-graphql/wp-graphql#592]
Had this working a few days ago. Then it stopped working suddenly. I made no change, except to update Gutenberg to version 4.5.1. I'm running Wordpress 4.9.8 with the default theme, and only a single post written using Gutenberg.

Using wp-graphql version 0.1.2.

And I'm using the `Post name` permalinks format (not the default): 

`http://test.mysite.org/sample-post/`

I get the following error when I visit `http://test.mysite.org/graphql`:

This page isn’t working
test.mysite.org didn’t send any data.
ERR_EMPTY_RESPONSE

I've tried deleting the package and reinstalling it, but that didn't work. I've tried flushing permalinks, but no luck. I had this working successfully a few days ago so I'm baffled at what happened. Any help would be appreciated.

**Comment by jasonbahl** [comment]
@andrewhl can you try without Gutenberg? Gutenberg is known for breaking a lot of things. . .wouldn't surprise me a bit if it were the culprit here as well

**Comment by jasonbahl** [comment]
@andrewhl do you have `WP_DEBUG` or `WP_DEBUG_DISPLAY` set to true? If so, maybe turn those off and try again as well?

**Comment by andrewhl** [comment]
@jasonbahl I just completely deleted Gutenberg and any posts I created with it. I changed my permalinks settings as well just to make sure it wasn't that. No change. I'll take a look in the debug settings, but I didn't do anything to turn those on so I'm not sure why that would be the case. This is a vanilla wordpress installation.

**Comment by jasonbahl** [comment]
`ERR_EMPTY_RESPONSE` almost seems like WordPress isn't loading _at all_ 🤔 

Are normal pages working fine still?

**Comment by andrewhl** [comment]
@jasonbahl I've set `WP_DEBUG` and `WP_DEBUG_DISPLAY` to false in wp-config.php. No change. I actually uninstalled wordpress and reinstalled it via cpanel on my hosting provider. This is literally a brand new install, and I still get the error. Very strange, no?

**Comment by andrewhl** [comment]
Yes, normal pages are loading fine.

**Comment by jasonbahl** [comment]
@andrewhl it is strange. 🤔

**Comment by jasonbahl** [comment]
@andrewhl is the site a multisite?

**Comment by andrewhl** [comment]
@jasonbahl Tech support solved it. They had to disable the Apache module mod_sec [what-is-modsecurity-and-why-is-it-important](https://www.inmotionhosting.com/support/website/modsecurity/what-is-modsecurity-and-why-is-it-important). I'm not sure what relationship this has to wp-graphql or the graphql endpoint, but it's all working now. Thanks for taking the time to look into this on your end!

**Comment by jasonbahl** [comment]
@andrewhl interesting issue. Glad you got it resolved!
