### ISSUE TITLE
Unit Tests for CommentsConnectionQueryArgsType

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#61]
The CommentConnections are not yet fully tested. We need to flesh out test coverage to ensure the CommentConnections are working as expected.

You can see coverage here: https://coveralls.io/github/wp-graphql/wp-graphql?branch=master

Basically, we need to test the various connection queries that can be made and ensure things are working as expected to get the CommentConnection* files up to 100% coverage.

**Comment by BE-Webdesign** [comment]
Working on this.

**Comment by tonimain** [comment]
Found a bug while writing this tests WIP.
The function orderBy is causing an error where the query returns:
```
SyntaxError: Unexpected token < in JSON at position 0
```

This is the query:
```
query {
  comments(where: {orderby: COMMENT_DATE}) {
    edges {
      node {
				approved
        id
        author {
         email
          url
        }
        commentId
        content
        type
        
      }
    }
  }
}
```
