### ISSUE TITLE
Protect WP_User->user_pass from leaking

### ISSUE THREAD

**Issue by chriszarate** [wp-graphql/wp-graphql#618]
Since type resolvers return the primitive WordPress object (e.g., `WP_User`), it opens up the possibility that a user's `user_pass` field could be indirectly exposed by WPGraphQL.

To be clear, that's not possible with WPGraphQL out-of-the-box, but a malicious plugin or theme could use `register_graphql_field` to add a field resolver to the `User` type and expose the user's hashed password.

Ideally we would delete or hide private fields like `user_pass` before passing them to field resolvers.

**Comment by CodeProKid** [comment]
This should be handled in #604 adding to the milestone so we make sure it's handled. 👍

**Comment by jasonbahl** [comment]
closed by #683
