### ISSUE TITLE
`dateGmt` for comments doesn't contains "T" (ISO)

### ISSUE THREAD

**Issue by MoOx** [wp-graphql/wp-graphql#620]
It would be nice to have consistent date format

<img width="1043" alt="screenshot 2018-12-14 at 15 43 05" src="https://user-images.githubusercontent.com/157534/50009495-6eee2900-ffb7-11e8-9542-d9bb27d65228.png">

It seems the behaviour modified for post is not applied for comments

https://github.com/wp-graphql/wp-graphql/blob/a663393cfb25544a30b1b99400079b63c6aaf753/tests/wpunit/PostObjectQueriesTest.php#L209

vs

https://github.com/wp-graphql/wp-graphql/blob/fde0424e0c352908170e31d421c96859d2f8d1d5/tests/wpunit/CommentObjectQueriesTest.php#L141

**Comment by jasonbahl** [comment]
closed by #821
