### ISSUE TITLE
Run tests against PHP 7.3

### ISSUE THREAD

**Issue by CodeProKid** [wp-graphql/wp-graphql#624]
We need to add support for running the tests on Travis through PHP 7.3 now that it is officially released.

**Comment by jasonbahl** [comment]
@CodeProKid let's punt this as we need to wait for the Docker image to be available...

**Comment by jasonbahl** [comment]
@CodeProKid I moved this out of 0.1.4 milestone

**Comment by mngi-arogers** [comment]
Forgot this issue was open.

Something to keep in mind: As of this writing, PHP 7.3 requires `xdebug-2.7.0beta1` instead of `xdebug-2.6.x`, which PHP 7.1 and 7.2 require. https://bugs.xdebug.org/view.php?id=1584

**Comment by jasonbahl** [comment]
@mngi-arogers all I have to say in response:

https://twitter.com/rkoutnik/status/1085633512839888896

**Comment by jasonbahl** [comment]
closed by #703
