### ISSUE TITLE
Add WordPress (VIP) CodeSniffs to test suite / CI

### ISSUE THREAD

**Issue by chriszarate** [wp-graphql/wp-graphql#627]
Implementing WordPress (and possibly VIP) code sniffs could provide a few benefits:

1. Enforced internal consistency by incorporating sniffs in test suite.
2. Familiarity / comfort for the many organizations that have adopted these sniffs.
3. Aligning with WP Core in code style
4. In the case of VIP sniffs, possibly introducing performance benefits for VIP customers (since many of their sniffs are oriented around performance considerations).

There are cons, of course:

1. Alienating developers that are unfamiliar with these standards or frustrated by the hurdles they impose.
2. Arguing about which additional sniffs to include / having to adopt new sniffs as they are added by WP.

If we agree on a set, it should be fairly straightforward to add to the test suite.

**Comment by jasonbahl** [comment]
@renatonascalves Hey, do you have an interest in reviving this effort?

I think we should get something implemented here 😄

**Comment by renatonascalves** [comment]
@jasonbahl Yes! I'll put something together for consideration. :)

**Comment by jasonbahl** [comment]
@renatonascalves Awesome! Looking forward to it. 😄

**Comment by jasonbahl** [comment]
Closed by #731
