### ISSUE TITLE
Cannot query field

### ISSUE THREAD

**Issue by kevindavis338** [wp-graphql/wp-graphql#630]
Hi there,

For some reason when I run the following query:
graphql?query={TableName{{id,title}}

I'm getting the following error: {"errors":[{"message":"Cannot query field \"TableName\" on type \"RootQuery\".","category":"graphql","locations":[{"line":1,"column":2}]}]}

Why am I getting the error? Could it be a bug or something that I could be missing?

Thank you,
Kevin Davis

**Comment by jasonbahl** [comment]
@kevindavis338 do you have a field `TableName` in your Schema? The error suggests that that doesn't exist in your Schema, so you would need to register that field first. 

Can you elaborate on what you're trying to accomplish?

**Comment by kevindavis338** [comment]
No.. In fact it should be the SchemaName (Sorry I'm still new to GraphQL),  so in reality, I'm calling the schema name with the following fields, id and title. 
What I'm trying to do is test to make sure I get the right information and put the query in the widget so I can display the title, while I'm checking the id of the title.

**Comment by jasonbahl** [comment]
by default, the WPGraphQL Schema exposes entry points for many of the core data types that WordPress uses, such as Post Types, Taxonomies, Comments, etc. 

So you can query something like: 

```
{
  posts { 
     edges {
        node {
            id
            title
         }
     }
  }
}
```

and in response you would get a list of "post" nodes with their ID and Title. 

if you want to query custom data, like data from a Custom Database Table or something, you would need to register Types and Fields to the Schema to expose that data, and you'd need to write resolvers to resolve said data. 

To get familiar with what's available in the Schema, I would recommend using the [wp-graphiql plugin](https://github.com/wp-graphql/wp-graphiql) to explore the Schema and play around with queries.

**Comment by kevindavis338** [comment]
Thank you..

**Comment by jasonbahl** [comment]
@kevindavis338 I'm going to close this issue, but if you have more general questions, feel free to reach out in [Slack](https://wpgql-slack.herokuapp.com/) or [Spectrum](https://spectrum.chat/wpgraphql).
