### ISSUE TITLE
Add filter to allow users to customise typeBy query args

### ISSUE THREAD

**Issue by hsimah** [wp-graphql/wp-graphql#638]
### When you open an _issue_ for a feature request, please add as much detail as possible:
- [ ] A descriptive title
- [ ] A description of the problem you're trying to solve, including *why* you think this is a problem
- [ ] An overview of the suggested solution
- [ ] If the feature changes current behavior, reasons why your solution is better

I have a need to query a type by custom fields (not just ID, object ID, slug, uri). I want to extend the `typeBy` query instead of rolling my own.

I will need to add fields to `$post_by_args` and a custom resolver to `RootQuery`.

I suggest adding two filters, one for args and one for custom resolution.

**Comment by hsimah** [comment]
To use:

```
    add_filter( 'graphql_userTutorialBy_args', function ( $post_by_args, $post_type_object ) {
        $post_by_args['tutorialId'] = [
            'type'        => 'Int',
            'description' => __( 'Gets the UserTutorial by linked Tutorial ID', 'wp-graphql' ),
        ];

        return $post_by_args;
    }, 10, 2 );
```

```
    add_filter( 'graphql_userTutorialBy_resolve', function( $post_type_object, $source, array $args, $context, $info ) {
        if ( ! empty( $args['tutorialId'] ) ) {
            global $wpdb;
            $user_id = get_current_user_id();

            $user_tutorial = null; // do your magic here - I use $wpdb to read a custom table

            if ( $user_tutorial && $user_tutorial->ID ) {
                return DataSource::resolve_post_object( $user_tutorial->ID, 'UserTutorial' );
            }
        }

        return null;
    }, 10, 5 );
```

**Comment by jasonbahl** [comment]
@hsimah I'm closing this. Referencing my comment on the PR for context: https://github.com/wp-graphql/wp-graphql/pull/639#issuecomment-451993929
