### ISSUE TITLE
Cursor pagination returns some duplicate data.

### ISSUE THREAD

**Issue by kentywang** [wp-graphql/wp-graphql#641]
I noticed that cursor pagination was behaving strangely.

For instance, when I want to fetch my first four posts, I run a query like this:
```
posts(first: 4) {
 edges {
    node {
      title
    }
  }
  pageInfo {
    endCursor
    hasNextPage
  }
}
 ```
And this returns my `post_1`, `post_2`, `post_3`, and `post_4`, as expected.

But when I want to fetch the next four posts, I run the same query but with the argument `after` set to the cursor on `post_4`:
```
posts(first: 4, after: $cursor_on_post_4) {
 edges {
    node {
      title
    }
  }
  pageInfo {
    endCursor
    hasNextPage
  }
}
 ```
I expect to get `post_5`, `post_6`, `post_7`, and `post_8`. Instead, the returned posts are `post_1`, `post_2`, and `post_3`.

The problem seems to stem from the static method `get_query_args` in `PostObjectConnectionResolver.php` that sets `$query_args['graphql_cursor_compare']` to `>` when a `last` argument in the query is present, and `<` otherwise. (Code [here](https://github.com/wp-graphql/wp-graphql/blob/develop/src/Data/PostObjectConnectionResolver.php#L91).)

This causes the `WHERE` clause of the output query to filter on the condition being of less than or equal to the cursor posts's post date, which returns the posts _before_ the cursor post, instead of what I want, which are the posts _after_ the cursor post. (Code [here](https://github.com/wp-graphql/wp-graphql/blob/develop/src/Data/Config.php#L95).)

I believe that by reversing the ternary statement in `get_query_args`, setting `$query_args['graphql_cursor_compare']` to `<` when a `last` argument is present, and `>` otherwise, the issue can be fixed.

**Comment by jasonbahl** [comment]
@kentywang any chance the posts have the same date? Like we’re they created via CLI or something?

**Comment by kentywang** [comment]
@jasonbahl Not for this case, no. I created the posts individually and they have different timestamps.

**Comment by jasonbahl** [comment]
@kentywang do you have any other plugins active that might be filtering the WP_Query?

I can run these queries and pagination doesn't appear to be an issue. 

See the attached GIF showing a vanilla WP install with content from `wptest.io` and the only plugins active are `WPGraphQL` and `WPGraphiQL`

I can query 5 posts and paginate using the `endCursor` and I get the next 5 posts. 

![wp-graphql-pagination](https://user-images.githubusercontent.com/1260765/50859470-acdd3380-1350-11e9-97f5-76acde1c047b.gif)

I would suggest checking out WPGraphQL Insights (https://github.com/wp-graphql/wp-graphql-insights) combined with Query Monitor (https://wordpress.org/plugins/query-monitor/)

Having these plugins active will give insight into the underlying queries that are executing during the GraphQL request. 

Here's a screenshot of the query above with those plugins active. 

I can see the raw WP_Query that was executed to get the list of posts. 

![wp-graphql-insights](https://user-images.githubusercontent.com/1260765/50859778-8370d780-1351-11e9-8bc5-c3a3a9e6882c.png)

In this case the raw query was: 

```
SELECT   wp_posts.ID FROM wp_posts  WHERE 1=1  AND wp_posts.post_parent = 0  AND wp_posts.post_type = 'post' AND ((wp_posts.post_status = 'publish')) AND wp_posts.post_date <= '2013-03-15 14:48:32' AND wp_posts.ID != 1000  ORDER BY wp_posts.post_date DESC LIMIT 0, 6
```

The cursor passed included an ID of the last post from the previous query, in this particular case, the ID was `1000`, so we ask for the next set of posts after that post, and not including that post.

We asked for 5 posts (via the `first: 5` arg in the query), so WPGraphQL asks for 1 more to see if the `pageInfo` should return `hasNextPage: true` or not. 

If you're able to use WPGraphQL Insights and Query Monitor to figure out how the raw WP_Query is being modified in your particular setup, you may be able to figure out what plugin/theme code is altering the behavior and compensate for those changes.

**Comment by jasonbahl** [comment]
@kentywang I'm going to close this, but happy to re-open if you do find the current cursor implementation is indeed problematic.
