### ISSUE TITLE
Can't find acf in the query - couldn't find an answer

### ISSUE THREAD

**Issue by bovas85** [wp-graphql/wp-graphql#658]
I couldn't figure out from previous issues a way to enable this. 

My WPGraphQL is latest on a Wordpress v4.9.9

You can visit it here https://api.nunziellasalluce.com/graphql

I can see no acf fields accessible nor I can get custom post types (in my case they are called case_studies

Is anyone able to assist?

**Comment by jasonbahl** [comment]
@bovas85 I'll need more info to help here. 

Did you have your ACF fields working before and they stopped working, or are you trying to access ACF Fields from WPGraphQL for the first time?

**Comment by bovas85** [comment]
I'm trying to access them for the first time using GraphQL. They work fine using regular rest api.

My plugins are acf to resti api and acf standard latest.

**Comment by jasonbahl** [comment]
@bovas85 have you gone through the steps listed here: https://www.wpgraphql.com/docs/getting-started/custom-post-types-taxonomies/

That outlines how to get your Custom Post Types and Taxonomies exposed to WPGraphQL

As far as custom fields go, there's no official plugin for exposing ACF to GraphQL (yet). I'm working on it, but not sure when I'll have it ready. 

In the mean-time you can read about how to expose custom fields for your specific needs here: https://www.wpgraphql.com/docs/getting-started/custom-fields-meta/

**Comment by bovas85** [comment]
Regarding the advanced custom fields, is there any hacky way to expose them even without a plugin?

**Comment by jasonbahl** [comment]
@bovas85 did you see the link in the previous comment for adding custom fields and meta?

https://www.wpgraphql.com/docs/getting-started/custom-fields-meta/

**Comment by aakash19090** [comment]
Hi @jasonbahl , i am unable to see the ACF fields in WPgraphQL Schema editor. I went through your video exactly https://www.youtube.com/watch?v=rIg4MHc8elg . Have all the need plugins. 

Note : I have created ACF fields for the "Page" not "Post" i.e. for my Front Page. Also selected that option "Show in GraphQL". But when i go in to that editor, don't know under which field the ACF fields would appear. Also i searched in the Documentation Explorer typing that fieldname, but its not producing results. Please guide out !

**Comment by andrewclo** [comment]
I am running into the same issue as @aakash19090. I have the ACF field added to "Page" and unable to see the fields when looking through the GraphQL explorer. I appreciate any insight.

**Comment by donpernino** [comment]
Hey, I am running to the same issue as @aakash19090  & @andrewclo ; Any updates on this? I just followed the youtube video.

**Comment by SuperMnr** [comment]
The plugin "WPGraphQL for Advanced Custom Fields" works fine for me. Hope this help

**Comment by FatmaMahmoud698** [comment]
I have the same problem here I have exist advanced custom fields then I install all mentioned plugins and follow all steps but still custom fields not appear on graphql
