### ISSUE TITLE
Allow pages queries to return flat results instead of parent-child nested results.

### ISSUE THREAD

**Issue by craigmcnamara** [wp-graphql/wp-graphql#673]
Per the discussion here: https://wp-graphql.slack.com/archives/C3NM1M291/p1548707624179300

I'm trying to use wp-graphql to implement a sitemap and page queries default to top level pages causing me to have to traverse page relationships to get the info required to make a list of pages within a sitemap.

I'd expect an option to allow a flat result set, ex:

```graphql
query {
  pages(where: { status: PUBLISH }, onlyTopLevelPages: false ) {
    nodes {
      id
      uri
      slug
      status
      modifiedGmt
    }
  }
}
```

I'm going to start working up a pull request for this, so any feedback on making the above example work would be appreciated.

I'm just getting acquainted with wp-graphql, most of my GraphQL implementation experience is within Ruby on Rails but I know my way around WP and PHP, so please excuse me if I ask some basic questions.

**Comment by craigmcnamara** [comment]
Turns out you can get this effect by passing null to the parent where arg.

```graphql
query {
  pages(where: { status: PUBLISH, parent: null }, first: 10000 ) {
    edges {
      node {
        id
        uri
        termSlugs
        status
	modifiedGmt
      }
    }
  }
}
```

**Comment by CodeProKid** [comment]
This seems like a hacky workaround. I feel like we should formalize this with some official arg.
