### ISSUE TITLE
Write tests for new model layer

### ISSUE THREAD

**Issue by CodeProKid** [wp-graphql/wp-graphql#685]
Need to write a few tests for the new Model abstraction. Things I'd like to test:
- Filters & hooks fire as expected, and the correct context is passed through
- Getting & setting data to the fields array works correctly
- Fields get wrapped with callback correctly
- Visibility gets added as expected

**Comment by jasonbahl** [comment]
@CodeProKid is this still outstanding or do you feel like it has enough coverage currently and we just forgot to close this?

**Comment by CodeProKid** [comment]
@jasonbahl There are still some tests that I think need to get written, especially surrounding hooks/filters.

**Comment by CodeProKid** [comment]
A lot of the tests for the model layer are really all over the place right now. It would be good to centralize them in one place.

I think this work probably needs to start with a logic map for how the model layer should be working, as in what data it should restrict in which situations, then we can develop test cases from that.

**Comment by jasonbahl** [comment]
@CodeProKid maybe during bugscrub tomorrow we could work on documenting the model layer in some sort of logic map? Would be good to get in the docs, and could inform things like organizing tests, as you stated

**Comment by CodeProKid** [comment]
@jasonbahl surely! That sounds great 😄
