### ISSUE TITLE
Every post object endpoint can resolve posts in any post type

### ISSUE THREAD

**Issue by chriszarate** [wp-graphql/wp-graphql#689]
In WPGraphQL latest (though I believe this has been the case for a long time), you can successfully query for a post in any post type using any post type endpoint.

```
query {
	post(id: "GLOBAL_RELAY_ID_OF_PAGE_OR_CUSTOM_POST_TYPE") {
		slug
	}
}
```

This is because `DataSource#resolve_post_object` does not check for post type.

Here's a test that I would expect to pass but currently fails:
https://github.com/Quartz/wp-graphql/commit/a7b71f40882dc7a7078bb6b3c9072efdeb5f6fb5

There is a fairly easy fix (check for post type in `resolve_post_object`), but there is one test (`testGetPostObjectByMethodForMultiplePosts`) that passes in an array of post types instead of a single post type. I'm not sure what the use case is for that and if it's still valid. No actual code seems to ever pass in an array of post types.

**Comment by jasonbahl** [comment]
@chriszarate I'm going to mark this as a duplicate of the #684 

There's been a lot of work done already by @CodeProKid to centralize access to objects in the Graph. 

For the time being, I would _probably_ suggest filtering resolvers directly via something like: 

`graphql_before_resolve_field` or `graphql_resolve_field` filters:

https://github.com/wp-graphql/wp-graphql/blob/develop/src/Utils/InstrumentSchema.php#L124
https://github.com/wp-graphql/wp-graphql/blob/develop/src/Utils/InstrumentSchema.php#L149

**Comment by jasonbahl** [comment]
@chriszarate closing this. If you feel like there's anything the Model Layer doesn't address, let's discuss more in #684 

You can see the progress of that feature here: https://github.com/wp-graphql/wp-graphql/tree/feature/model-layer

Specifically here: https://github.com/wp-graphql/wp-graphql/blob/feature/model-layer/src/Model/Post.php
