### ISSUE TITLE
playground.wpgraphql.com not showing directives

### ISSUE THREAD

**Issue by rpavantica** [wp-graphql/wp-graphql#712]
![screen shot 2019-02-26 at 3 47 45 pm](https://user-images.githubusercontent.com/45439458/53450958-37522300-39e3-11e9-809a-d9885d86c753.png)

**Comment by jasonbahl** [comment]
@rpavantica hey! You can actually open issues on that repo here: https://github.com/wp-graphql/playground.wpgraphql.com/

 Looks like the example in the screenshot is from before the v0.1.0 release of the plugin where connection names where changed. This one _should_ be `RootQueryToPostConnectionWhereArgs` now. 

Would you want to open a pull request to that repo to fix?
