### ISSUE TITLE
Authorization with JWT Auth Plugin

### ISSUE THREAD

**Issue by kmcaloon** [wp-graphql/wp-graphql#713]
Still confused over how exactly authorized requests are supposed to work.

Currently I am using the JWT Authentication plugin for WP REST API and am successfully authenticating and making authorized requests via REST. However, not sure that this token is supposed to work with WP GraphQL. I even tried setting the `GRAPHQL_JWT_AUTH_SECRET_KEY` as the same  value for `JWT_AUTH_SECRET_KEY`, but that didn't change anything.

Not sure if the below code is going to help but figured I would clarify as to how I am trying to include the token in my requests:

```
// Apollo boost setup....
const httpLink = new HttpLink( { uri: `${root}/graphql` } );
const authLink = new ApolloLink( ( operation, forward ) => {

  // This is successfully getting the full token from cookie...
  const token = getToken();

  if( token ) {
    operation.setContext( {
      headers: {
        authorization: `Bearer ${token}`,
      },
    } );
  }

  return forward( operation );

} );
export const graphqlClient = new ApolloClient( {
  link: authLink.concat( httpLink ),
  cache: new InMemoryCache(),
} );
```

Example of failed request

```
export const deletePost = async graphID => {

  graphqlClient.mutate( {
    variables: {
      input: {
        clientMutationId: `Delete Post`,
        id: graphID,
      }
    },
    mutation: gql`
      mutation DELETE_POST( $input: DeletePostInput! ) {
        deletePost( input: $input ) {
          deletedId
          post {
            id
          }
        }
      }
    `
  } );
}
```

I'm sure I'm missing something?

**Comment by jasonbahl** [comment]
@kmcaloon hey, if you're using the REST API JWT plugin, you probably want to de-activate the WPGraphQL JWT Auth plugin. 

Having both active will cause some issues for sure as they will both be looking for the token in the header and not know what to do. 

Try de-activating WPGraphQL JWT Auth and use the tokens from the REST API and see if that makes a difference?

**Comment by jasonbahl** [comment]
Closing as there's been no response from the issue author.

**Comment by kmcaloon** [comment]
Hey sorry about the @jasonbahl. This was for a side project that I had to move away from once I started getting swamped. As soon as I can I will check it all out and let you know .
