### ISSUE TITLE
graphql_map_input_fields_to_wp_query filter causes "Internal server error" if $post_type argument is used.

### ISSUE THREAD

**Issue by saarnilauri** [wp-graphql/wp-graphql#717]
When I use  `graphql_map_input_fields_to_wp_query` filter to do a meta query, I get internal server error, if I use `$post_type` argument. If this argument is removed the filter works without any problem. 

```
add_filter(
	'graphql_map_input_fields_to_wp_query',
	function ($query_args, $args, $source, $all_args, $context, $info, $post_type ){

		// only manipulate event input fields
		if ( 'event' !== $post_type ) { 
			return $query_args;
		}

		if ( ! isset( $args['max_end_date'] ) ) {
			return $query_args;
		}
	
		// do a meta_query
		$query_args['meta_query'] = [
			'event_time_clause' => [
				'key'     => 'event-time_end-date',
				'compare' => '>=',
				'value'   => $args['max_end_date'],
				'type'    => 'DATE',
			],
		];

		unset( $args['max_end_date'] );

		return $query_args;
	},
	10,
	6
);
```

I don't have a proposal how to fix this issue.

**Comment by epeli** [comment]
Your filter argument amount doesn't seem not match with the arguments you have actually listed. You have $accepted_args of 6 but you have listed 7 arguments.

See https://developer.wordpress.org/reference/functions/add_filter/

**Comment by saarnilauri** [comment]
Thank you. Silly mistake.
