### ISSUE TITLE
Feature request: Get total post counts in post connections

### ISSUE THREAD

**Issue by esamattis** [wp-graphql/wp-graphql#723]
When creating paginated lists we need to display the total amount the current query will return during the pagination.

So something equivalent to the `X-WP-Total` header in the REST API would be needed.

Maybe it could be added to the `WPPageInfo` object?

```graphql
query Posts($cursor: String) {
  posts(after: $cursor) {
    pageInfo {
      total  <---- Add this?
    }
    edges {
      node {
        title
      }
    }
  }
}
```

I'm open for implementation ideas and I can submit a PR for it.

**Comment by jasonbahl** [comment]
So this is one thing that was left out intentionally as it can be expensive for servers to calculate and return and I don’t think the consumer should necessarily “own” that. 

What I’ve told folks before is to just filter it in, then I realized that there’s not enough context in the connection filters to filter this in right now. 🤦‍♂️

Part of the work I’ve done in the DataLoader PR I opened yesterday gives a LOT more flexibility to filtering connections, as the WP_Query itself will now be available to filters trying to modify the connection. 

I plan to continue what I did with The post connection resolver with the other connections as well, which will make a feature like this easier to filter in for any connection. 

I’m not 💯opposed to including count, but if it can be easily filtered in I’m leaning toward leaving it out and letting folks filter it in for systems where they feel like the cost to expose isn’t harmful. 

I suppose we could go the other way and expose it by default, then document how to *filter it out* for folks that don’t want the added query cost. 

🤔

**Comment by jasonbahl** [comment]
If we did expose it, I think pageInfo makes sense, and I think we’d want to do a look ahead, by making use of the 4th argument passed to the connection resolver `$info`

We can use that to inspect the selected fields on the connection and determine if we need to ask the query to calculate the rows or not. 

I’m on my phone, so I don’t recall exactly, but it’s something like `$info->getSelectedFields()`

So we could check if `pageInfo.total` was requested, and if so modify the query_args to ask for the found rows in return, else don’t calculate them.

**Comment by epeli** [comment]
Right. Lets hold off until the DataLoader PR lands.

I was also thinking about checking for `getSelectedFields()`. I'm familiar with it from creating the polylang extension. If the count is only calculated when the users ask for it don't see a performance reason to not include it. It could even warn in its field description that it adds an additional sql query to the request.

**Comment by jasonbahl** [comment]
Ok, so we are now in a much better spot to support this feature, either actually in the core plugin (still have some reservations on exposing it by default), or via an extension.

The connections are now properly filterable, so we can _actually_ get info from the underlying query and pass through to PageInfo now. 

You can see an example in the code comments here: 

https://github.com/wp-graphql/wp-graphql/blob/feature/model-layer/src/Data/Connection/AbstractConnectionResolver.php#L517-L546

**Comment by epeli** [comment]
Cool! I'll probably have to tackle this in coming months if nobody else beats me to it.

**Comment by dz0ny** [comment]
For those Googling https://gist.github.com/jasonbahl/d2dfe0c56390e9c9c8b0c25d7d6c4bd2

**Comment by epeli** [comment]
Oh that's pretty need solution. Any gotchas with it?

**Comment by jasonbahl** [comment]
@epeli I think the main gotcha is performance. If you have large datasets, calculating totals can be expensive, which was the main reason it was left out initially.

**Comment by parkerproject** [comment]
@dz0ny which file should we add that script?

**Comment by dz0ny** [comment]
> @dz0ny which file should we add that script?

It can be a custom plugin(just add plugin header), themes functions.php file...

**Comment by jasonbahl** [comment]
I'm going to close this. There are filters and hooks in place to expose this for applications that need it. Plugins like [WPGraphQL Offset Pagination](https://github.com/valu-digital/wp-graphql-offset-pagination) are good examples of this in action. 

I don't feel like there's a compelling enough case for why the core WPGraphQL plugin should expose total out of the box. 

Happy to re-open if folks feel otherwise and can lay out a case.
