### ISSUE TITLE
Users should only be "public" if they have a published post

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#734]
The WP REST API and core WordPress treat users as public only if they have a published post associated with them. 

For example, if you create a user with no published posts, they will not have an author archive page. And if you hit the `/wp-json/wp/v2/posts` endpoint, users with no published posts will not be part of the results. 

Authenticated requests with capabilities of `list_users`, however, can see **_all_** users, regardless of the users connection to published posts.

**Comment by renatonascalves** [comment]
Just a suggestion that it could be useful to have an easy way to filter that. On the WP REST API, you are kind of alone there.

**Comment by jasonbahl** [comment]
@renatonascalves ya, this will all be filterable for sure. 

The goal for all of the model layer rules is to have sensible "secure" defaults, but still be allow site owners to granularly customize to fit their needs.

**Comment by jasonbahl** [comment]
closed by #736
