### ISSUE TITLE
Media Items shouldn't be considered public by default

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#735]
This one needs more discussion, but the core WP REST API doesn't output media items in the `/media` endpoint unless they have a `post_parent` set, and that `post_parent` is considered public. 

I don't fully agree with this, because there are many cases where images are publically available, even with no `post_parent` set. This has burned us many times in our Native iOS/Android apps that consume from the REST API. An image is used within a shortcode or as the featured image of a post, but the REST API won't return the image because the image has not `post_parent` set. Very frustrating experience for application developers. 

I get, on some level, why that decision was made for REST, because Media Items don't have formal statuses, but it doesn't make sense in production applications to have this limitation. 

I'm not sure what the ideal approach should be though. Definitely needs more discussion. . .both on this issue and probably in some core chats. 🤔

**Comment by renatonascalves** [comment]
Would it be complicated to have both options available? A hook somewhere...

**Comment by jasonbahl** [comment]
@renatonascalves can you expand what you mean a bit?

**Comment by renatonascalves** [comment]
Having the option to pull images from graphQL with this "restriction" and have an option to pull without the `post_parent`, like in a shortcode.

**Comment by jasonbahl** [comment]
Maybe. Like you mean if the GraphQL request is happening internally in PHP instead of as an HTTP request it could be treated differently? 🤔

**Comment by jasonbahl** [comment]
I think it ultimately boils down to WordPress being more consistent as a whole, not just WPGraphQL making some arbitrary decision here.

**Comment by jasonbahl** [comment]
If an image _should_ be private, shortcodes _should_ respect that as well. It's a wider problem than any specific API

**Comment by renatonascalves** [comment]
Agree! It's just that those things tend to take years to fix upstream.

**Comment by jasonbahl** [comment]
But _even_ in how WPGraphQL treats it, I don't think it should allow image access to be public in shortcodes and private in an API request. Access to an image should be consistent in PHP or JS.

**Comment by jasonbahl** [comment]
So, just a quick update here. WordPress core considers all uploaded media items public out of the box. 

If you upload a media item, it has a publicly accessible URL by default. I've verified with uploading a ZIP file, JPG, PDF and even an .html file. 

They all get a permalink with no prefix, like a page permalink structure. 

For the time being, WPGraphQL will remain exposing all media items as public, as it follows suit with a core WP install running a core twenty-** theme. 

I still think there's room to improve this, but I think it requires a larger community discussion, not _just_ how WPGraphQL wants to approach it.
