### ISSUE TITLE
Add Tooling for consuming GraphQL queries in PHP

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#752]
Right now, there aren't heaps of options for consuming GraphQL queries and doing something with the GraphQL data from within PHP. 

@benallfree suggested possibly making use of the Laravel Collection class to be able to do something like:

```
$ids = graphql("
    interviewBy(interviewId: 42) {
      timeCodes {
        edges {
          node {
            mentions {
              mentionId
            }
          }
        }
      }
    }
    ")
      ->timeCodes
      ->edges
      ->pluck('node')
      ->mentions
      ->pluck('mentionId')
    ;
```

This is sweet!

I'm not sure if I want to jump straight into just implementing this Collection class right away (although it does look 🔥), but I _at least_ want to get some discussion going around what folks would want as far as consuming GraphQL queries from within PHP.

I know one thing I've wanted for a while is the ability to get data from remote schemas easily

So whatever we implement, it would be nice to be able to use on internal GraphQL data, but also point to a remote GraphQL API and consume data from it as well. 

Let's get some discussion going around what a WPGraphQL Consumer class/tool/etc, should look like.

**Comment by benallfree** [comment]
A little more background on my motivation for suggesting this.

I was busily writing an ORM for WP CPTs, and eventually I realized that I could define all my models as GraphQL types and fields.

One important hurdle is model relationships, especially distant relationships like hasManyThrough, or even more distant. I can use `graphql()` to query those relationships inside a resolver, which is a good start. But the structure returned is not easily traversable, so my thought was to use Laravel's [Collection](https://laravel.com/docs/5.8/collections) class to provide fluent traversal of the graph. [Tighten](https://github.com/tightenco/collect) maintains a `Collection`-only split, and I've been using it for my own projects.

**Comment by benallfree** [comment]
Here is an actual example:

```php
Collection::macro('recursive', function () {
  return $this->map(function ($value) {
    if (is_array($value) || is_object($value)) {
      return collect($value)->recursive();
    }
    return $value;
  });
});

register_graphql_field('Interview', 'mentions', [
    'type' => ['list_of' => 'Mention'],
    'resolve' => function ($source, array $args, $context, $info) {
      $data = graphql(['query' => "
      query GET_INTERVIEW {
        interviewBy(interviewId: {$source->ID}) {
          timeCodes {
            mentions {
              mentionId
            }
          }
        }
      }
      "]);
      $data = collect($data)->recursive();

      return $data['data']['interviewBy']['timeCodes']
        ->pluck('mentions')
        ->collapse()
        ->pluck('mentionId')
        ->map(function ($id) {
          return DataSource::resolve_post_object($id, 'time-code-mentions');
        });
    },
  ]);
});
```
One caveat to using `graphql()` inside resolvers: be very careful about introducing infinite recursion.

**Comment by jasonbahl** [comment]
Ya. I wonder if there’s a way we could detect it and prevent it or throw some very explicit error or something. 🤔

**Comment by benallfree** [comment]
Probably would make sense that resolvers aren't re-entrant.

```php
$call_stack = collect();
function exec($resolver, $args) {
  if($this->call_stack->contains($resolver))) throw new \Exception("Recursion detected");
  $this->call_stack->push($resolver);
  $ret = call_user_func_array($resolver, $args);
  $this->call-stack->pop();
  return $ret;
}
```

**Comment by benallfree** [comment]
https://github.com/graphql/graphql-spec/issues/91#issuecomment-254895093

> The issue is that GraphQL has no way of actually confirming that the data it encounters is not infinitely recursive. Without an ability to make this guarantee, allowing for cyclic queries could in fact expose infinite execution queries which could be used as an attack vector.

Not sure if this is more of a graphql-php issue, but it's worth noting.

**Comment by ricksteruk** [comment]
Thanks for sharing this example:  I was struggling to construct mutations using the qraphql() function in wordpress php.    It might be nice if the WP-GraphQl documentation could explain this in a little more details. 

>       $data = graphql(['query' => "
>       query GET_INTERVIEW {
>         interviewBy(interviewId: {$source->ID}) {
>           timeCodes {
>             mentions {
>               mentionId
>             }
>           }
>         }
>       }
>       "]);

**Comment by jasonbahl** [comment]
I think there's some cool ideas here but going to close this as it doesn't seem to be in the scope of this plugin. 

Would love to see what folks come up with to aid in consuming of queries in PHP though!
