### ISSUE TITLE
How to create a field that is actually its own document tree (related custom post to current post).

### ISSUE THREAD

**Issue by joseffb-mla** [wp-graphql/wp-graphql#754]
Hi. I have two custom post types Apples and Buckets where Buckets tracks groups of Apples in it's comment field via Apple's ID.

How would I extend the plugin in PHP to basically lookup related apple post and toss those documents (along with their custom taxonomies) into a field variables.

I was looking at the register_graphql_field but I'm not sure if it supports entire document objects.

I'd basically want to pull it like this:

Buckets {
    edges {
      node {
   ... BucketFields 
       appleDocuments {
               edges {
                   node {
                      ... AppleFields 

Thanks for the assistance.

**Comment by jasonbahl** [comment]
@joseffb-mla So, you'd want to register a connection between Apples and Buckets. 

This will be _much_ easier to do after the upcoming v0.3.0 release dropping later this week. 

I'll be writing a guide on some things, including the new ConnectionResolvers, so keep an eye on that. 

If you still have questions after that, please ping me again and I'll see if I can help you further. 

Thanks,

Jason

**Comment by joseffb-mla** [comment]
Hi Jason, I was just looking at the way you set up comments in the code and came to same conclusion :) I'll wait for the update as this does seem a bit complicated :) Let me know if you need any testing as I am aiming on getting a working model out to team by end of week and wouldn't mind experimenting with you for QA.

**Comment by jasonbahl** [comment]
@joseffb-mla checkout the "model-layer" branch then. . .it's what the next release is going to be based on. 

The ConnectionResolvers I think are MUCH easier to work on.

**Comment by joseffb-mla** [comment]
OK will do.

**Comment by jasonbahl** [comment]
Just note that there are some breaking changes with that version. I'll be documenting them and an upgrade guide to publish with the release, but if you're already extending the plugin, some things could break on you when you update. 

Keep an eye out for the upgrade guide 😄

**Comment by joseffb-mla** [comment]
Look at the branch now. Is there any alpha docs for the new feature? if not I will wait for the release. ( I've just started with your plugin and it's better time spent to wait for your docs then to go fishing. )

By the way nice work so far. I've gotten the "apples" listing running on react with no probs so far.

**Comment by jasonbahl** [comment]
No docs quite yet. Probably spending a good chunk of the day tomorrow working on them.

**Comment by jasonbahl** [comment]
Code is commented probably better than the current version though 😄

**Comment by jasonbahl** [comment]
Oops. Didn't mean to close 🤦‍♂️

**Comment by joseffb-mla** [comment]
Cool, I'll go and work on more front-end stuff that's still pending until then I guess :)

I've downloaded the code and will be reading it in depth tomorrow 👍

**Comment by joseffb-mla** [comment]
ok so I've updated my composer to use the "model-layer" branch.

I've added register_graphql_connection to init.
`register_graphql_connection( self::get_graphQL_bucket_connection_config( 'bucket' ));` 

added a function to do the actual call back stuff.
```
public static function get_graphQL_bucket_connection_config($post_type, $args = [] ) {
		$post_type_object = get_post_type_object($post_type);
		$connection_args = PostObjects::get_connection_args();

		return array_merge( [
			'fromType'       => 'bucket',
			'toType'         => 'apple',
			'queryClass'       => 'WP_Query',
			'connectionFields' => [
				'postTypeInfo' => [
					'type'        => 'Apple',
					'description' => __( 'Information about the type of content being queried', 'wp-graphql' ),
					'resolve'     => function ( $source, array $args, $context, $info ) use ( $post_type_object ) {
						return DataSource::resolve_post_type( $post_type_object->name );
					},
				],
			],
			'resolveNode'      => function( $id, $args, $context, $info ) {
				$collection = new Buckets($id);
				return $collection->collection_readByID()['apple']; //array of post objects
			},
			'fromFieldName'    => 'collections',
			'connectionArgs'   => $connection_args,
			'resolve'          => function ( $root, $args, $context, $info ) use ( $post_type_object ) {
				return DataSource::resolve_post_objects_connection( $root, $args, $context, $info, $post_type_object->name );
			},
		], $args );
	}
```

but doesn't seem to work. What am I missing?

**Comment by jasonbahl** [comment]
@joseffb-mla I'm working on the upgrade guide today. I'll try and share with you a bit later and see if that helps. 

😄

**Comment by joseffb-mla** [comment]
Sounds awesome. Thanks!

**Comment by jasonbahl** [comment]
@joseffb-mla hey! Here's a doc on the new connections. You can check out the "model-layer" branch for these docs to be accurate, or wait until we formally release v0.3.0. . .it's not looking like it will change from that branch _too_ much. . .still trying to release sometime today, but trying to get more documentation prepared for it. 

Let me know if you still have questions after reading these connection docs, and note that other docs are still being written as we speak.

**Comment by joseffb-mla** [comment]
Sweet. I’ll look at the, tonight. I can creat you some advanced example
code based on what I’m doing once I get it working if you'd like. Let me
know.

**Comment by jasonbahl** [comment]
@joseffb-mla wow, I just noticed I didn't even share the link 🤦‍♂️ 

http://docs.wpgraphql.com/extending/connections

**Comment by joseffb-mla** [comment]
Np. I was tied up all weekend. Unfortunately I'm getting a web page error
on the doc page.

**Comment by Joseffb** [comment]
Hey @jasonbahl.

Got it working, but I needed to create my own resolver class to allow for Parent_post to be null and to include a post__in. 

I tried doing it via the resolver->setQueryArg('in', $array) and  resolver->setQueryArg('parent', 0) but they were both overridden further down the line with defaults.

**Comment by jasonbahl** [comment]
@joseffb-mla the `setQueryArg` gets executed right before the args are used by WP_Query, so they shouldn't be getting overridden at all. 

Can you share your code that you used so I can take a look?

**Comment by Joseffb** [comment]
Sure thing will email it to you later today.

**Comment by jasonbahl** [comment]
Just post in here instead of email. Will help anyone else looking to work on custom connections. . .unless I suppose there's something sensitive about the code.

**Comment by joseffb-mla** [comment]
Will do. Nah, just messy lol.

**Comment by jasonbahl** [comment]
@joseffb-mla when using `setQueryArgs`, you want to use the args as `WP_Query` would read them

So, instead of:

```
$resolver->setQueryArg('parent', 0);
$resolver->setQueryArg('in', $apples);
```

Try: 

```
$resolver->setQueryArg('post_parent', 0);
$resolver->setQueryArg('post__in', $apples);
```

And see if that works. Shouldn't need to copy the Resolver class at all.

**Comment by jasonbahl** [comment]
sorry if my documentation is lacking here. I need to provide some more examples, etc.

**Comment by joseffb-mla** [comment]
OK that makes more sense. I was using the short version you use in the actual graphql query.

This works now as expected (and let me delete one whole file :) )

I can draft up a quick how to for the scenario that I was working on (where you use the comment table to track related post — pretty common) if you would like.


Regards, Joseff
______________________________
Joseff Betancourt
Sr. Website Developer
jbetancourt@mla.org

**Comment by jasonbahl** [comment]
ya, the more knowledge that's out there for others doing similar things, the better.
