### ISSUE TITLE
Model Layer: MediaDetails

### ISSUE THREAD

**Issue by CodeProKid** [wp-graphql/wp-graphql#759]
Create a model layer for MediaDetails objects

**Comment by jasonbahl** [comment]
Interesting. Do you feel that this meta requires a model separate from the Media Item?

I guess I've always kind of thought of object meta as an extension of the object and would fall under the same Model as the object itself 🤔

**Comment by jasonbahl** [comment]
That said, we don't have a great way to handle defining access control for deeply nested properties within meta 🤔

**Comment by CodeProKid** [comment]
we chatted about this, and decided this would be handled on a higher level.
