### ISSUE TITLE
Menus not attached to a menu-location should be private

### ISSUE THREAD

**Issue by CodeProKid** [wp-graphql/wp-graphql#778]
Menus that aren't attached to a menu-location should be private in the Menu model.

**Comment by jasonbahl** [comment]
This is addressed in #1348 

Here, we have "Menu Without Location Assigned

![Screen Shot 2020-06-25 at 2 54 16 PM](https://user-images.githubusercontent.com/1260765/85794387-c8c6c780-b6f3-11ea-8a48-8d4302a03043.png)

## Query Single Menu:

I can query as an authenticated user with `manage_options` capability and see the menu: 

![Screen Shot 2020-06-25 at 2 55 45 PM](https://user-images.githubusercontent.com/1260765/85794518-04fa2800-b6f4-11ea-9c30-a7d26b746cd1.png)

But the same query as a public user returns no menu: 

![Screen Shot 2020-06-25 at 2 56 05 PM](https://user-images.githubusercontent.com/1260765/85794570-17746180-b6f4-11ea-82ce-ee2e6c432a07.png)

## Query List of Menus
I can also query a list of menus as an authenticated user and see the menu:

![Screen Shot 2020-06-25 at 2 58 15 PM](https://user-images.githubusercontent.com/1260765/85794742-53a7c200-b6f4-11ea-9bed-b3a5b424f160.png)

But as a public user I cannot see the menu:

![Screen Shot 2020-06-25 at 2 58 04 PM](https://user-images.githubusercontent.com/1260765/85794762-5f938400-b6f4-11ea-8cd4-dc64950be90b.png)

**Comment by jasonbahl** [comment]
^ This also applies to MenuItems. 

We can query for menu items as a public user, and we're limited only to menu items associated with a public menu:

![Screen Shot 2020-06-25 at 3 07 39 PM](https://user-images.githubusercontent.com/1260765/85795854-307e1200-b6f6-11ea-9096-2a2113049085.png)

But if we query as an authenticated user, we can access menu items of any menu:

![Screen Shot 2020-06-25 at 3 11 03 PM](https://user-images.githubusercontent.com/1260765/85795898-425fb500-b6f6-11ea-8e48-bf710344bb5b.png)

**Comment by jasonbahl** [comment]
Closing as this is being released with #1348
