### ISSUE TITLE
Unit Tests for Router.php

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#78]
The Router needs to be 100% unit tested. 

We've had some bugs cause issues with folks (for example Apollo pre-flight req's were broken) and good testing could've helped prevent this. 

The code _might_ need some refactoring to get to 100%.

**Comment by CodeProKid** [comment]
Per slack, this had a first pass of tests, but this probably needs some more thorough tests, and some small refactoring to make it a little more testable.
