### ISSUE TITLE
The link to the upgrade guide in the release notes for 0.3.0 is wrong

### ISSUE THREAD

**Issue by mwidmann** [wp-graphql/wp-graphql#784]
I have no if the release notes can be updated, but the link to the upgrade guide in the release notes points to https://www.wpgraphql.com/2019/04/03/upgrading-to-v0-3-0/ which leads to a 404, while it should point to https://www.wpgraphql.com/2019/04/05/upgrading-to-v0-3-0/

**Comment by jasonbahl** [comment]
Updated the link. Thanks for pointing that out. I linked to the draft URL but published 2 days later 🤦‍♂️
