### ISSUE TITLE
How to add meta data the right way

### ISSUE THREAD

**Issue by drewbaker** [wp-graphql/wp-graphql#795]
OK, so we are in the middle of building a big WordPress Nuxt framework. We are using WordPress a headless CMS. So obviously we need to make use of custom meta fields a lot.

I've read all the issues and docs on getting meta out of a WP-GQL query, and it seems there is a big ACF plugin coming (very needed), but in the meantime it seems just having a way to get back all meta would be a good work around. 

I tried this:

```
 add_action( 'graphql_register_types', function() {

    $post_types = WPGraphQL::$allowed_post_types;

    if ( ! empty( $post_types ) && is_array( $post_types ) ) {
        foreach ( $post_types as $post_type ) {
            $post_type_object = get_post_type_object( $post_type );

            register_graphql_field( $post_type_object->graphql_single_name, 'meta', [
                'type'        => ['list_of' => 'String'],
                'description' => __( 'All meta attached to this object as an array', 'wp-graphql' ),
                'resolve'     => function( $post ) {
                    $meta = get_post_meta( $post->ID );
                    return ! empty( $meta ) ? $meta : [];
                }
            ]);
        }
    }
 });
```

Or even better for ACF:

```
 add_action( 'graphql_register_types', function() {

    $post_types = WPGraphQL::$allowed_post_types;

    if ( ! empty( $post_types ) && is_array( $post_types ) ) {
        foreach ( $post_types as $post_type ) {
            $post_type_object = get_post_type_object( $post_type );

            register_graphql_field( $post_type_object->graphql_single_name, 'acfFields', [
                'type'        => ['list_of' => 'String'],
                'description' => __( 'All ACF meta attached to this object as an array', 'wp-graphql' ),
                'resolve'     => function( $post ) {
                    $acf_fields = get_fields($post->ID);
                    return ! empty( $acf_fields ) ? $acf_fields : [];
                }
            ]);
        }
    }
 });
```

But it doesn't work, gives a lot of `Internal server error`'s and I admit probably against the spirit of GQL (you'll get back way more than you asked for).

Also, sometimes we use meta to store an image ID, and obviously we'd want to actually return the ID, URL, `src-set` etc...

So I'm not sure the best way to approach getting meta out in a big way? It's trivial for 1 or 2 fields, but we'd end up with a lot of code to handle anything serious. We have some big sites with hundreds of meta fields thanks to ACF, with nested `flexible-content` and `repeater` fields, or attachments with images attached to them etc...

So I'm looking for some guidance or direction on the recommended way to handle meta beyond 1 or 2 fields.

**Comment by jasonbahl** [comment]
ACF is getting close. I can demo for you when we chat tomorrow 😀

**Comment by drewbaker** [comment]
Looking forward to it Jason!

For anyone else in the future, I was trying to get this working today. This would make it fast to register lots of meta fields that were strings.

```
    function register_gql_meta_strings() {
        $post_types = WPGraphQL::$allowed_post_types;

        // These all need to be strings
        $meta_keys = array(
            'custom_developer_id'   => ''
        )

        // Loop thropugh all posts types and register meta keys from white list above
        if ( ! empty( $post_types ) && is_array( $post_types ) ) {
            foreach ( $post_types as $post_type ) {
                $post_type_object = get_post_type_object( $post_type );

                foreach($meta_keys as $meta_key) {
                    register_graphql_field( $post_type_object->graphql_single_name, $meta_key, [
                        'type'        => 'String',
                        'description' => __( 'Meta for the key '.$meta_key. ' as a string', 'wp-graphql' ),
                        'resolve'     => function( $post ) {
                            $meta = get_post_meta( $post->ID, $meta_key, true );
                            return ! empty( $meta ) ? $meta : '';
                        }
                    ]);
                }
            }
        }
    }
    add_action( 'graphql_register_types', 'register_gql_meta_strings');
```

It doesn't work yet, I think because the meta_key needs to be camelCase, not underscored like what is the WordPress convention. Also, it seemed to give sever errors, I suspect because `$post_types` is more than just the usual `post, page, attachment`. But I'm not sure. I'll report back if I get this working better later.

**Comment by skaltenegger** [comment]
@jasonbahl I'm currently building a react (next.js) project with GraphQL and would love to include my existing wordpress api (that also exposes ACF fields) via wp-graphql... are there any news on this? 
I just installed https://github.com/wp-graphql/wp-graphql-acf but it does not seem to expose ACF's custom fields in the queries... 
Thanks a lot,
Stefan

**Comment by jasonbahl** [comment]
@skaltenegger your timing is great. We've just launched here: https://www.wpgraphql.com/acf/

I'll update that repo to reflect details on how to get the new version of the plugin. 

Looking forward to what ya'll create with it!

**Comment by skaltenegger** [comment]
Hi @jasonbahl,

That's great news indeed, thanks for sharing! 
Is there any possibility to get a free trial version of the plugin so that we can check out if it works well for our ACF field structure before we would of course buy a license?

Thanks and all the best,
Stefan

**Comment by jasonbahl** [comment]
@drewbaker Hey! I'm going to close this issue. The "right" way is to use the `register_graphql_field` API to add fields to your Schema. I think a lot of how you expose your meta to the Schema will be dependent on the needs of your application. 

We can discuss more details about the WPGraphQL for ACF plugin over here: https://github.com/wp-graphql/wp-graphql-acf 😄

**Comment by drewbaker** [comment]
Yeah using the ACF plugin is how we are going to solve this.

**Comment by martin-braun** [comment]
> Looking forward to it Jason!
> 
> For anyone else in the future, I was trying to get this working today. This would make it fast to register lots of meta fields that were strings.
> 
> ```
>     function register_gql_meta_strings() {
>         $post_types = WPGraphQL::$allowed_post_types;
> 
>         // These all need to be strings
>         $meta_keys = array(
>             'custom_developer_id'   => ''
>         )
> 
>         // Loop thropugh all posts types and register meta keys from white list above
>         if ( ! empty( $post_types ) && is_array( $post_types ) ) {
>             foreach ( $post_types as $post_type ) {
>                 $post_type_object = get_post_type_object( $post_type );
> 
>                 foreach($meta_keys as $meta_key) {
>                     register_graphql_field( $post_type_object->graphql_single_name, $meta_key, [
>                         'type'        => 'String',
>                         'description' => __( 'Meta for the key '.$meta_key. ' as a string', 'wp-graphql' ),
>                         'resolve'     => function( $post ) {
>                             $meta = get_post_meta( $post->ID, $meta_key, true );
>                             return ! empty( $meta ) ? $meta : '';
>                         }
>                     ]);
>                 }
>             }
>         }
>     }
>     add_action( 'graphql_register_types', 'register_gql_meta_strings');
> ```
> 
> It doesn't work yet, I think because the meta_key needs to be camelCase, not underscored like what is the WordPress convention. Also, it seemed to give sever errors, I suspect because `$post_types` is more than just the usual `post, page, attachment`. But I'm not sure. I'll report back if I get this working better later.

The reason why your sample wasn't working is, because you have to use the `use` keyword to pass `$meta_key` to the scope of the anonymous function. 

Sample: 

```php
                foreach($meta_keys as $meta_key) {
                    register_graphql_field( $post_type_object->graphql_single_name, $meta_key, [
                        'type'        => 'String',
                        'description' => __( 'Meta for the key '.$meta_key. ' as a string', 'wp-graphql' ),
                        'resolve'     => function( $post ) use ( $meta_key ) {
                            $meta = get_post_meta( $post->ID, $meta_key, true );
                            return ! empty( $meta ) ? $meta : '';
                        }
                    ]);
                }
```
