### ISSUE TITLE
v0.3.x breaks menus

### ISSUE THREAD

**Issue by JosephCarrington** [wp-graphql/wp-graphql#805]
On versions 0.3 and above, this query returns either an empty result set or a fatal error
```
query test {
  menus(where: {location: FOOTER}) {
    nodes {
      count
      # id // this node creates the fatal error
  }
}
```
while on version v0.2.3, the same query returns expected results.
This was tested on a vanilla WP install with only wp-graphql and wp-graphiql

Thanks!

**Comment by jasonbahl** [comment]
@JosephCarrington Thanks! I'll take a look shortly and make sure to get some tests in place to prevent another future regression.

**Comment by jasonbahl** [comment]
@JosephCarrington I opened a PR here to address this: https://github.com/wp-graphql/wp-graphql/pull/806

Thanks again for submitting the issue!

**Comment by jasonbahl** [comment]
@JosephCarrington Want to give the latest `develop` a shot and see if that's working for you now? 😄

**Comment by JosephCarrington** [comment]
I have done so. It fixes the issue mostly. However I had to re-assign the menu to the location to get it to work. Also, I assigned the test menu to the footer, then unassigned it. At that point, running the following query:
```
query test {
  menus(where: {location: FOOTER}) {
    nodes {
      count
      id
      slug
    }
  }
}
```
returned the test menu even though it as no longer assigned. I then assigned a new test menu, and running the above query returned two menus:
```
{
  "data": {
    "menus": {
      "nodes": [
        {
          "count": 1, // old, no longer assigned menu
          "id": "TWVudToy",
          "slug": "test"
        },
        {
          "count": 3, // newly assigned menu
          "id": "TWVudToz",
          "slug": "test2"
        }
      ]
    }
  }
}
```

But perhaps this is a different issue?

**Comment by JosephCarrington** [comment]
I am thinking that unassigning a menu from a location does not change whatever it is that wp-graphql is using to determine which menus go where

**Comment by jasonbahl** [comment]
@JosephCarrington 🤔 Perhaps a caching issue at play here?

**Comment by jasonbahl** [comment]
I imagine it's a cache issue based on the behavior you're describing. Do you have an persistent object caching in place?

**Comment by jasonbahl** [comment]
But, there still _may_ be another issue we need to investigate with WPGraphQL 🤔

**Comment by JosephCarrington** [comment]
I am on Kinsta. I have cleared it's cache from both the WP admin and the Kinsta admin, but still get the two menus. If it is in fact a caching issue then it is outside of my control presently. I see in the src that you are running: `$resolver   = new MenuConnectionResolver( $source, $args, $context, $info, 'nav_menu' );` I oinder if there is something similar I can do in regular old PHP to see if WP does in fact think two menus are assigned to that same location?

**Comment by jasonbahl** [comment]
so, it runs a WP_Term_Query and the args are determined here: 
https://github.com/wp-graphql/wp-graphql/blob/2c75ece5791b4a48e2b6c3a4a3761c78a3ceba37/src/Data/Connection/MenuConnectionResolver.php#L17-L43

so something like: 

```
new WP_Tem_Query([
  'hide_empty' => false,
  'include' => [],
  'taxomomy' => 'nav_menu',
  'include' => 'footer'
]);
```

**Comment by JosephCarrington** [comment]
Interestingly enough, that query does in fact return two menus:
```
array(2) {
  [0]=>
  object(WP_Term)#713 (10) {
    ["term_id"]=>
    int(2)
    ["name"]=>
    string(4) "test"
    ["slug"]=>
    string(4) "test"
    ["term_group"]=>
    int(0)
    ["term_taxonomy_id"]=>
    int(2)
    ["taxonomy"]=>
    string(8) "nav_menu"
    ["description"]=>
    string(0) ""
    ["parent"]=>
    int(0)
    ["count"]=>
    int(1)
    ["filter"]=>
    string(3) "raw"
  }
  [1]=>
  object(WP_Term)#721 (10) {
    ["term_id"]=>
    int(3)
    ["name"]=>
    string(5) "test2"
    ["slug"]=>
    string(5) "test2"
    ["term_group"]=>
    int(0)
    ["term_taxonomy_id"]=>
    int(3)
    ["taxonomy"]=>
    string(8) "nav_menu"
    ["description"]=>
    string(0) ""
    ["parent"]=>
    int(0)
    ["count"]=>
    int(3)
    ["filter"]=>
    string(3) "raw"
  }
}
```

**Comment by jasonbahl** [comment]
@JosephCarrington interesting 🤔 

Do you have multiple menus assigned somehow. Wonder if there's a core bug we just discovered too 🤔

**Comment by JosephCarrington** [comment]
Well no matter what we `include`, this code returns every menu:
```
add_action('init', function() {
        $menus = new WP_Term_Query([                                                                                                                        
                'hide_empty' => false,                                                                                                                      
                'include' => 'social',                                                                                                                      
                'taxonomy' => 'nav_menu'                                                                                                                    
        ]);                                                                                                                                                 
        die(var_dump($menus->get_terms()));
});   
```
I am wondering if this is either a Kinsta specific issue, or if maybe the `terms` are not the best way to determine the current state of truth for menus

**Comment by jasonbahl** [comment]
Seems like an underlying data issue from what I can tell. Looks like you have both `test` and `test2` assigned to the same location. 🤔

**Comment by JosephCarrington** [comment]
I think it might be one of those 'if WP cannot find anything matching this query, it returns everything'

**Comment by jasonbahl** [comment]
could be 🤔

**Comment by JosephCarrington** [comment]
May I invite you as an admin to my testing sandbox so that you can see that there are not two menus set to the same location?

**Comment by jasonbahl** [comment]
@JosephCarrington sure. are you in slack? we can coordinate creds in there

**Comment by JosephCarrington** [comment]
I am `on` Slack, but not in any kind of wp-graphql Slack. my email is jcarrington@meowwolf.com though, if that helps

**Comment by jasonbahl** [comment]
@JosephCarrington you can join the WPGraphQL slack here, if interested: https://wpgql-slack.herokuapp.com/

But I'll email you.
