### ISSUE TITLE
CreateComment Mutation does not update comment_approved status when provided.

### ISSUE THREAD

**Issue by joseffb-mla** [wp-graphql/wp-graphql#807]
Query: 
```
mutation CREATE_COMMENT($input: CreateCommentInput!) {
    createComment(input: $input) {
        comment {
            commentId
            content
        }
    }
}

Vars: 
{
  "input": {
    "commentOn": 1241,
    "clientMutationId": "CreateComment",
    "content": "19",
    "author": "CollectionBuilder",
    "type": "artifact",
    "approved": "1"
  }
}
```

Expectation:
Add the comment to post 1241 with content of "19" author of "CollectionBuilder" comment type of "artifact" and comment approved value of "1"

Result:
Add the comment to post 1241 with content of "19" author of "CollectionBuilder" comment type of "artifact" and comment approved value of "0"

I ran this authenticated as admin and unauthenticated, results same for each.
I ran this on the post with comments enabled and disabled, results same for each.

query returns null for contentId and content if you are unauthorized, filled when authorized. (maybe an error message should be given if unauthorized).

**Comment by justlevine** [comment]
Confirmed in v1.8.1

![image](https://user-images.githubusercontent.com/29322304/168170094-cb163685-1931-43b4-a54f-c596faff811a.png)


Ref: [possible status values](https://developer.wordpress.org/reference/functions/wp_set_comment_status/).
Related: https://github.com/wp-graphql/wp-graphql/pull/2323
