### ISSUE TITLE
Cannot query field update_date on type Post

### ISSUE THREAD

**Issue by ciprianimike** [wp-graphql/wp-graphql#809]
Updating wp-graphql from 0.2.x to 0.3.01 some queries that worked before now return 
`{message: "Cannot query field "update_date" on type "Post".", category: "graphql", locations: Array(1)}`

the query is defined as:
```
query PostsFeaturedQuery( $after: String, $first: Int, $before: String, $last: Int, $where: RootPostsQueryArgs, $postId: Int ) {
		postBy( postId: $postId ) {
			id
			alignment
			title
			excerpt
			date
			link
			featuredImage {
				sourceUrl
			}
		}

		posts( after: $after, first: $first, before: $before, last: $last, where: $where ) {
			pageInfo {
				startCursor
				endCursor
				hasNextPage
				hasPreviousPage
			}
			edges {
				cursor
				node {
					id
					alignment
					title
					excerpt
					date
					link
					featuredImage {
						sourceUrl
					}
				}
			}
		}
	}
```

then it is requested as:
```
query PostsFeaturedQuery($after: String, $first: Int, $before: String, $last: Int, $where: RootQueryToPostConnectionWhereArgs, $postId: Int) {
  postBy(postId: $postId) {
    id
    alignment
    title
    excerpt
    date
    update_date
    link
    featuredImage {
      sourceUrl
      __typename
    }
    __typename
  }
  posts(after: $after, first: $first, before: $before, last: $last, where: $where) {
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
      __typename
    }
    edges {
      cursor
      node {
        id
        alignment
        title
        excerpt
        date
        update_date
        link
        featuredImage {
          sourceUrl
          __typename
        }
        __typename
      }
      __typename
    }
    __typename
  }
}
```

It would seem that the update_date field is set in the query by the apollo client, and not at the application level.

**Comment by jasonbahl** [comment]
@ciprianmike, `update_date` Isn’t a field that’s been provided by WPGraphQL in any version. My guess is it was filtered into your Schema by custom code and something needs to happen to update how that field was added to your Schema. 

Can you provide info on how that field was added to the Schema on the server?

**Comment by jasonbahl** [comment]
@ciprianimike hey, wanted to check in to see if you got this resolved? I think that field is custom to your application and likely needs to be updated in your custom code. 

My only guess is that your custom resolver was expecting a `\WP_Post` and in v0.3.0 we introduced a formal "Model" layer, so your resolvers would now be passed a `\WPGraphQL\Model\Post` instead. 

You can read a bit more about the Models here: https://docs.wpgraphql.com/guides/model-layer

**Comment by jasonbahl** [comment]
I'm going to close this as I believe the issue most likely is related to your custom code and can be fixed by tweaking your custom resolver, but if you find you're still having issues, paste in the custom resolvers that are having issues and I'll see what I can do to help get you updated and compatible with v0.3.2+. 

Thanks!

**Comment by ciprianimike** [comment]
@jasonbahl I found it was an Apollo client issue, not a wp-graphql one. Thanks for you support

**Comment by jasonbahl** [comment]
Awesome! Glad you got it figured out.
