### ISSUE TITLE
v0.3.x menu where clause not being respected

### ISSUE THREAD

**Issue by JosephCarrington** [wp-graphql/wp-graphql#811]
No matter what args you provide to the menus(where: {}) clause, it returns all the menus. I think this is because the `$args` variable is not being fed into the parse_query_args() function at: https://github.com/wp-graphql/wp-graphql/blob/develop/src/Data/Connection/MenuConnectionResolver.php, so it's always null

**Comment by jasonbahl** [comment]
@JosephCarrington thanks for submitting this issue. I've opened a PR to address it. #812 

Thanks!
