### ISSUE TITLE
v0.3.x - Resolver on type User returning 'false' instead of meta key value

### ISSUE THREAD

**Issue by szvest** [wp-graphql/wp-graphql#819]
It seems that there is a problem with resolving custom user meta fields with version 0.3. 

I made sure to update my action `graphql_register_types` resolvers by replacing the legacy `\WP_User` with `\WPGraphQL\Model\User` but it seems that the User object cannot get resolved with `$user->ID` unless it is hardcoded.

Below is a reproduction of the issue (gif)... 

https://drive.google.com/file/d/1W5URQ92QJOrycQv7lunc2H7EP7zmwf4h/view

**Comment by CodeProKid** [comment]
@szvest try using `$user->userId` since `$user->ID` is the global ID, not the DB int ID now.

**Comment by szvest** [comment]
Excellent! Works like a charm now. Thanks @CodeProKid.

**Comment by szvest** [comment]
Excellent! Works like a charm now. Thanks @CodeProKid.

**Comment by jasonbahl** [comment]
Thanks @CodeProKid! closing this issue.

**Comment by jasonbahl** [comment]
ah @szvest beat me to it 😄
