### ISSUE TITLE
There is no "order" argument for any resource

### ISSUE THREAD

**Issue by manzoorwanijk** [wp-graphql/wp-graphql#829]
There is the `orderby` for Posts, Categories, Comments etc. in `whereArgs` but no `order` argument which could be `DESC` or `ASC` like in WP REST API. Is there any reason for that? If not, I would love to create a PR :)

**Comment by jasonbahl** [comment]
@manzoorwanijk we're pretty inconsistent here and I want to revisit sooner than later. Happy to collaborate with you to get this worked on if you have the time and interest to tackle it!

Right now the `order` args live within `where`, which I agree was a poor decision. My naiive-Schema-designing-self at the time just made the `where` arguments essentially a near 1-to-1 map of WP_Query args. 

So, the order/orderby fields live within `$where` currently. 

For example: 
![posts-orderby](https://user-images.githubusercontent.com/1260765/56812281-cae37c80-67f7-11e9-82b7-6708e1589926.gif)

Then for terms, the ordering is also in the `$where` args, but it's not as "rich". . .it lets you select the field to order by, but not the cardinality (ASC/DESC) 🤦‍♂️ 

Definitely need some work here. 

I think before we hit the ground running on implementation, we should come up with a solid plan for how it should look in the Schema, and how a user should interact with it, then once we have a good idea, we can work on making the proper changes to get it exposed. 

Happy to collaborate with you to make this happen. 😄 

We have these related open issues as well: #820, #329, #285
