### ISSUE TITLE
Get menuItem uri or slug

### ISSUE THREAD

**Issue by joshuaiz** [wp-graphql/wp-graphql#834]
When querying `menus` and their respective `menuItems` it would be great to be able to grab the `menuItem` uri or slug directly.

When working with headless WP and setting up menus, you really just want the page slug/uri to set up your link elements.

So something like this:

```javascript
{
  wpgraphql {
    menus {
      edges {
        node {
          menuItems {
            edges {
              node {
                label
                title
                slug
                uri
                target
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by drewbaker** [comment]
This might help, if it works for pages: https://github.com/wp-graphql/wp-graphql/issues/810

I would like to know if the menuItem is a page/post/categories or a custom item. Basically it's important to know if the user has entered an external URL, it's hard to infer that from parsing the URL.

**Comment by jasonbahl** [comment]
So, there’s a `connectedObject` field that allows you to get properties of the connected object via a union query. 

`...on Page { url }` for example

**Comment by jasonbahl** [comment]
Some docs here: https://docs.wpgraphql.com/getting-started/menus

**Comment by jasonbahl** [comment]
@drewbaker @joshuaiz I just fixed #810 

Does that satisfy your needs here?

You can now query something like: 

```
{
  menu(id: "TWVudTo2MA==") {
    menuItems {
      nodes {
        label
        childItems {
          nodes {
            connectedObject {
              __typename
              ... on Page {
                title
                id
                link
                slug
              }
              ... on Category {
                slug
                link
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by drewbaker** [comment]
Well I was hoping to know if the link was a “custom link” menu item. Like a menu item going out to google.com for example.

**Comment by jasonbahl** [comment]
@drewbaker you can do that. 

It's just another option for connected object:

I'm thinking now that we could have a general `uri` field, and it could resolve appropriately to the URI for a Post, Term or Custom Link without having to query the connected object directly 🤔 

Let me think about this a tad more, but I think it should be doable without _too_ much trouble

```
{
  menu(id: "TWVudTo2MA==") {
    menuItems {
      nodes {
        label
        childItems {
          nodes {
            connectedObject {
              __typename
              ... on Page {
                title
                date
                link
                slug
              }
              ... on Category {
                slug
                link
              }
              ... on MenuItem {
                url
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by jasonbahl** [comment]
@drewbaker @joshuaiz @TylerBarnes @CodeProKid 

Right now you can query the `url` of MenuItems like so:

```graphql
{
  menu(id: "dGVybTo1NQ==") {
    name
    id
    databaseId
    menuItems {
      nodes {
        id
        title
        url
      }
    }
  }
}
```

This will return a payload like so:

```json
{
  "data": {
    "menu": {
      "name": "Unpublished MEnu",
      "id": "dGVybTo1NQ==",
      "databaseId": 55,
      "menuItems": {
        "nodes": [
          {
            "id": "bmF2X21lbnVfaXRlbTo2Mzk=",
            "title": null,
            "url": "http://acf2.local/test-page/"
          },
          {
            "id": "bmF2X21lbnVfaXRlbTo2NDA=",
            "title": null,
            "url": "http://acf2.local/tests-more/"
          },
          {
            "id": "bmF2X21lbnVfaXRlbTo2NDE=",
            "title": null,
            "url": "https://external-site.com/some-page"
          },
          {
            "id": "bmF2X21lbnVfaXRlbTo2NDI=",
            "title": null,
            "url": "http://acf2.local/category/uncategorized-en/"
          }
        ]
      }
    }
  }
}
```

I was thinking a `uri` field would be good where we could output the relative path, but that gets interesting when it comes to custom links such as this one: 

```json
{
  "id": "bmF2X21lbnVfaXRlbTo2NDE=",
  "title": null,
  "url": "https://external-site.com/some-page"
}
```

Does the existing `url` field resolve the original needs of this issue, or does it still feel like there's a missing part of querying information re: menu items that would be useful here?

**Comment by CodeProKid** [comment]
@jasonbahl I think being able to get _just_ the URI would be good, since it's possible (if not probable) that the url for the admin will be different than the front-end app url. Something like [wp_parse_url](https://developer.wordpress.org/reference/functions/wp_parse_url/) might be useful for getting the slug on a custom link.

**Comment by joshuaiz** [comment]
@jasonbahl I would also like to get the uri/slug so you can replicate menus via page slugs in a headless app.

**Comment by joshuaiz** [comment]
@jasonbahl I would also like to get just the uri/slug to mirror WP menus in a headless app. In general, I don't need the url but just want the slugs from the menu to create routes.

**Comment by drewbaker** [comment]
To get menus to work, currently I have to get the `url` and then also get the site settings URL, and then I do a replace to remove the domain. So yes, a `uri` would be super helpful. 

Seems to me on a custom link, it should return `null`. Maybe you could talk me into it being `null` or the `uri` if the custom link it just pointing to the same domain as site settings?

PS: Honestly, the best thing you could do to make menus easier to use is allow querying of the menu by name, not by location or WP-GQL ID.

**Comment by jasonbahl** [comment]
Ya, I'm curious how to best handle external vs. internal links. 

Like just exposing the path doesn't work all around because some menu items can link to external URLs. 

I suppose though, internal urls could expose a relative path and external could expose absolute?

That should work for most headless CMS's, eh? I know [Gatsby Link](https://www.gatsbyjs.org/docs/gatsby-link/#replace-a-tags-with-the-link-tag-for-local-links) for example handles external URLs different than relative paths. 

so we could have a response like: 

```json
[
  {
    id: "item-1",
    uri: "/hello-world",
  },
  {
    id: "item-2",
    uri: "/tag/some-tag",
  },
  {
     id: "item-3",
     uri: "http://external-site.com/path"
  }
]
```

**Comment by jasonbahl** [comment]
So, the resolver could essentially be something like: 

If domain matches WordPress URL in settings, parse and return the path. Else, return the full url?

**Comment by jasonbahl** [comment]
@drewbaker re: 
> PS: Honestly, the best thing you could do to make menus easier to use is allow querying of the menu by name, not by location or WP-GQL ID.

I'm down with this idea. I _thought_ menu names were not unique identifiers (like posts, terms, etc), but it appears that WordPress does indeed enforce unique names for menus.

![Screen Shot 2020-06-25 at 1 15 37 PM](https://user-images.githubusercontent.com/1260765/85784892-fe64b400-b6e5-11ea-9799-71faf9417e8f.png)


I'll add this.

**Comment by jasonbahl** [comment]
@drewbaker coming to a v0.10.0 release near you: 

![Screen Shot 2020-06-25 at 1 56 23 PM](https://user-images.githubusercontent.com/1260765/85789363-b3e63600-b6eb-11ea-9a63-589ec15badce.png)

**Comment by jasonbahl** [comment]
Ok folks, how's something like this: 

The `path` field has the following description: `Path for the resource. Relative path for internal resources. Absolute path for external resources.`

![Screen Shot 2020-06-25 at 2 12 13 PM](https://user-images.githubusercontent.com/1260765/85790719-f01a9600-b6ed-11ea-9fa1-dd79159fb0b6.png)

**Comment by jasonbahl** [comment]
@joshuaiz @drewbaker ^ does that seem like it should work? 

I opted for the field name `path` instead of `uri` because as of right now any node with a URI field can also use that `uri` to get itself. That wouldn't be the case with a MenuItem, as the `path` is actually a reference to the connected object, and not the MenuItem itself.

**Comment by drewbaker** [comment]
Seems great to me, thanks @jasonbahl

**Comment by drewbaker** [comment]
For anyone wondering how we use this in Nuxt/Vue:

https://github.com/funkhaus/fuxt/blob/master/gql/queries/MenuByLocation.gql
https://github.com/funkhaus/fuxt/blob/master/components/WpMenu.vue
https://github.com/funkhaus/fuxt/blob/master/components/WpMenuItem.vue

**Comment by jasonbahl** [comment]
Marking this closed as it will be released with v0.10.0 (#1348)

**Comment by rodrigo-arias** [comment]
Hi @jasonbahl, I have noticed that if I use a domain in the Site Address URL other than the domain where WordPress is hosted, the path attribute is processed as an external resource (absolute path) when they are actually internal resources. At the moment I have solved it with a simple `replace()` on Gatsby, but I wanted to leave a message here.

**Comment by jasonbahl** [comment]
@rodrigo-arias can you open a new issue with examples/screenshots and reference this issue?

**Comment by rodrigo-arias** [comment]
@jasonbahl for sure #1532 thanks.
