### ISSUE TITLE
Hooking WooCommerce Categories to GraphQL 

### ISSUE THREAD

**Issue by joshglenn** [wp-graphql/wp-graphql#835]
Good afternoon! Loving wp-graphql so far. It's a very important step forward for wordpress, in my opinion.

Ok, so I am trying to hook up graphql to woocommerce. I am able to get some fields back from the product using the instructions in #321. In fact, my issue is somewhat related to #321. 

However, when I try to get categories belonging to a product, I get server errors when the ID is queried. Take a look:

This is my query:
```
{
  products {
    edges {
      node {
        id
        price
        regular_price
        productId
        thumbnail
        categories {
          name
          id
        }
      }
    }
  }
}

```

This is the field declaration:

```
    $fields['categories'] = [
        'type' => \WPGraphQL\Types::list_of(\WPGraphQL\Types::taxonomy()),
        'description' => __('The product\'s categories', 'woocommerce-to-wpgraphql'),
        'resolve' => function( $post) {
            $product = new WC_Product($post->ID);
            $cat_ids = $product->get_category_ids();
            $cats = array_map(function($cat_id) {
                return get_term($cat_id);
            }, $cat_ids);
            return $cats;
        }
    ];
```

This is what the error says in the graphql response:

```
  "errors": [
    {
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 10,
          "column": 9
        }
      ],
      "path": [
        "products",
        "edges",
        0,
        "node",
        "categories"
      ]
    },
```

This is what I get when I am debugging the field declaration:

<img width="313" alt="Screen Shot 2019-05-01 at 12 30 12 PM" src="https://user-images.githubusercontent.com/6953274/57032074-112d4700-6c0f-11e9-8ed2-a14e844d96c3.png">

I notice in the debug variable in the photo above, that there is no `id` field, but a `term_id`. Could that have anything to do with it? Any idea where I should begin in order to troubleshoot this?

**Comment by renatonascalves** [comment]
@joshglenn Did you try this project https://github.com/kidunot89/wp-graphql-woocommerce/ ?

**Comment by jasonbahl** [comment]
@joshglenn Thanks for the kind words. Glad you're enjoying WPGraphQL. 

I'd first recommend you check out the WooCommerce integration going on here: https://github.com/kidunot89/wp-graphql-woocommerce

It also looks like you might be on an old version of WPGraphQL? 

Your code also looks like it's returning a `Taxonomy` type and not a Term type: `\WPGraphQL\Types::list_of(\WPGraphQL\Types::taxonomy())` That `taxonomy` Type is the actual Taxonomy definition, not a Term definition

**Comment by joshglenn** [comment]
Thank you @renatonascalves and @jasonbahl ,  I am using that plugin now. It works much better.

I'm using the master branch, I think it is the most recent. Kind of a moot point now, `wp-graphql-woocommerce` is a much more mature solution. Thanks again!

**Comment by jasonbahl** [comment]
Going to close this issue in favor of following the `wp-graphql-woocommerce` project here: https://github.com/kidunot89/wp-graphql-woocommerce

**Comment by joshglenn** [comment]
Yes, thanks for the tip. `wp-graphql-woocommerce` works great and is a much more complete solution
