### ISSUE TITLE
menuItem cssClasses is always null

### ISSUE THREAD

**Issue by drewbaker** [wp-graphql/wp-graphql#839]
When doing the below query, `cssClasses` is always null, even if a class is specifically set in the menu under `Appearance > Menus` in WordPress dashboard.

```
query GET_MENU($location: MenuLocationEnum) {
    menuItems(where: { location: $location }) {
        nodes {
            label
            cssClasses
            target
            url
        }
    }
}
```

**Comment by jasonbahl** [comment]
@drewbaker Just opened a PR to address this. Silly typo 🤦‍♂
