### ISSUE TITLE
Provide a way to clear the cached Schema.

### ISSUE THREAD

**Issue by kidunot89** [wp-graphql/wp-graphql#846]
**Description**
In the event that a new type is created dynamically after the schema is established, for instance a new `term` or `post_type` is defined for use in a test, and function is needed to set `WPGraphQL::schema` to `null` before the next `graphql()` call.

**Solution**
I propose a `WPGraphQL::clear_schema()` be added. It should be static obviously.

**Comment by jasonbahl** [comment]
@kidunot89 we both burned some time on this and got nowhere. 😭 

I think we have workarounds for this though re: testing bootstrapping. If this comes back up as a pain point, we can try and take another stab and re-open, or open another issue.

**Comment by jasonbahl** [comment]
@kidunot89 re-opening. I got burned by this again working on some tests for the ACF plugin.

**Comment by jasonbahl** [comment]
I also did a bit of work to dive in again and have some progress. 

I'm able to now register a post_type in the setUp method of a file, or within the test method directly, then query against it. 

However, the way I have this working breaks pretty much everything else in the plugin. 😂 

So, now that I understand it _can_ be done and that it's not a specific WP + Codeception issue, I can at least address it now. 

Hope to have this resolved tomorrow 🤞

**Comment by jasonbahl** [comment]
Closed. This was resolved by v0.4.0
