### ISSUE TITLE
"id" is only parameter for category and tag queries. Need at least "slug", "taxonomyId", "first", "after" and "hasNextPage"

### ISSUE THREAD

**Issue by paulisloud** [wp-graphql/wp-graphql#851]
When trying to query the posts in a category, something like this seems to be the only query possible (based on the available parameters from the schema):

```gql
query GET_CATEGORY($id:ID!) {
  category(id:$id) {
    name
    posts {
      pageInfo {
        hasNextPage
        endCursor
      }
      edges {
        cursor
        node {
          title
        }
      }
    }
  }
}
```

To have this be a meaningful part of the schema, I need to be able to specify:
* The `slug` of the category I want
* Or, it's `taxonomyId` (or something similar)
* `first` to specify how many posts I want back
* and `after`

While I can query the fields of `hasNextPage` and `endCursor`, I can't do anything with them since `after` is not an available input to the query. Also, `hasNextPage` is returning `false` for a category that does indeed have more than 10 posts.

This query returns just the first 10 posts, and as things presently stand, no possibility to do a follow-up query to return more / different data.

Perhaps I am overlooking another Type to be querying, but at present, am I correct in assuming that this part of the schema is still yet to be developed?

**Comment by CodeProKid** [comment]
There are other ways to achieve this with a different query. Could just be a documentation issue.

**Comment by jasonbahl** [comment]
Closing this as there are many ways to achieve this now. 

For example: 

```graphql
{
  termNode(id: "uncategorized", idType: SLUG, taxonomy: CATEGORY) {
    __typename
    name
    id
  }
  category(id: "dGVybTox") {
    name
    id
    databaseId
  }
  categoryByDatabaseId: category(id: 1, idType: DATABASE_ID) {
    name
    __typename
  }
}
```

In action:

![Screen Shot 2020-06-24 at 8 30 23 PM](https://user-images.githubusercontent.com/1260765/85646537-8f417e00-b659-11ea-8d2b-79c1a91f8cd3.png)
