### ISSUE TITLE
wp-graphql-jwt-authentication plugin doesn't work after upgrading from 0.2.3 -> 0.3.3?

### ISSUE THREAD

**Issue by jkhaui** [wp-graphql/wp-graphql#854]
Hey,

Top job so far on development of the WP GraphQL plugin, it's coming along really well.

I've been using the WP GraphQL JWT Auth plugin alongside it and it's been fine for a while (been using it with the WP GraphQL 0.2.3 release). 
However, as soon as I updated to 0.3.3 JWT auth no longer works. I get the "No user was found with the provided ID" error when querying the logged-in user, which used to work fine with 0.2.3. Any ideas?

Thanks!

**Comment by jasonbahl** [comment]
Ah ya. The fix has been merged over on the JWT plugin. I’ll go do a release now.

**Comment by jasonbahl** [comment]
Pushed the release: https://github.com/wp-graphql/wp-graphql-jwt-authentication/releases/tag/V0.3.2
