### ISSUE TITLE
Make PHP Composer dependencies work with PHP 7.0+

### ISSUE THREAD

**Issue by mngi-arogers** [wp-graphql/wp-graphql#865]
Travis should run tests on PHP 5.6 and PHP 7.X, however Travis is only running tests on PHP 7.X because some PHP Composer dependencies require PHP 7.1 or newer. Here is one example:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/inflector v1.3.0 -> satisfiable by doctrine/inflector[v1.3.0].
    - doctrine/inflector v1.3.0 requires php ^7.1 -> your PHP version (5.6.39) does not satisfy that requirement.
```

The PHP Composer dependencies will need to be modified or managed for Travis to run tests on PHP 5.6 and PHP 7.X.

Please see this link for more information:
https://github.com/wp-graphql/wp-graphql/pull/860#issuecomment-494159436

**Comment by CodeProKid** [comment]
This can probably get closed since we aren't going to support 5.6 anymore.
