### ISSUE TITLE
Registering $option_group name with underscores causes bugs when querying settings groups and fields.

### ISSUE THREAD

**Issue by sbarry50** [wp-graphql/wp-graphql#869]
Currently unable to provide multi-word WordPress `$option_group` names in snake case as demonstrated in the WordPress & WPGraphQL docs without a few bugs.

1) Unable to query setting fields in a custom settings group unless the `$option_group` name was registered as a single word.
2) Querying setting fields with `allSettings` works, however the naming convention is mixed. For example, if the registered `$option_group` is `my_options_group` and `$option_name` is `my_option_name`, the resulting setting name to query with would be `my_options_groupSettingsMyOptionName`. I'm not sure if this is intended but it doesn't feel right. One would expect it to be all camel case `myOptionsGroupSettingsMyOptionName`.

I was able to fix this by converting the variables containing the group name to camel case in TypeRegistry.php, line 138 and Settings.php, line 30. And then converting the group name back to snake case in DataSource.php in `function get_setting_group_fields($group)`. This fix only works if the `$option_group` is registered in WordPress in snake case though. Registering them in camel case still produces the first bug described above.

I can try to submit a pull request if you'd like. I've never contributed to a project before so I figured it might be safer just to create an issue first and I wasn't sure if this was the best way to go about fixing it.

**Comment by jasonbahl** [comment]
@sbarry50 ya, opening an issue first was good. Thanks!

Ya, the "standard" for field names is `snakeCase`, so I would agree that `myOptionsGroupSettingsMyOptionName` should be the fieldName based on what you've described. 

A user should be able to register the group as `my_options_group` and it should become `myOptionsGroup{$settingName}`. . .so somewhere we're not properly converting to snakeCase. 

I'm open to a PR if you have time to address. 😄 

Happy to chat more too if needed to get to the right spot with this.

**Comment by sbarry50** [comment]
Thanks @jasonbahl . Submitted a PR. Let me know if I need to change anything.

**Comment by jasonbahl** [comment]
closed by #870
