### ISSUE TITLE
Deregister mutations

### ISSUE THREAD

**Issue by hsimah** [wp-graphql/wp-graphql#878]
I saw this come up in Slack this week - the ability to remove mutations from the schema.

I have several 'create only' post types and would benefit from deregistering the update mutations that are created when `show_in_graphql` is true.

I haven't looked where this would go - I know fields are deregistered in the `WPObjectType`. If someone points me to where the hook should be applied I can whip up a PR.

**Comment by jasonbahl** [comment]
@kidunot89 and I have been chatting about how to make the `register_post_type` and `register_taxonomy` args more flexible for situations like this. 

Currently we support `show_in_graphql => true/false`, `graphql_single_name` and `graphql_plural_name`. 

But to this point, I think we might want more flexibility like: 

```
'graphql' => [
  'single_name' => 'example',
  'plural_name' => 'examples',
  'single_root_field' => true/false,
  'connection_root_field' => true/false,
  'create_mutation' => [
    'show_in_schema' => true/false,
    'capability' => 'some-custom-cap',
  ],
  'update_mutation' => [
    'show_in_schema' => true/false,
    'capability' => 'edit-posts', 
  ],
  'delete_mutation' => [
    'show_in_schema' => true/false,
    'capability' => 'manage-options', 
  ],
]
```

^ That is an _idea_ not necessarily a spec we need to follow. Just a thought to incite more discussion around what fields might be useful when registering post types/taxonomies, etc

**Comment by CodeProKid** [comment]
@jasonbahl says you should be able to just deregister the mutation field on the root mutation type to achieve this. Though it may be nice to add a wrapper to the `deregister_field()` helper func to handle this specifically for mutations.

**Comment by jasonbahl** [comment]
Closing this. We will track in #874
