### ISSUE TITLE
Unknown Argument "where" on field "menu" of type RootQuery

### ISSUE THREAD

**Issue by SilvanTheuma** [wp-graphql/wp-graphql#880]
Trying to query a menu using REST with the `menu(where: {id: 1})` gives the error `Unknown Argument "where" on field "menu" of type RootQuery.` This can also be replicated on the docs site for wpgraphql. The below link should show you this. 

https://docs.wpgraphql.com/getting-started/menus

**Actual Result:** `Unknown argument "where" on field "menu" of type "RootQuery".`
**Expected Result:** The data for the single menu should be returned.

**Comment by Kainkainkain** [comment]
I am having the same issue using the code provided on the website link above. 
I'm not using REST thought (typo from Silvan?) but the GraphiQL. 

In fact several examples don't work in the documentation but I have found code online for general graphql that does work. Usually when trying WHERE type options...

**Comment by jacobarriola** [comment]
@SilvanTheuma @Kainkainkain I ran into this issue as well. It seems as though the API change recently.

This worked for me: `menu( id: 'abx123')`

And to get the ids of all of your menus:

```graphql
menus {
    edges {
      node {
        id
      }
    }
  }
```

So once you have a given `id`, the query should be:

```graphql
{
  menu(id: "TWVudTo1MTQ=") {
    name
    slug
    menuItems {
      nodes {
        label
      }
    }
  }
}
```

**Comment by jasonbahl** [comment]
Ah, ya, the docs have a mistake. As @jacobarriola pointed out it should be `{ menu( id: "..." ) { `

There is an open issue to be able to query single nodes by other fields as well: https://github.com/wp-graphql/wp-graphql/issues/263

That issue _probably_ needs to be broken up into an issue per type, but it would be good to support fetching single menus by any unique identifier, not _just_ the Relay Style global ID

**Comment by jasonbahl** [comment]
I just PR'd a change to the docs as well. 

Going to close this as the docs have been updated, and there's already an open issue to address fetching single nodes by more than just the ID.
