### ISSUE TITLE
WP GraphQL breaks when adding an empty layout inside a flexible content field.

### ISSUE THREAD

**Issue by MihaiAlexP** [wp-graphql/wp-graphql#881]
Steps to reproduce:

Create a Flexible Content type field.
Add a new Layout under it (without adding a nested field in the Layout).
Hit Update.

/graphql
Server error: 
500

FE error:
The site is experiencing technical difficulties.

If adding a field under the layout is mandatory, it would be great if there's a message saying that.

**Comment by jasonbahl** [comment]
@MihaiAlexP thanks for reporting this! Looking into it.

**Comment by CodeProKid** [comment]
This should be moved to the ACF repo
