### ISSUE TITLE
Feature request and bug: Query current user data always return NULL

### ISSUE THREAD

**Issue by mihazs** [wp-graphql/wp-graphql#884]
Hello, i need to query current user data. And i don't want to store user data when login was done, i want independent components in React and more stateless as possible. 
So, it's good to have a way to query which user is logged in, without to make login again.
For my case, i want a component that display user name, user avatar, user email, and other things.
i've tried this, but i don't have success (even using `wp_get_current_user()`), in this case, viewer attribute of the context are always null. And when the id is different of null (using `wp_get_current_user()`), the return is always null.
```php
    register_graphql_field( 'RootQuery', 'me', [
        'type' => \WPGraphQL\Types::user(),
        'resolve' => function( $root, $args, $context, $info ) {
           

          return \WPGraphQL\Data\DataSource::resolve_user($context->viewer->ID, $context);
        }
    ]);
```
It's  cool to have that in WPGraphQL core. 
And, how can i resolve that in my case?

EDIT:
I have tested, and if i do a simple query for user, i always get null:
```graphql
query{
  user(id: 1) {
    name
  }
}
```
results:
```json
{
  "data": {
    "user": null
  }
}
```

**Comment by mihazs** [comment]
i use viewer query and now it works

**Comment by jkhaui** [comment]
@mihazs Hey, can you explain how you solved this? I'm having the same issue. Thanks

**Comment by mihazs** [comment]
> @mihazs Hey, can you explain how you solved this? I'm having the same issue. Thanks

I used the viewer query instead of create a new one. Check the WPGraphiQL

**Comment by acafourek** [comment]
For those who might come upon this thread as I did, the "viewer query" being referred to is, I believe, the example given for how to use the WPGraphQL JWT plugin you will find here:
https://github.com/wp-graphql/wp-graphql-jwt-authentication

Essentially, you cannot fetch details about a user unless your request is authenticated, so you need to include credentials with your query for users. An anonymous query will return null data but if you are authenticated (and have the right permissions), you'll get what you're looking for.
