### ISSUE TITLE
User and Customer don't share the same ID

### ISSUE THREAD

**Issue by rotexhawk** [wp-graphql/wp-graphql#886]
I am using this plugin and the recommended woocommerce plugin. The problem is that `ids` don't match so when a user logs in I save their id and when they are ready to checkout I query for `customer(id: ID)` but the problem is that these id's don't match. If you provide the default db id's graphql complains. Shouldn't they share the same ids? 

Here is the result of the queries. 

```
"data": {
    "customers": {
      "nodes": [
        {
          "email": "test@test.com",
          "username": "test",
          "id": "Y3VzdG9tZXI6Mg==",
          "customerId": 2
        },
```

 ```
"users": {
      "nodes": [
        {
          "email": "test@test.com",
          "username": "test",
          "id": "dXNlcjoy",
          "userId": 2
        },
```

**Comment by renatonascalves** [comment]
The `userId` and `customerId` are both 2. So I guess they are the same. I'm not sure what ID this `id` is referring to...

**Comment by renatonascalves** [comment]
Bear in my that WooCoomerce has guest customers which are not regular WP user. So they don't have regular user ID.

**Comment by rotexhawk** [comment]
The problem is that `wp-graphql` query for customer only accepts the `relay id`. For guest checkout it's ok because the user won't be logged in anyways. In wordpress when a logged in user places an order, their information will be auto-populated in the checkout page. Currently that's not possible with wp-graphql and this plugin because the `relay ids` don't match and `wp-graphql` doesn't accept the `wordpress ids as query parameters`.

**Comment by CodeProKid** [comment]
This is somewhat related to #997 / #998, though I think the change ultimately needs to happen in the WooCommerce plugin since the customer query @rotexhawk is referring to resides in that extension.

**Comment by jasonbahl** [comment]
@kidunot89 closing this as this is something to address or document in the WPGraphQL for WooCommerce repo. 

If you have thoughts on how to better address it with APIs, etc in the core WPGraphQL repo, let's open another issue to discuss.
