### ISSUE TITLE
Ability to filter which image sizes are returned in MediaDetails

### ISSUE THREAD

**Issue by esamattis** [wp-graphql/wp-graphql#889]
Use case: I need to render list of items that have images associated with them and I need to use the `medium` sized image.

I can get the sizes for each item with the following query

```graphql
          images {
            sourceUrl
            mediaDetails {
              sizes {
                name
                sourceUrl
              }
            }
          }
```

Unfortunately this results in serious over fetching because every image can have over dozen different sizes.

I'd like be able to filter the returned sizes.

Eg.

```graphql
sizes(sizes: ["thumbnail", "medium"]) {
  name
  sourceUrl
}
```

**Comment by epeli** [comment]
Quick userland implementation

```php
	register_graphql_field( 'MediaDetails', 'filteredSizes', [
		'type' => 'string',
		'description' => 'sadsf',
		'type' => [ 'list_of' => 'MediaSize' ],
		'args' => [
			'sizes' => [
				'type' => [
					'list_of' => 'String',
				],
			],
		],
		'resolve' => function ( array $media_details, array $args ) {

			$requested_sizes = ! empty( $args['sizes'] ) ? $args['sizes'] : null;

			if ( ! empty( $media_details['sizes'] ) ) {
				foreach ( $media_details['sizes'] as $size_name => $size ) {
					if ( null === $requested_sizes || in_array( $size_name, $requested_sizes ) ) {
						$size['ID']   = $media_details['ID'];
						$size['name'] = $size_name;
						$sizes[]      = $size;
					}
				}
			}

			return ! empty( $sizes ) ? $sizes : [];
		},
	] );
```

![image](https://user-images.githubusercontent.com/225712/60170252-c3991900-9810-11e9-9728-cc46fa694956.png)

**Comment by CodeProKid** [comment]
I think this would be a nice addition. FWIW I implemented this on my custom GraphQL implementation, and I think it makes a lot of sense. Doing this as field inputs let you keep your query static, and then depending on which component will be outputting the images, they can declare the sizes you actually need.
