### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#893]
Opening this issue to discuss making the WPGraphQL Documentation better.

**Comment by jkhaui** [comment]
Would love to help out if I can. I'm building a large-scale React app which uses Apollo client-side, and WP-GraphQL as a server for authentication (using your graphql-jwt plugin) as well as letting users manage their profile and storing custom post types. PHP is not my strength but perhaps I could contribute some client-side examples of interacting with the WP-GraphQL endpoint.

**Comment by jasonbahl** [comment]
@jkhaui client side examples are great! We do have this repo if you want to contribute there: https://github.com/wp-graphql/examples

Or if you are interested in writing tutorials on wpgraphql.com, that would be sweet too!

**Comment by simonh1000** [comment]
Would love to see the addition of how to use standard graphiql (not wordpress plugin) with this

**Comment by jasonbahl** [comment]
@simonh1000 hey! There are many versions of GraphiQL and many other GraphQL IDEs. 

I’ve listed some here: https://docs.wpgraphql.com/getting-started/interacting-with-wpgraphql

I also have an embedded version of the raw GraphiQL component on that page with tooltip guides that walk through usage. That component usage is documented in the GraphiQL component repo here: https://github.com/graphql/graphiql/tree/master/packages/graphiql

If there are critical details you think should be included in our docs I’m open to considering it, but I think if there are questions on using a 3rd party tool, their docs should provide instructions on usage. We can support docs for WPGraphiQL because it’s a tool we maintain and can properly support, but it’s difficult to maintain docs for external tools we don’t maintain. 

Let me know what you feel like should be included in our docs aside from what we have currently. 

Thanks!

**Comment by simonh1000** [comment]
Sorry, not sure why I was so alergic to the wordpress plugin - now that i've found it it seems to do all I need

**Comment by jasonbahl** [comment]
Someone asked in Slack about what mutations are added to the Schema when a Post Type is registered to `show_in_graphql`. It would be good to expand on what happens when you add a post_type to GraphQL.

**Comment by jasonbahl** [comment]
@TylerBarnes didn't we say at WCUS that we should close this as it's too general and not actionable? I suppose we could use it to remind us to do a Documentation audit that leads to actionable issues being opened? 🤷‍♂

**Comment by CodeProKid** [comment]
lol, this should definitely get closed for more specific issues. This issue is offensively vague 😆
