### ISSUE TITLE
Get nodes of any type by URI

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#899]
See: https://github.com/wp-graphql/wp-graphql/pull/715#issuecomment-478086104

---

The concept here is that any node with a URI (post, page, cpt, tag, category, custom tax, user, anything else with a public URI) should be able to be fetched by URI in a union query

Something like:

```
{
  nodeByUri( uri: "/path/to/thing" ) {
     __typename
    ...on Post {
        id
        title
     }
     ...on User {
        id 
        firstName
        lastName
     }
  }
}
```

**Comment by CodeProKid** [comment]
I am _very_ curious what this is going to look like on the backend to relate uri paths to entities across types, seems like something that will get messy pretty quick. I definitely see the utility of this, but implementation will be tricky.

**Comment by jasonbahl** [comment]
Ya, I mean WordPress does this already when you enter a URL in the web browser and the appropriate template is returned to you, so I imagine there are some common functions in WordPress we can use, either directly or as inspiration to handle it. 

This would assume that the input matches the permalink structure set in WordPress. You couldn't have a different permalink structure set by, say, Next.js that doesn't match the WP Permalink structure.

**Comment by taraschi** [comment]
I have a need for something similar to this and did some investigating because `uri` was not behaving as I was expecting.

I think the weirdness here is WordPress's concept of `uri`, which is essentially just `post_name` if the post type is not hierarchical. 

WP maintains unique `post_name`s in a post type unless it is hierarchical, so `uri` is not guaranteed to be unique across post types.

Because of the above I'm not sure querying by `uri` across types would make sense, it would probably need to be a new property like `path` that is essentially the permalink of the object.

Querying by `path` would be relatively easy to do using WP's `url_to_postid` function.

**Comment by luishdz1010** [comment]
I have a version of this on production for several months now. My use case is having 0% routing logic on the frontend, instead, the frontend forwards all requests as-is to WP and is ready to handle any possible object returned. This works only for Posts currently, as I haven't had the need to extend it for anything else. 

Here is the gist of it:

```php
 function content_by_uri( string $uri ) {
        // Save these because we need to override them
        [ $path_info, $request_uri, $wp ] = [ $_SERVER['PATH_INFO'] ?? null, $_SERVER['REQUEST_URI'], $GLOBALS['wp'] ];

        // This is dirty, but this is the way WordPress itself resolves URLs, the WP class IS a big router...
        // which gives us a "native" router experience 
        $router = new WP();

        // Set up our "contained" global environment 
        $GLOBALS['wp']          = $router;
        $_SERVER['PATH_INFO']   = '';
        $_SERVER['REQUEST_URI'] = $uri;
        $old_get                = $_GET;

        $parsed_qs = [];

        $url_parts = \explode( '?', $uri );

        if ( ! empty( $url_parts[1] ) ) {
            parse_str( $url_parts[1], $parsed_qs );
        }

        $GLOBALS['_GET'] = $parsed_qs;

         // Run the routing algorithm
        $router->parse_request();

        // Use a local WP_Query with $router->query_vars which has all the logic to return a valid post embeded
        $query = new WP_Query();
        $query->query( $router->query_vars );
        $maybe_post = $query->get_queried_object();

       // Restore the global env
        [ $_SERVER['PATH_INFO'], $_SERVER['REQUEST_URI'], $GLOBALS['wp'], $GLOBALS['_GET'] ] =
            [ $path_info, $request_uri, $wp, $old_get ];

        if ( $maybe_post instanceof WP_Post ) {
                return new WPGraphQL\Model\Post($maybe_post); 
        }
       
        // handle other cases...
        
        throw new UserError(...);
    }
```

This is not the exact version I'm running, I have a special case there for CMS-side preview support, which works nicely thanks to the usage of the native WP class.

**Comment by jasonbahl** [comment]
@luishdz1010 @taraschi I've been working on this in the upcoming v0.6.0 release. 

My current implementation is kinda gnarly as it re-uses a LOT of the WP class, but in a way the WP class wasn't specifically designed for. I want to spend time cleaning that part up, but wanted to get things working first. 

You can read more about how things are working here: https://github.com/wp-graphql/wp-graphql/pull/1086#issue-355361386

**Comment by jasonbahl** [comment]
Closing this as a dupe of the work being done in #263
