### ISSUE TITLE
Unable to create mutation with same name as previously deregistered mutation

### ISSUE THREAD

**Issue by mlipscombe** [wp-graphql/wp-graphql#903]
Deregistering a mutation via `deregister_graphql_field('rootMutation', 'createPost')` does not fully remove the mutation.  Creating a new mutation via `register_graphql_mutation('createPost', array())` continues to use the previous mutation's input fields.

**Comment by CodeProKid** [comment]
I'm pretty sure this was a known thing. Is this something that was fixed in a recent release @jasonbahl ?

**Comment by jasonbahl** [comment]
I've replicated this issue. We should add a `deregister_graphql_mutation()` API that cleans up the mutation field, but also cleans up the registered mutation Types. 

Closing as it's duplicate of: #874 #878 and I we'll track in #874
