### ISSUE TITLE
Cache-Control: no-cache, must-revalidate

### ISSUE THREAD

**Issue by betweenbrain** [wp-graphql/wp-graphql#904]
With the current _develop_ branch installed, and previously with v0.3.2, responses include a header of `'Cache-Control: no-cache, must-revalidate, max-age=0'`. This prevents the browser from caching the response and thus fetching data every time the page is loaded.

I would think we would want it to be something along the lines of `* Cache-Control: public, max-age=300` so that the browser caches the response, or somehow make this header configurable.

**Comment by jasonbahl** [comment]
@betweenbrain hey! 

WPGraphQL sends the no-cache headers for authenticated requests. You can see where that's set here: https://github.com/wp-graphql/wp-graphql/blob/develop/src/Router.php#L222-L227

If the request is authenticated (`is_user_logged_in()`) then the requests are not cached.

If you prefer to not send those headers, you can use the `graphql_send_nocache_headers` filter and make it false and the nocache headers won't be sent.

If you want to adjust the value of the headers, you can use the WordPress core filter within the `wp_get_nocache_headers()` function: https://developer.wordpress.org/reference/functions/wp_get_nocache_headers/

That filter is: `nocache_headers` and you can see it here in WordPress core: https://core.trac.wordpress.org/browser/tags/5.2/src/wp-includes/functions.php#L1277

--- 

I'm going to close this, as I believe there are sufficient filters for you to accomplish what you're after, but if you believe there's still something missing or something blocking you, let me know.

**Comment by betweenbrain** [comment]
Awesome, thanks @jasonbahl!

**Comment by betweenbrain** [comment]
Hey @jasonbahl,

Thanks again! Do you think that it would make sense to send a header like `Cache-Control: public, max-age=300` if `graphql_send_nocache_headers` is set to false? Looking at https://github.com/wp-graphql/wp-graphql/blob/70134e4ca3c3a13bdf6d80cf93b68fd687c69660/src/Router.php#L200-L227, it seems that `Cache-Control` isn't sent if this is the case.

For the sake of documenting this, does the following seem like the best approach to add this header for now?

```
add_filter( 'graphql_send_nocache_headers', false );

add_filter( 'graphql_response_headers_to_send', function($headers){
	$headers['Cache-Control'] = 'public, max-age=300';

	return $headers;
}, 1, 4 );
```

**Comment by ltroya-as** [comment]
Hello @betweenbrain, 

did you find a solution for this? If I use the `graphql_send_nocache_headers` filter I received a CORS error.
