### ISSUE TITLE
Cannot query hierarchical taxonomy children while querying the connected post type too

### ISSUE THREAD

**Issue by epeli** [wp-graphql/wp-graphql#905]
Steps to reproduce 

Add following taxonomy

```php
add_action('init', function() {
	register_taxonomy('test', 'page', [
		'hierarchical' => true,
		'label' => __( 'Test' ),
		'show_ui' => true,
		'show_in_graphql' => true,
		'graphql_single_name' => 'test',
		'graphql_plural_name' => 'tests'
	] );
});
```

Create parent and child terms

![image](https://user-images.githubusercontent.com/225712/61213330-6ad0e800-a70d-11e9-8e9a-5f4371327217.png)

You should be able to query the child:

![image](https://user-images.githubusercontent.com/225712/61213362-84722f80-a70d-11e9-8d42-c70ebf7ab6ab.png)

But convert the query to 

```graphql
{
  tests {
    nodes {
      children {
        nodes {
          name
        }
      }
    }
  }
  pages {
    nodes {
      title
    }
  }
}
```

And the result from term children disappears:

![image](https://user-images.githubusercontent.com/225712/61213422-abc8fc80-a70d-11e9-9c1c-5a604a071144.png)

If unrelated post type is queried the children query works again:

![image](https://user-images.githubusercontent.com/225712/61213469-cd29e880-a70d-11e9-9f65-e56cd46a2132.png)

I'm using the current `develop`(0d4409fc942788ca090e050e60cf12a2e244562c) branch from wp-graphql without other plugins

**Comment by epeli** [comment]
When there's no `pages` query the generated SQL is like this

```sql
SELECT t.term_id,
       tt.parent,
       tt.count,
       tt.taxonomy
FROM wp_terms AS t
INNER JOIN wp_term_taxonomy AS tt ON t.term_id = tt.term_id
WHERE tt.taxonomy IN ('test')
  AND tt.parent = '102'
ORDER BY t.name ASC
```

But when the pages query is added the query becomes


```sql
SELECT t.term_id,
       tt.parent,
       tt.count,
       tt.taxonomy
FROM wp_terms AS t
INNER JOIN wp_term_taxonomy AS tt ON t.term_id = tt.term_id
INNER JOIN wp_term_relationships AS tr ON tr.term_taxonomy_id = tt.term_taxonomy_id
WHERE tt.taxonomy IN ('test')
  AND tr.object_id IN (399)
  AND tt.parent = '102'
ORDER BY t.name ASC
```

**Comment by epeli** [comment]
This is related to `setup_postdata()` again.

The query gets modified because `object_ids` is set for `WP_Term_Query` here:

https://github.com/WordPress/WordPress/blob/820ce9c438eb0817a30335acfeecba82bd524c2c/wp-includes/class-wp-term-query.php#L639-L641


And `object_ids` gets set because global post is present here

https://github.com/wp-graphql/wp-graphql/blob/0d4409fc942788ca090e050e60cf12a2e244562c/src/Data/Connection/TermObjectConnectionResolver.php#L134-L136

So my guess is that the `pages` query sets the global post to something and does not clear it up afterward it's done.

Currently the global post is reset after the full graphql query has finished:

https://github.com/wp-graphql/wp-graphql/blob/0d4409fc942788ca090e050e60cf12a2e244562c/src/Request.php#L147-L150

Maybe this could be solved by moving the reset after each root query has been done so it wouldn't leak to other queries.

**Comment by jasonbahl** [comment]
@epeli I think this is related to: https://github.com/wp-graphql/wp-graphql/issues/887

See my comment on that issue here: https://github.com/wp-graphql/wp-graphql/issues/887#issuecomment-508808865

----

I think the problem is more about my naiive Schema design, which you can read about more in that comment. 

Happy to elaborate more if needed.
