### ISSUE TITLE
Feature Request: Relative Permalink URLs

### ISSUE THREAD

**Issue by JeffMatson** [wp-graphql/wp-graphql#912]
Support for getting a relative path to a post's permalink would be helpful.

A use-case would be headless WordPress sites that want to share a permalink configuration.

The `link` field on posts essentially does this, but requires additional manipulation after the data is retrieved to make it relative.

This could either be done as its own field, such as `path` or as an argument inside the `link` field, such as `link(relative: true)`.

**Comment by CodeProKid** [comment]
Definitely seems like a useful feature, need to flesh out implementation details on this.

**Comment by jasonbahl** [comment]
Closed by #1112 

There is now a `UniformResourceIdentifiable` Interface applied to all Post Object Types, Term Types and the User Type. 

Each of these types has a `uri` field which returns a relative path that can be used to identify the resource. 

See this in action:

![Screen Shot 2020-01-13 at 10 00 31 PM](https://user-images.githubusercontent.com/1260765/72315572-7bc4cc80-3650-11ea-8b88-4b4e6380ea37.png)

We can then use those paths in return by querying resources by their uri. See that in action:

![Screen Shot 2020-01-13 at 10 02 58 PM](https://user-images.githubusercontent.com/1260765/72315581-8a12e880-3650-11ea-857c-6b9e74f3340e.png)
