### ISSUE TITLE
Authentication succeeds without nonce (CSRF vulnerability)

### ISSUE THREAD

**Issue by amanning11** [wp-graphql/wp-graphql#916]
Hi,

I recently started playing with this plugin and noticed that the documentation seems incorrect.
It states that a nonce is required to authenticate with wpGraphQL (like the WP REST API) when making an xhr request from within WordPress.

I've found that simply providing the WP authentication cookie in the request header is sufficient to authorise. No nonce is required, leading to a CSRF vulnerability.

![image](https://user-images.githubusercontent.com/32957675/61882058-fc074200-aef7-11e9-871b-44d0eeeb018a.png)

![image](https://user-images.githubusercontent.com/32957675/61882094-10e3d580-aef8-11e9-8272-205fb3c6ce1a.png)

Notes:
wp-graphql v0.3.4
WordPress 5.2.1

**Comment by jasonbahl** [comment]
Thanks for reporting. I have a fix in progress for this. Should have a PR for it within a day or two. 

Thanks!

**Comment by jasonbahl** [comment]
@amanning11 Have you tried this with mutations such as creating posts?

Users (that have published posts) are considered public entities in WordPress. You don't need to be authenticated to see users in WordPress using REST or just browsing a site. WPGraphQL behaves the same. 

I've attempted using the "cookie" auth method as described above, and I'm not able to create data using mutations or read private data, such as users that are not published authors, or sensitive fields such as user email addresses. 

Can you try with an operation that actually is trying to access protected data? Something like:

```
{
  generalSettings {
    email
  }
}
```

or:

```
{
  users {
     nodes {
        id
        name
        email
     }
  }
}
```

**Comment by jasonbahl** [comment]
I don't have evidence that this is an actual issue. The issue was opened querying publicly available data and receiving publicly available data in response. 

If there is more evidence of a CSRF vulnerability we can open another issue with more concrete info to address.
