### ISSUE TITLE
Filter the user model layer to expose users without published posts

### ISSUE THREAD

**Issue by operapreneur** [wp-graphql/wp-graphql#918]
For users that are not logged in, I would like to list out all users on a page even if they have zero published posts. I understand that this request goes against WP security best practices but the site is behind SSO, so security will already be high. If you could provide direction on adding a filter to the model layer it would be greatly appreciated!

**Comment by justlevine** [comment]
I know it's a few years late, but this article walks you through making all users public.

https://www.wpgraphql.com/recipes/make-all-users-public/
