### ISSUE TITLE
Login return 403 error with auth enabled

### ISSUE THREAD

**Issue by webface** [wp-graphql/wp-graphql#922]
I cant log in a user because the auth plugin returns a 403 error for every query or mutation so even though I get an auth token in my payload, I get an error 403

**Comment by jasonbahl** [comment]
@webface can you provide an example of how you're performing the login mutation? Are you sending invalid Authorization headers along with the `login` mutation?

**Comment by webface** [comment]
`import React, { Component } from 'react'
import { Mutation , ApolloConsumer} from 'react-apollo'
import gql from 'graphql-tag'

const LoginUserMutation= gql`
	mutation LoginUser($input:LoginInput!) {
		login( input: $input) {
		authToken
		user {
			id
			name
		}
		}
	}
`; 
class SignUp extends Component {
	state = { 
		username : '',
		email: '',
		password: '',
		confirmpassword: '',
		errors:''
	 }
	createMarkup=(text) =>{
		return {__html: text}
	  }
	handleChange=(e)=>{
        this.setState({
            [e.target.id]:e.target.value
        })
    }

    handleSubmit=(e)=>{
        e.preventDefault();
        console.log(this.state);
    }
	render() { 
		const { username,password,errors} = this.state;
		return (
			<ApolloConsumer>
				{client =>(
						<div className="card center-align">
						<div className="card-content ">
							<form onSubmit={this.handleSubmit}>
								<span className="card-title">Login</span>
								<div className="input-field">
									<input id="username" type="text" value={username} className="validate" onChange={this.handleChange}/>
									<label htmlFor="username">Username</label>
								</div>
								<div className="input-field" >
									<input id="password" type="password" value={password} className="validate" onChange={this.handleChange}/>
									<label htmlFor="password">Password</label>
									
								</div>

								<Mutation
									mutation={LoginUserMutation}
									variables={{input: {
										clientMutationId: "uniqueid",
										username,
										password
									}}}
									onCompleted={({ login }) => {
										this.setState({errors:''})
										console.log(login)
										localStorage.setItem('user', login.user);
										localStorage.setItem('token',login.authToken)
										client.writeData({ data: { isLoggedIn: true } });
										this.props.history.push('/')
									}}
									onError={(({ graphQLErrors, networkError }) => {
										if (graphQLErrors){
											
											graphQLErrors.map(({ message, locations, path },i) =>{
												this.setState({errors:message})
												console.log(
													`[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`,
													)
												return true;
											});
										}
										
									
										if (networkError) console.log(`[Network error]: ${networkError}`);
									})}
								>
								{ LoginUser => 
								<button className="btn blue  waves-effect waves-light" type="submit" name="action" onClick={LoginUser}>Login
								<i className="material-icons right">send</i>
									</button>
								}
								</Mutation>
								<p className="red-text error" dangerouslySetInnerHTML={this.createMarkup(errors)}></p>
							</form>
						</div>   
					</div>
				)}	
				
			</ApolloConsumer> 
			   
		 );
	}
}
 
export default SignUp;`

**Comment by webface** [comment]
`import React from 'react';
import {ApolloClient} from 'apollo-client'
import { ApolloProvider } from 'react-apollo'
import { BrowserRouter, Route, Switch } from 'react-router-dom'
import { InMemoryCache } from 'apollo-cache-inmemory';
import { HttpLink } from 'apollo-link-http';
import Toasters from './components/Toasters'
import Toaster from './components/Toaster'
import './App.css';
import SignUp from './components/SignUp';
import SignIn from './components/SignIn';
import Search from './components/Search';
import NotFound from './components/NotFound'
import { resolvers, typeDefs } from './resolvers';

const cache = new InMemoryCache();

const client = new ApolloClient({
  cache,
  link : new HttpLink({
	uri: 'http://localhost:1018/graphql',
	headers: {
		Authorization: `Bearer ${localStorage.getItem('token')}`,
	  },
  }),
  typeDefs,
  resolvers,
});
cache.writeData({
	data: {
	  isLoggedIn: !!localStorage.getItem('token'),
	},
  });
function App() {
  return (
    <ApolloProvider client={client}>
		<BrowserRouter>
		<header>
			<nav>
					<div className="nav-wrapper blue">
						{/* <img src="img/logo.png" className="logo"> */}
						<a href="/" className="brand-logo">Toasters</a>
						<a href="#!" data-target="mobile-menu" className="sidenav-trigger"><i className="material-icons">menu</i></a>
						<ul className="right hide-on-med-and-down">
						<li><a href="/">Toasters</a></li>
						<li><a href="/search">Search</a></li>
						<li><a href="/signup">Register</a></li>
						<li><a href="login">Login <i className="material-icons left">accessibility</i></a></li>
						<li><a href="#">Logout</a></li>
						{/* <li><img src="img/a03.png" className="circle valign"></li> */}
						</ul>
						
					</div>
				</nav>
				<div className="sidenav" id="mobile-menu">
					{/* <img src="img/a03.png" className="circle">
					<ul className="">
						<li><a href="#">Login</a></li>
						<li><a href="#">Register</a></li>
						<li><a href="#">Dashboard</a></li>
						<li><a href="#">Logout</a></li>
					</ul> */}
				</div>
	</header>    
    
    <main>
		<div className="container content">
			<Switch>
				<Route exact path="/" component={Toasters}></Route>
				<Route path="/toasters" component={Toasters}></Route>
				<Route path="/toaster/:slug" component={Toaster}></Route>
				<Route path="/signup" component={SignUp}></Route>
				<Route path="/search" component={Search}></Route>
				<Route path="/login" component={SignIn}></Route>
				<Route component={NotFound}></Route>
			</Switch>
		</div>
	</main>
    
    <footer className="page-footer blue">
		<div className="footer-copyright">
			<div className="container">
			© 2014 Copyright Text
			<a className="grey-text text-lighten-4 right" href="/">More Links</a>
			</div>
		</div>
	</footer>
		</BrowserRouter>
	</ApolloProvider>
  );
}

export default App;
`

**Comment by webface** [comment]
@jasonbahl 
const token = localStorage.getItem('token');
const client = new ApolloClient({
  cache,
  link : new HttpLink({
	uri: 'http://localhost:1018/graphql',
	headers: {
		authorization: token ? `Bearer ${token}` : ''
	  },
  }),
  typeDefs,
  resolvers,
});
I tried this and cleared local storage. It seems to work for a minute.
[https://www.wpgraphql.com/2019/01/30/preventing-unauthenticated-requests-to-your-wpgraphql-api/](url)
This however is what im trying to do. The token only lasts for 5 mins then its 403 error again

**Comment by webface** [comment]
@jasonbahl I caught up on the gists in the repos. I guess I can always redirect my users to signin or get a new token in case of a 403. I'm looking forward to seeing your dashboard to see your implementation of this in action. This is my first react app and I appreciate the work you have done with wpgraphql
