### ISSUE TITLE
Schema federation

### ISSUE THREAD

**Issue by JakeBeresford** [wp-graphql/wp-graphql#925]
Are there any plans to update the plugin for schema federation? [Apollo have announced schema stitching will be  deprecated in favor of federation](https://www.apollographql.com/docs/graphql-tools/schema-stitching/)

I'm about to start a project which will ideally use federation to combine the WP graph with another graph, im sure others have or will have similar requirements.

**Comment by jasonbahl** [comment]
@JakeBeresford I think it would be great to have WPGraphQL support federation. 

I don't have immediate plans to add support, but I'd be interested in getting this on the roadmap.

If you have ideas on the approach, let's chat! Happy to collaborate on this. I believe @CodeProKid might be interested as well. 

One thought is to make a `wp-graphql-federation` plugin where it can be worked on, so folks using federation can activate that plugin. I'm not opposed to having support in core, but I have a feeling we might see more specs like federation pop up, and WPGraphQL core can't possibly sanely scale to support _all_ specifications in the wild.

**Comment by jasonbahl** [comment]
@JakeBeresford @CodeProKid I created a repo here where we can start working on this feature as a plugin: https://github.com/wp-graphql/wp-graphql-federation

Let's plan features using issues over there and see what we can come up with. 😄
