### ISSUE TITLE
Introduce showInFlatList to Pages, Posts, or Custom Post Types

### ISSUE THREAD

**Issue by henrikwirth** [wp-graphql/wp-graphql#928]
So the default behavior of querying a post or page is to get all root elements, but not their children. Like so:

```
query GET_PAGES {
  pages {
    nodes {
      title
      childPages {
        nodes {
          title
        }
      }
    }
  }
}
```

But what if you want t get all elements, even the children? As @jasonbahl told me, in `categories` the `showInFlatList` argument got introduced. So I suggest the same for this.

Also there is an example here: https://github.com/progital/gatsby-wpgraphql-blog-example/blob/f7695fe41ee40ec98638949d954422d8ad3be743/gatsby/createPages.js#L4-L26

This actually gets you all the elements, even the child-elements. Which doesn't make sense. So the where filter should be checked with this too. I'll split it up in another ticket: #929

**Comment by henrikwirth** [comment]
#534 Here is the related Ticket

**Comment by TylerBarnes** [comment]
This would make things a lot easier on the Gatsby side! Since I'm pulling all top level nodes and then just linking any connected nodes by id, if these could output flat it would mean writing less logic on my side.

**Comment by TylerBarnes** [comment]
I believe the current plan is to do this for menus. It probably makes sense to keep it consistent and do it everywhere

**Comment by jasonbahl** [comment]
Closing this, as the default (as of #1337) will now be to return connections as flat lists, so an argument like this won't be needed. 

Instead, if you prefer to only fetch nodes with a specific parent, you can specify that in the args, othwerwise you'll get all nodes in a flat list.
