### ISSUE TITLE
Move docs back into main repo

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#931]
The docs currently live in the repo here: https://github.com/wp-graphql/docs.wpgraphql.com

Moving the docs back into the main repo will resolve a few things: 

- ties documentation to a specific version of the code
- help encourage more participation with the documentation

**Comment by renatonascalves** [comment]
I wonder how it helps option two since both are on github?

**Comment by jasonbahl** [comment]
@renatonascalves I believe having one repo for folks to contribute to will reduce friction compared to users having to seek out an additional repo. 

As new features are added and bugs are fixed, I think having the docs in the same repo will encourage contributors to update the docs at the same time they PR their bugfix/new feature, similar to tests. Not everyone contributes tests with their PRs but if they had to go to another repo to contribute tests I believe it would decrease contributions to tests.

**Comment by jasonbahl** [comment]
closed by #981
