### ISSUE TITLE
Move WPGraphiQL into the main WPGraphQL repo

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#932]
Currently WPGraphiQL lives in a separate repo here: https://github.com/wp-graphql/wp-graphiql. 

Most GraphQL libraries (Apollo, GraphQL Express, Gatsby, etc) all ship with a GraphQL IDE without users having to find another one. 

Having the WPGraphiQL IDE in the main WPGraphQL repo will reduce friction for new (and existing) users, and will encourage more participation in adding features to the WPGraphiQL IDE.

**Comment by henrikwirth** [comment]
I'm not 100% sure why, but I feel it should stay separate, so the user can decide for himself if he wants to have more functionality or not. Kinda separation of concerns as it is nothing you would need to work with WPGraphQL. I would rather like to see it as something that is suggested by the WPGraphQL plugin and that it can easily be installed with one click.

I do understand your point of encouraging more people to contribute, but maybe this could be also done through Documentation and Homepage by making it more visible/obvious.

Well just thinking out loud ...

**Comment by renatonascalves** [comment]
If it can be (de)activated with a `const` or `hook`, I'm all for it! ;)

**Comment by jasonbahl** [comment]
Closed in v0.13.0
