### ISSUE TITLE
Multiple values Post Object ACF field not working

### ISSUE THREAD

**Issue by TheoKoenig** [wp-graphql/wp-graphql#939]
When using a multiple values Post Object ACF field, WPGraphQL return an empty object instead of the list of post objects.
Steps to reproduce:

1. Make a multiple values Post Object ACF field
2. Try to query it

**Comment by jasonbahl** [comment]
Closing as I moved the issue to the WPGraphQL for ACF repo here: https://github.com/wp-graphql/wp-graphql-acf/issues/45
