### ISSUE TITLE
Custom Post Type won't display if parent is not set to 0. 

### ISSUE THREAD

**Issue by BartoszLobejko** [wp-graphql/wp-graphql#941]
Hey, 
I experienced this tricky issue where:

- I have Custom Post Type (Locations) that is not hierarchical
- I used WP Ultimate CSV Importer to get data
- Import is successful but records not display in GraphQL

To resolve the problem you should:

- Make sure that each CPT record has set "Parent Post" set to 0 while importing.
- To achieve that you can manually change post parent or edit Import plugin by hardcoding "0"

I do realise it's not an ideal solution and it's more related to Import plugin, but It might be helpful to someone, especially that it only causes an issue for GraphQL display and not WP post itself.

**Comment by jasonbahl** [comment]
@BartoszLobejko hey, in looking at this, it appears that the WordPress database has the post_parent column set to BIGINT with default of `0` as the value. 

Can you provide info on how the import plugin was setting values for the post_parent? was it setting something other than 0?

**Comment by jasonbahl** [comment]
Related to #929

**Comment by BartoszLobejko** [comment]
@jasonbahl It was set to post id 321 every time I import which is a bit random as it's not any post that exists nor active. (I would expect to be parent post or first post ever created but it's not.) I found in the database it is Menu ID.

**Comment by jasonbahl** [comment]
I'm closing this as I believe the real issue is related to how the data was imported.
