### ISSUE TITLE
Comment Mutations update_additional_comment_data() is empty

### ISSUE THREAD

**Issue by paulisloud** [wp-graphql/wp-graphql#942]
This function should create a hook, i.e.:

```php
public static function update_additional_comment_data( $comment_id, $input, $mutation_name, AppContext $context, ResolveInfo $info ) {
  /**
    * Run an action after the additional data has been updated. This is a great spot to hook into to
    * update additional data related to postObjects, such as setting relationships, updating additional postmeta,
    * or sending emails to Kevin. . .whatever you need to do with the postObject.
    *
    * @param int           $comment_id              The ID of the commentObject being mutated
    * @param array         $input                   The input for the mutation
    * @param \WP_Post_Type $output_args             The Comment Object for the comment being mutated
    * @param string        $mutation_name           The name of the mutation (ex: create, update, delete)
    * @param AppContext    $context                 The AppContext passed down to all resolvers
    * @param ResolveInfo   $info                    The ResolveInfo passed down to all resolvers
    * @param string        $intended_comment_status The intended comment_approved status the comment should have according to the mutation input
    * @param string        $default_comment_status  The default status comments should use if an intended status wasn't set
    */
  $intended_comment_status = 0; // Probably needs to account for authentication
  $default_comment_status = 0;
  do_action( 'graphql_comment_object_mutation_update_additional_data', $comment_id, $input, $output_args, $mutation_name, $context, $info, $intended_comment_status, $default_comment_status );
}
```

Note that `$intended_comment_status` should probably account for authentication (i.e. can only set `1` if logged in), but I'm not sure where that happens in the flow of the plugin, so submitting this as an issue vs. a PR.

**Comment by paulisloud** [comment]
Do you want a pull request with this change? This issue is fairly old and is preventing me from upgrading WP-GraphWL automatically.

**Comment by justlevine** [comment]
@jasonbahl from my understanding of the code ([CommentCreate.php](https://github.com/wp-graphql/wp-graphql/blob/develop/src/Mutation/CommentCreate.php#L190), [CommentUpdate.php](https://github.com/wp-graphql/wp-graphql/blob/develop/src/Mutation/CommentUpdate.php#L133), errors are already thrown if the the user cannot create/update the comment (be it due to permissions or other issues) by the time `CommentMutation::update_additional_comment_data()` gets called.

If so, we can remove the `@todo` and close this.

**Comment by ManishBairwa09** [comment]
Mutations update_additional_comment_data() is empty

**Comment by jasonbahl** [comment]
@ManishBairwa09 can you share more context on what you're trying to accomplish? What are your expectations vs actual behavior?
