### ISSUE TITLE
Support querying multiple post types in PostObjectConnectionResolver

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#944]
Currently, the `PostObjectConnectionResolver` is setup to expect to query just one post_type at a time, as seen here: 

https://github.com/wp-graphql/wp-graphql/blob/develop/src/Data/Connection/PostObjectConnectionResolver.php#L44

You're expected to pass a post_type to the Class, which is set, then used to do validation, such as: 

https://github.com/wp-graphql/wp-graphql/blob/develop/src/Data/Connection/PostObjectConnectionResolver.php#L91

The problem with this, is that for querying multiple post_types, say, for a `search` query, or another custom query that would return a `PostObjectUnion`, the resolver needs to be able to query many post types.

----

### Possible solution

change: https://github.com/wp-graphql/wp-graphql/blob/develop/src/Data/Connection/PostObjectConnectionResolver.php#L44

To set the value as an array.

Then:

When validating like so: https://github.com/wp-graphql/wp-graphql/blob/develop/src/Data/Connection/PostObjectConnectionResolver.php#L91

We could do something like: `if ( in_array( 'revision', $this->post_types ) ) {` and if `revision` is the _only_ post_type, we can prevent execution. If it's one of many, and the user doesn't have caps for it, we can just unset it from the array.

It gets tricky when trying to mix post_types here though: https://github.com/wp-graphql/wp-graphql/blob/develop/src/Data/Connection/PostObjectConnectionResolver.php#L177

Because images and revisions have a different status than most post_types. Will need to explore more with this one.

**Comment by justinwhall** [comment]
I'm assuming the _why_ here is so you could eventually do something like:

```
  allPosts(where: {authorName: "justin"}) {
    nodes {
      id
    }
  }
```

**Comment by TylerBarnes** [comment]
We had a talk in person and we're going to name the type something like `ContentUnion` and the root connection field like `content { nodes {...} }`

**Comment by TylerBarnes** [comment]
Also to return post type data we want `contentTypes { nodes { ... } }`
