### ISSUE TITLE
Allow filtering of query args for User connections

### ISSUE THREAD

**Issue by darylldoyle** [wp-graphql/wp-graphql#945]
Currently, there is the ability to filter the query args for both Posts and Terms using the following filters:

`graphql_term_object_connection_query_args`
`graphql_post_object_connection_query_args`

These are very useful, especially when trying to pull the total number of items a query can return as per the suggestions in #723. 

I'm currently trying to pull the total number of users returned by a query, to do this I need to set `$query_args['count_total']` to `true`. Unfortunately, there's no way to do this as it stands as we can only filter the query args for Posts and Terms.

~~I suggest adding a filter to all connections so that users can adjust those queries as they need.~~

I've looked at the code and it seems that only the User type is missing a filter to do this!

I will open a PR for this shortly 🙂

**Comment by jasonbahl** [comment]
@darylldoyle I believe this filter provides central filtering for all connections query args: https://github.com/wp-graphql/wp-graphql/blob/develop/src/Data/Connection/AbstractConnectionResolver.php#L152

Can you confirm this filter will work? 

I believe the other filters you mention for the term/post connections were left for backward compatibility, but a single central filter, I think makes more sense for maintenance going forward. 

Let me know if that central hook won't work and we can discuss more.

**Comment by darylldoyle** [comment]
@jasonbahl as I mentioned in the PR, this filter works amazingly and it makes complete sense to have a single one rather than one in each. Not sure how I missed it, but thanks for pointing it out 🙂

**Comment by cfxd** [comment]
@jasonbahl thank you for creating and maintaining the outstanding suite of WP GraphQL plugins!

For some reason, no matter what I try, neither of these filters work at all:

`graphql_post_object_connection_query_args`
`graphql_connection_query_args`

I even directly modify the plugin code directly to change `$query_args['posts_per_page']` and > 10 values have no effect in the local WP's GraphiQL or in the remote query. I definitely have > 10 posts and modifying other values (like `$query_args['post_type']`) work as expected. Settings `$query_args['posts_per_page']` to < 10 does work as expected, though.

I searched for WP transients and I don't see evidence of any.

So far this is all being done locally without any additional plugins.

The only step that increases the number of posts retrieved is to add a `first` in my actual remote query or in the GraphiQL UI. Even trying to filter that value doesn't work! I've tried -1, 100, 20, every number I can think of. In fact, the only numbers that have any effect are numbers less than 10, then the behavior is as expected.

I'm running v0.8.1 on WP.

### Am I missing something? This is driving me mad!

Here are the snippets I've used:

```php
function custom_graphql_post_object_connection_query_args($query_args, $source, $args, $context, $info) {
  if(!isset($args['first']) && !isset($args['last'])) {
    $query_args['posts_per_page'] = 20; // <--------tried every possible number there (even without the conditional), seems only numbers less than 10 have any effect
  }
  return $query_args;
}
add_filter('graphql_post_object_connection_query_args', __NAMESPACE__.'\\custom_graphql_post_object_connection_query_args', 10, 5);
```

```php
function custom_graphql_connection_query_args($args, $resolver) {
  $args['posts_per_page'] = 20; // <--------tried every possible number there, seems only numbers less than 10 have any effect
  return $args;
}
add_filter('graphql_connection_query_args', __NAMESPACE__.'\\custom_graphql_connection_query_args', 10, 2);
```

Btw, I also noticed that the query logic won't allow for `posts_per_page => -1`, which WP usually allows retrieving all posts.
