### ISSUE TITLE
Menu Pagination does not work and menu query acts erratically. 

### ISSUE THREAD

**Issue by hybridwebdev** [wp-graphql/wp-graphql#956]
So it seems that the menu query resolver is barely functional. 

Here's my code:

`
query{
	menus(first: 3, after:"") {
	  edges {
	    node {
        name
	    }
	  }
     pageInfo {
       endCursor
       startCursor
     }
	}
}
`

which results in:

`{
  "data": {
    "menus": {
      "edges": [
        {
          "node": {
            "name": "menu 1"
          }
        },
        {
          "node": {
            "name": "menu 2"
          }
        },
        {
          "node": {
            "name": "menu 3"
          }
        }
      ],
      "pageInfo": {
        "endCursor": "YXJyYXljb25uZWN0aW9uOjQ=",
        "startCursor": "YXJyYXljb25uZWN0aW9uOjI="
      }
    }
  }
}`

If you try and use the end cursor for the next page, it does not work, you just get back the same results. In fact, if you inverse the query like so: 

`query{
	menus(last: 3, before:"") {
	  edges {
	    node {
        name
	    }
	  }
     pageInfo {
       endCursor
       startCursor
     }
	}
}`

then you get: 

`{
  "data": {
    "menus": {
      "edges": [
        {
          "node": {
            "name": "menu 3"
          }
        },
        {
          "node": {
            "name": "menu 2"
          }
        },
        {
          "node": {
            "name": "menu 1"
          }
        }
      ],
      "pageInfo": {
        "endCursor": "YXJyYXljb25uZWN0aW9uOjI=",
        "startCursor": "YXJyYXljb25uZWN0aW9uOjQ="
      }
    }
  }
}`

In total I have 10 menus, numbered menu x. If i do first 10 or first 9999 then it lists all 10 menus.

So yeah, seems that the menu query barely works. 

Was using .34, updated to .36 and issue remained. I've tried disabling every single plugin, and several themes including twenty 15, 16, 17, 18 and 19. Please do not suggest it's a plugin or theme conflicting as that's simply not the case. 

*Edit 1* It seems menus are ordered by title. Eg if you have
Menu 1
...
Menu 11

then list shows up as 

Menu 1
Menu 10
Menu 11

*Edit* Post edited to remove sarcasm.

**Comment by ecurtis** [comment]
I can confirm that menu does not behave properly with variables. I noticed that posts do work, perhaps some similar logic needs to be here. Thank you to the maintainers for working on this.

**Comment by hybridwebdev** [comment]
> I can confirm that menu does not behave properly with variables. I noticed that posts do work, perhaps some similar logic needs to be here. Thank you to the maintainers for working on this.
> 
> Update:
> Looks like the MenuConnectionResolver.php file only has basic scaffolding for query parameters, unlike the PostObjectConnectionResolver.php

Adding to this. It seems that unlike with things like post queries where you can do stuff like:
`where: {ids: [1,2,3]}`
you are unable to do so with menus, being forced to query 1 id at a time. This is unfortunate as it means if you're using a dataloader to consolidate queries into 1 query, it's impossible. To elaborate, this means that doing a query for 3 different menus, means 3 different queries.

**Comment by jasonbahl** [comment]
closed by #1348

With this release, the MenuConnectionResolver now makes use of the query args from the parent TermObjectConnectionResolver so pagination is calculated like other terms.

Here's a GIF showing successful pagination in action:

![menu-pagination](https://user-images.githubusercontent.com/1260765/85652951-5e694500-b669-11ea-9251-55ea663af9ef.gif)
