### ISSUE TITLE
How to add custom input fields to existing mutation?

### ISSUE THREAD

**Issue by safouane-ahmed-salah** [wp-graphql/wp-graphql#957]
I would like to add custom input fields to createUser Mutation?

Thanks

**Comment by safwan39** [comment]
I think there should be filter for config mutation in function register_graphql_mutation.

`function register_graphql_mutation( $mutation_name, $config ) {
       $config = apply_filter("graphql_mutation_{$mutation_name}_config", $config);
	\WPGraphQL\TypeRegistry::register_mutation( $mutation_name, $config );
}
`

**Comment by CodeProKid** [comment]
Related: #965

**Comment by johnlund** [comment]
👍

**Comment by jonshipman** [comment]
At the very least a filter around the get_input_fields return in src/Mutation/PostObjectCreate.php

**Comment by maximilianschmidt** [comment]
any update on this issue? i am looking for a way to add a custom field to the `RegisterUserInput`-Type

**Comment by matepaiva** [comment]
any update on this? I think it's a very important issue, and it's easy to solve it with @jonshipman suggestion.

**Comment by SimeonGriggs** [comment]
Is this an actual limitation at the moment? I can't do a createPost mutation including ACF Fields/post meta because I can't find a way to extend the default input object.

**Comment by maximilianschmidt** [comment]
there is a way, @hsimah figured it out and was kind enough to give me an code snippet for this. basically you make use of the [graphql_input_fields](https://www.wpgraphql.com/filters/graphql_input_fields/) filter. Here is an example for adding a custom field "Company" to the UserRegistration-Mutation:

```
add_filter('graphql_input_fields', function($input_fields, $type_name) {
  if ($type_name === "RegisterUserInput") {
    $input_fields['company'] = [
      'type' => 'String',
      'description' => __('A string containing the user\'s company.', 'wp-graphql'),
    ];
  }

  return $input_fields;
}, 10, 2);
```

**Comment by Wali-ur-Rehman** [comment]
> there is a way, @hsimah figured it out and was kind enough to give me a code snippet for this. basically you make use of the [graphql_input_fields](https://www.wpgraphql.com/filters/graphql_input_fields/) filter. Here is an example for adding a custom field "Company" to the UserRegistration-Mutation:
> 
> ```
> add_filter('graphql_input_fields', function($input_fields, $type_name) {
>   if ($type_name === "RegisterUserInput") {
>     $input_fields['company'] = [
>       'type' => 'String',
>       'description' => __('A string containing the user\'s company.', 'wp-graphql'),
>     ];
>   }
> 
>   return $input_fields;
> }, 10, 2);
> ```

@maximilianschmidt thanks, it works.

**Comment by therealgilles** [comment]
What's the correct way to write a new createUser mutation field to user meta?
Would it look like this:

```PHP
        register_graphql_field(
			'createUser',
			'newField',
			array(
				'description' => 'A new user field',
				'type'        => 'String',
				'resolve'     => function( $user, $args, $context, $info ) {
					$field_value = $args['newField'] ?? null;
					if ( $field_value && /* add field validation here */) {
					    return update_user_meta( $user->userId, 'newField', $field_value );
					}
					return null;
				},
			)
		);
```

?

**Comment by therealgilles** [comment]
Never mind, looks like I need to hook into `graphql_user_insert_post_args` and `graphql_user_object_mutation_update_additional_data` instead.

**Comment by justlevine** [comment]
Recommending we close this as [`graphql_input_fields`](https://www.wpgraphql.com/filters/graphql_input_fields/) works currently and more targeted filtering is covered by #965

**Comment by alaa-alshamy** [comment]
Actually `register_graphql_fields()` should be enough to register a new fields to an existing input, for example:

```
register_graphql_fields(
  'RegisterUserInput',
  [
    'company' => [
      'type' => 'String',
      'description' => __('A string containing the user\'s company.', 'wp-graphql'),
    ]
  ]
);
```

I tested it and it's working, so is there something I have missed or what ?
