### ISSUE TITLE
"orderby" does not work as expected.

### ISSUE THREAD

**Issue by manzoorwanijk** [wp-graphql/wp-graphql#966]
`orderby` argument does not work as expected when more than one pair is passed. Only the last pair is taken into consideration.

Possibly a bug [here](https://github.com/wp-graphql/wp-graphql/blob/771ea045d6c082a3a20ead7acdccffd393d1c1f1/src/Data/Connection/PostObjectConnectionResolver.php#L251,L253).

Shouldn't it be
```PHP
) ) {
    $query_args['orderby'][] = esc_sql( $orderby_input['field'] );
                       /* ^^ push field into the array */
} elseif ( ! empty( $orderby_input['field'] ) ) {
    $query_args['orderby'][ esc_sql( $orderby_input['field'] ) ] = esc_sql( $orderby_input['order'] );
                       /* ^ ---------use-field-as-key--------- ^ */
}
```
which results in
```PHP
$query_args['orderby'] = [
	'post__in',
	'title' => 'ASC',
];
```
for the input
```JS
{
  "where": {
    "orderby": [
      {
        "field": "IN",
        "order": "DESC"
      },
      {
        "field": "TITLE",
        "order": "ASC"
      }
    ]
  }
}
```
instead of
```PHP
) ) {
	$query_args['orderby'] = esc_sql( $orderby_input['field'] );
} elseif ( ! empty( $orderby_input['field'] ) ) {
	$query_args['orderby'] = [
		esc_sql( $orderby_input['field'] ) => esc_sql( $orderby_input['order'] ),
	];
}
```
which results in
```PHP
$query_args['orderby'] = [
	'title' => 'ASC',
];
```
for the same input?

**Comment by jasonbahl** [comment]
@manzoorwanijk If I make the suggested change, it leads to a SQL error. 

I believe the reason it is the way it is now might have something to do with: https://core.trac.wordpress.org/ticket/38034

🤔

**Comment by manzoorwanijk** [comment]
@jasonbahl It's not about `post__in` at all. You can see that the code ignores multiple orderby params. I can give you a practical example of the difference in results using `WP_Query` and WP GraphQL with same set of arguments.

**Comment by manzoorwanijk** [comment]
Here is how you can reproduce the issue.

1. Create two pages/posts with no parent (in my case ID = `235` and `237`)
2. Create 3 children of both the above pages.
3. Use the below query in WP GraphiQL with the given query variables.
```gql
query GET_PAGES($where: RootQueryToPageConnectionWhereArgs!) {
  pages(where: $where) {
    nodes {
      parent {
        ... on Page {
          pageId
        }
      }
      title
    }
  }
}
```

Query Variables
```json
{
  "where": {
    "parent": "fake",
    "parentIn": [
      235,
      237
    ],
    "orderby": [
      {
        "field": "PARENT",
        "order": "ASC"
      },
      {
        "field": "TITLE",
        "order": "DESC"
      }
    ]
  }
}
```
**Expected behavior**
The posts with lesser parent ID should be at the top.
**Actual behavior**
The posts are not in order.

![image](https://user-images.githubusercontent.com/18226415/68074859-484f0180-fdc6-11e9-8494-99d5000faeab.png)

Now use the below code to the correct order:
```php
$args = array(
	'post_type'       => 'page',
	'fields'          => 'id=>parent',
	'post_parent__in' => array( 235, 237 ),
	'orderby'         => array(
		'parent' => 'ASC',
		'title'  => 'DESC',
	),
);
	
$query = new WP_Query( $args );

print_r( $query->posts );
```
You will see this result:
![image](https://user-images.githubusercontent.com/18226415/68074877-88ae7f80-fdc6-11e9-8be2-83cd9450a543.png)


**Conclusion**: You can see that WP GraphQL only cares about the last orderby pair i.e. `title`.

P.S. While reproducing the bug, I came across another bug that `parentIn` and `parentNotIn` do not work because WP GraphQL sets `post_parent` to `0` which is given preference by `WP_Query` over `post_parent__in` and `post_parent__not_in`. You can see that I had to pass `parent: "fake"` to avoid that preference. I will create a new issue for that.

**Comment by justlevine** [comment]
Seems to be working fine in v1.9.1
![image](https://user-images.githubusercontent.com/29322304/188700398-1a9608f6-d8cb-4464-9dc7-417b66f6d027.png)
