### ISSUE TITLE
Query slug or path for menus?

### ISSUE THREAD

**Issue by santinfoa** [wp-graphql/wp-graphql#967]
Is it possible to query the 'slug' values for menus like with `gatsby-source-wordpress`? 
This is the one I use with the former plugin:

```graphql
  allWordpressPage {
    edges {
      node {
        slug
        title
      }
    }
  }
```

this is the one I manage to replicate with `source-graphql` and `wp-graphql`:
```graphql
  wpGraphQl {
    menu(id: "TWVudToy") {
      menuItems {
        edges {
          node {
            label
            url
          }
        }
      }
    }
  }
```

The problem is that the `url` value points to the source url (the wordpress one).
In order to navigate the gatsby website its useful to get the slug or the path.

**Comment by mohamadyaserakbari** [comment]
use this code for your query , and get ID then you can get it by menuItem query 
`query MyQuery {
  menuItems {
    nodes {
      title
      menuItemId
      label
      id
    }
  }
`
`  menuItem(id: "") {
    id
  }`

**Comment by santinfoa** [comment]
@mohamadyaserakbari 
Unfortunately this doesn't work, seems that there is an empty object. 
 
![image](https://user-images.githubusercontent.com/49034773/66831577-4973d800-ef58-11e9-8c03-dde995deeeb1.png)

**Comment by jasonbahl** [comment]
@santinfoa for the `menuItems` query, you need to pass a location of a menu you want to query. 

For example, if you had a menu location called "Primary" and you had a menu assigned to that location, then you could query like so: 

```
{
  menuItems(where:{location:PRIMARY}) {
    nodes {
      id
      title
      label
    }
  }
}
```

And in Gatsby with the `wpGraphQl` prefix it would be: 

```
{ 
  wpGraphQl {
    menuItems(where:{location:PRIMARY}) {
      nodes {
        id
        title
        label
      }
    }
}
```

**Comment by santinfoa** [comment]
@jasonbahl Hi, thanks for the response. 
I manage to get some results, but the problem persist, since the "url" from the query is still the complete url of the wordpress site, so the headless wordpress (I mean `www.myheadlesswp.com/menu-voice`)

Is it possible that the menu voices must be custom link entry? I'm used to create wordpress menus using the dynamic content that WP already gives me: usually I choose among pages and construct my menu, but if I instead create a menu with custom voices maybe I could insert only the path on the menu. Right? Like this: 

![image](https://user-images.githubusercontent.com/49034773/67009949-04cd7580-f0ed-11e9-9e27-d675c91f78d2.png)

Is it possible that this method with graphql assumes that once need to make it's menus in this way?

**Comment by santinfoa** [comment]
Hi again @jasonbahl  !

I took a look at how you managed to do this with the [blog-example demo](https://github.com/progital/gatsby-wpgraphql-blog-example/blob/master/src/components/SiteMenu/index.js) and I came with a solution.

Basically I got the id of the menu, so I'm using the same query of the first message (I just add the "id" under node): 

```graphql
{
  wpGraphQl {
    menu(id: "TWVudToy") {
      menuItems {
        edges {
          node {
            id
            label
            url
          }
        }
      }
    }
  }
}
```

Then once I map the nodes I just create two variables (`wpurl` and `onlyPath`) in order to use replace on the full Url and get only the path:

```jsx
<Sidebar>
	<div className="wrapper-listing">
		<ul className="list">

		{ wpGraphQl.menu.menuItems.edges.map(({ node }) => {

		const wpurl = `https://admin.borgosangiuliano.com`
		const onlyPath = node.url.replace(wpurl, ``)

		return (
			<li key={node.id}>
				<Link to={`/${onlyPath}/`}>
					<h4>{node.label}</h4>
				</Link>
			</li>
		)})}

		</ul>
	</div>
</Sidebar >
```

This works well without the need to change neither the menu on the worpress or the query.
