### ISSUE TITLE
issues with having two posts

### ISSUE THREAD

**Issue by mohamadyaserakbari** [wp-graphql/wp-graphql#968]
hi guys , i want to have two posts in the same query but it gave me error , could you help me plz ???

**Comment by jasonbahl** [comment]
@mohamadyaserakbari can you elaborate more on what you've tried and what the error is? Screenshots perhaps or code snippets would be helpful.

**Comment by mohamadyaserakbari** [comment]
i need two different posts in one query , when i write this it gives me error .
`query MyQuery {
  posts(first:10) {
    nodes {
      date
    }
  }
    posts(where:"sample") {
    nodes {
      categories {
        edges {
          node {
            id
          }
        }
      }
    }
  }
}
`

**Comment by jasonbahl** [comment]
@mohamadyaserakbari you can accomplish this by using an alias. 

```
query MyQuery { 
  posts(first:10) { 
    nodes { 
      date 
    } 
  } 
  exampleAlias: posts(where:"sample") { 
    nodes { 
      categories { 
         edges { 
            node { 
              id 
            } 
          } 
        } 
      } 
   } 
}
```

This will now return your data as `{ "data": { "posts" ..., "exampleAlias": ... } }`

For more info on Aliases, see: https://graphql.org/learn/queries/#aliases
