### ISSUE TITLE
GraphiQL schema not working in with Gatsby & Apollo

### ISSUE THREAD

**Issue by D19cannon** [wp-graphql/wp-graphql#969]
Hey guys! 
I've working with WP + Gatsby for a while and I am currently building Apollo on top of that and I need wp-graphql in order to use the Apollo queries. However, I ran in an interesting issue.

GraphiQL only show me endpoints of the rest end and wp-graphql is completely ignored. For example I can find the **allWordpressPost**, while I am actually looking for the the **post** field with it's list.

`
query AllWordpressTranslatedCorrelations {
 allWordpressPost {
    edges {
      node {
        slug
        id
        title
        lang
        path
        translations {
          en
          fi
        }
      }
    }
  }
}
`

Maybe a conflict there with the build in Gatsby configurations. But it would be nice if I can explore both schemas or at least see some schema structure.

**Comment by jasonbahl** [comment]
@D19cannon It sounds like you are using `gatsby-source-wordpress` which is a wrapper around the WordPress REST API. To use WPGraphQL, I suggest checking out [gatsby-source-graphql](https://www.gatsbyjs.org/packages/gatsby-source-graphql/)

**Comment by D19cannon** [comment]
@jasonbahl thanks for the quick response! 

You are right I am using gatsby-source-wordpress. I had a look into the link and I tried to add the wp-graphql plugin. However, the plugin is installed on the WP side with composer, while gatsby-config.js only accepts installed node_modules. This is also giving me the same result when I am trying to add an option in there and direct it to the path __dirname/../../etc. Also, if there are any options it should be giving according to the plugin documentation 

--> https://www.gatsbyjs.org/docs/gatsby-config/#plugins

> Some plugins may need only to be listed by name, while others may take options (see the docs for individual plugins).

**Comment by jasonbahl** [comment]
@D19cannon so, you need to install and activate WPGraphQL (this plugin) on your WordPress site as it is a WordPress plugin that makes your WordPress site a GraphQL server, then install `gatsby-source-graphql` in Gatsby as that's a Gatsby plugin

**Comment by D19cannon** [comment]
@jasonbahl Hi, that's exactly what I did. But I can't see the schema from WPGraphQL, which makes it next to impossible to create any queries.

**Comment by jasonbahl** [comment]
Based on your last comment, it looks like you tried to install `wp-graphql` as a plugin in Gatsby. 

Look at `gatsby-source-graphql` (https://www.gatsbyjs.org/packages/gatsby-source-graphql/) and read how to configure that to work with your WordPress GraphQL endpoint

**Comment by D19cannon** [comment]
It still is not working for me. I followed the configurations and no results. 
`````
module.exports = {
  siteMetadata: {
    title: 'project',
    siteUrl: 'http://project.test',
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-sass',
    'gatsby-plugin-favicon',
    {
      resolve: 'gatsby-source-wordpress',
      options: {
        // The base url to your WP site.
        // Dev wp.dev.saamo.donbran.co
        baseUrl: 'project.test',
        // WP.com sites set to true, WP.org set to false
        hostingWPCOM: false,
        // The protocol. This can be http or https.
        // Dev https
        // Local http
        protocol: 'http',
        // Use 'Advanced Custom Fields' Wordpress plugin
        useACF: true,
        auth: {},
        // Set to true to debug endpoints on 'gatsby build'
        verboseOutput: true,
      },
    },
    {
      resolve: "gatsby-source-wordpress",
      options: {
        typeName: "WPGraphQL",
        fieldName: "wpgraphql ",
        // Url to query from
        url: "http://project.test/graphql",
        // Additional options to pass to node-fetch
      },
    },
    {
      resolve: "gatsby-source-wordpress",
      options: {
        typeName: "WPGraphQL ",
        fieldName: "wp-graphql",
        // Url to query from
        url: "http://donbranco.test/graphql",
      },
    },
    'gatsby-plugin-sharp',
    'gatsby-transformer-sharp',
    'gatsby-plugin-netlify', // make sure to keep it last in the array
  ],
}
`````

All I can see is:
<img width="253" alt="Screenshot 2019-10-11 at 19 08 31" src="https://user-images.githubusercontent.com/14916043/66666971-9014ba00-ec5a-11e9-8792-422d483665c8.png">

**Comment by jasonbahl** [comment]
@D19cannon it looks like you're trying to configure `gatsby-source-wordpress` and _not_ `gatsby-source-graphql`

**Comment by D19cannon** [comment]
Tried gatsby-source-graphql and that crashed the entire build.

**Comment by jasonbahl** [comment]
Here's an example repo you can check out: https://github.com/wp-graphql/gatsby-wpgraphql-blog-example/blob/master/gatsby-config.js#L57-L66

**Comment by D19cannon** [comment]
@jasonbahl The example did the trick! Not sure what happened, because I am confident that I did the configurations correctly. 

Thanks for you help! :)
