### ISSUE TITLE
Figure out what to do with clover.xml file

### ISSUE THREAD

**Issue by CodeProKid** [wp-graphql/wp-graphql#97]
Should probably figure out what to do with this `clover.xml` file. Definitely seems like it's not supposed to be in the repo, it's showing ton's of file changes every time we run tests.

**Comment by jasonbahl** [comment]
got this .gitignored now

**Comment by jasonbahl** [comment]
Gonna wait and see if things are working right with Travis CI, so I re-opened this until confirmed that things are working

**Comment by jasonbahl** [comment]
Confirmed that Coveralls is still logging on merges, even after the logs have been removed from the repo:
https://coveralls.io/builds/10320538
