### ISSUE TITLE
Unable to add fields to whereArgs on connections in v0.4.0

### ISSUE THREAD

**Issue by TylerBarnes** [wp-graphql/wp-graphql#985]
I've registered a post type:

```php
$labels = array(
            "name" => __("Action Monitor", "WP_Gatsby"),
            "singular_name" => __("Action Monitor", "WP_Gatsby"),
        );

        $args = array(
            "label" => __("Action Monitor", "WP_Gatsby"),
            "labels" => $labels,
            "description" => "Used to keep a log of actions in WordPress for cache invalidation in gatsby-source-wpgraphql.",
            "supports" => array( "title" ),
            "show_in_graphql" => true,
            "graphql_single_name" => "ActionMonitorAction",
            "graphql_plural_name" => "ActionMonitorActions",
        );

        register_post_type("action_monitor", $args);
```

I'm then attempting to add a field to the where args:
```php
add_action(
    'graphql_register_types',
    function () {
        register_graphql_field(
            'RootQueryToActionMonitorActionConnectionWhereArgs',
            'testTest', 
            [
                'type' => 'String',
                'description' => 'just testing here'
            ] 
        );
    }
);
```

This works on `master` but when I switch to `release/0.4.0`, the field is no longer registered.

**Comment by jasonbahl** [comment]
@TylerBarnes thanks for opening this issue! I was able to confirm that this indeed is a regression and needs to be fixed. 

It looks like some filters that once executed on the WPInputObject are no longer executing. 

Adding the filters back works. 

I'll open a PR and write some tests to ensure we don't introduce this regression again.

**Comment by jasonbahl** [comment]
@TylerBarnes Here's the PR, and it includes a test, similar to the issue you opened, where a Post Type is registered, then a field is registered to the connection input, and then we use an Introspection query to ensure the field was properly added to the Schema.

**Comment by TylerBarnes** [comment]
#987 fixes this issue for me!
