### ISSUE TITLE
WPInterfaces aren't fully compatible with `register_graphql_field()` and `register_graphql_connection()`

### ISSUE THREAD

**Issue by kidunot89** [wp-graphql/wp-graphql#991]
The have been a few issues related to Interfaces and they all point back to incorrect registration the schema. For example
1. Install and activate **WPGraphQL**, **WPGraphiQL**, **WooGraphQL**, and **WPGraphQL ACF**, along with their corresponding plugins.
2. Import the sample product data included in the **WooCommerce** plugin.
3. Create a coupon. Its properties aren't important.
4 Create an order. Again it's properties aren't important.
5. Create a custom field group *(e.g. fieldsTest)* with a test field *(e.g. testText)* with a default value and set rules to target the `Product`, and `Coupon` post-types.
6. Now navigate to **WPGraphiQL** and run the following query.
```
{
  coupons {
    edges {
      cursor
      node {
        id
        fieldsTest {
          fieldGroupName
          textTest
        }
      }
    }
  }
  products {
    edges {
      cursor
      node {
        id
      	fieldsTest {
          fieldGroupName
          textTest
        }
      }
    }
  }
}
```
And you should get a result like this
![query results](https://i.imgur.com/phE13Pr.png?1)

The coupons resolve the correctly, however the products don't even show the field. This is because `Product` is an Interface type and WPGraphQL ACF registers the field on the Interface but not it's child object types. And fields that registered to the Interface but not the child object type don't exist to that child object type. If you tried changing
```
 products {
    edges {
      cursor
      node {
        id
      	fieldsTest {
          fieldGroupName
          textTest
        }
      }
    }
  }
```
to
```
 products {
    edges {
      cursor
      node {
        id
        ... on SimpleProduct {
      	  fieldsTest {
            fieldGroupName
            textTest
          }
        }
      }
    }
  }
```
You would get this error.
```
{
  "errors": [
    {
      "message": "Cannot query field \"fieldsTest\" on type \"SimpleProduct\".",
      "category": "graphql",
      "locations": [
        {
          "line": 20,
          "column": 11
        }
      ]
    }
  ]
}
```

I personally feel this should be address at the `register_graphql_field()` level. And it should register the field on both the Interface and it's child object types.

The next part is `register_graphql_connection()`. Just as above connections aren't registered to the child object types, and manually registering the connection for the child object type creates a mix-match type issue. The return types will be a different for both Interface and the child object type resulting in a number of fragmenting errors with client-side libraries like Apollo.

*The following output came from `codegen` from a user the Slack.*
![codegen results](https://i.imgur.com/bUWDfjB.png)

Just like with the first issue, I think this should be handled at the `register_graphql_connection()` level.

This issue is also linked with this one [here](https://github.com/wp-graphql/wp-graphql-acf/issues/56) in the **WPGraphQL ACF** repo.

**Comment by jasonbahl** [comment]
closed by #1005 and #1025
