### ISSUE TITLE
Update Resolvers for all ID inputs to behave consistently

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#998]
See issue #997 

### Mutations
- [x] Comment mutations ( #2328 )
- [x] MediaItem mutations ( #2331 )
- [x] PostObject mutations ( #2338 )
- [x] TermObject mutations ( #2336 )
- [x] User mutations ( #2337 )
### Connections
- [x] Comment connections ( #2522 )
- [x] MenuItem connections ( #2523 )
- [x] PostObject connections (#2525 )
- [x] TermObject connections ( #2524 )

**Comment by justlevine** [comment]
## To do
### Mutations
- [ ] Comment mutations ( #2328 )
- [ ] MediaItem mutations ( #2331 )
- [ ] PostObject mutations
- [ ] TermObject mutations
- [ ] User mutations
### Connections
- [ ] Comment connections
- [ ] MenuItem connections
- [ ] PostObject connections
- [ ] TermObject connections

**Comment by justlevine** [comment]
@jasonbahl mutation prs are ready for review and merge.

[As mentioned](https://github.com/wp-graphql/wp-graphql/pull/2328#issuecomment-1089395266), connections are more complicated - I'll begin playing around with different ideas soon.

**Comment by justlevine** [comment]
PRS for connection where args are up and ready for merge. Once that happens, we can close this issue _and_ I believe #1095
