### ISSUE TITLE
TODO: pay for security audit and address any security issues that are raised

### ISSUE THREAD

**Issue by TylerBarnes** [wp-graphql/wp-graphql#999]
One was done previously but we need another one pre-v1.0

**Comment by TylerBarnes** [comment]
Jason says "This may be something we want to talk to Automattic about"

**Comment by jasonbahl** [comment]
I think we should hire a 3rd party to do some penetration testing and access control checks. Pen Test Partners was commissioned by Credit Karma to do a security audit before the v0.3.0 release, and those issues have been addressed, but it would be good to do another thorough 3rd party audit before v1.0 release.

Might even be worth hiring someone like @danielbachhuber (who worked on getting the REST API into WordPress core) to consult and ensure we are following proper core WordPress access control.

**Comment by CodeProKid** [comment]
I'd love to see a 3rd party audit as well.

I also think prioritizing #685 would be good as well. I added a comment about adding tests in there.

**Comment by TylerBarnes** [comment]
@CodeProKid I just added it to the V1 project now. On contributor day a group of us started going through all the issues and prioritizing them. I think @jasonbahl is looking through more now. We're planning on a call to go over some more tomorrow as well if you want to join!

**Comment by jasonbahl** [comment]
Security audit has been completed. Closing this
